### ISSUE TITLE
Decide how to deal with incorrectly encoded short byte arrays

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#10156]
The encoding of short byte arrays has an area of "undefinedness": If the last byte is even, it means that the array is encoded in-place. The problem is that the encoding only has space for 31 bytes while the last byte can encode a length of up to 127.

This situation can of course only be reached through explicit sstore operations in inline-assembly.

I think we have two options:
a) treat the length value as "the truth" and just create additional zeros when copyng from it
b) read the length field as 31 in such a case

If we go for option b, then we have to check all length reading functions to get them synchronized.

**Comment by cameel** [comment]
How about just reverting if the length is >= 32? It will still be possible to get at the raw bits in the inline assembly so if someone is doing such a low-level manipulation, it should not be a big obstacle. And it will only affect newly deployed contracts anyway.

**Comment by chriseth** [comment]
The problem with reverting is that it might be too late to do something about it. Reverting on "bad input" is easy, because you can recover most of the time, but it might be impossible to recover from "bad storage value".

**Comment by cameel** [comment]
You can always recover by zeroing/deleting the whole slot. Or using inline assembly if you really need the data back. And you won't get into this situation in the first place unless you're playing with the raw bytes.

I'm not sure that just making assumptions about the length or zero-padding is necessarily better since it can lead to misinterpreting the data. Someone might find a way to exploit it in an underhanded way like in case of the short address attack.

**Comment by leonardoalt** [comment]
I agree with @cameel and tend to prefer reverting

**Comment by chriseth** [comment]
A similar situation we could consider is the case of a short byte array encoded in the "out-of-place" way: If we have a byte array of length 2 whose length field (the last byte) is `5`.

**Comment by cameel** [comment]
Summary of the stuff I mentioned on the call:
- We already do revert for invalid enum values.
    - If we ever implement [Generic value range types](https://github.com/ethereum/solidity/issues/2918), we'll have a similar problem with invalid values too (I think we should revert in that case too).
- One could argue that `enums` and `bytes` should be handled differently because there's no sensible interpretation for an invalid enum value, but:
    - There actually was a proposal to remove the check for invalid enum values: #9986.
    - For `bytes` capping the length at 31 if it's greater is not the only sensible interpretation. We could also assume that the top 2 bits of the length byte are garbage and discard them. I could see a situation where someone discovers that these bits are unused and uses them as a hardcore optimization to avoid using a full slot for some extra boolean flag. In that case 31 would probably not be the correct length.
- Misinterpreting the data might be worse than a revert. Let's say someone used this hacky optimization I mentioned above to store extra flags. Now you could run into a situation where the content is `"1"` and the length byte is `0xc2` (1 byte * 2 for length + the two "unused" bits set). If we assume that the length is 31, the value will turn into `"10000000000000000000000000000000"` on copy.

**Comment by chriseth** [comment]
Having mulled over it, I now also think that reverting is the right choice.

**Comment by chriseth** [comment]
Fixed in #10239
