### ISSUE TITLE
I withdrew my dsp and nothing was deposited

### ISSUE THREAD

**Issue by xxxrampage1xxx1** [ethereum/solidity#10168]
my 7k dsp is missing  how do i get it back?

**Comment by cameel** [comment]
This isn't the right place to report problems with specific dApps unless you believe the problem is directly caused by a bug in the Solidity compiler. If that's the case please provide some information on how to reproduce the bug and then reopen this issue.

Just a general hint: if you're having problems with an Ethereum transaction please make sure you used the correct address and that you're not making the withdrawal on the testnet and expecting to receive tokens on the mainnet (or vice versa). Also, make sure that you're using the dApp correctly. Another thing to account for is that if you set a low gas price for the transaction, it might take some time before it's included in a block. In none of these seems to be the cause it might be a bug in the contract and then it would be best to contact the authors.
