### ISSUE TITLE
Change source location to cover the entire function prototype

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10210]
From #9607: Change source location to cover the entire function prototype, especially when displayed as a candidate for overload resolution failure.

Example of unwanted behaviour:
```
Note: Candidate:
   --> src/Game.sol:156:2:
    |
156 |         function checkPattern(int _x, int _y, CrossState[] memory _pattern,
    |  ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by chriseth** [comment]
The source location covers the entire function, but the error reported only shows the first line.

**Comment by axic** [comment]
I said "function prototype [..] when displayed as a candidate for overload resolution failure" and I think that would be a good change. No point displaying the entire function of course :)

**Comment by cameel** [comment]
Some extra context for someone who will be implementing this.

The problem here is that error messages for overloads list potential candidates and for each one point at the whole function (starting from the `function` keyword to the ending `}`) rather than just the function prototype (from `function` to the end of the parameter list). See an example of this in https://github.com/ethereum/solidity/issues/9607#issue-677611250. This means that even if the prototype is short and fits on a single line, we'll see the `(Relevant source part starts here and spans across multiple lines)` bit making it unnecessarily longer.

The cause is that we use [`ASTNode::location()`](https://github.com/ethereum/solidity/blob/v0.8.18/libsolidity/ast/AST.h#L112) to get the location and for functions it simply points at the whole function. My suggested solution would be to introduce something like `prototypeLocation()` to [CallableDeclaration](https://github.com/ethereum/solidity/blob/v0.8.18/libsolidity/ast/AST.h#L828) and use that instead.

I think it should be possible to implement `CallableDeclaration::prototypeLocation()` just by combining existing locations. I.e. by taking the start from `location()` and the end from the location of the parameter list.

The code that generates this particular error is here:
https://github.com/ethereum/solidity/blob/ddbef8f65092cd09422366881d0fc1dad5d4b64e/libsolidity/analysis/TypeChecker.cpp#L3597-L3615

But note that we have a few similar messages for overloading and the issue covers all of them.

**Comment by axic** [comment]
Probably this would still be useful.

**Comment by ekpyron** [comment]
> Probably this would still be useful.

Honestly, this is the kind of cosmetics, I'd assign a priority so low, that I'd just let the stale bot do its thing on them. We won't spend resources on this any time soon - the way things are doesn't do that much harm - and it's apparently not a good first issue, as demonstrated by the PR we had, which siphoned a lot of resources and led nowhere in the end...

Once we're in a better place with the core language, we can again start dealing with cosmetics like this - but we may just have changed parsing enough in the process that this issue will have vanished by that time anyways, so I see little benefit in artificially keeping it alive now.

For the time being, cosmetics is not our priority and we try to reduce open issues to "we are likely to actually do this within the next few months" instead of "in principle this may probably still be useful".
