### ISSUE TITLE
Add editorconfig-checker to the CI

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10238]
See https://editorconfig-checker.github.io/

i.e.g what is the point having the `.editorconfig` if we don't enforce it. This tool helps to do that.

**Comment by axic** [comment]
@cameel @christianparpart since you have modified the configuration, what do you think?

**Comment by cameel** [comment]
I'm all for enforcing it for newly created files but I'm not sure it's a good idea for existing ones. Currently a lot of files don't stick to these rules unfortunately. It would require reindenting a lot of code and make `git blame` less useful.

Anyway, even without enforcing it I think that `.editorconfig` is useful because many editors recognize it (there's even a vim plugin: https://github.com/editorconfig/editorconfig-vim).

**Comment by axic** [comment]
>I'm not sure it's a good idea for existing ones. Currently a lot of files don't stick to these rules unfortunately. It would require reindenting a lot of code and make git blame less useful.

In general I disagree with this statement, as that would mean that projects can never fix their code style. And `git blame` works even after reformatting, for affected lines just need to do blame on the commit prior.

While it is unfortunate not enforcing rules earlier, I think it is a bad direction not enforcing it ever.

**Comment by chriseth** [comment]
I don't think we need to enforce it. It is a recommendation.

**Comment by axic** [comment]
Why do we have coding styles, guides, and recommendations, when we do not make use of it? Sounds rather pointless to me.
