### ISSUE TITLE
Replace ASTString by vectorRef (or std::span) to the source code

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10288]
From [pivotaltracker](https://www.pivotaltracker.com/story/show/82260032):
> Replace ASTString by vectorRef to the source code

We could actually consider making `ASTString` a `span` to the source, but I don't see the memory savings benefit being worth the complexity.

If we agree on that, I suggest to get rid of the extra typedef and just use `std::string`.

**Comment by axic** [comment]
Furthermore what is the story with `ASTPointer` and this comment (the below is from `libsolidity/ast/ASTForward.h`, also in [pivotaltracker](https://www.pivotaltracker.com/story/show/82180346)):
```
// Used as pointers to AST nodes, to be replaced by more clever pointers, e.g. pointers which do
// not do reference counting but point to a special memory area that is completely released
// explicitly.
template <class T>
using ASTPointer = std::shared_ptr<T>;

using ASTString = std::string;
```

**Comment by axic** [comment]
Perhaps this is a right spot for @ekpyron to give opinion on ranges-v3 :)

**Comment by ekpyron** [comment]
Well, we shouldn't just replace by ``std::string`` because that'll be allocation hell. If we want to point to the sources, then here in fact an ``std::string_view`` would be best.

The comment makes sense, though, and would go towards using a repository a bit like the ``YulStringRepository``, but with less emphasis on optimizing comparisons, but mostly for lifetime management... ``shared_ptr`` works, but it's rather ugly and evil for this, explicit lifetime is always better and should be possible.

If all of them really always only point to some source range, ``string_view`` would be really nice, but we'd need to check.

But actually nothing here needs ``range-v3`` ;-).
