### ISSUE TITLE
Type deduction of  multi dimensional uint Arrays defined in storage

### ISSUE THREAD

**Issue by johhonn** [ethereum/solidity#10301]
## Description

Error:"TypeError: Unable to deduce common type for array elements."
When defining multidimensional arrays in storage a difference in the max values of a given element triggers a type deduction error. If all elements of one sub array are less than 8  bits and one or more elments are above 8 bits in another sub array an error is thrown even though both elements are of type uint256[].

## Environment

Remix IDE, Solidity 0.7.4 +commit, compiler default

## Steps to Reproduce

```solidity
contract TEST {  
    
   uint256[5][] TEST=[[100,150,100,0,60],[257,50,80,0,3]];
    constructor() public {       
    }
}
```

**Comment by cameel** [comment]
Yeah, looks like a bug to me (or at least an undocumented omission) because the docs say that [there must be a common type for all elements are convertible to](https://docs.soliditylang.org/en/v0.7.4/types.html#array-literals) and this is clearly the case here. `[100,150,100,0,60]` (of type `uint8[5]`) is implicitly convertible to `uint16[5]` (the type of `[257,50,80,0,3]`). I think the compiler should be able to deduce that.

I checked earlier versions and this behavior goes back as far as 0.4.24, maybe even earlier.

Also, this is not just for storage. Memory arrays behave that way too.

**Comment by chriseth** [comment]
I think this is even an FAQ: You have to specify a "proper" type for at least one element of an inline array of literal numbers. The reason is that there is no common type between two different literal numbers - none of them can be converted to the other. Furthermore, I think it is correct to not assign allow such arrays without an explicit type.

**Comment by chriseth** [comment]
I think the sentence `In the example below, the type of [1, 2, 3] is uint8[3] memory. ` is the documentation is wrong and should be adjusted.

**Comment by cameel** [comment]
> The reason is that there is no common type between two different literal numbers - none of them can be converted to the other. 

If that's the case, why does the code below work? None of these causes a compilation error. As long as the literal is in the right range, it appears to be deduced to be `uint16`:
``` solidity
contract C {
    uint256[5][] a = [[uint16(100), 150, 100, 0, 60], [257, 50, 80, 0, 3]];
    uint256[5][] b = [[uint16(100), 150, 100, 0, 60], [uint16(257), 50, 80, 0, 3]];
    uint256[5][] c = [[1000, 150, 100, 0, 60], [257, 50, 80, 0, 3]];
}
```

**Comment by chriseth** [comment]
Ah, ok, so the problem seems to be that the inner arrays have different types

**Comment by axic** [comment]
Is this considered a bug? Just a missing feature (which we may or may not want)? Or a lack of good error reporting?
