### ISSUE TITLE
What is the purpose of 'ewasm' function of solc？

### ISSUE THREAD

**Issue by q871795224** [ethereum/solidity#10370]
I currently use solc's --ewasm to process smart contracts, but I found some confusing situations during processing.
Why did I change the content of the contract, but the wast file did not change significantly？
the old contract:
```
contract Caller {
    function callAddress(address a) public {
        a.call("");
    }
}
```
the new contract:
```
contract Caller {
    function callAddress(address a) public {
        a.call("");
        a.call("");
    }
    function A(address a) public{
        a.call("");
    }
}
```
The difference between the them:
![image](https://user-images.githubusercontent.com/33190881/99906699-78d84500-2d13-11eb-9042-366f93b8027b.png)
![image](https://user-images.githubusercontent.com/33190881/99906716-93122300-2d13-11eb-8363-4a23c59e8a2e.png)

the wasm files has no difference.
Therefore, I would like to know the purpose of 'ewasm' function of solc？

**Comment by cameel** [comment]
There is a difference but it might not be very apparent in the text form because it's only the runtime code that differs. Note the first difference highlighted in the diff:

```wasm
    ;; custom section for sub-module
    ;; The Keccak-256 hash of the text representation of "Caller_13_deployed": d1813742dfca576723bf11a62e05908eadf19b646e0af2b817f263a605f60b72
    ;; (@custom "Caller_13_deployed" "0061736d0100000001bc032860000060000...")
```
```wasm
    ;; custom section for sub-module
    ;; The Keccak-256 hash of the text representation of "Caller_31_deployed": 1c42535be8454173a7b5cff50f509f979c0d852e8821a1423f46d31bba391ac7
    ;; (@custom "Caller_31_deployed" "0061736d0100000001bc032860000060000...")
```

This is the runtime code. It starts the same way for both but there are differences. And different hashes of the text representation  indicate that it was different too.

All the text except that part is just the construction code and since your contract does not have a constructor, immutables or much of anything to do at deployment time, it's just boilerplate with generic utility functions. The optimizer will throw away almost all of it.

It's the runtime part that contains the actual logic of your contract and it's what you see in the commented-out `@custom` section. In EVM assembly this would be a separate subassembly and in Yul it would be a subobject. You can see this for yourself by compiling with `--asm` or `--ir` option instead of `-ewasm`.

In wasm there's no concept of submodules so we're just storing the bytecode in a custom section. Unfortunately this only works in binary form. In text form custom sections have not been standardized yet. It's actually only in solc 0.7.5 that we're even printing this hash and bytecode (#10219). In earlier versions compiler would omit it completely from the text form.

**Comment by q871795224** [comment]
Thanks for your help. 
I get the code from commented-out @custom section and change it to wasm. I find that the last 125 funcs of the two wasm are the same. Does this correspond to those generic utility functions?

**Comment by cameel** [comment]
I'd have to check to be sure but they should generally be the same. Those are the predefined functions you can find in https://github.com/ethereum/solidity/tree/develop/libyul/backends/wasm/polyfill
