### ISSUE TITLE
[CI] Parallelise external compilation jobs

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#10398]
Currently, we have a single job per external compilation test. This scales poorly because every time we add a new external project to the testing repo, a new CI job needs to be needlessly introduced. This issue tracks support for parallelising this setup within a single CI job.

**Comment by cameel** [comment]
We had a [discussion about it on gitter today](https://gitter.im/ethereum/solidity-dev?at=5fca3c6b89c5424e7959c35c). I think that packing multiple external test jobs into a single one is not a good idea because they already run in parallel, they're not uniform and they could potentially affect each other.

### Reasons for not packing these jobs into a single container
1. They can affect each other. Most of them try to start a global `ganache-cli` process and either fail when one is already running (Gnosis) or reuse it even if it already has some blockchain state (Colony). There seems to be a general assumption on their part that they have the whole machine to themselves.
2. There's not much opportunity for saving time by doing common bootstrap for these scripts. The heaviest part of the initialization is the npm module installation. But each project uses different packages and even the ones in common are all in different versions. We might be able to patch them to use the same versions but this often does not work without changes in the code. I think we're better off just treating them as black boxes. The patching we do currently just to use the newer compiler is already pretty brittle.
3. They're not uniform. The execution time varies wildly and will change over time (e.g. Gnosis v2 has only a single test but surely will get more). I think that running them in a single container will either delay feedback about failures until the longest one finishes or will cancel the longer ones when shorter ones fail, leaving us with incomplete feedback. The times are currently:
    - Gnosis v2: 2 min
    - ENS: 3 min
    - Gnosis v1: 10 min
    - OpenZeppelin: 12 min
    - Colony: 44 min
4. These jobs already run in parallel because they do not depend on each other. They don't even depend on the `t_ems_compile_ext_xxx` variants because they just repeat the compilation themselves (compilation takes very little time compared to the rest of the setup so no point in reusing it). So this will decrease test running time only if we have so many jobs that they are waiting in queue.
    - While debugging #10429 [I modified the workflow to have 10 instances of each test job](https://app.circleci.com/pipelines/github/ethereum/solidity/11175/workflows/3fc38283-1878-442f-a69b-30948d635f1e). This means 40 external test jobs trying to run at the same time (I skipped Colony). It finished in 53 minutes compared to 50 minutes a [normal workflow](https://app.circleci.com/pipelines/github/ethereum/solidity/11175/workflows/3fc38283-1878-442f-a69b-30948d635f1e) takes. The difference is smaller than the variation we're normally seeing in running times. I think this shows that we are far from being constrained by the queue.
5. We do have a lot of CI jobs and if there is actually some unnecessary redundancy then reducing that number might be worthwhile. On the other hand packing multiple jobs into one would just hide them. Personally I think it's better to be able to see them as separate entries in PRs.

### What we could do instead
1. We should parallelize what these scripts to internally. They all repeat the test up to 3 times sequentially, each one with different optimizer settings. We'd still have to keep them isolated somehow though. Ironically, it might be easiest to get both parallel execution and isolation by converting each run into a separate job :)
2. We could cache the npm packages (separately for each job).
3. We could merge each compilation+test job pair into one job. That actually **is** redundant and we could reduce their number by half that way. The downside is that we then wouldn't be able to run one on PRs and the other nightly. Both would always have to run at the same time.
4. We could reduce duplication in CircleCI config by using YAML's `<<` and defining a common base configuration. Right now each test is defined separately. I was going to try to deduplicate that after #10429 anyway.

**Comment by cameel** [comment]
@ekpyron pointed out that the parallel jobs do run in separate containers ([Running Tests in Parallel](https://circleci.com/docs/2.0/parallelism-faster-jobs/#other-ways-to-split-tests)). That solves the isolation issue.

I also see that it's possible to split the load more evenly (based on the the timing of previous runs) if we use `store_test_results`.

I tried to find info on what happens when one of the parallel jobs fail. I only found this old feature request: [Run jobs in parallel, fail the long job if a short one has failed](https://ideas.circleci.com/cloud-feature-requests/p/run-jobs-in-parallel-fail-the-long-job-if-a-short-one-has-failed). So apparently the other jobs still run to completion and the point about not seeing the feedback until the longest job finishes still stands.

**Comment by ekpyron** [comment]
So I just checked what happens in https://github.com/ethereum/solidity/pull/10504.
The state of the test run in the PR in fact stays yellow/pending, even if one of the parallel jobs already failed while the others are still running. Clicking on the test run already clearly shows it as failing on the CircleCI status page (and in general, still running the other jobs to the end makes sense IMO), but apparently the early failure is not immediately reported as status to github (which would be nice).

That being said, I'm not entirely sure that that's too big of an issue for the external tests, actually :-).

**Comment by cameel** [comment]
Here's my PR that does deduplication: #10518. CircleCI allows parameterized jobs and I think we could even use them to replace some of the current templates. It has considerably reduced boilerplace required for external scripts.

I was going to try to parallelize the 3 sequential test runs too but it's a bit late today. I'll go back to that tomorrow.
