### ISSUE TITLE
Confusing error message for missing `;` in pragma

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#10411]
Compiling the following contract with `solc-0.7.5`:
```
pragma solidity ^0.7.5
pragma experimental ABIEncoderV2;

contract A {
}
```
yields the error message:
```
Error: Source file requires different compiler version (current compiler is 0.7.5+commit.eb77ed08.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> src/hmm.sol:1:1:
  |
1 | pragma solidity ^0.7.5
  | ^ (Relevant source part starts here and spans across multiple lines).
```
But the error is actually a missing semicolon in the first pragma line

**Comment by axic** [comment]
The version pragma is handled in a special way, in the parser, in order to abort early.

Currently it seems to be parsing all tokens up to the semicolon, e.g. "pragma solidity ^0.7.5 pragma experimental ABIEncoderV2;".

~~What would be easy parser-wise is terminating if there is no semicolon after the version (technically: if more than two tokens follow the pragma keyword), as a special case.~~ Not as simple as that, the special characters (caret, etc.) are tokens themselves.

**Comment by cameel** [comment]
I see in the [grammar for a source unit](https://docs.soliditylang.org/en/latest/grammar.html#a4.Solidity.sourceUnit) that the version value consists of separate tokens which means that they could be whitespace-separated and/or span multiple lines. So this is currently perfectly valid:
```solidity
pragma solidity^


0. 7.
4

;
```

**Comment by cameel** [comment]
Maybe vertical pragmas will become a new trend for fashionable smart contracts one day :P
```solidity
pragma
solidity
^
0
.
7
.
4
;
```

**Comment by axic** [comment]
Hah, we need an Obfuscated Solidity Competition 😅  (cc @franzihei)
