### ISSUE TITLE
Allow reading immutable variables during construction

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#10463]
Is there a fundamental reason why immutable variables can't be read during construction?

I would've liked to make some of the existing state variables in OpenZeppelin Contracts immutable, since they're only used in that way, but it will have to wait until our next major release (likely to happen after Solidity 0.8) because it would be a breaking change. (I would prefer if this was not a breaking change at all.) People could be reading them indirectly through internal or public functions during construction, and those function calls would become an error.

**Comment by cameel** [comment]
I think that allowing reads during construction is technically possible, but it comes with some gotchas and added complexity. AFAIK we simply didn't think that dealing with these issues was worth the hassle:
1. Immutables can be initialized at any point in the constructor. If you call a function before the immutable is initialized it will see a different value than if you called it after the initialization. I think this might easily catch people off guard. The immutables should be immutable after all. We could of course detect reads before initialization but that requires doing extra analysis that's simply not needed if you assume they're never read during construction.
2. You'd have to generate different construction and runtime code for these functions. A read in the runtime code is dead simple - you just read the value embedded at a predefined location in the bytecode. That's not possible in construction code because it has to compute the value first and it cannot modify itself to insert that value. Note that the value does not have to be a compile-time constant - it can depend on things like balance or results of external calls so the compiler cannot pre-compute it and insert it into the construction code. You need an actual variable to hold it and alternative code to access it.

Being able to reuse existing functions during construction does sound to me like a good reason for having that feature so maybe this should be reconsidered.

**Comment by frangio** [comment]
Thanks for explaining!

Generating different code makes a lot of sense, though it would be at odds with #10396.

**Comment by frangio** [comment]
I came up with the following scheme which I think solves point 2 above in a simple way. Let me know if I'm mistaken! :smile: 

Immutable variables should be statically assigned a position in memory for the duration of the constructor. Instead of emitting an empty placeholder where the immutable variable is loaded onto the stack, Solidity should emit the few instructions necessary to load the value from its assigned memory position. These instructions are then overwritten with the direct load to the stack.

It would still be necessary to disallow reading from them before they are initialized.

**Comment by chriseth** [comment]
I think generating different code is not such a big deal, but I think we should enforce that immutables are not read from before they are initialized. This could be a bit difficult when they are read in other functions, but it is not impossible.

**Comment by nventuro** [comment]
`immutable` is a fantastic feature, in my opinion the best one developed in recent time by far. The number of design patterns it enables with minimal gas cost is surprisingly high.

...but not being able to read an `immutable` variable during construction is a huge limitation. This might not be obvious at a first glance, since you could always store whatever is assigned to `immutable` locally, and use that instead:

```solidity
contract Foo {
    uint256 immutable bar;

    constructor(uint256 baz) {
        uint256 qux = foo(baz);
        bar = qux;

        useBar(qux); // can't pass bar, pass qux instead
    }
}
```

The issue arises when using inheritance: if the immutable variable is held by a base contract, it will not be accessible to its children during construction.

```solidity
contract Foo {
    uint256 immutable bar;

    constructor(uint256 baz) {
        bar = foo(baz);
    }
}

contract Bar is Foo {
    constructor(uint256 baz) Foo(baz) {
        useBar(bar); // forbidden
    }
}
```

If gas is not an issue, it could be argued that `foo` could also be called in `Bar`'s constructor in this example. But if this operation has side-effects (e.g. if it is the reuslt of an external call, such as registering with some other contract and getting an ID back), it is not possible to have this code duplicated in both parent and child.

**Comment by chriseth** [comment]
Since the order of construction is a bit difficult, this can lead to problems especially with multiple inheritance. We could try to do some static analysis coupled with runtime errors, but it's a bit tricky to get this working in all cases, I think.

**Comment by frangio** [comment]
@chriseth What problems would it cause exactly? Reading an immutable variable that hasn't been assigned yet should return its default zero value, like storage variables do.

**Comment by frangio** [comment]
I should note, we're extremely interested in this feature for OpenZeppelin Contracts. We want to be able to use immutable variables to improve gas efficiency but we don't want to impose strange usage limitations on the internal functions that happen to read those immutable variables. We might be okay with releasing an initial version with this limitation if you plan to remove the limitation relatively soon.

**Comment by chriseth** [comment]
I actually don't think we should allow the default value to be read - this contradicts the `immutable` property. Read before write should be detected at compile-time as much as possible and at runtime through a Panic if it is too complicated to detect.

**Comment by frangio** [comment]
Are there plans to implement this soon? We're using immutable variables now and are hoping to be able to remove limitations for calling internal functions that access these immutable variables.

**Comment by frangio** [comment]
Sorry to insist. This keeps showing up as a problem for our users in the places where we've decided to use immutable variables to improve gas efficiency.

I would love to do anything possible to help move this forward.

**Comment by chriseth** [comment]
This might not be too difficult anymore when we combine the immutable validator with the extended call graph generator we recently implemented.

**Comment by chriseth** [comment]
@GNSPS do you have an opinion on
 - a) allowing immutables to be read during construction time and
 - b) allowing them to be read before they are assigned (resulting in the default / zero value)?

**Comment by chriseth** [comment]
Since the assignment has to happen at the top level inside the constructor, I think it is not too difficult to do a reachability analysis for all code that is called in the constructor until the assignment of the immutable (do not forget the right-hand-side of that assignment itself). Any read access to the immutable inside there is an error. We also have to check state variable initialization and base constructors (also check the different orders of initialization in "via IR" and "legacy", at best it should work for both).

**Comment by axic** [comment]
I think this would be a useful feature.  Currently many projects need to create local variables even if it is reused within the constructor (not talking about helper functions).  Solving it for helper functions would be an additional improvement.
