### ISSUE TITLE
ICE in `StructType::isDynamicallyEncoded()` when a function has a `memory` struct argument with an internal type inside

### ISSUE THREAD

**Issue by agroce** [ethereum/solidity#10516]
## Description

This contract:
```solidity
contract C {
    struct S {
    	function () e;
    }
    function f(S[2] memory s1) public {
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.cpp(2321): Throw in function virtual bool solidity::frontend::StructType::isDynamicallyEncoded() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

Looks like all other deaths in isDynamicallyEncoded were fixed, so this is a new variant (the structure looks different to me at a glance).

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

**Comment by cameel** [comment]
The crash happens because `TypeChecker::visit(FunctionDefinition)` does not stop when it detects `TypeError 4103: Internal type is not allowed for public or external functions.`. It continues to visit function parameters and in case of an array, it ends up calling `isDynamicallySized()` on the base type - which is not allowed when the type is an internal one.

If we change the type to a struct (rather than an array of structs) it does not crash. Apparently `isDynamicallySized()` does not get called in that case. It also does not crash if I change the example so that there's a single struct that contains an array of function pointers.

So the question is: does `isDynamicallySized()` really need to use an external type? I see that `interfaceType()` is used by it only in case of structs. For example we just use the base type directly in case of arrays. I looked at what `interfaceType()` does an it looks like it either returns an unchanged type, creates a copy of the type as a `memory` type or returns an error (if there's no external type). In my opinion none of these things can affect whether the type is dynamically sized or not.

So my first attempt at fixing this would be to simply use the base type directly. I'm going to submit a PR that does this.

If this is not a good solution then another one would be to just make it a fatal error and stop the analysis before we analyze the parameters.

**Comment by chriseth** [comment]
I think a fatal error is the better solution.

**Comment by cameel** [comment]
ok
