### ISSUE TITLE
formal verification: add tests for WhyML extraction

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1052]
This issue keeps track of adding tests for WhyML extraction, maybe as a CI test, maybe as a Makefile target like `make test-why3`.  This issue is about the first step, so the tests can just observe the returned status of `solc --formal x.sol` commands.

**Comment by chriseth** [comment]
The tests should be flexible enough so that they do not break if we change some part in the translation. Perhaps it would make most sense if we have tests that search for specific substrings to be present or not present in the translation and the another set of tests where we just run the verifier and see that some condition can be verifier and some cannot.

**Comment by pirapira** [comment]
Maybe it's a good idea to `why3 execute` the WhyML files.

**Comment by pirapira** [comment]
But the specifications in the translation should be also checked.

**Comment by chriseth** [comment]
Why3 will be removed, so closing this.
