### ISSUE TITLE
Improve error reporting of scanner issues in the Solidity and Yul parsers

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10627]
Consider improving error reporting of scanner errors (including SemVerParser). Right now both Solidity and Yul parsers may just report "invalid token".

_Originally posted by @cameel in https://github.com/ethereum/solidity/pull/10625#discussion_r544221923_

**Comment by vinayman** [comment]
Hi @axic and @cameel  - I saw this is a good first candidate issue and started doing some work specifically with the SemVer error reporting. You can see a draft PR here:

https://github.com/ethereum/solidity/pull/12487

I just wanted to check before continuing work on this whether you are happy with the implementation and some questions:
- I'm not sure what error codes we should throw or where I can find typical error codes - this is currently failing in the CI since for development purposes I've just made the error code 1465.
- I added the BOOST_THROW_EXCEPTION in the catch since some invalid parsed expressions did not throw - is this okay or would this break some of the language compilation?

After your guidance I would be up for moving onto the other scanner errors to try improve the reporting.

Please let me know and thank you :)
