### ISSUE TITLE
[SMTChecker] Underflow/overflow should only warn if always happens

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#10717]
Now that underflow/overflow always reverts (in checked arithmetic) it feels kinda weird to generally warn for underflow/overflow:
```
    function f(uint a, uint b) pure public returns (uint) {
        return a + b;
    }
```
This reports
```

Warning: CHC: Overflow (resulting value larger than 2**256 - 1) happens here.
Counterexample:

a = 1
b = 115792089237316195423570985008687907853269984665640564039457584007913129639935
 = 0

Transaction trace:
C.constructor()
C.f(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935)
 --> o.sol:5:10:
  |
5 | 		return a + b;
```
which is kinda weird because the overflow cases will never reach the end of the function.

I think the interesting case is rather "always overflows", because the contract is then locked. This can be more generalized to "function does not terminate".

I guess my suggestion here is to remove underflow/overflow checks and add function termination checks.
@axic @blishko @chriseth @ekpyron ideas?

**Comment by ekpyron** [comment]
Hm... are we all-in on the idea that automatic overflow checks basically function as implicit ``require``? I'd say it still makes sense to report overflows, even if they revert by default, forcing you to think about reasonable limits that you specifically, manually ``require`` yourself...
In general I'd still treat failing auto-generated as failed assertions... but not sure if I'm alone in that view ;-).

**Comment by leonardoalt** [comment]
Well, no one is going to write
```
  function f(uint a, uint b) pure public returns (uint) {
        require(a + b >= a);
        return a + b;
    }
```
in 0.8, the effect is the same

**Comment by ekpyron** [comment]
What you should do is
```
  function f(uint a, uint b) pure public returns (uint) {
        require(a < 1000, "unreasonable amount for a");
        require(b < 1000, "unreasonable amount for b");
        return a + b;
    }
```
I'd say that actual overflows are never really reasonable bounds for anything.

**Comment by leonardoalt** [comment]
Right, but no one is going to do that. I think most people are just going to do math and use the compiler generated reverts to get rid of that behavior. In that case, people are gonna get tens or hundreds of useless overflow messages

**Comment by ekpyron** [comment]
I'm not sure if we should go for assuming people do things badly anyways and thereby build things towards people doing things badly :-). But yeah... since I expect to be outvoted on that anyways ;-):

"always overflows" is indeed an interesting property to check for, especially in CHC where you should be able to tell, if a contract can reach a state in which some function won't work anymore because of it... but: by the same argument as for the "may sometimes overflow" case: won't this be expected as well and result in similarly "useless" warnings?

I.e.:
```
contract C {
  uint8 numMembers;
  function addMember() { numMembers++; ... }
}
```
Under the assumption that people will just use implicit overflow checks as "require", in this case here, in which I indeed can reach a case of 255 members, in which ``addMember`` always overflows, don't I have to assume that that's also just as well by design and nothing to warn about then? Why would I expect people do add ``require(numMembers <= 255);`` here, but not in other cases?

So I'd say one could argue: if we really expect people to use implicit overflow checks as ``require``s and thus want to treat them as ``require``s, it's never actually justified to warn about over-/underflows anymore...

**Comment by ekpyron** [comment]
Or do you mean "always overflows" as in "locally always overflows" only, as in ``uint8 a = 200; uint8 b = 200; a + b;``? About that of course it definitely always makes sense to warn, even though I wouldn't expect it to happen very often...

**Comment by ekpyron** [comment]
So local function termination checks (i.e. "function never terminates regardless of contract state") probably generally make sense. One could consider to make warning about overflows optional... but not sure if that'd open the way to SMT settings hell...

**Comment by blishko** [comment]
Personally, I also think that overflow warnings would be useful, but I guess it depends on what philosophy are you trying to put forward.
It is also possible to wait and see what the reaction is from the users :)
Another possibility would be to turn this into an option which the users could turn on or off.

Regarding the "always overflows", it sounds like a useful thing to detect.
But exactly as @ekpyron writes, it depends what you mean. The "locally always overflows" does not sound like something you write by accident (but maybe I am wrong).
The other case, where there is some transaction sequence which leads to a state where calling a function will always revert because of overflow, I am not sure if this is possible to detect with the current framework (but again, I might be wrong).

**Comment by leonardoalt** [comment]
I see those points, what I'm thinking in practice is:
Imagine a current contract that uses a bunch of SafeMath. 70% of the current unique deployed contracts do. When upgrading to 0.8, the devs simply remove the SafeMath calls and use the appropriate arithmetic operator, as in replacing `x.add(y)` by `x + y`.
In this case, every single arithmetic operation will warn "overflow", where the dev probably reacts with "well, yes, that's what I used SafeMath for, and now rely on the compiler".
I can imagine this just bloats the ouptut.

**Comment by leonardoalt** [comment]
I mean an operation causing transactions to always revert

**Comment by blishko** [comment]
> I mean an operation causing transactions to always revert

Always reverts regardless of the state of the contract or depending on the state of the contract?

**Comment by chriseth** [comment]
Overflows create a panic error just as division by zero or invalid array access does, so I think any potential panic should be reported.

**Comment by frangio** [comment]
> I'm not sure if we should go for assuming people do things badly anyways and thereby build things towards people doing things badly 

This is the first time I hear that relying on the compiler overflow checks would be considered doing things badly. Is that really the case?

**Comment by leonardoalt** [comment]
> Overflows create a panic error just as division by zero or invalid array access does, so I think any potential panic should be reported.

It's not the same. That is a `panic` that *will* be reached *all the time*. I myself when writing 0.8 contracts do not guard the arithmetic operations with previous requires and just rely on the compiler to filter it out for me.

**Comment by ekpyron** [comment]
> > I'm not sure if we should go for assuming people do things badly anyways and thereby build things towards people doing things badly
> 
> This is the first time I hear that relying on the compiler overflow checks would be considered doing things badly. Is that really the case?

Well, I don't think there is complete consensus about that. But I personally would say: most definitely yes, just as relying on SafeMath was doing things badly ;-). Both should always only have been considered as last safety net just in case you messed up and some case slipped through your fingers that *isn't* caught by explicit ``require``'s. I'd still maintain that doing https://github.com/ethereum/solidity/issues/10717#issuecomment-754679759 and having the compiler optimize away the autogenerated check in ``a+b`` would be ideal. And I don't think anyone would actually argue against that being ideal.
However in practice the problem is both that this appears to be hardly adhered to by anyone and that the optimizer still has a hard time removing redundant checks like that so far.

**Comment by leonardoalt** [comment]
Tbh I think it's naive to think that this will happen. The automatic replacement for SafeMath will be to just rely on the compiler, also because of gas.

**Comment by leonardoalt** [comment]
We moved on to not reporting underflow/overflow by default, so closing this.
