### ISSUE TITLE
Replace `compileViaYul` with `codegen` setting

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#10779]
Proposal is to have `v1` and `v2` (or `v1only` and `v2only`) as options. If this setting is lacking, the test case should pass on both codegens.

The current `compileViaYul` is a confusing with its false/true/also settings.

**Comment by ekpyron** [comment]
Maybe we should also explicitly have ``both`` and just require it to be specified.
We need to assume that not everything that ultimately should be ``both`` can be set to ``both`` yet, though, so we should have a dedicated comment in the file indicating that the current setting is only due to bugs/missing implementation and mentioning what we'll ultimately expect once it's done.

We could actually also not make this a comment, but a real setting like ``codegenIntended: both``, ``codegenWorking: v1`` - that would make it easier to have ``isoltest`` correctly try if ``working`` can be upgraded to ``intended`` each time...

Or something like that at least ;-).

**Comment by axic** [comment]
Tow more names, `legacy` and `ir`, were also suggested. We do have files suffixed with `_v1` and `_v2`, hence my initial suggestion.

**Comment by chriseth** [comment]
I like `legacy` / `ir`

**Comment by cameel** [comment]
+1 for `legacy` / `ir`.

`_v1` / `_v2` sounds like ABI Encoder to me :)

> We need to assume that not everything that ultimately should be both can be set to both yet

I think that @chriseth said today that there are no more tests that do not pass with the new codegen are not explicitly using `compileViaYul: false`. So this is no longer true, right?

**Comment by cameel** [comment]
> Maybe we should also explicitly have `both`

How about just listing both names instead, i.e. `codeGenerationPaths: legacy, ir`?
Then we won't have to rename it if we add more backends. Even now we could do `codeGenerationPaths: legacy, ir, ewasm` and drop the `compileToEwasm` option.

**Comment by chriseth** [comment]
List of paths sounds good! Maybe it could be a bit shorter, though: `codegen:`? Also, should "all of them" be the default or should 'legacy, ir' be the default (skipping ewasm)?

**Comment by cameel** [comment]
`codegen` sounds natural to me but I didn't suggest it because I was thinking it might be ambiguous. Now that I think of it, shouldn't really be a problem. So +1 for `codegen`.

I think that having it all on by default would be least confusing. It has the downside that when we introduce a new codegen, almost all test cases need to be modified to disable it. Having the codegen disabled initially does not require that but I think that after eventually making it the default we're going to want to remove the setting in cases where it matches the defaults so we'll be modifying all test cases anyway.
