### ISSUE TITLE
Adding a `forceOverride` keyword

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#10829]
## Abstract

Since the introduction of the `virtual` and `override` keywords in solidity 0.6, libraries of smart contracts, which are designed to be inherited from, have to explicitly chose which contracts they allow their users to override. Functions which are not marked as virtual, cannot be overloaded. This proposal introduces a new keyword `forceOverride` that allows a child contract to overload a function that was not marked virtual.

## Motivation

Libraries of smart contract such as OpenZeppelin's [contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) hope to provide well designed tools that can improve the smart contract developer's experience. The contract include both virtual and non virtual functions. The virtual functions are often used as hooks add functionality while the non virtual ones take care of the core mechanism (which are security critical).

[Still some advance users do find very specific use-cases where overloading a core function is required.](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154)

This put OpenZeppelin's (and other) developers in an uncomfortable situation where marking some function virtual is dangerous (since it makes it very easy for less experienced users to unknowingly break critical component of the contract) while not making them virtual prevent advanced users from pushing innovative designs.

The consequence of this is, more often than not, that advanced user fork the library's code, modify it to make function virtual, and package it with their code. This break dependency management, and thus prevent automatic updates. Consequently I would call it bad practice.

On the other hand, I do understand the logic of not making everything virtual.

I believe least-bad solution would be to have a `forceOverride` keyword, that advanced developers can use to force an override. This will keep expressivity of the father smart contracts (trying to override a non virtual function will continue to trigger an error), and at the same time allow advanced users to force an override without breaking the dependency management system.

## Specification

Add a `forceOverride` keyword, that would allow a function to overload parents implementations if at least one of them is not marked as virtual. This keyword MUST NOT be used with the override `keyword`.

Today:
```
contract A {
  function trigger1() public virtual { /* so something */ }
  function trigger2() public virtual { /* so something */ }
}
contract B {
  function trigger1() public virtual { /* so something */ }
  function trigger2() public         { /* so something */ }
}
contract C is A, B {
  function trigger1() public override(A,B) { /* so something else */ } // OK
  function trigger2() public override(A,B) { /* so something else */ } // ERROR
}
```

With the proposed changes:
```
contract A {
  function trigger1() public virtual { /* so something */ }
  function trigger2() public virtual { /* so something */ }
}
contract B {
  function trigger1() public virtual { /* so something */ }
  function trigger2() public         { /* so something */ }
}
contract C is A, B {
  function trigger1() public override(A,B)      { /* so something else */ } // OK
  function trigger2() public override(A,B)      { /* so something else */ } // ERROR
  function trigger2() public forceOverride(A,B) { /* so something else */ } // OK
}
```

## Discussion

If a `forceOverride` function is marked virtual, should it be possible to overload using a simple `override`?

## Backwards Compatibility

AFAIK, this will "only" break contract that include function, variable, modifiers or custom types names `forceOverride` since this would become a reserved word. Otherwise, the current behavior is unaffected.

**Comment by axic** [comment]
What would stop people from **only** using `forceOverride` and just ditching `override`?

**Comment by Amxx** [comment]
Good practice. 
Maybe forceOverride could trigger a warning (not an error), and linters rules would reject that.

**Comment by axic** [comment]
> Maybe forceOverride could trigger a warning (not an error)

If the compiler triggers a warning, people come with proposals that a) it should not trigger a warning; b) there should be a way to silence the warning 😏

**Comment by Amxx** [comment]
There should be a way to silent the warning. The idea is to let people do what they are doing anyway ... and do it in the "least dangerous way" ... while making sure they know its still dangerous.

**Comment by frangio** [comment]
The thing with warnings is that they are useful for learning best practices, but in some cases you really want to do the thing that is warned against anyway.

This is related to the "force override" concept. While I don't think a `forceOverride` keyword would be a good idea, it reflects the reality that developers have different levels of risk tolerance. This is something we struggle with at OpenZeppelin because we want to build secure contracts but at the same time provide flexibility for the advanced users who know what they're doing.

Maybe Solidity should accomodate that there are different levels of risk tolerance. Maybe the compiler should be configurable and have modes to allow things that would be risky but are "sound". Maybe there can be a risk-mode that ignores `virtual`, assuming everything is virtual and can be overriden.

**Comment by leonardoalt** [comment]
> There should be a way to silent the warning. The idea is to let people do what they are doing anyway ... and do it in the "least dangerous way" ... while making sure they know its still dangerous.

What are people doing currently that has the same behavior as the proposed `forceOverride`?

**Comment by Amxx** [comment]
> > There should be a way to silent the warning. The idea is to let people do what they are doing anyway ... and do it in the "least dangerous way" ... while making sure they know its still dangerous.
> 
> What are people doing currently that has the same behavior as the proposed `forceOverride`?

Copying OpenZeppelin's codebase in there repo (rather then having a package manager do it), modifying it, and re-publishing it with their code. This causes different project to have different version of what should be the same contract. These dependencies are unlikely to ever be updated, and building contract that interact with multiple projects can cause name clashs.

Adding this feature (or having a compiler flag that disables all virtual/override checks) won't fix everything ... but I believe it might help.

**Comment by axic** [comment]
> Maybe Solidity should accomodate that there are different levels of risk tolerance. Maybe the compiler should be configurable and have modes to allow things that would be risky but are "sound". Maybe there can be a risk-mode that ignores virtual, assuming everything is virtual and can be overriden.

@frangio on that note there was a not well discussed proposal (#3916) many years ago.

Both such a feature, a general warning switch off feature, or a specific warning switch off feature requires quite a bit of thought put into it, before it can be accepted. I think a in-source annotation (#2691) is likely the best option out of these.

**Comment by axic** [comment]
Since https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2473 was merged, does that mean this issue is not that relevant anymore?

**Comment by frangio** [comment]
I saw this issue more about starting a discussion than a concrete feature proposal. As I expressed above, I don't think `forceOverride` would be a good idea.

That said, with OpenZeppelin/openzeppelin-contracts#2473 we're more or less happy with the result. But given this new direction it's worth noting that OpenZeppelin Contracts are basically not obtaining any value out of `virtual`/`override`, because at this point almost everything is virtual and people can override what they want.

Note that we now _opt out_ of overrides by using the fully qualified function call syntax `Foo.bar()` instead of plain `bar()` in a few sensitive places. We need to do this to prevent people from shooting themselves (and us) in the foot with an override that would change the semantics in a nonsensical way. I think this is a really interesting development because it kind of serves the same purpose that non-virtual was meant for, namely fixing a certain behavior of an internal function that we don't want users to change. But at the same time it allows people to override the external-facing function in a derived contract if they want.

I think what the Solidity team needs to pay attention to is that this change was driven by huge demand from our users. "Make everything virtual" was basically one of our top requests.
