### ISSUE TITLE
Wrong version was published as solc@0.8.1 on npm?

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#10868]
There is something wrong with the `solc@0.8.1` package on npm. It reports itself as being version `0.8.0`:

```
$ npm install solc@0.8.1
$ node -pe 'require("solc").version()'
0.8.0+commit.c7dfd78e.Emscripten.clang
```

Besides, it doesn't seem able to compile files with pragma `0.8.1`.

**Comment by cameel** [comment]
Indeed, looks like the 0.8.1 was published to `npm` with an older `soljson.js` binary. The problem is only in the npm package because `solc-bin` does contain the [0.8.1 binary](https://github.com/ethereum/solc-bin/blob/gh-pages/bin/soljson-v0.8.1+commit.df193b15.js) and if you clone `solc-js` and do `npm install` manually, it downloads the latest version.

Unfortunately I don't have credentials to update the npm package so someone else will have to do it. @chriseth, @axic, @ekpyron?

**Comment by chriseth** [comment]
It looks like npm does not allow this to be fixed. We currently do not know how this happened, the publish process usually updates the binary directly before publishing.

Note that only the npm package is affected, not the binary in solc-bin, so if you use `loadRemoteVersion` and use a framework that allows to switch Solidity versions, you are probably fine.

Sorry that this happened.

**Comment by chriseth** [comment]
Since we cannot really delete/modify the version, we decided to deprecate the 0.8.1 npm package as soon as 0.8.2 comes out.

**Comment by axic** [comment]
> Since we cannot really delete/modify the version, we decided to deprecate the 0.8.1 npm package as soon as 0.8.2 comes out.

@chriseth did we do this yet?

**Comment by chriseth** [comment]
Yes, 0.8.1 is deprecated.

**Comment by axic** [comment]
https://www.npmjs.com/package/solc/v/0.8.1
