### ISSUE TITLE
Mapping data structure

### ISSUE THREAD

**Issue by Debendranath** [ethereum/solidity#10871]
contract MyMapping {

    mapping(uint => uint) public myMap;

    function store(uint key, uint val) public {
       myMap[key]=val;
    }

    function retrieve(uint key) public view returns (uint){
        return myMap[key];
    }
}

In the above code, how many key values I can store in myMap? Can I store all the possible 2^256 entries as key values in the mapping myMap (assuming the size of uint is 256 bit)?

When a variable is declared as storage, is it saved in Ethereum Blockchain? In case, if we alter its value then a transaction is made and go to the blockchain after mining to reflect the updated state. Am I right?

**Comment by chriseth** [comment]
You can store all possible entries in the mapping in theory, but in practice, nobody can afford the gas costs for that.
Yes, storage values that are modified are stored in the Ethereum blockchain.

This issue is not really suited for the issue tracker in this github repository. If you have further questions, please use https://ethereum.stackexchange.com/ or similar sites.
