### ISSUE TITLE
Call stack depth attack and precompiles.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/solidity#1096]
Yesterday it hit me that the precompiles might be vulnerable to the call stack depth attack. Yikes! I went and tried it.

[Here is my test code.](https://gist.github.com/anonymous/6c123d75adb8279b41c33be0d893e458)

The good news is that all that happens is the calling contract gets confused and loops until out of gas. This is probably the desired behavior overall, but would it be better/possible if Solidity explicitly threw?

**Comment by chriseth** [comment]
Precompiles have proper error propagation. Perhaps you confused the "looping" you saw with the iterated error propagation?

**Comment by Smithgift** [comment]
Looking at the end of an "attack" (with the above code) in the debugger, it loops through the following three instructions:

```
ISZERO
PUSH 0002
JUMPI
```

The call stack itself won't unwind. For more details, it'll probably be easier to just try the code.

That said, after testing this again I have discovered that it will break like this if it runs out of the stack, whether it reaches the precompile or no.

**Comment by chriseth** [comment]
@Smithgift you are right that these three opcodes are executed, but it is not really a "loop". Instead, the `JUMPI` causes an invalid jump exception (on purpose) and thus an immediate return to the caller. Since the opcode before the `ISZERO` opcode is the `CALL` one call stack level higher, it seems to loop by continuing with the `ISZERO` opcode. So the snippet you cite above is exactly the code that is responsible for exception propagation.

**Comment by Smithgift** [comment]
Ah. Sounds like there's no bug, then.
