### ISSUE TITLE
Fix confusing links for build documentation.

### ISSUE THREAD

**Issue by nejucomo** [ethereum/solidity#110]
I'm attempting to build `solc` so I first see the [README.md Building section](https://github.com/ethereum/solidity#building) which links to [the cpp-ethereum wiki](https://github.com/ethereum/cpp-ethereum/wiki) which immediately says it "is a dead repository". This in turn links me to [the webthree-umbrella wiki](https://github.com/ethereum/webthree-umbrella/wiki).

I get lost once I get to the webthree-wiki. All I want is `solc` but I don't see any mention of how to build just that. So I just guess the build process will be similar for solidity as for alethzero or ethereum cli, except probably with different dependencies.

Now, however, I click "install guide" since I'm an "advanced user on ubuntu" (except I'm really on debian), but that's a dead link!  Finally, I click lower down for building on ubuntu to get to [the Building on Ubuntu page](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu).

One problem here is that I actually want to build from source, and I'm on debian rather than ubuntu, so relying on PPA packages and updating apt signing keys doesn't work for me.

At this point, I find myself succumbing to despair because the ubuntu instructions suggest I need to install a non-standard (for ubuntu) LLVM, as well as things like ethereum-qt. I shouldn't need qt anything and hopefully not an unusual LLVM just to build `solc` right?  But that's not really a documentation issue, so I'm going to file a different request ticket for that.

**Suggested improvements:**
- remove the intermediate "dead repository" link into the cpp-ethereum wiki and link directly to the webthree-umbrella wiki.
- explain on the webthree-wiki page explicitly how to build `solc` or else put the instructions directly in this repository.
- fix the dead "install guide" link on [the webthree-umbrella wiki home page](https://github.com/ethereum/webthree-umbrella/wiki).
- provide a dependency list in addition to the list of apt/PPA/apt-signing key instructions, so that people who want to install those dependencies another way can install the right dependencies.
- provide documentation that's more specific to solidity itself instead of alethzero or cpp-ethereum.

**Edits:** I added one more suggested improvement about defining the dependencies.

**Comment by bobsummerwill** [comment]
Hey @chriseth!    Just for reference, which of the suggestion actions above did you take?

@nejucomo With regard to comprehension and management of external dependencies, I really feel your pain.    I've poured a lot of time and love into https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X over the past few weeks, and still know that will be unstable over time.   I've been a user of the Ubuntu setup myself.     Yesterday I built on Windows for the first time, and that was pretty nasty too.

More generally, we've currently got a setup which is very tweaky and unstable and platform-specific for package management.    I would love to bring more of the external dependencies into the webthree-umbrella as sub-modules, both so that we can easier lock-down on versioning, and also so that we avoid the nastier parts of this platform-specific configuration setup.
