### ISSUE TITLE
Document recommended workarounds for common warnings

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11012]
Related to #2691 and #2675.

One of the reasons people want to be able to ignore warnings might be that they're not aware of how simple it is to fix some of them. @axic proposed documenting the common ones them along with the recommended workarounds. 

I think that a good example of something like this is the list of [enumerated shellcheck codes](https://gist.github.com/nicerobot/53cee11ee0abbdc997661e65b348f375#file-_shellcheck-md). Each one has a page with examples of good and bad code, rationale, etc. I'm not sure if we want to go that much in depth but if we did, I think this is a good example to follow. Or maybe this would work better in a form of a wiki maintained by the community?

If we prefer something more compact, we could also revive the FAQ section in the docs.

**Comment by cameel** [comment]
One more thing. On the call today it was also said that in simpler cases the recommendation should just be included in the warning message itself. On the other hand these messages are sometimes too long already and #10534 could help with that.

**Comment by frangio** [comment]
I think it's a good idea to include the recommendation with the warning itself.

However, it seems to me that the request to ignore warnings generally relates to either: 1) files that are out of the control of the developer (i.e. library code), or 2) disagreeing with the compiler recommendation (e.g. SPDX comments).

In neither of these cases a does it matter how simple it is to fix the underlying cause of the warning. So this might not be really getting at the core of the issue people are having.

**Comment by chriseth** [comment]
No file is out of the control of the developer. This is all open source. I think the root problem is that people are not confident in using the language if they shy away from making trivial changes to libraries that are suggested by the compiler.

**Comment by frangio** [comment]
In fact, we did receive several pull requests to OpenZeppelin Contracts where people made the necessary changes to remove warnings about constructor visibility. However, the warnings were already fixed, but we were not able to release them generally because they were a breaking change that we wanted to avoid. (We had to release it as a separate version specific to Solidity 0.7 that people were not getting by default.) I insist that the compiler should try to avoid propagating breaking changes downstream to libraries. In the case of this warning I don't see why it was necessary.

**Comment by xlab** [comment]
There is some unfixable stuff in `solc` like #11077 and "waiting" is not really an option for any serious programmer there. So instead of a nice flag to ignore certain (or all) warnings, we just downgrade compilers, waiting on new versions, or using `sed` in the javascript manifests. 🤨

**Comment by chuckb** [comment]
> No file is out of the control of the developer. This is all open source. I think the root problem is that people are not confident in using the language if they shy away from making trivial changes to libraries that are suggested by the compiler.

I disagree with no file being out of control of the developer. Open source-ed-ness is not the issue. Code can validated by third parties at specific revision levels. If you are building a project that will be subject to an audit, an auditor might rely on the findings of already audited code. But if one subsumes said code, then any modification negates said audit, making your audit more time consuming and expensive. So there are entirely valid reasons to need this ability...even more so in the realm of smart contracts where the notion of audit is de rigueur.

Ever owned a farm? Have a truck manufactured after 2010? Do work on your farm and tell me how much you value the do-gooders design of seat belt dingers you cannot silence.

**Comment by chuckb** [comment]
Here is another use case for me knowing better about whether I need the warnings or not:

```
contracts/mock/implementations/DelegatableMock.sol:59:26: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function votePowerAt(uint blockNumber) public view override returns(uint256) {return 0;}
```

I have a mock contract. I use it for testing. I know that the variable is unused, thank you very much, but I want that it way. Could I add code to make the warning go away? Sure. But why should I have to? I'd be fine with a hint placed over the line, or specifiable on the command line, acknowledging that help was provided, and I declined to accept it.

**Comment by chriseth** [comment]
There are two ways to remove code to make the warning go away:
```
 function votePowerAt(uint blockNumber) public view override returns(uint256) {}
```
or
```
 function votePowerAt(uint) public view override returns(uint256) { return 0; }
```

While I can understand your concerns with regards to audits, I fear this brings us on the wrong track: Your analogy with the truck company is a good one. The problem is that we should not write smart contracts in the way that we use trucks as in your example: I would prefer if smart contracts engineers were knowledgeable enough and trucks simple enough such that in case of problem with the truck, the engineer can repair every single aspect of it because she just understands it 100%.

I'm afraid of a situation where someone writes smart contract code without understanding all its dependencies trusting that the auditor will find any flaws that are present.
