### ISSUE TITLE
[Yul] Syntax for "origin" source location

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11086]
Since Yul's goal is to be used as an IR we want to keep the source locations of the *actual source code* in Yul. This is needed to have proper debugging support through the IR pipeline.

I could not find an issue for this, but we discussed it on several design meetings. If I recall correctly, the idea is that we change the `location` field in [Yul AST](https://github.com/ethereum/solidity/blob/develop/libyul/AST.h) to "annotations". This a could then contain Yul source location and "origin" source location. We could extend it with more debugging data to be transmitted later on.

For the syntax this is a [suggestion from 2017](https://gitter.im/ethereum/solidity-dev?at=601170c3428d9727dd38ea14) (ouch! -- well this link is from January, but based on an old commit) which is inspired by NatSpec:
```
/// @origin <sourcename>:<start>,<end>
```

Some name ideas: `@location`, `@origin`, `@generator`.

**Comment by chriseth** [comment]
I would propose to change the Yul AST data structures for that. We replace the `location` field of each of those by a more generic `debugdata` field that can contain various data, like the solidity source location, the yul source location, the variables that start their scope here and so on. The good thing is that all optimizer steps already properly copy this location field and thus would also copy the debugdata field.

The Yul parser would have to be able to read these annotations suggested in the description and properly fill the debugdata field. The ast printer should be able to export them in a similar way.

In the end, the existing debugging data structures can be generated from them.

**Comment by chriseth** [comment]
@axic and me just discussed the following in a meeting:

The AsmParser should be set into a mode where it does not use the source locations from the scanner, but instead uses source locations from doxygen comments. This mode is activated by a special doxygen tag on the first element that is parsed. Furthermore, we do not distinguish (yet) between "yul source location" and "solidity source location".

Syntax:

```
/// @use-src "fileA.sol": 0, "fileB.sol": 2
{
    /// @src <sourceIndex>:<start>,<end>

}
```

The `@use-src` activates the mode where source locations are taken from the `@src` tag instead of from the scanner. The `use-src` tag is followed by a mapping from file name to file number. Collisions in file numbers are an error, but gaps are fine.

The use of `use-src` anywhere else is an error, as is multiple uses. If `@src` is used without `@use-src`, it is NOT an error - the tag is just ignored. Other tags should also be ignored.

The parser should maintain a "current source location" that is then used for all yul ast nodes that follow. The "current source location" is reset to the value before the block whenever a block is left (might be similar for other syntactic constructs).

**Comment by cameel** [comment]
I see that #11558 took care of reading the `@src` annotations and adding the locations to the Yul AST, so the remaining thing to do here is to handle `@use-src`?

**Comment by Marenz** [comment]
I think this can be closed https://github.com/ethereum/solidity/pull/11594
