### ISSUE TITLE
Constructor superclass invocations are mislabled as ModifierInvocation in AST

### ISSUE THREAD

**Issue by mattdf** [ethereum/solidity#11081]
## Description

When a constructor explicitly invokes a superclass constructor, the AST output misrepresents the NodeType as `'ModifierInvocation'` rather than as a `'FunctionCall'` or, I suppose a new NodeType that should be specific to constructor invocations. 

## Environment

- Compiler version: v0.8.2
- Target EVM version (as per compiler settings): default
- Operating system: Linux

## Steps to Reproduce

Compiling the below code with `--ast-compact-json`:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract A {
    constructor(uint256 a) {}
}

contract B is A {
    constructor() A(1) {}
}
```

The NodeType that represents `A(1)` is a `ModifierInvocation`:

```
[
  {
    "arguments": [
      {
        "hexValue": "31",
        "id": 13,
        "isConstant": false,
        "isLValue": false,
        "isPure": true,
        "kind": "number",
        "lValueRequested": false,
        "nodeType": "Literal",
        "src": "142:1:0",
        "typeDescriptions": {
          "typeIdentifier": "t_rational_1_by_1",
          "typeString": "int_const 1"
        },
        "value": "1"
      }
    ],
    "id": 14,
    "modifierName": {
      "id": 12,
      "name": "A",
      "nodeType": "IdentifierPath",
      "referencedDeclaration": 8,
      "src": "140:1:0"
    },
    "nodeType": "ModifierInvocation",
    "src": "140:4:0"
  }
]
```

**Comment by chriseth** [comment]
The type of node is correct. It is not a function call - function calls happen at expression level. Note that writing `SuperClassName(x)` does not even invoke the super class constructor. The order of evaluation of constructors cannot be changed by this, it is fixed through the C3 linearization. What you do when you use this syntactic construct is that you set the base constructor arguments - nothing more nothing less.

Since it is syntactically the same as a modifier invocation, this ast node type is used for both these semantic uses in the AST.

**Comment by mattdf** [comment]
It would be helpful to at least have a `.kind` property in this NodeType that differentiates between an actual modifier and a `SuperClass` constructor "call", the same way `FunctionCall` has differentiations via `.kind`, so one doesn't have to resolve the referenced declaration to figure out that it's not actually a modifier invocation.

**Comment by chriseth** [comment]
Yep, we can do that!
