### ISSUE TITLE
[Docs] The ABI spec doesn't mention how tuples are encoded when computing a function's selector

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/solidity#11184]
Hi,

Just some quick feedback. I'm implementing an ABI encoder/decoder and I'm having a bit of trouble.

The canonical name is in general not very well defined. I'd expect a section explaining precisely what it is and how it is computed for each type. I guess you can grasp it from examples for anything except for tuples. I had to read an ABI encoder to understand what to do.

**Comment by hrkrshnn** [comment]
@cameel mentioned adding more documentation to ABI encoding sometime back. Perhaps there is another issue about it.

**Comment by cameel** [comment]
Thanks for the reminder, I should finally create one :) But I think this one is a separate thing. 

This issue is about a different part of the ABI spec - the one that describes how to compute the selector, not how to encode the parameters.

The part I thought needed rewriting was the dense [Formal Specification of the Encoding](https://docs.soliditylang.org/en/latest/abi-spec.html#formal-specification-of-the-encoding). I think it really needs a diagram because the matter isn't really that complicated, it's just not visualized well.

**Comment by cameel** [comment]
Here's the issue for simplifying the encoding spec #11191.

**Comment by cameel** [comment]
One thing that I just ran into (https://github.com/ethereum/solidity/pull/11050#discussion_r639926610) that should also be mentioned in the docs too: parameters of an external function type are not a part of the signature. So all of these have the identical signature:

```solidity
function foo(function() external) public {}
function foo(function(uint) external) public {}
function foo(function(S memory) external) public {}
```

**Comment by chriseth** [comment]
@alcuadrado are you saying it is not clear which string is hashed when computing the selector of a solidity function that takes a struct as argument?

**Comment by chriseth** [comment]
So as a summary: For the non-obvious Solidity types, we should mention how they map to the ABI types. Note that this is Solidity specific, so it might be outside of the linked page.

**Comment by alcuadrado** [comment]
> @alcuadrado are you saying it is not clear which string is hashed when computing the selector of a solidity function that takes a struct as argument?

Yes, I meant that it's not clear which string to hash. A solidity function that takes a struct is an example, but I meant this as a general ABI question.

> So as a summary: For the non-obvious Solidity types, we should mention how they map to the ABI types. Note that this is Solidity specific, so it might be outside of the linked page.

Yep, agreed. How those map into abi types is Solidity specific and should be kept independent from the abi spec imo.

**Comment by volkyeth** [comment]
Since #11191 was closed, I think adding some examples of signatures for functions with tuple and struct inputs would be a great low-effort improvement to the docs. It's such an important piece of the docs, but still so ambiguous.

wdyt @cameel? Can we reopen this and agree on adding some examples instead of rewriting the formal specification?
