### ISSUE TITLE
[Sol->Yul] ICE due to library function bound to a literal

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#11325]
```
library L{
  function f(uint) external {}
}

contract C {
  using L for *;
  function g() public {
    8.f();
  }
}
```

throws

https://github.com/ethereum/solidity/blob/5c02837485b8bae0a484ec1e1490851fae264417/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L1588-L1599

```
$ solc --experimental-via-ir test.sol
```

**Comment by cameel** [comment]
Oh, so it's possible after all. You broke the system with `using L for *;` :)
When I was implementing this I could not find any way to apply a library to types you cannot name like literals or slices and I thought it's not allowed. So apparently it is. We clearly lack test coverage here so we should add some semantic tests with functions bound to those types.

We might also want to document that this is a way to get a library to apply to literals. For example I expected that `using L for uint` would allow me to do `8.f()` but it does not. Only works for `uint` variables. Since we do not have an explicit rational type, I guess that `*` is the only way to affect literals?

**Comment by axic** [comment]
Side-note: Perhaps with templates we'll need to come up with a notation for literal arguments, and then we could use that?
