### ISSUE TITLE
published binaries should be built in the open via automation

### ISSUE THREAD

**Issue by tmc** [ethereum/solidity#11345]
Today, users of precompiled binaries here have to trust the binaries uploaded to the github releases. It would be safer to have automation (such as Github Actions) build and publish these binaries instead.

**Comment by chriseth** [comment]
We are also wondering what the best way is here. The binaries are actually built by automation, we just upload them manually. The reason is that we do not want to give circelci (or github actions) write access to the complete archive mainly to avoid a compromised build server (or plugin / external dependency - cf. recent coverity (?) exploit) messing with older binaries. Do you have an idea how that problem could be solved?

Also, what is the attack scenario you are concerned about? Is it a compromised developer system or a modified smart contract? The latter is not such a big problem IMO because we have multiple fully independent build systems that can be used to verify compiled contracts: The PPA build is done fully automated on an offline build server we have zero control over, for example.

**Comment by tmc** [comment]
> We are also wondering what the best way is here. The binaries are actually built by automation, we just upload them manually. The reason is that we do not want to give circelci (or github actions) write access to the complete archive mainly to avoid a compromised build server (or plugin / external dependency - cf. recent coverity (?) exploit) messing with older binaries. Do you have an idea how that problem could be solved?

Providing the CI environment github artifact upload permissions should be a safe thing to do if you're not pulling in uncontrolled third party dependencies at build time. If that is the case, I'd encourage an initiative to not pull in untrusted code at build time.

With a little configuration I think you could do things like run less-trusted operations of the source code in automation more safely by not providing the access token with release upload permissions to those build steps (github actions allows you to be pretty granular with the repository secrets).

There are a host of possible ways to add additional assurances regarding the provenance of a built binary.

> 
> Also, what is the attack scenario you are concerned about? Is it a compromised developer system or a modified smart contract? The latter is not such a big problem IMO because we have multiple fully independent build systems that can be used to verify compiled contracts: The PPA build is done fully automated on an offline build server we have zero control over, for example.

The former is the more concerning thing -- presumably, the software on a solidity developer's machine would be easier to compromise than a well-controlled CI supply chain. A compromised solidity developer's machine could be leveraged to steal tokens by inserting malicious code into the released binaries.
