### ISSUE TITLE
Windows build of 0.8.2 seems to lack 0.8.2 features

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#11358]
I reported this in the chat but I want to leave it here because there may be something wrong in the build pipeline or release process that should probably be looked into.

The Windows build for 0.8.2 doesn't seem to support `@custom` NatSpec tags. Later builds (0.8.3, 0.8.4) do not have this problem.

![](https://user-images.githubusercontent.com/481465/117513931-214c2f80-af69-11eb-91d3-7bf4fc73c213.png)

Reproduction: https://github.com/frangio/solidity-0.8.2-windows

**Comment by cameel** [comment]
I just checked the binary and looks like you're right. It does not support custom tags and is also missing other changes like the `.address` fix from #11009. `--version` still reports `Version: 0.8.2+commit.92b52cbf.Windows.msvc` though.

This is really weird because I remember @chriseth asking me to check it before he added it to solc-bin, and specifically to make sure it supports custom tags. I checked the [binary from the v0.8.2 release page](https://github.com/ethereum/solidity/releases/download/v0.8.2/solc-windows.exe) and it was fine. I even rechecked it now and it's still fine - turns out that it's not the same binary that ended up in solc-bin. Looking at solc-bin now, the commit that added the binaries (https://github.com/ethereum/solc-bin/commit/b316019b1e494c0a6257d0cfc1c3db261cfeb697) is weird - it adds release binaries but has the message copied from the nightly that was built at the same time. So something must have gone wrong there. That release was pretty stressful because there were problems with CircleCI and some binaries actually ended up being built wrong. They were caught by the bytecode check in solc-bin and rebuilt but we do not have that check for Windows binaries so this might be why the broken binary managed to slip through.

Anyway, please try the binary from the release page. It seems fine to me so the solution would be simply to use it to replace the one in solc-bin. We will also have to make sure other binaries from that release match solc-bin.

**Comment by chriseth** [comment]
The problem back then was that the github API was just malfunctioning and returned the wrong commit hash or the wrong code. So the push to fully automate the release process is not a solution to these problems.

**Comment by frangio** [comment]
Thanks for looking into this! I don't have the time to test the binary from the release page, but if you think that one is correct I agree the solc-bin repo should be updated with that one.

**Comment by cameel** [comment]
Here's a PR that puts the release page binary into solc-bin: https://github.com/ethereum/solc-bin/pull/92
I also compared all binaries between 0.8.0 and 0.8.4 between solc-bin and the release page and this is the only one that differs.
