### ISSUE TITLE
try/catch block does not catch the exception caused by EXTCODESIZE check on external calls

### ISSUE THREAD

**Issue by aybehrouz** [ethereum/solidity#11373]
## Description
`try/catch` block is unable to catch an exception.

## Environment

- Compiler version: 0.8.3
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix
- Operating system: Win10

## Steps to Reproduce

```solidity
pragma solidity ^0.8.0;


interface HaveF {
    function f() external view returns (uint);
}


contract Test {
    function dontFail(HaveF c) public {
        try c.f() returns (uint v) {
            
        } catch {
            
        }
    }
}
```
When `Test.dontFail(addr)` is called with an `addr` which is not a contract, and does not implement `f()`, the transaction fails:
```
transact to Test.dontFail errored: VM error: revert. revert The transaction has been reverted to the initial state. Note: The called function should be payable if you send value and the value you send should be less than your current balance. Debug the transaction to get more information
```
`dontFail` method should not fail. It seems that the `try/catch` block is unable to catch the thrown exception.

**Comment by cameel** [comment]
This is not a bug. `catch` by design can only catch reverts that happen inside the contract you're calling. If the address does not represent a contract, the `CALL` opcode actually reports success (this is a weird quirk of the EVM). This behavior of the opcode is counter-intuitive so high-level external calls in Solidity have an extra check to determine if the call was to a contract or not. It if was not, your contract reverts. But this revert is performed by your own contract so unfortunately you cannot catch it.

Both the behavior of `catch` and this extra check are documented but I can see how the effect when you combine them might be hard to realize. I think we should add an explicit warning about this gotcha.

**Comment by aybehrouz** [comment]
Thanks a lot for your detailed answer.
The problem is that this can easily introduce security bugs. There are situations that you need to make sure an external call can never make your contract fail or your contract will stop functioning forever. You may think(as I did) that with a try/catch block you can prevent your contract from failing (like what you do in all other conventional programming languages). but that may not work the way you thought.

**Comment by leonardoalt** [comment]
Well, that's the more general problem of making external calls to arbitrary unknown addresses which should be avoided in the first place.

**Comment by chriseth** [comment]
@aybehrouz I see that this might seem like the failure is coming from `c` and thus it is an "attack vector" take make `dontFail` fail forever. One could argue that passing `c` (or storing it in storage) is already the problem. As an analogy, if you have a function
```
function f(uint x) returns (uint) { return x - 1; }
```
then this function can fail if you pass the "wrong" `x` and there is no possibility to use `try/catch` because the failing code is in the current contract. This is the same with calling `c.f()` - the check for `c` being a contract is in the current contract and thus outside of the region covered by `try/catch`.

**Comment by aybehrouz** [comment]
@chriseth Thanks for your answer.
@cameel explained the situation very well and I did understand why this is happening. What I am trying to say is that this behavior is really counterintuitive. because a try/catch block is supposed to cover a *region* of code not a function or an operator. A programmer usually tries to handle errors that come from some region of the code. Maybe you should use a different syntax for try/catch blocks?

And it can introduce security problems. In my code an admin can register ERC20 tokens in our contract. usually the admin should be a good guy but if our admin turns out to be a bad guy he may try to register *bad* contracts. So our contract should be able to handle that situation. If the admin registers an ERC20 contract that fails when its balanceOf() method is called he can make our contract stop functioning forever.

**Comment by chriseth** [comment]
`try/catch` does on purpose not work with regions of code, but only with external function calls. If we use a different term, people will still try to make the connection - "ah, this works just like try/catch in other languages". The edge case of this issue is one of the very small details that can still be considered to be covered by the syntax, and I think we should highlight that in the documentation but not change the syntax. In general, I believe that such denial-of-service attacks should not be mitigated through try/catch but rather though multi-step processes.

The reason is that even if `c.f()` is a valid function and is executed but consumes all gas, it can make the contract stop working. You still have 1/64th of the gas left, but I think it is not good practice to rely on that.

**Comment by aybehrouz** [comment]
> 
> The reason is that even if `c.f()` is a valid function and is executed but consumes all gas, it can make the contract stop working. You still have 1/64th of the gas left, but I think it is not good practice to rely on that.

oh thanks a lot for pointing out that problem. I really can not find a solution for that. Some internal state needs to be updated and it has to be done for all registered tokens.

However in my case, the admin of the system is me and the ERC20 tokens are stable coins like USDT,DAI,.... I was wondering that if some one stole my private keys what would happen for my contract. Also I'm worried that I may register a wrong address by mistake while adding the functionality for un-registering tokens is not an option.

**Comment by frankgscott** [comment]
if someone wants to help me understand any of this I am willing to try and learn and fix this

**Comment by cameel** [comment]
@frankgscott There's really nothing to fix here, except for adding a warning about this particular case in the try/catch docs. I think that any "fix" would be a major redesign and it still wouldn't be complete because of cases like out-of-gas mentioned above.

@aybehrouz Just for completeness, another case try/catch will not catch is badly encoded return data from an external call. This could very well happen if you try to use the wrong interface and the function you're calling returns a different set of types than you expect it to but a malicious contract can also just use inline assembly to return virtually any invalid sequence of bytes. The decoding is obviously performed in your contract so, again, it's your contract that reverts on error.

**Comment by aybehrouz** [comment]
@cameel that's very good to know. thanks a lot for adding that useful information.

**Comment by k06a** [comment]
Sadly we consider this behaviour (revering during `try-catch`) as a new attack vector. Attackers could selfdestruct contract which are used with try-catch and code assumes this try-catch will never revert - but it will revert.

Example of code sensitive to this attack: https://github.com/1inch/erc20-pods/blob/a2dd8997a1c7b3ade48de269ccb081ec8bcc6ea1/contracts/ERC20Pods.sol#L98-L100

**Comment by cameel** [comment]
Here's a new syntax proposal that would address this: https://github.com/ethereum/solidity/issues/13869#issuecomment-1422879881.

We have too many duplicate issues about this so I'm closing this one in favor of #13869.
