### ISSUE TITLE
Change the bug list to be closer to OWASP terminology

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#11511]
See page 8 of https://owasp.org/www-pdf-archive/Riskratingmanagement-170615172835.pdf, and also this nice tool https://www.owasp-risk-rating.com/.

In short: OWASP has *likelyhood* and *impact* as separate measures, and the product of the two is the *risk* value.

Currently in `bugs.json` we have a single metric, `severity` which is a free text field having values of `very low`, `low/medium`, `medium`, `medium/high`, `high`. This metric tries to encompass both likelyhood (of exploitabilty) and the impact of it, i.e. equals to the OWASP risk.

The suggestion is to introduce three new fields (`likelyhood`, `impact`, `risk`), each on a 0-10 scale, where the higher number means *more*. Allowing 0 means that it is possible to say that something has either no impact or no likelyhood.

We could then deprecate `severity` (keep it for old bugs) or make sure that the new `risk` field comes up with the same results, the following brackets are risk values for given severities:
- `low`: 0-1
- `low/medium`: 1-3
- `medium`: 4-5
- `medium/high`: 6-7
- `high`: 8-10

**Comment by axic** [comment]
@holiman since you have implemented a similar JSON for geth, do you have some feedback for us?

**Comment by GNSPS** [comment]
I like this! 😄

**Comment by holiman** [comment]
We use owasp risk rating for many things, but we've found that it doesn't quite fit well with solidity. In e..g geth, it's pretty clear cut what the impact of a bug is (does it crash? does it go out of consensus? does it impact the whole network?) , and also the likelihood (does it require direct network access? Can it only be executed against a node which is doing a sync?)

For solidity, it's much more intricate. Is "likelihood" the likelihood that someone is affected by the bug, or is it the likelihood that someone who suffers from the bug can be exploited? 
Is the severity the potential severity if someone were to have the e.g. faulty generated code in the contract? 

So when we've discussed this in the past, we've instead said to focus on these areas: 

- How hard would it be to detect the bug, if an affected contract has some basic testing in place?
- How likely is it that the presence of this bug would lead to an exploitable code? 
- How likely is it that someone would be hit by this bug (e..g , does it only occur on hand-written assembly, or very elaborate structs, or would a common pattern lead to it?)

We might have had a few more characteristics too, those are the ones that I vaguely remember now. In any case, it's more difficult to judge a bug in "a thing which generates code for other things" than the "thing" itself.

**Comment by holiman** [comment]
Also, if you go with OWASP, I wouldn't use a scale of 0-10, but just the rating : ![risk rating](https://bounty.ethereum.org/owasp_w600.png)

**Comment by banescusebi** [comment]
This is great! Here are some thoughts:

Confusion might occur due to the terms used in the [table on slide 17](https://owasp.org/www-pdf-archive/Riskratingmanagement-170615172835.pdf) (same table as in the previous comment from @holiman) and the terms used for the old severity values. Is the mapping below accurate?:

- `note` -> `low`
- `low` -> `low/medium`
- `medium` -> `medium`
- `high` -> `medium/high`
- `critical` -> `high`

This [tool](https://www.owasp-risk-rating.com/) is nice, but it would need some adjustments for Solidity smart contracts. At least, the following questions and/or their drop-down values should be rephrased/replaced/removed:

1. How much data could be disclosed and how sensitive is it? _<- remove/replace_
2. How much data could be corrupted and how damaged is it? _<- not sure if the damage of data is relevant because there are snapshots and the original values before a hack could be recovered._
3. How much service could be lost and how vital is it? _<- this could be relevant to vulnerabilities that might lead to some functions that throw an out-of-gas error._ 
4. Are the threat agents' actions traceable to an individual? _<- the attacker could always use something like Tornado Cash and then the answer to this questions might always be NO_
5. How much exposure does non-compliance introduce? _<- this doesn't seem to be applicable in this space since it's not regulated_
6. How much personally identifiable information could be disclosed? _<- remove/replace_

Some of these questions (e.g. 1 and 6) focus on (personal) data, which is not a concern for smart contracts because the security model of public Ethereum is such that data is not going to be kept confidential or private.

**Comment by chriseth** [comment]
Is there an established practice how other compilers handle OWASP?

**Comment by holiman** [comment]
I don't know, but I suspect not. Owasp comes from "Open Web Application Security Project", so the root context is webb-apps, which is quite different from compilers.

**Comment by axic** [comment]
I have used OWASP more as a guideline, than strict source of truth. The fact is that we already juggle two metrics and try to come up with a single severity based on that metric. I think it would be useful two individually represent those two metrics instead.
