### ISSUE TITLE
Allow instantiating multiple variables in the first component of a for loop

### ISSUE THREAD

**Issue by y0wl** [ethereum/solidity#11517]
## Abstract

Allow syntax like `for (uint8 i, uint j, uint k;;) {}`

This can be hackily "solved" with https://github.com/ethereum/solidity/issues/3300 however this doesn't allow for definitions of multiple variable types. I couldn't find any similar issues that cover this feature.

## Motivation

This is a commonly used syntax in many other popular languages

## Specification

This would allow for a list of comma separated statements in the first component of the for loop. The existing behavior allows for only a single statement.

## Backwards Compatibility

This _should_ compile to the existing workaround `uint8 i; uint j; for (uint k;;) {}`. The old syntax will still be compatible with single statements in the first component.

**Comment by cameel** [comment]
We discussed it today and we do not think this is worth complicating the syntax. The workaround with putting variables before the loop isn't terrible. Putting these variables in the loop would limit their scope which is nice but you can easily get the same effect with a function or a block.

To be clear, it did not seem to me like anyone was strongly opposed to this feature. It's more that the reasons for adding it do not seem compelling enough. Also, you're the first one to actually request this which indicates that demand is low.

I'm going to close this but feel free to open a discussion on this topic with other users on the [forum](https://forum.soliditylang.org/). If it turns out there's significant demand for this, we might reconsider.

**Comment by y0wl** [comment]
I think this is a totally fine resolution! :)
