### ISSUE TITLE
Exception on overflow in unsigned->signed conversion

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1153]
When an unsigned integer is converted to a signed integer of the same size, in half the cases, the original number is not expressible in the target type.  This is one form of overflow and it should cause an exception, following the discussion in #796.

**Comment by chriseth** [comment]
Are you talking about explicit conversions? I think we should not throw an exception for explicit conversions because otherwise there is no way to actually perform explicit overflow.

There have been suggestions to provide two types of explicit conversions with different error behaviour, but there is no proposal on syntax yet.

**Comment by pirapira** [comment]
I'm trying to enumerate overflows in arithmetics.

**Comment by pirapira** [comment]
Delegated back to #796.
