### ISSUE TITLE
Solc 0.8.6 release announcement link is broken

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#11570]
## Page

https://github.com/ethereum/solidity/releases

## Abstract

The 'release announcement' link is broken (leads to 404).

You can go to the page above and click that link, or try it directly at https://blog.soliditylang.org/2021/06/22/solidity-0.8.6-release-announcement/.

**Comment by cameel** [comment]
Thanks for reporting but it's not a bug. You're a bit too quick :) The release is currently being prepared and it always takes some time. Publishing the blog post is one of the last steps. That's why the release page on github says "Release in progress - please wait".

If you want to read it already you can take a look at https://github.com/ethereum/solidity-blog/pull/142
