### ISSUE TITLE
Make `--pretty-json` work with Standard JSON output

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#11583]
By default the compiler prints any JSON output in a compact form:

```bash
echo "contract C {}" | solc - --combined-json abi
```
```json
{"contracts":{"<stdin>:C":{"abi":[]}},"version":"0.8.6+commit.11564f7e.Linux.g++"}
```

You can use `--pretty-json` option to get nicely indented output from `--combined-json` option:

```bash
echo "contract C {}" | solc - --combined-json abi --pretty-json
```
```json
{
  "contracts":
  {
    "<stdin>:C":
    {
      "abi": []
    }
  },
  "version": "0.8.6+commit.11564f7e.Linux.g++"
}
```

This does not work with `--standard-json`. Make `--pretty-json` affect it too.

Optionally, it would also be nice if you could specify the indent size for the option to make the output easier to read (e.g. `--pretty-json 4`).

**Comment by cameel** [comment]
Once this is done, we could also make `test/cmdlineTest.sh` use that option to print test output in a more readable way.

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.
