### ISSUE TITLE
[YulOpti] Converting loops that copy into memory into calldatacopy and returndatacopy

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11586]
## Converting a memory loop into calldatacopy

Take the example

```solidity
    contract C {
        function f(uint[] memory x) external returns (uint) {
            return x.length;
        }
    }
```

Copying from calldata to memory currently would be done in the following loop:

```yul
for { } lt(i, _4) { i := add(i, 1) }
{
    mstore(dst, calldataload(src))
    dst := add(dst, 32)
    src := add(src, 32)
}
```

However, it's more optimal to rewrite this as

```
if lt(i, _4) {
    calldatacopy(dst, src, mul(32, sub(_4, i)))
}
```
----
## Analysis on the savings

Assuming that the loop will be run `n` times, each iteration involves

1. the condition check: total: 25 gas.
   - `lt(i, _4) + iszero`: 12 gas
   - `push tag` + `jumpi`: 13 gas
2. loop body: total: 33 gas (current codegen: 45 gas)
   - `calldataload(src)`: 6 gas
   - `mstore(a, calldataload(src))`: 9 (including memory exansion cost; assuming it's linear)
   - `dst := add(dst, 32)`: 9 (ends up being 15 gas right now though)
   - `src := add(src, 32)`: 9 (also ends up being 15 gas right now.)
4. post condition: 9 gas (current codegen: 15 gas)
   - `i := add(i, 1)`: 9 (also ends up being  15 gas)

So each iteration is: 67 gas (in the best case) or 85 gas (in the current codegen.)

However, the equivalent average cost for one iteration in the `calldatacopy` case would be approximately`6` gas. Total cost would be
- If condition + `jumpi`: 25
- Body: `3 + 6*n` (for calldatacopy) + 21 for the rest.

The total cost for loop would be `25 + 64 * n` whereas it's `49 + 6*n` for the if condition, where `n` is the number of iterations.

(In practice, a user reported that a certain function after the change went from `3k` to `700` gas!)

---

## Implementation

One way to implement this is similar to pattern matching in `ExpressionSimplifier`.

We match

```
for { } lt(X, Y) { Z := add(Z, 1) }
{
    mstore(U, calldataload(V))
    U := add(U, 32)
    V := add(V, 32)
}
```

and replace it by 

```
if lt(X, Y) {
    calldatacopy(U, V, mul(32, sub(Y, X)))
}
```

Where `X`, `Y`, `U` and `V` should match only identifiers or literals.

--- 
## Other loops.

Similarly, also for `returndata`.

**Comment by chriseth** [comment]
We were thinking about a pattern matching system that can match Yul syntax beyond expressions previously (I guess there is also an issue).

For this particular case, we have the additional requirements that:
 - `X` and `Y` are movable
 -  `Z`, `U` and `V` are never read after the for loop

(I actually think that `X` and `Z` should be the same variable)

The second condition can be removed by changing the replacement so that `U`, `V` and `X`/`Z` are just incremented accordingly. Another optimizer stage should remove this assignment if they are never read afterwards.

Also, potentially wrapping behaviour should be taken into account for the condition.

**Comment by sambacha** [comment]
any update on this? thx
