### ISSUE TITLE
The second example from `libraries.rst` crashes Remix IDE

### ISSUE THREAD

**Issue by lie16** [ethereum/solidity#11687]
## Page

https://docs.soliditylang.org/en/v0.8.6/contracts.html#libraries

## Abstract

Remix crashed every time I tried to paste 2nd example, I don't know what's wrong, could someone help me?

**Comment by chriseth** [comment]
The code formatting in the second example of `https://docs.soliditylang.org/en/v0.8.6/contracts.html#libraries` is weird. My guess is that `type` is considered a keyword and thus `type(uint)` does not parse properly. This could also be the reason for the crash in remix. Would be happy for someone to investigate further.

**Comment by cameel** [comment]
> The code formatting in the second example of `https://docs.soliditylang.org/en/v0.8.6/contracts.html#libraries` is weird. My guess is that `type` is considered a keyword and thus `type(uint)` does not parse properly.

No, it's actually the `||` operator. Lexer used for highlighting in docs appears to be buggy and has trouble parsing things like  `&&`, `||`, `? :`, `1e18` or even `pragma solidity >x.y.z;` (`>=` is fine). And it's not just this single example. There are actually tons of warnings about code snippets when I build the docs locally but these warnings do not show up in CI because we're using very old Sphinx/Pygments there. I actually have a PR that updates these packages and fixes the warnings (mostly by slightly changing examples or just using `:force:`): #11662. I think we'll have to fix the lexer ourselves eventually though.

> This could also be the reason for the crash in remix.

I just tried it and it does not crash for me. And `solc` compiles it just fine too. How can I reproduce the crash?

BTW, @lie16 what kind of crash is this? Is there an error message or something?

**Comment by lie16** [comment]
This is what happen when I post this problem:
1. When I try it remix become unresponsive and I had to reopen new remix tab. 
2. When I reopen the file in the new tab, the source code just gone.

Today I try it again it work fine, maybe the crash was related to the solidity file(unfinished code & not compilable) that I already delete yesterday.
Sorry for the trouble.
