### ISSUE TITLE
Feature Request: Combine nested structs in single storage slots

### ISSUE THREAD

**Issue by zemse** [ethereum/solidity#11691]
## Abstract

```solidity
struct Number {
    uint56 value;
    uint8 shift;
}

struct Slot0 {
    Number val1;
    Number val2;
    Number val3;
    Number val4;
}

struct Slot1 {
    uint64 val1;
    uint64 val2;
    uint64 val3;
    uint64 val4;
}

Slot0 public slot0;
Slot1 public slot1;

// costs 4 SSTOREs
function write0() public {
    slot0 = Slot0(Number(1, 1), Number(1, 1), Number(1, 1), Number(1, 1));
}

// costs 1 SSTORE
function write1() public {
    slot1 = Slot1(1, 1, 1, 1);
}
```

## Motivation

Allowing fixed-length structs to behave as a `uint` type in the storage sense (like in this case `Number` as `uint64`) can be very helpful and simplify the code.

## Specification

Since Slot0 in total uses (8+56)x4 = 256 bits, it should use only one slot instead of 4.

## Backwards Compatibility

~Since there is no change in syntax is needed, just how the storage layout works this out, existing solidity code would also be successfully compiled.~

This is a backward-incompatible change to the storage layout. Some contracts using upgradable proxy patterns are affected.

**Comment by axic** [comment]
This isn't really an optimiser feature, but a core feature how storage is laid out. Marking it an optimiser feature would mean storage layout changes whether the optimiser is turned on or not.

**Comment by cameel** [comment]
> Since there is no change in syntax is needed, just how the storage layout works this out, existing solidity code would also be successfully compiled.

The fact that the contract still compiles does not make the change backwards-compatible if the behavior of the compiler changes. It's a backwards-incompatible change to the storage layout. Consider for example the case of someone using a proxy to make his contract upgradable. In the case you're presenting the location of `slot1` would shift and even the same exact source code compiled with a newer compiler having this feature would not be usable with that proxy.

So this at least needs a way to get the old behavior back. And I think that making the new behavior the default is an unnecessary complication. The change would be completely backwards-compatible if you had to explicitly request it. For example:

```solidity
struct Slot0 {
    Number packed val1;
    Number packed val2;
    Number packed val3;
    Number packed val4;
}
```
or
```solidity
struct packed Slot0 {
    Number val1;
    Number val2;
    Number val3;
    Number val4;
}
```

**Comment by chriseth** [comment]
The problem is not only with the layout, it is also with how storage items are referenced. If you use `slot0.val2` in the original example, then that expression needs two stack slots to be represented: The slot number and the offset inside the slot. Structs only use a single stack slot, so this would have to be changed. So using `slot packed` on Slot0 as @cameel suggested is not enough, you also need to change the type of `Number`.

My recommendation is to first do user-defined value types #11531 and then introduce functions to access the members:
```
type Number is uint64;
function value(Number _n) pure returns (uint56) { return uint64(_n) & type(uint56).max; }
function shift(Number _n) pure returns (uint8) { return (uint64(_n) >> 56) & type(uint8).max; }
```

This could cause `Number` to be tightly packed inside structs. The only downside is that assignment needs its own function again, but this is how proponents of functional-style languages would want it anyway:

```
function NewNumber(uint56 value, uint8 shift) pure returns (Number) {
  return Number(uint64(value) << 8 | uint64(shift));
}

slot0.val1 = NewNumber(value, shift);
```

If combined with `using {value, shift} for Number;` at least accessing looks almost like member access:
`n = slot0.number();`

**Comment by frangio** [comment]
Is this still considered now that there are user defined value types that pack in storage?
