### ISSUE TITLE
[SMTChecker] Filter `unsupported` messages

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#11703]
Currently the SMTChecker always reports when a certain Solidity feature is unsupported. This is annoying and might clutter the output with irrelevant information if the user has set the `contracts` option, and the unsupported feature is not reachable (not imported for example) from the target contract.
We should automatically only report those for code that is reachable from the target contracts.

**Comment by leonardoalt** [comment]
https://github.com/ethereum/solidity/pull/11850 already removed all redundant warnings, maybe it's already enough instead of this one.

**Comment by cameel** [comment]
Just a general idea: maybe SMTChecker should have some kind of "lite" mode meant to give you the best bang for the buck? I.e. it would disable warnings like these where they just *might* be hiding some problem and would avoid only the targets that are likely to give many false-positives, like the overflow checks. In general it would not give user the expectation that the results are complete and would instead do what it can to avoid listing spurious problems. There would also be one easy flag to enable this mode.

Having something like this might make the verbosity of the complete output less of an issue because you'd only see it when you are prepared to go through the code with a fine-toothed comb.

**Comment by leonardoalt** [comment]
I think it's fine to even make such mode the default. We already made the default not run underflow/overflow, maybe we could even remove out of bounds because that might yield a lot of checks, maybe we could *only* check asserts by default. But I don't think we should just disable these warnings, they can be a good indicator of why you got a certain result. I actually like the approach from solc-verify, they just bundle these things together (like we also did with the unproved targets), and say "X unsupported things/errors, use --show-errors to see all). We could do the same here, then you only get two messages max about unproved/unsupported stuff, and you can expand at a later run if you want. Would this be aligned with your suggestion?

**Comment by cameel** [comment]
It would be a way to make output less verbose and summarize it so it sounds good too.

> But I don't think we should just disable these warnings, they can be a good indicator of why you got a certain result.

But you would still get that info if you do a full run.

I think that the advantage of doing it the way I suggested might be that it would give users an easy way find the low hanging fruit and entice them to use it regularly without too much effort. They would only need a full run if something seemed like a false-positive of when doing the final in-depth analysis.

I think that the summary approach would still require you to rerun with `--show-errors` most of the time. The advantage is that you force the user to understand the output better but the downside is that it might not be as convenient for regular light usage. I think it's better as the default behavior though. The "lite" mode would be better off as something you have to explicitly request because by design it would not try to do a thorough job and user should not be misled into thinking that it's all SMTChecker does.

**Comment by leonardoalt** [comment]
That sounds good too. What config would you suggest for the light mode?

**Comment by leonardoalt** [comment]
Besides the discussion above: the idea of this issue is to group together all "unsupported" warnings into a single one similarly to how we currently do for "unproved targets". For example:

```solidity
contract C {
    function f(uint x, uint y) public pure {
        assembly {}
        assert(x < y);
    }

    function g(uint x, uint y) public pure {
        assembly {}
        assert(x < y);
    }
}
```

The smtchecker issues the following for the code above:

```bash
...

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
 --> a.sol:3:9:
  |
3 |         assembly {}
  |         ^^^^^^^^^^^

Warning: Inline assembly may cause SMTChecker to produce spurious warnings (false positives).
 --> a.sol:8:9:
  |
8 |         assembly {}
  |         ^^^^^^^^^^^


...
```

This should be grouped under a single warning:

```bash
Warning: 2 unsupported feature(s). If you want to see all of them in detail, run with "show unsupported" enabled.
```
