### ISSUE TITLE
undo making "error" a keyword

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#11743]
@axic proposed to not make it a keyword, and I slightly agree it can lead to serious problems with upgrading.

note: Making "error" a keyword has already been implemented in the breaking branch.

**Comment by hrkrshnn** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/mocks/ERC721ReceiverMock.sol#L20

is the only example from OpenZeppelin that would break now. It's merely a test case.

I don't really see why this would cause problems in upgrading (hopefully nobody has an external function with name `error`; even then it's not an impossible upgradability scenario since you can change the name to something with the same selector.)

All similar names `event, emit` etc are keywords, I think we shouldn't have an exception for `error`. The following code is currently valid

```solidity
struct error{uint x;}
contract C {
	error E;
}
```

Maybe it's better to advertise that error will be a keyword in 0.9.0 and ask people to refrain from using it now.

**Comment by chriseth** [comment]
If we keep `error` a keyword for 0.9.0, we should at least warn about it now. I think it is already a problem that `error` is used in openzeppelin - how many of the other verified contracts did you search?

**Comment by hrkrshnn** [comment]
Here's a "grep" of etherscan verified contracts using error currently

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/tintinweb/smart-contract-sanctuary+lang:Solidity+content:%22+error%5B%28%3B%29%5D%22++&patternType=regexp&case=yes

**Comment by ekpyron** [comment]
I vote for not only keeping ``error`` as keyword, but also promoting ``receive`` and ``fallback`` to keywords. For alleviating upgrade issues, we should add the ability to specify custom signatures in interfaces only (as we already considered when we had this debate for ``receive`` and ``fallback``).

That being said, if we *don't* want to add such a workaround and *don't* do the same for ``receive`` and ``fallback``, then ``error`` is no different from ``receive`` and ``fallback`` and it's more consistent to indeed not make it a keyword.

**Comment by ekpyron** [comment]
But we should be aware that deciding against making ``error`` a keyword now, basically means that we can never introduce any new keywords again whatsoever, since it will always basically be the same situation. And we *did* introduce new keywords in the past, so there is precedent for this.
Deciding on a whim on a case-by-case basis trying to judge how likely something is to occur does not seem overly reasonable to me. And will only force us to use obscure keywords in the language in the future.

**Comment by chriseth** [comment]
I'm fine either way, the main difference is that `error` could be a very common variable name while `fallback `and `receive`, `this` or `unchecked` not so much.

**Comment by hrkrshnn** [comment]
Here is a  list of etherscan verified contracts that has functions with name "error". None of them are part of the external interface. 

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/tintinweb/smart-contract-sanctuary+lang:Solidity+content:%22function+error%5C%5C%28%22&patternType=regexp&case=yes

For variable names, the breaking change merely involves renaming. I don't see how that is problematic.

**Comment by ekpyron** [comment]
There are public state variables in there, aren't there? (I just looked at the list here https://github.com/ethereum/solidity/issues/11743#issuecomment-899316573 and was about to write the opposite, i.e. that it *does* occur in external interfaces :-))

**Comment by chriseth** [comment]
It is problematic, because you have to re-do the audit.

**Comment by ekpyron** [comment]
> It is problematic, because you have to re-do the audit.

Yes, switching between breaking versions of a language is just fine, but beware those variable names :-).

**Comment by hrkrshnn** [comment]
> There are public state variables in there, aren't there?

Yeah, that is true :(

For future reference, here's the list of public state variables: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/tintinweb/smart-contract-sanctuary+lang:Solidity+content:%22public+error%3B%22++&patternType=regexp&case=yes

**Comment by ekpyron** [comment]
> There are public state variables in there, aren't there? (I just looked at the list here [#11743 (comment)](https://github.com/ethereum/solidity/issues/11743#issuecomment-899316573) and was about to write the opposite, i.e. that it _does_ occur in external interfaces :-))

I.e. those are part of the external interface: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/tintinweb/smart-contract-sanctuary+lang:Solidity+content:%22public+error%5B%28%3B%29%5D%22++&patternType=regexp&case=yes

**Comment by hrkrshnn** [comment]
Decided to undo the change from breaking.

In the future, we would like to make this a keyword. But we also want to provide a way to such keywords as function names or for other ABI related stuff.

@ekpyron mentioned writing up an issue on allowing this in a backwards compatible way.

**Comment by hrkrshnn** [comment]
Implemented in  https://github.com/ethereum/solidity/pull/11859
