### ISSUE TITLE
What is the meaning of `src` in `solc --ast-json` output?

### ISSUE THREAD

**Issue by shawnwbts** [ethereum/solidity#11921]
![image](https://user-images.githubusercontent.com/40200349/132703000-3dca42fe-c65f-4a68-86df-3c02c1240f9f.png)
Sorry to bother you, what is the meaning of **src** in the **ast-json** file generated by solc compilation?  I want to get the number of lines in the source code corresponding to the starting position of the function getEther in the figure, so I used the following code to make a judgment, but the number of lines seems to be incorrect.

**Comment by shawnwbts** [comment]
![image](https://user-images.githubusercontent.com/40200349/132704666-d26ff24e-3179-4a8f-bca4-ef85eb563112.png)

**Comment by shawnwbts** [comment]
Well, actually, I use the following code to get the specific location of the variable in the code. 6677 is the first **src** of function **getEther**, and 7026 is the first src of variable **call** ,but the result is unsatisfactory. The former is correct ,and its output is 158,but the later is 162(actually it should be 161)

![image](https://user-images.githubusercontent.com/40200349/132706017-f0a5e570-9725-4f53-a63a-f8fc8df6d1c2.png)
![image](https://user-images.githubusercontent.com/40200349/132706114-f99472bd-8277-486d-9316-e2eaad17441b.png)

**Comment by taylorgag** [comment]
![image](https://user-images.githubusercontent.com/40200349/132706582-f7a28e4c-a5ae-4d58-9dbc-99ea5b86ab77.png)

**Comment by shawnwbts** [comment]
![image](https://user-images.githubusercontent.com/40200349/132706823-eda393fe-f3e7-4d00-9e17-c418955e8b08.png)

**Comment by cameel** [comment]
Well, we should finally document the AST format (#1511).

`src` identifies the location of the text corresponding to the AST node in a Solidity source file. The format is `<start>:<length>:<index>`, where `start` is the position of the first byte belonging to that location. It's not the number of lines. It's also 0-based.

Not sure why you're getting wrong results from your function - it seems correct at a glance. There might be some subtle error though. Or you could be looking at a wrong line (does your editor display the first line as 0 or 1?). Or your file could be modified or maybe mangled due to line ending conversion in the editor if you're on Windows? Or it could even be a bug in the compiler. I can't really tell without seeing the input file and even with it, I'm not going to retype it all from a screenshot anyway.

By the way, the bug tracker is not the best place for questions like this. Please use it if you have a bug to report or a feature to request. If you need help just come to the [#solidity](https://gitter.im/ethereum/solidity) channel on gitter. Given that this is not properly documented, I think that this question would also be appropriate on the [forum](https://forum.soliditylang.org).

Also, just a bit of advice. You're making it unnecessarily hard for people to answer your question :) When I saw it first a few days ago I just skipped it because the title is useless and the screenshots just make it seem like the problem is very complex. Now I see that it's just a simple question about the `src` property that could be answered in a few minutes.  You'd be better off pasting just a small input snippet and a compiler command that anyone can run locally. If you want to paste the output, trim it a bit. And paste it as text - posting a screenshot is quick and easy for you but then anyone wanting to examine your problem has to tediously retype it and no one is really going to do that. I'd highly recommend taking a look at this: [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)

**Comment by shawnwbts** [comment]
Thank you for your warm reply. I'm sorry that my question caused some trouble to you. At the same time, thank you for your suggestion.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethereum/solidity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 凌晨2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethereum/solidity] solc --ast-json (#11921)





 
Well, we should finally document the AST format (#1511).
 
src identifies the location of the text corresponding to the AST node in a Solidity source file. The format is <start&gt;:<length&gt;:<index&gt;, where start is the position of the first byte belonging to that location. It's not the number of lines. It's also 0-based.
 
Not sure why you're getting wrong results from your function - it seems correct at a glance, though there might be some subtle error. Can't really tell without seeing the input file and I'm not going to retype it from a screenshot anyway.
 
By the way, the bug tracker is not the best place for questions like this. Please use it if you have a bug to report or a feature to request. If you need help just come to the #solidity channel on gitter. Given that this is not properly documented, I think that this question would also be appropriate on the forum.
 
Also, just a bit of advice. You're making it unnecessarily hard for people to answer your question :) When I saw it first a few days ago I just skipped it because the title is useless and the screenshots just make it seem like the problem is very complex. Now I see that it's just a simple question about the src property that could be answered in a few minutes.  You'd be better off pasting just a small input snippet and a compiler command that anyone can run locally. If you want to paste the output, trim it a bit. And paste it as text - posting a screenshot is quick and easy for you but then anyone wanting to examine your problem has to tediously retype it and no one is really going to do that. I'd highly recommend taking a look at this: How do I ask a good question?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
