### ISSUE TITLE
Allowing regular constructor syntax for user defined value types

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#11953]
User defined value types currently only allow constructions via the `UserDefineType.wrap(...)` function call. This can be rather verbose, especially when we allow operators on the type.

```solidity
type MyInt is int;
MyInt x;
x + MyInt.wrap(5);
// v/s
x + MyInt(1);
// v/s more controversial implicit literal conversion
x + 1;
```

**Proposal**: for a user defined type `Type T is V;` allow the syntax `T(<type V>)` to construct an element. This is in line with the same syntax for built-in types as well as for structs.

---

A second problem with `.wrap` and `.unwrap` is the lack of *type-encapsulation*. As long as the type `MyInt` is visible in the context, so are the functions `MyInt.wrap` and `MyInt.unwrap`. This makes compiler enforced type-encapsulation impossible, currently.

One way to solve this is allowing the constructor only in the same source unit as the type declaration.
```solidity
==== Source: A ====
type MyInt is int;
==== Source: B ====
import {MyInt} from "A";
// this would be a compile error as the constructor is not 'public'
MyInt(1);
```

This is also how rust solves it: see section [Problem 1](https://www.worthe-it.co.za/blog/2020-10-31-newtype-pattern-in-rust.html).

(As @ekpyron pointed out, encapsulation isn't an issue exclusively with `.wrap` and `.unwrap`--we can enforce the same rules to `.wrap` and `.unwrap`.)

As a side proposal: perhaps it is worthwhile to allow `type MyInt is public int;` which would expose the `MyInt(...)` constructor in other source units. However, this can be done separately in the future.

---

*Issues*

The proposed syntax looks quite similar to conversions. This may be confusing. For example, in  `type Fixed18 is int;`, a user may confuse `Fixed18(1)` to mean `Fixed18.wrap(10**18)`. Encapsulation may be a solution for this. Where a fixed point library can implement it as follows:
```solidity
==== Source: FixedMath ====
type Fixed18 is int;
function toFixed18(int x) pure returns (Fixed18) { return Fixed18(x * 10**18); }
==== Source: B ====
import {Fixed18, toFixed} from "A";
// only toFixed18() is accessible here.
// Fixed18(5) would not typecheck here
```

Other issues (raised by @ekpyron and @chriseth):
- The construction syntax is unnamed, and this only works if there is clearly one way to do it.
- Looking at `MyInt(5)` only as construction, rather than conversion, might require changing all the existing conversions. Relevant: https://github.com/ethereum/solidity/issues/11284.
- Potential issues with generics in the future.

**Comment by ekpyron** [comment]
Encapsulation works just as well with `wrap` and `unwrap`. We can just remove them from the type outside of whatever scope this should be restricted to - but still have defined explicit conversions.
So this really doesn't have anything to do with wrap/unwrap vs conversion syntax.

And as you say: as long as ``MyInt(...)`` is our conversion syntax for other types, we should also treat it as conversions and not as construction for user-defined types, otherwise things become inconsistent and confusing.
Once we have different conversions I'd be very happy to use ``MyInt(...)``as construction - however, what you haven't talked about at all is destruction - how do you imagine that to work? Is pattern matching another requirement for this change or do you have a different solution?

**Comment by chriseth** [comment]
I think it is a good thing that construction from the underlying type is verbose by default. For fixed point types, this is exactly what one wants. We can allow user-defined implicit conversion and then use explicit and implicit conversion interchangeably (explicit conversion should be done by a named function).

I'm not really sure where this issue is getting at, but operators are not a problem in my opinion:
```
MyInt x;
x + 1;
```
works as long as there is
```
using {myAdd as +} for MyInt;
function myAdd(MyInt x, uint y) pure returns (MyInt) { ... }
```
