### ISSUE TITLE
Compile ASTJsonConverter.cpp failed to "error C3861: 'iter_swap': identifier not found" and "error C2672: 'ranges::iter_swap': no matching overloaded function found"

### ISSUE THREAD

**Issue by YangYang129** [ethereum/solidity#12027]
Compile ASTJsonConverter.cpp failed to "error C3861: 'iter_swap': identifier not found" and "error C2672: 'ranges::iter_swap': no matching overloaded function found", can you help look? Thank you very much

**Environment**
- Compiler version: VS2019 (16.11.2)
- Operating system: Windows server 2016

**Reproduce steps:**
1. git clone https://github.com/ethereum/solidity
2. cd solidity
3. mkdir build_amd64
4. cd build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBoost_INCLUDE_DIR="F:\tools\boost_1_67_0\x64" ..
6. msbuild /p:Configuration=Release;Platform=x64 solidity.sln /t:Rebuild /m

**Error log:**
[msbuild_x64.log](https://github.com/ethereum/solidity/files/7231141/msbuild_x64.log)

**Error info:**
1. F:\solidity\build_mad64\deps\include\range/v3/algorithm/sort.hpp(92,25): error C3861: 'iter_swap': identifier not found (compiling source file F:\solidity\libsolidity\ast\ASTJsonConverter.cpp) [F:\solidity\build_mad64\libsolidity\solidity.vcxproj]
2. F:\solidity\build_mad64\deps\include\range/v3/algorithm/sort.hpp(92,25): error C2672: 'ranges::iter_swap': no matching overloaded function found (compiling source file F:\solidity\libsolidity\ast\ASTJsonConverter.cpp) [F:\solidity\build_mad64\libsolidity\solidity.vcxproj]

**Note:**
These errors is due to compile ASTJsonConverter.i (cl /EHsc /permissive- /std:c++20 /TP ASTJsonConverter.i) 
[ASTJsonConverter.i.zip](https://github.com/ethereum/solidity/files/7231159/ASTJsonConverter.i.zip)

**Comment by cameel** [comment]
I think that the error is coming from `ranges::sort()` added in #11837 (we were using `boost::range::sort()` until then). The question is why.

It does not fail in our CI - [`b_win` job passed on that PR](https://app.circleci.com/pipelines/github/ethereum/solidity/18301/workflows/aae7c2d7-b365-4930-84b1-26bef9f1ac32/jobs/816098) with MSVC 16.11.0+0538acc04 and is still passing in newer PRs.

At first I wanted to suggest that it might be because you're mixing c++17 and c++20 but you don't have `/std:c++20` in your repro (only in the command to generate the .i file) so that can't be it.

ranges-v3 generally has [tons of workarounds for weird MSVC behaviors](https://github.com/ericniebler/range-v3/blob/0.11.0/include/range/v3/detail/config.hpp#L222-L277), including [one specifically for `iter_swap`](https://github.com/ericniebler/range-v3/blob/0.11.0/include/range/v3/iterator/access.hpp#L194-L196) and this might have something to do with them. Your compiler is slightly newer than the one we're using so you might be just running into something new that needs another workaround.

To debug this, we need someone with Windows env that can reproduce it, so it looks like a task for @christianparpart :)

**Comment by cameel** [comment]
By the way, this is how we build it on Windows in CI: [`build_win.ps1`](https://github.com/ethereum/solidity/blob/develop/.circleci/build_win.ps1) (this gets executed by the [`b_win` job](https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml#L880-L910)). The options are not identical to yours but I don't see anything that would be an obvious cause of the errors your getting. Still, if you could try to build it with options as close to ours as possible, we'd at least be able to exclude this as a cause.

**Comment by YangYang129** [comment]
@cameel Thanks for your reply and info. According to [build_win.ps1](https://github.com/ethereum/solidity/blob/develop/.circleci/build_win.ps1) and [install_deps.ps1](https://github.com/ethereum/solidity/blob/develop/scripts/install_deps.ps1), I install cmake-3.18.2-win64-x64 and  and boost_1_74_0, then try to msbuild, still display these two errors. Please help me to look at this issue, thanks for advance.

**Reproduce steps:**
1. git clone https://github.com/ethereum/solidity
2. cd solidity
3. mkdir build_amd64
4. cd build_amd64
5. cmake ..\deps\cmakex64\cmake-3.18.2-win64-x64\bin\cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBoost_DIR="F:\solidity\deps\boost\x64\lib\cmake\Boost-1.74.0" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_INSTALL_PREFIX="F:\solidity\upload" ..
6. msbuild /p:Configuration=Release;Platform=x64 solidity.sln /t:Rebuild /m

**Error log:**
[msbuild_x640930.log](https://github.com/ethereum/solidity/files/7257327/msbuild_x640930.log)

**Note:** I do not install Z3

**Comment by cameel** [comment]
You actually need Boost 1.77 now, because of #12024/#11688 but looking at the log, that's what you used. In any case, it should not affect this.

So looks like it's not because of the differences in options. In that case I really can't help much more since I don't have an environment where I could reproduce this. @christianparpart, we need you here :)
