### ISSUE TITLE
Expensive access calldata member

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#12103]
## Description
If an external method receives a struct member, it seems only natural to use "calldata" in internal methods to access its members: after all, it requires no stack pushes and no extra copy of unneeded data from calldata to memory.

Apparently, it isn't that simple:

accessing "calldata" structure member is very complex, and **very expensive**.
instead of simple "calldataload(offset)" call, the compiler generates a complex method.

below is a sample code, which shows that replacing direct `struct.member` member access with a method call (implemented as a one-liner assembly) reduces the gas cost by **400** !

Apparently, if my custom assembly method is that simple, the compiler knows how to inline it completely (which is great. its just too bad it can't do the same with the auto-generated member-access method)

An extra problem is that there is no easy way to write these accessor functions in assembly: there is no way to know the offsets of the fields inside the struct, and need to do manual offset calculation. And if we want to access dynamic parameters, its even more complex and error-prone.

```solidity

// SPDX-License-Identifier: GPL-3.0-only
pragma solidity ^0.8;
import "hardhat/console.sol";

contract AArun {
    constructor() {
        Test t = new Test();
        uint g = gasleft();
        Struct memory s;
        s.sender = address(this);
        s.extra="asd";
        t.test1(s);
        uint g1 = gasleft();
        t.test2(s);
        uint g2 = gasleft();
        uint t1=g-g1;
        uint t2=g1-g2;
        console.log("test1 %s test2 %s diff= %s", t1, t2, t1-t2 );
    }
}

struct Struct {
        address sender;
        bytes extra;
    }

library StructLib {
    function getSender(Struct calldata s) internal pure returns (address ret) {
        assembly { ret:=calldataload(s) }        
    }

}    

contract Test {
   using StructLib for Struct;

    function test1(Struct calldata s) external {
        require(s.sender == msg.sender, "sender check");
    }    
    function test2(Struct calldata s) external {
        require(s.getSender() == msg.sender, "sender check2");
    }    

}
```

**Comment by chriseth** [comment]
I would advise you to take a look at the generated assembly in the two cases and compare it. You will see that instead of a simple `calldataload`, the compiler calls an internal routine from the generated file "#utility.yul". You can obtain that file using `--combined-json generated-sources-runtime`. The internal routine is the following:
```
function abi_decode_tuple_t_struct$_Struct_$6_calldata_ptr(headStart, dataEnd) -> value0
{
  if slt(sub(dataEnd, headStart), 32) { revert(0, 0) }
  let offset := calldataload(headStart)
  if gt(offset, 0xffffffffffffffff) { revert(0, 0) }
  let _1 := add(headStart, offset)
  if slt(sub(dataEnd, _1), 64) { revert(0, 0) }
  value0 := _1
}
```

And here you can see the trade-off between `memory` and `calldata` structs: Both of them are always checked for access beyond calldata, but while for memory structs, this only has to be done once when the data is copied to memory, it has to be done for each access when you use calldata.

There is a slight inconvenience here: Since we did not want to implement calldata access twice, we are re-using the new IR-based code generator in the current code generator. This way, one of the checks will be done twice, I believe.

The good news is that the two ways to access the sender member optimize to exactly the same code when using the new IR-based code generator for the full contract. You can try it out using `solc --experimental-via-ir`.

Because of that, I'm closing this issue. We will likely make the new code generator non-experimental before fixing this in the old code generator.

**Comment by drortirosh** [comment]
I don't think your example is relevant to that specific case: I'm referencing the a member of a struct that its offset is known at compile time. Also, its size is fixed and known.
I agree that if I access a dynamic member, like `extra`, above, you'd have to verify the returned offset, and then the total length (and still, allow "unchecked" code run without those checks)

**Comment by hrkrshnn** [comment]
@drortirosh About the benchmark: there is a small issue in this comparison. Since `test1` and `test2` are in the same contract, the order in which the function appears in the function dispatch makes will affect your benchmark. In this case, `test2` is the first function in the dispatch. Could you try to redo the benchmark, but with two different contracts, each having only a single function? Also, are the numbers after you enable the optimizer?
