### ISSUE TITLE
Consider adding Gitpod support for contributors to the codebase

### ISSUE THREAD

**Issue by nickytonline** [ethereum/solidity#12112]
## Abstract

This is not so much a problem but a way to enable more folks to potentially contribute to Solidity. The proposal is to give contributors the option to work on the Solidity codebase in a cloud-based IDE. Gitpod is cloud-based IDE development environment that would enable this.

## Motivation

Potentially enable more folks to be able to contribute to the codebase.

## Specification

Gitpod would be configured to install the necessary dependencies for Solidity and build it. I've already configured Gitpod as I was looking to contribute to the codebase through Gitpod. See https://github.com/nickytonline/solidity/tree/nicktyonline/add-gitpod-to-solidity.

![image](https://user-images.githubusercontent.com/833231/136592763-dfd1a6d4-6d57-4ae5-b002-8ab47acaf297.png)

If the maintainers think this is a good idea, I'd love to put up a pull request from my branch.

## Backwards Compatibility

N/A

**Comment by cameel** [comment]
It depends how much maintenance it requires. If it's just just a small static config file that does not need to change between releases then why not. But anything that would require listing source files or compiler options will quickly go out of date. Also anything that would need to be regularly updated.

It's just that no one on the team is using GitPod so we will not really notice if this config breaks - we'd be relying on the community reporting breakage and testing updates. I'm not sure if GitPod is popular enough for this to work out in practice - see for example the recent issue with snap package (#11940) which has been broken since 0.5.16 without anyone reporting a problem.

Maybe a better alternative would be to document steps required for GitPod somewhere in [Installing the Solidity Compiler](https://docs.soliditylang.org/en/latest/installing-solidity.html) in the docs?

A few remarks about the config in your fork:
```yaml
  - name: Install deps and build Solidity
    init: |
      ./scripts/install_deps.sh
      brew install z3
      ./scripts/build.sh 
```
- `install_deps.sh` is no longer actively maintained and we have recently decided that we're going to remove it. Please just copy the part relevant to your environment to your script.
- `brew install z3` - note that this is mac-specific. Does GitPod actually run the build on macOS?
- `scripts/build.sh` is probably not what you want when you're setting up a dev environment.
    - It selects `Release` build by default. You probably want `Debug` or `RelWithDebInfo`.
    - It runs make with `-j 2` which may or may not be appropriate for this machine. How many cores are available? Choosing a value that is too low will unnecessarily slow down the build.
    - It installs the binaries in system dirs.

**Comment by nickytonline** [comment]
Thanks for the feedback. I'll take a peek at all this on the weekend. In regards to Homebrew, it's [supported by GitPod for Linux environments](https://www.gitpod.io/blog/brew).

**Comment by cameel** [comment]
ok. Well, it would not be my first choice of a package manager but if it works then I guess it's fine.

**Comment by nickytonline** [comment]
@cameel, I've removed the dependencies installation script you mentioned that is deprecated and have added the necessary dependencies explicitly, and also via `apt-get` instead of `brew`, as you mentioned it wasn't your first choice for a package manager.

I'll modify how it compiles for a development environment when I have some more time this week.

I'm happy to add this to the documentation instead, but I believe it would be minimal maintenance to have the Gitpod configuration in the project.

https://github.com/nickytonline/solidity/blob/nicktyonline/add-gitpod-to-solidity/.gitpod.yml

As well, it would not affect your CI/CD pipeline since it's only configuration to load the project into an online IDE. Worst case, if there were lots of changes at some point to the project, I or another community member that uses Gitpod would most likely be the ones to update it if no one on the core team had.

Again, happy to do whichever you think is best for the project, i.e. docs vs. Gitpod config in the project.

**Comment by cameel** [comment]
Great. Something like the config you linked would be fine. I think that there would be no problem accepting a PR with that (though I think you still need to add build instructions there? Currently it only install the dependencies).

This might actually turn out to be more useful than I thought - @ryzheboka had problems with building the compiler locally to work on #10308 and is interested in trying it out. If the IDE would help resolve the problems in this case, it would actually be a big help!

**Comment by nickytonline** [comment]
That's great that it could already potentially help someone who would love to contribute to the project.

For compiling the build in debug mode, I will add that back as per your instructions.

> - scripts/build.sh is probably not what you want when you're setting up a dev environment.
>    - It selects Release build by default. You probably want Debug or RelWithDebInfo.
>    - It runs make with -j 2 which may or may not be appropriate for this machine. How many cores are >available? Choosing a value that is too low will unnecessarily slow down the build.
>    - It installs the binaries in system dirs.

I'll put up a draft PR for now and continue on this. 😎

**Comment by nickytonline** [comment]
@cameel, is it customary on this project to ask to be assigned to an issue? If so, please assign this to me. Thanks!

**Comment by cameel** [comment]
Sure. I assigned you.

**Comment by chriseth** [comment]
I'm not sure how many resources are available in the cloud for this, but I almost never build in debug mode because the binary is extremely big, the build time is increased (mostly due to linking large files) and the test runs take much longer.

Is it possible to have multiple build profiles for this hosted IDE?

**Comment by chriseth** [comment]
Oh and by the way, my preferred build mode is `-DCMAKE_BUILD_TYPE=` which is neither release nor debug mode, but builds fastest.

**Comment by ryzheboka** [comment]
Thanks, I could finally build solidity from source and run it using Gitpod! Gitpod wouldn't build without the option -DUSE_Z3=OFF

**Comment by cameel** [comment]
> Gitpod wouldn't build without the option -DUSE_Z3=OFF

I see that the config does install libz3 so I suspect this might be because it's too old. What was the error message?

We normally require the latest stable version (4.8.12) because that's the only version where SMT tests will pass. We maintain a PPA that provides this version (see [Installing the Solidity Compiler > Linux Packages](https://docs.soliditylang.org/en/latest/installing-solidity.html#linux-packages)).

Alternatively, if you are ok with having to skip skipping these tests with the `--no-smt` flag then any 4.8.x version would work and most distros are on 4.8.x already. In that case you can use `-DSTRICT_Z3_VERSION=OFF` to make the compiler accept a lower version.

**Comment by nickytonline** [comment]
It seems to install 4.8.7 and I can't figure out why it's not installing latest for z3. Still digging.

**Comment by cameel** [comment]
Probably because the distro (is it Ubuntu, Debian or some other Debian derivative?) does not ship the latest version yet. That's why we maintain the PPA. Please use it.

**Comment by nickytonline** [comment]
I didn't forget about this. I had some other things come up last week. I have installed the ppa as you had suggested @cameel, but just sorting out a few things in regards to that. Apparently the PPA doesn't support the Ubuntu version in the default image on Gitpod. Just looking into sorting that out.

**Comment by cameel** [comment]
Which version is that? We're generally dropping support for old versions eventually to make maintenance easier (getting up to date versions of libraries and compilers is a pain) but knowing what is used in practice might make us hold on to them a bit longer in the future.

**Comment by nickytonline** [comment]
It's actually a newish version, Ubuntu 20.04.3 LTS (Focal Fossa). It appears to not support Focal Fossa, or maybe I'm reading the logs incorrectly.

I ran `sudo apt-add-repository -y ppa:hvr/z3` based on what I saw in the deps script.

```
Err:17 http://ppa.launchpad.net/hvr/z3/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
```

Full log:

```
sudo apt-add-repository -y ppa:hvr/z3
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                        
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                                                                           
Get:4 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease [23.8 kB]   
Get:5 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [12.5 kB]                            
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                                    
Get:7 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [801 kB]                          
Ign:8 http://ppa.launchpad.net/hvr/z3/ubuntu focal InRelease                                                         
Get:9 https://apt.llvm.org/focal llvm-toolchain-focal InRelease [5,526 B]                                            
Get:10 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,167 kB]                                                 
Get:11 https://apt.llvm.org/focal llvm-toolchain-focal/main amd64 Packages [11.9 kB]           
Get:12 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]                       
Get:13 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [618 kB]              
Get:14 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]                            
Get:15 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [3,165 B]                           
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,085 kB]                     
Err:17 http://ppa.launchpad.net/hvr/z3/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [670 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,614 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.4 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [6,310 B]
Reading package lists... Done                                 
E: The repository 'http://ppa.launchpad.net/hvr/z3/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by cameel** [comment]
We do support focal:
https://github.com/ethereum/solidity/blob/ef21e43fa36be8ff58725133aa5bb6e74bd06baf/scripts/deps-ppa/static_z3.sh#L30

> I ran `sudo apt-add-repository -y ppa:hvr/z3` based on what I saw in the deps script.

Oh, so that's the problem :) This does not look like our PPA. Please try `add-apt-repository ppa:ethereum/ethereum` (see [Installing Solidity > Linux Packages](https://docs.soliditylang.org/en/latest/installing-solidity.html#linux-packages)).

**Comment by nickytonline** [comment]
@cameel, I'll preface this with this is the first time I'm using a PPA. 😅  I have a feeling I'm doing something silly or just not updating the correct package. So I've added the proper PPA according to your previous comment, but the `libz3-dev` package does not update. Also as mentioned previously, Gitpod is running Ubuntu 20.04.3 LTS (Focal Fossa) which is supported by the PPA.

```
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get -y update
sudo apt-get -y install build-essential libboost-all-dev libz3-dev
```

When I run `sudo apt-get -y install libz3-dev`, it tells me that nothing was upgraded.

```
gitpod /workspace/solidity $ sudo apt-get -y install libz3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libz3-dev is already the newest version (4.8.7-4build1).
0 upgraded, 0 newly installed, 0 to remove and 109 not upgraded.
```
I'll keep digging for the time being.

**Comment by ekpyron** [comment]
To be honest, I'm a bit worried about this. Are we going to add and maintain configuration files for any old commercial and paid cloud service that happens to ask?

**Comment by nickytonline** [comment]
> To be honest, I'm a bit worried about this. Are we going to add and maintain configuration files for any old commercial and paid cloud service that happens to ask?

This wouldn't affect the project itself. It would only affect anyone that decides to use gitpod as their development environment. And if this configuration for some reason got out of date, most likely people using gitpod, would update it,.  Having said that, I can appreciate the reservation to maintain another configuration. I haven't dug into the project too much, but if there is an existing Docker configuration for development, we could use that as gitpod does support custom Docker images.

**Comment by ekpyron** [comment]
Doesn't gitpod provide a separate mechanism for adding configuration files *for* repositories instead of requiring them *in* the repository? To me that would seem to be a more reasonable approach.

If the file is in our repository, we will need to maintain it one way or another (if only by reviewing updates by users).
While this may be ok for *one* such file for *one* external IDE, once we start adding such support, we could hardly argue against also doing it for any other IDEs that might like to have such support.

As for docker images: we do in fact use docker images for our CI setup - they could very well be suitable for this, but we generally do not promote them or provide support for them. You can try if it works for your purpose - the Dockerfiles are in https://github.com/ethereum/solidity/tree/develop/scripts/docker/buildpack-deps - the current version of the ``ubuntu2004`` variant is on dockerhub as ``solbuildpackpusher/solidity-buildpack-deps@sha256:9c3cdfc1d573d1ca3edacd892590a9a83487a1f746a6ca2093d7e009818c5179`` (https://hub.docker.com/layers/solbuildpackpusher/solidity-buildpack-deps/ubuntu2004-8/images/sha256-9c3cdfc1d573d1ca3edacd892590a9a83487a1f746a6ca2093d7e009818c5179)

We refer to them via sha256 hash only ourselves, but in case they work for you and you want to make use of them for this, we could start pushing a ``latest`` tag in the future to make this easier.

**Comment by ekpyron** [comment]
If they work for you, using the docker files may be preferable in general - since they are used to run our CI they are pretty much always guaranteed to be up to date and work with the current state of the repository without any need for additional maintenance by anyone :-).
Also the docker images additionally contain builds of evmone and hera, which are required for running the full test suite, that's another bonus.
