### ISSUE TITLE
Contract size warning missing a crucial bit of information required in order to fix it

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#12171]
## Abstract

When a contract exceeds the maximum size (24K), it would be very helpful to know the actual size of that specific contract.

## Motivation

Allowing the developer to perform a more efficient process of reducing the "rogue" contract.

## Specification

In https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/CompilerStack.cpp#L1241-L1255, change this:
```
"Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). "
"This contract may not be deployable on mainnet. "
"Consider enabling the optimizer (with a low \"runs\" value!), "
"turning off revert strings, or using libraries."
```
To I guess something like this:
```
(
    string("Contract code size = ") +
    std:to_string(compiledContract.runtimeObject.bytecode.size()) +
    " > 24576 bytes (a limit introduced in Spurious Dragon). "
    "This contract may not be deployable on mainnet. "
    "Consider enabling the optimizer (with a low \"runs\" value!), "
    "turning off revert strings, or using libraries."
).c_str()
```

Thanks :)

**Comment by cameel** [comment]
True, the message would be more informative with the size included.

**Comment by barakman** [comment]
Thank you @cameel... Why 'good first issue' though? I've been posting issues here since v0.4 :)

**Comment by cameel** [comment]
Haha, it's not saying that it's first issue reported by you but that it's a good candidate to be picked as a first issue by a contributor :) With this label it will appear under https://github.com/ethereum/solidity/contribute and we have Hacktoberfest now so there's a high change that someone will pick it up soon. That's generally a good thing because these easy issues do not usually have a high priority (there are just too many of them).

**Comment by BoyanP** [comment]
Could i pick this one up? @cameel

**Comment by cameel** [comment]
Looks like we already have a PR for this (#12177).
