### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by Tied2eth** [ethereum/solidity#12234]
https://github.com/ethereum/solidity/blob/735550b734c79835e4f19ada6789835564292367/scripts/install_deps.sh#L126

**Comment by ekpyron** [comment]
You can try manually installing the dependencies listed in https://docs.soliditylang.org/en/latest/installing-solidity.html#prerequisites-all-operating-systems instead.

The script you were running is deprecated and will be removed in the foreseeable future (we don't have the resources to maintain a working script over all platforms).

Note, however, that we do not officially support building on FreeBSD, so while you *may* get the compiler to build and work, the compiler receives no testing on FreeBSD and you may encounter further issues (if you still want to try and need help with particular issues, feel free to ask in our matrix channel https://matrix.to/#/#ethereum_solidity-dev:gitter.im (or via gitter at https://gitter.im/ethereum/solidity-dev)).

**Comment by cameel** [comment]
Oh, so that was the trigger for #12237 :)

I don't think this "user" is actually using BSD. This looks like a spam account to me. There's another one with a very similar name (@tied2token) that is regularly spamming our repo with nonsense comments and occasionally even PRs.

Oddly it sometimes manages to drop a comment that makes sense in context like in https://github.com/ethereum/solidity/pull/12040#pullrequestreview-769528484 or even this PR :)

**Comment by ekpyron** [comment]
Yes it was :_). But ok, right :-). But yeah, it's perfectly plausible to run the script on FreeBSD and then just drop that message here, since the message pretty much tells you to do that :-).
