### ISSUE TITLE
use _library_ integer constants as fixed-length array sizes

### ISSUE THREAD

**Issue by benediamond** [ethereum/solidity#12248]
## Description

Integer constants can't be used as the sizes of fixed-length arrays, _even_ when they come from libraries.

## Environment

- Compiler version: 0.8.9
- Target EVM version (as per compiler settings): london
- Framework/IDE (e.g. Truffle or Remix): remix, hardhat, etc.
- EVM execution environment / backend / blockchain client:
- Operating system: MacOS

## Steps to Reproduce
`A.sol`:
```solidity
library A {
    uint256 constant N = 42;
}
```
`B.sol`:
```solidity
import './A.sol';

contract B {
    uint256[A.N] b;
}
```
leads to
```
TypeError: Invalid array length, expected integer literal or constant expression.
  --> contracts/B.sol:12:13:
   |
12 |         uint256[A.N] b;
   |                 ^^^

-->
```
somewhat related original issue, about constants in the _same_ file, now fixed: https://github.com/ethereum/solidity/issues/716
https://github.com/ethereum/solidity/issues/1290 is _not_ the same issue; it's about grabbing constants from other contracts which are _not_ libraries. but the workaround suggested there also works here.

**Comment by phyBrackets** [comment]
i think array length should be compile time constant not runtime constant . 

`contract B {
    uint constant u = 9;
    uint c;
    constructor(uint val){
        c= val;
    }
   uint256[c] b;
}`  

if you'll run this then you'll find the same error because we take the value at the runtime. and the array expect something which is compile time constant.
 This expression A.N will evaluated at runtime. So i think may be this is the problem.

**Comment by phyBrackets** [comment]
i think array length should be compile time constant not runtime constant .
``` solidity
contract B {
 uint constant u = 9; 
uint c;
 constructor(uint val){ 
c= val; 
} 
uint256[c] b;
 }```

if you'll run this then you'll find the same error because we take the value at the runtime. and the array expect something which is compile time constant.
This expression A.N will evaluated at runtime. So i think may be this is the problem.

**Comment by phyBrackets** [comment]
i think array length should be compile time constant not runtime constant .


``` solidity 
   contract B {
 uint constant u = 9;
 uint c; 
constructor(uint val){ 
c= val; 
} 
uint256[c] b;
 } 
```

if you'll run this then you'll find the same error because we take the value at the runtime. and the array expect something which is compile time constant.
This expression A.N will evaluated at runtime. So i think may be this is the problem.

**Comment by phyBrackets** [comment]
I think fixed size array expect compile time constant , but here A.N will be evaluated at runtime .

**Comment by chriseth** [comment]
A workaround for now would be to move the constant to file level.

This issue could have a duplicate somewhere by the way.

**Comment by benediamond** [comment]
> This issue could have a duplicate somewhere

i looked carefully and didn't find one.

> A workaround for now would be to move the constant to file level.

interesting, this move hadn't occurred to me. thanks. feel free to close if you want (though of course i think the "issue" is still open).

**Comment by ifuckingyouyeah** [comment]
![download](https://user-images.githubusercontent.com/93928639/140761082-d6712741-f9e9-46e5-99ca-35254bf6394f.jpeg)
hey is this a porn page

**Comment by qwerty472123** [comment]
@chriseth 

For `a.sol`

```solidity
uint constant a = 0x12345678;
```

`b.sol`

```solidity
import "./a.sol";

contract Hello {
    uint[a] x;
}
```

is OK, but `c.sol`

```solidity
import * as X from "./a.sol";

contract Hello {
    uint[X.a] x;
}
```

outputs `Error: Invalid array length, expected integer literal or constant expression.`.

**Comment by KumaCrypto** [comment]
Hey, guys! I faced the same problem with compiler version 0.8.23. Do you plan to add support for setting array length using a constant from the library?
The workaround mentioned above didn't work for me.

My simplified case:
```solidity
library MyLib {
    uint256  internal  constant ARR_LENGTH =  5;
    function getArray()  internal  pure  returns(uint256[ARR_LENGTH] memory arr) {
        return arr;
    }
} 

contract MyContract {
    function useArrayFromLib()  external  {
        uint256[MyLib.ARR_LENGTH] memory arr = MyLib.getArray();
    }
}
```
