### ISSUE TITLE
Create package for Fedora Linux (RPM)  

### ISSUE THREAD

**Issue by Itotutona** [ethereum/solidity#12270]
## Motivation

I am using Fedora Linux, and while searching the Github page, I did not find a package that was closely compiled for RPM based systems. It would be nice to create an rpm package for the solidity compiler. 

## Specification

It would be possible to publish the rpm package to copr (an equivalent of ubuntu ppa). 

## Links

https://copr.fedoraincloud.org
https://getfedora.org
https://rpm.org

**Comment by cameel** [comment]
Unfortunately we do not have the manpower to maintain packages for multiple distros. We only provide a PPA for Ubuntu and that's partly because we need to build packages for some of the dependencies for use in CI.

We also provide static Linux binaries of the compiler in [solc-bin](https://github.com/ethereum/solc-bin/). These should generally work on any distro. There's nothing special needed for RPM-based systems - it's just a single file. It does not really need packaging other than to make it easy to install via your package manager.

If you'd like to create and maintain a Fedora package, we're fine with it but we can't really maintain such a package ourselves.

**Comment by 0xSaksham** [comment]
Hey, as a fedora user. I would love to create such a package, but will require guidance from a experienced professional such as yourself.
