### ISSUE TITLE
Custom errors raised from external calls are not recognized by Remix

### ISSUE THREAD

**Issue by Nielsbishere** [ethereum/solidity#12290]
## Description

Unfortunately, calling revert Error(...) in a library won't show a proper message to the caller. It works fine if you call the library manually. This makes it almost impossible to use, since it's not clear which error occurred:

## Environment

- Compiler version: 0.8.10
- Target EVM version (as per compiler settings): ^
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: ^
- Operating system: N/A

## Steps to Reproduce

```sol
// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

library Test {
    
    error TestError(uint32);
    
    function answer(uint32 i) external pure {
        
        if(i != 42)
            revert TestError(i);
            
        //You receive unlimited riches here
    }
}

contract TestC {
    
    function callMeWrong() external pure {
        Test.answer(41);
    }
    
    function callMeRight() external pure {
        Test.answer(42);
    }
}
```
callMeWrong() only says:
```
revert
	The transaction has been reverted to the initial state.
Note: The called function should be payable if you send value and the value you send should be less than your current balance.
Debug the transaction to get more information.
```
instead of the expected
```
revert
	The transaction has been reverted to the initial state.
Error provided by the contract:
TestError
Parameters:
{
 "0": {
  "value": "41"
 }
}
Debug the transaction to get more information.
```

**Comment by chriseth** [comment]
I'm pretty sure this is a problem with remix (it cannot decode the error data) - the data is correctly returned.

**Comment by chriseth** [comment]
@yann300 can you please have a look if this might be a bug in remix? Thanks!

**Comment by cameel** [comment]
This is not limited only to libraries. Same happens if an external call to a contract reverts with an error:

```solidity
contract C {
    error E(string);

    function triggerError(bool fail) external pure returns (bool) {
        if (fail)
            revert E("Failed!");
        else
            return true;
    }
}

contract Test {
    function good() external returns (bool) {
        return new C().triggerError(false);
    }

    function bad() external returns (bool) {
        return new C().triggerError(true);
    }
}
```
```
transact to Test.bad errored: VM error: revert.

revert
	The transaction has been reverted to the initial state.
Note: The called function should be payable if you send value and the value you send should be less than your current balance.
Debug the transaction to get more information.
```

I think Remix is not detecting the error because it's not listed in the ABI for a contract unless that contract uses that error directly. And that's because our call graph does not follow external calls.

And we can't follow them unless we have the source. For libraries currently you always have to provide the source at compilation time (though #12096/#11695 would change that) so it might be technically feasible for the compiler to include errors from libraries. For contracts you might only have an interface though. The same effect can be achieved much easier if the tool just gathers possible errors from the ABI of all contracts included in the compilation so yeah, it's probably something best done on Remix side.

BTW, decoding errors is something that tools in general seem to be struggling with. For example some related Hardhat issues: https://github.com/nomiclabs/hardhat/issues/1618, https://github.com/nomiclabs/hardhat/issues/1919, https://github.com/nomiclabs/hardhat/issues/1875. When an error is propagated through a chain of external calls where you do not have the source of all the contracts in the chain, you might not be able to decode it. This is definitely a disadvantage compared to just passing an error message.

I wonder if it would be a good idea to have an auto-generated file with all errors in the project that people could share along with interfaces. The file would also transitively include all errors from other such files added as input along with the sources.

**Comment by Nielsbishere** [comment]
Seems like this is now applied in the latest Remix, thanks @yann300
