### ISSUE TITLE
Deallocation of memory for simple cases (e.g. keccak + abi.encode)

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#12335]
It's very easy to write code that makes wasteful use of memory so I think it's an important place to look for simple and common patterns amenable to optimization.

One such pattern is `keccak256(abi.encode(...))`. The result of encoding is put in memory and never deallocated, even though it's immediately used and there is no reference to it.

I'm not familiar with the optimization pipeline (for either codegen system) so I don't know what's an appropriate implementation strategy. I see this particular pattern very often, essentialy any use of `keccak256` goes together with `abi.encode` or `abi.encodePacked`, so it's worth detecting it and making sure that the free memory pointer is either restored to its previous position before the `keccak256` function call, or never bumped to begin with.

**Comment by cameel** [comment]
Thanks for a more detailed description. So it's a different optimization than the one I've been thinking of when I wrote https://github.com/ethereum/solidity/issues/12306#issuecomment-980043720. The PRs/issues I listed there are all about removing `mstore`s that can be proven to be redundant. Your case here is about memory allocation and reuse instead.

Turns out we do have an issue about that (#5107) and there's already been some progress there. I have not been closely tracking its overall status so @chriseth could give a much better update but we already do have sthe allocation/deallocation functions mentioned there. I remember at least reviewing a PR that made the Yul codegen consistently use them internally.

Also, this optimization will only be available via the Yul optimizer.

**Comment by chriseth** [comment]
The attempts to do this on the yul level were not very fruitful so far, but I think we could improve that on the Solidity level, in that we do reference and lifetime tracking on memory objects.

**Comment by frangio** [comment]
If it can't be implemented in a generalized way, is it possible to do it specifically for expressions of the form `keccak256(abi.encode[Packed](...))`?

**Comment by cameel** [comment]
Some older issues about the same optimization: #4182, #9046.

**Comment by cameel** [comment]
@frangio It can be implemented in a generalized way, just not necessarily in the optimizer. We discussed this recently and the current idea is to try something like this: #12351.

**Comment by frangio** [comment]
That approach sounds great, thanks for thinking about it and following up!
