### ISSUE TITLE
Place access modifiers first on the line

### ISSUE THREAD

**Issue by jesseduffield** [ethereum/solidity#12369]
## Abstract

By placing access modifiers, and the `payable` keyword at the start of the line, solidity code would be more readable.

## Motivation

Currently, access modifiers (e.g. 'public', 'external') are placed between the variable type and variable name, and for functions they're placed midway through the function signature. I find this makes it harder to read the code than if the access modifier appears first in the line as is typical with other languages.

Compare this snippet from the blind auction example in the [docs](https://docs.soliditylang.org/en/v0.8.10/solidity-by-example.html#id2):

```solidity
contract BlindAuction {
    struct Bid {
        bytes32 blindedBid;
        uint deposit;
    }

    address payable public beneficiary;
    uint public biddingEnd;
    uint public revealEnd;
    bool public ended;

    mapping(address => Bid[]) public bids;

    address public highestBidder;
    uint public highestBid;

    // Allowed withdrawals of previous bids
    mapping(address => uint) pendingReturns;
```

Although it's not so bad for the first four variables, the `bids` variable requires a bit more effort to determine whether it's public because you need to rely on good peripheral vision, or reading the actual line, to know that it's public.

If the access modifiers came in front it would like like this:
```solidity
contract BlindAuction {
    struct Bid {
        bytes32 blindedBid;
        uint deposit;
    }

    public address payable beneficiary;
    public uint biddingEnd;
    public uint revealEnd;
    public bool ended;

    public mapping(address => Bid[]) bids;

    public address highestBidder;
    public uint highestBid;

    // Allowed withdrawals of previous bids
    mapping(address => uint) pendingReturns;
```

This allows you to tell at a glance that the first seven variables are private and the `pendingReturns` variable isn't, without obscuring anything else. 

Likewise, with function definitions, the first thing I want to know about a function is its access level because that best contextualises it with respect to the rest of the code. Having it placed after the function name and input parameters makes this difficult. I would replace
```solidity
  function placeBid(address bidder, uint value) internal
          returns (bool success)
```

with

```solidity
  internal function placeBid(address bidder, uint value)
          returns (bool success)
```

For what it's worth, I would also treat the `payable` keyword the same. I would replace:

```solidity
uint public value;
address payable public seller;
address payable public buyer;
```

with

```solidity
public uint value;
public payable address seller;
public payable address buyer;
```

This colocates the variable type with the variable name, which I find makes the code easier to read. `public payable address seller` reads much closer to regular english than `address payable public seller`.

## Specification

public access keywords, as well as `payable` are placed at the start of the line for both variable and function declarations. Function modifiers are kept as-is.

## Backwards Compatibility

This doesn't actually change functionality so there's no compatibility issue for code that's already compiled. The breaking change will apply to source code however. We could make things backwards compatible by allowing the access modifier to appear in either the old spot or the new spot at the start of the line, and deprecate the old format, but in general I think that if we're still not at version 1, now is a good time to make a change like this which will increase readability in the long run.

I'm not a long-time solidity user myself so I'm not sure if there's some hidden benefit I'm missing regarding these access modifiers but I think moving access modifiers to the start of a line makes the code much easier to read and understand. I'm not sure how great this repo's tolerance is for breaking changes right now, but I thought I'd raise this issue anyway. Thanks!

**Comment by cameel** [comment]
Hello! Thanks for taking the time to submit a well-though out proposal. I've seen people mention this from time to time but I think you're the first one to actually request this as a feature :)

Placing modifiers after a function is not unheard of as far as programming languages go. For example in C++ you can mark functions as `const` or `volatile` this way. It's not the most popular choice of placement but that does not make it necessarily bad. I think that people's opinions on this will depend strongly on what languages they're coming from.

The biggest reason for placing it after the function in Solidity is that it's where all the modifiers are. Singling it out would result in people asking why it's the only one you cannot place after the function :) You could argue that all modifiers could be placed in front (e.g. on a separate line like decorators in Python) but that's another discussion.

By the way, would you allow the new placement also for mutability modifiers (`view`, `pure`, `payable`)? If not, why? This seems like the logical next step so I'm sure that someone will request it if we allow it for the access modifiers.

I do agree that placing the access first in your examples makes them somewhat easier to read. I think this is mostly due to the fact that all your state variables are `public` and line up neatly so there's less visual noise. This will not always be the case. If access types were more varied, it would be less clear-cut:
```solidity
address private token;
address payable public recipient;
uint roundStart;
uint roundEnd;
uint public reward;
bool public ended;
mapping(address => Bid[]) private bids;
address highestBidder;
uint public highestBid;
```
vs
```solidity
private address token;
public payable address recipient;
uint roundStart;
uint roundEnd;
public uint reward;
public bool ended;
private mapping(address => Bid[]) bids;
address highestBidder;
public uint highestBid;
```

I think you do have a point here though - it's probably common to have only public and internal variables and they can be clustered together to benefit from this change. I'm just not sure if the benefit is big enough to justify a breaking change in the language.

And unfortunately I don't think accepting both placements is viable because it would make syntax for state variables of function types ambiguous (in Solidity you can have variables and parameters of external and internal function types). For example, would `public` in a state variable declared as `public function () f;` refer to access of the function or the variable?

In case of function type state variables I think that readability actually decreases. For example an internal state variable of external function type now can  look like this:
```solidity
contract C {
    function (uint, bool) external view returns (uint) internal f;
}
```

and would turn into this instead:
```solidity
contract C {
    internal external function (uint, bool) view returns (uint) f;
}
```

Note that specifying `internal` for both state variables and for function types is optional (it's the default). This could be solved without ambiguity in the syntax - because function types and state variables share only one access type (`internal`) - but I think it would still look ambiguous to humans. For example this would be a private state variable of internal function type (modifier applies to the **variable**):
```solidity
contract C {
    private function (uint, bool) view returns (uint) f;
}
```
And this would be an internal state variable of external function type (modifier applies to the **type**):
```solidity
contract C {
    external function (uint, bool) view returns (uint) f;
}
```

Overall I think that there's no inherent problem with the current syntax and changing it now is too much trouble for too little benefit. It's just my personal opinion though and it would be interesting to hear what others on the team and other users think about this.

**Comment by jesseduffield** [comment]
@cameel very good points. 

> By the way, would you allow the new placement also for mutability modifiers (view, pure, payable)? If not, why? This seems like the logical next step so I'm sure that someone will request it if we allow it for the access modifiers.

I'm not 100% confident in my response but I would say yes, mutability modifiers would also be pulled to the front, but user-defined modifiers would remain where they were. I think that it's useful to see view/pure/etc before the rest of the function signature because it gives more context to prepare your brain for when you read the function name/inputs/outputs. You could make the argument that user-defined modifiers also provide good context, but I find they make a lot more sense after you see the function name and inputs/outputs. But I recognise the argument that user-defined modifiers and builtin modifiers are both just modifiers so should be colocated.

We can resolve the issue of state variables of function types by having the variable name come before the type like so:

```solidity
public payable beneficiary address; // this actually reads like regular english more so than the example in the OP
public biddingEnd uint;
public revealEnd uint;
public ended bool;

public bids mapping(address => Bid[]);
public highestBidder address;
public highestBid uint;

pendingReturns mapping(address => uint)
...
contract C {
    internal f external view function (uint, bool) returns (uint);
    private f2 view function (uint, bool) returns (uint);
    f3 external view function (uint, bool) returns (uint);
}
```

Come to think of it, I actually prefer this arrangement to the original proposal in terms of giving the reader the best context. I think it's better to see something like 'public payable' first, so that when you come across 'beneficiary' it makes sense, and then when you come across 'address' it makes even more sense.

With that said, I understand if you believe it's too big a breaking change to justify!
