### ISSUE TITLE
Equality operator for external functions

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12411]
## Abstract
Currently the equality operator only works with internal function types. It should be allowed also for external function types.

## Motivation
The way you compare function pointers today is not intuitive. For external ones you can only compare serialized values (e.g. `keccak256(abi.encodePacked(f))`) and using `==` and `!=` is disallowed. For internal ones the opposite is true. It would be much more intuitive to have one method that works uniformly with both.

The main reasons not to allow easy comparison with `==` for some types are that (1) it could potentially hide a very costly operation (e.g. when comparing arrays) or (2) it would be ambiguous (e.g. shallow comparison of references vs deep comparison of content). I think that none of these applies here. External function pointers have fixed size and the address+selector combination is enough to uniquely identify an external function without ambiguity.

Serialization also makes the comparison unnecessarily costly. The `keccak256()` + `abi.encode()` combination allocates memory and this allocation has been notoriously hard to optimize out so far (#12335).

### Example of current behavior
```solidity
contract C {
    function () external externalStorage;

    function comparePtr() public {
        function () external externalLocal1;
        function () external externalLocal2;

        externalLocal1 == externalLocal2;
        externalLocal1 != externalLocal2;

        externalLocal1 == externalStorage;
        externalStorage != externalLocal2;
    }
}
```
```
Error: Operator == not compatible with types function () external and function () external
 --> test.sol:8:9:
  |
8 |         externalLocal1 == externalLocal2;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Operator != not compatible with types function () external and function () external
 --> test.sol:9:9:
  |
9 |         externalLocal1 != externalLocal2;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Operator == not compatible with types function () external and function () external
  --> test.sol:11:9:
   |
11 |         externalLocal1 == externalStorage;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Operator != not compatible with types function () external and function () external
  --> test.sol:12:9:
   |
12 |         externalStorage != externalLocal2;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Specification
`f == g` and `f != g` should not cause a compilation error if `f` and `g` are external functions (or variables of an external function type) with the same signature. The comparison should always return `false` if they belong to different contracts. If should return `true` if and only if both the address and the selector are identical.

## Backwards Compatibility
The change is fully backwards-compatible because such comparisons are currently disallowed and result in a compiler error.

**Comment by chriseth** [comment]
Let's do it.

**Comment by chriseth** [comment]
Hints for implementation:
 - change `TypeResult FunctionType::binaryOperatorResult` to also work for Kind::External (note that the size on stack should be 2 in that case) - it should not work if either of the functions is bound (there is a member function to check this).
 - modify the old code generator: `ExpressionCompiler::appendCompareOperatorCode` needs a new case for external function types. Note that this has to compare two stack items with two other stack items:
   The stack will look like <fun1_addr> <fun1_selector> <fun2_addr> <fun2_selector>
   In order to compare you need to swap fun2_selector with fun1_addr to move fun1_addr up. You can use swap3 for that. Then use eq for the comparison, swap a bit more, compare again and combine the comparison results using and.
- modify the new code generator: `IRGeneratorForStatements::visit(BinaryOperation const& _binOp)` again needs a case for external functions. The new code generator generates yul code as text. Because external function types have two stack slots, you need to write code that is very different from the existing code. It is probably best to define a new utility function in YulUtilFunctions that takes four arguments: `checkExternalFunctionsEqual(leftAddr, leftSelector, rightAddr, rightSelector) -> result` and use that instead of the built-in `eq` when assigning to `expr`.

Things to check: In the old code generator, the addresses can have dirty higher oder bits. We have to make sure they are cleared before the comparison. This is usually done in `ExpressionCompiler::visit(BinaryOperation const&`,  which calls `acceptAndConvert` with 'cleanup' set to true - check that it actually performs the cleanup and add a semantic tast that uses inline assembly to create dirty higher order bits (others can help you there)
