### ISSUE TITLE
Wrong stack construction.

### ISSUE THREAD

**Issue by freaker2k7** [ethereum/solidity#12518]
## Description

The stack is built wrong!!!

Dear Vitali,

You mate the stack enter a function before checking/parsing the arguments.

## Environment

- Compiler version: 0.8.11
- Target EVM version (as per compiler settings): 0.8.11
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: blockchain
- Operating system: MacOS

## Steps to Reproduce

I have the following code in my contract:

```
	function slot(address user, address[] memory _helpers, address affiliate, string[] memory chains) external {
		uint8 plan = USERS.getUserPlan(user);
		USERS.setUser(WPEG, ROUTERS, dev, _helpers, CA, affiliate, user, CHAIN_STR, address(0), chains, plan, block.timestamp);
	}
```

Now this works while the following throughs me a "stack to deep":

```
	function slot(address user, address[] memory _helpers, address affiliate, string[] memory chains) external {
		USERS.setUser(WPEG, ROUTERS, dev, _helpers, CA, affiliate, user, CHAIN_STR, address(0), chains, USERS.getUserPlan(user), block.timestamp);
	}
```

Which means you parse from the inside out. That's a vital mistake!

**Comment by ekpyron** [comment]
The stack construction is not "wrong" per se, it just works as it does by convention and any convention will cause issues in some particular cases. The underlying issue is that the EVM only allows access to 16 stack slots, which we can only try to circumvent on the language level.
In general, "stack too deep" errors are known issues and we are working on mitigating them as far as possible.
You can try using the latest version of the compiler and compile using the experimental "via-ir" pipeline and enable the optimizer (i.e. ``--experimental-via-ir --optimize``) - we expect fewer stack-too-deep errors to occur in that compiler mode.

Since the general issue of stack too deep errors is tracked elsewhere (https://github.com/ethereum/solidity/issues?q=is%3Aissue+is%3Aopen+stack+too+deep+), I'm closing this.
