### ISSUE TITLE
Allowing the usage of `type` on non-primitive types

### ISSUE THREAD

**Issue by barakman** [ethereum/solidity#12526]
My motivation is slightly more than just allowing something like `type UintArray is uint256[]`, so I will explain by code.

I have something like this:
```
library Lib1 {
    function funcA(uint256[] memory x, uint256[] memory y) internal pure returns (uint256[] memory z) { ... }
    function funcB(uint256[] memory x, uint256[] memory y) internal pure returns (uint256[] memory z) { ... }
    function funcC(uint256[] memory x, uint256[] memory y) internal pure returns (uint256[] memory z) { ... }
    ...
}
```
And for obvious reasons, I want to change it to something like this:
```
struct Obj {
    uint256[] data;
}

library Lib2 {
    function funcA(Obj memory x, Obj memory y) internal pure returns (Obj memory z) { ... }
    function funcB(Obj memory x, Obj memory y) internal pure returns (Obj memory z) { ... }
    function funcC(Obj memory x, Obj memory y) internal pure returns (Obj memory z) { ... }
    ...
}
```
My current solution is to wrap `Lib1` inside `Lib2`:
```
import "./Lib1.sol";

struct Obj {
    uint256[]
}

library Lib2 {
    function funcA(Obj memory x, Obj memory y) internal pure returns (Obj memory z) { z = Obj(Lib1.funcA(x.data, y.data)); }
    function funcB(Obj memory x, Obj memory y) internal pure returns (Obj memory z) { z = Obj(Lib1.funcB(x.data, y.data)); }
    function funcC(Obj memory x, Obj memory y) internal pure returns (Obj memory z) { z = Obj(Lib1.funcC(x.data, y.data)); }
    ...
}
```
But this has two downsides:
1. Minor: code duplication
2. Major: higher gas cost

I believe that `uint256[]` and `struct Obj { uint256[] data; }` have the exact same memory-layout.
Moreover, I believe that they also have the exact same ABI-encoding.
If so, then there should be a way to achieve my goal without the two downsides mentioned above.

Ideally, the Solidity language could simply support something similar to `typedef uint256[] struct Obj` in the C language.
However, the `type` keyword does not seem to support this for non-primitive types.
Is there any other way (assembly, etc)?

Thank you.

**Comment by ekpyron** [comment]
The ABI type of ``strict Obj { uint256[] data; }`` is ``(uint256[])``, i.e. an unary tuple of ``uint256[]``. That's distinct from ``uint256[]`` and will have a different encoding: there will be an additional indirection in the encoding, i.e.
``0x20, 0x20, 1, 42`` is an ABI encoding of ``Obj`` with ``data`` of length 1 with one entry of value ``42``, while
a simple array of length 1 with one entry of value ``0x42`` is merely encoded as ``0x20, 1, 42``.

We only recently introduced "user-defined value types" using the ``type MyUint is uint256;`` syntax - it is well possible that we will extend this to support non-value types (e.g. structs and arrays) in the future, but since the support for user-defined value types is not even complete yet, it may take a while until we get there.

I'm not quite sure I understand the concrete reason for your encapsulation into a struct in your snippets - but that's the current state of the "typedef"'s I think you are requesting: it will probably happen eventually, but not in the immediate future.

**Comment by barakman** [comment]
@ekpyron: Thank you for the very quick response!

My concrete reason is for users of that library to be able to use `Obj` arguments instead of `uint256[]` arguments.

I've figured I could use `struct Obj { uint256[] data; }` without any runtime impact (including gas-cost).

But since the ABI-encodings are not identical, as you've just explained, I now understand that replacing `uint256[]` with a `Struct Obj { uint256[] data; }` would increase the gas-cost.

So going back to my original goal - passing `Obj` arguments instead of `uint256[]` arguments, **regardless of what `Obj` is** - I guess that the only way is by allowing `type Obj is uint256[]`.

Is that correct, or do I have any other way to achieve this goal?

**Comment by ekpyron** [comment]
To me it very much sounds like you need ``type Obj is uint256[];``, i.e. user-defined types that go beyond value-types, yes. Which is on our agenda, but I wouldn't expect it to be available in the immediate next releases.
But we're working on improving this and will get to more complete support for arbitrary user-defined types with custom operators, etc, eventually :-).

**Comment by barakman** [comment]
Thank you very much!

**Comment by cameel** [comment]
Isn't this a duplicate of #1100?

**Comment by barakman** [comment]
@cameel @chriseth : any word on this?
