### ISSUE TITLE
Syntax to explicitly indicate security properties of function calls

### ISSUE THREAD

**Issue by maurelian** [ethereum/solidity#12538]
## Abstract

Very little can be inferred about the effects of a function call simply by observing it in place. Adding symbols to function calls to indicate 'impure' behaviors would make it easier to review and audit solidity.

## Motivation

Solidity's built-in [visibility specifiers](https://docs.soliditylang.org/en/latest/cheatsheet.html#function-visibility-specifiers) and [modifiers](https://docs.soliditylang.org/en/latest/cheatsheet.html#modifiers), are a simple and powerful security feature of the language. These keywords also have the benefit of conveying a lot of information to the reader about the safety of a function. However they are only visible at the point of the function's definition. In many cases the reader will simply make assumptions about the functions behavior based on its name and context (ie. `setX` needs attention, `getX` is probably benign, but this is not guranteed). 

This issue proposes to enforce a minimal but explicit syntax at the point of a function call which would convey safety information to the reader, and help guide readers/auditors towards which functions require further information. 

A specific example of where this feature would help is outlined in by @samczsun's article [The Dangers of Surprising Code"](https://samczsun.com/the-dangers-of-surprising-code/). The bug results from the assumption that `_safeMint()` is the safer option, when in fact it introduces an external `CALL` leading to a reentrancy vuln. Despite being published over 6 months ago, the [same bug](https://twitter.com/maurelian_/status/1482214808116211713) is [being found](https://twitter.com/onewayfunction/status/1482216770735800324) on a regularly basis.

## Specification

A simple example of one approach, based on the experimental [SmartLang](https://consensys.net/diligence/blog/2020/05/an-experiment-in-designing-a-new-smart-contract-language/), which was in turn inspired by a [convention in scheme](https://schemers.org/Documents/Standards/R5RS/HTML/r5rs-Z-H-4.html#%_sec_1.3.5).

```solidity
function getsSomething() view public returns(uint) {
	return x;
}	
function setsSomething(uint _x) public {
	x = _x;
}	
function callsSomething() public {
	address(x).call();
}
function example() public {
  uint y = getsSomething();

  !setsSomething(x+1);

  $callsSomething();
}

```

There are certainly more situations to consider than the above. I won't try to be exhaustive, but off the top of my head: 
* At the site of a call to an external function, one cannot always make guarantees about everything that function does / does not do. IMO this feature should only be applicable to internal function calls.
* Should the author be able to modify the function being called based on which symbol they use (ie. prevent a function from making an external call by leaving out the `$`. I'd say no, there should only be one correct way to write the function call. 

Additionally the `$callsSomething();` syntax is notable in that there is no function specifier which restricts/allows the ability to make an external call. I think that would also be a nice feature, but I assume it's already been suggested somewhere. 

## Backwards Compatibility

Older codebases would require updating to comply.

**Comment by 0xsublime** [comment]
A specifier (like `view` or `payable`) might also be enough to avoid this problem. Let's say that a function which may call an external contract, directly or through a subroutine, must have the `interaction` specifier on it. 

In the case of `_safeMint` I think the reason this happens is that the actual external call happens in a subroutine several layers down. A dev looking at `_safeMint` may reasonably expect that it doesn't contain an interaction. My I see this commonly with reentrancy vulnerabilities, that they stem from an external call deeper in the stack.

I think a crutch for any implementation of this feature is that there are trusted and untrusted contracts. If you write functions that call trusted contracts within your protocol, then you will need to mark them with a symbol or a word, but that will not alert you to whether you also make *untrusted* external calls in the same function. Separating trusted from untrusted calls in the type checks should be possible but may not be feasible from a UX perspective, and may be too much of a hassle to implement. So we would have to live with this crutch I think.

**Comment by hjorthjort** [comment]
A specifier (like `view` or `payable`) might also be enough to avoid this problem. Let's say that a function which may call an external contract, directly or through a subroutine, must have the `interaction` specifier on it. 

I think a specifier would be enough, because in the case of `_safeMint` the reason devs make this mistake is that the external call happens in a subroutine several calls down the stack. A dev looking at `_safeMint` may reasonably expect that it doesn't contain an interaction. I see this commonly with reentrancy vulnerabilities, that they stem from an external call deeper in the stack. 

For a backwards compatible implementation, the default could be that a function is an `interaction`, and we add a keyword for the other case. This would be similar to how `view` and `pure` works. But I can't think of a good descriptive keyword that doesn't cause confusion with `internal` or other software concepts, or isn't bulky. For example:

* `noninteractive` (bulky)
* `local` (confusion with `internal`, common keyword in other languages, different meaning)
* `inhouse`: (confusing with `internal`, bulky)

I think a crutch for any implementation of this feature is that there are trusted and untrusted contracts. If you write functions that call trusted contracts within your protocol, then you will need to mark them with a symbol or a word, but that will not alert you to whether you also make *untrusted* external calls in the same function. Separating trusted from untrusted calls in the type checks should be possible but may not be feasible from a UX perspective, and may be too much of a hassle to implement. So we would have to live with this crutch I think.

**Comment by maurelian** [comment]
> a function which may call an external contract, directly or through a subroutine, must have the `interaction` specifier on it.

I like that idea (as noted towards the end of my initial post). But IMO that's a sufficiently different feature that it would merit a new issue, though I'd be somewhat surprised if it hasn't been requested before.

**Comment by hjorthjort** [comment]
Here's a relevant existing discussion: #10422

**Comment by maurelian** [comment]
I prefer this one: https://github.com/ethereum/solidity/issues/9248
