### ISSUE TITLE
Getting "TypeError: This variable is of storage pointer type and can be accessed without prior assignment, which would lead to undefined behaviour.", when initializing Array of struct inside struct.

### ISSUE THREAD

**Issue by miketanto** [ethereum/solidity#12549]
### **Is there anyway to initialized a Struct which contains an Array of Structs?**

For context the pragma being used is pragma solidity 0.8.6
The structs in question look like this:
```solidity
    struct MarketSale{
      address seller;
      address owner;
      uint256 price;
    }
  struct MarketItem {
          uint itemId;//Make it a one-to-one mapping with nftContract and tokenID
          address nftContract;
          uint256 tokenId;
          uint256 currentPrice;
          MarketSale[] saleHistory;
          uint256 saleIndex;
          ItemCategories category;
          bool listed;
          address creator;
          address currentOwner;
      }
```
the problem lies when trying to initialize the MarketItem struct with this code:
```solidity
 
    MarketSale[] storage _saleHistory;
    MarketSale memory sale = MarketSale(address(0),address(msg.sender),0)
    _saleHistory.push(sale);

    //One-to-one mapping itemId to item
    idToMarketItem[itemId] =  MarketItem(itemId, nftContract, tokenId,0,_saleHistory,0,ItemCategories(category), false, address(msg.sender),address(msg.sender));
```

When getting compiled it returns: 
TypeError: This variable is of storage pointer type and can be accessed without prior assignment, which would lead to undefined behaviour.

### **Are there any suggestions on how to go about this?**

**Comment by ekpyron** [comment]
A local variable like ``MarketSale[] storage _saleHistory;`` needs to actually point to a proper state variable (otherwise where in storage would you expect the array to be stored? Only state variables are assigned actual storage slots.).
So for example:
```
contract C {
  struct MarketSale { ... }
  MarketSale[] storage saleHistory;
  function f() public {
    MarketSale[] storage _saleHistory = saleHistory; // now the local variable points to an actual state variables in storage.
    MarketSale memory sale = MarketSale(...);
    _saleHistory.push(sale);
  }
}
```

In case you don't want the array to actually be permanently stored in storage, you need to make it an ``memory`` array and create it with ``new``.

Also note that this bug tracker is not a general support forum for the language use, but rather meant to track bugs in the solidity compiler. A better place to ask questions about language use is for example the solidity chat channel on matrix https://matrix.to/#/#ethereum_solidity:gitter.im or gitter https://gitter.im/ethereum/solidity

**Comment by miketanto** [comment]
Thanks so much for the help! I'll definitely note to ask these questions on those other channels next time!

**Comment by krushangSk17** [comment]
have you found the solution???

**Comment by krushangSk17** [comment]
> Thanks so much for the help! I'll definitely note to ask these questions on those other channels next time!

please reply if you found any solution for making struct array inside the struct.

**Comment by camiinthisthang** [comment]
Hi! I was running into a similar problem and posted the question and answer here:
https://ethereum.stackexchange.com/questions/127954/using-memory-vs-storage-for-arrays-in-structs-in-solidity-qa
