### ISSUE TITLE
Support remappings.txt in LSP

### ISSUE THREAD

**Issue by christianparpart** [ethereum/solidity#12603]
Seems like vscode-solidity supports the remappings.txt format of dapptools now, too. It would make sense to adopt it then for our LSP server.

See: https://github.com/gakonst/dapptools-template/blob/master/remappings.txt

**Comment by cameel** [comment]
My proposal would be to make it a general feature (not just for LSP). We could add a CLI option for specifying remappings in a file, e.g. `--remappings=<path>` or (`--remappings-file=<path>` as proposed by @christianparpart on gitter). The file would have the same simple structure as `remappings.txt` (i.e. just a plain list of remappings, one per line). Since `remappings.txt` is getting some traction, we could make make it the default value for the LSP to reduce the amount of configuration needed (but IMO there should still be a setting to override it). For plain CLI I'd always require it to be specified explicitly and without it only accept remappings on the CLI as we do now.

This would not even be the first place where we support something like this. The `--libraries` option also accepts a file.

**Comment by chriseth** [comment]
We should be careful here. We have to avoid that the LSP behaves differently than the compiler itself. In addition to that, remappings should be less and less common now that we have include paths.

For now, I think it would be better to handle this mechanism inside the plugins instead of the LSP, at least until we have some more generic project configuration file that can be read by both the lsp and the compiler itself.

**Comment by hrkrshnn** [comment]
Foundry also uses `remappings.txt`. https://github.com/gakonst/foundry. A common template (https://github.com/ZeframLou/foundry-template) uses it, so I think `remappings.txt` will be prevalent.

**Comment by stevennevins** [comment]
It's worth mentioning that while the remappings.txt is still there in ZeframLou's repo, that I think foundry is moving away from it in favor of the foundry.toml file also in the repo: https://github.com/ZeframLou/foundry-template/blob/main/foundry.toml

**Comment by gakonst** [comment]
> My proposal would be to make it a general feature (not just for LSP). We could add a CLI option for specifying remappings in a file, e.g. `--remappings=<path>` or (`--remappings-file=<path>` as proposed by @christianparpart on gitter). The file would have the same simple structure as `remappings.txt` (i.e. just a plain list of remappings, one per line). Since `remappings.txt` is getting some traction, we could make make it the default value for the LSP to reduce the amount of configuration needed (but IMO there should still be a setting to override it). For plain CLI I'd always require it to be specified explicitly and without it only accept remappings on the CLI as we do now.
> 
> This would not even be the first place where we support something like this. The `--libraries` option also accepts a file.

Foundry maintainer here, I'd support this over a remappings txt given that it'd might be too specific / restrictive (and yeah we might not use the txt file as much in the future). We're OK with passing in remappings over CLI.
