### ISSUE TITLE
Confusing behaviour of running solc without selecting output.

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#12712]
I would expect that all compilers do real compilation, if a compiler gets called with a single source file. This works like this for `gcc`, `javac`, `clang` - so why not `solc`? Right now, if there was  no output explicitly selected, `solc` is just performing parsing, but no real compilation. If a user knows that behaviour, this behaviour may be totally ok. But it may cause some confusion, if someone is not fully aware of this. Maybe we should just prevent that such confusion arise.

One solution could be to define a default output mod - to force real compilation. Where someone could force the compiler to not select any default output with a special parameter command line parameter, e.g. `--no-output`

This behaviour is only visible, if something is going wrong during code generation (e.g. unimplemented feature error).

**Comment by aarlt** [comment]
Ok, after looking slightly deeper into this it looks like that those errors are totally expected.

I discovered this behaviour, when I was rewriting the import export tests. The compiler is just not doing anything (apart from parsing?), if no output was selected - it makes somehow sense, but it may create some confusions.

However, maybe we should then always select an output [here](https://github.com/ethereum/solidity/blob/develop/scripts/ASTImportTest.sh#L43), e.g. specifying `--bin`.

@cameel would you agree?

**Comment by aarlt** [comment]
Hmm.. but maybe this behaviour is too confusing.. wouldn't it be better to always run the full compiler? Maybe with default output flags, e.g. `--bin` is always selected as default.

@chriseth

**Comment by aarlt** [comment]
@cameel but I guess at least for the ast import/export it makes sense to not specify `--bin` because I guess it would slow down the tests a lot. So I think that the mentioned change for the ast import/export tests should not be done.

**Comment by aarlt** [comment]
@chriseth @cameel the current behaviour makes definitely sense. But at least I got confused ;)

**Comment by cameel** [comment]
> Where an `UnimplementedFeatureError` exception is thrown, if called with e.g. `--combined-json asm`.

Well, this is just an unimplement feature in the codegen. We already had this reported as a bug (e.g. #3446) and these issues were all closed. In the end this is going to be resolved when we add `copyof` (#2435).

I do think that just throwing an ICE is not very user-friendly. I think we should either detect this in the analysis and report a normal error or have a way to report unimplemented features as errors during the codegen phase. I'd report this specifically as a separate issue (feature request?) though. We'd need to add it to the design backlog and discuss it first.

> The compiler is just not doing anything (apart from parsing?), if no output was selected - it makes somehow sense, but it may create some confusions.

This was intentional. See #11895. Daniel used to complain that we pointlessly run the old codegen even if we don't use its results and at some point he just went and changed it. I think it's a good change. If we're not printing the output then there's really no point.

> However, maybe we should then always select an output [here](https://github.com/ethereum/solidity/blob/develop/scripts/ASTImportTest.sh#L43), e.g. specifying `--bin`.

True, I think this part was written with the assumption that the compiler does the full compilation, all the way down to the bytecode, even without `--bin`. So I'd add `--bin` there.

It was not really about performance so I would not worry about the additional overhead of `--bin`. Just that the test does what was intended.

**Comment by cameel** [comment]
I adjusted the title - it's not really related to `--combined-json`, but to the array copying. It's just that the ICE does not show up unless you select an output that triggers the codegen - as you noticed yourself.

**Comment by aarlt** [comment]
Just for the record: I got confused, because it looked like that `solc contract.sol` was able to compile everything correctly, where in contrast to this `solc --combined-json bin contract.sol` throw an error. So I had the impression that only because of `--combined-json` the compiler had a problem. But in reality `solc contract.sol` was only parsing the contract and never really compiling.

**Comment by cameel** [comment]
Yeah, it's an easy mistake. I actually fell into this trap myself :) Not long after this was implemented I wasted some time debugging what I thought was a serious codegen issue. There was an ICE but not always so I thought that in some cases the codegen would not trigger it and instead continue, generating wrong bytecode. Turned out I was just comparing different runs, some of which were using outputs that trigger the codegen and others weren't :)

**Comment by aarlt** [comment]
> I adjusted the title - it's not really related to `--combined-json`, but to the array copying. It's just that the ICE does not show up unless you select an output that triggers the codegen - as you noticed yourself.

I think this issue should be more about the confusion. Not sure whether it makes sense to do anything with it. Maybe we should discuss something like a default output mode, so that the whole compiler runs if it got only a contract was supplied. Maybe we could add something like `--parse-only` or `--no-output`, that is the same behaviour as right now with no output-mode selected.

> Yeah, it's an easy mistake. I actually fell into this trap myself :) Not long after this was implemented I wasted some time debugging what I thought was a serious codegen issue. There was an ICE but not always so I thought that in some cases the codegen would not trigger it and instead continue, generating wrong bytecode. Turned out I was just comparing different runs, some of which were using outputs that trigger the codegen and others weren't :)

Maybe we should do something to prevent such confusions. I guess everyone who was not fully aware that not the full compiler runs, will be confused for a moment. And in the worse case invest a lot of time.

I will change the title that is more reflecting the confusion of not running the full compiler, if only the contract was given.

**Comment by aarlt** [comment]
I labeled this with "annoys users", even that is probably not the case. Maybe we should add a label "confusing behaviour".

**Comment by cameel** [comment]
Fair enough. The new title makes sense too. I'm not sure if it would really annoy users though. Probably annoys only compiler developers :) This problem is limited to situations where you get an ICE in at the codegen stage and want to reproduce it. As a user I'd probably consider the fact that it does not crashes in situations where it would otherwise to be a good thing.

As for default output - there is already a kind of default output - it's compilation errors and warnings. For me that's the most common thing I want to see and the fact that there's not much printed when there are no errors is a good thing to me. I suspect this might also be true for the few users who actually use the compiler's CLI directly and not a framework or an IDE.

**Comment by aarlt** [comment]
Basically I would just expect that all compilers do real compilations, if a compiler was called with a source. This works like this for `gcc`, `javac`, `clang` - so why not `solc`?

And yes, we need another label.. maybe "confusing" :)

**Comment by chriseth** [comment]
Please either close this issue or corrects its title or description. What is the confusing behaviour and how to fix it?

**Comment by cameel** [comment]
But GCC or Clang do not print the compiled program to stdout :) You'll get output just as terse as from solc when there are no compilation errors. They'll create an `a.out` file automatically but I'm not sure it's really better than solc's behavior. I see it more as a historical artifact that can't be changed due to compatibility.

**Comment by aarlt** [comment]
> But GCC or Clang do not print the compiled program to stdout :) You'll get output just as terse as from solc when there are no compilation errors. They'll create an `a.out` file automatically but I'm not sure it's really better than solc's behavior. I see it more as a historical artifact that can't be changed due to compatibility.

Yes, that's true :) my main point is basically that invoking the compiler does not actually run the (full) compiler. 

However, another option would be to generate an error/warning (e.g. "warning/error: no output selected, parsing only"), if no output was selected. I think an error would be better - because it will exit with != 0. An explicit `--no-output` would then just behave as right now without having compiler output selected (also returns with exit code of 0, if everything went good).

**Comment by aarlt** [comment]
All this only happens if the compiler hits an unimplemented feature error (and maybe similar errors) during code generation. So maybe it makes no real sense to take care of this. The majority of users will never see this behaviour.

**Comment by cameel** [comment]
> my main point is basically that invoking the compiler does not actually run the (full) compiler.

It's not a bug, it's a feature :P I wonder what @ekpyron things about this one.

**Comment by ekpyron** [comment]
Well, the idea is that anything that passes analysis should go through full compilation without error - so in that sense any case in which that's false (be it due to unimplemented feature errors or any other assertion) is its own bug :-).

We did in fact change this intentionally, since there actually is no unique choice for running actual compilation: e.g. if we run the legacy pipeline, we get unimplemented assertions that won't occur during IR code generation.

When we changed this, another point was that standard-json has worked like this and changing CLI to do the same made them consistent.

All that being said, especially with unpredictable stack-too-deep assertions during codegen, only realizing them when actually requesting output can of course be annoying, but I don't see a nice way around that (the stack-too-deep errors in particular depend on the chosen backend and settings...).

**Comment by cameel** [comment]
> standard-json has worked like this and changing CLI to do the same made them consistent.

True, I think this in particular is a good point.

**Comment by aarlt** [comment]
> standard-json has worked like this and changing CLI to do the same made them consistent.

ah interesting! what output is selected for standard-json as default (and what are other default settings)?

**Comment by cameel** [comment]
I never checked but from @ekpyron said I assume there's just no output selected?

**Comment by ekpyron** [comment]
No particular output artifacts are selected by default. However it will always parse and analyze and report warnings and errors. But it only actually runs code generation if https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/StandardCompiler.cpp#L259 returns true, i.e. some bytecode-ish artifact is explicitly requested. So pretty much how CLI works since the change.
