### ISSUE TITLE
Consider exposing ``evmasm::disassemble`` in ``tools/`` as a "poor man's disassembler".

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12753]
Came up in https://github.com/ethereum/solidity/issues/12738
It would have been quicker to determine the cause of that, if we had a simple tool to translate binary bytecode to an opcode list.
And we do have ``evmasm::disassemble`` anyways for the compiler's ``--opcodes`` output.

Specification:
Add a simple tool in ``tools/`` that reads a hex string from stdin and writes the result of ``evmasm::disassemble(util::fromHex(stdinContent), "\n")`` to stdout.

The result will not really be a good disassembler, since it won't resolve tags or anything fancy, but it'd still help in diffing binary bytecode.

**Comment by hrkrshnn** [comment]
> it'd still help in diffing binary bytecode.

Just want to mention that the `evm` executable from geth (https://github.com/ethereum/go-ethereum#executables) is also useful for this. `evm disasm file.txt`

**Comment by ekpyron** [comment]
Yeah, there are a lot of other ways to do this - still, since we have the function anyways, there's little harm in making it a little tool in our repo as well...

**Comment by hrkrshnn** [comment]
One cool use case for this would be to expose https://github.com/ethereum/solidity/blob/develop/libevmasm/ControlFlowGraph.h, i.e., a simple CFG out of the disassembled code. IIRC, that piece is code is unused currently (due to function pointers messing with the analysis).

The downside is additional maintenance, and these tools may not be widely used.

**Comment by ekpyron** [comment]
Let's close this, we won't do it any time soon.
