### ISSUE TITLE
allow specifying a function should be inlined in the signature

### ISSUE THREAD

**Issue by moodysalem** [ethereum/solidity#12782]
many internal functions are so small that they should be inlined to avoid a jump

perhaps the solidity optimizer should handle this with a large number of runs, but some functions are expected to be run much more than others.

it would be nice to be able to control whether a function is inlined where it's called at the callsite or in the function signature

**Comment by cameel** [comment]
I cannot find an issue covering this but I think it was discussed before. I only see #10938, which is about improving the inlining in the optimizer.

Overall, I remember that our position was that we want to make inlining heuristics better, not drop the responsibility on the users. In most cases the compiler is in a better position to make that decision. There are of course situations where you're hand-optimizing a specific piece of code and you'd make a better decision, but we prefer to focus on getting the optimizer better rather than on adding syntax for fine-tuning it, which complicates the language.

Having said that, I agree that there's a lot to improve here. The biggest reason why it isn't more aggressive right now are the "Stack too deep" errors. Inlining in most cases increases stack pressure so you're more likely to run into them. Work on that has been going for quite a while and we're actually reaching the point where we're considering relaxing the conditions for inlining, at least for the new code generator. See #12731.

Another obstacle was that it was hard to evaluate how much the change will affect real projects. That's also something we have taken care of - we now have a more extensive set of projects to benchmark against, including Uniswap - so you can expect more progress on that front.

**Comment by toongeorges** [comment]
I see the problem with "Stack too deep" errors, though would it not be possible to check if an internal/private function only uses variables that are passed as argument or not?

If a function only uses variables that are passed as argument, inlining this function should be straightforward?  If so, a function that is only used once could always be inlined.

**Comment by cameel** [comment]
@toongeorges Maybe. Hard to say up front if it'll be worth it - I think that such functions are small in most cases and we're already inlining functions smaller than 6 or 8 lines of Yul code (as long as nothing else prevents it) - but it's an interesting idea and seems doable at least. You could submit it as a feature request and we'll consider it when extending the inliner. But as a separate issue - this one is about syntax for inlining.

**Comment by toongeorges** [comment]
I created the issue #13248

**Comment by CJ42** [comment]
This would be a great feature for the Solidity language, as it could allow better code maintenance and readability while benefiting the runtime code for runtime cost and efficiency.

Voting to get this open again.

**Comment by iFrostizz** [comment]
Would lean towards having the inlining directive when calling the function instead of in the function signature, even if it's better than nothing.
Inlining might be appropriate for scenarios where runtime matters more than code size but they should not obligate the caller to inline the function, for instance when importing a library, it would be pretty annoying and could lead to contracts exceeding the maximum size if that cannot be controlled. Why don't we add a comment before like

```solidity
/// solidity:inline-func
myInternalFunction();
```
