### ISSUE TITLE
Internal getters for mappings

### ISSUE THREAD

**Issue by 134dd3v** [ethereum/solidity#12816]
## Abstract

The following method exists:

```solidity
function implementedMethod(
        function(int16) view returns (uint256) self,
        int24 someArgs
) internal view returns (int24 someReturnValues) {
        // .... logic
}
```

Now I want to use the above method to implement:

```solidity
 function overloadedMethod(
        mapping(int16 => uint256) storage self,
        int24 someArgs
) internal view returns (int24 someReturnValues) {
        return implementedMethod(mappingToFunction(self), someArgs);
}

function mappingToFunction(
        mapping(int16 => uint256) storage self, 
        int16 val
) internal returns (function(int16) view returns (uint256)) {
        return function (int16 val) internal {
                return self[val];
        };
}
```

The above code doesn't work obviously, but is it possible to convert mapping into a view function?

## Motivation

Mappings are sort of like view functions with one input and one output. So there should be a way to cast a mapping type into a view function.

## Specification

```solidity
mapping(typeA => typeB) hello;

hello.toFunction // type of this should be function(typeA) view returns (typeB)
```

The `toFunction` can be something else.

## Backwards Compatibility

No issue

**Comment by cameel** [comment]
So, basically, you'd like to have a way to ask the compiler to automatically generate an internal getter function for any mapping?

Note that currently you can do this with with external functions if your mapping is public (because the compiler generates a getter in that case):
```solidity
contract C {
    mapping(int16 => uint256) public map;

    function foo(function(int16) external view returns (uint256)) internal view {}

    function test() public {
        foo(this.map);
    }
}
```

With internal functions you can achieve this by defining the function yourself as long as you can access the original storage variable:
```solidity
contract C {
    mapping(int16 => uint256) map;

    function mapGetter(int16 key) internal view returns (uint256) {
        return map[key];
    }

    function foo(function(int16) view returns (uint256)) internal view {}

    function test() public {
        foo(mapGetter);
    }
}
```
If you only have a variable reference via a `storage` parameter, this is not currently doable but will be if we implement #12297.

> Backwards Compatibility
> No issue

There is an issue, at least with your proposed syntax. Due to `using for`, state variables can have arbitrary members and adding a special `toFunction` would conflict with that. We would have to reserve that name and that would be breaking.

---

Finally, can you describe your use case? We need to determine if this is common/useful enough that it would make sense to add special language support for it. What benefit would it have that defining a function manually (or using a closure after #12297) would not provide?

**Comment by cameel** [comment]
Actually, I think that one advantage over #12297 would be that this is much simpler to implement than closures in general. So the main issue is mainly how common is this - we need use cases.

**Comment by 134dd3v** [comment]
Just to mention the motivation I had for this: there's a method in Uniswap lib where they take [mapping as an input](https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/libraries/TickBitmap.sol#L42). However one cannot pass this kind of function `function(int16) view returns (uint256)`. 

Similarly if there's a function that accepts a function `function(int16) view returns (uint256)`, one cannot pass mapping to it with similar input and output types. While these both are different types, they sort of have similar i/o interface. Currently, it seems the only way is to just have two copies of same logic, which is done [here](https://github.com/Uniswap/v3-core/blob/d55e297b938e5b56fd1cf9fe668f5bd385be85b5/contracts/libraries/Simulate.sol#L166). Which may not be big deal but where ever we have two copies of same code in same repo, it looks bad. If the language can expose some features in the long term it would be awesome.
