### ISSUE TITLE
Overflow checks should not avoid overflow

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#12814]
I'm not totally sure anymore why we implemented overflow checks without using overflow, but I think we should change that and use the cheapest method possible.
I can think of two reasons:
1. it might be easier for a possible future reasoning engine in the compiler
2. it might be easier to detect overflow by external tools

The reasoning engine we currently have in mind should be powerful enough to deal with overflows. Furthermore, we make use of wrapping arithmetic in the optimizer rules already (subtraction is turned into addition for example).

**Comment by chriseth** [comment]
It looks like we can save 7 gas per addition:
```
let z := add(x, y)
if gt(x, not(y)) { revert(0, 0) }
```
wrt
```
let z := add(x, y)
if lt(z, x) { revert(0, 0) }
```

**Comment by cameel** [comment]
Just to clarify: you mean we should have used the `ovf` and `sovf` flags from [EIP-1051: Overflow checking for the EVM](https://eips.ethereum.org/EIPS/eip-1051)?

How do we access them at Yul level?

EDIT: I see that the EIP is stagnant so it's probably not this mechanism.

**Comment by ekpyron** [comment]
I think the main reason for doing the checks as they are done now, was that we expected a weaker reasoning engine to be able to deal with them more easily that way - but the plan back then was not to use any of this in production before the optimizer could remove most of the checks and to revisit how to do the check, when working on the optimizer to remove them...
Given how things turned out since then, it makes sense to hand-optimize them to the cheapest ones without optimization right now...

**Comment by ekpyron** [comment]
Anything left here?
