### ISSUE TITLE
install_deps.sh removed... replaced with what?

### ISSUE THREAD

**Issue by SolidStaker-fiefKing** [ethereum/solidity#12827]
## Page

[]
https://docs.soliditylang.org/en/v0.5.11/installing-solidity.html#dependencies-helper-script

## Abstract

Working with WSL 2, Docker, ubuntu 18.*, Win10 enterprise. Trying to run the helper script and one of the recent commits has a commit (see comment on file install_deps.ps1) and that commit states "removed install_deps.sh"... I tried several things and looked for what may have replaced "install_deps.sh" but could not find anything that would work.

The ps1 on my win10 seems to be working.

**Comment by cameel** [comment]
See #9582 for full context.

We removed the script because it was basically unmaintained. The commands to install dependencies are in most cases very simple and what the script was providing was really just a bit of encapsulated knowledge on what the right commands are for each system. It was failing at this simple task because we almost never recheck that these still work - we only actively test on some of these platforms in our CI and for the others it was a coin toss whether it would work or not. We think that users are better off running these commands on their own. We're open to adding more docs about installation on specific platforms if someone wants to submit a PR to clarify that, but we don't think maintaining such a script is a good idea long-term.

 In case of Ubuntu what the script was doing is more or less this:
```bash
apt-get update
apt-get install build-essential cmake git libboost-all-dev libz3-dev
```
