### ISSUE TITLE
Should `using` be applicable for interfaces and libraries?

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12830]
```solidity
// Bad interface
interface IERC20 {
    function safeTransferFrom(address from, address to, uint value) external;
}
library SafeTransfer {
    function safeTransferFrom(IERC20 token, address from, address to, uint value) internal {
        // do nothing
    }
}
// This type checks, but would produce an error when used
// Error: Member "safeTransferFrom" not unique after argument-dependent lookup in contract IERC20.
using SafeTransfer for IERC20;

contract C {
    // using SafeTransfer for IERC20;
    IERC20 constant token = IERC20(address(0));
    function stake(uint value) external {
        // uncomment to see the error
        // token.safeTransferFrom(msg.sender, address(this), value);
    }
}
```

**Comment by chriseth** [comment]
We retained the same mechanism that was in place already for "using" inside a contract.

**Comment by hrkrshnn** [comment]
The main issue now is that you can ship a file with a global using statement  and only realize at callsite that the statement cannot be used. I think we need to introduce more checks at the using statement definition.

Unfortunately, this would be a breaking change 😢

**Comment by hrkrshnn** [comment]
The decision was to break `using X for I` where `I` is interface or contract type. Will write a blog post regarding this.

**Comment by chriseth** [comment]
`using SafeTransfer for IERC20 global` turned out to be an unintended feature, i.e. a bug.

Whether or not we should disallow `using X for I` for interfaces and contracts should probably be discussed with more user feedback, but I personally tend to disallowing it.

Essentially: If there is a different way to define member functions for types, the other way should be used.
