### ISSUE TITLE
[Yul Optimizer] Optimized Contract crashes when it transacts

### ISSUE THREAD

**Issue by chamitro** [ethereum/solidity#12840]
## Description

Hello everyone,

in the contract below
```
contract n
{
        fallback(bytes calldata) external returns (bytes memory b)
        {
                uint x = 1;
                uint z = 1000;
                assembly {
                        for { b := 1 } b
                        {
                                x := add(mload(0x40),10020)
                                z := mload( add(20002039,x))
                                z := sload( add(28283, x))
                                mstore(add(b, 32), z)
                          } {}
                }
                return b;
        }
}
```
when it is compiled with solc 0.8.12 or 0.8.13 its is not deployed,
but when it compiler's with yul optimization it is deployed but hangs when it transacts and remix crashes.

## Environment

- Compiler version: solc 0.8.13
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: ubuntu 16.04

**Comment by chriseth** [comment]
Thank you for opening this issue!
Can you tell us a bit more about what you expect the compiler to do with your code?
The inline assembly in your code has an infinite loop, so whatever call you make to the contract, it will consume all gas.

What do you mean by "crash" and what do you mean by "it is not deployed"? I can successfully deploy the contract in remix using solidity 0.8.13.

**Comment by chamitro** [comment]
Hello,

this is a contract that is produced by my fuzzer, so the infinte for statement and part of the inline assembly code is produced with my fuzzer mutations. What I mean is that, when you try to run the unoptimized contract with an input (e.g. calldata 1A) then, the regular code will never run, while the optimzed one while run, consuming all the gas.

**Comment by chriseth** [comment]
What do you mean by "it will never run"? It runs out of gas for me as well as the optimized version. How exactly do you compile it and how to do you execute it?

**Comment by chamitro** [comment]
the optimized version when you try to transact with calldata 1A :

![2](https://user-images.githubusercontent.com/36297330/159954520-f270db50-b6e8-4a9f-a484-7f264932c9c4.png)

the unoptimized(regular) version when you try to transact with calldata 1A :

![1](https://user-images.githubusercontent.com/36297330/159955275-a6a2cbf6-cf8d-4411-8ae4-0878a50cae74.png)

**Comment by chriseth** [comment]
Ok, now I understand. The unoptimized version performs large memory accesses while the optimized version only accesses storage. I think this is rather a bug in remix than in solidity.

**Comment by chamitro** [comment]
but despite the large memory accesses shouldn't both contracts run at the end? I mean if an optimized contract can run, while the same regular contract can't, my intuition this that is a bug.
But of course I am not sure. What should be the expected outcome?

**Comment by chriseth** [comment]
They both run, but the optimized contract reaches the gas limit earlier - earlier in the sense of execution time not gas used. The reason is that storage access in remix is overpriced because it does not need to perform harddisk access.

**Comment by chamitro** [comment]
Ok, but you can see the execution and transaction cost before you make the transaction and put the gas limit higher than this. Despite that the same happens.

**Comment by cameel** [comment]
@CHM1993 What @chriseth meant here is that in Remix the gas cost of opcodes does not correspond well to how heavy they are to execute (as it would be the case if an Eth node executed them). Normally the storage access would be the most expensive operation because it involves disk. In Remix though even memory operations can be pretty heavy computationally compared to how cheap they are in terms of gas. In effect you can easily create a contract that will take Remix a lot of time to execute before it hits the gas limit (effectively making Remix hang).

I just did a simple experiment and managed to hang it with this simple code:
```solidity
contract C {
    uint x = 0;
    function foo() public {
        while (true)
            ++x;
    }
}
```

So due to this, the fact that the snippet from the description hangs Remix just means that Remix is not very efficient at executing it (perhaps it should be reported as a problem in Remix) but it does not seem to be an actual bug in the code produce by the compiler. An EVM running outside of the browser would probably not have any issues executing it.

**Comment by bshastry** [comment]
Should we close this issue since it appears to be Remix related?
