### ISSUE TITLE
Compiler is not evaluating all if/elseif/else branches to check for “Immutable variables cannot be initialized inside an if statement"

### ISSUE THREAD

**Issue by StErMi** [ethereum/solidity#12864]
## Abstract

Currently, solidity compiler is correctly raising an error if an `immutable` variable is initialized only inside one branch of an if/else statement.

The following contract will raise the following compiler error: “Cannot write to immutable here: Immutable variables cannot be initialized inside an if statement.”

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.13;

contract Immutable {
    uint256 public immutable iamImmutable;

    constructor(bool shouldInitWithZero) {
        if (shouldInitWithZero) {
            iamImmutable = 0;
        }
}
```

The same error is thrown also if the `immutable` variable is initialized in the `else` branch of the `if/else` statement.

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.13;

contract Immutable {
    uint256 public immutable iamImmutable;

    constructor(bool shouldInitWithZero) {
        if (shouldInitWithZero) {
            iamImmutable = 0;
        } else {
            iamImmutable = 1;
        }
    }
}
```

But it's **not thrown** if we use the ternary operator to initialize the variable

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.13;

contract Immutable {
    uint256 public immutable iamImmutable;

    constructor(bool shouldInitWithZero) {
        iamImmutable = shouldInitWithZero ? 0 : 1;
    }
}
```

## Motivation

The compiler error should be thrown **only** if the `immutable` state variable is not initialized **in all** the if/elseif/else branch.

## Backwards Compatibility

I don't think that there should be any backward compatibility problem.

**Comment by ekpyron** [comment]
Thank you very much for the issue, but we won't do this for two reasons:
- No analysis of whether an immutable is written in all cases is prefect, so rather than eliminating invalid cases, we'd just keeping to accumulate special casing (think ``constructor(bool hasPropertyA) { bool doesNotHavePropertyA = !hasPropertyA; if (hasPropertyA) immutable = 1; if (doesNotHavePropertyA) immutable = 0;``).
- It hides the actual *cost* of the operation. The write to the immutable operates on memory, not on stack, so we shouldn't encourage doing it more than once anyways.
- We will be replacing immutables by a code data location in the future, which will not have the "write-once" restriction in the constructor at all, which will implicitly address this issue.

For those reasons, I'm closing the issue for now. Feel free to comment, if you disagree.
