### ISSUE TITLE
RETURNDATACOPY opcode is not disallowed in pure functions

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#12860]
The main feature of a pure function is that it cannot read blockchain state, which includes not only reading storage but also things like accessing external contract code, checking balance, checking remaining gas, etc. There are also cases where this is not so clear cut, e.g. CODECOPY (#12260, #8153) but we tend towards disallowing that as well. Another such case is RETURNDATACOPY. It was recently pointed out that it should not be accessible in pure functions.

The fact that it's allowed should probably be considered a bug. Otherwise it's a breaking change.

## Environment

- Compiler version: 0.8.13

## Steps to reproduce
This code compiles just fine:
```solidity
function foo() pure {
    assembly {
        returndatacopy(0, 32, 64)
    }
}
```

While the same would not work with e.g. EXTCODECOPY:
```solidity
function foo() pure {
    assembly {
        extcodecopy(0, 0, 32, 64)
    }
}
```
```
Error: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
 --> test.sol:3:13:
  |
3 |             extcodecopy(0, 0, 32, 64)
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Extra information
Here's the full list of instructions currently disallowed in `pure` functions
https://github.com/ethereum/solidity/blob/c4909e99c1015233d6937d229058cde52615f246/libevmasm/SemanticInformation.cpp#L465-L520

**Comment by cameel** [comment]
@chriseth 
- RETURNDATASIZE should also be disallowed, correct? Anything else to disallow?
- Do we actually consider it a bug fix or should it be a breaking change like for CODECOPY?

**Comment by ekpyron** [comment]
This is a bit tricky...
```
contract C {
        function g() public pure returns (bytes memory) {
                return new bytes(32);
        }
        function f(C c) public pure returns (uint256) {
                bytes memory x = c.g();
                return uint256(bytes32(x[0]));
        }
}
```
This also works just fine right now... which is arguably fine (passing something as ``c`` that has a non-pure ``g()`` is possible and will allow for calling ``f`` "impure"ly, but maybe that's fine)...

And if that's fine, one could argue that ``returndatacopy`` and ``returndatasize`` are also just fine in pure functions...
What's really a problem is an external *call* to something, since that may not in fact be pure - but if everything that's called *is* pure, then using the returndata is a non-issue, is it?

All of that assuming the weaker notion of ``pure``, i.e. "externally pure", resp. "does not read state", rather than the stronger "can be compile-time evaluated" notion of pure...

**Comment by ekpyron** [comment]
Ah, well... actually further, it should probably only be allowed to use ``returndatacopy`` and ``returndatasize`` in a pure function *after* that very same pure function has made an external call... before an external call, it's quite non-pure...
Given that, it's probably true that we should disallow it entirely (even though it's implicitly possible using high-level mechanisms)...
