### ISSUE TITLE
Bug in ABI encoding empty storage array

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#12880]
The following function does ABI encoding of strings in storage. However, this has a bug when the string in storage is empty. If the string is short, it will still have an empty data that's part of the ABI. But that is not how empty strings are encoded in ABI.

https://github.com/ethereum/solidity/blob/c4909e99c1015233d6937d229058cde52615f246/libsolidity/codegen/ABIFunctions.cpp#L699-L703

For reference, the ABI encoder v1 version correctly encodes the data.
```solidity
// pragma abicoder v1;
contract C {
    string message;
    event Message(string);
    function emitMessage() external {
        emit Message(message);
    }
}
```
---
Found in https://github.com/gakonst/foundry/issues/1027#issuecomment-1079880060

The ABI encoding for the empty string should be  (48-bytes)
```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000000
```

but ends up being

```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by bshastry** [comment]
Can reproduce this with the Solidity fuzzer. However, I recall @ekpyron  telling me that `pragma abicoder v1;` is a source of false positives since the encoding is known to be different between legacy and new (abi v2) coders. So, the design decision I took was to disable generation of the `pragma abicoder v1;` since the new codegen would anyway ignore the directive and use `v2` instead and thereby produce false positives.

**Comment by bshastry** [comment]
From chat with @hrkrshnn 

```
contract C {
    string message;
    event Message(string);
    function emitMessage() external {
        emit Message(message);
        string memory tmp = message;
        emit Message(tmp);
    }
}
```

The problem seems to be that even abi coder v2 encodes the first emit call (`emit Message(message)`) and the second emit call (`emit Message(tmp)`) differently. The first encoding is longer one (see original post), the second encoding is shorter. However, both legacy and IR codegens produce the same set of encodings i.e., longer and shorter respectively.

**Comment by chriseth** [comment]
I see two ways to fix this:
1) add an `if` (or switch) inside the case 0 to check for zero length
2) do the mstore in case 0 ever for zero length (it does not hurt) and compute the offset for `pos` using something like `mul(0x20, iszero(iszero(length))` - or a cheaper version that does not use `mul`
