### ISSUE TITLE
Custom error is described as "function() pure" instead of "error" in error messages in case of explicit conversions

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum/solidity#12896]
## Description

Say we have a custom error defined like this in an interface:

```solidity
interface MyInterface {
    error MyCustomError();
}
```

The compiler mistakenly considers `MyInterface.MyCustomError` to be of type `function() pure` instead of type `error`. The latter is what should be used because that's what ends up being set in the ABI.

Casting `MyInterface.MyCustomError` to `bytes4` should work, but it doesn't:

> Explicit type conversion not allowed from `function() pure` to `bytes4`.

```text
Error:
   0: Compiler run failed
      TypeError: Explicit type conversion not allowed from "function () pure" to "bytes4".
        --> /path/to/my/test/file.t.sol:33:25:
         |
      33 |         vm.expectRevert(bytes4(MyInterface.MyCustomError));
         |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Environment

- Compiler version: v0.8.13+commit.abaa5c0e
- Target EVM version (as per compiler settings): default for v0.8.13
- Framework/IDE (e.g. Truffle or Remix): forge
- EVM execution environment / backend / blockchain client: HEVM (forge v0.2.0 (a0db055))

- Operating system: macOS v12.3.1

## Steps to Reproduce

```solidity
interface MyInterface {
    error MyCustomError();
}

contract MyContract {
    function myFunction() external {
        bytes4(MyInterface.MyCustomError);
    }
}
```

**Comment by chriseth** [comment]
Please provide a way to fix this if you mark this as "good first issue".

**Comment by PaulRBerg** [comment]
@chriseth it wasn't I who added that label. Or were you talking to @cameel?

**Comment by chriseth** [comment]
Yes, I was talking to cameel :)

**Comment by cameel** [comment]
Fair enough. I applied the label because I think this is just a matter of adding a special case for errors (and maybe also events) in [`TypeChecker::typeCheckTypeConversionAndRetrieveReturnType()`](https://github.com/ethereum/solidity/blob/v0.8.13/libsolidity/analysis/TypeChecker.cpp#L1753-L1876). 

Actually, instead of special-casing it in the type checker, maybe it's better to extend [`FunctionType::toString()`](https://github.com/ethereum/solidity/blob/v0.8.13/libsolidity/ast/Types.cpp#L3093-L3120) for errors and events. Not sure if that won't break someting (i.e. like formatting the type for AST/ABI output or something?) but if so, leaving it as is and instead adding a separate function that calls it and handles events and errors specially should still be safe.

In any case, this seems like a relatively simple, isolated change. Or am I missing something?

**Comment by chriseth** [comment]
toString should not be changed, that is used in signatures. We could introduce a new function in the class Type - `humanReadableName` for example, that by default just calls toString.

**Comment by StrongerXi** [comment]
I'd gladly take this issue, but to clarify things, which one (or both) do we want here?
1. Add a special case in [TypeChecker::typeCheckTypeConversionAndRetrieveReturnType()](https://github.com/ethereum/solidity/blob/v0.8.13/libsolidity/analysis/TypeChecker.cpp#L1753-L1876) to allow conversion from `FunctionType` with `Kind::Error`.
2. Add `Type::humanReadableName` which calls `toString` by default, and override it for `FunctionType` with `Kind::Error`.

**Comment by chriseth** [comment]
I would say 2 is enough, we don't need to explain why the conversion is not allowed - at least I wouldn't even know what to say.

**Comment by StrongerXi** [comment]
Hmm okay I'll send a PR for (2).

Although I saw this comment from the PR author so I thought we might want to support 1?

> Casting MyInterface.MyCustomError to bytes4 should work, but it doesn't

**Comment by cameel** [comment]
Thanks for pointing this out, I actually missed that part of the description.

This already works but not through a conversion. You can use `MyInterface.MyCustomError.selector`, which is already `bytes4`. @nishant-sachdeva is also currently working on adding that for events too (#12581). Not sure we really need an alternative mechanism for doing this. `.selector` should be more intuitive since it's how it works with functions and for functions we definitely do not want such a conversion.

**Comment by StrongerXi** [comment]
> .selector should be more intuitive since it's how it works with functions and for functions we definitely do not want such a conversion

I didn't know this before, and I totally agree. I was honestly quite confused when I first saw `bytes4(MyInterface.MyCustomError);`.

**Comment by StrongerXi** [comment]
How exactly do we want the error message to look here? 

```
1. Explicit type conversion not allowed from error to bytes4
2. Explicit type conversion not allowed from error function to bytes4
3. ...?
```

**Comment by ywon0925** [comment]
Hi, is this issue solved? 
If not, I would like to take the issue and solve by adding a special case in TypeChecker::typeCheckTypeConversionAndRetrieveReturnType() as @cameel mentioned.

**Comment by ywon0925** [comment]
Hi, is this issue solved by @StrongerXi ?
If not, I would like to take the issue and solve it by adding a special case in `TypeChecker::typeCheckTypeConversionAndRetrieveReturnType()` as @cameel mentioned.

**Comment by cameel** [comment]
> How exactly do we want the error message to look here?

If possible, I'd include the error name:
```
TypeError: Explicit type conversion not allowed from "error MyCustomError" to "bytes4".
```
though just `error` would still be better than describing it as a function.

@ywon0925 For now @StrongerXi seems to be interested in implementing it so you'll need to find a different task. To be honest we're currently getting more PRs that we can review and on top of that most of the team is out on a conference now so things are stalled. It would be most helpful to try to take over some of the older PRs and finish them. For example #12166 has been stalled for a long time now and is up for taking.

**Comment by ywon0925** [comment]
@cameel I was asking since it was marked as 'good first issue', but I'll take a look at other issues & PRs to see if there are any I could help with.
