### ISSUE TITLE
Rewrite command line test script cleanly in python.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#12897]
Came up in https://github.com/ethereum/solidity/pull/12851.
``test/cmdlineTests.sh`` has grown more and more complicated over time - I'd say it's time to consider making it a python script and rewriting it nicely.
This would for example allow to easily filter by its sub-test-suites and individual tests, etc.

On the other hand it shares logic with other script, so whether this is a good idea may depend on whether we want to transition them as well.

**Comment by cameel** [comment]
I think it's a good idea and here's the plan for doing it I came up with with @Marenz last year:
1) Add support for a new kind of CLI test - one that has a Python or Bash script inside.
2) Split the [Bash tests that are currently tacked on at the end of `cmdlineTests.sh`](https://github.com/ethereum/solidity/blob/v0.8.13/test/cmdlineTests.sh#L291-L674) into such smaller tests.
    - When naming dirs for these tests use a prefix to makes them sort at the end to much the current behavior (they currently run after all the other tests and I think we want to keep it that way since they can be long). `~` is a good candidate for such a prefix.
3) Rewrite the smaller scripts in Python.
4) Rewrite `cmdlineTests.sh` in Python.

I actually have an old branch where I did (1) and started (2). I'm going to assign myself here for now since I'd like to finish that when I have time. Then (3) and (4) could be done piece by piece.

**Comment by christianparpart** [comment]
@cameel you self-assigned this, but we already have soo many PRs (you've 10 open ones). Let's try to close them first? :-)

**Comment by cameel** [comment]
I assigned this because I already started working on this last year. There just was no issue for this back then but I have a branch with (1) and (2) almost done. I had to switch to more important tasks but if we're doing this then I want to update that branch and submit it as a PR when we're done with PR squashing.

**Comment by christianparpart** [comment]
ah, perfect. thx. ;)
