### ISSUE TITLE
Access to constants through contract names

### ISSUE THREAD

**Issue by ethernomad** [ethereum/solidity#1290]
It is currently possible to do this:

```
pragma solidity ^0.4.3;

contract Constants {

    uint constant FLAG = 0x1;
}

contract Test is Constants {

    function x() returns (uint) {
        return Constants.FLAG;
    }
}
```

But surely it should be possible to do this:

```
pragma solidity ^0.4.3;

contract Constants {

    uint constant FLAG = 0x1;
}

contract Test {

    function x() returns (uint) {
        return Constants.FLAG;
    }
}
```

**Comment by chriseth** [comment]
We still have to figure out how we want constants to behave exactly. Currently, I think you might be able to access private information via constants, which is perhaps not such a good idea.

**Comment by chriseth** [comment]
Now that we have the pure check, it should be fine to do this at least for actually pure constants.

**Comment by j-h-scheufen** [comment]
As a side note to this ticket: To simulate the desired constant behavior until it's fully supported in the language I'm using a workaround via libraries:

```
library Constants {
   function FLAG() pure returns (uint) {
      return 0x1;
   }
}

contract Test {
    function x() returns (uint) {
        return Constants.FLAG();
    }
}
```

To be frank, I actually don't know the cost of simulating constants via library functions, because you have an additional function on the callstack and memory every time you access it, but it does the trick and gives me what I need for more efficient coding. Once constants are supported fully, it is not too hard to turn the library into a contract and search/replace its usage to remove the `()` parentheses.

I'm not worried about gas cost as the solutions that use this approach run on a permissioned EVM with no gas limit, but it would be great to get your opinion on the above, @chriseth.

**Comment by axic** [comment]
I am leaning towards that constants should be supported in interfaces instead.

**Comment by cygnusv** [comment]
It seems this is solved with Solidity 0.6

**Comment by j-h-scheufen** [comment]
I looked at the Solidity 0.6 release notes and did not see how this is solved with that release. Can anyone point to an example or other relevant docs?

**Comment by chriseth** [comment]
Ah sorry, I thought I tried the example, but I must have made a mistake.

**Comment by sambacha** [comment]
can confirm, 100% still an issue

**Comment by chriseth** [comment]
Design call: moving it into the icebox because there seems to be not too much interest. We may allow constants at file level in the future instead.

**Comment by cameel** [comment]
Just for reference - issue about constants at file level: #9671.

**Comment by pedrommaiaa** [comment]
This is still an issue on 0.8.15:

```Solidity
Contract Test1 {
    uint256 public constant WAD = 1e18;
}

Contract Test2 {
    function getWad() external pure returns (uint256) {
        return Test1.WAD();
    }
}
```

returns `Member "WAD" not found or not visible after argument-dependent lookup in type(contract Test1). `

**Comment by itbrda** [comment]
I also believe that something like this would be perfectly possible

type(ContractWithConstant).CONSTANT_NAME

very similar to

type(uint).max
