### ISSUE TITLE
SMTChecker: broken "counterexample"

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#12962]
In the following sample, the SMTChecker correctly recognize there is a problem, but the counter-example it provides is broken: 
it suggests: 
```
  _x = 0x80 * 2**24
  _y = 2
```
but this value breaks the "require" 

(it does provide a proper counter-example for addition operation, but not for multiplication..)

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.0;

contract Overflow {
    uint32 immutable x;
    uint32 immutable y;

    function mul(uint32 _x, uint32 _y) internal pure returns (uint32) {
        return _x * _y;
    }

    constructor(uint32 _x, uint32 _y) {
	require( _y < 50000 );
	require( _x < 50000 );
        (x, y) = (_x, _y);
    }

    function stateMul() public view returns (uint32) {
        return mul(x, y);
    }
}
```

**Comment by hrkrshnn** [comment]
@drortirosh Can you post a minimal example? The example you posted doesn't seem to have any asserts.

**Comment by drortirosh** [comment]
This sample is based on the overflow sample in the doc.
If you run it with overflow check, it will report an error

**Comment by leonardoalt** [comment]
I don't think the assertion is wrong. Considering the requires, the multiplication can never overflow.
BMC reports a counterexample as a false positive, since it does not track the state, so it ignores the requires basically, only looking at the first function.
CHC unfortunately doesn't prove it with the default underlying solver. If I use an alternative underlying solver, it proves that the assertion is correct. I should really add eldarica a default option...

**Comment by leonardoalt** [comment]
Closing given the explanation above. Please reopen if needed.
