### ISSUE TITLE
Ensure that any contract that compiles with the new optimizer also compiles when disabling optimizations

### ISSUE THREAD

**Issue by wuestholz** [ethereum/solidity#12980]
## Abstract

According the discussion with @chriseth at the FV hangout, it may happen that a contract that compiles with the new Yul-based optimizer does not compile when disabling that optimizer. The reason seems to be a new compiler/optimizer pass that spills stack variables to memory. As far as I understand, when disabling the optimizer, this pass is currently not run and contracts may not compile due to lack of stack space. It would be great if this pass could always be run, independently of other (optimization) passes, to make sure the optimizer can always be disabled if needed.

## Motivation

Users should have the option to disable the optimizer. For instance, it seems that without optimization more debug information is preserved and users may want to disable the optimizer when testing/debugging/verifying their code before deployment.

## Specification

When a user can compile a contract with the new optimizer they should also be able to compile it when disabling the optimizer (e.g., through existing flags/options).

## Backwards Compatibility

This should not break backwards compatibiliy. In fact, it seems like the current (Yul-based) compilation pipeline breaks backwards compatiblity.

**Comment by ekpyron** [comment]
We'll most probably enable some minimal optimizations including stack-to-memory by default in one of the upcoming releases.

**Comment by wuestholz** [comment]
@ekpyron Thanks for the update! Do you already have an estimate about when this will be released? I think this would be really useful for various tools that want to provide accurate debug information.

I found this issue: https://github.com/ethereum/solidity/issues/13972. Is this the issue that you use for tracking this feature?

**Comment by ekpyron** [comment]
That issue should at least mitigate the problem quite a bit and is currently being actively worked and and is planned for the next release (which may happen some time next month).

We will need to see whether and in how many cases we will still run into this issue afterwards, though, the mechanisms are not entirely foolproof currently (we'll separately also be working on changing that, but that may take a bit longer to do).

**Comment by wuestholz** [comment]
@ekpyron Thanks a lot for the update! Are you planning to ensure that the minimal optimizations keep the source maps as accurate as possible? That would be crucial for our use case.

**Comment by ekpyron** [comment]
We're generally trying to keep source maps as accurate as possible and the minimal optimizations are conservative and shouldn't affect them significantly - but we do also switch to a newer backend to generate bytecode in the end; also for that we of course try to generate accurate source maps, but we don't have good data about the potentially induced change being an issue for tooling or not - if you want you can check yourself with the current PR draft https://github.com/ethereum/solidity/pull/14149 and report back to us if the generated source maps seem workable for you - if they're lacking in some way we can try to remedy that.

**Comment by wuestholz** [comment]
Thanks! I'll let you know if we notice anything funny. :) We currently use the the unoptimized bytecode when we want to obtain the most accurate source locations. For optimized bytecode we've observed that there are often instructions that do not map to a source location.

**Comment by cameel** [comment]
Responding to https://github.com/ethereum/solidity/pull/14149#pullrequestreview-1466030939 but I'll post here for better visibility.

> One thing we could still check (no need to add tests for it, but just to confirm locally at a few random example cases) is that this won't negatively affect source mappings (given concerns like https://github.com/ethereum/solidity/issues/12980#issuecomment-1568278894)

To be honest, not sure what to check for so I compared the current source maps with those from 0.8.20.

It's actually pretty hard to find non-trivial code to compare because most of our bigger test snippets do not even compile via IR with no optimization before my PR. This includes stuff from `test/libsolidity/semanticTests/externalContracts/`, `test/benchmarks/` and even `test/libsolidity/semanticTests/various/erc20.sol`. So in those terms, whatever source map we get is a clear improvement over not having a source map at all :)

In the end I compiled all syntax and semantic tests in a loop and for comparison I selected a few of those that produced the biggest source maps.

Overall, a vast majority of differences looks like just jump annotations (`i`, `o`, `-`) being moved around. It's hard to say if there's more of them before or after - I suspect they're just at different locations. If I filter that out I see very few other differences (see diffs below). Interestingly, the code with minimal optimization seems to actually have a little more annotated locations (though the difference is not big either way).


## Diffs

Diffs of the output from `solc --via-ir --combined-json srcmap-runtime`, filtered to put each source reference on a separate line and remove the jumps and empty lines.

<details>

The exact filters used:

```bash
jq --raw-output '. | select(.contracts != null) | .contracts[]."srcmap-runtime"' |
    sed -e 's|$|\n---\n|g' |
    sed -e 's|;|\n|g' |
    sed '/^$/d' |
    sed '/^:::[io\-]$/d'
```

</details>

### [`semanticTests/smoke/arrays.sol`](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/semanticTests/smoke/arrays.sol)

<details>

```diff
@@ -1,0 +2,2 @@
+-1:-1:-1
+35:898:0
@@ -12 +13,0 @@
-144:88
@@ -17,0 +19 @@
+307:9
@@ -23 +24,0 @@
-305:23
@@ -25 +25,0 @@
-305:23
@@ -27 +27,2 @@
-237:98
+324:3
+298:30
@@ -33 +34,2 @@
-406
+400:16
+406:2
@@ -37 +39,2 @@
-425
+418:18
+425:3
@@ -41 +43,0 @@
-340:104
@@ -47 +49,2 @@
-449:76
+513:5
+506:12
@@ -53 +55,0 @@
-530:79
@@ -59 +60,0 @@
-614:86
@@ -65 +65,0 @@
-705:93
@@ -70 +69,0 @@
-885:39
@@ -72 +70,0 @@
-885:39
@@ -74 +71,0 @@
-803:128
```

</details>

### [`syntaxTests/nameAndTypeResolution/288_conditional_with_all_types.sol`](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/syntaxTests/nameAndTypeResolution/288_conditional_with_all_types.sol)

<details>

```diff
@@ -2,3 +2,2 @@
-90:26
-121:::-
-0:2072::-
+-1:-1:-1
+0:2072:0
@@ -6 +5,2 @@
-307:6
+370:6
+307
@@ -12,3 +12 @@
-359:1
-348:12
-339:21
+370:6
@@ -19 +17,2 @@
-460:1
+475:6
+444:21
@@ -21 +20 @@
-464:1
+460:1
@@ -23,0 +23 @@
+475:6
@@ -28 +27,0 @@
-546:42
@@ -31 +30,11 @@
-0:2072::-
+564:24::-
+453:12
+475:6
+444:21
+453:12
+464:1
+453:12
+348
+359:1
+348:12
+0:2072
@@ -37,6 +45,0 @@
-717:5
-703:19
-694:28
-736:1
-:9
-741:4
@@ -44,2 +47,3 @@
-732:13
-843:1
+703:19
+836:18
+935:16
@@ -47,3 +51 @@
-871:1
-864:18
-899:1
+864
@@ -54,3 +56,2 @@
-924:1
-913:12
-892:33
+935:16
+942:9
@@ -60 +61,2 @@
-937
+:16
+937:1
@@ -68,3 +70,2 @@
-1065:1
-1054:12
-1037:29
+1076:16
+1083:9
@@ -74 +75,2 @@
-1078
+:16
+1078:1
@@ -81,0 +84,3 @@
+1223:6
+647:590::o
+1201:12::-
@@ -84,5 +89,13 @@
-1190:23
-1228:1
-1223:6
-647:590
-0:2072::-
+1054
+1065:1
+1054:12
+913
+924:1
+913:12
+736:9
+741:4
+736:9
+703:19
+717:5
+703:19
+0:2072
@@ -92 +105 @@
-1350:8
+1332:37
@@ -94 +107 @@
-1361:8
+1350:8
@@ -98,0 +112 @@
+1446:1
@@ -101,3 +114,0 @@
-1431:5
-1416:20
-1400:36
@@ -111,3 +121,0 @@
-1572:6
-1556:22
-1547:31
@@ -116,4 +124 @@
-1633:1
-1632:6
-1636:1
-1632:6
+1606:41
@@ -121,4 +126,2 @@
-1642:1
-1641:6
-1645:1
-1641:6
+1633:1
+1636
@@ -127,2 +129,0 @@
-1667:1
-1666:6
@@ -130 +130,0 @@
-1666:6
@@ -133,0 +134 @@
+1797:8
@@ -136,3 +137,2 @@
-1781:6
-1765:22
-1729:58
+1797:4
+:8
@@ -146,0 +147,2 @@
+1912:6
+1881:9
@@ -150,4 +152 @@
-1900:1
-1893:9
-1874:28
-1863:39
+1912:6
@@ -157 +156,29 @@
-0:2072::-
+1874:28::-
+1912:6
+1893:9
+1900:1
+1893:9
+1874:28
+1765:22
+1797:8
+1781:6
+1765:22
+1625
+1606:41
+1625:22
+1642:1
+1645
+1625:22
+1556
+1572:6
+1556:22
+1416:20
+1446:1
+1431:5
+1416:20
+1343:26
+1332:37
+1343:26
+1361:8
+1343:26
+0:2072
```

</details>

### [`syntaxTests/abiEncoder/abi_encode_conversions.sol`](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol)

<details>

```diff
@@ -2,3 +2,2 @@
-233:39
-277:37::-
-205:792::-
+-1:-1:-1
+205:792:0
@@ -6 +5,2 @@
-370:4
+370:6
+:4
@@ -9,0 +10 @@
+319:90
@@ -11,0 +13,2 @@
+:4
+:6
@@ -14,0 +18,2 @@
+391:11::-
+370:::-
@@ -17 +22,2 @@
-463:4
+463:6
+:4
@@ -20,0 +27 @@
+414:88
@@ -22,0 +30,2 @@
+:4
+:6
@@ -25,0 +35,2 @@
+484:11::-
+463:::-
@@ -27,2 +37,0 @@
-594:3
-593:5
@@ -30,0 +40,2 @@
+561:38
+507:99::o
@@ -33 +44,3 @@
-699:4
+666:41
+699:6
+:4
@@ -35 +47,0 @@
-698:8
@@ -37 +49,3 @@
-750:4
+717
+750:6
+:4
@@ -39 +52,0 @@
-749:8
@@ -40,0 +54,3 @@
+666
+717
+768:36
@@ -42 +57,0 @@
-800:3
@@ -43,0 +59,3 @@
+561:38
+768:36
+814
@@ -45 +62,0 @@
-846:3
@@ -46,0 +64,3 @@
+860:54
+893:19
+901:10
@@ -50 +69,0 @@
-892:21
@@ -52,2 +71,3 @@
-939:4
-:6
+924:27
+939:6
+924:27
@@ -55 +74,0 @@
-947:3
@@ -57,2 +76,3 @@
-976:4
-:6
+961
+976:6
+961:27
@@ -60 +79,0 @@
-984:3
@@ -62 +81 @@
-626:369
+626:369::o
```

</details>

**Comment by wuestholz** [comment]
@cameel Thanks a lot for implementing this and for the above analysis! 🙏 If the source maps are as accurate as the ones without optimization that would be awesome.

If I understand correctly you compared without optimization and with minimal optimization.  Do you also have some data comparing minimal optimization and "full" optimization in terms of source maps?

I assume that for this comparison one could look at more complex contracts. I'd be curious if this would confirm our impression that full optimization reduces the accuracy of the source maps significantly (unfortunately, based on only a few contracts).

**Comment by cameel** [comment]
> Do you also have some data comparing minimal optimization and "full" optimization in terms of source maps?

Not really. If you want to try yourself, you can check out the script below (which is basically the code I used to get the above, but modified to compare the things you mentioned, and also to download a binary with the new feature from CI, and some stats at the end).

Not sure how helpful that is though. You can generally see the difference between the number of annotated instructions, so you should be able to see whether the optimization is removing a lot of those annotations. But it's hard to tell anything about accuracy because you don't see which instructions get annotated in which version.

### Comparison script
```bash
function format_srcmap {
    jq --raw-output '. | select(.contracts != null) | .contracts[]."srcmap-runtime"' |
        sed -e 's|$|\n---\n|g' |
        sed -e 's|;|\n|g' |
        sed '/^$/d' |
        sed '/^:::[io\-]$/d'
}

# Download solc binary from CI (build from develop, just after #14149).
curl \
    --location \
    --output /tmp/solc-develop \
    https://output.circle-artifacts.com/output/job/fd25631d-4ab4-4475-9b90-a1f29f75bca2/artifacts/0/solc-static-linux
chmod +x /tmp/solc-develop
/tmp/solc-develop --version

# YOU CAN PLUG YOUR OWN COMPILER BINARY AND INPUT FILES HERE
solc=/tmp/solc-develop
input_files=(
    # This is a test file from the repo. To use it as is, you must be at the repo root.
    # You can list multiple files here.
    "test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol"
)

diff_output=$(
    diff --unified --color \
        <(${solc} --via-ir            --combined-json srcmap-runtime "${input_file[@]}" | format_srcmap srcmap-runtime) \
        <(${solc} --via-ir --optimize --combined-json srcmap-runtime "${input_file[@]}" | format_srcmap srcmap-runtime)
)
echo "$diff_output"
echo "Annotations lost: " "$(echo "$diff_output" | grep --invert-match --regexp '.*---.*' | grep '^-' | wc --lines)"
echo "Annotations added:" "$(echo "$diff_output" | grep --invert-match --regexp '.*---.*' | grep '^+' | wc --lines)"
```

For this particular file I get:
```
Annotations lost:  67
Annotations added: 126
```

**Comment by wuestholz** [comment]
@cameel Cool! Thanks for sharing!

I'll try to experiment a little more if I have time. Unfortunately, I don't quite remember if our issues where due to the map entry being gone entirely or being inaccurate (that is, pointing to a much "larger" source code region, such as the entire contract).
