### ISSUE TITLE
add suggestion when dynamic memory arrays are used if size is not given

### ISSUE THREAD

**Issue by 0xalpharush** [ethereum/solidity#12989]
## Abstract

Add compile time warning for dynamic memory arrays that are not explicitly allocated when declared.

## Motivation

The below example compiles and results in an "index out of bounds" warning when run. It would be easier to debug and likely prevent runtime exceptions if the compiler warned or errored with the following syntax.

## Specification
```
MyStruct[] memory structs;
for (uint i = 0; i < array.length; i++) {
    structs[i] = MyStruct(...)
}
```
Suggest: structs does not declare a size and cannot be dynamically resized... try `structs = new MyStruct[](size);`
## Backwards Compatibility
No issues. There may be forward compatibility issues if `push` is implemented for dynamic arrays.

**Comment by cameel** [comment]
You have a bug in your example. You're using `array.length` instead of `structs.length`. A correctly coded example will not revert because an "uninitialized" array does not contain random data. Its length is guaranteed to be zero:
```solidity
contract C {
    struct MyStruct {
        uint x;
    }
    function foo() public {
        MyStruct[] memory structs;
        for (uint i = 0; i < structs.length; i++) {
            structs[i] = MyStruct(i);
        }
    }
}
```

Also, it's perfectly fine not to allocate the array immediately. You might not know the size of the array immediately:
```solidity
MyStruct[] memory structs;
if (someFlag)
    structs = new MyStruct[](10);
else
    structs = new MyStruct[](20);
```

**Comment by 0xalpharush** [comment]
Using a different array was purposeful... whenever one modifies array elements e.g. converts to a different type and copies them into a new array, the length of the input array is not always zero. And, the for loop will run in that case.
```
contract C {
    struct MyStruct {
        uint x;
    }
     struct Data {
        bytes32 y;
    }
    function foo(Data[] memory data) public {
        MyStruct[] memory structs;
        for (uint i = 0; i < data.length; i++) {
            structs[i] = MyStruct(uint(data[i]));
        }
    }
}
```

> Also, it's perfectly fine not to allocate the array immediately. You might not know the size of the array immediately:

In this example, an explicit size is used, so it's not something I'd expect a warning about.

**Comment by r0qs** [comment]
> A correctly coded example will not revert because an "uninitialized" array does not contain random data. Its length is guaranteed to be zero:

Hi @0xalpharush, as @cameel  pointed out, there are no such thing as uninitialized dynamic arrays in Solidity, i.e. everything that's not explicitly initialized gets some default `zero` value, in this case, it is an array of size zero.

And although your suggestion is valid, it should preferably be done by static analysis tools and not by the Solidity compiler, since having a warning there would not be in line with how all other variables work.

Thus, I will be closing this issue for now. Please, feel free to reopen it if you have anything to add.
