### ISSUE TITLE
The legacy assembly blocks cross-tagging between deploy and runtime code

### ISSUE THREAD

**Issue by hedgar2017** [ethereum/solidity#12990]
Since the legacy assembly is not documented, I create this issue in this section.

Could anyone help me with EVM legacy assembly? I'm trying to figure out the following pattern:

```
031 Tag 5                                                               
032     JUMPDEST                                                                        
033     PUSH            0                                                               
034     PUSH [tag]      8                                                               
035     PUSH [tag]      9                                                               
036     PUSH            20                                                              
037     SHL                                                                             
038     PUSH [tag]      18446744073709551625                                            
039     OR                                                                              
040     PUSH            20                                                              
041     SHR                                                                             
042     JUMP            [in]
```

What should be the result of such operation?
If I just execute the binary operations on the tags as on decimal numbers, the result does not add up to a tag of an existing block. Neither in the deploy nor in the runtime code.

**Comment by hedgar2017** [comment]
@ekpyron you gave me some useful information lately, though I didn't clarify this particular aspect back then.
Could you please elaborate the behavior above?

**Comment by hrkrshnn** [comment]
@hedgar2017 What generated this assembly code?

**Comment by hedgar2017** [comment]
@hrkrshnn this test for example:
```
contract A {
    function f() public virtual returns (uint256 r) {
        return 1;
    }
}


contract B is A {
    function f() public virtual override returns (uint256 r) {
        return super.f() | 2;
    }
}


contract C is A {
    function f() public virtual override returns (uint256 r) {
        return super.f() | 4;
    }
}


contract D is B, C {
    uint256 data;

    constructor() {
        data = super.f() | 8;
    }

    function f() public override (B, C) returns (uint256 r) {
        return data;
    }
}
// ====
// compileToEwasm: also
// compileViaYul: also
// ----
// f() -> 15
```

Or any other where internal functions are called from the constructor.

**Comment by hedgar2017** [comment]
@hrkrshnn the question is basically what is the expected behavior of the following operations: `SHL`, `SHR`, `OR`, `XOR`, `AND`, if 1 or 2 of their operands are **tags**.

**Comment by hrkrshnn** [comment]
Tags just represent offsets in code. It can be treated as `push num`. Maybe a nice illustration of this can be
```solidity
contract C {
   function f() internal { ... }
   function g() internal { ... }
   function test(bool b) external {
       function() x = b ? f : g;
       x();
   }
}
```
In the legacy compilation pipeline, you will see operations on tags here.

**Comment by hedgar2017** [comment]
@hrkrshnn I know what they represent.
The question is above: what is the expected behavior of the following operations: SHL, SHR, OR, XOR, AND, if 1 or 2 of their operands are tags.

**Comment by ekpyron** [comment]
> ```
> 031 Tag 5                                                               
> 032     JUMPDEST                                                                        
> 033     PUSH            0                                                               
> 034     PUSH [tag]      8                                                               
> 035     PUSH [tag]      9                                                               
> 036     PUSH            20                                                              
> 037     SHL                                                                             
> 038     PUSH [tag]      18446744073709551625                                            
> 039     OR                                                                              
> 040     PUSH            20                                                              
> 041     SHR                                                                             
> 042     JUMP            [in]
> ```

``18446744073709551625`` in hexadecimal is ``0x010000000000000009``...
that's the internal tag ID of a tag that refers to something in "subassembly" 1, i.e. it's how construction code refers to the runtime tag 9... might be nice to make the evmasm output nicer for such cases...

In the translation from evmasm to an actual opcode sequence, this would resolve to the offset of tag 9 in the runtime code (which is known to fit into 32 bytes!).

So the sequence
> 035     PUSH [tag]      9                                                               
> 036     PUSH            20                                                              
> 037     SHL                                                                             
> 038     PUSH [tag]      18446744073709551625                                            
> 039     OR                                                                              

constructs a shared runtime *and* creation time tag offset to tag_9 in creation and tag_9 in runtime code (it's just a coincidence that it's tag_9 in both cases).

We need such combined offsets, since you can *store* such a tag value in storage - and we don't know if it is used only from runtime code, only form creation code or from both.

Then *calling* such a thing from creation code uses the higher-order bits of this combined offset, whereas calling it from runtime context uses the lower-order bits.

So the next part of the sequence

> 040     PUSH            20                                                              
> 041     SHR                                                                             

extracts the offset of the respective function in creation code - and then jumps into that.


Did that make sense :-)? So
> 038     PUSH [tag]      18446744073709551625

will in the end really push an offset into *runtime* code during creation.
And the tag IDs don't have any numeric relation to the actual offsets - they're just symbolic IDs and will be resolved in the translation from evmasm to opcodes.

**Comment by hedgar2017** [comment]
@ekpyron thanks a lot! That had been my working version I was going to try today!

But still, the behavior of the `OR` opcode on tags remains a little obscured and I would like to clarify it completely.

I understand that before `SHR 32` there must be the needed tag in the bits `32..64` of the tag operand. Therefore, the `OR` instruction must shift either the higher or lower bits there, depending on whether we are in the creation or runtime code at the moment. Am I right?

**Comment by ekpyron** [comment]
The ``OR`` just combines the deploy-time offset with the creation-time offset... it could just as well be ``ADD``, in case that helps :-)?
Note that while the tag ID in ``PUSH [tag] 18446744073709551625`` appears to be large, this is just a symbolic ID - the actual offset later on will be something small, like ``0x42`` or so...

So
> 035 PUSH [tag] 9
> 036     PUSH            20                                                              
> 037     SHL                                                                             
> 038     PUSH [tag]      18446744073709551625                                            
> 039     OR                                                                              

Is ``or(shl(32, <creation-offset>), <runtime-offset>)`` - the ``or`` just merges the left-shifted runtime offset and the creation offset together... so after the ``or`` you have the creation offset in the higher bits, the runtime offset in the lower bits.
Then shifting to the right, will give you back the creation-time-offset (which is the right one, since you're directly jumping to it and this snippet is taken from creation code).

**Comment by ekpyron** [comment]
So as actual opcodes you will in the end see that

> 035 PUSH [tag] 9
> 036 PUSH 20
> 037 SHL
> 038 PUSH [tag] 18446744073709551625
> 039 OR

will be translated to something like

> 035 PUSH 0xAA
> 036 PUSH 20
> 037 SHL
> 038 PUSH 0xBB
> 039 OR

Just instead of ``0xAA`` whatever the creation-time-offset of tag 9 is and ``0xBB`` the offset of whatever the corresponding tag in runtime code is.

**Comment by hedgar2017** [comment]
Ok, we have clarified that the behavior of the bitwise operations is not different than with ordinary operands.

Here is the example:
```
011 Tag 1                                                               
012     JUMPDEST                                                                        
013     POP                                                                             
014     PUSH [tag]      4                                                               
015     PUSH [tag]      5                                                               
016     PUSH            20                                                              
017     SHL                                                             // 500000000
018     PUSH [tag]      18446744073709551624                            // 10000000000000008                         
019     OR                                                              // 10000000500000008
020     PUSH            20                                                              
021     SHR                                                             // 100000005
022     JUMP            [in]    
```

Thus, the behavior of the `JUMP` is different. This jump has an intention to jump to the block 5 of the **creation** code (the block 5 does not exist in the **runtime** code). Why that 1 is needed in the 5-th byte, and what is the exact behavior of `JUMP` in such cases?

**Comment by ekpyron** [comment]
Let me repeat :-): ``PUSH [tag]      18446744073709551624`` does ***not*** push ``10000000000000008``. There is no 1 in the 5-th byte of whatever this tag will ultimately resolve to.
Just like ``PUSH [tag] 4`` will **not** push the value ``4``, but the offset of the tag labeled 4 in the ultimate bytecode.
Those are symbolic tag IDs, not literal offsets.

The higher order bit 1 you see in ``18446744073709551624``, resp. ``0x10000000000000008`` is just an internal marker that distinguishes tags referring to different sub-assemblies from normal tags. But this will still just resolve to a small offset into the runtime bytecode, once you continue compilation to pure opcodes instead of evmasm (evmasm is *not* opcodes precisely since it retains named tags instead of resolving down to concrete bytecode offsets).

So the value pushed by ``PUSH [tag]      18446744073709551624`` will **always** be smaller than ``2^32 - 1``, so after the right shift you will ultimately **always** just get the value of tag 5. This is not the literal value ``0x05`` either, but the *offset into the creation code at which the tag labeled tag_5 is located*.

**Comment by ekpyron** [comment]
You can have a look at what you get if you compile to actual opcodes either by using ``solc --opcodes`` or disassembling the binary - you will no longer see the tag IDs in there, but they will be resolved to actual bytecode offsets. Those tag IDs will only be present as long as you stay in evmasm - and then they don't refer to literal values, but it's just IDs of tags that will ultimately resolve to whatever offset in the bytecode will actually be the position of the symbolic tag.

And a tag like ``0x10000000000000008`` just refers to the offset of the 8th tag in the ``1``st nested evmasm sub-assembly - that's what that 1 means, nothing else :-).

**Comment by hedgar2017** [comment]
@ekpyron this is that particular detail I needed to hear :-) Sorry for my nuisance.

I am writing a EVM-to-LLVM compiler, and in my case those tags are indeed meaningful values and they are rendered into LLVM block identifiers. So if there was anything possibly hidden under the good, I needed to know it.

**Comment by ekpyron** [comment]
Sure no worries - I already realized after my first post that probably that first post didn't clarify that part sufficiently well :-).

**Comment by hedgar2017** [comment]
In fact, I also use these tags to reconstruct the control flow tree, so I push the tags on the stack as ordinary integers indeed :-)

Thanks a lot for the detailed explanation!
