### ISSUE TITLE
Warn when an arithmetic expression in a common type is implicitly upcast to an even larger type

### ISSUE THREAD

**Issue by sseefried** [ethereum/solidity#13004]
## Page

No documentation

## Abstract

I recently discovered that literal expressions of the form `n days` seem to get given the type `uint24`. However, I couldn't find any documentation on this and it leads to problems once you try to multiply by a number with smaller precision.

The following simple contract highlights this problem

```sol
pragma solidity 0.8.7;

contract Test {

    function r1(uint8 n) public view returns (uint32) {
        return n * 1 day; 
    }

}
```

If you compile, deploy and call function `r1` -- I used Remix -- you will find that it reverts because of an arithmetic overflow whenever `n` is in the range `n >= 195` and `n <= 255` (`uint8.max`). 

This is how I discovered that `1 day` must be assigned the type `uint24`.  Assigning `n = 194` does not cause an overflow but assigning `n = 195` does. This is because `uint24.max = 16777215` and the following two facts are true:

- `194 * 86400 = 16761600`
- `195 * 86400 = 16848000`

The first is slightly less than `uint24.max` and the latter just slightly more.

What I suspect happens is that Solidity sees that we have a `uint8` multiplied by a `uint24` and then upcasts the `uint8` to a `uint24` and then performs the multiplication. Unfortunately `uint24` is just not big enough to hold the result and so we get an arithmetic overflow. 

Try as I might I couldn't find any documentation on this issue anywhere on the web, and I couldn't find any in the Solidity docs either.

I also ran a debugging session in Remix and stepped, opcode by opcode, through the code and discovered that my casting theory was essentially correct. I saw the opcode `AND` applied to a value and `0xFFFFFF`, which is `uint24.max` several times while stepping through.

My question is: is this behaviour by design? It seems reasonable if so, but it needs to be documented. I would be happy to help out with that effort if someone can confirm that what I've found is correct _and_ intended behaviour. 

## Pull request

I wanted to check that this was a real, and known issue before submitting a PR. I hope that is okay.

**Comment by cameel** [comment]
Thanks for the report. This really looks like a bug. `1 days` is supposed to be a a literal, equivalent to writing `24 * 60 * 60`. If you write
```solidity
uint8 x = 1 days;
```
you get an error
```
Error: Type int_const 86400 is not implicitly convertible to expected type uint8. Literal is too large to fit in uint8.
```
and it's the same exact error you get if you get when using a literal:
```solidity
uint8 x = 1 * 24 * 60 * 60;
```
```
Error: Type int_const 86400 is not implicitly convertible to expected type uint8. Literal is too large to fit in uint8.
```
The analysis clearly does not treat it as an expression of type `uint24` or it would have issued this error instead:
```
Error: Type uint24 is not implicitly convertible to expected type uint8.
```

**EDIT**: The snippet below is wrong. I did not put the `1 * 24 * 60 * 60` part in parentheses. It's not a bug after all. It's consistent with behavior of literals. See my next comment.
<details>

~I think that the analysis is right and it's the codegen that incorrectly treats is as `uint24`. Combined with `unchecked` it can lead to incorrect calculation results. For example in the code below `f1()` returns 163 while `f2()` returns 2 because the value is calculated within different types.~

```solidity
contract Test {
    function f1() public view returns (uint) {
        uint8 n = 195;
        unchecked {
            return (2 * n * 1 days) / (n * 1 days);
        }
    }

    function f2() public view returns (uint) {
        uint8 n = 195;
        unchecked {
            return (2 * n * 1 * 24 * 60 * 60) / (n * 1 * 24 * 60 * 60);
        }
    }

    function test() public view {
        assert(f1() == f2());
    }
}
```

</details>

**Comment by cameel** [comment]
After discussing it with @ekpyron looks like I was wrong. This is actually the expected behavior for literals. If you do `n * (1 * 24 * 60 * 60)`, the `1 * 24 * 60 * 60` part is a literal expression but it gets converted to its mobile type before the operation, which is `uint24` in this case. Same happens when you use `1 days` instead.

So there's no bug here and the suffixes do not inherently give that value a type but when used in expressions, you need to be aware that operations between such literals and variables are performed in limited precision and the precision depends on the type of the variable and the value of the literal.

The problem here is really that the expression is computed in smaller precision than the return type of the function and it may not be immediately clear when looking at it. @ekpyron suggested that perhaps we should warn about such situations and I agree that it would be a good idea:
> Whenever you have an arithmetic expression in a common type that is then implicitly upcast to an even larger type, there is likely something off I guess...
> Might be possible to warn about this and ask for one of the operands to be upcast explicitly...

We just need to think carefully about the conditions under which we want this warning to avoid unnecessary false-positives.

**Comment by sseefried** [comment]
@cameel Thanks for your thorough research on the topic. I searched for the term "mobile type" in the Solidity docs and found this

> In case one of the operands is a [literal number](https://docs.soliditylang.org/en/v0.8.12/types.html#rational-literals) it is first converted to its “mobile type”, which is the smallest type that can hold the value (unsigned types of the same bit-width are considered “smaller” than the signed types). If both are literal numbers, the operation is computed with arbitrary precision.

This is exactly what I was looking for earlier but failed to find. Thank you for helping me find it.

I don't think the behaviour I saw in my function `r1` above is incorrect but it is _tricky_. What I was expecting was that the whole expression would be computed with the precision of `uint32`. But when you actually get into the details of how the expression is evaluated, part by part, you see that you need to upcast the `uint8` to a `uint32` to get the intended behaviour. 

e.g.
```sol
    function r1(uint8 n) public view returns (uint32) {
        return uint32(n) * 1 days; 
    }
```

**Comment by 0xask3** [comment]
Are there any plans to fix this issue? Like a warning when implicit typecast can cause arithmetic overflows
