### ISSUE TITLE
Array indices are `uint64` but `array.length` is `uint256`

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13071]
## Description

From the [Solidity blog](https://blog.soliditylang.org/2020/04/06/memory-creation-overflow-bug/):

> Starting from Solidity version 0.6.5 the maximum allocation size for dynamic memory arrays is `2**64-1`. Attempting to allocate larger arrays now directly reverts.

Therefore array indices are `uint64` type in Solidity. However, `array.length` returns a `uint256` type.

This gives an error as follows:

```
uint64 currIdx = myArray.length;

=>

TypeError: Return argument type uint256 is not implicitly convertible to expected type (type of first return variable) uint64.
```

## Environment

- Compiler version: 0.8.14
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: Hardhat
- Operating system: Linux

## Steps to Reproduce

See above

**Comment by cameel** [comment]
Well, the compiler still allocates a whole 32-byte word for the length field so the type is technically correct. Changing it to `uint64` would actually be a small performance hit since operations on integer types smaller than a stack slot require adding extra masking and bit shifts so they cost more. Currently you get that hit only if you actually cast the length to `uint64`.

I think this change would make more sense if we actually decided to reduce the length field to 64 bits. I think it's unlikely though. Many people writing low-level code depend on this being 32-bytes so we'd only do it if the benefits were large enough to be worth such breakage. Currently the compiler always aligns memory at 32-byte words because it's relatively cheap and most of the time it's better to avoid the extra arithmetic associated with smaller types.

**Comment by lukehutch** [comment]
That all makes sense, thanks for explaining. Feel free to close this bug.

Does a transaction revert if `array.push()` increases `array.length` to `2**64`?

**Comment by cameel** [comment]
ok then.

As for the revert, I'm not sure actually but I doubt it. Storage arrays do not have this limit and they're the only ones that allow `push()`. But if you want to be sure it's easy to check by compiling a short snippet with `--ir` option and checking if the condition is there in the Yul output.

**Comment by lukehutch** [comment]
Quick related question: the justification given for why dynamic memory arrays have a limit of `2**64-1` elements is given in the blog post I linked as:

> While the length of the array is stored directly as is, the amount of memory to allocate, i.e. the increment for the “free memory pointer”, is calculated as 32 times the array length. Since this multiplication was not protected against overflows, a sufficiently large length can cause an overflow, resulting in only a small amount of memory to be actually allocated (i.e. the free memory pointer will only be incremented by the overflowed size). Subsequent memory allocations will therefore use memory regions that overlap with the originally allocated array.

Why did the allocator not simply revert if the requested array length was greater than `(2**256)/32-1`? It seems that this would have been a much better way to have solved the problem.
