### ISSUE TITLE
Possibility of converting payable to non-payable functions in solidity makes no sense (according to documentation itself)

### ISSUE THREAD

**Issue by mojtaba-eshghie** [ethereum/solidity#13114]
## Page

[Solidity function types](https://docs.soliditylang.org/en/v0.8.14/types.html?highlight=abi.encodeWithSignature#function-types)

## Abstract
In the conversion section, it is said that one of the conditions for converting from function A to B is that the state mutability of A is more restrictive than the state mutability of B. Also, it is explicitly stated that non-payable functions are more restrictive than payable ones, so, it makes sense if non-payable functions are convertible to payable functions. However, not only it is said the opposite, but also the justification in the following paragraph does not make any sense to me:
> The rule about payable and non-payable might be a little confusing, but in essence, if a function is payable, this means that it also accepts payment of zero Ether, so it also is non-payable. On the other hand, a non-payable function will reject Ether sent to it, so non-payable functions cannot be converted to payable functions.

**Comment by nishant-sachdeva** [comment]
This question can be asked in https://matrix.to/#/#ethereum_solidity:gitter.im

Can discuss possible fixes for this

**Comment by cameel** [comment]
@nishant-sachdeva This actually does not look like a simple support question but more like a request to clarify the docs. I'm going to keep this open.

@mojtaba-eshghie The docs are correct but I agree that the justification is confusing. That's because there's a small semantic quirk here. It's that `payable` guarantees different things on *functions* and on *function pointers*.

- When you define a non-payable *function*, you guarantee that it will reject any ether sent to it, which is an additional restriction just like a guarantee that a `view` function will not write state. The compiler inserts a runtime check to enforce that. Not rejecting ether is less restrictive so you can override a payable function with non-payable but not the other way around (or at least you should be able to eventually: https://github.com/ethereum/solidity/issues/11253).
- When you define a non-payable *function pointer*, the compiler does not (and cannot) enforce that the function will actually reject ether. Instead it enforces that the function pointer is never used to send ether, which is a different thing. It's perfectly safe to assign a payable function to a non-payable pointer because if you can't send ether, both types behave the same way.

It seems to me that this could have been designed differently. The situation is similar with `pure`, where the compiler cannot enforce that the called external function is `pure` either and it just assumes it based on the declaration it sees (which could be out of sync with what's actually deployed). The same way the compiler could assume that a function declared `payable` will always reject ether. And then it could enforce this interpretation of payable on function pointers. That would be more consistent - though not necessarily more useful than the current situation.

For now I think we should just make that semantic difference clearer in the docs.

**Comment by nishant-sachdeva** [comment]
Closing this issue as it's been solved by #13613
