### ISSUE TITLE
Add `array.popAndGet()` that returns the last value in array after `pop()`

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13125]
## Abstract

Currently `array.pop()` does not return a value. It should return a memory copy of the last element of the storage array that was popped.

## Motivation

Currently if you want to remove the last element of a storage array, you have to do the following:

```
Item memory lastItem = array[array.length - 1];
array.pop();
```

It would be nice to be able to do simply

```
Item memory lastItem = array.pop();
```

## Specification

`pop()` should return a memory copy of the last element of an array, after removing it from the array, as shown above.

## Backwards Compatibility

The proposal would be fully backwards compatible because currently, there is no return value from `pop()` (so adding a return value cannot break code).

The only tricky thing that would need to be taken care of in the compiler is to eliminate the memory copy if the popped item is discarded, e.g. in the case of:

```
array.pop();
```

N.B. it would also be nice to have a `peek()` operation that would return the last item in the array, without popping it:

```
Item memory lastItem = array.peek();    // Same as: = array[array.length - 1];
```

**Comment by cryptonomicon46** [comment]
This seems like a useful thing to have. +1

**Comment by ekpyron** [comment]
The main problem here, is that the optimizer will have a hard time to remove the read from storage that would result from this (which at least won't be necessary if the array is not packed otherwise), as well as the memory allocation, in case it is not used.

So just implementing this naively right now, would probably result in all ``.pop()``s to become significantly more expensive, even without the return value being used.

There would be two ways to go about this:
- Have a special code generation path for the case in which the return value is not used (i.e. for ``array.pop();`` only as a statement). However, this is more tricky than it sounds due to corner cases like ``(array.pop());``, etc., and there is little precedent for severe special case handling like this.
- Consider better memory optimization a dependency for this (e.g. https://github.com/ethereum/solidity/issues/12351 or https://github.com/ethereum/solidity/issues/5107).

**Comment by lukehutch** [comment]
Optimizing the generated code in this case, and many optimizations like it, could be implemented if Solidity had a dataflow analyzer. Even if very basic dataflow is only implemented within functions (and not across function call boundaries, which is much more complicated), you could do a lot of useful things like check whether the return value of a `pure` or `view` function is not used, and either issue a warning (probably better), or optimize out the call entirely.

**Comment by ekpyron** [comment]
The current concept of the compiler is to *not* optimize on the Solidity level at all, but have a very simple and foolproof translation to Yul, and then optimize on the Yul representation (for which we have data flow analysis, which is much simpler on Yul, since the language is much more restricted). That's a good strategy most of the time - however, since Yul looses a lot of the type structure and lifetime information, it also makes things trickier, especially for memory optimizations. That's what the issues I linked are about - either transfer sufficiently much information from a Solidity-based analysis to Yul, or to add more structure to Yul to make such optimizations possible on the Yul level. So long story short: this is on the agenda; there are multiple ways to go about it; it may take a while - but eventually we'll have it and then we can be more relaxed about changing the language in ways that currently may still be wasteful lacking such optimizations.

**Comment by lukehutch** [comment]
Got it, thanks for the explanation.

Meanwhile, adding a `peek()` function would be an awesome task for a first-time contributor (I don't have the bandwidth right now, unfortunately).

**Comment by lukehutch** [comment]
@ekpyron OK, how about adding a `.popAndGet()` method that always makes and returns a copy, and leaving `.pop()` as-is?

**Comment by dev-tom-0108** [comment]
I think both are very useful for programming.
