### ISSUE TITLE
"TypeError: Linearization of inheritance graph impossible" when interface is both implemented and inherited

### ISSUE THREAD

**Issue by lukehutch** [ethereum/solidity#13142]
## Description

Compiling the following

```solidity
interface Iface {
}

abstract contract SuperContract is Iface {
}

contract SubContract is SuperContract, Iface {
}
```

gives error

```
TypeError: Linearization of inheritance graph impossible
 --> contracts/X.sol:7:1:
  |
7 | contract SubContract is SuperContract, Iface {
  | ^ (Relevant source part starts here and spans across multiple lines).

Error HH600: Compilation failed
```

## Environment

- Compiler version: solc 0.8.14

**Comment by cameel** [comment]
Oh, now that you gave a correct example I see how your problem was related to #13136. So yeah, it actually is the same problem. Sorry for that, I thought it was something else. Let's actually continue that discussion in #13136.

The bottom line is that if we implement the feature from #13136, this will compile as is. But for now the solution for your case is simple: change it to either `SubContract is Iface, SuperContract` or `SubContract is SuperContract`.

**Comment by lukehutch** [comment]
No problem, and ah! I hadn't considered that changing the order of listed inheritance would fix this. Thanks for the solution.
