### ISSUE TITLE
Allow "using BaseContract.virtualMethod" syntax when there are conflicting virtual methods.

### ISSUE THREAD

**Issue by leonwilly** [ethereum/solidity#13143]
## Abstract

```solidity 

abstract contract A {
   function doSomething() public virtual {}
}

abstract contract B {
  function doSomething() public virtual {}
}

contract C is A, B {
  // forced to re-declare the function just to call the correct implementation 
  function doSomething() public override(A, B) {
    B.doSomething();
  }
  // instead of a redundant re-declaration make use of the "using" keyword similar to C++
  using B.doSomething;
}

```

## Motivation

Reduce the amount of code that needs to be written thus reducing errors.

## Specification

Make use of the already builtin keyword "using" to tell the compiler which virtual function the derived contract would like to use. The compiler can then create the required override function or do a copy / paste of the overridden function into the derived contract.

```solidity
using [base].[method]
```

## Backwards Compatibility

I don't believe this would break backwards compatibility as the former method could still be used with the newer method providing a more readable and less verbose path for future development.

**Comment by ekpyron** [comment]
``using`` in Solidity has quite a different meaning in other contexts, so I'm not sure it's a good idea to overload it.
Also the conveniently short ``using B.something;`` drops the intentional requirement to explicitly override all bases (indicating that you realize that the you are aware of the independent requirements of the base interfaces and making the statement of their compatibility explicit).

We did have an earlier proposal to allow short-hand delegating implementations, though, that would be
```
function doSomething() public override(A, B) = B.doSomething;
```
Mainly since we could implement that even if all ``B.doSomething`` is ``external``.

**Comment by antoncoding** [comment]
I think this is a good feature to have! useful when you're overriding interface and a virtual contract
