### ISSUE TITLE
Strengthen Whiskers' matching

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#13226]
Whiskers' regex looks for `<..>` as opposed to tokenizing the input, so it is not able to detect truncated/mistyped input.

For example it can't detect that `<!b` is not terminated in`<?b> X <!b Y </b>`.

With some heuristics it could be improved: match for `<?`, `<!` and `</` and only allow identifiers which are terminated with `>`, otherwise it is invalid.

_Originally posted by @axic in https://github.com/ethereum/solidity/pull/13219#discussion_r907476574_

**Comment by rajgaur98** [comment]
Hi @axic ,
What should the code do?
1) Check `m_template` for the invalid tags like `<!b` as soon as it is passed to the Whiskers constructor and throw an error?
2) Check if the `tag` is valid when `operator(_parameter, _value)` is called and throw an error?

**Comment by rajgaur98** [comment]
My initial approach is, we apply a regex match for the whole template using regex
```(?:<\?[a-zA-Z0-9_$-]+>?)|(?:<![a-zA-Z0-9_$-]+>?)|(?:<\/[a-zA-Z0-9_$-]+>?)```
 for cases of `<?`, `<!` and `</`

This should match anything starting with `<?`, `<!` or `</` and ending with `>` or till any other special character is encountered.
For example, it will match `<?abc>` and `<?abc` both.

So now we can iterate over the matches, and see if the match ends with `>`, otherwise it is invalid and throw error.

Please let me know if I can go ahead and create a PR for this :)

**Edit**: came up with this `(?:<[?!\/][a-zA-Z0-9_$-]+(?:[^a-zA-Z0-9_$>-]|$))` regex, which will match for only unclosed tags like `<?a`, `<!a` or `</a` but not `<?a>`. We can directly return the first match saying tag `a` is unclosed.
