### ISSUE TITLE
Bad encoding for a dynamic array followed by a static calldata array

### ISSUE THREAD

**Issue by chancehudson** [ethereum/solidity#13249]
## Description

Inconsistent abi encode behavior with tuples containing both a dynamic array and fixed length array.

## Steps to Reproduce

```js
pragma solidity >=0.7.0 <0.9.0;

contract EncodeTest {
   
    struct Test {
        uint[] vals;
        uint[2] valsFixed;
    }

    function testEncode(Test calldata input) public pure returns (bytes memory) {
        return abi.encode(input);
    }

    function testDecode(bytes calldata input) public pure returns (Test memory) {
        return abi.decode(input, (Test));
    }
}
```

When calling `testEncode` with the following argument: `{ vals: [1, 2, 3], valsFixed: [1, 1] }` the following is received (split into chunks of 64 hex characters for readability): 
```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000060
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000000 // <- should be 0x03?
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000003
```

When abi encoding using web3 or ethers the following is received:

```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000060
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000003
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000003
```

<summary>web3/ethers code</summary>
<details>

```js
const { ethers } = require('ethers')
const Web3 = require('web3')

console.log(
  ethers.utils.defaultAbiCoder.encode(
    [`tuple(uint[] vals, uint[2] valFixed)`],
    [{vals: [1,2,3],valFixed: [1,1]}]
  )
)

const web3 = new Web3()
console.log(
  web3.eth.abi.encodeParameter(
    'tuple(uint[] vals, uint[2] valFixed)',
    [[1, 2, 3], [1, 1]]
  )
)
```

</details>

--

Furthermore, when using the `testDecode` function the first output does not decode the `vals` array, while the second output does. Is this expected or known behavior of `abi.encode`?

**Comment by cameel** [comment]
Thanks for the report! This does look like a serious bug. You're absolutely right about the expected encoding - the length should be 3, not 0. I can confirm that it's reproducible both in Remix IDE and in our semantic tests (executed via evmone).

With Remix I can reproduce it as far back as 0.7.0. Might be affecting older versions too, but Remix seems to have some issue with its version selector - choosing anything below 0.7.0 automatically switches back to 0.8.15 on compilation.

I tried some variations and:
- The length of either array does not matter.
- They must be arrays - bug is not reproducible when using `bool` or `uint` instead of the static one.
- The struct is not needed. It happens as well if we make arrays the arguments of the function.
- It does not happen if we swap the order and put the static array before the dynamic one.
- It only happens when the static array is in `calldata` (or a part of a `calldata` struct). For the dynamic array it does not matter.
- It does not happen when you change the base type of the static array to `address` or `uint128`. Changing the base type for the dynamic array does not seem to matter.
- It does not happen when both arrays are dynamic.
- Not only the explicit use of `abi.encode()` is affected. Same happens if you just return these arrays and let the encoding happen implicitly (which is not surprising since it uses the same mechanism).

### Semantic test
```solidity
semanticTests/abiEncoderV2/calldata_struct_dynamic_and_static.sol: FAIL
  Contract:
    pragma abicoder v2;

    contract C {
        function f(uint256[] memory a, uint256[1] calldata b) external returns (bytes memory) {
            return abi.encode(a, b);
        }

        function g(uint256[] memory a, uint256[1] calldata b) external returns (bytes memory) {
            return this.f(a, b);
        }
    }
    // ====
    // EVMVersion: >homestead

  Expected result:
  // f(uint256[],uint256[1]): 0x40, 0xff, 1, 0xffff -> 0x20, 0x80, 0x40, 0xff, 1, 0xffff
  // g(uint256[],uint256[1]): 0x40, 0xff, 1, 0xffff -> 0x20, 0x80, 0x40, 0xff, 1, 0xffff

  Obtained result:
  // f(uint256[],uint256[1]): 0x40, 0xff, 1, 0xffff -> 0x20, 0x80, 0x40, 0xff, 0, 0xffff
  Warning: Could not convert "bytes" to internal ABI type representation. Falling back to default encoding.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Could not convert "bytes" to internal ABI type representation. Falling back to default encoding.
  Warning: The call to "f(uint256[],uint256[1])" returned
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ff]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ff,ff]
  // g(uint256[],uint256[1]): 0x40, 0xff, 1, 0xffff -> 0x20, 0x60, 0x40, 0xff, 0
  Warning: Could not convert "bytes" to internal ABI type representation. Falling back to default encoding.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Could not convert "bytes" to internal ABI type representation. Falling back to default encoding.
  Warning: The call to "g(uint256[],uint256[1])" returned
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ff]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

  Attention: Updates on the test will apply the detected format displayed.
```

**Comment by cameel** [comment]
Turns out the Remix issue was actually a surprise feature :) It automatically changes version to match the version pragma (which enforces at least 0.7.0 here). After removing the pragma, it is reproducible down to 0.5.8, which seems to be the compiler version that introduced ABI encoding of calldata structs - below that I'm getting `UnimplementedFeatureError: Encoding struct from calldata is not yet supported.`

**Comment by cameel** [comment]
@Marenz The way I've been debugging it so far was to compile the two small contracts I'm posting below to Yul, diff their code and see if there is anything obvious that's wrong. I could not find anything so I think this needs some actual debugging, with the ability to inspect memory. Not sure if we have something like that in the test suite currently. I.e. we do have Yul tests and we have tests that print out memory but I'm not sure if you can combine the two :)

### My test files
```bash
solc --ir --debug-info none bad.sol > bad.yul
solc --ir --debug-info none good.sol > good.yul
```

#### `bad.sol`
```solidity
contract C {
    function f(uint256[5] calldata b, uint256[] memory a) external returns (bytes memory) {
        return abi.encode(a, b);
    }
}
```

#### `good.sol`
```solidity
contract C {
    function f(uint256[5] calldata b, uint256[] memory a) external returns (bytes memory) {
        return abi.encode(b, a);
    }
}
```
