### ISSUE TITLE
Bug: Compiler should not error on detecting multiple `// spdx` (non-natspec'd)

### ISSUE THREAD

**Issue by sambacha** [ethereum/solidity#13278]
solc should not error on detecting multiple `// spdx` (non-natspec'd) directives.

**Comment by cameel** [comment]
It's not a bug, it was done intentionally (with a minor bug that allowed it in some circumstances and was fixed in #10145). The license goes into metadata and having the compiler silently choose one of the multiple options arbitrarily for the user or even ignore them all is worse in my opinion.

What is your use case? Is there anything preventing you from fixing the license annotation?

The only situation I can think of where it would be a problem is flattening the whole project into a single file for verification. We don't (and really can't) support that. There are already many language features that depend on namespacing introduced by files and don't play well with flattening. Instead we recommend using Standard JSON for multi-file verification.
