### ISSUE TITLE
Solidity compiler issue on Arch Linux

### ISSUE THREAD

**Issue by leandro-driguez** [ethereum/solidity#13364]
## Description

The problem is that the compiler tries to look for the `libz3.so.4.8` library but it doesn't find version 4.8, the one it finds is 4.9, maybe just updating the binary and telling it to directly use the latest library, in this case 4.9, solves the problem.

## Environment

- Compiler version: solidity 0.8.15-1
- Operating system: Arch Linux
- Package: https://archlinux.org/packages/community/x86_64/solidity/

## Steps to Reproduce

```
$ solc
solc: error while loading shared libraries: libz3.so.4.8: cannot open shared object file: No such file or directory
```

**Comment by ekpyron** [comment]
Thanks for the report, but the right place for filing this issue is with archlinux package maintainers - we don't have any influence over their package builds :-). (I've just flagged the package out-of-date due to the 0.8.16 release; them rebuilding due to that may already solve this issue)

So since we can't do anything about this, I'm closing this issue.
