### ISSUE TITLE
Security: blog post, minified example

### ISSUE THREAD

**Issue by fulldecent** [ethereum/solidity#13373]
## Page

https://blog.soliditylang.org/2022/08/08/calldata-tuple-reencoding-head-overflow-bug/

## Abstract

The example in that page is not a minimal test case. We have found a minimal test case. Please consider updating to article to use this broader, minimal test case.

## Pull request

Test case:

```solidity
pragma solidity 0.8.15;

contract E {
    function f(bytes32[1] calldata c) external returns (bytes memory, bytes32[1] calldata) {
        return ("dan", c);
    }
}
```

And here is the test runner:

```solidity
contract Test {
    function test() external {
        bytes memory testB = "dan";
        bytes32[1] memory testC = bytes32[1]([bytes32(uint256(16))]);

        E e = new E();
        (bytes memory resultB, bytes32[1] memory resultC) = e.f(testC);

        require(keccak256(resultB) == keccak256(testB), "test B fail");
        require(resultC[0] == testC[0], "test C[0] fail");
    }
}
```

Discussed with @dtedesco1 during NFT/Web3 Community Service Hour https://phor.net/#hour

**Comment by cameel** [comment]
To be honest, it wasn't meant to be a minimal example. I chose it because it's still relatively simple while showing two interesting things:
1. You can have tuples at any nesting level. Argument list as a whole is a tuple but structs are also affected.
2. It's very common for a length field of some dynamic type to be overwritten but that's not the only possible case. Putting something dynamic in a struct/array makes it dynamic.

I don't mind adding another example, but I don't see what more it would add. Why do you think we need one?

Also, this is just as minimal:
```solidity
contract C {
    function f(bytes32[1] calldata c) external {
        abi.encode("dan", c);
    }
}
```
Or this:
```solidity
contract C {
    error E(bytes, bytes32[1]);
    function f(bytes32[1] calldata c) external {
        revert E("dan", c);
    }
}
```

**Comment by fulldecent** [comment]
Got it, thank you.

When I read it the first time, I thought that the nested parts were required. So I worked it down to the minimal thing that's affected. That's what I need to start going around looking for vulnerabilities.

**Comment by cameel** [comment]
ok, makes sense. I guess I can add a sentence mentioning that the case I'm describing is not the simplest possible case.
