### ISSUE TITLE
Impossibility of getting current function selector in nested calls via `msg.sig`

### ISSUE THREAD

**Issue by mojtaba-eshghie** [ethereum/solidity#13412]
## Description

I am working on a project where I need the current function signature in a sequence of function calls. The functions are marked as public but they are called within the contract by each other. In the following `steps to reproduce` section function if we send a transaction to function `one`, it will call `two`, however, if we look at `msg.data` or `msg.sig` it will return the signature of the original transaction for function `one`. This makes it impossible to distinguish between different functions in solidity code in nested calls as calldata returns only the first function signature in the chain. Is there a way to get around this? 

## Environment

- Compiler version: 0.8.15
- Target EVM version (as per compiler settings): default for Remix
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix vm
- Operating system: -

## Steps to Reproduce

```
contract MsgDataTester {
    event MsgDataLogger(bytes4 data);

    function one(uint256 a) public {
        emit MsgDataLogger(msg.sig);
        two(2);
    }

    function two(uint256 b) public {
        emit MsgDataLogger(msg.sig);
        
    }
}
```
-->

**Comment by cameel** [comment]
`msg` is a global object specifically meant to represent the transaction input. The fact that the value is the same in nested calls is the expected behavior.

If you're interested in the selector of the current function instead, you should use the `.selector` member on that function:

```solidity
contract MsgDataTester {
    event MsgDataLogger(bytes4 data);

    function one(uint256 a) public {
        emit MsgDataLogger(this.one.selector);
        two(2);
    }

    function two(uint256 b) public {
        emit MsgDataLogger(this.two.selector);
    }
}
```

> This makes it impossible to distinguish between different functions in solidity code in nested calls as calldata returns only the first function signature in the chain. Is there a way to get around this?

`two(2)` in your code is an internal call so you can't really "distinguish" it in the sense that it's running in the same context. It has the access to the same stack, memory, etc. If you made it an external call (`this.two(2)`), `msg.sig` would have a different value just as you expect it. But I'm not sure if this is really what you're after. External calls to your own contract are not a common thing and I suspect that's not what you need.
