### ISSUE TITLE
Request: Contract AST nodes should include info on what internal functions the contract uses in internal function pointers

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#13425]
## Abstract & Motivation

Contracts compiled with `viaIR` turned on use a new representation for internal function pointers, one that uses an internal index instead of a pair of PCs.  We'd like to be able to decode such new-style pointers.  (Yes, Truffle Debugger doesn't work well with `viaIR` contracts at the moment, but remember we also want to be able to decode such pointers in storage with Truffle Decoder!)  While we haven't implemented this yet (our open issue for it is [here](https://github.com/trufflesuite/truffle/issues/5466)), for the most part, it seems like it should be doable.  Unfortunately, free functions and internalized library functions pose a problem.  (**Edit**: Turns out all functions pose a problem, oops!)

If the contract does not make use of either of these, then mapping an index to its corresponding function is straightforward enough; functions are listed in the order they're defined, and if there's inheritance, base contracts come before derived contracts.  (**Edit**: Oops, no it's not!  Functions that are never pointed to don't get indices!  So actually this is a problem regardless!)  However, free functions and internalized library functions pose more of a problem.  They come after functions defined within the contract or its ancestors, but beyond that, it's not clear that there's any reasonable way to predict the order.  More to the point, even if the order is predictable, the problem is then to determine which ones are actually used, since unused functions do not get indices.

I don't see any good way to detect this information from the AST at present.  Or, I have some ideas, but I am skeptical that they would work in full generality.  (Possibly I should do some more experiments to see, but I figured I should really just go ahead and file this issue first.)  So, it would be nice if this information would be provided, with a list of used internal functions, in order, attached to the `ContractDefinition` node.  Of course, this is assuming that I am correct and there is no other good way to determine this information; if you know of one, then perhaps this feature request is unnecessary!

## Specification

Each `ContractDefinition` node of the AST should include a field -- I'll call it `usedInternalFunctions` to parallel `usedErrors` but obviously the name is immaterial -- which consists of an array of AST IDs.  The AST IDs would be the IDs of the `FunctionDefinition` node for every internal function which is included in the function's bytecode.  (**Edit**: Oops, no, it should only include the ones that get indices.)  This means both functions in the contract itself declared `public`, `internal`, or `private`; functions from base contracts declared `public` or `internal`; and any used free functions and any internalized `public` or `internal` library functions.  The order of these IDs should be the same order that would be used by the internal function dispatcher if compilation were performed with `viaIR` turned on, but ideally the field should be present regardless of compilation settings.  Every function that would get an index should be included, and every function that would not get an index should not be included.  (Note: If other things I've said conflict with this, this should obviously take precedence, as it's the point!)  Depending on how you want to do it, you could also include some sort of dummy/internal ID as the first element of the array, before the IDs fo the actual functions, similar to how references to builtins use internal IDs.  If you do it that way then the indices will match with no shift necessary.

## Backwards Compatibility

There should be no backwards compatibility issues.

**Comment by haltman-at** [comment]
Oops -- turns out I made a bad assumption when writing this issue... I thought all internal functions got indices.  Seems like in fact only ones that are pointed to get indices!  That changes things massively, and makes not having this much more of a problem.  Hoping this might possibly be done sooner rather than later?  To be clear, the important thing here is getting the indices, not getting a list of all the functions.  I wrote above that I want a list of all the internal functions, but, no, what I want is the ones that get indices, so we can decode.

Thank you!

**Comment by gnidan** [comment]
@ekpyron pinging you because you told me to

**Comment by ekpyron** [comment]
> @ekpyron pinging you because you told me to

Thanks - I finally got around to actually have a look, sorry for the delay.

This most certainly sounds like debugging information we should provide. In general, in cases like this, don't hesitate to open issues and bug us in the matrix channels, since for these kinds of issues it's always easier and more future-proof for us to output the required data instead of reverse-engineering (even if that only helps for future versions and you may still have to find a solution for version up until any kind of output from us, but still better than staying with a reverse-engineered solution only only to have us break it eventually). We'll try to react quicker next time :-).

If I understood the issue correctly, I see several ways to address this:
- Annotate the push of the internal function IDs itself as referring to an internal function on the Yul, resp. bytecode level.
- Add an optional field like "internalFunctionID" to the AST node of internal functions, which would contain the ID for all functions that get one.
- Some dedicated debugging output for handling internal function pointers.

The first option would probably be the most future-proof and could be part of the (hopefully) upcoming stack maps (i.e. we could mark internal function pointer values specifically whenever they occur on stack, which would be completely transparent to any changes we may ever make wrt such IDs). However, it may delay things further, since we don't have much progress on the stack map specification just yet.

In comparison, the second option would probably be rather easy and straightforward, but harder to guarantee to remain stable over time. The third option would be contingent on more debugging format discussions and thus also cause further delays.

Staging this issue for our next team discussions in any case.

**Comment by haltman-at** [comment]
Well, I did open an issue once I realized the problem!  I don't really hang around the Matrix channel I'm afraid; when I have occasionally in the past, very little of it has been relevant to me.  In general I've followed the process of, if something *needs* to be changed (IMO), file an issue; ask on Matrix in the case where I'm not sure.  Are you saying I should alert you on Matrix even in the case where I'm filing an issue, for extra visibility?

I suppose if I hang around on the Matrix channel I could potentially notice this sort of thing earlier, but given how little is relevant to me there I'm just not sure that's something I can rely on.  In this case I noticed the problem late because, well, I hadn't really tried out `viaIR` much, and in fact I learned of the issue not from trying out `viaIR` with internal function pointers (not an experiment I'd have thought to run) but rather because I was browsing through documentation and happened across the note about it!  So that was basically luck...

But yeah I'm OK with basically any solution as long as it contains sufficient information.  Although I would prefer something that can go in as soon a Solidity version as possible, so that we can handle code compiled with such versions (even if there's going to be a better solution later).

**Comment by cameel** [comment]
@haltman-at I think this was what you mentioned on the call today :) It seems to me that there's a bit of a misunderstanding here. IMO @ekpyron just meant that it's fine to be a bit louder and more demanding about these kinds of issues because fixing them quickly makes things easier. So if we miss it somehow and don't react, we don't mind anyone coming to the channel and bugging as about it. Not that it's necessary have to hang in there all the time. Filing an issue was the right way to go about it and we should have noticed and reacted earlier. Just when that does not happen for whatever reason, pinging on the channel is usually a pretty effective way to get our attention to it.

**Comment by ekpyron** [comment]
Yes, that's exactly what I meant indeed.
As for the issue: we'll try to do something about it in the next release - we're just simultaneously implementing experimental EOF support, and EOF may have jump tables, which may affect how we will want to assign internal function IDs in the future, so we may still end up slightly changing the internal function IDs before starting outputting this information for them, but haven't gotten around to deciding that yet (taking into account tooling-compatibility, etc.).

**Comment by ekpyron** [comment]
@r0qs will slowly start actually implementing this.

We'll be going for the following of the options above:
- Add an optional field like "internalFunctionID" to the AST node of internal functions, which would contain the ID for all functions that get one.

This will entail moving some logic that we currently only have in code gen out into earlier analysis stages, s.t. we have the information available to actually store in the AST.
