### ISSUE TITLE
Rewrite `FunctionCallGraph` tests as soltest test suite

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13426]
[`FunctionCallGraph`](https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/FunctionCallGraph.h) is currently [covered with boost tests](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/analysis/FunctionCallGraph.cpp). These tests are generally harder to maintain and update than our soltest-style tests.

We should define a custom test case class for them and put expectations in annotations. See [`StackLayoutGeneratorTest`](https://github.com/ethereum/solidity/blob/develop/test/libyul/StackLayoutGeneratorTest.h) and [`test/libyul/yulStackLayout/`](https://github.com/ethereum/solidity/tree/develop/test/libyul/yulStackLayout) for an example of such a custom test suite and test cases based on it.

### Example
We should be able to replace the following test case:
https://github.com/ethereum/solidity/blob/a3de6cd60e4277051a1cc0f8eb8f1516e6c0ec57/test/libsolidity/analysis/FunctionCallGraph.cpp#L253-L292

with a `.sol` file that looks like this:
```solidity
function free() {}

library L {
    function ext() external {}
    function pub() public {}
    function inr() internal {}
    function prv() private {}
}

contract C {
    function ext() external {}
    function pub() public {}
    function inr() internal {}
    function prv() private {}
}
// ----
// CREATION
//     contract C
//     library L
// DEPLOYED
//     contract C
//         Entry -> function C.ext()
//         Entry -> function C.pub()
//     library L
//         Entry -> function L.ext()
//         Entry -> function L.pub()
```

**Comment by 0xGeorgii** [comment]
Hi @cameel I'm new to Solidity but want to dig deeper into it. May I elaborate on this issue and provide an improvement? It takes some time and I will ask questions. Hope it won't be too bothering.

**Comment by matheusaaguiar** [comment]
Hi @GeorgePlotnikov , maybe this issue is not really a good first issue for someone starting out, because it could demand understanding of how other test classes are implemented. I am not sure how long you are digging into solidity or how much time you are dedicating to it. So in order to give you more options, I'd like to suggest some other good first issues:
 - [Pretty print expected json output of command line tests](https://github.com/ethereum/solidity/issues/7665)
 - [Errors reported for modifier overloading should outright say that overloading is not allowed](https://github.com/ethereum/solidity/issues/12332)
 I just wanted to give you more options and remark that this is a medium size task, so if you are new, you might want a smaller one.

**Comment by 0xGeorgii** [comment]
hi @matheusaaguiar thanks for clarifying. Let me consider these two before. If this one will be still orphaned I grab it.
