### ISSUE TITLE
Missing optimizer rules for `if (b == true)` to `if (b)`

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/solidity#13442]
Here's the example: https://godbolt.org/z/Mbs9bd5nr

Similarly for `if (b == false)`  to `if(!b)`

**Comment by hrkrshnn** [comment]
This should probably be a peephole optimizer rule, especially to apply for `jump` / `jumpi` conditions.

**Comment by leonardoalt** [comment]
Why are people writing `if (b == true)` in the first place? In your example why not just `return a`?

**Comment by hrkrshnn** [comment]
Yeah, not ideal to write this, but the compiler should optimize the `b == true` case.

**Comment by chriseth** [comment]
The peephole optimizer rules in the PR look quite extensive to me. We should try to do as much as possible in the rulelist. Of course, the rulelist does not know if the expression is followed by a jumpi.

In the example from the linked godbolt code, there are some expressions that strike me as unoptimized:

1) ``iszero(eq(value, iszero(iszero(value))))``
2) ``eq(iszero(iszero(var_a)), 0x01)``

The first could be turned into a rather complex simplification rule, because it is the condition to check for a bool to be cleaned. If in a bolean context, we could simplify the whole thing to `shr(1, value)`, but we don't know if we are in a boolean context. We could simplify to `iszero(iszero(shr(1, value))` and hope the peephole optimizer will do the rest (which already has a rule for iszero iszero jumpi).

2) This could be done by ``eq(iszero(X), 0x01) -> iszero(iszero(X))``
