### ISSUE TITLE
Nightly builds in solc-bin broken due to git's `safe.directory` check

### ISSUE THREAD

**Issue by cameel** [ethereum/solidity#13506]
Nightly builds in solc-bin seem to have been failing for 2 weeks now: [8239563561](https://github.com/ethereum/solc-bin/runs/8239563561).

```
fatal: detected dubious ownership in repository at '/root/project'
To add an exception for this directory, call:

	git config --global --add safe.directory /root/project
```

This seems to be due to the checks introduced recently by git to address a security vulnerability: [Git security vulnerability announced](https://github.blog/2022-04-12-git-security-vulnerability-announced/).

**Comment by r0qs** [comment]
@cameel looking at this issue, I also noted that [build_emscripten.sh](https://github.com/r0qs/solidity/blob/develop/scripts/ci/build_emscripten.sh) creates the `emscripten_build` folder under the solidity directory tree as root.
As far as I could see, the docker instance needs to run with root user because of [this line](https://github.com/r0qs/solidity/blob/develop/scripts/ci/build_emscripten.sh#L44) to install lz4. The volume is also mounted under the `/root` directory in the emscripten container.

Since the `build_emscripten` script will run as root in the container to execute the apt-get, the git commands in the script will be performed by a different user, and git will detect the changes in the ownership from the current user when traversing files, which will trigger the issue.

I do not know why the `lz4` need to be installed in the build script and cannot be directly installed in the [solbuildpackpusher docker image](https://github.com/ethereum/solidity-buildpack-deps/blob/master/docker/Dockerfile.emscripten).
My proposed solution is that we move the installation of lz4 to that image, letting the script only responsible for building emscripten and not installing dependencies, and change the `docker run` command to run as the current user and mount the volume under the emscripten user, like so:

```
docker run -v "$(pwd):/home/emscripten/project" -w /home/emscripten/project \
    --user "$(id -u):$(id -g)" \
    solbuildpackpusher/solidity-buildpack-deps@sha256:f1c13f3450d1f2e53ea18ac1ac1a17e932573cb9a5ccd0fd9ef6dd44f6402fa9 \
    ./scripts/ci/build_emscripten.sh "$BUILD_DIR"
```

We also need to update the WORKSPACE variable [here](https://github.com/r0qs/solidity/blob/develop/scripts/ci/build_emscripten.sh#L46)

This will fix the permissions issues without requiring to change the `safe.directory` configuration. The emscripten user is already created by the base image (emscripten/emsdk) used in the solbuildpackpusher.

Let me know if this sounds reasonable and I can open a PR with the fix.

**Comment by r0qs** [comment]
Actually, I just found another dockerfile that seems to be the correct one here https://github.com/ethereum/solidity/blob/develop/scripts/docker/buildpack-deps/Dockerfile.emscripten
And it already install the lz4, so we just need to remove it from the `build_emscripten` and change the user and volume mount.

**Comment by cameel** [comment]
Sounds good. Let's try this. I do think it's better to avoid using `root` in docker images when possible, it's just that that's the easiest way for people to set it up so that's probably why our image does it.

> I do not know why the lz4 need to be installed in the build script

It is installed in the image. See #13424. The one you're looking at looks like an old repo created by @aarlt that we ended up not using. Or is it actually used somewhere? We should either delete it or keep it up to date with our current images, which are in https://github.com/ethereum/solidity-buildpack-deps.

I don't remember why we install it both in the script and in the image (pinging @Marenz) but this is a very recent change. There should be no problem changing that as long as the images still build correctly.

**Comment by cameel** [comment]
> Actually, I just found another dockerfile

Right. In any case, try changing it.

BTW, check out [`buildpack-deps/README.md`](https://github.com/r0qs/solidity/blob/develop/scripts/docker/buildpack-deps/README.md) for info on how building these images works. They're versioned and built automatically but not used automatically by CI - hashes in the CI config need to be updated first.

Would be simpler if we did not have to hard-code the hashes, but there was some issue with pulling from DockerHub via tags. That's another thing you might want to improve in due time - @aarlt and @ekpyron know the details of what exactly the problem was and I'm sure it's also written down in one of the old PRs/issues from the time it was being set up. I might be able to find it if need be.

**Comment by ekpyron** [comment]
The main reason for using hard-coded hashes is actually security. It makes us robust against repushing docker images or compromised docker hub or all sorts of things like that. So I actually wouldn't touch that :-).

Of course the hashes are just posted by CI that may be compromised as well, but the surface there is much smaller.

**Comment by r0qs** [comment]
It seems that `/root/project` is used in much more places than I expected. So it may require some refactoring.

**Comment by cameel** [comment]
I just realized that we may have one more problem here that probably did not show up only because the nightly is broken. I.e. we enabled branch protection in solc-bin. The action commits nightlies directly to the main branch so I suspect it will still be failing even after we fix the issue here.

**Comment by r0qs** [comment]
Hum...but it uses the same `build_emscripten.sh` script as solidity for the build: https://github.com/ethereum/solc-bin/blob/gh-pages/.github/workflows/nightly-emscripten.yml#L78
This script in turn, calls the one shared with the CI (`scripts/ci/build_emscripten.sh`).

So if we add the `safe.directory` in the `scripts/ci/build_emscripten.sh` before the git operations, it should work for both.

**Comment by r0qs** [comment]
Oh, now I see what you mean, in the `add-nightly-and-push` action in the solc-bin workflow.

**Comment by ekpyron** [comment]
> I just realized that we may have one more problem here that probably did not show up only because the nightly is broken. I.e. we enabled branch protection in solc-bin. The action commits nightlies directly to the main branch so I suspect it will still be failing even after we fix the issue here.

I guess this was probably the reason why branch protection wasn't enabled there in the first place :-). We can disable it again, if there's no way around doing that for automatically pushing nightlies.

**Comment by cameel** [comment]
I see in settings that there's an option to whitelist pushes from specific users. The problem is that the action is not really a user. It just sets some name and e-mail and that does not have a corresponding github account I could whitelist.

> - [ ] **Allow specified actors to bypass required pull requests**
>     Specify people, teams, or apps who are allowed to bypass required pull requests.

**Comment by ekpyron** [comment]
It says "people, teams or apps"... at least the docker hash comments like https://github.com/ethereum/solidity/pull/13438#issuecomment-1228393223 are posted by a github action app from the looks of it... maybe it works via that?

**Comment by r0qs** [comment]
According to the github documentation it is possible to `allow specified actors to bypass required rules` when using branch protection. And the actor can be a github app but currently it cannot be a github action.

```
You can only give push access to a protected branch, or give permission to create a matching branch, to users,
teams, or installed GitHub Apps with write access to a repository. People and apps with admin permissions to a 
repository are always able to push to a protected branch or create a matching branch.
```

However, there are some suggestions of possible workarounds here: https://github.com/community/community/discussions/13836
Basically, we can: 1) build a github app and grant it access to bypass the pull request rules or 2) have a user who has admin permissions to create a PAT, use it as a secret in the github action. As it will have admin permissions it can bypass the restriction.

Option 1 seems to be the right direction to go: https://github.com/orgs/community/discussions/25305#discussioncomment-3247401
But maybe this can also work: https://github.com/ridedott/merge-me-action
