### ISSUE TITLE
feat: introduce `block.prevrandao` as alias for `block.difficulty`

### ISSUE THREAD

**Issue by pcaversaccio** [ethereum/solidity#13512]
## Summary

[EIP-4399](https://eips.ethereum.org/EIPS/eip-4399) renames the `DIFFICULTY (0x44)` opcode to `PREVRANDAO (0x44)`. The return value of the `DIFFICULTY (0x44)` instruction after this change is the output of the randomness beacon provided by the beacon chain.

For reference, I implemented this feature in Vyper [here](https://github.com/vyperlang/vyper/pull/3085).

**Comment by axic** [comment]
Should be consider not making it a blank alias (like we had for `sha256` vs `sha3`), but enable one or the other based on the `evmVersion` selected?

I think that would make more sense, as it gives an indication to the user of a potential issue. Of course one can deploy a contract compiled for an older evm version, so it is not bulletproof.

**Comment by pcaversaccio** [comment]
@axic I get your point - for that reason actually, we put a warning depending on the EVM version used (see [here](https://github.com/vyperlang/vyper/pull/3085/files#diff-452732981c7a1a928e9f249c7b14c723695de3d6635568ccc8899b6cab2fc54bR284)).

**Comment by cameel** [comment]
I think it might be better only to switch between which one is the default depending on the EVM version but still accept both. Otherwise it would be breaking regarding the asm import (we're currently implementing). And would also change assembly output which probably should also be considered breaking since tools may depend on that.

**Comment by AliMohammadnia** [comment]
Hi guys I am Ali I want to learn blockchain programming How should I practice and what programming language should I use????❤️

**Comment by ekpyron** [comment]
Yeah, the opcode name in assembly output is something to think about.
What's your thoughts about making this a full hard switch depending on the evm version setting? I.e. remove ``block.difficulty`` entirely for Paris and also only emit and parse ``prevrandao`` in assembly - while keeping everything as is for <Paris?
The error message for the use of ``block.difficulty`` or the opcode with evm version set to paris could mention that you can just specify a different evm version to make it work again.

Given that you could restore the previous behaviour easily,  makes it less of a severe breaking change. We could also hold off on making paris the default evm version until we have tooling feedback on this...

EDIT: also promoting this to ``must have`` since #13517 depends on a decision on this.

**Comment by ekpyron** [comment]
Just to clarify - this will entail:
 - renaming the Yul builtin, resp. inline assembly builtin, for the opcode
 - renaming the name of the opcode for importing and exporting evmasm
 - renaming the member of ``block`` on the solidity level

Anything else I missed?

**Comment by mryalamanchi** [comment]
Let's assume to remove the `block.difficulty` if it's paris version and replace it with `block.prevrandao`.

What would happen to the Contracts that were previously using block.difficulty and decided to upgrade (using upgradable SM architecture) from >=0.8.x to the latest one which has this change, and suddenly the compiler throws warning or doesn't compile?

**Comment by cameel** [comment]
@mryalamanchi It would not affect upgrades (i.e. storage layout) at all. The compiler should still produce the same exact bytecode even with the new name.

At the EVM level the way the opcode works will change immediately with the merge whether we do anything or not. The change in the compiler is simply to reflect that change in meaning but does not itself change that meaning.

**Comment by cameel** [comment]
So far the biggest problem seems to be the fact that this would affect portability of third-party libraries. They would no longer be able to provide code that uses `block.difficulty()` and still works when EVM is set to `paris`. For this reason we're likely to just keep both names available until the next breaking release.

**Comment by cameel** [comment]
Decision from the call today: we'll do it the same way Vyper does, i.e.
- we’ll keep both `difficulty` and `prevrandao` usable on all EVM versions.
- the EVM version will decide whether we output one or the other,
- there will be a warning if you use `difficulty` on `paris` and when you use `prevrandao` on older versions.

**Comment by ekpyron** [comment]
Just as a small addition: on the Yul level this will mean adding ``prevrandao`` as pseudo-builtin only for now, i.e. to introduce it, but to also allow shadowing it by a user-defined function called ``prevrandao`` (while emitting a warning). We should then promote it to a proper builtin (disallowing any user-defined functions with that name) with 0.9.

**Comment by Marenz** [comment]
> the EVM version will decide whether we output one or the other,

Aren't we outputting the opcode anyway, which is staying the same?

**Comment by Marenz** [comment]
Started working on this in https://github.com/ethereum/solidity/tree/paris-oh-paris (no pr yet)

**Comment by cameel** [comment]
> Aren't we outputting the opcode anyway, which is staying the same?

I meant the name of the opcode, which does change. It's the numeric value used in bytecode (`0x44`) that stays the same. So bytecode will not change but Solidity, Yul and EVM asm output will.

**Comment by immujahidkhan** [comment]
`uint256 seed = uint256(keccak256(abi.encode(block.timestamp, totalTickets)));`
