### ISSUE TITLE
memory writes in yul don't happen unless alongside a hardhat console log

### ISSUE THREAD

**Issue by thedavidmeister** [ethereum/solidity#13530]
## Description

I'm really not sure why this is happening but it seems memory writes do not happen in one of my functions.

As soon as I include console logs from hardhat the writes start to take effect.

This happens with or without compiler optimisations enabled.

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/022adea41d0c891bf8d92c117bcc4a18fb98278f

removing this

https://github.com/beehive-innovation/rain-protocol/actions/runs/3061601203/jobs/4941572318#step:4:400

causes this test to fail, which means that it is not writing a value to memory that it is looking for when it tries to read it back

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/c967e0d3d64eca79777f2040ce6482b1487cb402

disabling optimiser doesn't help

https://github.com/beehive-innovation/rain-protocol/actions/runs/3061791728/jobs/4941999523

test still fails

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/c0c20e92df01a139436d5a19309aab75376cf254

adding console log fixes the test

https://github.com/beehive-innovation/rain-protocol/actions/runs/3061817876/jobs/4942058769

this passes now

## Environment

- Compiler version: 0.8.15 and 0.8.17 tested
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): hardhat
- EVM execution environment / backend / blockchain client:
- Operating system: mac/linux

## Steps to Reproduce

I don't have a minimum reproduction because it seems like some low level yul issue that i have never seen before, i've been calling this `eval` function many times in many different places and never noticed this before.

very open to debugging ideas, it's difficult to debug given the console log makes the bug disappear

**Comment by thedavidmeister** [comment]
i thought that perhaps the issue is that i'm not keeping an explicit reference to the allocated `uint[]` in solidity

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/1220cf5c59490ac24b64fff69565c3ebe65ff9b4

that still fails tests

https://github.com/beehive-innovation/rain-protocol/actions/runs/3076479876/jobs/4970663451

**Comment by thedavidmeister** [comment]
i tried setting the state function to view instead of pure, this is the only function called by the test script, i thought perhaps somehow that it being pure meant the compiler would elide the memory writes

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/565dea0743fe613ac865e2e1710f6ada88b14090

that does not work either

https://github.com/beehive-innovation/rain-protocol/actions/runs/3076500199/jobs/4970695379

**Comment by thedavidmeister** [comment]
putting a console log inside the `eval` function rather than alongside it

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/c1689fdf479a2478258ecc70c4a2b09f56758632

does cause the tests to pass

https://github.com/beehive-innovation/rain-protocol/actions/runs/3076516870/jobs/4970722734

**Comment by thedavidmeister** [comment]
ok i have a clue

this is what the values in memory look like when it fails:

```
~~~
0 115183058774379759847873638693462432260838474092724525396123647190314935293775
1 912823093544680850579175995568783282090442467040
2 5
3 6
4 1258222091183498019947225577994668400935317599945
5 7
6 8
7 115183058774379759847873638693462432260838474092724525396123647190314935293775
8 912823093544680850579175995568783282090442467040
9 1
10 2
11 1258222091183498019947225577994668400935317599945
12 3
13 4
14 115183058774379759847873638693462432260838474092724525396123647190314935293775
15 20
16 115183058774379759847873638693462432260838474092724525396123647190314935293775
17 912823093544680850579175995568783282090442467040
18 5
19 6
***
```

this is what it looks like when it passes

```
~~~
0 115183058774379759847873638693462432260838474092724525396123647190314935293775
1 912823093544680850579175995568783282090442467040
2 5
3 6
4 1258222091183498019947225577994668400935317599945
5 7
6 8
7 115183058774379759847873638693462432260838474092724525396123647190314935293775
8 912823093544680850579175995568783282090442467040
9 1
10 2
11 1258222091183498019947225577994668400935317599945
12 3
13 4
14 115183058774379759847873638693462432260838474092724525396123647190314935293775
15 115183058774379759847873638693462432260838474092724525396123647190314935293775
16 115183058774379759847873638693462432260838474092724525396123647190314935293775
17 115183058774379759847873638693462432260838474092724525396123647190314935293775
18 0
19 0
***
```

we can see that the 4 duplicate values from index 14-17 in the good run ~~are collapsed into a single value at index 14 in the bad run~~

~~looks like the function call to `state` (linked in comment above) is simply ignored somehow when the output is the same~~

somehow the bad run is copying from the start of what was previously written, including the length (20) of what was allocated for the writes

**Comment by thedavidmeister** [comment]
i tried removing `("memory-safe")` from the assembly responsible for copying the above data into place

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/1f6860e5f3589a8cb325c56dcc5a390bf9bdc32f

still failing 

https://github.com/beehive-innovation/rain-protocol/actions/runs/3077145101/jobs/4971798589

this is the code that's somehow copying from the wrong location when console logs are absent:

```solidity
    /// Stack a value from the state.
    function state(
        VMState memory state_,
        Operand operand_,
        StackTop stackTop_
    ) internal view returns (StackTop) {
        unchecked {
            uint256 type_ = Operand.unwrap(operand_) & 0x1;
            uint256 offset_ = Operand.unwrap(operand_) >> 1;
            assembly {
                mstore(
                    stackTop_,
                    mload(
                        add(
                            mload(add(state_, mul(0x20, type_))),
                            mul(0x20, offset_)
                        )
                    )
                )
            }
            return StackTop.wrap(StackTop.unwrap(stackTop_) + 0x20);
        }
    }
    ```

**Comment by cameel** [comment]
This could be an issue in the compiler but could just as well be something in your code. `console.log()` emits events, which involves ABI-encoding and this can leave some garbage in the scratch space in the first 2 memory slots (addresses `0x00-0x64`) and in the unallocated space past the free memory pointer. If you have a bug and accidentally depend on the contents of these areas, something like a silly `console.log("")` could affect the behavior of your contract.

I tried looking into the problem and managed to reproduce it in your project but we'll really need a stripped down repro to figure this out. I know nothing about the codebase and there's just too much of it. There's nothing that immediately stands out as wrong so we'll just have to compare and analyze the Yul code generated from the two versions and that's much easier to do when all the code unrelated to the bug is not there.

Could you do the following?
1) Minimize inputs. I see that `should preview defined flow IO for ERC1155 (multi element arrays)` inside `test/Flow/Flow/previewFlow.ts` is the test that fails and it basically runs contract constructor and then calls `previewFlow()`. Please use that to create a small, isolated test without any bits that are not essential to reproducing the bug. Ideally, you'd end up with just a few external calls that don't depend on any JS code so that we can reproduce the problem directly with `solc` and a debugger, without going through Hardhat.
2) Extract the relevant contracts. I see that the failing path is `Flow.previewFlow()` -> `_previewFlow()` -> `stackToFlow()` -> `consumeSentinel()`. So we only need `Flow.sol`, `LibFlow.sol` and `LibStackTop.sol`. Please take just these contracts and anything they depend on.
3) Minimize the contracts. Please remove anything non-essential to reproducing the bug from the contracts.

Ideally, you'll either be left with just a small bit of code that clearly shows that the compiler is doing somethting wrong - and we can take it from there - or you'll find some problem in your own code along the way.

**Comment by cameel** [comment]
By the way, there were two recent bugs, which could potentially produce somewhat similar effects:
- [Optimizer Bug Regarding Memory Side Effects of Inline Assembly](https://blog.soliditylang.org/2022/06/15/inline-assembly-memory-side-effects-bug/)
- [Head Overflow Bug in Calldata Tuple ABI-Reencoding](https://blog.soliditylang.org/2022/08/08/calldata-tuple-reencoding-head-overflow-bug/)

The first one can result in the compiler removing an `mstore()` under very specific conditions. The second might mis-encode data. But since you say you're seeing it on 0.8.17 and it's reproducible even without the optimizer this seems unlikely. It's either a new bug or something in your contract.

**Comment by thedavidmeister** [comment]
@cameel i'm fairly sure that i'm not reading or writing to the first two memory slots on this codepath, i hear you on the repro though, i'll try to make something simpler that shows the same behaviour

**Comment by thedavidmeister** [comment]
@cameel so looks like adding `bytes memory foo_ = abi.encodeWithSignature("log(bytes)", "");` to eval "fixes" the issue in the same way as the console log, so that's some info

**Comment by thedavidmeister** [comment]
explicitly zeroing the first 2 memory slots does nothing to help, but adding `0xA0` to the pointer at `0x40` makes tests pass

https://github.com/beehive-innovation/rain-protocol/pull/452/commits/4d89dcaa89e590a5853b96cbb4579fe5e3793bc7#diff-84a5ca0e7658e2f6de553fa9797f941b3251296cfcb0343a9840e35dadbc04a3R297

**Comment by thedavidmeister** [comment]
@cameel ok i found the bug in our contract, thanks for the tips!

**Comment by cameel** [comment]
Great! Thanks for reporting anyway. If there's a chance it's a compiler bug, we definitely want to investigate.
