### ISSUE TITLE
Replace `boost::filesystem` with `std::filesystem`

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#13575]
Tracking issue for this task. See also https://github.com/ethereum/solidity/pull/7263#discussion_r314240318

**Comment by cameel** [comment]
My comment from an earlier discussion on the topic (https://github.com/ethereum/solidity/pull/11650#issuecomment-879857238):
> I think it's risky. There are subtle differences between the two that affect normalization (see for example https://github.com/boostorg/filesystem/issues/88#issuecomment-435102621) and I think we do not have enough test coverage related to paths to just swap one with another and expect things not to be broken in some way. The new stuff I'm adding is covered pretty extensively but the existing code mostly is not.

I really think we need better coverage before we do this because these libraries have subtle differences that will affect us in corner cases. Note for example that we're using `filesystem` for resolving relative imports (even though they're not real paths):
https://github.com/ethereum/solidity/blob/2201526a90a7ae318273e16480a88b4c7df8e690/libsolutil/CommonIO.cpp#L141-L159
