### ISSUE TITLE
Wrong behaviour achieved by example code - Voting example

### ISSUE THREAD

**Issue by mauricedesaxe** [ethereum/solidity#13590]
## Page

[Solidity by Example - Voting](https://docs.soliditylang.org/en/latest/solidity-by-example.html#voting)

## Abstract

In the example of the voting contract, the `delegate` method, at its very end, has this piece of code:

```solidity
if (delegate_.voted) {
    // If the delegate already voted,
    // directly add to the number of votes
    proposals[delegate_.vote].voteCount += sender.weight;
} else {
    // If the delegate did not vote yet,
    // add to her weight.
    delegate_.weight += sender.weight;
}
```

The above code does indeed compile, but doesn't achieve the wanted behaviour. 

To exemplify what I mean, imagine: a dev would build on top of the example to implement a 'revokeVote` method. Whenever the delegate revokes his votes he loses out on the weight that has been assigned to him by the voter when his vote was already cast.

It doesn't make sense to use an `if/else`. The delegate should be receiving the weight regardless, like this:

```solidity
delegate_.weight += sender.weight;
if (delegate_.voted) {
    proposals[delegate_.vote].voteCount += sender.weight;
}  
```

## Pull request

I'm used to adding a PR after the issue, so I'll keep this empty for the moment and update later.

**Comment by nikola-matic** [comment]
The behaviour is only wrong *if* a `revokeVote` method were to be implemented; however, it isn't, so the example in its current state is not wrong, at least from what I can see. I'll be closing this issue, since it's technically wrong, however, if you feel a `revokeVote` method should be implemented in the example, and thus the tail end of the `delegate` method be reworked, you can open a separate issue for this, and if you're so inclined, even open a PR yourself to address.

 If I was somehow wrong in my interpretation of the example, feel free to reply in this issue, since we can always re-open it. Cheers, and thanks for contributing.
