### ISSUE TITLE
Cannot use `unchecked` keyword inside of an if statement without curly braces

### ISSUE THREAD

**Issue by clemlak** [ethereum/solidity#13602]
## Description

Using the keyword `unchecked` inside of an if statement without curly branches will trigger the following error: `ParserError: "unchecked" blocks can only be used inside regular blocks.`.

I think it's an issue with the parser, as I don't see any particular reason to prevent this situation from happening?

## Example

```solidity
// SPDX-License-Identifier: WTFPL
pragma solidity 0.8.17;

contract Foo {
    uint256 public balance;

    function boop(int256 amount) external {
        if (amount > 0) unchecked { balance += uint256(amount); }
        else balance -= uint256(~amount + 1);
    }
}
```

**Comment by hrkrshnn** [comment]
This is expected:

> The unchecked block can be used everywhere inside a block, but not as a replacement for a block. It also cannot be nested.

https://docs.soliditylang.org/en/v0.8.17/control-structures.html?highlight=unchecked#checked-or-unchecked-arithmetic

**Comment by cameel** [comment]
As @hrkrshnn said, this is by design and not a bug. Should we treat this as a feature request or is the explanation satisfactory?

But, to be honest, I'm not sure why we even disallowed this. I don't see much risk in allowing this and it might make code more readable by removing an extra pair of unnecessary braces.

**Comment by clemlak** [comment]
Looks like I missed the explanation in the documentation, my bad! However, I feel like we can then treat this as a feature request, as @cameel just mentioned, it can help improve the readability of the code.

**Comment by Rassska** [comment]
Hey, that looks amazing, can I try to work on that?

**Comment by cameel** [comment]
Sorry, but we have not yet decided whether to implement this. Like I said, the current design was intentional and there were probably some good reasons for it. I think it could be changed but we'd have to get some consensus on that first.

This is also pretty low priority for us but if you'd like to move discussion on this forward, you can always drop in on one of our [team calls](https://docs.soliditylang.org/en/latest/contributing.html#team-calls).
