### ISSUE TITLE
Add "macro" keywords for better logging of error

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#13667]
## Abstract

Add `__FILE__`, `__LINE__`, `__CONTRACT__` and `__FUNCTION__` keywords, following the example of C/C++ macros, to improve the debugging

## Motivation

A recent discussion ([here on twitter](https://twitter.com/MicahZoltu/status/1586894671988785152)) discussed the upsides, and downside, of revert strings vs custom error. Without going to much into the details of the arguments, there appear to be rough consensus that filename and line number are valuable information to provide.

Following my past experience with C++, I remember extensively using the macro commands to do "poor man tracing". I believe it would be nice to have the opportunity to do the same in solidity

## Specification

Introduce 4 new reserved keywords: `__FILE__`, `__LINE__`, `__CONTRACT__`, `__FUNCTION__`.
When compiling a file, these keywords should be statically replaced with the corresponding value:

- `__FILE__` → a string containing the name of the file (including the fullpath?). Example `"contracts/ERC20.sol"`
- `__LINE__` → a number containing the line in the file. Example `173`
- `__CONTRACT__` → a string containing the name of the contract (or library) where the function is defined. (for free functions: replace with an empty string). Example: `"ERC20"`
- `__FUNCTION__` → a string containing the name of the current function. To resolve ambiguity, this should contain the arguments type, but not the visibility or the return type. Example: `"_transfer(address,address,uint256)"`

There "keyword" are not types, because they are just to be replaced by some preprocessor. From the compiler/optimizer point of view they should be equivalent to the developer writing the corresponding value itself.  

## Backwards Compatibility

This will break compatibility with any contract that currently uses any of these keywords. I don't expect that to be an issue. A quick search on [tintinweb/smart-contract-sanctuary](https://github.com/tintinweb/smart-contract-sanctuary) does not find any such occurence.

**Comment by nikola-matic** [comment]
Hi @Amxx, and thanks for posting. I'll be closing this issue since it's not a high priority (and not on our roadmap), and as such, preprocessor is not in the scope for the team, at least in the foreseeable future. The request you posted does however have merit, and would be nice to have, however your point about this being breaking, but not expecting it to be an issue is a bit of a moot point, since on our end, it is 100% a breaking change, and would as such require a breaking release, regardless of whether people were actually using these identifiers or not.

In any case, it would be nice to open a forum post and get some support for this so that we can at least properly prioritize issues for development, since at the moment, we have hundreds of open issues, and not enough resources to address all of them. All in all, if this does get to the point where we decide it's something we'll work on - it will still require language design.
