### ISSUE TITLE
Include possible custom errors on ABI

### ISSUE THREAD

**Issue by gagiuntoli** [ethereum/solidity#13683]
## Abstract

I am dealing with the problem of trying to include in the ABI of a contract all the possible custom errors thrown by the contracts called by the first. E.g.:

```solidity
error customErrorA();
error customErrorB();

contract A {
    function foo() {
         revert customErrorA();
    }

    function callB(address _addressB) {
         B(_addressB).bar()
    }
}

contract B {
    function bar() {
         revert customErrorB();
    }
}
```
 
## Motivation

If the custom error of the called contracts is included in the caller contract ABI, it is possible to catch the error type easier with the calls.

Now I am dealing with it by defining a global error interface and inheriting it on the contracts:

```solidity
interface Errors {
   error customErrorA();
   error customErrorB();
}

contract A is Errors {
    function foo() {
         revert customErrorA();
    }

    function callB(address _addressB) {
         B(_addressB).bar()
    }
}

contract B is Errors {
    function bar() {
         revert customErrorB();
    }
}
```

## Specification

I would like to know if the solidity compiler already has another way to do that and add external possible custom errors on the ABIs. If not, are there plans to include this on the compiler? Has sense to include this capability on the compiler?

## Backwards Compatibility

It is just including more error codes on the ABI, this would not affect any byte code.

**Comment by ekpyron** [comment]
The most immediate problem I'm seeing here is that this would give a false sense of certainty on the possibly raised errors.
In your example, you can call ``A.callB`` with any address, independently of whether it's actually a B - it may be in fact a disguised contract ``C``, which may end up throwing ``customErrorC``. There's no way to guard against that at compile-time. The only way to make sure, would actually be to catch and decode errors on the call to ``B`` and re-raise the ones that are expected, while raising a special one on unexpected errors (in which case they'd actually show up in the ABI again).

**Comment by ekpyron** [comment]
Or put differently: there is, in general, no way to determine an accurate set of possible custom errors across external calls at compile time. I think any analysis beyond that, rather benefits from us being precise about the errors that actually occur in any given contract - I see in the linked issue that such an analysis is considered in tooling, and I'd generally say that tooling is the place to look for such kinds of auxiliary analysis rather than the compiler itself. Given that, I'm closing the issue, but feel free to reopen, if you disagree, resp. preferably to open a broader discussion in the [Solidity forum](https://forum.soliditylang.org/) to gather additional feedback.
