### ISSUE TITLE
Inline Assembly: Stack height unknown after jump

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#1374]
```
contract InternalFunctionCall {

    function add(uint a, uint b) constant returns (uint sum) {
        assembly {
            added
            a
            b
            jump(_add)
            added:
            =: sum
        }
    }

    function _add(uint a, uint b) internal constant returns (uint) {
        return a + b;
    }

}
```

The `=: sum` assignment at the bottom of the inline assembly block does a `SWAP3` rather then `SWAP1`. The compiler also complains that the stack is not balanced (leaves 2 items on stack), but it is. The reason seems to be that it believes `a` and `b` are still on the stack, even though `_add` treats them as regular function parameters and pops them automatically.

**Comment by chriseth** [comment]
It is impossible to tell the stack height at the point where you jump back to `added` because the control flow just leaves the assembly it the jump and comes in at added from somewhere outside its control. In the compiler, this is dealt with my manually adjusting the stack height. We could add such a feature, but I'm not sure that is the right way to go.

Syntax could be:

```
jump(_add)
added[-2]:
=: sum
```

**Comment by androlo** [comment]
Not very useful feature I suppose. Better wait until it's full support for function calls. Just playing around anyways. Figured I'd bring it up since i saw some other similar issue (the one when the entire block is just a variable declaration).
