### ISSUE TITLE
`immutable` can be declared and never initialized

### ISSUE THREAD

**Issue by trocher** [ethereum/solidity#13769]
## Description

When trying to compile a contract in which the constructor does not initialize an immutable state variable, the compiler outputs `TypeError: Construction control flow ends without initializing all immutable state variables.`. By embedding the initialization of such variable in a `For` loop such that the control flow never reach the initialization instruction, it is possible to compile a contract that does not initialize an immutable.

## Environment

- Compiler version: 0.8.17
- Target EVM version (as per compiler settings): --
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: --
- Operating system: OSX

## Steps to Reproduce
The following contract compiles successfully.
```solidity
pragma solidity 0.8.17;

contract A {
    bool immutable a;
    constructor(){
        for(uint i = 0; i<3;i++){
            if (i==0){
                break;
            } 
            a = true;
        }
    }
}
```

**Comment by joshlangs** [comment]
I've managed the same outcome by having try/catch in the constructor

When I looked, the docs told me it *IS* initialized to its default value (zero).

The compiler uses it's best efforts to warn you if you forgot to initialize an immutable variable, because it figures "well, why have one if you're not going to initialize it?!?".  But there's no harm done if you find a way to trick it.  The value is just "zero".
