### ISSUE TITLE
Visibility modifiers for struct fields

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#13773]
## Abstract

Sometimes it is good to restrict access to some fields of structs to be only accessible within outer contract/library.

## Motivation

Some popular libraries are currently adding underscore to the field names, but can't really protect these vars from being accessed.
For example, `Counter.sol` in OpenZeppelin library: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/49c0e4370d0cc50ea6090709e3835a3091e33ee2/contracts/utils/Counters.sol#L19

## Specification

Let's allow to specify `private`,`public` (and maybe `view`, which could be read-only from other contract/libraries) keywords for struct fields:
```solidity
library Counters {
    struct Counter {
        uint256 private _value;
    }
}
```

So this field `_value` should be accessible within `library Counters` and be non-accessing from the other contracts/libraries. This would allow to build libraries which really protect their consistency from unrestricted access.

## Backwards Compatibility

Default visibility modifier should be `public`.

**Comment by ekpyron** [comment]
This makes some sense, but the problem here would be that the scope to which the modifier applies is never clear, resp. the rules would need to be complicated (e.g. for file-level structs etc.).

I think the preferred way to solve the underlying issue will be to generalize user-defined value types to general user-defined types that can encapsulate even structs and then to only expose certain accessor functions selectively. As such, I'm closing this issue as currently not planned.
