### ISSUE TITLE
Different error message when constructor of base contract is not called

### ISSUE THREAD

**Issue by fvictorio** [ethereum/solidity#13824]
## Description

The error message shown for a missing call to the base constructor and a missing function implementation is the same.

## Environment

- Compiler version: 0.8.17

## Steps to Reproduce

Compile this:

```solidity
abstract contract Bar {
  constructor (uint x) {}
}

contract Foo is Bar {
  constructor (uint x) {}
}
```

The error message shown (error 3656) is not fundamentally different from the one you get if you try to compile this:

```solidity
abstract contract Bar {
  function f() public virtual;
}

contract Foo is Bar {
}
```

This is important for our solidity vscode extension because it makes it hard to provide an useful quickfix. While we have one for the second case, telling it apart from the first case is not straightforward. Having a different error in each case would be great, and I think it makes sense conceptually.

**Comment by NunoFilipeSantos** [comment]
Hey! 👋 Feel free to submit a PR but we're closing it for now.

**Comment by cameel** [comment]
To clarify here, we have a very long list of such small tweaks that sit in the issue tracker and are so low priority that they're unlikely to ever get implemented. So we felt that we're better off just closing this unless someone can offer a PR.

But I took a closer look and I think it's actually a small bug (or at least inconsistency) and we should fix this. The error messages look like this:

```
Error: Contract "Foo" should be marked as abstract.
 --> test1.sol:5:1:
  |
5 | contract Foo is Bar {
  | ^ (Relevant source part starts here and spans across multiple lines).
Note: Missing implementation:
 --> test1.sol:2:3:
  |
2 |   constructor (uint x) {}
  |   ^^^^^^^^^^^^^^^^^^^^^^^
```
```
Error: Contract "Foo" should be marked as abstract.
 --> test2.sol:5:1:
  |
5 | contract Foo is Bar { }
  | ^^^^^^^^^^^^^^^^^^^^^^^
Note: Missing implementation:
 --> test2.sol:2:3:
  |
2 |   function f() public virtual;
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The compiler indicates which method is unimplemented - and in the first example it points at the constructor which does have an implementation. These cases seem to have been dumped into the same bucket because they can both be solved by making the contract abstract, but I agree that they're fundamentally different. In the first case I think you're more likely to want to add the missing arguments and the hint is just wrong.

I implemented a fix for this in #13971. Also fixed another, slightly related hint while at it. Here's a [Linux binary from the PR with the fix](https://output.circle-artifacts.com/output/job/d9fe56b5-1129-43d3-a273-7e6742c5c8a1/artifacts/0/solc) if you want to try it out.

**Comment by fvictorio** [comment]
Thank you @cameel!

@NunoFilipeSantos I totally get the idea of closing low priority issues for bookkeeping reasons, but I would suggest responding with a clearer explanation of why you're doing it (like Kamil did). GitHub's [saved replies](https://docs.github.com/en/get-started/writing-on-github/working-with-saved-replies/using-saved-replies) are super useful for exactly this use case.

Also, I'd recommend closing those issues as "not planned" and not as completed, but that's less important.

**Comment by NunoFilipeSantos** [comment]
Thank you for the suggestion. We’re still automating most of these flows. 👍
