### ISSUE TITLE
Local build Failed on MacOS 13.2 Beta x86_64

### ISSUE THREAD

**Issue by hsyodyssey** [ethereum/solidity#13854]
## Description

Attempt to compile Solidity locally but failed. The error log shows: "solidity/libsolidity/lsp/DocumentHoverHandler.cpp:66:27: error: chosen constructor is explicit in copy-initialization
        MarkdownBuilder markdown{};"

## Environment

- Operating system: MacOS 13.2 Beta
- CPU: Intel x86_64 
- Clang: Apple clang version 11.0.0 (clang-1100.0.33.17) Target: x86_64-apple-darwin22.3.0
- codebase version: https://github.com/ethereum/solidity/commit/2e2210222c1d68f8dd5710cd4911bf34f434571b

## Steps to Reproduce

- run ./scripts/build.sh

Errors:

```
[ 54%] Building CXX object libsolidity/CMakeFiles/solidity.dir/lsp/DocumentHoverHandler.cpp.o
[ 55%] Building CXX object libsolidity/CMakeFiles/solidity.dir/lsp/FileRepository.cpp.o
solidity/libsolidity/lsp/DocumentHoverHandler.cpp:66:27: error: chosen constructor is explicit in copy-initialization
        MarkdownBuilder markdown{};
solidity/libsolidity/lsp/DocumentHoverHandler.cpp:38:15: note: in implicit initialization of field 'result' with omitted initializer
        stringstream result;
                     ^
1 error generated.
1 error generated.
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/lsp/DocumentHoverHandler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jhheider** [comment]
I believe this fixes it: https://github.com/teaxyz/pantry.extra/blob/f478a144ba5cf99ad48377572d0e4cb4ef0782c8/projects/soliditylang.org/clang-error.diff (unless I chose the wrong direction, of course).

**Comment by hsyodyssey** [comment]
Thanks Ser. It works after I pull the latest code from the dev branch and change this line(https://github.com/ethereum/solidity/blob/develop/libsolidity/lsp/DocumentHoverHandler.cpp#L66) to` MarkdownBuilder markdown = {stringstream(ios_base::in)};` as your advice.

**Comment by cameel** [comment]
@jhheider I think it should also be enough to replace `MarkdownBuilder markdown{};` with `MarkdownBuilder markdown;`. That would not let us keep it default-initialized. Feel free to submit that as a PR (after testing it locally). Our CI does not catch it, probably because it must be something that has changed between XCode versions. What are your XCode and macOS versions?

**Comment by hsyodyssey** [comment]
> @jhheider I think it should also be enough to replace `MarkdownBuilder markdown{};` with `MarkdownBuilder markdown;`. That would not let us keep it default-initialized. Feel free to submit that as a PR (after testing it locally). Our CI does not catch it, probably because it must be something that has changed between XCode versions. What are your XCode and macOS versions?

macOS Ventura13.2 (b) Beta and xcode 14.0.1

**Comment by cameel** [comment]
Interesting. I tried to look up the XCode version based on your clang version and [this table from Wikipedia](https://en.wikipedia.org/wiki/Xcode#Xcode_11.0_-_14.x_(since_SwiftUI_framework)_2) and it matches XCode 11.3.1, not 14.0.1.

I mean, I mostly just wanted to know if it's something that was added in newer XCode (and we should update) or something that used to be an error and was relaxed in later versions. Currently [we're at XCode 13.2.0](https://github.com/ethereum/solidity/blob/v0.8.18/.circleci/config.yml#L385).

I guess, since you're using a beta version of macOS it must actually be newer XCode despite what it says about clang. In that case we'll probably get this error eventually too. For now we can just accept the tweak that helps you as long as it works on the XCode we're using too.

**Comment by jhheider** [comment]
Our failure was under linux/arm64 with llvm 14.0.6: https://github.com/teaxyz/pantry.extra/actions/runs/4068729377/jobs/7007648961. I'll try the minimalist fix.

**Comment by jhheider** [comment]
> @jhheider I think it should also be enough to replace `MarkdownBuilder markdown{};` with `MarkdownBuilder markdown;`. That would not let us keep it default-initialized. Feel free to submit that as a PR (after testing it locally).

confirmed and submitted.
