### ISSUE TITLE
Potential Casting Discrepancy (Yul)

### ISSUE THREAD

**Issue by alex-ppg** [ethereum/solidity#13853]
## Description

The documentation of Solidity does not strictly define what happens when a sub-32 byte negative integer is upcast to a `bytes32` variable in an `assembly` / Yul context where it is permitted. Currently, it appears to misbehave as it will pre-fill the byte representation with `ff` to indicate it is a negative number rather than only writing the bytes that the sub-32 byte integer held and leaving the remaining zero.

## Environment

The compiler utilized where the behaviour is present is `0.8.7`, however, some example compiler versions where this is applicable are: `0.8.0`, `0.7.0`, `0.6.0`, `0.5.0`, and `0.4.0`

## Steps to Reproduce

Below is a minimal example of how this discrepancy manifests:

```solidity
function retrieve() public view returns (bytes32 b) {
    int64 a = -5;
    assembly { b := a }
}
```

The above example will yield `0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb` instead of `0x000000000000000000000000000000000000000000000000fffffffffffffffb`, as if we performed an upcast of `int64` to `int256` prior to assignment.

I believe this is not a deliberate action by the compiler and is a side-effect of how sub-32 byte variables are "artificial" and not natively supported by the EVM. I advise its behaviour to be explicitly documented as it can affect encoding mechanisms significantly.

**Comment by ekpyron** [comment]
This is deliberate - inline assembly is not typed, so any referenced variable is treated as a "raw" 256-bit word. So ``a`` in the assembly block refers to the 256-bit word representation of the 64-bit integer ``-5``, which indeed is ``0xff..ffb``.

In general, a lot of care has to be taken when dealing with sub-32-byte variables in inline assembly and the behaviour here is intentionally not well documented, since we reserve the right to change behaviour, resp. in these circumstances using inline assembly follows a "you need to know what you're doing" policy. However, we may want to consider specifying the behaviour more strictly and then adhere to that specification, since issues like this have been the source of some confusion and bugs in the past.

**Comment by alex-ppg** [comment]
Understood, I believe expanding the documentation is something that should be done in this case. The problem I see with the above snippet is that an in-memory assignment manipulates bit space differently than what the same in-storage assignment would do. Considering the following:

```solidity
contract Test {
    int64 internal a = -5;

    function retrieve() public view returns (bytes32 c, bytes32 d) {
        int64 b = -5;
        assembly { 
            c := sload(a.slot)
            d := b
        }
    }
}
```

The variables `c` and `d` would hold different bitwise representations even though `a == b` would yield `true`. Such issues will become especially prevalent with signed integers rather than unsigned (as `uint64` / positive values would yield the same bitwise outputs). 

This behaviour needs to be explicitly documented (with appropriate warnings that specify it can change) as currently, developers are "in the dark" as to how their `assembly` code should behave.
