### ISSUE TITLE
Clarification about offset of string storage pointers

### ISSUE THREAD

**Issue by frangio** [ethereum/solidity#13915]
## Page

https://docs.soliditylang.org/en/latest/assembly.html#access-to-external-variables-functions-and-libraries

> You can also assign to the .slot part of a local storage variable pointer. For these (structs, arrays or mappings), the .offset part is always zero.

## Abstract

We are wondering if the `.offset` part of a `string storage` variable can be assumed to be zero. The section above doesn't explicitly mention strings (unless they are considered under "arrays").

**Comment by Amxx** [comment]
For context, this is code that we have that we are not sure is safe

```solidity
library StorageSlot {
    struct StringSlot { 
        string value;
    }

    function getStringSlot(string storage store) internal pure returns (StringSlot storage result) {
        assembly { result.slot := store.slot }
    }
}
```

**Comment by cameel** [comment]
> unless they are considered under "arrays")

They're arrays so I think they were considered to be covered by that. IIRC there are more places in the docs where we phrase things like this.

So I'd say the docs are fine here but since it wasn't clear to you, it would be a good idea to rephrase that anyway.

> For context, this is code that we have that we are not sure is safe

I'd say it's safe because the long/short string format relies on that (we assume that strings shorter than 32 bytes can be stored in the short format) and the way strings are stored is a part of the storage ABI and changing this would be a very breaking change.
