### ISSUE TITLE
Link to open code blocks in remix breaks the layout of the documentation page on small devices.

### ISSUE THREAD

**Issue by RupeshWadne** [ethereum/solidity#13948]
## Page
When the documentation is opened in small devices the screen started overflow like this.

![Screenshot (27)](https://user-images.githubusercontent.com/111430616/217485933-cc62e59e-8eb1-4818-a162-c1aa5e5e7659.png)

https://docs.soliditylang.org/en/v0.8.18/introduction-to-smart-contracts.html

## Abstract

I think there is an issue in CSS file. I made some changes and it's gone, but the link arrow to remix IDE is not visible properly. We can move it besides heading to solve this problem maybe.
![Screenshot (26)](https://user-images.githubusercontent.com/111430616/217487194-e1dd1b64-4b86-473d-91d9-09da457e5477.png)

Let me know how can we work on this 😊.

**Comment by r0qs** [comment]
Hi @ShubhamWadne, thanks for reporting the problem.

I gave it a quick look, and it seems that the problem is indeed in our layout. The `remix-link-container` is set as a [paragraph tag](https://github.com/ethereum/solidity/blob/c980e96b64f9f810f909d291791a1c421ffbf08d/docs/ext/remix_code_links.py#L40) positioned in the far right corner of a code block (see: https://github.com/ethereum/solidity/blob/develop/docs/_static/css/custom.css#L53), outside the total display area.

I think that if we want to display the open-in-remix arrow button on the side of the example code block, we should decrement the total size of the code block until it fits the link, inlining the `remix-link-container`, and maybe also making it a `div` instead of a `p`. Or we can convert the arrow button to a simple, but nicer, button and display it on top of the respective code block. Either options would be fine I guess.

If you would like to give it a try, please let's us know :)

**Comment by RupeshWadne** [comment]
Yes, I would love to do it💯. I will do changes what suits the interface and let you know.

**Comment by RupeshWadne** [comment]
I just made a pull request. Let me know about it.

**Comment by ShubhamWadne** [comment]
#13959

**Comment by RupeshWadne** [comment]
Changed the arrow icon to button #13959
