### ISSUE TITLE
[Parser] Null pointer deref while parsing `using for` directive that contains an empty string as operator name

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#14016]
```
using{a as''
```

derefs null ptr here

https://github.com/ethereum/solidity/blob/983407762c3423e9c301d5ae56ac7b6d951655df/libsolidity/parsing/Parser.cpp#L998

**Comment by cameel** [comment]
Interesting. It actually triggers an exception inside STL:
```
Uncaught exception:
Dynamic exception type: std::logic_error
std::exception::what: basic_string::_M_construct null not valid
```
And it's unrelated to the fact that the directive is truncated. The full form causes the same crash:
```solidity
using {a as ''} for uint;
```
Tokens like `""` or `hex""` trigger the same problem. Interestingly, others that I would expect to cause this as well do not. `()`, `1`, `x`, `"abc"`, `false` are all handled properly.

I found a very similar problem early in the PR's life where using an identifier like `x` was causing a crash. That was because such tokens have no string representation assigned in `Token.h` (they have `nullptr` instead). That's the case for string literals too so I wonder what's different specifically about empty string literals.
