### ISSUE TITLE
Call of not existing function reverts but without reason

### ISSUE THREAD

**Issue by migoldfinger** [ethereum/solidity#14023]
## Description

While writing unit tests for my contracts I did run in an unexpected behavior.
A call to an non existing function did revert the transaction (as expected), but there was no reason so the caller is left in the dark about the reason of the revert. It did pop up on existing unit tests after upgrading the compiler version older compiler versions did revert with the  reason "Transaction reverted: function returned an unexpected amount of data". That was not ideal but it was something.

## Environment

- Compiler version: 0.8.17
- Framework/IDE (e.g. Truffle or Remix): hardhat
- Operating system: Linux (RockyLinux)

## Steps to Reproduce

I was taking a closer look on the SafeERC20.sol implementation of openzeppelin, especially the safeIncreaseAllowance method
```
function safeIncreaseAllowance(IERC20 token, address spender, uint256 value) internal {
        uint256 oldAllowance = token.allowance(address(this), spender);
        _callOptionalReturn(token, abi.encodeWithSelector(token.approve.selector, spender, oldAllowance + value));
}

function _callOptionalReturn(IERC20 token, bytes memory data) private
    {
        // We need to perform a low level call here, to bypass Solidity's return data size checking mechanism, since
        // we're implementing it ourselves. We use {Address.functionCall} to perform this call, which verifies that
        // the target address contains contract code and also asserts for success in the low-level call.
        bytes memory returndata = address(token).functionCall(data, "SafeERC20: low-level call failed");
        if (returndata.length > 0)
        {
            // Return data is optional
            require(abi.decode(returndata, (bool)), "SafeERC20: ERC20 call failed");
        }
    }
```
I notices that when calling with an address that does not hold a contract this reverts with no reason. Older compiler reverted with reason "Transaction reverted: function returned an unexpected amount of data".

In an attempt to fix this behavior and return some useful reason I changed the method to
```
    function safeIncreaseAllowance(IERC20 token, address spender, uint256 value) internal
    {
        uint256 newAllowance = _callReturnUint256(token, abi.encodeWithSelector(token.allowance.selector, address(this), spender)) + value;
        _callOptionalReturn(token, abi.encodeWithSelector(token.approve.selector, spender, newAllowance));
    }

    function _callOptionalReturn(IERC20 token, bytes memory data) private
    {
        // We need to perform a low level call here, to bypass Solidity's return data size checking mechanism, since
        // we're implementing it ourselves. We use {Address.functionCall} to perform this call, which verifies that
        // the target address contains contract code and also asserts for success in the low-level call.
        bytes memory returndata = address(token).functionCall(data, "SafeERC20: low-level call failed");
        if (returndata.length > 0)
        {
            // Return data is optional
            require(abi.decode(returndata, (bool)), "SafeERC20: ERC20 call failed");
        }
    }

    function _callReturnUint256(IERC20 token, bytes memory data) private returns (uint256)
    {
        // We need to perform a low level call here, to bypass Solidity's return data size checking mechanism, since
        // we're implementing it ourselves. We use {Address.functionCall} to perform this call, which verifies that
        // the target address contains contract code and also asserts for success in the low-level call.
        bytes memory returndata = address(token).functionCall(data, "SafeERC20: low-level call failed");
        console.log(returndata.length);
        if (returndata.length != 32)
        {
            revert("SafeERC20: ERC20 call failed");
        }
        return abi.decode(returndata, (uint256));
    }
```
the method functionCall is located at https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol

This solved the problem with the reason but I am still struggling with one feature yet.
I was unable to find a way to check the return type in regards of type correctness.
My tests show that a token with an allowance that returns uin128 instead of uint256 is still be valid.
While this is not problematic in my use case since I am satisfied with every value that fits in an uint256.
From an type-safe point of view this in not optimal.
I did not find a way to check for type correctness until now.
I also did try to put the call inside a try/catch but it seems that a reverted transaction did not hit the catch block.

So in addition to get some revert reason strings when the called method is missing I would love to get some revert with reason if the return type is not matching the expected type. If I do not have to rely to low level calls to achieve this it would be the best option.

**Comment by Vinayak-Patil-Dev** [comment]
In Solidity, calling a non-existing function on a contract will cause the transaction to revert. The reason for the revert is that Solidity enforces strict typing and will not allow calling a function that does not exist on a contract.

When the transaction reverts due to calling a non-existing function, the revert message should provide a reason for the revert. However, if you are experiencing a revert without a reason, it is possible that the reason message was not provided or was overwritten by another operation in the transaction.

To help identify the reason for the revert, you can try the following steps:

1. Use a Solidity debugger or a tool like Remix to debug the transaction and see if there is any information in the debug log about the revert reason.

2. Check if any other operations in the transaction could be overwriting the revert message. For example, if there is another operation that is also causing a revert in the same transaction, its revert message could be overwriting the one from the non-existing function call.

3. Ensure that the contract being called is the correct contract and that the function name and parameters are correct.

4. Check if the contract has been deployed correctly and that the ABI (Application Binary Interface) used to interact with the contract is correct.

If none of these steps help identify the reason for the revert, it is possible that there is a bug in the Solidity compiler or the Ethereum client being used. In that case, you may want to reach out to the Solidity or Ethereum development community for further assistance.

**Comment by migoldfinger** [comment]
@Vinayak-Patil-Dev thanks for your copy & paste general answer, it was very helpful do go over all the 4 Points again with the same result.

However I did try out different compiler versions in the meantime. And at least it looks like hardhat is not fetching the reason in this case. I am unsure why but I create an issue there maybe they changed something.

However my second problem still stands. How can I check the returnvalue to be correct inside a contract. because the returned bytecode looks exactly the same for uint8, uint... and uint256.
