### ISSUE TITLE
[Codegen] Legacy and IR code generators behave differently

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#14038]
```
function freeFunction() returns (bool) {}
contract C {
  receive() external virtual payable
  {
    unchecked {
      bool l1 = payable(this).send(0);
      bool l2 = freeFunction();
    }
  }
  function f() external virtual
  {
    payable(this).transfer(0);
 }
}
// ----
// f() -> FAILURE
// f() ->
```

First outcome is legacy, second is IR. ~~I think both should be reverting due to insufficient balance?~~

**Comment by cameel** [comment]
I tried to analyze this and I can reproduce it but can't really see why the legacy version reverts. I did manage to reproduce it with Remix, so it's an actual bug though. The only real difference is that the reverting code leaves the stack clean, while the non-reverting one leaves extra stuff on it.

### Minimal repro
```solidity
function freeFunction() {}

contract C {
    receive() external payable {
        payable(this).send(0);
        freeFunction();
    }

    function f() external {
        payable(this).transfer(0);
    }
}
```

It fails on legacy and passes via IR. The free function call and a mix of `send()` and `transfer()` seem to be the necessary elements to trigger it. It's reproducible only with optimizer disabled.

### Analysis
The revert on legacy goes away if you remove the call to the free function. This is weird because it should be a no-op. To check what's going on I compiled the example above with and without `freeFunction()` call on 0.8.19 and compared the asm output.

```
solc test.sol --asm --debug-info none
```
[with-free-function-call-unoptimized.asm.txt](https://github.com/ethereum/solidity/files/10943518/with-free-function-call-unoptimized.asm.txt)
[without-free-function-call-unoptimized.asm.txt](https://github.com/ethereum/solidity/files/10943519/without-free-function-call-unoptimized.asm.txt)

There are minor differences in layout (different tag names, an extra unconditional jump), but ignoring that, the only thing that could be causing it seems to be this bit:

```diff
     tag_1:
       jumpi(tag_2, calldatasize)
       address
       0xffffffffffffffffffffffffffffffffffffffff
       and
       0x08fc
       0x00
       swap1
       dup2
       iszero
       mul
       swap1
       mload(0x40)
       0x00
       mload(0x40)
       dup1
       dup4
       sub
       dup2
       dup6
       dup9
       dup9
       call
-      swap4
-      pop
-      pop
-      pop
-      pop
-      pop
-      tag_7
-      tag_8
-      jump     // in
-    tag_7:
       stop
```
```diff
-    tag_8:
-      jump     // out
```

This is the body of the `receive` function. The "before" version in this diff is the one with the free function call. It pops 5 values from the stack after `call` and then jumps to the empty `freeFunction()` and back.

I thought that it might be popping too much, but after counting the slots it does not seem to be the case. If did not make some mistake, the stack just before `call`, with "squashed" dups and swaps looks like this:
```
       [11] and(address, 0xffffffffffffffffffffffffffffffffffffffff)     
       [10] mul(iszero(0x00), 0x08fc)
       [09] 0x00
       [08] mload(0x40)
       [07] 0x00
       [06] mload(0x40)
       [05] sub(mload(0x40), mload(0x40))
       [04] mload(0x40)
       [03] 0x00
       [02] and(address, 0xffffffffffffffffffffffffffffffffffffffff)     
       [01] mul(iszero(0x00), 0x08fc)
```

`call` consumes 7 of of 11 items and returns one. We're left with 5 and these are consumed by `pop`s. The unconditional jumps afterwards just consume `tag_7` and `tag_8` and then we reach `stop`. with an empty stack

Interestingly, the optimized version does not revert, even though it looks like it should leave the stack in the same state:

```
solc test.sol --optimize --asm --debug-info none
```
[with-free-function-call-optimized.asm.txt](https://github.com/ethereum/solidity/files/10943555/with-free-function-call-optimized.asm.txt)
[without-free-function-call-optimized.asm.txt](https://github.com/ethereum/solidity/files/10943556/without-free-function-call-optimized.asm.txt)

```diff
    tag_1:
      jumpi(tag_2, calldatasize)
      mload(0x40)
      address
      swap1
      0x08fc
      swap1
      0x00
      swap1
      dup2
      dup2
      dup2
      dup2
      dup2
      dup9
      dup9
      call
-      pop
-      pop
-      pop
-      pop
-      pop
-    tag_7:
       stop
```

@chriseth @ekpyron Any idea why one reverts and the other does not?

**Comment by cameel** [comment]
My suspicion is that this is not really a semantic difference between codegens but just a result of minor differences in gas consumption due to different optimization.

The difference might be caused by whether after the chain of nested `send()` calls there is enough gas left to execute the extra opcodes. If there is, the top-level `receive` successfully ignores the return code from `send()`. Otherwise it reverts out of gas, making `f()` revert as well due to its use of `transfer()` rather than `send()`.

I'm not that well versed in all the subtleties regarding how much gas is forwarded and what reverts when so I could be wrong. Someone has to confirm this.

**Comment by bshastry** [comment]
> It's reproducible only with optimizer disabled.

iirc, the original example is reproducible even with optimizer enabled

**Comment by ekpyron** [comment]
I'll have a proper look next week, but it's most probably indeed not a bug. Note that these are infinite recursions and the behavior will depend on how much gas happens to be left when the last external call (which itself will fail as out of gas) returns (returning false as failure). If the gas left is enough to return, you get success, otherwise you fail with out of gas.
So the difference is just the different gas efficiency between legacy and via-IR that merely becomes weirdly visible here.

**Comment by ekpyron** [comment]
IIRC we had a very similar case not that long ago... I wonder if there's a good way to detect these cases during fuzzing to avoid false positive reports, but not sure how...

**Comment by bshastry** [comment]
> IIRC we had a very similar case not that long ago... I wonder if there's a good way to detect these cases during fuzzing to avoid false positive reports, but not sure how...

Good point, I feel avoiding recursive calls is one option but a generic solution is hard since recursive calls could take many forms A->B->C->D->A. Also, low level calls without valid signature need to be somehow tied to fallback function if exists. May be for now, I simply be extra careful and consider recursion before filing an issue.

**Comment by ekpyron** [comment]
Yeah, there's much more potential harm in overprotecting here and being in the danger of missing an actual issue, rather than having a few false positives. In general, we do want this stuff to be tested... so yeah, maybe it's enough to just be aware of these cases for now - it drove me nuts the first time I saw a case like this until I got what happened and it was probably similar for Kamil now :-) - but once you know it's not too hard to see what's happening.

In any case, I'm closing this issue as a non-issue for now.
