### ISSUE TITLE
[StackLayoutGenerator] Fails an assertion on stack depth

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#14037]
```
{
  function g(b,s) -> y {
    y := g(b, g(y, s))
  }
}
```

throws

https://github.com/ethereum/solidity/blob/7cd589eee46bf83635bd279d0957c199ec16c8ca/libyul/backends/evm/StackLayoutGenerator.cpp#L759

Repro

```
solc test.yul --strict-assembly --optimize --asm --yul-optimizations ":"
```

CC https://github.com/ethereum/solidity/pull/13785#issuecomment-1444551710

**Comment by Vishal-Kuruba** [comment]
There is no base case or default case...

**Comment by bshastry** [comment]
A solidity test case that triggers this issue

```
type T0 is address;
pragma solidity >= 0.0.0;
contract C0 {
  type T1 is uint88;
  bool  s0 = true;
  int40[2]  s1;
  uint168  s2;
  constructor(int40[2] memory i0,uint168 i1) payable  {
    s1 = i0;
    s2 >>= (uint168((false ? uint176(9804562508255347250040549753) : uint176(uint32(2929920713)))) << uint168(203403957390802182221255917185821350187566384614114));
    unchecked {
    }
  }
  function f0(C0[2] calldata i0) external   returns(C0.T1 o0)
  {
    assembly
    {
      stop()
      sstore(s1.slot, o0)
      function af0(ai0, ai1, ai2) -> ao0, ao1, ao2
      {
        ao0 := ai0
        let al0, al1, al2 := af0(xor(ao2, 22921747626927277635096291755001870733748359807325933), 107167272211853377649721232174600963084950735156013834666759028302795502, ai2)
        let al3, al4, al5 := af0(ai0, al1, 104929345027614562)
      }
      o0 := o0
      invalid()
      pop(o0)
    }
  }
}
```

Repro

```
solc --via-ir --bin test.sol
```

**Comment by ekpyron** [comment]
This will happen whenever a Yul function body reads a return variable of the function prior to any assignment to it. Conceptually, the return variable has a default value of zero in such cases, but we try not to already push that zero when entering the function, since that'd lead to suboptimal stack usage.

Now so far we only ran the optimized code transform post the yul optimizer - and the yul optimizer has the property of replacing all those reads from return variables by a plain zero - so the new code transform just never ran on this pattern so far. Now that we run it on unoptimized (respectively, minimally optimized) yul code, such cases *will* occur, though...

Unfortunately, it's a bit tricky to make it robust against these cases.
