### ISSUE TITLE
bugs_by_version.json file out of date

### ISSUE THREAD

**Issue by devtooligan** [ethereum/solidity#14068]
## Page

https://docs.soliditylang.org/en/v0.8.19/bugs.html

## Abstract

The bugs_by_version.json file referenced in the docs hasn't been updated since 0.8.9 and could be misleading if that was the only document referenced.  It should either be updated or deprecated.  Deprecating the file seems reasonable as its an additional maintenance chore and that information can be obtained by querying the [master file](https://github.com/ethereum/solidity/blob/develop/docs/bugs.json).

## Pull request

I might be able to submit a pr for this if you can give some feedback on which path to take (deprecate vs. update)

**Comment by cameel** [comment]
`bugs_by_version.json` is up to date and contains all the recent version. You may have missed them because the keys are sorted alphabetically and versions above `0.8.9` [sort between `0.8.1` and `0.8.2`](https://github.com/ethereum/solidity/blob/develop/docs/bugs_by_version.json#L1709-L1782).

Also note that https://docs.soliditylang.org/en/v0.8.19/bugs.html does not display the content of `bugs_by_version.json`. It shows [`bugs.json`](https://github.com/ethereum/solidity/blob/develop/docs/bugs.json) instead. That file does not have entries for versions that have no known bugs so the last one there is 0.8.17.

**Comment by devtooligan** [comment]
I'm an idiot lol.  Yes I see that now thank you!
