### ISSUE TITLE
Getting compilation error for correct code. Error 2449: Definition of base has to precede definition of derived contract

### ISSUE THREAD

**Issue by IgorKoval** [ethereum/solidity#14088]
## Description

Getting compilation error for correct code.

## Environment

- Compiler version: Version: 0.8.19-develop.2023.4.3+commit.7dd6d404.Linux.g++

## Steps to Reproduce

File tree.sol
```solidity
import "modifiers.sol";
contract Tree is Modifiers {
}
```

File modifiers.sol
```solidity
import "tree.sol";
abstract contract Modifiers {
}
```

Command line:
`solc tree.sol`

Output:
```
Error: Definition of base has to precede definition of derived contract
 --> tree.sol:3:18:
  |
2 | contract Tree is Modifiers {
  |                  ^^^^^^^^^
```

**Comment by r0qs** [comment]
Hi @IgorKoval, the code is not correct. Please see the documentation: https://docs.soliditylang.org/en/v0.8.19/contracts.html#multiple-inheritance-and-linearization

You have a cyclic dependency, thus, the code will not compile. Why do you have imported `tree.sol` in the `modifiers.sol`? You should remove it from there, which I believe is what you want to achieve, and the code will compile.

**Comment by IgorKoval** [comment]
I don't have a cyclic dependency in contracts. It's ok to import files from each other.
Look, these is compiled.
`solc tree.sol`
File tree.sol
```
import "modifiers.sol";
contract Tree {
}
```
File modifiers.sol
```
import "tree.sol";
abstract contract Modifiers is Tree {
}
```
But this https://github.com/ethereum/solidity/issues/14088#issue-1652908673 isn't compiled.

**Comment by cameel** [comment]
You'll get the same error if you try this:
```solidity
contract Tree is Modifiers {}

abstract contract Modifiers {}
```

The problem is that the compiler encounters `Tree` before `Modifiers`. Cyclic imports in general are allowed but the gotcha is that they may lead to contracts being processed in such an order.

In this simple example it's clear that the compiler could do better, but in a general case it might not be possible without having to jump back and forth between the input files. Currently the compiler has to be able to compile the whole file in one go. It might be possible to change but it would complicate the compilation, but the question is if it's even worth it. Can you give an example of code where this is an actual problem that can't be resolved by removing cyclic imports or reordering declarations?
