### ISSUE TITLE
import { ... } from "..." syntax does not know all objects even if it should

### ISSUE THREAD

**Issue by migoldfinger** [ethereum/solidity#14148]
With this setup
IERC20.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface IERC20
{
...
}
```

IERC20Metadata.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import { IERC20 } from "./IERC20.sol";

interface IERC20Metadata is IERC20
{
	function name() external view returns (string memory);
	function symbol() external view returns (string memory);
	function decimals() external pure returns (uint8);
}
```

ERC20.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import { IERC20Metadata } from "./IERC20Metadata.sol";

contract ERC20 is IERC20Metadata
{
...
}
```

MyToken.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import { IERC20Metadata, IERC20, ERC20 } from "./ERC20.sol"; // Error on this line

contract MyToken is ERC20
{
...
}
```
On the import line IERC20Metadata is known, ERC20 is also known. But IERC20 is unknown and raises an error.
This is unexpected since IERC20 is imported in the IERC20Metadata file.

Expected Result
Option 1:
When importing specific contracts or interfaces the compiler has to go down all nested imports to look for the object. Therefore IERC20 should be valid in this example.
Option 2:
The Compiler does not follow nested imports. In this case IERC20 and IERC20Metadata should fail because they are not directly included in the imported file.

The current behavior seems to be that only nested imports that are listed in the imported file are followed. But for consistency it should follow all nested imports including the ones nested in nested imports or none.

**Comment by cameel** [comment]
That's by design. In `ERC20.sol` you do not import `IERC20` so it's not present in the module namespace and, as a consequence, another module cannot import it from that namespace. Contracts that other contracts inherit from are not automatically available in the namespace.

If you want it to be in the namespace, `ERC20.sol` has to explicitly import it:
```solidity
import { IERC20Metadata, IERC20 } from "./IERC20Metadata.sol";
```
or just import all names:
```solidity
import "./IERC20Metadata.sol";
```

The way it works currently makes perfect sense to me and I don't think it should be changed. In the same vein, you would not expect to have e.g. the type of a struct field necessarily available just because you can access that struct or its type. You can use the field but not use its type unless you explicitly import that type (assuming it's not a built-in type).
