### ISSUE TITLE
solc version 0.4.21 does not support Constantinople

### ISSUE THREAD

**Issue by elizabethdinella** [ethereum/solidity#14142]
## Description
Solc 0.4.21 does not allow compiling a simple contract with EVM version Constantinople.

According to [the release](https://github.com/ethereum/solidity/releases/tag/v0.4.21), I would have expected Constantinople to be a valid EVM version.

## Environment

- Compiler version: Version: 0.4.21+commit.dfe3193c.Darwin.appleclang
- Target EVM version (as per compiler settings): constantinople

## Steps to Reproduce
`solc --evm-version constantinople foo.sol`  
outputs:
`Invalid option for --evm-version: constantinople`

`solc --evm-version byzantium foo.sol` compiles successfully. 

foo.sol contents:
```solidity
pragma solidity =0.4.21;

contract VoipToken  {
    
    address owner = msg.sender;

    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }
    
    function VoipTken () public {
        owner = msg.sender;    
    }
    
    function withdraw() onlyOwner public {
        address myAddress = this;
        uint256 etherBalance = myAddress.balance;
        owner.transfer(etherBalance);
    }
    
}
```

**Comment by r0qs** [comment]
Hi @elizabethdinella, this error is due to a bug on that release and the proper support for `constantinoble` EVM version through the command line was only added in version `0.4.22`. See: https://github.com/ethereum/solidity/commit/a59d6d2e5303e714a6e66a5d11bd6a9c2e904e4e and https://github.com/ethereum/solidity/pull/3713

Can you try with `0.4.22` instead of `0.4.21`?

**Comment by r0qs** [comment]
Just tested here and your example works on `0.4.22` for both EVM versions, so I'm closing this issue ;)
