### ISSUE TITLE
Allow `pop()` to take an argument indicating how many elements to remove from a storage array

### ISSUE THREAD

**Issue by 0xbok** [ethereum/solidity#14207]
## Abstract

Removing `n` elements from the end of a storage array requires calling `pop()` on it `n` times. This `delete`s the last element and decrements the length of the array. So I have to pay gas to update the storage slot containing length `n` times.

## Motivation

If `pop()` can take an argument, `pop(n)` will just decrement array length by `n`. It can skip deleting the corresponding elements which is the same behavior when `delete` is called on the storage array. This can save gas cost when popping a storage array more than once.

## Specification

For storage arrays, extend `pop()` to take an argument `n` (an unsigned integer). If `x` is a storage array, `x.pop(n)` decreases `x`'s length by `n` if `x.length >= n`; otherwise it reverts.

## Backwards Compatibility

This should be backward compatible as `pop(n)` on storage arrays does not exist yet.

**Comment by Coollaitar** [comment]
```solidity
pragma solidity ^0.8.0;

contract MyContract {
    uint[] storageArray;
    
    function pop(uint n) public {
        require(storageArray.length >= n, "Insufficient elements to pop");
        
        // Reduce the length of the array by n
        assembly {
            mstore(storageArray, sub(mload(storageArray), n))
        }
    }
}
```

**Comment by 0xbok** [comment]
@Coollaitar this should be sstore and sload.

**Comment by ekpyron** [comment]
The reason we don't do this is that the compiler keeps storage slots that are unused clean, as in ``pop`` explicitly writes zeroes to the slots - hence the operation is more expensive than simply overwriting the length field, and we don't provide convenience syntax for this in order not to hide the fact that this will inherently be an expensive loop.

We *can't* get around zeroing the slots, since the compiler assumes that the slots are zero on ``push``es, etc.
So to be clear: just writing a new length to the array in assembly leads to non-sane undefined behaviour that can lead to hard-to-detect bugs.

**Comment by 0xbok** [comment]
thanks, good to know!
