### ISSUE TITLE
`solc --help` incorrectly states that `solc` will read from stdin when no input file is given

### ISSUE THREAD

**Issue by davidBar-On** [ethereum/solidity#14259]
## Description
`solc --help` say: "Compiles the given Solidity input files (or the standard input if **none given** or "-" is used as a file name) ...".
However, when running `solc` it behave the same as `solc --help`.  `solc -` works properly and allows using the standard input.
The help text may need to be changed to something like "Compiles the given Solidity input files (or the standard input if "-" is used as a file name) ...".

## Environment

- Compiler version: 0.8.21-develop.2023.5.23+commit.a2a00850.Linux.g++
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): WSL Ubuntu command line
- EVM execution environment / backend / blockchain client:
- Operating system: Linux (WSL Ubuntu)

## Steps to Reproduce
Run `solc` with no other parameters.

**Comment by cameel** [comment]
Yeah, looks like the help text needs to be adjusted. Thanks for the report!

This behavior was introduced in #3696 because some users found it confusing that `solc` would wait for input if no input files were given. It does work the way described in the help text with `--standard-json` but not in other input modes (and this discrepancy looks like a small bug).

Actually, we could still support the described behavior without confusing users - by reading from stdin only if it was redirected. We already do that when `solc` is invoked with no arguments at all, which allows us to display the help text in that case. But we won't be doing any bigger changes to the CLI in the near future so just adjusting the help text is the best solution for now.

Feel free to submit a PR with a correction.

**Comment by davidBar-On** [comment]
Submitted PR #14262.

**Comment by matheusaaguiar** [comment]
Fixed by #14262 .
