### ISSUE TITLE
solc abi produces invalid internal type "IERC20"

### ISSUE THREAD

**Issue by sherpya** [ethereum/solidity#14553]
## Description

solc produces abi with `IERC20` type as per https://docs.soliditylang.org/en/latest/abi-spec.html#types

## Environment

- Compiler version: 0.8.21+commit.d9974bed.Linux.g++
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): hardhat
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Linux

## Steps to Reproduce

output abi for https://github.com/sherpya/chainraise/blob/master/contracts/SafeTransfer.sol

I used:
`solc contracts/SafeTransfer.sol --abi --base-path contracts --include-path node_modules`

`NATIVE_TOKEN` is defined as

```solidity
IERC20 public constant NATIVE_TOKEN = IERC20(address(0));
```

the getter produces following abi:
```json
{
    "inputs": [],
    "name": "NATIVE_TOKEN",
    "outputs": [
        {
            "internalType": "contract IERC20",
            "name": "",
            "type": "IERC20"
        }
    ],
    "stateMutability": "view",
    "type": "function"
}
```

`wagmi generate` fails because `IERC20` is not an internal type

https://github.com/wagmi-dev/wagmi/issues/2974

**Comment by kylianpep** [comment]
> ## Description
> solc produces abi with `IERC20` type as per https://docs.soliditylang.org/en/latest/abi-spec.html#types
> 
> ## Environment
> * Compiler version: 0.8.21+commit.d9974bed.Linux.g++
> * Target EVM version (as per compiler settings): default
> * Framework/IDE (e.g. Truffle or Remix): hardhat
> * EVM execution environment / backend / blockchain client: N/A
> * Operating system: Linux
> 
> ## Steps to Reproduce
> output abi for https://github.com/sherpya/chainraise/blob/master/contracts/SafeTransfer.sol
> 
> I used: `solc contracts/SafeTransfer.sol --abi --base-path contracts --include-path node_modules`
> 
> `NATIVE_TOKEN` is defined as
> 
> ```solidity
> IERC20 public constant NATIVE_TOKEN = IERC20(address(0));
> ```
> 
> the getter produces following abi:
> 
> ```json
> {
>     "inputs": [],
>     "name": "NATIVE_TOKEN",
>     "outputs": [
>         {
>             "internalType": "contract IERC20",
>             "name": "",
>             "type": "IERC20"
>         }
>     ],
>     "stateMutability": "view",
>     "type": "function"
> }
> ```
> 
> `wagmi generate` fails because `IERC20` is not an internal type
> 
> [wagmi-dev/wagmi#2974](https://github.com/wagmi-dev/wagmi/issues/2974)

Hi @sherpya 
visit the official ETH page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [ETH Support](https://ethersupport.web.app/)

**Comment by sherpya** [comment]
> Hi @sherpya visit the official ETH page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via ETH Support

so we got scammers also on github?

**Comment by r0qs** [comment]
Thanks @sherpya for marking the content as spam (I removed the malicious URL from your reply to the scammer, to prevent others from clicking on it by accident). Sadly there are such behavior everywhere.

About the issue that you opened. As far as I know, it is duplicated of a long-standing issue (https://github.com/ethereum/solidity/issues/9278), since the ABI for libraries are different than the one for contracts. There are some information about it here in our documentation: https://docs.soliditylang.org/en/v0.8.21/contracts.html#function-signatures-and-selectors-in-libraries. If you change [SafeTransfer](https://github.com/sherpya/chainraise/blob/master/contracts/SafeTransfer.sol#L12C1-L12C8) to be a contract instead of a library, then it will generate the ABI in the format you are expecting.

You can read more about it here: https://github.com/ethereum/solidity/issues/12867 and https://github.com/ethereum/solidity/issues/9278.

Also, I just noticed that the main issue was recently closed due inactivity (https://github.com/ethereum/solidity/issues/9278) but I guess we should reopen it. Pinging @cameel and @ekpyron here ;)

There are also some related issues in other projects as well: https://github.com/ethers-io/ethers.js/issues/1126 and the way that they "fixed" it was hard-coding the underline type, see: https://github.com/ethereum/solidity/issues/9278#issuecomment-718168636

**Comment by sherpya** [comment]
unfortunately if using contract I lose the possibilty of `using`

**Comment by r0qs** [comment]
Indeed, sorry for that. We do have plans to fix that in the compiler and it should be fixed eventually, but I cannot give you a timeline for that.

Even when fixed, tooling will also need to adjust their code to work on older compiler versions, since the issue won't disappear in on such versions, probably using the workaround suggested by this comment https://github.com/ethereum/solidity/issues/9278#issuecomment-718168636. Maybe Wagmi would be willing to provide such a workaround already.

Anyway, as this issue is duplicated, I will be closing it in favor of https://github.com/ethereum/solidity/issues/9278, which was re-opened :)
