### ISSUE TITLE
Solidity 0.8.21, Type string and bytes32 issues when overloading.

### ISSUE THREAD

**Issue by DevUreak** [ethereum/solidity#14584]
## Description

When overloading, string and bytes32 types cannot be distinguished

TypeError: No unique declaration found after argument-dependent lookup.

If it is an overloading function that we are familiar with, and shouldn't it work according to Solidity syntax?

## Environment

- Compiler version: 0.8.21 
- Target EVM version (as per compiler settings): shanghai
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: 
- Operating system: 

## Steps to Reproduce

```solidity

function same (bytes32 value) public pure {
    
}

function same (string memory value) public pure {
    
}
same("hello");

```
-->

**Comment by r0qs** [comment]
Hi @DevUreak, currently string literals are not really of the type `string` nor `bytes32` but are implicitly convertible to both types. For a literal, without an explicit conversion, the compiler cannot determine which function should be called.

In yours particular case, you could use a [hexadecimal string literal](https://docs.soliditylang.org/en/latest/types.html#hexadecimal-literals) as a workaround, since it is only convertible to bytes and not to string. Or use a variable instead of string literal. Please see the example below:

```solidity
pragma solidity >=0.8.2 <0.9.0;

contract C {
    function same (bytes32 value) public pure {}
    function same (string memory value) public pure {}
   
    function f() external pure {
        same(hex"001122FF");
        // or
        //string memory s = "lala";
        //same(s);
    }
}
```

Sadly, there's no good solutions for the current syntax without changing the language significantly, which is something we won't do now. However,  we are currently working in a rewrite of the type system and issues like this one will probably be fixed in the future, but there is no time line for that.

**Comment by DevUreak** [comment]
Thank you for answer. I said that overloading functions that cannot actually be called should be handled as exceptions at the compilation stage. thank you

**Comment by r0qs** [comment]
> Thank you for answer. I said that overloading functions that cannot actually be called should be handled as exceptions at the compilation stage. thank you

Hi @DevUreak, but they are, no? Your code does not compile for the reasons I explained above and the compiler will throw the error you mentioned during compilation. I.e.:

* This will not compile:
```solidity
contract C {
    function same (bytes32 value) public pure {}
    function same (string memory value) public pure {}

    function f() external pure {
        same("hello"); // This does not compile because the compiler cannot determine which function to use when passing a string literal.
                       // TypeError: No unique declaration found after argument-dependent lookup.
    }
}
```

* This will compile:
```solidity

contract C {
    function same (bytes32 value) public pure {}
    function same (string memory value) public pure {}
   
    function f() external pure {
        same(hex"001122FF"); // This will resolve to `same(bytes32 value)`

        string memory s = "hello";
        same(s); // This will resolve to `same(string memory value)`
    }
}
```
