### ISSUE TITLE
solc/yul disable all optimisations flag

### ISSUE THREAD

**Issue by winsvega** [ethereum/solidity#14619]
Currently there is no way to completely disable optimisations from cmd when using solc. 
The only way to do it is this:

> Create x.yul with this content:

```
{
   pop(mload(0x20))
}
```

When you compile it normally:

```
qbzzt1@tests:~/yul$ ./solc --yul x.yul

======= x.yul (EVM) =======

Pretty printed source:
object "object" {
    code { { } }
}


Binary representation:
00

Text representation:
    /* "x.yul":0:23   */
  stop
```

But if you create this inp.json file:

```
qbzzt1@tests:~/yul$ cat inp.json 
{
  "language": "Yul",
  "sources":
  {
     "x.yul":
     {
        "urls": ["./x.yul"]
     }
  },
  "settings": {
    "outputSelection": {
      "*": {
        "*": [ "evm.bytecode" ]
      }
    },
    "optimizer": {
      "details": {
         "yul": true,
         "yulDetails": {
         }
      }
    }
  }
}
```

And run 

```
./solc --standard-json inp.json | jq .contracts[].object.evm.bytecode.object
```

You get the result we actually want.

```
qbzzt1@tests:~/yul$ ./solc --standard-json inp.json | jq .contracts[].object.evm.bytecode.object
"60205100"
```

the default cmd flag `--no-optimize-yul` does not do that. optimisations still executed. am I missing smth?

**Comment by r0qs** [comment]
Hi @winsvega, I'm assuming you are using Solidity version `0.8.21`. And since that version there are a minimal set of optimizations that are now enable by default. See this [changelog](https://github.com/ethereum/solidity/releases/tag/v0.8.21) entry:
```
Yul Optimizer: Stack-to-memory mover is now enabled by default whenever possible for via IR code generation
and pure Yul compilation.
```

May I ask for what reason would you like to disable optimizations? Is that causing any problems for you? If so, could you please share what kind of problems is it causing?

I believe these discussions here https://github.com/ethereum/solidity/pull/14149#discussion_r1174026509 and here: https://github.com/ethereum/solidity/issues/14470#issuecomment-1706467804 are also relevant for you.

However, using the compiler settings that you provided does not yield the same bytecode as in your example when compiling via standard JSON, i.e.:

Using the following settings with solidity `0.8.21`:
```json
    "optimizer": {
      "details": {
         "yul": true,
         "yulDetails": {
         }
      }
    }
```

Results in the following:
```json
{
  "contracts": {
    "x.yul": {
      "object": {
        "evm": {
          "bytecode": {
            "functionDebugData": {},
            "generatedSources": [],
            "linkReferences": {},
            "object": "00",
            "opcodes": "STOP ",
            "sourceMap": "0:23:0:-:0"
          }
        }
      }
    }
  },
  "errors": []
}
```

This is now the same as when using `"yul": false` since solidity version `0.8.21`, because [UnusedPruner](https://docs.soliditylang.org/en/latest/internals/optimizer.html#unused-pruner) is now enabled by default. Which will produces the same bytecode when using the CLI:
```
Binary representation:
00
```

If you really need to disable optimizations, you can use the following settings as mentioned [here](https://github.com/ethereum/solidity/pull/14149#discussion_r1174026509), although it is counter intuitive:
```json
"optimizer": {
      "details": {
         "yul": true,
         "yulDetails": {
	      "optimizerSteps": ":"
         }
      }
    }
```

This will result in the bytecode you are expecting:
```json
{
  "contracts": {
    "x.yul": {
      "object": {
        "evm": {
          "bytecode": {
            "functionDebugData": {},
            "generatedSources": [],
            "linkReferences": {},
            "object": "60205100",
            "opcodes": "PUSH1 0x20 MLOAD STOP ",
            "sourceMap": "15:4:0:-:0;9:11;5:16"
          }
        }
      }
    }
  },
  "errors": []
}
```

Or you can use solidity `<= 0.8.20`:
```
> solc-v0.8.20 --yul x.yul
...
Binary representation:
60205150
```

**Comment by winsvega** [comment]
We are using solc yul to compile bytecode for tests. and it really breaks some of the tests since we need a strict bytecode sometimes. 
the everchanging optimisations result in a different bytecode compiled by different versions of solc, which leads to different gas metrics, different code hashes and CREATE2 opcode destination changes. 
So we have to update the tests each time with solc update. an we want to be update with the most recent solc version for test generation.

**Comment by r0qs** [comment]
Hi @winsvega, does the option that I suggested to disable optimizations work for you? You can use it via command-line as well by doing: `solc --strict-assembly --optimize --yul-optimizations=":" x.yul`

Please, note that unfortunately, you will need to use the `optimize` flag but pass the empty optimization sequence (i.e. `":"`). 

FYI, we discussed this issue today in our weekly meeting and we will add a proper CLI flag to disable optimizations in the same way that the combination that I mentioned above works.

**Comment by winsvega** [comment]
Let me check

**Comment by qbzzt** [comment]
> Hi @winsvega, does the option that I suggested to disable optimizations work for you? You can use it via command-line as well by doing: `solc --strict-assembly --optimize --yul-optimizations=":" x.yul`
> 
> Please, note that unfortunately, you will need to use the `optimize` flag but pass the empty optimization sequence (i.e. `":"`).
> 
> FYI, we discussed this issue today in our weekly meeting and we will add a proper CLI flag to disable optimizations in the same way that the combination that I mentioned above works.

Sorry, but it doesn't work. I tried with solc 0.8.21 on Linux.

```
qbzzt1@tests:~/yul$ ./solc --strict-assembly --optimize  optimizations=":" x.yul 

======= x.yul (EVM) =======

Pretty printed source:
object "object" {
    code { { } }
}


Binary representation:
00

Text representation:
    /* "x.yul":0:23   */
  stop
```

**Comment by cameel** [comment]
Please try this:

```bash
./solc --strict-assembly --optimize --yul-optimizations=":" x.yul
```

You're missing the `--` part before the option. The only reason you're not getting an error is that the `=` makes it look like a [remapping](https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping) to the compiler. I think it would be a good idea to disallow specifying remappings in situations where they are ignored, but that's a separate issue.

**Comment by qbzzt** [comment]
Thank you, it works!!! And sorry for wasting everybody's time - I really should get more sleep.

**Comment by r0qs** [comment]
Closing this in favor of https://github.com/ethereum/solidity/issues/14621
