### ISSUE TITLE
ParserError: Use of unary + is disallowed.

### ISSUE THREAD

**Issue by alex1448** [ethereum/solidity#14624]
## Description
The use of unary operator ```+``` is disallowed during parsing stage since version ```0.8.20```, but it looks like some valid expressions are also disallowed. Since version ```0.8.20```, the following program is not accepted:

```solidity
pragma solidity ^0.8.20;

function f() pure {
  (0) + 1;
}
```
Compiler output:
```
Error: Use of unary + is disallowed.
 --> error.sol:4:7:
  |
4 |   (0) + 1;
  |       ^
```

I believe the error is triggered when a binary expression (with operator ```+```) is being used as an expression statement and the left operand is any tuple expression. The right operand can be anything.

## Environment

- Compiler version: 0.8.20

**Comment by r0qs** [comment]
Hi @alex1448, unary `+` is indeed disallowed since Solidity `0.8.20`, see here for more details: https://github.com/ethereum/solidity/pull/14139/files

~However, your example should compile fine (if you use the return of the expression), since it uses `+` as a binary operator, see this example here: https://remix.ethereum.org/?#language=solidity&version=soljson-v0.8.20+commit.a1b79de6.js&code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IEdQTC0zLjAKCnByYWdtYSBzb2xpZGl0eSBeMC44LjIwOwoKZnVuY3Rpb24gZigpIHB1cmUgcmV0dXJucyh1aW50KSB7CiAgLy91aW50IHggPSArKDEpIC0gMTsgLy8gPC0tIFRoaXMgaXMgZGlzYWxsb3dlZAogIHJldHVybiAoMCkgKyAxOwp9~

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.20;

function f() pure returns(uint) {
  //uint x = +(1) - 1; // <-- This is disallowed
  return (0) + 1; // <-- This compiles (see link above)
}
```

~Sadly, I could not reproduce your error.~

**Comment by r0qs** [comment]
Oh, I see the problem, you are right. It should emit a warning that the statement is unaffected, but instead it parses it as unary operator when you have only `(0) + 1`. If you do `uint x = (0) + 1` or use the return of the expression it parses it correctly.

**Comment by cameel** [comment]
Yeah, definitely a bug in #14139. Apparently we have no coverage for this case or it would have come up in testing. Interesting that this only affects the expression on its own and not in an assignment.

**Comment by alex1448** [comment]
Hello again @r0qs and @cameel, indeed, it only appears when the expression is used by itself as a statement. However, I also found out that the left operand does not have to be a tuple expression only. For example, the statement ```this.x + 1;``` also has the same error, but ```x + 1;``` or ```this.x() + 1;``` does not. And possibly other cases where this happens. I thought to mention this in case it is useful.
