### ISSUE TITLE
In yul, there's a bug when mixing `verbatim`, `switch`, and unoptimized code

### ISSUE THREAD

**Issue by qbzzt** [ethereum/solidity#14640]
## Description

We need unoptimized Yul code to measure gas costs (see https://github.com/ethereum/solidity/issues/14621). This is often facilitated using expressions such as:

```
delta := verbatim_1i_1o(hex"<gas><swap1><operation, which uses the parameter><gas><swap1><sub>", <input value>)
```

However, such expressions tend to confuse the compiler when put inside a `switch` statement

## Environment

- Compiler version:
  ```
  qbzzt1@tests:~/yul$ ./solc --version
  solc, the solidity compiler commandline interface
  Version: 0.8.21+commit.d9974bed.Linux.g++
  ```

- Target EVM version (as per compiler settings): The default, but I also verified with `--evm-version shanghai`.

- Framework/IDE (e.g. Truffle or Remix): None

- EVM execution environment / backend / blockchain client: Geth, but I can prove that's not the issue.

- Operating system: 

  Running on GCP
  ```
  qbzzt1@tests:~/yul$ uname -a
  Linux tests 5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
  qbzzt1@tests:~/yul$ 
  ```

## Steps to Reproduce

Compile this Yul code:

```yul
{
  let dummy := 0xAABBCCDDEEFF
  let input := sload(0)
  let output

  // I also verified this when switching on a variable's value
  switch input
  // This is the case that needs to be executed
  case 0x00 {
      output := verbatim_1i_1o(hex"506000", dummy)

      // Case gets executed with this (logically equivalent) code:
      // output := verbatim_0i_1o(hex"6000")
  }
  case 0x01 {
      output := 1 
  }
  // This is the case that actually gets executed.
  // It is the last but one case.
  case 0x02 {
      output := verbatim_1i_1o(hex"506002", dummy)

      // The first case gets executed correctly if I put here
      // this (logically equivalent) code
      // output := verbatim_0i_1o(hex"6002")
  }          
  case 0x03 {
      output := 3
  }          

  sstore(0, output)
}
```

Using the command line:

```sh
./solc --strict-assembly --optimize --yul-optimizations=":" x.yul 
```

The binary you get is: 

```
5f805465aabbccddeeff8115602e578160011460385781600214602e57506003146027575f55005b5060035f55005b9150505060025f55005b50505060015f5500
```

When I run it on geth, starting with empty storage, I get this output:

```
    "0xcccccccccccccccccccccccccccccccccccccccc" : {
        "code" : "0x5f805465aabbccddeeff8115602e578160011460385781600214602e57506003146027575f55005b5060035f55005b9150505060025f55005b50505060015f5500",
        "nonce" : "0x01",
        "balance" : "0x0186a0",
        "storage" : {
            "0x00" : "0x02"
        }
    }
```

Even though `sload(0)` returns zero (we start from an empty storage), so `input` is zero and therefore we'd expect the first case of the `switch` to happen, not the third.

Here is a raw trace:

```
{"pc":0,"op":95,"gas":"0x26207f8","gasCost":"0x2","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH0"}
{"pc":1,"op":128,"gas":"0x26207f6","gasCost":"0x3","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"DUP1"}
{"pc":2,"op":84,"gas":"0x26207f3","gasCost":"0x834","memSize":0,"stack":["0x0","0x0"],"depth":1,"refund":0,"opName":"SLOAD"}
{"pc":3,"op":101,"gas":"0x261ffbf","gasCost":"0x3","memSize":0,"stack":["0x0","0x0"],"depth":1,"refund":0,"opName":"PUSH6"}
{"pc":10,"op":129,"gas":"0x261ffbc","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff"],"depth":1,"refund":0,"opName":"DUP2"}
{"pc":11,"op":21,"gas":"0x261ffb9","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff","0x0"],"depth":1,"refund":0,"opName":"ISZERO"}
{"pc":12,"op":96,"gas":"0x261ffb6","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff","0x1"],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":14,"op":87,"gas":"0x261ffb3","gasCost":"0xa","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff","0x1","0x2e"],"depth":1,"refund":0,"opName":"JUMPI"}
{"pc":46,"op":91,"gas":"0x261ffa9","gasCost":"0x1","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff"],"depth":1,"refund":0,"opName":"JUMPDEST"}
{"pc":47,"op":145,"gas":"0x261ffa8","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff"],"depth":1,"refund":0,"opName":"SWAP2"}
{"pc":48,"op":80,"gas":"0x261ffa5","gasCost":"0x2","memSize":0,"stack":["0xaabbccddeeff","0x0","0x0"],"depth":1,"refund":0,"opName":"POP"}
{"pc":49,"op":80,"gas":"0x261ffa3","gasCost":"0x2","memSize":0,"stack":["0xaabbccddeeff","0x0"],"depth":1,"refund":0,"opName":"POP"}
{"pc":50,"op":80,"gas":"0x261ffa1","gasCost":"0x2","memSize":0,"stack":["0xaabbccddeeff"],"depth":1,"refund":0,"opName":"POP"}
{"pc":51,"op":96,"gas":"0x261ff9f","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":53,"op":95,"gas":"0x261ff9c","gasCost":"0x2","memSize":0,"stack":["0x2"],"depth":1,"refund":0,"opName":"PUSH0"}
{"pc":54,"op":85,"gas":"0x261ff9a","gasCost":"0x4e20","memSize":0,"stack":["0x2","0x0"],"depth":1,"refund":0,"opName":"SSTORE"}
{"pc":55,"op":0,"gas":"0x261b17a","gasCost":"0x0","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"STOP"}
{"output":"","gasUsed":"0x567e"}
```

Tracing the code manually shows us what happens:

| PC | Opcode | Stack (after operation) |
| -: | - | :- |
| 0 | PUSH0 | 0
| 1 | DUP1 | 0,0
| 2 | SLOAD | 0,0
| 3 | PUSH6 0xaabbccddeeff | 0xaa..ff, 0, 0
| 10 | DUP2 | 0, 0xaa..ff, 0, 0
| 11 | ISZERO | 1, 0xaa..ff, 0, 0
| 12 | PUSH1 0x2E | 0x2E, 1, 0xaa..ff, 0, 0
| 14 | JUMPI | 0xaa..ff, 0, 0
| (0x2e=) 46 | JUMPDEST | 0xaa..ff, 0, 0
| 47 | SWAP2 | 0, 0, 0xaa..ff
| 48 | POP | 0, 0xaa..ff
| 49 | POP |  0xaa..ff
| 50 | POP | 
| 51 | PUSH1 0x02 | 2
| 53 | PUSH0 | 0, 2
| 54 | SSTORE | 
| 55 | STOP |

Note that this is an edge case. If I replace either of the `verbatim` expressions with `verbatim_0i_1o(hex"<same operation, but without the initial pop>")`, the compiler works correctly.

**Comment by ekpyron** [comment]
Thank you very much for the report - I just confirmed this.

This is a genuine bug in the libevmasm block-deduplicator's treatment of verbatim assembly items.
The comparison used for the block deduplicator is broken - if there are two blocks that are completely identical except for a difference in the data of a verbatim assembly item, they may wrongfully compare equal. (In your example this leads to the optimizer wrongfully collapsing the jump target of the zero case and the two case.)

You can work around it by disabling the block deduplicator (that's possible via standard-json in the optimizer detail settings). The fix is https://github.com/ethereum/solidity/pull/14649.

We will need to closely evaluate which other effects this bug may have.

**Comment by cameel** [comment]
I tried compiling the code with the buggy operator removed and looks like we have exactly 2 places that use it:

https://github.com/ethereum/solidity/blob/28ee5d3fad770dfaf4c5c1addb9f1ee489bc34e3/libevmasm/BlockDeduplicator.cpp#L76
https://github.com/ethereum/solidity/blob/28ee5d3fad770dfaf4c5c1addb9f1ee489bc34e3/libevmasm/ConstantOptimiser.cpp#L42-L44

The latter will not use the item when `type() == VerbatimBytecode` so looks like `BlockDeduplicator` must be the only affected component.

**Comment by cameel** [comment]
Here's what I found regarding the use of `verbatim` in the wild.

### Optimism
As far as I can tell, Optimism switched to a new design shortly after we introduced `verbatim`, which made it unnecessary for them.

[OVM Deep Dive](https://medium.com/ethereum-optimism/ovm-deep-dive-a300d1085f52) seems to describe how it worked at the time of https://github.com/ethereum/solidity/issues/10869#issuecomment-773649502 (February 2021). Back then the bytecode had to be specially crafted to replace some opcodes with calls to an "Execution Manager" contract and this was done using [solc-transpiler](https://www.npmjs.com/package/@eth-optimism/solc-transpiler). In July we released 0.8.5 with support for `verbatim`.

[Optimism's Solidity fork](https://github.com/ethereum-optimism/solidity) was retired in May 2021. Maybe they toyed with `verbatim`, but even if so, probably not for long. [Introducing EVM Equivalence](https://medium.com/ethereum-optimism/introducing-evm-equivalence-5c2021deb306) from October 2021 already describes a new system that simulates EVM to run bytecode as is. There's no mention of any transpilation.

The current [official instructions for deploying to Optimism using various frameworks](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/getting-started) don't mention any special compilation or post-processing step. Sample configs just have the frameworks use solc the way they normally do.

### Ethereum Execution Tests
Execution tests use `verbatim` a lot. See [search for `verbatim` in `ethereum/tests`](https://github.com/search?q=repo%3Aethereum%2Ftests+verbatim&type=code).

### zkSync Era
`verbatim` is used in zkSync precompiles and some contracts, e.g.:
- [`SHA256.yul`](https://github.com/matter-labs/era-system-contracts/blob/main/contracts/precompiles/SHA256.yul)
- [`EventWriter.yul`](https://github.com/matter-labs/era-system-contracts/blob/main/contracts/EventWriter.yul)
- [code search for `verbatim` in `matter-labs` org](https://github.com/search?q=org%3Amatter-labs+verbatim+path%3A*.yul&type=code)

Those do not seem relevant to us. They use solc only for generating Yul and metadata. Yul is then compiled into circuits using their own [zksolc](https://era.zksync.io/docs/tools/compiler-toolchain/solidity.html). Since they do not emit bytecode, `verbatim` seems to be used differently, apparently using some primitives from their target, e.g.  `verbatim_2i_1o("precompile", precompileParams, gasToBurn)`. So there's no risk of someone trying to compile and deploy it on the mainnet.

### Other uses
I did not see any other significant use of `verbatim` in public repos.

There are tiny experimental libs like [`Fmuldiv.yul`](https://github.com/bitwise343/fmuldiv/blob/main/src/Fmuldiv.yul) but no large public projects using it.

Here are [other results from code search](https://sourcegraph.com/search?q=context%3Aglobal++lang%3AYul+content%3A"verbatim"+++-repo%3Aethereum%2Fsolidity+-repo%3Amatter-labs&patt1ernType=regexp&case=yes&sm=0&groupBy=repo) if case anyone wants to browse through them.

**Comment by qbzzt** [comment]
Yes. Since the OVM 2.0 fork went into production (Nov 2021) Optimism had no reason to do anything strange with the Solidity compiler.

I know the execution tests use `verbatim` a lot, I think I wrote most of those tests. The most common reason is that we need to have tests for opcodes early, usually before they are available in Yul. The second reason (which is how I discovered this bug) is that the Yul compiler does some rearranging that makes it difficult to measure the gas costs of operations. `verbatim` lets us avoid all of those changes.

**Comment by Subway2023** [comment]
How did you discover such complex bugs? Was it through differential testing?

**Comment by qbzzt** [comment]
Not differential testing, just use in execution layer tests. We use
`verbatim` a lot because we need to test opcodes before the compiler is
updated to support them. Some tests stopped working.

**Comment by Morhef** [comment]
Hi

**Comment by Jon2791-Lobo** [comment]
{"pc":0,"op":95,"gas":"0x26207f8","gasCost":"0x2","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH0"}
{"pc":1,"op":128,"gas":"0x26207f6","gasCost":"0x3","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"DUP1"}
{"pc":2,"op":84,"gas":"0x26207f3","gasCost":"0x834","memSize":0,"stack":["0x0","0x0"],"depth":1,"refund":0,"opName":"SLOAD"}
{"pc":3,"op":101,"gas":"0x261ffbf","gasCost":"0x3","memSize":0,"stack":["0x0","0x0"],"depth":1,"refund":0,"opName":"PUSH6"}
{"pc":10,"op":129,"gas":"0x261ffbc","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff"],"depth":1,"refund":0,"opName":"DUP2"}
{"pc":11,"op":21,"gas":"0x261ffb9","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff","0x0"],"depth":1,"refund":0,"opName":"ISZERO"}
{"pc":12,"op":96,"gas":"0x261ffb6","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff","0x1"],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":14,"op":87,"gas":"0x261ffb3","gasCost":"0xa","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff","0x1","0x2e"],"depth":1,"refund":0,"opName":"JUMPI"}
{"pc":46,"op":91,"gas":"0x261ffa9","gasCost":"0x1","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff"],"depth":1,"refund":0,"opName":"JUMPDEST"}
{"pc":47,"op":145,"gas":"0x261ffa8","gasCost":"0x3","memSize":0,"stack":["0x0","0x0","0xaabbccddeeff"],"depth":1,"refund":0,"opName":"SWAP2"}
{"pc":48,"op":80,"gas":"0x261ffa5","gasCost":"0x2","memSize":0,"stack":["0xaabbccddeeff","0x0","0x0"],"depth":1,"refund":0,"opName":"POP"}
{"pc":49,"op":80,"gas":"0x261ffa3","gasCost":"0x2","memSize":0,"stack":["0xaabbccddeeff","0x0"],"depth":1,"refund":0,"opName":"POP"}
{"pc":50,"op":80,"gas":"0x261ffa1","gasCost":"0x2","memSize":0,"stack":["0xaabbccddeeff"],"depth":1,"refund":0,"opName":"POP"}
{"pc":51,"op":96,"gas":"0x261ff9f","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":53,"op":95,"gas":"0x261ff9c","gasCost":"0x2","memSize":0,"stack":["0x2"],"depth":1,"refund":0,"opName":"PUSH0"}
{"pc":54,"op":85,"gas":"0x261ff9a","gasCost":"0x4e20","memSize":0,"stack":["0x2","0x0"],"depth":1,"refund":0,"opName":"SSTORE"}
{"pc":55,"op":0,"gas":"0x261b17a","gasCost":"0x0","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"STOP"}
{"output":"","gasUsed":"0x567e"}``
