### ISSUE TITLE
Make solidity internal libraries optionally installable

### ISSUE THREAD

**Issue by leo4048111** [ethereum/solidity#14669]
## Abstract

The goal is to incorporate libsolidity and its associated static libraries into my personal project seamlessly. The current approach involves cloning the entire repository and compiling from source, subsequently linking the Solidity targets with my project's targets. This process is highly time-consuming and significantly hampers the compilation speed due to the need to validate the built Solidity targets during each build iteration.
Thus, I propose the idea of making the internal libraries of Solidity (e.g., libsolidity, libyul, etc.) available for optional installation to streamline this integration process.

## Motivation

While a manual workaround exists, which involves copying the build artifacts directly into global library and header search paths (like `/usr/local/lib`), automating this process with a make install command would greatly enhance efficiency and reliability.

## Specification

The features I am advocating for inclusion are as follows:

+ Addition of `install(TARGETS, ...)` within the CMakeLists of the Solidity internal libraries.
+ Creation of CMake options that allow users to opt for the installation of internal libraries upon executing the `make install` command, for instance, through `eth_default_option(INSTALL_LIBS ON)`.
+ Development of a FindSolidity.cmake script to enable the use of the `find_package` function in CMake.

**Comment by ekpyron** [comment]
The repository is indeed currently not particularly well-designed to be pulled in as a dependency (other than building it as part of your project e.g. as a submodule). Since this is not the main expected use of the compiler at this point (this may change in the future), we currently also don't really have the resources to properly support its use as a library across platforms.

That being said, I'd be open to accepting a PR that adds the required options to cmake, while making them **disabled by default** and adding a short **explanatory text** to them stating that this is currently "expected to work, but unsupported".

**Comment by leo4048111** [comment]
Great, thanks for replying. I will work out a detailed PR for revision as soon as possible.

**Comment by ekpyron** [comment]
For the record: since the internal headers have further dependencies that we cannot reasonably install ourselves, the only internal library that we *could* impose like this (header-wise) is ``libsolc/libsolc.h``.

**Comment by leo4048111** [comment]
Understood, thanks for the information, issue closed.
