### ISSUE TITLE
[profile.default.model_checker] extCalls = "trusted" is not working as expected!

### ISSUE THREAD

**Issue by acmLL** [ethereum/solidity#14695]
When performing ** forge build --force ** in a Mac (macOS Monterey v12.7.1 Intel i7 Dual-Core, 2,2GHz, 8GB RAM), Z3 version 4.12.2 - 64 bit, using a foundry.toml as follows:

[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.model_checker]
extCalls = "trusted"
engine = "chc"
solvers = [ "z3" ]
timeout = 0
targets = [
	"assert"
]
showProved = true
showUnproved = true
showUnsupported = true
showProvedSafe = true

[profile.default.model_checker.contracts]
"src/ERC721Verifications.sol" = [ "ERC721Secure" ]

I am obtaining the following report (partial because the rest is not relevant):

[⠢] Compiling...
[⠊] Compiling 2 files with 0.8.21
[⠒] Solc 0.8.21 finished in 3.81s
Compiler run successful with warnings:
Warning (8729): Contract deployment is only supported in the trusted mode for external calls with the CHC engine.
  --> src/ERC721Verifications.sol:10:26:
   |
10 |         ERC721 myToken = new ERC721("ERC721", "ERC721");

What am I missing with the entry: [profile.default.model_checker] extCalls = "trusted"?

Thanks!

**Comment by nikola-matic** [comment]
I don't see the option [extCalls](https://book.getfoundry.sh/reference/config/solidity-compiler#model-checker) in the book of foundry; I think you may be confusing it with the same options from the [standard JSON](https://docs.soliditylang.org/en/v0.8.22/smtchecker.html#trusted-external-calls) interface of the compiler. Regardless, I'll be closing the issue since this is Foundry related (I suspect you'll have more luck reaching out to them).
