### ISSUE TITLE
Parser doesn't accept empty tuple as a statement

### ISSUE THREAD

**Issue by alex1448** [ethereum/solidity#14713]
## Description

Since version ```0.4.24```, the empty tuple expression as a statement, ```();```, isn't allowed by the parser. Obviously, this statement is not very useful, but I think that a parser should be able to accept any valid syntax, even if meaningless.

Consider for example that the statement ```() + 1;``` is disallowed by the parser, but the statement ```1 + ();``` is disallowed by the type checker. Perhaps both errors should be reported by the type checker.

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.23;

contract C {
  function f() public pure {
    ();
  }
}
```

Compiler output:
```
Error: Expected primary expression.
 --> Empty.sol:7:6:
  |
7 |     ();
  |      ^
```

## Environment

- Compiler version: ```>= 0.4.24```

**Comment by matheusaaguiar** [comment]
Hi @alex1448! 
I don't think this is a bug, albeit it is a bit weird. In your example, the compiler is actually expecting an expression wrapped in parenthesis and that expression never appears. In the case of `1 + ()`, the empty tuple is parsed because it is part of the binary add operation which is already the expected expression.
I understand your point that it would be best for the compiler to recognize that in reality the empty tuple is the one expression there. But unless there is a potential attack or code generation problem arising from this, the team does not have the capacity to commit work to improve this specific case which seems harmless.
I will be closing the issue for now, but, please, don't take that as an end to the discussion. Feel free to provide more information and considerations that can further clarify the situation. In case I am mistaken, we can always reopen the issue, no problem :)
