### ISSUE TITLE
error: unnecessary parentheses in declaration of ‘_literal’ [-Werror=parentheses].  Why?

### ISSUE THREAD

**Issue by Xutp-F** [ethereum/solidity#14752]
[ 81%] Building CXX object libsolidity/CMakeFiles/solidity.dir/inlineasm/AsmParser.cpp.o
afl-cc 2.52b by <lcamtuf@google.com>
/home/ffwang/wff/solidity/libsolidity/inlineasm/AsmParser.cpp: In static member function ‘static bool dev::solidity::assembly::Parser::isValidNumberLiteral(const string&)’:
/home/ffwang/wff/solidity/libsolidity/inlineasm/AsmParser.cpp:609:7: error: unnecessary parentheses in declaration of ‘_literal’ [-Werror=parentheses]
   u256(_literal);
       ^
cc1plus: all warnings being treated as errors
libsolidity/CMakeFiles/solidity.dir/build.make:971: recipe for target 'libsolidity/CMakeFiles/solidity.dir/inlineasm/AsmParser.cpp.o' failed
make[3]: *** [libsolidity/CMakeFiles/solidity.dir/inlineasm/AsmParser.cpp.o] Error 1
CMakeFiles/Makefile2:354: recipe for target 'libsolidity/CMakeFiles/solidity.dir/all' failed
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
CMakeFiles/Makefile2:537: recipe for target 'test/tools/CMakeFiles/solfuzzer.dir/rule' failed
make[1]: *** [test/tools/CMakeFiles/solfuzzer.dir/rule] Error 2
Makefile:299: recipe for target 'solfuzzer' failed
make: *** [solfuzzer] Error 2

boost:1.65.1

**Comment by r0qs** [comment]
Hi @XiaoXiaofanzi could you provide more information of your building environment? For instance, what is the Solidity compiler version you are trying to build? Is it the latest version in the `develop` branch? Because it seems to work fine for me here.
Also, what is your operating system and how you are trying to build the compiler from the source, i.e. the commands you are using.
