### ISSUE TITLE
Parser treats state variable visibility as function type visibility

### ISSUE THREAD

**Issue by alex1448** [ethereum/solidity#14769]
## Description

Parser treats state variable visibility of function types as a visibility for the function type itself in the code given bellow. In this example, ```f``` should be a private state variable of default (internal) function type. Instead it reports an error. The second declaration (of ```g```) works without a problem.

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity =0.8.23;

contract C {
  function () private f;  // this is disallowed
  function () returns (int) private g;  // this is ok
}
```

Compiler output:

```
TypeError: Invalid visibility, can only be "external" or "internal".
 --> contracts/4_Test.sol:6:3:
  |
6 |   function () private f;  // this is disallowed
  |   ^^^^^^^^^^^^^^^^^^^^^
```

## Environment

- Compiler version: ```0.8.23``` or any older version

**Comment by cameel** [comment]
This works as intended. It's just that both of these visibility specifiers are optional. If you provide only one, the compiler has to make an assumption about which one you meant. In this case it decides to interpret it as the visibility of the function.

So `function () private f;` means `function () private internal f;`, which is invalid. If you mean `function () internal private f;` instead, you can bypass this default choice by writing it out in full.

You could argue that the compiler should not make this assumption and just reject the shorthand, but IMO in this case it's pretty harmless. It's unambiguous in the two variants that are allowed, so at worst you get an error and not a variable that has a different visibility than you think it does:
- `function () internal f;` must mean `function () internal internal f;` because both visibilities default to `internal`.
- `function () external f;` must mean `function () external internal f;` because state variables cannot have `external` visibility.
