### ISSUE TITLE
`payable` declaration defaults function to `public` visibility

### ISSUE THREAD

**Issue by z0r0z** [ethereum/solidity#14799]
Seems simple and cool to me without losing anything afaik. I think this is what has already changed for `constructor()`?

**Comment by r0qs** [comment]
Hi @z0r0z, thanks for the question. However, the `payable` modifier can also be applied to functions with `external` visibility. So, I don't see a clear advantage in not explicitly stating it in the function declaration.

> I think this is what has already changed for `constructor()`?

Not really, since Solidity version `0.7.0`, the function visibility is no longer required for constructors (neither `public` nor `internal`). However, note that constructors are not `payable` by default; you need to explicitly declare them as payable.

**Comment by z0r0z** [comment]
thanks for your clarifications and thoughts @r0qs. I think the idea I propose more is that by default anything that is payable be made public as a syntactic sugar. It sort of works with the idea that you can make a constructor payable, and it is public by default. But I appreciate the tension against the fact that external is also optionally payable.
