### ISSUE TITLE
replace `Brownie` with `Ape`

### ISSUE THREAD

**Issue by cenwadike** [ethereum/solidity#14871]
## Page

Resources page

https://docs.soliditylang.org/en/v0.8.24/resources.html#integrated-ethereum-development-environments

## Abstract

Brownie is no longer actively maintained and has been replaced by Ape. 

Ape should replace Brownie to avoid leading new users from using an unmaintained tool.

## Pull request

https://github.com/ethereum/solidity/pull/14870

**Comment by nikola-matic** [comment]
From what I can tell, brownie had a [release](https://github.com/eth-brownie/brownie/releases) just last week, so I wouldn't say it's no longer being actively maintained.

**Comment by cenwadike** [comment]
That's true. However, there is no guarantee for regular release and maintenance.

It would be better to direct devs to tools with some guarantee that the tool will be maintained for the foreseeable future.

**Comment by cameel** [comment]
I'd not go as far as to remove Brownie. If it's still releasing, it still a valid choice. We should list both.

But yeah, even the maintainer admits that there's not going to be much happening there other than basic maintenance and seems supportive of Ape: https://github.com/eth-brownie/brownie/issues/1515#issuecomment-1126926496. So adding a note along these lines would be fair, so that people know that they should try more actively maintained frameworks first.

**Comment by cameel** [comment]
Also, perhaps we should list [Wake](https://getwake.io) too? I actually don't know anything about it, found it only recently, but it claims to be another Python-based Solidity framework.

**Comment by cenwadike** [comment]
I guess I will have to adjust the changes in the pull request to accommodate Brownie too.

**Comment by cameel** [comment]
Let's wait for the discussion to resolve here, especially for @mehtavishwa30's opinion. I'm fine with the change the way I stated above, but ultimately she's the one responsible for maintaining that section of the docs now so it's her call.

**Comment by GAMECHANGE** [comment]
djeva

**Comment by mehtavishwa30** [comment]
Hey @cenwadike! Thank you for bringing this up. It's helpful to know which tools are maintained and should be encouraged as alternatives to older inactive ones. However, as @cameel mentioned, I am planning to do a refresh of the resources page based on a wider ecosystem evaluation of the tooling landscape.

Currently, it makes most sense to introduce the suggested changes only as part of a holistic update rather than addressing individual issues/contributions. This would allow to also accommodate feedback and interest from the larger user community, the yearly survey results, etc. With that reasoning, I will be closing this issue for now. :)
