### ISSUE TITLE
can get the memory address of  array or Bytes  direclty?

### ISSUE THREAD

**Issue by pureland** [ethereum/solidity#1495]
create a call data store in Array/Bytes when use call in internal assembly , call data input by memory address  and datasize, if can get the memory address of array or Bytes?

**Comment by chriseth** [comment]
I am not sure I understood the question, but if you access the name of a memory array variable in inline assembly, the memory position of that variable is "returned". Note that the data in memory starts with the length of the array (one word, 32 bytes) and then only the actual data starts.

In general, such questions are much better suited for ethereum.stackexchange.org - this is only an issue tracker. Because of that, I will close this issue.
