### ISSUE TITLE
Inconsistent storage caused by function-type variable assignment

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#14982]
## Description

The contract involves assigning a function-type variable, followed by compilation using four different types: 'origin', 'optimize', 'viaIr', and 'optimize-viaIr'. Upon executing the four sets of bytecode, inconsistencies in **storage** are observed.

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE: Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```
contract C {
    function() internal returns (uint) a;
    function set() public returns (uint256 ret) {
        a = set;
        assembly{
            ret:=sload(0)
        }
    }
}
```
### optimize
![1712215092147](https://github.com/ethereum/solidity/assets/147013944/0b5692c1-f301-417e-8592-570e9b262116)
### viaIr
![1712214651619](https://github.com/ethereum/solidity/assets/147013944/adddb13c-437e-4aea-ad8a-3aabcea9d273)
![1712215343092](https://github.com/ethereum/solidity/assets/147013944/b3c8a2bf-222f-44a4-8540-5f0090b46128)
### optimize-viaIr
![1712215312782](https://github.com/ethereum/solidity/assets/147013944/16fff451-fcfe-4853-9fbd-c463858fad8c)

### origin
![1712214999992](https://github.com/ethereum/solidity/assets/147013944/cbe5df3b-1184-4133-af69-29289404a13d)
### optimize
![1712215172441](https://github.com/ethereum/solidity/assets/147013944/1d52547a-99e6-48d1-b30f-1bf77ba9f4e0)
### viaIr/optimize-viaIr
![1712215032620](https://github.com/ethereum/solidity/assets/147013944/2921943d-b32e-41f8-add3-9511bfa1ef2c)

**Comment by mehtavishwa30** [comment]
Hey @Subway2023! Thanks for raising the question.

The difference/"inconsistency" in the storage layout that you notice here is caused due to the fact that the IR-codegen represents internal function pointers differently from the old codegen. The old code generator uses code offsets or tags for values of internal function pointers. Whereas in the IR codegen, function pointers use internal IDs that are allocated in sequence.

For reference, you can check out the Solidity docs that describe this [difference between the two codegens](https://docs.soliditylang.org/en/develop/ir-breaking-changes.html#internal-function-pointers).
