### ISSUE TITLE
Interface handling inconsistency between IR-based Codegen and Codegen

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#14993]
## Description
After coercing contract type variables using interfaces and then calling functions within the contract, IR-based Codegen and Codegen may exhibit inconsistent function selection.

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE: Remix
- EVM execution environment / backend / blockchain client: None
- Operating system: None

## Steps to Reproduce

```solidity
interface C0 {
    function g() external pure returns (uint[1] memory);
}
contract C1 {
    function g() external pure returns (uint[3] memory) {}
}
contract C2 {
    function f() public{
        C1 c1 = new C1();
        C0(address(c1)).g();
    }
}
```
Compile and execute the above code under different compilation conditions, debug it, and check the memory. 

### origin/optimize
![1712411698431](https://github.com/ethereum/solidity/assets/147013944/702ee8dd-89cd-4355-95ca-86073bec0fb2)
 The value at 0x40 is 0x100, which is 256 in decimal. Initially, the value at 0x40 is 128. So, 256 - 128 = 128, which exactly corresponds to 4 uint（3uint + length）. Therefore, at this point, the function g from contract C1 is being called

### viaIr and optimize-viaIr
![1712411748526](https://github.com/ethereum/solidity/assets/147013944/d2c2b4bd-fc59-46fc-b8c3-f05159b56b15)

 The value at 0x40 is 0xc0, which is 192 in decimal. Initially, the value at 0x40 is 128. So, 192 - 128 = 64, which exactly corresponds to 2 uint（1uint + length）. Therefore, at this point, the function g from interface C0 is being called

**Comment by cameel** [comment]
This is not a bug. It's an enhancement present in the IR code generator that wasn't (and likely won't) be backported to the legacy codegen.

In #12647/#12684 the IR codegen was changed to allocate only as much memory for the return value as expected based on the target contract's ABI. The legacy codegen would instead copy the whole returndata into memory.

This does not break the interface since the extra returndata would not be decoded as a part of the returned value anyway. It just saves some gas and prevents the target contract from returning so much unaccounted data that it eats up all the gas.
