### ISSUE TITLE
Apt repo is broken

### ISSUE THREAD

**Issue by vemonet** [ethereum/solidity#15008]
A few weeks ago installing `solc` in a debian-based Docker image following the official docs was working without issue.

Here is the `Dockerfile`:

```Dockerfile
FROM python:3.10

WORKDIR /app

RUN apt-get update && \
    apt-get install -y software-properties-common wget build-essential libssl-dev postgresql-client libpq-dev && \
    pip install --upgrade pip

RUN add-apt-repository ppa:ethereum/ethereum
RUN apt-get update
RUN apt-get install -y solc
```

Today it gives:

```
RUN add-apt-repository ppa:ethereum/ethereum:
0.542 Traceback (most recent call last):
0.542   File "/usr/bin/add-apt-repository", line 362, in <module>
0.542     sys.exit(0 if addaptrepo.main() else 1)
0.542                   ^^^^^^^^^^^^^^^^^
0.542   File "/usr/bin/add-apt-repository", line 345, in main
0.543     shortcut = handler(source, **shortcut_params)
0.543                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.543   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
0.543     return handler(shortcut, **kwargs)
0.543            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.543   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
0.543     if self.lpppa.publish_debug_symbols:
0.543        ^^^^^^^^^^
0.543   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
0.543     self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
0.543                   ^^^^^^^^^^^
0.543   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
0.543     self._lpteam = self.lp.people(self.teamname)
0.543                    ^^^^^^^^^^^^^^
0.544 AttributeError: 'NoneType' object has no attribute 'people'
```

The apt repo seems broken

What would be the solution to install solc in Linux in a stable way?  For python based usage later 

I just put the static binary from releases in the path? Do I need to add any environment variables?

**Comment by r0qs** [comment]
Hi @vemonet thank you for opening the issue. As far as I can tell, the problem is not that the PPA is broken, but that your base image, i.e. `python:3.10`, is a [Debian-based image](https://hub.docker.com/layers/library/python/3.10/images/sha256-cf5cac6010f4caa5446516c18f48369215df2e912a12ff314ceb9a1d95a5fd60?context=explore) and not Ubuntu-based, and PPAs are not supported on Debian. You could workaround it by installing: `python3-launchpadlib` (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029766 for further details). However, although this would fix your current error it would attempt to fetch the PPA files for Debian “bookworm” (i.e. Debian 12), which does not exists, since we don't ship it. 

If you want to use the PPA releases, you can change your  base image to a Ubuntu-based image, and everything should work as expected. You can see the list of supported Ubuntu versions here: https://ppa.launchpadcontent.net/ethereum/ethereum/ubuntu/dists/

For reference, you could change your Dockerfile to:
```Dockerfile
FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && \
    apt-get install -y software-properties-common \
    wget build-essential libssl-dev postgresql-client \
    libpq-dev python3.10 python3-pip && \
    pip install --upgrade pip

RUN add-apt-repository ppa:ethereum/ethereum
RUN apt-get update
RUN apt-get install -y solc
```

Or you can download the static binaries as described in our documentation: https://docs.soliditylang.org/en/v0.8.25/installing-solidity.html#static-binaries, or from our repository at: https://github.com/ethereum/solidity/releases, and add it to the system/user path as you mentioned. There is no need to set extra environment variables.
