### ISSUE TITLE
SMTChecker: Unable to correctly determine the return value of a function-type variable call.

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15013]
## Description

Assigning a function to a function-type variable and then calling that variable, the SMTChecker is unable to correctly determine the return value

## Environment

- Compiler version: 0.8.25
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Command-line
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce

```solidity
contract C {
  function() internal returns (uint) a;
  function g() public returns (uint256) {
      return 1;
  }
  function set() public {
      a=g;
      assert(a()==1);
  }
}
```

```bash
solc C.sol --model-checker-engine all
```
![1712925964105](https://github.com/ethereum/solidity/assets/147013944/0dd874ba-2b5a-46ed-967a-1f76bd93c47a)

**Comment by blishko** [comment]
Function pointers are not supported by SMTChecker and it issues a warning about that on this example:
`Warning: SMTChecker: 1 unsupported language feature(s). Enable the model checker option "show unsupported" to see all of them.`

Since SMTChecker over-approximates in the presence of unsupported features, the assertion violation warning is to be expected.
