### ISSUE TITLE
AST-importer fails at version 0.7.6

### ISSUE THREAD

**Issue by Subway2023** [ethereum/solidity#15051]
## Description

When I try to reproduce this bug [DynamicArrayCleanup](https://soliditylang.org/blog/2020/10/07/solidity-dynamic-array-cleanup-bug/) I find that AST-importer fails at version 0.7.6. All versions under 0.8.0 have this problem.

## Environment

- Compiler version: 0.7.6
- Target EVM version (as per compiler settings): No restrictions
- Framework/IDE (e.g. Truffle or Remix): Command-line
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: GPL-3.0
// The bug is present in all versions of solidity prior to 0.7.3
pragma solidity >=0.6.0 <0.7.3;
contract C {
    uint128[] x;
    function f() public {
        x.push(42); x.push(42); x.push(42); x.push(42);
        uint128[] memory y = new uint128[](1);
        y[0] = 23;
        // This will shrink the array x to one element.
        x = y;
        // Resizing the array to length 4.
        x.push(); x.push(); x.push();
        // After resizing the array, its contents are [23, 0, 0, 42],
        // instead of [23, 0, 0, 0]. Resizing can be also be done by
        // assigning to `.length` or by assigning to the `slot` member
        // inside inline assembly.
    }
}
```

```
solc-0706 C.sol --combined-json ast >> C.json
```

```
solc-0706  --bin-runtime --import-ast C.json --metadata-hash none
```

```
Error: 
Failed to import AST: Top-level node should be a 'SourceUnit'
```

**Comment by cameel** [comment]
This is not a bug, on 0.7.x you just need different options to get an AST that `--import-ast` can handle. Use `--combined-json ast,compact-format` or better `--ast-compact-json`.

Historically the format of the AST we output changed a few times. The ones I'm aware of:
- `--ast` CLI option produces legacy non-JSON format, removed in 0.6.0
- `--ast-json` CLI option produces legacy non-compact JSON format, removed in 0.8.0
- `--ast-compact-json` CLI option produces compact JSON format that we support now.
- In Standard JSON we now only have `ast`, which is the compact format. We used to have `legacyAST` there too and off the top of my head I'm not sure which of the legacy formats it produced. `legacyAST` was removed from Standard JSON in 0.8.0 in any case.

`--import-ast` expects the compact format.

Now, the problem with `--combined-json` is that in 0.8.0 we changed its format:
- On 0.7.x `--combined-json ast` produced the non-compact format and `--combined-json ast,compact-format` produced the compact format.
- On 0.8.x `--combined-json ast` produces the compact format and `compact-format` was removed from `--combined-json`.

[Solidity v0.8.0 Breaking Changes > Interface Changes](https://docs.soliditylang.org/en/develop/080-breaking-changes.html#interface-changes) mentions this but very vaguely and not in a way that would help anyone who was not already somewhat aware of what those options were doing. Other than that, I don't think we ever had the various formats, their differences and options properly documented. Unfortunately we can't amend docs for old versions. I also don't think this really has a place in the current docs, since it's more of a historical trivia.
