### ISSUE TITLE
No Documentation Available for compiling from source on ARM machine

### ISSUE THREAD

**Issue by AhsanAliUet** [ethereum/solidity#15287]
Hi,

I am looking for some documentation which is about "Compiling Solidity compiler from source on ARM machine (Raspberry Pi/Jetson Nano)". Almost everything is for AMD64 architecture and nothing about ARM64 architecture.

Can someone please refer me some documentation about ARM64? Or some prebuilt binaries which can run on ARM arhitecture?

Thanks.

**Comment by ekpyron** [comment]
ARM64 is currently not a supported target platform. Since we need to guarantee deterministic compilation across all architectures, adding any new target involves a significant increase in our testing surface - so far the demand for ARM64 builds hasn't been high enough to justify that complexity. The emscripten/WebAssembly builds are platform independent and can be used on ARM64 platforms (albeit with some drawbacks).
