### ISSUE TITLE
Wrong Error Message for Out-of-Bounds Array Access

### ISSUE THREAD

**Issue by abhishekrch** [ethereum/solidity#15331]
## Description

When accessing an out-of-bounds index in a fixed-size array, the contract execution reverts, but the error message provided is a generic revert message that doesn't indicate the specific cause of the error. 

## Reproducible Example

```solidity
pragma solidity ^0.8.26;

contract Array {
    
    uint [6] public arr = [1,2,3];

    function insertElement(uint index, uint value) public {
        arr[index]= value;
    }

    function returnAllElement() public view returns (uint [6] memory) {
        return arr;
    }

    function returnElement(uint index) public view returns (uint) {
        return arr[index];
    }

}

```

## Steps to Reproduce

1. Deploy the above contract
2. Now attempt to access an index that is out of bounds, e.g. arr[8]
3. Call `returnElement(6)` or any index >= 6

## Current Error Message
```
call to Array.returnElement errored: Error occurred: revert.
revert
The transaction has been reverted to the initial state.
Note: The called function should be payable if you send value and the value you send should be less than your current balance.
You may want to cautiously increase the gas limit if the transaction went out of gas.
```

## Expected Behavior
The error message should clearly indicate that the index is out of bounds for the array

## Actual Behavior
The transaction is reverted with a misleading error message that mentions payable functions and gas limits

## Suggested Improvement
Consider updating the error message to clearly state "Array index out of bounds" or similar. 

## Environment

- Compiler version: 0.8.26
- Framework/IDE : Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Windows 10

**Comment by nikola-matic** [comment]
Hi @abhishekrch, and thanks for the report.

Fortunately for us, none of this is a bug (at least nor our bug :)). The `Note: ...` that you're getting is from Remix, and not from the Solidity compiler, so that's not us. The reason that the compiler does not inject error messages into reverts by default is simply due to gas costs; if you're interested getting *some* debug information in your reverts, you can take a look at the `--revert-strings debug` CLI option, or `"revertStrings": "debug"` in the Standard JSON interface (see the [docs](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-api)).

This isn't fully comprehensive, and will inject an error message during the ABI encoding phase.

**Comment by abhishekrch** [comment]
Hi @nikola-matic,
Thank you for your help and clarification.
