### ISSUE TITLE
Initialization order discrepancy between compilation pipelines

### ISSUE THREAD

**Issue by adhusson** [ethereum/solidity#15340]
[Test repository here
](https://github.com/adhusson/solc-initialization-order-discrepancy)

Solidity initializes contracts differently depending on the compilation pipeline selected, in particular inline state variables. The discrepancy has existed since 0.7.6.

Short version:
```
contract Take {
    constructor(uint param) {
        console.log("Take",param);
    }
}

contract Give {
    uint internal PARAM = 1;
}

contract C is Give,Take {
    constructor() Take(PARAM) {
        console.log("C",PARAM);
    }
}
```

* If `new C` is called after compilation with via_ir, `Take` will log `Take 0`. 
* Without via_ir, `Take` will log `Take 1`. 
* In both cases, `C` will log `C 1`.

**Comment by mehtavishwa30** [comment]
Hey @adhusson!

Thanks for bringing this up. However, this behaviour is not a compiler bug and is rather intentional in Solidity language based on the pipeline that is selected. You can check out the official documentation that describes the initialization order for the IR pipeline (see: https://docs.soliditylang.org/en/develop/ir-breaking-changes.html#semantic-only-changes).

Hence, I will be closing this issue. :)
