### ISSUE TITLE
Ambiguity in the documentation about what kind of string is considered as an absolute path

### ISSUE THREAD

**Issue by pirapira** [ethereum/solidity#1534]
In the documentation, in `layout-of-source-file`, there is a sentence ``Path names that do not start with `.` are treated as absolute paths.`` which is ambiguous to me.

* Is `../a` treated as an absolute path or not?  The path starts with the character `.` but not the directory `.`.
* Is `.file` treated as an absolute path or not?  The path starts with the character `.` but not the directory `.`.

**Comment by chriseth** [comment]
Actually the implementation has a bug there (it is in `CompilerStack::absolutePath`). I guess the following should be the correct behaviour:

Path elements are separated by `/`. If the first path element is `.` or `..`, it is a relative path, otherwise it is an absolute path.

Could you modify both the implementation and the documentation?

**Comment by pirapira** [comment]
OK.
