### ISSUE TITLE
Call external pure function from another pure function of the same contract using "this" causes an error

### ISSUE THREAD

**Issue by haoyang9804** [ethereum/solidity#15444]
## Description

Just as the title shows. I met this problem in trying out Solidity programs. Seems that I have to copy-paste function `f` into `f2` and change `f2`'s visibility into internal/public/private and remove `this.` to reuse already defined external pure functions. I don't know if it's a bug.
Below is the reproducible test case.
```solidity
contract A {

  function f() external pure {}

  function g() internal pure {
    this.f();
  }
}
```

The error message is as below. It warns me that `this` may read from the environment. But I found it's misleading. Putting aside the assumption that "this" might be read from the state, even if I change "pure" to "view", isn't it possible for "this" to modify the state?
```
Error: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
 --> test1.sol:6:5:
  |
6 |     this.f();
  |     ^^^^

```
Looking forward to your reply. Thanks:)

**Comment by Reedme-21** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@haoyang9804

**Comment by Philogy** [comment]
This is the intended behavior: https://docs.soliditylang.org/en/v0.8.25/contracts.html#pure-functions.

You're reading the `this` address, it can change based on a DELEGATECALL and may have different results in different contracts.

**Comment by haoyang9804** [comment]
I see. Thx

**Comment by cameel** [comment]
> You're reading the `this` address, it can change based on a DELEGATECALL and may have different results in different contracts.

Exactly. Just to make it clear, not all uses of `this` are disallowed in pure functions, just those that lead to the address being accessed. E.g. `this.f.selector` is fine, even though it uses `this`, since the value can be calculated at compilation time without the knowledge of the underlying address.

It may not always be easy to distinguish whether the expression will actually use the address in the end, so the compiler may be overeager to disallow this in some cases (see e.g. #11540 for a related case). Those would actually be bugs. This particular case is not, because it does require accessing the address. You can't make an external call without knowing it.

Also note that calling the same function internally (just `f()`) or calling it externally via a hard-coded address or one you pass in via a variable (`a.f()`, where `a` is of type `A`) is allowed.
