### ISSUE TITLE
Designing a smart contract for real world use case(s)

### ISSUE THREAD

**Issue by varunagarwal315** [ethereum/solidity#1546]
I would like to refer to [this][1] documentation of list of possible use-cases for smart contracts written by people part of the hyperledger team. I have deployed some basic smart contracts of my own on a testnet with basic permissioning as well and want to tackle a much more advance, real-world use case.

The problem statement is 

>    Jane is opening an account at MidBank in Finland. As part of that process, the bank asks her to provide two from a variety of possible sources to confirm her identity - a so called "Know Your Customer" check. She selects government-supplied verifiable claims that confirm she receives postal mail at a certain address and that she has a national ID card. Confirming these allows the bank to open her account and be confident in her identity when she conducts transactions.
    Now that the account is open, Jane is issued a digitally signed credential for her checking account at MidBank. This credential verifies that Jane has an account at MidBank and has access to her associated checking account. Since MidBank (and all banks in Finland) are required to perform "Know Your Customer" checks on accounts, this credential can also be used as sufficient verification by other financial institutions. This can help Jane assure destination banks that she is verified, thereby allaying concerns about misdirected transactions and money laundering.

I have one `people` contract which is called every time a new person like Jane is added to the system.
 Multiple identities can be used. Now if in the future, apart from Social Security number or address, say a mobile bill is accepted, then in that case it is better to have separate contracts for them and link it to each `people` contract as contracts cannot be upgraded. Each identity contract can either hold information for one unique person or can be used a registry and contain all data related to one document type (passport etc.) for each of the `people` contracts deployed.

I wanted to have an open discussion on how contracts such as these can be structured keeping in mind that the system should be upgradable, in the sense that, if a new government document is made acceptable, the system should be able to account for it without causing hindrance 

If the system has 100k people then keeping one `identity contract` to handle each document type and use it as a registry would be good, or deploying 100k + (100k * number of docs) be a more viable option as each person would then have his own `person contract` and separate contracts linked to it for each document type that he would upload.

Would love to hear community thoughts on this.
1]: https://opencreds.github.io/vc-use-cases/#finance

**Comment by chriseth** [comment]
Thanks, for your thoughts, @varunagarwal315! Identity verification is indeed an interesting problem. I fear that the whole system has to be much more complicated since in reality, trust should not be transitive and it has to be possible to revoke such verifications. I think the uport project already spent quite some thoughts on these matters. As far as software architecture is concerned, I guess that using a generic interface for "person" and "identity verification" and a registry contract that contains lists of "accepted" instances of these contracts would be a viable approach.

Unfortunately, I don't think that this is the right place to discuss such matters, since this is merely an issue tracker for bugs in a programming language. I would recommend making a posting to http://reddit.com/r/ethereum.

**Comment by 7flash** [comment]
The question is not about identity. 
The question is next.
What is the best way to structure a lot of contracts with a lot of information?
How to implement flyweight design pattern is solidity?

**Comment by karikalanCyberForza** [comment]
_;   this modifier purpose and use cases
