### ISSUE TITLE
What are the conditions for Solidity to clear the scratch space?

### ISSUE THREAD

**Issue by lum7na** [ethereum/solidity#15478]
Hi! I have some questions about the scratch space from memory `0x00` to `0x3f`. I noticed in the Solidity documentation that it mentions: 'Scratch space can be used between statements (i.e., within inline assembly).' Does this imply that the values in the scratch space are preserved within a single inline assembly block? If I break a block into several adjacent ones, could the values in the scratch space change between these blocks?

When I compile the following program using the solc 0.8.14 with `solc-0.8.14 --optimize --optimize-runs=99999999`, function `f` does not return `0x42`, which subsequently leads to incorrect execution results for function `g`.

```solidity
contract C {
  function f() public returns(uint256 x) {
    assembly  { mstore8(0, 0x42) }
    assembly { x := mload(0) }
  }


  function g() public returns(uint256) {
    if (f() != 0) {
      return 0;
    }
    uint a;
    assembly  {
      {
        a := call(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
      }
    }
    return a;
  }
}
```

**Comment by cameel** [comment]
> Does this imply that the values in the scratch space are preserved within a single inline assembly block?

Yes.

> If I break a block into several adjacent ones, could the values in the scratch space change between these blocks?

They probably won't, but we don't guarantee that, since technically the compiler is free to wrap the block in something or insert something in between. We only guarantee that we won't do this to code inside the assembly block itself.

> When I compile the following program using the `solc 0.8.14 with solc-0.8.14 --optimize --optimize-runs=99999999`, function `f` does not return `0x42`, which subsequently leads to incorrect execution results for function `g`.

I think you're just running into this compiler bug, that affected several compiler versions, including 0.8.14 in particular: [Optimizer Bug Regarding Memory Side Effects of Inline Assembly](https://soliditylang.org/blog/2022/06/15/inline-assembly-memory-side-effects-bug/). This won't happen on the latest version.
