### ISSUE TITLE
support switch-case statements

### ISSUE THREAD

**Issue by 3esmit** [ethereum/solidity#15504]
## Abstract

Switch case is important for code cleanness. It's a common feature in _all_ high level languages.

## Motivation

While I undestand there is some complex edge cases to deal with on EVM for this control structure been implemented, it should start as simple as possible. 

## Specification

First iteration:
- uint256
```solidity
enum MyEnum { A, B, C };
// (...)
MyEnum b = MyEnum.B;
switch(uint(b)){
     default:
         emit MyEvent();
     case uint(MyEnum.A):
         //(...)
         break;
     case uint(MyEnum.B):
        //(...)
        break;
}
``` 

Second iteration: 
- enum type;

Third iteration: 
- custom errors

Fouth iteration:
- complex structures

Whatever would cause a complexity or need more discussion to be porperly implemented should be left to a later iteration. In my example I used a `default:` without `break;`, if that would be difficult to solve, left it for a later iteration.

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mehtavishwa30** [comment]
Hey @3esmit! Thanks for taking the time to propose this.

I doubt that we will implement a C++-style switch-case as proposed but I believe we are planning to have something similar to the Rust-style `match` expression in the new Experimental Solidity in the future.

It would be best to close this and direct any further discussions around the design of similar features like `enums with data` under [this older issue about it](https://github.com/ethereum/solidity/issues/909) due to the relevance.
