### ISSUE TITLE
About function params question

### ISSUE THREAD

**Issue by banxiu** [ethereum/solidity#15677]
## Page

https://docs.soliditylang.org/en/v0.8.28/structure-of-a-contract.html

## Abstract

nothing wrong ，im just start learn about Solidity ，I see some teach video ，he write this case ：
contract FuncationOutputs {
    function returnMany() public pure returns (uint, bool) {
        return (1, true);
    }
    function destructAssigments() public pure  {
        ( ,bool b ) = returnMany();       
    }
}

he said if you want pay less gas you can write this   : ( ,bool b ) = returnMany();    
In remix dev tools  ，this is warning and it cant complied  ，i know  normal write is correct ：  (uint x ,bool b ) = returnMany();      
 i dont know what is wrong with this write :( ,bool b ) = returnMany();

**Comment by r0qs** [comment]
Hi @banxiu, this isn't the appropriate place for such questions. Please direct general Solidity-related questions and discussions to [our forum](https://forum.soliditylang.org/), our [Matrix community channel](https://matrix.to/#/#ethereum_solidity:gitter.im), or the [Ethereum Stack Exchange](https://ethereum.stackexchange.com).

Regarding the warning you see when using `( ,bool b) = returnMany();`: it occurs because `b` is not being used in the `destructAssigments()` function. For example, if you return `b` in that function, the warning will disappear. In any case, the contract actually compiles fine in Remix.
