### ISSUE TITLE
arrays missing from struct abis

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/solidity#1626]
The following contract creates a `things(uint256)` function. However the abi is missing the `values` output.

```
pragma solidity ^0.4.4;
contract structMap {
  struct Thing{
    address sender;
    uint256[] values;
  }

  mapping(uint256 => Thing) public things;
}
```

ABI:

```
[
   {
      "constant":true,
      "inputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"things",
      "outputs":[
         {
            "name":"sender",
            "type":"address"
         }
      ],
      "payable":false,
      "type":"function"
   }
]
```

**Comment by chriseth** [comment]
This is on purpose. The reason is the following:
Accessors for mappings or dynamic arrays (or complex objects composed from them) never return the full mapping or array. For a mapping this is obvious - there is no way to iterate over the mapping. For arrays, the output would be just too big. As there is no clear point where you could say that the output is too large, the decision was to always just return a single element from the mapping or array and require the key for that element to be a function argument. This works quite well for arrays and arrays of arrays but it is not really possibly to supply the argument for a struct that has an array as a member. The idea is that the virtual code for the accessor should always be of the form `return x[a][b][c]`, and if this results in a struct, the struct is turned into a tuple of all its elementary members. Non-elementary members are stripped from the tuple.

**Comment by aakilfernandes** [comment]
I follow you for mappings. But doesn't the "might be too big" problem exist for any function that returns a dynamic array?

ie

`function getNumbers() constant returns(uint256[])`

**Comment by chriseth** [comment]
Sure, but if you define a function you can either use
`function getNumbers() constant returns(uint256[])` or `function getSingleNumber(uint index) constant returns(uint256)`. With accessors you do not have a choice.
