### ISSUE TITLE
Compiler produces different bytecode based on the filesystem path to the source file.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#1644]
Given the same source file, the compiler outputs different bytecode and runtime bytecode values depending on the path used to reference the source file.

```javascript
pragma solidity ^0.4.0;

contract Test {
  function Test() {
  }
}
```

```bash
$ solc Test.sol --bin

======= Test.sol:Test =======
Binary:
60606040523415600b57fe5b5b5b5b603380601b6000396000f30060606040525bfe00a165627a7a72305820a5afe3725d432100f53c5ad31a395a817483211a2e09b3cc546b37c92a4c085d0029
$ solc ../tmp/Test.sol --bin

======= ../tmp/Test.sol:Test =======
Binary:
60606040523415600b57fe5b5b5b5b603380601b6000396000f30060606040525bfe00a165627a7a72305820cd38ccee989addea365d38d17c0fec4c0b44a78b003915f483df64fa21f34e9c0029
```

Why?

**Comment by axic** [comment]
The last section of the bytecode is the metadata hash in CBOR encoding. Since the metadata contains the name of the input file, the hash of it will differ. See this section for explanation: http://solidity.readthedocs.io/en/develop/miscellaneous.html?highlight=metadata

The part in the middle is the Swarm hash of the metadata:
`a165627a7a72305820 a5afe3725d432100f53c5ad31a395a817483211a2e09b3cc546b37c92a4c085d 0029`
`a165627a7a72305820 cd38ccee989addea365d38d17c0fec4c0b44a78b003915f483df64fa21f34e9c 0029`

This should also be fixed by JSON compiler interface, because there one will be able to define the source names.

**Comment by pipermerriam** [comment]
Thank you. This is what I was missing. I'm on mobile so unable to close
this myself until later when I'm back at me computer. Feel free to consider
this issue closed.

**Comment by axic** [comment]
I think this issue could stay here as a reminder to document this. (I mean the fact that the file path matters.)

**Comment by locklin** [comment]
FWIIW solc-g++, solc-clang and solc-emscripten also produce different bytecode as of 0.4.8 even with same path to source (compiling on Ubuntu 14.04/Mint-17). The issue seems to have disappeared in 0.4.10.
