### ISSUE TITLE
get range of bytes into fixed-size type

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#167]
Is there an idiomatic way to put the first 32 bytes of a `bytes` into a `bytes32`?

**Comment by chriseth** [comment]
There is no way yet. You can use this snippet:

```
contract c {
    function toBytes32(bytes data, uint index) returns (bytes32) {
        uint val;
        for (uint i = index; i < index + 32; i++)  {
            val *= 256;
            if (i < data.length)
                val |= uint8(data[i]);
        }
        return bytes32(val);
    }
}
```

**Comment by augustoteixeira** [comment]
Any news on this?

This would be very useful for the following rationale:
- accessing storage data is very expensive, while accessing contract code is very cheap;
- this gives a great gas advantage for the use of constants, because they live in the contract's code;
- value-type constants are not good for storing larger amounts of data;
- `bytes32[20] constant` is considered a `constant of non-value type`;
- pointers to data defined through `bytes constant table = hex"398ba..." are not accessible in assembly (`TypeError: Only direct number constants and references to such constants are supported by inline assembly.`);
- the solution of copying every byte through a loop reduces the gas gains obtained by avoiding storage.

Here are possible solutions:
- allow the code to get a range of bytes into fixed-size types, like this issue suggests;
- make `bytes32[20] constant`s possible, like `bytes constant`s currently are;
- make a pointer to a `bytes constant` accessible in assembly;

Is there a chance of any of this solutions be made available in the near future?

Is there another solution that I am not seeing?

**Comment by cameel** [comment]
If you mean the initial bytes like the original requester, this is now possible with a conversion. See #9170.

If you mean arbitrary slices, then not yet but it's on our roadmap and will be possible eventually. See #7423.
