### ISSUE TITLE
failed to inherit some members

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#173]
```
data/balance_db_test.sol:29:9: Error: Member "assertFalse" not found or not visible after argument-dependent lookup in contract DSBalanceDB_Test
        this.assertFalse(ok, "sub failed below zero");
```

`assertFalse` is a function on `Test`, of which `DSBalanceDB_Test` is an instance.

The crazy thing is that `assertTrue` is available, as are a seemingly random set of functions from `Test`. Why does it get confused about the type?

(I have to exclude the `this` to get a clearer error message, otherwise it tells me `assertFalse` is an just undeclared identifier)

**Comment by chriseth** [comment]
Thank you for reporting this issue. If possible, please check by in [gitter](http://gitter.im/ethereum/solidity) because it is much easier to find the cause of this problem there.

My first guesses without seeing the source code would be:
1. `assertFalse` is not publicly visible, and because of that, `this.assertFalse` cannot be found.
2. `assertFalse` is an overloaded function (declared multiple times with different argument types) and none of the argument types you give match one of the functions.

**Comment by nmushegian** [comment]
The error appears or dissappears based on whether I try to build this contract in my long list of files:

```
contract False {
    function() returns (bool) {
        return false;
    }
}
```

The error doesn't appear in files that seem to have anything to do with this. Very weird.

**Comment by chriseth** [comment]
Were you able to find out how to reliably reproduce this?

**Comment by chriseth** [comment]
Please reopen if the problem is reproducible.
