### ISSUE TITLE
Stack items differ for calldata parameters

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#1803]
```
contract C {
  function f(bytes calldata) external {
    assembly {
        let x := add(calldata, 32)
    }
  }
}
```

This fails with:
```
Untitled:4:22: Error: Expected instruction(s) to deposit 1 item(s) to the stack, but did deposit 2 item(s).
        let x := add(calldata, 32)
                     ^------^
Untitled:4:18: Error: Expected instruction(s) to deposit 1 item(s) to the stack, but did deposit 2 item(s).
        let x := add(calldata, 32)
                 ^---------------^
```

Making the function non-external fixes it. I guess in external it defaults to calldata. What are the stack items in that case?

We should document it in the *Assembly* section.

**Comment by axic** [comment]
It seems the top item is the len in the calldata, and the next item is the offset:

```
contract C {
  function f(bytes calldata) external returns (string ret) {
      uint offset;
      uint len;
      assembly {
          calldata
          =: len
          =: offset
      }
      ret = new string(len);
      assembly {
          calldatacopy(add(ret, 32), offset, len)
      }
  }
}
```

**Comment by chriseth** [comment]
Yes, this should be documented in the inline assembly section.

**Comment by axic** [comment]
Since recent changes, the above code cannot be compiled.

Cannot reference directly:
```
1803.sol:4:22: Error: Only types that use one stack slot are supported.
        let x := add(calldata, 32)
                     ^------^
```

Cannot reference using `_offset`:
```
1803.sol:4:22: Error: The suffixes _offset and _slot can only be used on storage variables.
        let x := add(calldata_offset, 32)
                     ^-------------^
```

@chriseth what is the new proposed way to access that?

**Comment by chriseth** [comment]
I guess we have to go a similar route as we went with storage variables, but perhaps we should reconsider if calldata variables actually make sense, they have again a different encoding than memory variables and I'm not sure we can support that.

**Comment by haltman-at** [comment]
I was going to open an issue suggesting you do something similar as with storage variables, but then I found this issue, so I'll just comment here.  I have two additional comments regarding this:

1. In addition to doing this with calldata variables that take up two stack slots, you could also do this with variables of `function external`, too.  Currently you can't use those in assembly either.

2. I'd like to make a comment here about the error messages; I think the current error messages regarding this are confusing/inconsistent:

A. If you attempt to use a `function external` variable, you just get a generic error message regarding variables that take up two stack slots being disallowed in assembly.

B. ...but if you use a calldata variable that takes up two stack slots, you get a specific error message saying you can't use calldata variables in assembly...

C. ...except this error message actually isn't correct, because if you use a calldata variable that only takes up a single stack slot, it works perfectly fine.

My suggestion:

1. Add ways to use two-stack-slot variables in assembly, similar to how storage variables are treated.  For external functions, you can have `f_address` and `f_selector` (although maybe it should have a different name to warn people that these selectors are left-padded, instead of right-padded like usual?).  For calldata variables, you can have `x_start` and `x_length`.  Or maybe the names would be different, these are just suggestions.

2. Add specific error messages warning people to use these, like you have for storage variables.  Like, if you attempt to use an external function variable `f` directly, it should tell you to use `f_address` and `f_selector` instead, and if you attempt to use a two-slot calldata variable `x` directly, it should tell you to use `x_start` and `x_length` instead.

Btw, this is getting a bit tangential, but has there been any thought given to changing the `_slot` and `_offset` syntax in 0.6.0?  It bothers me that (while unlikely) this could notionally overlap with the name of a local variable.  (If I try out this situation -- having both a state variable named `x` and a local variable named `x_offset` -- then when I attempt to use `x_offset` in assembly, the compiler complains that it can't find that identifier.)  Perhaps it could be `x.offset` instead?  That could still collide with the name of an *assembly* local variable, but that's OK, because the compiler could just recognize that, hey, the name `x.offset` is already in use and not let you declare such an assembly-local variable.  As long as it could no longer collide with an external local variable I think it's fine.  Similarly with these other suggestions I'm making, obviously.

You could even perhaps add specific error messages for if someone attempts to use one of these inappropriately.  Like if someone attempts to use `x_start` or `x_length` for a single-slot calldata variable, you could have an error message saying, hey, this one's just one slot, just use `x` instead.  Maybe that's just unnecessary though; presumably if someone is doing assembly with calldata variables, they already know how they work, and the generic error message will suffice to make them realize, oh, duh, I should just use `x` instead.

**Comment by axic** [comment]
Is this still an open issue? cc @chriseth @ekpyron

**Comment by ekpyron** [comment]
Well, it's at least better errors now... do we have another issue for accessing external function types and dynamic calldata types from inline assembly? That part is still unsolved, so we can re-purpose this issue for that.

**Comment by axic** [comment]
Yep, the message is nicer:
```
Error: Call data elements cannot be accessed directly. Copy to a local variable first or use "calldataload" or "calldatacopy" with manually determined offsets and sizes.
 --> 1803.sol:4:22:
  |
4 |         let x := add(calldata1, 32)
  |                      ^^^^^^^^^
```

I would suggest to close this and create a new issue.
