### ISSUE TITLE
Inconsistent behaviour between references to members of string arrays vs. other

### ISSUE THREAD

**Issue by maurelian** [ethereum/solidity#1812]
I am getting very different behaviour with string values depending on whether or not I name the `returns` value in the function declaration. 

    contract PopArray {
        string[] public string_arr;
        
        function PopArray() {
            // fill the array with some data
            string_arr = ['zero', 'one', 'two', 'three', 'four'];
        }
    
        // Calling this once returns 'four', calling it a second time returns 'three', etc. 
        function pop_string () returns (string member) {
            member = string_arr[string_arr.length-1]; //get the last value
            string_arr.length = string_arr.length-1;  // reduce the length of the array
            return member;
        } 
    
        // Calling this returns nothing, but does reduce the length of the array.
        function broken_pop_string () returns (string) {
            string member = string_arr[string_arr.length-1];
            string_arr.length = string_arr.length-1;
            return member;
        }
    }
    

Here is how the results look in remix when I call one function, then the other : [![remix results][1]][1]. 

By adding event logs, I can see that the reference is deleted by this line: `string_arr.length = string_arr.length-1;`. I also was able to address the issue by using `string memory member = ...` when the variable is not named in the declaration.

That seems like reasonable behaviour, however when I tried this out with other array types, a value is returned regardless of whether or not the return value is named in the function declaration, or the `memory` keyword is used. 

[Here is some code][2] testing it out with `uint` and `bytes32` values.

Is there a subtlety regarding strings that I'm missing here? I could not find documentation describing it. 

  [1]: https://i.stack.imgur.com/qvvBT.png
  [2]: https://gist.github.com/maurelian/2a8ff9b1f7e3d8c69374f751af960633

**Comment by chriseth** [comment]
This indeed is subtle behaviour and has its roots in the way Solidity was created in increments.

Local variables of reference types are storage references by default. If you use `string member` you are declaring a storage reference instead of a memory variable. This means `member = string_arr[string_arr.length-1];` assigns a reference to the last element of the array in storage. If you then reduce the length of the array, this element is deleted and you return the empty string.

Function arguments and return values, in contrast, are memory references by default, so by `member = string_arr[string_arr.length-1];` in `pop_string` you are requesting a copy from storage to memory.

**Comment by chriseth** [comment]
Just created this issue to at least slightly improve the situation: https://github.com/ethereum/solidity/issues/1815

**Comment by maurelian** [comment]
Thanks for your response @chriseth. Your explanation is enlightening, it makes sense that a storage reference would be returned empty if what it references is deleted. 

However its still unclear to me, or even moreso now, why the behaviour isn't similar with other types. This [example code](https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.10+commit.f0d539ae.js&gist=16bdce8dae1743e96879c544dd3ee7f8) implements exactly the same `broken_pop_string` function, two more times but with `uint` and `bytes32`. As far as I can tell they are identical, including the declaration of `member` in the body of the function. However, when the array item they reference is deleted, the variable still holds the original value. 

What is different about a local variable that references an item in a `string[]` array? I can't find anything about it in the docs.

**Comment by chriseth** [comment]
@maurelian `string` is a reference type (mainly because it has variable length) while `uint` and `bytes32` are value types (they fit inside 256 bits). Value types are always copied and never referenced while reference types are always referenced and only copied if an assignment changes the data location (i.e. from storage to memory or memory to storage).

**Comment by maurelian** [comment]
Thanks for clarifying @chriseth.
