### ISSUE TITLE
namespace of function and event 

### ISSUE THREAD

**Issue by pureland** [ethereum/solidity#2099]
there are many functions/events if develop a programs consist of several contracts ，difference  function /event name is very important to update contract or other using.
so if use namespace smiler C++, but contract name as the default namespace of a contract, and replace "function name and Args" with "contract name" +"function name and Args" when calculate function Sig

**Comment by chriseth** [comment]
Solidity did not take the approach of namespaces but rather of modules. This avoids the problem of having to come up with globally unique names, or at least moves this problem to the package manager.

If I understand you correctly, you suggest to add the name of a contract to the function signature to avoid naming conflicts. Note that functions in different contracts cannot really conflict, because each function call in Ethereum is always directed to a contract.

**Comment by axic** [comment]
@pureland please reopen and expand if the answer isn't satisfactory

**Comment by wighawag** [comment]
Note that there is now an ERC to discuss the potential benefit of namespacing function for use in the same contract : https://github.com/ethereum/EIPs/issues/1407
