### ISSUE TITLE
Remove Why3 translator

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2195]
The Why3 output is not maintained and there doesn't seem to be a plan for maintaining it. Would it make sense removing it?

**Comment by axic** [comment]
@chriseth @pirapira any thoughts?

**Comment by pirapira** [comment]
We should go ahead and remove it.  Otherwise people will try it out and find it not working.  I'm not going to do anything about the Why3 interface.

Instead, I'm going to
1. use [Rosetta](https://emina.github.io/rosette/) on the VM/Julia level and check for `0xfe`s.
2. use Lem/ML to build executable specification of Solidity

**Comment by roadriverrail** [comment]
Yes, back when I wrote the do/while loop, I think I saw that Why3 didn't
exactly support one, and I thought perhaps Why3 wasn't going to fit.

**Comment by chriseth** [comment]
I agree, we should build the verification from bottom to top. Rosetta looks nice and implementing an interpreter for julia in it is certainly doable!

**Comment by axic** [comment]
So then we should remove it form JSON I/O right now before the release.

**Comment by chriseth** [comment]
@axic just make it optional in the spec

**Comment by chriseth** [comment]
or just remove it from the spec
