### ISSUE TITLE
Encoding of preconditions for non-payable functions

### ISSUE THREAD

**Issue by wuestholz** [ethereum/solidity#2293]
According to the documentation (https://github.com/ethereum/solidity/blob/develop/docs/control-structures.rst), the compiler introduces an `invalid` instruction for the following two scenarios:
- "If your contract receives Ether via a public function without payable modifier (including the constructor and the fallback function)."
- "If your contract receives Ether via a public getter function."

Given that in such cases the callee can't really prevent callers from passing Ether, I am tempted to say that the compiler should instead introduce a `revert` instruction. In some sense, this is a kind of implicit parameter validation or precondition that is automatically inserted by the compiler.

@chriseth @pirapira @retotrinkler What do you think?

**Comment by pirapira** [comment]
These are clearly cases for `revert`.

**Comment by axic** [comment]
We've realised that it still uses `invalid` in this thread: https://github.com/ethereum/solidity/pull/2194#discussion_r113966169

I think I agree with your reasoning and it complies with the statement "if the invalid opcode can be reached, the contract has a bug".

Though I must mention that either we consider both the above and "unknown function selector" (i.e. no supported signature and no fallback present - see #2241) as a case for `revert` or none of them, because all these are described in the ABI.

**Comment by wuestholz** [comment]
@pirapira @axic Great! Thank you for confirming my assessment so quickly!

@axic I also agree with the changes in the pull request you are referring to. I would encode all of these scenarios using `revert`.

**Comment by wuestholz** [comment]
@pirapira @axic Please let me know if you need any help with implementing both of these changes. I think it would be great if they could make it into the next release.

**Comment by pirapira** [comment]
This is in my list, but usually this kind of thing stays for a few weeks before I start it.

**Comment by pirapira** [comment]
Now I can start it!

**Comment by pirapira** [comment]
But I think @chriseth has done this.
