### ISSUE TITLE
Think about giving Inline assembly as parsed AST in AST output

### ISSUE THREAD

**Issue by federicobond** [ethereum/solidity#2419]
Does it make more sense to represent the operations as a list of parsed assembly items?

**Comment by chriseth** [comment]
It might, but the assembly grammar is much simpler, so we went this way.

**Comment by ekpyron** [comment]
This might be the cleanest solution to the recent issues in https://github.com/ethereum/solidity/pull/7153#issuecomment-530986932
Since we currently use a pretty printed version of the original inline assembly it's impossible to reconstruct the original source locations of all yul AST nodes during re-import.

The least hacky solution to that problem is probably outputing the yul AST as JSON tree instead of as just a string of operations.

**Comment by djudjuu** [comment]
> is probably outputing the yul AST as JSON tree instead of as just a string of operations.

just to be sure i got this correctly: inlineAssembly is a subset of yul. (Or at least it is parsed by the yul::Parser). 

So in broad strokes my idea to approach this would be: 
- 1) define helper functions(or a class?) ```Json::Value AsmConverter::toJson(yul::Literal/Identifier/...)```
- 2) in ASTJsonConverter::visit(InlineAssembly): do 
```["operations"] = AsmJsonConverter::toJson( _node.operations())``` (instead of Printedstring)
  - (AST::InlineAssembly's member m_operations is a yul::Block with the AST in it)

- Questions:
      - this is not using the accept/visit/endvisit-scheme. As I understand this was mostly to be able to do stuff like annotations. But all "Asm-nodes" are structs (see AsmData.h) which should be straightforward to (recreate) and which are not annotated.

**Comment by ekpyron** [comment]
It probably makes sense to coordinate this with https://github.com/ethereum/solidity/pull/7386 (which will change the dialect for inline assembly to "proper yul")

**Comment by djudjuu** [comment]
## Problem:

I need to process a *yul::Block*, which is a vector of *Statement*., which is a boost::variant() for manyt hings(yul::Expression, yul::Instruction, yul::Label,....>

So as i understand I can deduce the type of the statement using boost.variant's ```.which```,
but I still don't know how to access the values within that struct.

E.g. if I know that a statement is of type *Instruction*, I still can't call 
statement.instruction. ("no member instruction in boost::variant<Expression, Label,...>).

Can i cast it somehow? 

So, (as I think I can not cast) the solution to get something out of the
boost::variant is to write a dedicated *visitor*, as is done for the location in AsmData.h::lines 86-97

So my idea would be to write one visitor (similar as locationOf) per type of struct in the variant.

#### example, for "VariableDeclaration" 

it is defined like this:
```struct VariableDeclaration { langutil::SourceLocation location; TypedNameList variables; std::unique_ptr<Expression> value; };```

therefore the function (two actually) would be:

```
template <class T> inline std::pair<TypedNameList, Expression> getVariableDeclarationInfo(T const& node) {
   return boost::applyVisitor(VariableDeclarationExtractor(), node) 
}

struct VariableDeclarationExtractor: boost::static_visitor<std::pair<TypedNameList, Expression>{
   {
   template <class T> std::pair<TypedNameList, Expression> operator()(T const& node) const {
        return make_pair(node.variables, node.values)
   }
}
```

This seems like a lot of work. Can you point me to a smarter way to do that?

**Comment by chriseth** [comment]
The question is resolved, right? You just use `boost::apply_visitor`.

**Comment by djudjuu** [comment]
Yes. I am confident, that this will solve it.

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/7537
