### ISSUE TITLE
More explicit when accessing state variables

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#2577]
Especially when writing to state variables, it seems safer to be more explicit.

A "loose" way is to "enforce" some coding convention on state variables.  Another consideration is to make the use of `this` mandatory.  Other ideas welcome too.

**Comment by axic** [comment]
Is this still an issue if #973 is implemented?

**Comment by ethers** [comment]
Yes, I think so.  Contract code is also for anyone reading it and trying to follow it.  (The more people that can read contracts and minimize the cognitive load, the higher the possibility that today's events will be more discoverable/preventable.)

**Comment by chriseth** [comment]
The problem with requiring `this` for state variables is that `this` refers to the external interface, where state variables are changed to their getter functions. We could of course twist that since `this` has a special meaning and you could get the external interface using `ContractType(this)`. I don't think anyone is actively using `this.a` for anything else than passing callbacks.

**Comment by ethers** [comment]
If `this.a` is a good way to achieve the goal of explicitness when accessing state variables, then yes I do think that requiring `ContractType(this)` to access the external interface is a beneficial "tradeoff".

**Comment by federicobond** [comment]
The alternative here is an explicit assignment operator: <- or :=

We could issue a warning and then slowly deprecate = assignments to state variables if this moves forward.
