### ISSUE TITLE
Can't overload function by changing only return types

### ISSUE THREAD

**Issue by nmushegian** [ethereum/solidity#259]
`function stuff() returns (uint) {}`

`function stuff() returns (uint, bool) {}`

These have distinct signatures, but the compiler won't let me create both versions

**Comment by chriseth** [comment]
This is on purpose. For overload resolution, only the parameter types are taken into account, as is customary in many other languages. The reason is that you can easily omit the return values (or their types), but not the parameters. In both of the following examples, resolution is ambiguous.

```
stuff();
var x = stuff();
```

The main problem, though, is that resolution does not need to terminate after one step and can create ambiguities even if you use the return values:

```
function stuff() returns (uint) {}
function stuff() returns (bool) {}
function g(uint) returns (bool) {}
function g(bool) returns (bool) {}
function h() {
bool x = g(stuff());
}
```

**Comment by nmushegian** [comment]
Darn. I feel like this is an extension that will inevitably be required, to fit a contract into two different systems that expect different APIs.

I'm sure you could annotate a function in a way that will force expressions to never have an ambiguous type but it sounds like solidity 2.0 feature

**Comment by axic** [comment]
> These have distinct signatures, but the compiler won't let me create both versions

@nmushegian they are not part of the signature
