### ISSUE TITLE
Replace public with getter on state variables

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2595]
Replace the `public` keyword with `getter` on state variables to make the intent clearer.

Comments welcome whether this keyword is better or worse (or suggestions for better alternatives).

**Comment by o0ragman0o** [comment]
I don't think `getter` would be descriptive of an external call to a public function which initiates a TX.

**Comment by axic** [comment]
I don't fully follow what "external call to a public function which initiates a TX" means?

Note, the "public" keyword is very misleading on functions too as it has a slightly different meaning to what "external" means and the ABI contains only methods which are available externally.

**Comment by o0ragman0o** [comment]
`public constant` are the getters but not `public` on it's own.

**Comment by axic** [comment]
I am not entirely following, but no matter if it is `public constant` or `public`, only a getter will ever be generated.  The only difference is that a variable marked `constant` cannot be assigned to from within the code.

**Comment by o0ragman0o** [comment]
`public` on its own indicates state might change which is contrary to the concept of a getter.

**Comment by axic** [comment]
Sorry, I still do not get what you are saying. Do you mean that a getter indicates that its value will never change?

**Comment by o0ragman0o** [comment]
So I guess I'm expressing the confusion you're trying to address, so I'll try unpack that....(Remininding myself that you're talking specifically of `public` state variables and not `public` functions)

Solidity, being an OOL using `public` in similar way to say C++ but,
`public` in C++ allows a class member to be viewed and changed externally from the instance.
`public` for a Solidity variable only exposes a `public constant` function getter but no setter.
`public` for a Solidity function generates an ABI, may mutate state unless `constant` is also used.

`uint public foo;` produces the equivalent abstract `function foo() public constant returns(uint);`
`uint public constant foo;` produces the same abstract function.
Thinking of both a `public` and `public constant` variables in terms of `public constant` function which is different to a `public` function is definitely a point of confusion.

The other issue ([#2633](https://github.com/ethereum/solidity/issues/2633)) is that the equivalent abstract getter of a `public` variable is not recognised as implemented when that variable is declared in the deriving contract. So in order to have a consistent interface, the variable must be declared as private under a different name with an explicit getter function to implement the abstract interface.  This defeats the whole purpose of using `public` as a getter shortcut.  

So, that said (sorry for the all confusion), yes I agree `getter` would be a more suitable keyword for exposing variables through the ABI.  The declaration must also be recognised as the implementation of the getter functions abstract which may be declared in an interface.

**Comment by axic** [comment]
In the past three years a lot has changed in the language, so the discussion above is slightly out of date:
- `constant` of function definitions is replaced with state-mutability (view/pure/...)
- `constant` of variables means constants (set at compile time) and `immutable` was introduced for set-once (during deployment) variables
- interfaces can not contain variables anymore, just functions describing what the interface does
- interfaces can't have `public` specifier anymore, just `external`
- "getters" can implement such interface functions, if their generated signature matches (e.g. `uint public a;` is valid to implement `function a() external view returns (uint);`) -- this is a tad bit confusing

Additionally people have expressed more confusion about `public` in general.

Given all the above, I think it makes even more sense to consider this change.

**Comment by chriseth** [comment]
I just really don't like the word `getter`. Another option (maybe foolish) would be to allow `view` to serve the purpose of `getter`.

**Comment by cameel** [comment]
I also don't like the word `getter` that much but I think there's some merit to it over `public`. I find that many beginners do not realize that (1) `public` does not make the variable writable from the outside (2) you do not have to provide your own getter when you have it.
