### ISSUE TITLE
Suggest using the ~ modifier in the version pragma

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#2614]
- [ ] examples
- [ ] style guide

**Comment by veox** [comment]
From: https://github.com/ethereum/solidity/issues/2608#issuecomment-316868140

**Comment by chriseth** [comment]
Can you explain the benefit of `~` over `^`? They behave identical in the examples given in the linked comment.

**Comment by axic** [comment]
I think I've confused the two, we should be fine.

After major 0 it will be different though:
```
~1.2.3 := >=1.2.3-0 <1.3.0-0 “Reasonably close to 1.2.3”.
^1.2.3 := >=1.2.3-0 <2.0.0-0 “Compatible with 1.2.3”.
```

**Comment by chriseth** [comment]
So can this be closed?

**Comment by veox** [comment]
@chriseth Guess so.

Must say, I, too, have misunderstood the difference between tilde and caret ranges (for ref in `npm`'s doc: [`~`](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1) and [`^`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)).

For extra safety in the future (after `v1.0.0`), it _might_ be prudent to recommend (in [the docs](https://solidity.readthedocs.io/en/develop/layout-of-source-files.html#version-pragma)) `~M.m.p` (that is, tilde and _all three_ of major-minor-patch), in the off-chance that a backward-incompatible change makes it into a "minor" update by accident. People who don't think this can happen can use `~M.m` instead.

That said, _if_ this recommendation change would be made prior to `v1.0.0`, it should be safe to start recommending now, since `~0.5.0` and `^0.5.0` result in the same range: `>=0.5.0 <0.6.0` (according to `npm`'s docs - haven't looked at `solc`'s code at all on this one).
