### ISSUE TITLE
Normalize paths before using them for lookup key in Standard JSON

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#2738]
Discovered while troubleshooting #2665.

At the moment, global file names aren't normalized before using them as a lookup key when using standard-json.  This includes relative paths vs absolute paths and windows separator vs linux separator.  I recommend normalizing the keys to absolute path, unix separator (since that works on Windows) before using it as a lookup key rather than using the key as-is.  The current behavior can lead to a lot of wasted engineering time debugging as various layers of tooling may use different pathing techniques and the end-user likely expects the lookup to be normalized.

**Comment by chriseth** [comment]
I think we should not silently normalize the paths. Instead we should not allow `.` or `..` as part of a filename in standard-json. In standard-json, the file paths are the identifiers used everywhere else and should not be silently changed.

**Comment by MicahZoltu** [comment]
This wouldn't resolve the problem I ran into 3.5 years ago.  😄  IIRC, the issue I was having is that I had a pretty complex suite of tools and they were all spitting out different outputs.  To resolve this, the keys need to be the same no matter what OS you are building on.

That being said, I do support the rule that all paths must be relative to some common root (no `./` or `../`).  This could be a compiler option, where you tell it "the source root is `../source` relative to this `compiler-input.json`" or one could just assert that the source root is whatever folder `compiler-input.json` is in.  I'm not a fan of the second as it forces a particular directory structure.  Also, keep in mind that when people are fetching contracts via NPM, they may end up in a different directory structure from local contracts.

Removing the ability to use `./` or `../` should probably be a separate issue though.

**Comment by chriseth** [comment]
This sounds a lot like the `--base-path` option we already have.

**Comment by MicahZoltu** [comment]
In that case just remove support for `./` and `../`.  😀  Again though, separate from this issue.  😉

**Comment by cameel** [comment]
@chriseth 
> I think we should not silently normalize the paths. Instead we should not allow `.` or `..` as part of a filename in standard-json. In standard-json, the file paths are the identifiers used everywhere else and should not be silently changed.

I think we should go a bit beyond that and require stricter normalization:
- Path should not contain sequences of multiple slashes.
- Trailing slashes should not be allowed (at least in places where we require file names rather than directory names).
- `file://` prefix should not be present.
- Relative paths (i.e. something like `a/b/c.sol`) should not be allowed when an absolute `--base-path` is used because in that case no import can match them.

Also, we should either do some basic normalization on imports or enforce that they are already normalized according to the rules above. Currently we have too many cases where paths in imports resolve to the same file on disk but the compiler sees them as different files. This can result in cryptic errors. Or even worse, they can be different files in Standard JSON which is not possible in the filesystem. We already normalize import paths that start with `./` and `../` anyway.

**Comment by cameel** [comment]
@MicahZoltu
> In that case just remove support for `./` and `../`.  😀  Again though, separate from this issue.  😉 

Why though? I mean, to me initially it was not at all obvious that `x.sol` is relative to current working directory while `./x.sol` is relative to the directory containing the file but I think the functionality itself is useful. Maybe notation could just be more explicit, e.g. `import "{PARENT}/x.sol";` or `relative import "x.sol";` but still, when I see a relative path in a source file, the natural assumption for me is that it's relative to the location of the file, not some unknown directory someone will be running the compiler from.

Personally, I think that the base path could even be completely replaced with path remapping. Instead of allowing paths like `x.sol`, which is ambiguous, we could require specifying a named root like `@root/x.sol` (or maybe even unnamed like `@/x.sol`). I've seen that notation used for libraries in some contracts using Truffle (e.g. `@openzeppelin/x/y/z.sol`) - I think Truffle does use remappings under the hood for this? We could make that a part of the language and only allow paths that are either absolute or relative to the current file or relative to a named/unnamed root (which has to be remapped to an actual path on the command-line or in JSON).

**Comment by cameel** [comment]
> I think we should not silently normalize the paths. Instead we should not allow `.` or `..` as part of a filename in standard-json. In standard-json, the file paths are the identifiers used everywhere else and should not be silently changed.

Looks like we already have an issue for that: #5146.
