### ISSUE TITLE
Limit number of errors reported to something smallish (100).

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#2876]
Sometimes a small typo results in pages and pages of errors in Solidity compiler output.  The compiler should limit the number of errors shown to a smallish number (maybe 100), as additional errors after that are not useful and end up blowing stderr scroll buffer making it so relevant information may no longer be available.

**Comment by axic** [comment]
Do you have an example please?

**Comment by MicahZoltu** [comment]
Next time it happens I'll make a note of what triggered it and update this issue (I don't have a repro case handy, just happens once every couple days as normal course of operation).

**Comment by chriseth** [comment]
What is the downside of using `solc | head` or `solc | less`? Especially when considering an integrated compiler, it is not always clear which error messages are fine to remove. Think of an IDE showing errors in source files and you are mainly interested in errors in the current source file, but due to some reason, there are tons of errors in other source files and the errors in the current file are cropped.

**Comment by MicahZoltu** [comment]
Every IDE I know of also limits the number of errors.  When errors are limited, the first errors are retained as they are more likely to be the problematic ones.  The problem with `solc | less` is actually the exact thing you described, I am using `solc` by way of `py-solc` at the moment, and when running my tests each test ends up with a _ton_ of error spam.  If I did `pytest | less` I would miss out on the footer of the test details which sometimes includes useful aggregate information.  Also, the sheer volume of data spammed out by solc is so much that it actually takes my tests a _significant_ amount of time to fail because each test is throwing so much data to stderr/stdout.

Of course, py-solc could also do better about dealing with this situation, but it feels to me like `solc` is a more generalized place to handle this since in the _vast_ majority of cases seeing anything after the first 100 (or even 1000) errors is _very_ unlikely to be useful.

As a point of reference, GCC has `-fmax-errors=n` to deal with this, though I'm not sure if there is a default setting or not.

**Comment by axic** [comment]
I'd still be eager to see an actual example as it feels unlikely that 1000 errors would be shown during regular usage, perhaps there is a bug somewhere.

**Comment by MicahZoltu** [comment]
Will do once it happens again.  :)

**Comment by chriseth** [comment]
I'll try to see if we can limit the number of errors per file.

**Comment by chriseth** [comment]
Hm, this could actually be quite easy to implement inside the ErrorReporter class, which could check that the number of errors per file (including the "non-file") is at most 100, treating warnings and errors differently, so that it cannot happen that there is an error, but the compiler only reports warnings.

**Comment by chriseth** [comment]
@axic noted that the problem is not about the number of errors but mostly about the source snippets for extremely long lines. That's perhaps where we should start.
