### ISSUE TITLE
address.call(bytesVar) results in corrupted data in the call

### ISSUE THREAD

**Issue by lastperson** [ethereum/solidity#2884]
If the `bytesVar` is a `bytes` param from a function call, then passing it to `address.call` will result in the input being zero padded to 32*n bytes.

Which version of Solidity you are using: 0.4.16 (reproducible on 0.3.5 too)
What was the source code (if applicable):
```
pragma solidity 0.4.16;
contract Caller {
    Caller2 receiver;
    function Caller(Caller2 _rec) {
        receiver = _rec;
    }
    function forward() {
        receiver.forward(msg.data);
    }
}
contract Caller2 {
    event Debug(uint, bytes);
    address receiver;
    function Caller2(address _rec) {
        receiver = _rec;
    }
    function forward(bytes _data) {
        Debug(_data.length, _data);
        receiver.call(_data);
    }
}
contract Receiever {
    event DebugReceive(uint, bytes);
    function () {
        DebugReceive(msg.data.length, msg.data);
    }
}
```
Which platform are you running on: Remix IDE
How to reproduce the issue(abstract code):
```
var receiver = new Receiver();
var caller2 = new Caller2(receiver.address);
var caller = new Caller(caller2.address);
caller.forward();
```
What was the result of the issue(events emitted):
```
Debug(4, '0xd264e05e')
DebugReceived(32, '0xd264e05e00000000000000000000000000000000000000000000000000000000')
```
What the expected behavior is:
```
Debug(4, '0xd264e05e')
DebugReceived(4, '0xd264e05e')
```
Example in mainnet https://etherscan.io/tx/0x994098c4d8166baa361729b48470b44e700bf4ccfb214ebc81cf872dc3d64d15 (check Parity trace)

Contract that cannot receive calls from multisigs due to this bug:
https://etherscan.io/address/0x1776e1f26f98b1a5df9cd347953a26dd3cb46671#code

Code that fails to process corrupted calls:
```
    // mitigate short address attack
    modifier onlyPayloadSize(uint numWords) {
        assert(msg.data.length == numWords * 32 + 4);
        _;
    }
```

**Comment by lastperson** [comment]
Examining the documentation on ABI encoding, I see that this is by design. The question then (I fail to find answer in the documentation) is why it is by design? I see the point for fixed size types, but if in order to find the end of a dynamic type we need to examine it's length anyway, then why do the right padding to a multiple of 32?

**Comment by chriseth** [comment]
I'm sorry, but I still do not understand everything. The fact that `a.call(x)` pads to multiples of 32 bytes indeed sounds like a bug.

Your statement "in order to find the end of a dynamic type we need to examine it's length" should not be correct, the ABI is designed to ignore the length of the input - that's also why it is not checked by solidity functions.

Could you please describe the observed and the expected encoded data?

**Comment by lastperson** [comment]
Yep, I also thing that `a.call(x)` padding thing is a bug. As per encoding, here is what I think is reasonable, tough probably hardly implementable to maintain backwards compatibility:

Assuming you have a function `function encoding(bytes _a, bytes _b)`, calling it like `encoding('0x11111111', '0x222222222222')` will result in the following input:
```
0x540e773b
0000000000000000000000000000000000000000000000000000000000000040
0000000000000000000000000000000000000000000000000000000000000080
0000000000000000000000000000000000000000000000000000000000000004
1111111100000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000006
2222222222220000000000000000000000000000000000000000000000000000
```
While I see no reason(probably I just didn't think too much about it) why it cannot be:
```
0x540e773b
0000000000000000000000000000000000000000000000000000000000000040
0000000000000000000000000000000000000000000000000000000000000064
0000000000000000000000000000000000000000000000000000000000000004
1111111100000000000000000000000000000000000000000000000000000000
00000006222222222222
```

Anyways, can we deal with `a.call(x)` thing? :)

**Comment by chriseth** [comment]
You mentioned the ABI :-)

`a.call(x)` does not do any ABI encoding.

**Comment by chriseth** [comment]
Ok, I had a look at the code again and we actually need padding for `a.call()`, otherwise `a.call(1,2,3)` would not work as expected.

The thing is: `a.call()` is an ancient beast that should not be used. I would recommend using inline assembly for such tasks, since it provides the same security guarantees but does not do any invisible magic.

**Comment by lastperson** [comment]
Example with `function encoding()` is about ABI encoding, how it is working right now, and how it might work. Not related to `a.call(x)`.

> we actually need padding for a.call(), otherwise a.call(1,2,3) would not work as expected.

Can't there be an exception to the case when a single bytes type parameter passed in? Why it works differently when we pass `msg.data` there?

```
pragma solidity 0.4.16;
contract Caller {
    address receiver; 
    function Caller(address _rec) {
        receiver = _rec;
    } 
    function forward() {
        receiver.call(msg.data); // not padded, DebugReceived(4, '0xd264e05e')
        bytes memory b = bytes(msg.data);
        receiver.call(b); // padded, DebugReceived(32, '0xd264e05e00000000000000000000000000000000000000000000000000000000')
    }
}
contract Receiver {
    event DebugReceive(uint, bytes);
    function () {
        DebugReceive(msg.data.length, msg.data);
    }
}
```

**Comment by chriseth** [comment]
Ah, that's interesting! You might want to try changing `forward` to be `external`. But in general: `call` has many weird quirks and I would much rather just remove it from the language than fix all these quirks.

**Comment by AlexeyAkhunov** [comment]
The fix for this seems to be addition to this line: https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.h#L1022

The original line 

`bool padArguments() const { return !(m_kind == Kind::SHA3 || m_kind == Kind::SHA256 || m_kind == Kind::RIPEMD160); }`

should be extended to (and to include BareDelegateCall and BareCallCode, though I did not test them):

`bool padArguments() const { return !(m_kind == Kind::SHA3 || m_kind == Kind::SHA256 || m_kind == Kind::RIPEMD160
		|| m_kind == Kind::BareCall); }`

I have tested the addition using Gnosis Multisig and **transfer** call with **onlyPayloadSize** modifier.

Unfortunately, I don't see how to embed this test into solidity repository, because it relies on **go-ethereum** and its abigen tool.

**Comment by axic** [comment]
@chriseth is this still outstanding?

**Comment by chriseth** [comment]
@axic I think so.

My proposal would be to change call to not do packed encoding anymore, but only accept a single `bytes` parameter and not do any padding. Maybe support a single parameterless overload.

**Comment by axic** [comment]
@chriseth I think we implemented everything here?

**Comment by chriseth** [comment]
Yes!
