### ISSUE TITLE
Consider semantic versioning semver

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#292]
http://semver.org

How do I know when to release 1.0.0?

If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by chriseth** [comment]
I think semantic versioning works probably fine for source-level libraries which have a single entry point ("API") and can provide backwards compatibility by having fallbacks that provide the old behaviour. Furthermore, semantic versioning is useful for libraries which are pulled into other projects as a dependency.

Please try to prove me wrong, but I think that semantic versioning (in the strict sense) is not applicable to Solidity due to the following reasons:

Solidity does not have something that can be called "API": It has several entry points which may break compatibility: The language itself, the commandline compiler, the C++ library and the javascript compiler. Only the C++ library and the javascript compiler provide a way to avoid breaking changes as I explained above. All others are used by humans directly and thus it is hard to avoid breaking changes without making the language or the commandline compiler cumbersome to use.

Having said that, I try to avoid breaking changes in all of the four "entry points" listed above. I am a bit less concerned about breaking compatibility in undocumented features, very new features or things considered as bugs. Whenever a breaking change happens, I increment the second version number (not the first as in semantic versioning).

If you care about the correctness of you programs, please take a look at the [changelog](https://github.com/ethereum/wiki/wiki/Solidity-Changelog) regularly.

I would love to hear all your thoughts about versioning, breaking changes and especially experiences with breaking changes concerning Solidity.

**Comment by axic** [comment]
@chriseth actually you are doing what semantic versioning suggests. For major version 0 (early dev), breaking changes mean an increment in the minor version. When you reach 1.0.0 the rules change slightly.
