### ISSUE TITLE
Why do enum checks use invalid instead of revert?

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#3027]
I've noticed that by looking at the asm generated for a sample code using enum, and got curious about the reason.

**Comment by chriseth** [comment]
It depends on the context. Decoding enums uses `revert` and encoding enums uses `invalid`. The idea is that if you use an invalid enum value internally, it is probably a programming error, but if it is an input, it is a "user error".

**Comment by leonardoalt** [comment]
I see, thanks.
Just to clarify a bit more, I have the following example:
```
pragma solidity ^0.4.17;

contract T {
    enum Test {
        A, B
    }

    function f(Test a) {
        if(a == Test.A) {
            g();
        }
    }

    function g() {}
}
```
The way I understood, this case should use `revert`, but when I look at the asm it uses `invalid`:
```
...
     /* "enum.sol":79:158  function f(Test a) {... */
...
    tag_4:
      tag_5
      0x4
      dup1
      dup1
      calldataload
      0xff
      and
      swap1
      0x20
      add
      swap1
      swap2
      swap1
      pop
      pop
      jump(tag_6)
...
   tag_6:
        /* "enum.sol":116:122  Test.A */
      0x0
        /* "enum.sol":111:122  a == Test.A */
      0x1
      dup2
      gt
      iszero
      tag_11
      jumpi
      invalid
...
```

**Comment by chriseth** [comment]
This is due to the fact that the old ABI decoder does not perform verification of inputs. The `invalid` you are seeing is because it comes from `a == Test.A`, a point where internal checking is done again right before the equality comparison. This will be fixed soon.

**Comment by jackpot1136** [comment]
So let me ask you something, are you in charge of checking out my case? And if so who is the one that's helping me out? I just wanna check because what it looked like to me is that a whole bunch of money private keys including my Trrezor. Look if you guys have to in and check everything I'm ok with that. No problem I've got nothing to hide. On top of that I'm greatfulbecause ive learned so much in the last two days. Thank you. Now we're all grown adults here, right? I encourage that but please come at me like a man so that it doesn't look all shady like it's being stolen. I even said whoever was there that I'm giving him 10k tonight for helping. Please get a hold of me so we can get back to work please. And if you're in charge I'd appreciate it greatly if you approve the data that checked out to be withdrawn. Why the trezor data? Please the sooner we finish the sooner we get back to work. No more delaying please.

**Comment by chriseth** [comment]
The comment by @jackpot1136 looks like randomly generated spam.

**Comment by jackpot1136** [comment]
@leonardoalt are you ready? Common

**Comment by jackpot1136** [comment]
Now I managed to copy some of the files that were sent out and well compare the numbers

**Comment by leonardoalt** [comment]
Oh I see.
Thanks for the explanation!
