### ISSUE TITLE
SMT Solver: Use ite-function on braches

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3137]
As suggested through experiments by @leonardoalt on oyente, the SMT solver might be able to handle the exponential blow-up induced by branches much better than the "driver" of the SMT solver.

Currently, Solidity assumes arbitrariness for touched variables after branches. An improved version could collect all conditions leading to the end of a branch and then use
`x := ite(condition, last_value_of_x_in_branch1, last_value_of_x_in_branch2)`

In the current version, `revert(c)` is not regarded as a branch but just adds `c` to the constraint set. Also, push and pop are used to scope branches, this also has to be changed because the full history of both branches need to be in scope.

Another question would be how to handle loops in such a framework.

**Comment by leonardoalt** [comment]
I've implemented the `ite` part in my fork, and removed the solver push/pop for the branches (also removed the addAssertion for the condition and !condition). It works well right away exactly because the SSA indices of the vars do not overlap in the branches! So the vars can be computed inside the branches freely without constraints, but they're only used afterwards if their conditions are satisfied.
It now proves that the following code is correct and stopped giving false positives.
```
contract C {
  function f(uint a) public {
    uint b;
    if (a == 0)
      b = 100;
    else {
      if (a == 1)
        b = 200;
      else
        b = 300;
    }
    assert(b < 500);
  }
}
```
The way it is now, the condition will be repeated in the `ite` for every var after the branches merge back. It would maybe be better to have `condition -> conjunction_of_assignments`.

**Comment by chriseth** [comment]
@leonardoalt wonderful! Can you create a pull request?

**Comment by leonardoalt** [comment]
Done: https://github.com/ethereum/solidity/pull/3216

**Comment by chriseth** [comment]
Implemented in https://github.com/ethereum/solidity/pull/3346
