### ISSUE TITLE
Support for EIP #196 - #198 precompiles

### ISSUE THREAD

**Issue by nateawelch** [ethereum/solidity#3165]
Is there a timeline/plan for supporting the precompiles introduced in byzantium?

**Comment by axic** [comment]
Can you please explain why is there a need for language support? It can be implemented via libraries easily.

**Comment by nateawelch** [comment]
It's not necessarily needed, but there should have language support because the precompiled contracts are part of the platform, not user made contracts. Solidity also has language support for the pre-byzantium precompiles, so I think it only makes sense to have language support for the byzantium precompiles.

**Comment by axic** [comment]
Keep in mind pre-Byzantium precompiles have a very simple interface and are widely used.

The Byzantium precompiles are way more complex and providing a generic interface may not be that useful given the high gas cost of it. Actual implementations using those contracts can achieve a lower gas cost for their use cases.

Also note that support for the old precompiles are part of the language due to historical reasons, simply there was no efficient way to implement them as libraries, not even support for libraries existed. 

I hope in the long term even the old ones can be moved into libraries.

**Comment by nateawelch** [comment]
Thanks for clarifying. I hadn't realized that historically it was because libraries didn't exist yet, I agree then that it's best to have them implemented as libraries. This issue can be closed.
