### ISSUE TITLE
UnimplementedFeatureErrors do not give a line number

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#3249]
It would be useful to have a line number reference for the source code to know which portion of the code is not yet supported.

> Unimplemented feature:
/tmp/solidity-20171019-1003-26zk82/solidity_0.4.18/libsolidity/codegen/CompilerUtils.cpp(124): Throw in function void dev::solidity::CompilerUtils::storeInMemoryDynamic(const dev::solidity::Type &, bool)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::UnimplementedFeatureError>
std::exception::what: 
[dev::tag_comment*] =

**Comment by roschler** [comment]
Definitely.  This is a really troubling condition to debug, especially when it occurs in relation to a storage type related context since you don't know if it's due to complex key being used in a public storage element, or as a parameter declaration problem in a function call or declaration, etc.:

UnimplementedFeatureError: Encoding type "struct EtherBandBattlesDataTypes.structPendingPaymentDetails memory" not yet implemented.

The original report is over a year old I see so bumping this one up.

**Comment by erak** [comment]
@roschler Thanks for bringing this up again. Yes, this is a nice enhancement, but it would come with the cost of a small to medium-sized refactoring. Would anyone be willing to help with that?

**Comment by axic** [comment]
This is tracked in #5161.
