### ISSUE TITLE
Add helper function for pre computing 4-byte abi signatures

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/solidity#327]
### What is the problem?

When using the `.call(..)` api I find myself choosing between the following two options.
- Option A: `call(bytes4(sha3("someFunction()")))`
- Option B: `call(0x...)`

Option A is easy(ish) to read and it is clearer what this code is doing.
Option B costs less gas at the expense of readability.
### Proposed solution

Implement a helper function `abi_signature` that computes the 4 byte signature at compile time.
- New Option: `call(abi_signature("someFunction()"))`

This has the benefit of being both easy to read and more efficient on gas.

**Comment by chriseth** [comment]
Firstly, if you use the optimizer, `bytes4(sha3("someFunction()"))` will produce the same bytecode as `0x12345678` (the actual value).
Secondly, I'm not sure if we should provide helpers for using `call` - that function should always be a last resort and it it is fine to look ugly, because it should.

**Comment by pipermerriam** [comment]
> Firstly, if you use the optimizer, bytes4(sha3("someFunction()")) will produce the same bytecode as 0x12345678 (the actual value).

This is good enough for me.  I wasn't aware that it would actually compute the bytecode.  Closing the issue.
