### ISSUE TITLE
Internal functions only referenced in the constructor are still included in the runtime code

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3271]
```
contract C {
  function C() {
    f();
  }
  function f() internal {
    uint x = 42;
  }
}
```

the code for `f()` will be included both in the constructor and the deployed bytecode.

**Comment by chriseth** [comment]
This is the case even without optimiser.

**Comment by chriseth** [comment]
Ah sorry, it's not... seems to be rather a bug to me...

**Comment by chriseth** [comment]
So the logic in `ContractCompiler` first appends all functions with an external interface and while doing so, it collects all referenced functions and puts them in a queue. `appendMissingFunctions()` then adds the code for the functions in the queue also queueing referenced functions again.

**Comment by chriseth** [comment]
The reason for this behaviour is that references to internal functions in the constructor always create an identifier for the creation-time and the run-time aspect of the function, because the function pointer might be stored in storage.

Currently, I cannot think of a nice way to resolve this issue. The simplest case of just directly calling the function can get rid of the runtime identifier, but it would be rather hacky.

**Comment by chriseth** [comment]
Although, we already do something similar for library member access, I will give it a try.
