### ISSUE TITLE
ABIEncoderV2: error computing signature of public library function

### ISSUE THREAD

**Issue by vdrg** [ethereum/solidity#3400]
The signature of a library function that receives a struct as a parameter (using ABIEncoderV2) is computed in a different way from what is shown in the specs:

```
pragma solidity^0.4.19;
pragma experimental ABIEncoderV2;

library LibMock {
    function setValue(
        InstanceLib.Instance instance, // { bytes32, address }
        bytes32 key,
        uint256 value
    ) public {
         // ...
    }
}
```
The signature computed for the `setValue` function is `sha3("setValue(InstanceLib.Instance,bytes32,uint256)")`, when it should be `sha3("setValue((bytes32,address),bytes32,uint256")`.

**Comment by chriseth** [comment]
The reason for this is that you were always able to pass storage references to structs in calls to library functions. Since this is specific to Solidity and not covered by the ABI, a signature that is incompatible with the ABI was chosen on purpose.

The actual problem here is that the compiler does not warn you that `instance` will be a storage reference and that you should explicitly mention `storage`. If you change it to `setValue(InstanceLib.Instance memory instance,` it should work as expected.

**Comment by vdrg** [comment]
I have just tried setting it as `setValue(InstanceLib.Instance memory instance, ...)` and I get the same result 😕

**Comment by chriseth** [comment]
Can you provide a complete example?

**Comment by chriseth** [comment]
Please re-open if the problem persists.
