### ISSUE TITLE
Are getter functions completely free of gas?

### ISSUE THREAD

**Issue by dapplion** [ethereum/solidity#3408]
Both in the remix.ethereum and test networks any getter function is free of gas and does not return a transaction hash. Do the main ethereum network offer the same behaviour? What is the reasoning behind making a getter function free if it requires a small amount of work?

Thank you so much!

**Comment by redsquirrel** [comment]
Getter functions don't require any work from miners, so they are free. They simply read from whatever Ethereum node you're connected to, rather than having to be transmitted throughout the network and included in a block.

See also, the difference between eth.sendTransaction and eth.call:
* https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction (costs gas)
* https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcall (is free)

**Comment by chriseth** [comment]
Closing this because this is a question and not an issue with the compiler.
