### ISSUE TITLE
Public getters for array lengths

### ISSUE THREAD

**Issue by wjmelements** [ethereum/solidity#3416]
Public arrays, such as
```
contract A {
    uint256[] public allTimestamps;
}
```
are more useful if you can know their lengths. I have been creating public length getter methods, like
```
function timestampCount() {
    return allTimestamps.length;
}
```
but it would be preferable for either the default behavior or some function modifier to do this automatically.

**Comment by wjmelements** [comment]
Also, we as a community should agree on a naming standard for array length accessors.

**Comment by cameel** [comment]
I see that this issue was marked stale but never really got a response, so I'll respond now.

As for making it an implicit behavior, it's unlikely we would do this because it would increase contract size for something that would be in many cases unused. It would also silently bloat existing contracts - most of which already have a function for this if it was deemed useful.

A modifier for this sounds better, but I'm still not convinced it's really necessary given how easy is to add a function for this. It would also be a breaking change because we'd have to reserve its name, and prevent it from being used to name the array.

Given that and the fact that this was not acted upon in the last 5+ years, I'm closing it. We could still reconsider if somehow there turns out to be a really big demand for this feature but it does not seem to be the case.
