### ISSUE TITLE
User defined types in Yul

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#3525]
User defined types, if used properly, can be useful. (This we have discussed multiple times, recently today on gitter.)

For example, in `mstore`  we want to make sure that memory pointers and values are never swapped by mistake.

We could use a new `typedef` keyword in assembly to achieve that, which takes an underlying base type and creates two special functions for typecasting. It also allows the user type to be used in literals and the value range of the base type is enforced.

```
typedef <user_type> -> <base_type>
// or typedef <base_type> as <user_type>

// creates these two functions:
function cast_<user_type>_to_<base_type>(a:<user_type>) -> b:<base_type> {}
function cast_<base_type>_to_<user_type>(a:<base_type>) -> b:<user_type> {}

// allows this:
let a:<user_type> := 1234:<user_type>
```

A real world example:
```
typedef memptr -> u256

function add_memptr(a: memptr, b: u256) -> c:memptr {
  x := cast_u256_to_memptr(add(cast_memptr_to_u256(a), b))
}

let a:memptr := 64:memptr
mstore(a, 1:u256)
a := add_memptr(a, 32:u256)
mstore(a, 2:u256)
```

**Comment by axic** [comment]
Alternatively special functions could be introduced such as `cast:memptr()` and `cast:u256()` (or even C++ like `cast<memptr>()`) instead of `cast_u256_to_memptr` and `cast_memptr_to_u256`, respectively.

It seems however that would conflict with the current parser and not sure we want to introduce any more complexity in that regard.

**Comment by axic** [comment]
Since we support dots in function names, how about `convert.<from>_to_<to>` instead of the `cast_<from>_to_<to>` syntax?

**Comment by chriseth** [comment]
`<from>.to.<to>`?

**Comment by chriseth** [comment]
We could also ask the user to provide the names of the conversion functions as part of the typedef:

`typedef <a> as <b> convertvia a_to_b, b_to_a;`

**Comment by axic** [comment]
Feedback from the summit: maybe user defined types are not too urgent, but having specific types from dialect (#7830) would be useful.

I suggest we consider the following types for the EVM dialect:
- address -> `address`
- memory pointer -> `memptr`
- storage key?
- storage pointer? 
- calldata pointer?

And define typecasting functions for them in the form of `<from>_to_<to>`, e.g. `memptr_to_u256` and `u256_to_memptr`.

**Comment by chriseth** [comment]
The benefit of having to specify the names of the conversion functions is that it allows you to search for a function being referenced and see that it is a conversion function or not.

**Comment by SilentCicero** [comment]
### My preferences:
```
define SomeType as uint256
define OtherType as uint256, uint32

cast(SomeType, uint8) // like datacopy etc *special functional notation*

define MemoryLocation as pointer
define StorageLocation as pointer

function something(a:MemoryLocation, b:StorageLocation) {}
```

### Typedef:
I also prefer `define` vs `typedef` in that case you're cutting the word define off. This is not Yulish IMO.

```
type Nick as uint8
define Nick as uint8
```

I like `type` or `define` not `typedef` (i.e. be explicit and clear, it's also similar to TypeScript)

### Pointer conversation:
I like a general pointer type, more basic. Not against though a memory / storage pointer. But for now even basic pointer is fine. I don't really like the idea of converting between memory pointers and storage pointers but I see the safety reasons for it.

If we add mem/storage, I like the below statement:

```
define Nick as storagepointer // use the full word like datacopy etc
define Nick as memorypointer // use full word

or

define Nick as spointer // like sstore
define Nick as mpointer // like mstore
```

### Address Builtin Type:
You could do an address type, but is it not more strict to define uint160 instead.

```
define Contract as address // address does seem clearer
define Contract as uint160
```

### Casting:
I sometimes which case was just a function (i know it doesn't make sense) but.. cast(t1, t2).. like datacopy etc.

```
cast(uint160, bool)
```

**Comment by chriseth** [comment]
@SilentCicero can you elaborate on how `cast(uint160, bool)` would work? The current idea is that there are only conversion functions from a user-defined type to its base type and vice-versa - because that is the bare minimum you need in order to operate. Everything else can be done by user-defined functions.

So assuming you meant `cast(address, uint160)` - how would you apply such a function to variables of that type?

I think it makes sense to abbreviate the word `pointer` to `ptr` - you probably have to write it a lot. So either `memptr` or `mptr`.

Furthermore, I think we should introduce as many types as make sense on the EVM (this also means that `uint8` and such should not be built-in types) and type the parameters to the built-in functions. The reason is that this is a good protection against confusing the parameters - just think about the `call` bulitin function!

Extensive list, could be trimmed down:

uint256
int256 (sdiv!)
bool (iszero - but maybe not)
bytes32 (distinction between arithmetic and bitwise functions, maybe overkill)
memptr
memlength (the only thing that can be added to a memptr and is used for the length params, maybe overkill)
sslot / storageptr / storageslot (I'm leaning towards `slot` since storage is not byte-addressable)
gas (probably overkill)
address
balance / wei (probably overkill)
calldataptr
calldatalength (could also have generic `length` type, which can also be returned by `returndatasize`)

Thinking about this again, maybe the following is a good choice:

uint256
int256
bool
bytes32
memptr
length
sslot
gas
address
wei
calldataptr

**Comment by chriseth** [comment]
Sorry, this got out of hand away from user-defined types. My current preferred solution for the typedef would be:

`type UserName as uint256 via uint256_to_UserName, UserName_to_uint256`.

**Comment by chriseth** [comment]
I'm wondering if it makes sense to allow for user-defined restrictions on existing built-in functions. For example, if we have

```
type mptr as u256 via u256_to_mptr, mptr_to_u256
```

then we would like `mload(u256)->u256` to change to `mload(mptr)->u256`. Without that, the user-defined type is not really helpful.

Should we add
```
restrict mload(mptr) -> u256
```
where the listed types (note we only have types here, no variable names) have to have a base type that equals the actual types of the builtins. This statement has the effect that the named function changes its signature in the scope of the statement.
