### ISSUE TITLE
CI builds should only be triggered, if sources where changed

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#3533]
Currently the CI builds are triggered, also if only documentation was changed. At least travis builds are  super slow, probably that could help to get faster feedback from CI.

**Comment by chriseth** [comment]
I'm not sure about this. We should instead have good caching so that builds are fast. Sometimes, it is important to have a full run on the change because the CI run also creates binaries and might deploy them somewhere. If that doesn't work, we might be completely stuck on e.g. a release.

I think the better way forward would be to move as much as possible away from travis. Circle seems to be much faster and also better with caching.

**Comment by aarlt** [comment]
@chriseth @axic From my point of view this issue can be closed.
