### ISSUE TITLE
Deprecate `years` suffix

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/solidity#3606]
The `years` literal number suffix is defined as 31536000 seconds at https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L747

This is incorrect - the correct value is 31557600 seconds.

A true Earth year is closer to [365.256363004 days](https://en.wikipedia.org/wiki/Earth) which is standardized as 365.25 days of 86400 SI seconds each in the [Julian Year](https://en.wikipedia.org/wiki/Year), as used in astronomy and other sciences.

However, as civilians and the Gregorian calendar uses [common](https://en.wikipedia.org/wiki/Common_year) and [leap years](https://en.wikipedia.org/wiki/Leap_year), it may be worthwhile to consider deprecating `years` to avoid potential confusion altogether.

**Comment by chriseth** [comment]
The `year` suffix is unrelated to what we humans experience as a year on Earth. The [documentation](https://solidity.readthedocs.io/en/develop/units-and-global-variables.html#time-units) states that `1 years == 356 days`, `1 days == 24 hours` and so on and also warns that this is far from the truth. The only number we can rely on is seconds, although this is already questionable, since this value is under the control of the miners and can be manipulated.

Having said that, all these values are inexact, but the definition of `1 year` is perhaps the most dangerous, so I'm fine with deprecating it.

@axic, what do you think?

**Comment by chriseth** [comment]
Documentation was not updated.

**Comment by axic** [comment]
I think #4019 (and #4046) actually did update it. Please reopen again if not satisfied :)

However, we still need to remove the extra `if 050` check.
