### ISSUE TITLE
Add cmd flag to suppress warnings

### ISSUE THREAD

**Issue by stevenroose** [ethereum/solidity#3619]
Title is self-explanatory. To see if the compilation succeeded, the many warnings can be annoying. A `--nowarnings` would be appreciated.

**Comment by axic** [comment]
The output code should be 0 or 1 depending on success, see `echo $?` in the shell.

**Comment by stevenroose** [comment]
I assume that, but it's not entirely clear. Also, output is put on Stderr instead of Stdout so can't easily be grep'd.

Also to see what errors you have, it's useful to suppress warnings.

I have a relatively large code base that is written in an older solidity version (before not declaring visibility was a warning and before throw was deprecated), so I get at least two warnings for every method, which is extremely verbose.

Perhaps there should be a different issue for not printing warnings if the pragma is a version before the deprecation of things.

**Comment by chriseth** [comment]
@stevenroose you can either use an old compiler or the standard-json interface. In that one, it should be rather easy to filter out warnings.

**Comment by cameel** [comment]
Related to #2675 and #2691.

**Comment by cameel** [comment]
I'm going to close this issue in favor of #2675 because looks like that one is going to cover a more general case of filtering warnings. See specifically https://github.com/ethereum/solidity/issues/2675#issuecomment-782365034 for a summary our discussion on the last weekly call. If you have any feedback, let's continue the discussion in that other issue.
