### ISSUE TITLE
Confusing that solc waits for input on stdin if no files specified.

### ISSUE THREAD

**Issue by AnthonyBroadCrawford** [ethereum/solidity#3696]
# Issue 
When invoking solc with the compute gas flag `solc --gas` and you don't specify a contract solc will permanently hang.

## Steps to recreate 

1. Invoke solc with the following command `solc --gas` and don't specify a file 

## Specs 

1. Mac OSX High Sierra 
2. On develop branch 

## Ideal solution 
We should throw an error message informing the user to provide a file

**Comment by redsquirrel** [comment]
It's not hanging, it appears to be waiting for input from STDIN. If you type the following and then hit ^D, solc will proceed.
```
pragma solidity ^0.4.20;
contract Foo {}
```

**Comment by AnthonyBroadCrawford** [comment]
@redsquirrel is that documented anywhere?  It may be worth putting a prompt when a file isn't passed along.

**Comment by redsquirrel** [comment]
To me, it's just standard Unix behavior. Unless otherwise specified on the command line, a program will wait for STDIN. This allows for pipelining. For instance, type `ruby`, `cat`, or `wc` on the command line, and they will hang, waiting for input, and keep taking input until they receive an EOF character. Which means you can pipe streams into these programs, such as 
```
echo "pragma solidity ^0.4.20; contract Foo {}" | solc --bin
```

**Comment by chriseth** [comment]
You can use `solc --bin -` to make it expect input on stdin explicitly, so we could actually remove this behaviour, but I don't know who relies on it.

**Comment by axic** [comment]
I'd be for the explicit `-`, but perhaps limit this to the 0.5.0 release?

**Comment by chriseth** [comment]
I agree.
