### ISSUE TITLE
[SMT] Storage variables of value type

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#3712]
- [X] Bool, Integer, Address
- [x] Fixed-size array
- [x] Enum

**Comment by leonardoalt** [comment]
Ideas for stages:

1) Support integer and Bool storage vars. At the beginning of every function definition they're set to unknown values. At the end of every function definition we can just set their SSA index back to 0 (since the solver is reset anyway) or increase it.

2) Support other types (I guess this is included in another issue about mapping access)

3) Constructor

**Comment by chriseth** [comment]
The nice thing about storage is that we can resolve aliasing easily: If the "path" to reach two "items" in storage is different, then the items are different, as long as the path does not start with a local variable pointing at storage. Path here means the sequence of index and member access operations.
