### ISSUE TITLE
Dynamic arrays in mappings

### ISSUE THREAD

**Issue by namreg** [ethereum/solidity#3727]
I have the following contract:
```js
pragma solidity ^0.4.18;

contract ReferralProgram {
    // referrer => array of referrals
    mapping (address=>address[]) private referrals;

    function becomeReferral(address referrer) public {
        require(referrer != 0x0);
        referrals[referrer].push(msg.sender);
    }

    function getReferrals() public view returns (address[]) {
        return referrals[msg.sender];
    }
}
```
I call method `becomeReferral` multiple times from different accounts specifying the same `referrer` address. Then I call `getReferrals` from referrer address and it returns empty array. It is possible use dynamic arrays in mappings? Documentation says `_ValueType can actually be any type, including mappings`. 
What am I doing wrong? Thanks.

**Comment by chriseth** [comment]
You get an empty array because `referrals[msg.sender]` (in `getReferrals`) and `referrals[referrer]` (in `becomeReferral`) are only the same array if `msg.sender` and `referrer` hold the same value.

Closing this because it is neither a bug nor a feature request. If you have further questions, please either ask in https://gitter.im/ethereum/solidity or https://ethereum.stackexchange.com/
