### ISSUE TITLE
Not able to install solc via snap on debian 9

### ISSUE THREAD

**Issue by tappoz** [ethereum/solidity#3732]
# Steps to reproduce this

Install `snap` on debian: `$ sudo apt install snapd`

Then install `solc`: 
```
$ sudo snap install solc
solc v0.4.18 from 'elopio' installed
```

Then I can not recall `solc` from my command line, not even after a reboot.

# Context information

## Check the directory structure of `snap` / `solc`
```
$ ls -lah /snap/bin/
total 8.0K
drwxr-xr-x 2 root root 4.0K Mar 14 10:05 .
drwxr-xr-x 5 root root 4.0K Mar 14 10:05 ..
lrwxrwxrwx 1 root root   13 Mar 14 10:05 solc -> /usr/bin/snap
```

```
$ ls -lah /snap/solc/current
lrwxrwxrwx 1 root root 3 Mar 14 10:05 /snap/solc/current -> 460
```

```
$ ls -lah /snap/solc/current/bin/
total 23M
drwxr-xr-x 2 root root  27 Oct 18 17:23 .
drwxr-xr-x 6 root root  89 Oct 18 17:23 ..
-rwxr-xr-x 1 root root 23M Oct 18 17:21 solc
```

## Try to run `solc`
```
$ /snap/solc/current/bin/solc 
/snap/solc/current/bin/solc: error while loading shared libraries: libz3.so.4: cannot open shared object file: No such file or directory
```

## Debian details

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
$ cat /etc/debian_version 
9.2
```

## Details on the installation process

I have followed this guide: https://solidity.readthedocs.io/en/latest/installing-solidity.html#binary-packages
and this guide: https://docs.snapcraft.io/core/install-debian

**Comment by chriseth** [comment]
@elopio could you help here, please? You [added libz3-dev to snap](https://github.com/ethereum/solidity/pull/2790), but somehow it does not seem to be used - perhaps we also need a dependency on the runtime version of the library?

**Comment by come-maiz** [comment]
@tappoz can you please try running `/snap/bin/solc`?

**Comment by tappoz** [comment]
First: meanwhile I wiped out the whole `snap` thingy with this:
```
$ sudo apt purge snapd
$ sudo rm -r /snap
```
So I've performed again the steps I mentioned earlier to install everything needed.

Now: the interesting thing is that when running what you asked then I can see the expected output for the `solc` command, e.g. when checking the version:

```
$ /snap/bin/solc --version
solc, the solidity compiler commandline interface
Version: 0.4.18+commit.9cf6e910.Linux.g++
```

After this test now I am not sure I am understanding that symbolic link:

```
$ ls -lah /snap/bin/
total 8.0K
drwxr-xr-x 2 root root 4.0K Mar 14 10:05 .
drwxr-xr-x 5 root root 4.0K Mar 14 10:05 ..
lrwxrwxrwx 1 root root   13 Mar 14 10:05 solc -> /usr/bin/snap
```

Also this started working as well:

```
$ /snap/solc/current/bin/solc --version
solc, the solidity compiler commandline interface
Version: 0.4.18+commit.9cf6e910.Linux.g++
```

I am a bit confused.

One last thing: why my `$PATH` does not include the `snap` subtree? I.e. this `echo $PATH | grep snap` gives empty results (even with `sudo`)?

**Comment by axic** [comment]
@elopio any idea why it still installs 0.4.18? We are 0.4.21.

**Comment by come-maiz** [comment]
The thing is that the binaries from /snap/bin are executed in the snapd confined environment, which makes some redirection to find the libraries inside of your snap instead of searching them on the system.

What you have to do is to add /snap/bin to $PATH. Which I've just tried on debian and it happens after reboot, so I'm not sure why it didn't happen to you. You can ask about it on https://forum.snapcraft.io

@axic I think something got out of sync with my release scripts. I will take a look next week. For now, you can install from edge to get the latest from `develop`:
    
    $ sudo snap install solc --edge

Or refresh if you have it already installed:
    
    $ sudo snap refresh solc --edge
 
    elopio@polydamas:~/Downloads$ solc --version
    solc, the solidity compiler commandline interface
    Version: 0.4.22-develop.2018.3.15+commit.9e109560.Linux.g++

**Comment by come-maiz** [comment]
Actually, the release scripts are working because we have 0.4.21 on candidate:
```
$ sudo snap refresh solc --candidate
solc (candidate) develop from 'elopio' refreshed
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.21-develop.2018.3.8+commit.dfe3193c.Linux.g++
```
What didn't work was the version script, no idea why. So I've pushed the candidate snaps to stable, which will have the wrong tag on the snap but will show the right version on `solc --version`. Please let me know if you find any other troubles, and I'll dig on this.

**Comment by chriseth** [comment]
Is there something left to do here?

**Comment by come-maiz** [comment]
All the versions are still marked as develop, not taking the right tag. But that's not related to debian, so this bug can be closed. 

In order to fix the other one, it would be easier to trace everything and get the snapcraft devs to fix the issue if we were using the dashboard. As I mentioned in https://github.com/ethereum/solidity/issues/3982#issuecomment-385477883, this requires a few steps by somebody from the solidity team.

**Comment by axic** [comment]
Closing this assuming it is due to the version issue which is tracked in #3982.

@tappoz please let us know if you think it is a different problem
