### ISSUE TITLE
Comparison of int literals with different signs

### ISSUE THREAD

**Issue by tolymoz** [ethereum/solidity#3794]
It looks that comparison operators in _if_ statements work well with literals with the same signs
`if ( 3 >= 5 ) { ... }`
`if ( - 4 != -1 ) { ... }`

but with different signs, it gives unexpected compiler error
`if ( -1 >= 4 ) { ... }`
Logically, such operation should be valid.

**Comment by chriseth** [comment]
What do you mean by "unexpected compiler error"? Is it an internal error or is it just an error that you would net expect?

If it is not an internal error, then there are at least three different things that come together for this to happen:

 - we only have infinite precision for rational numbers and not for bools
 - the final type of a rational number only depends on the number itself and not the context in which it is used (otherwise it would be really confusing)
 - the type in which a binary operand is executed is always the type of one of the operands (this also helps with limiting the confusion, I would say, but it has other drawbacks)

The type of `-1` is `int8` and that of `4` is `uint8` (smallest type that can hold the number). These two types cannot be converted into each other, because they only have an overlapping value range. Thus, there is no common type in which the comparison could be done.

One way to solve this would be to weaken the requirement of "the computation of a binary operator happens in the type of one of the operands" for comparisons, since the result type is always bool and the type in which the comparison is performed does not matter (because there cannot be arithmetic overflow, for example).

**Comment by tolymoz** [comment]
It looks comparison operators define literal types differently in the first and the second positions.
If we try with variables type conversion of comparison operators works well in both positions:
`int8 x = -1;`
`uint16 y = 10;`
`if( x != y ) { ... } //OK`
`if( y != x ) { ... } //OK`

If  we use one literal:
`if( x != 1) {} //OK, 1 has type int8`
`if( 1 != x) {} //Compiler error, 1 has type uint8`
Intuitively, these two variants should be equivalent.

Seems in the second position positive literals can be converted either to int or uint, but in the first position only to uint.

**Comment by chriseth** [comment]
Oh wow, this is weird. Created a new issue for that: https://github.com/ethereum/solidity/issues/3796

**Comment by axic** [comment]
@chriseth I think this issue was superseded by #3796?
