### ISSUE TITLE
Cleanup exceptions and exception handling.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#3819]
Exceptions and exception handling is somewhat inconsistent throughout the codebase.

For example ``CompilerError``, ``InternalCompilerError``, ``FatalError`` and ``UnimplementedFeatureError`` in ``libsolidity/interface/Exceptions.h`` could be integrated in the ``Error`` class.

**Comment by chriseth** [comment]
Those exceptions are not errors: Errors are stuff displayed to the use while the exceptions listed above are just exceptional terminations of some compiler routines, which could result in displaying an error to the user but does not have to.

Apart from that, the Error class should not be an exception, because it should not be thrown, it should just be added to the list of errors.

**Comment by ekpyron** [comment]
OK - however it would still be good to be able to handle those exceptions using a common base class.

They already inherit from ``Exception`` and consequently from ``boost::exception``, so they could just add their name (and potentially further information) as ``errinfo_comment``, etc., so that catching ``Exception`` will yield all necessary information and we no longer need to catch them separately.

Changing the ``Error`` class towards not being an exception and never being thrown could be a separate step.

**Comment by axic** [comment]
From https://www.pivotaltracker.com/story/show/111957119:
> Remove the exception base classes from the Error classes and add a constructor that allows to specify the reason and the source location directly. Make sure that those objects are not thrown (which should already be the case).

**Comment by axic** [comment]
I did some work with this, but it is a deep rabbithole.
