### ISSUE TITLE
A return that also fires an event with the same data

### ISSUE THREAD

**Issue by ethers** [ethereum/solidity#390]
The idea is being able to simply do this in a contract function:

`returnWithEvent (1, 2, 3);`

Instead of having to define an event in the contract, like `event fooEvent(uint x, uint y, uint z)` and then invoking it separately:

```
fooEvent(1,2,3);
return (1, 2, 3);
```

So single line of code `returnWithEvent (1, 2, 3);` would automatically fire `fooEvent(1,2,3);`.  Solidity could come up with a convention for what the default generated event name is.  In this example, the convention is function name concatenated with "Event".

**Comment by VoR0220** [comment]
Hmmmm...interesting proposal. Could you detail it out a bit more what you might like to see if at all possible?

**Comment by chriseth** [comment]
This looks really useful! Still, could you please provide some real-world use cases? I know that this is important for non-constant functions being "called" from UIs. Assuming that is solved by the EVM infrastructure (as considered for serenity), are there still a lot of use cases left?

**Comment by ethernian** [comment]
I see this enhancement related to another [issue#709](https://github.com/ethereum/solidity/issues/709). 

I would see an event firing as an implementation of value return in the case of external function call (from UI). 
Thus I would propose ALWAYS to fire an event as implementation of value return for the case of external call (or if the function is marked as external?). This is because this is the only way to transport the returned value to UI. 
If the external UI do not need a return value of the function, it should use an extra function without return value. It it clean.

**Comment by axic** [comment]
@ethers I'm wondering what is the return value as events have no return values.

Do you mean the event is fired and the method returns without any return value?
 Or the event arguments are always passed back as a tuple?

**Comment by ethers** [comment]
@axic I mean that the event is fired and the method returns the value just like a normal `return`.

`returnWithEvent (1, 2, 3);` would return the tuple (1,2,3) after firing an event.

It doesn't have to be a tuple.  `returnWithEvent someValue;` would return `someValue` but also fire an event with `someValue` just before it returns.  The could help UIs calling non-constant functions to get the return value, without requiring the contract to add and fire an event separately.
