### ISSUE TITLE
Initializing static memory array with a constant is unsupported

### ISSUE THREAD

**Issue by aaronstjohn** [ethereum/solidity#391]
Solidity seems to have trouble initializing a static array using a constant as a size. The following code produces solidity errors.

```
uint constant CELLS = 10;
...
function initmap()
{
      uint[CELLS]  memory map;
     ... 
}
```

Produces: `Error: Invalid array length.`

Additionally, attempting to initialize an array in this fashion

```
function initmap()
{
      uint[]  memory map;
      map.length = CELLS;
     ... 
}
```

Produces : `Error: Expression has to be an lvalue.`

**Comment by chriseth** [comment]
There is a story for constants as size on the backlog.
Solidity tries to make expensive operations look expensive, at least on the built-in types, so resizing memory arrays is not possible (because that would need a full copy of the array). I hope that we will have smart arrays soon, which should have that feature.
Closing this issue.
