### ISSUE TITLE
Improve documentation regarding metadata

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4021]
In #4011 this came up as an issue because perhaps it is not prominently explained.

In #3741 it also came up as it could be mentioned in when discussing source maps.

**Comment by ricmoo** [comment]
I would like a lot more documentation on the source map. In https://github.com/ethereum/solidity/issues/3741 you mention it is based on "sections" but in the given example, how do you map section 0 to the relevant opcodes?

The documentation at https://solidity.readthedocs.io/en/develop/miscellaneous.html#source-mappings is quite limited and does not explain how to use the "f" field, especially since I get f = 0 for every part.

Thanks!

**Comment by chriseth** [comment]
You only get `f=1` if you use multiple source files. You might have to use internal functions from libraries in other source files or inherit from contracts in other source files to get a larger `f`.

**Comment by ayrat555** [comment]
any updates on the issue? @axic 
It would be nice to have metadata format description for all versions of Solidity, not only the latest one

**Comment by NunoFilipeSantos** [comment]
Hi! 👋 This issue is stale, and for that reason we're closing it for now.
