### ISSUE TITLE
Allow access to pragma's in ``Type::is*Convertible``, ``Type::*OperatorResult``, etc.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4109]
Some breaking changes for 0.5.0 could have been implemented using pragma 050, if the respective member functions of ``Type`` had access to the pragmas.

Relevant functions are ``Type::isImplicitlyConvertible``, ``Type::isExplicitlyConvertible``,  ``Type::unaryOperatorResult``, ``Type::binaryOperatorResult``, ``Type::commonType``.

These are mostly used in the ``TypeChecker``, but also in different contexts (e.g. ``CompilerUtils::revertWithStringData``), so it may be hard to find a suitable object to pass to them (without creating a "god object").

We should consider:
  * Do we expect more changes in the future for which access to the pragmas in these functions would help?
  * What kind of object (that provides access to pragmas) would be reasonable to pass to these functions?

**Comment by randomnetcat** [comment]
- Yes, I think it is reasonable to expect more changes in Types where it would be useful to have access to pragmas.

Obviously, the second question is more complicated. I think it would be too unwieldy to get some context everywhere that could possibly use a Type. Since solc is inherently single-threaded (with no plans to change this right now), you could pass it in as a static field in the Type class. Another solution would be to pass it in as a constructor argument.
What to pass in: Maybe just a TypeContext class with some useful information. It could just start with pragmas.

**Comment by ekpyron** [comment]
Since we kind of decided not to use such pragmas anymore, but instead to keep a breaking branch, I'm closing this.
