### ISSUE TITLE
Move libevmasm to solidity

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#413]
libevmasm, liblll and lllc should be moved into the solidity repository (as directories parallel to libsolidity). Please keep the commit history, for example by doing it like that: http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by bobsummerwill** [comment]
And lllc too presumably?

Hmm.   Won't that make libethereum dependent on solidity?

What about libevmcore?

Have a look at http://doublethinkco.github.io/webthree-umbrella-cross/images/target_dependency_graph.svg.

I think what you are saying here makes sense, but we'll just have a little bit to work through on these edge cases.

BTW - I cannot add labels here.   Are permissions for Solidity repo using different teams/groups?   Ditto Mix.

**Comment by chriseth** [comment]
We might duplicate libevmcore

**Comment by bobsummerwill** [comment]
Right.

As we discussed a while back, as all the various clients already have copies of this stuff, duplicating it between eth and solidity is a bit smelly, but not the worst thing in the world for the decoupling that would give us.

**Comment by androlo** [comment]
Will the cpp vm also be part of the build, or is it compiler only? Just curious.

**Comment by chriseth** [comment]
@androlo not totally sure what you mean, but the compiler does not need the vm.

**Comment by androlo** [comment]
Just curious if it would be compiler only or if it would also have the VM, maybe for some extra coding tools later or w/e.

**Comment by bobsummerwill** [comment]
Hey @androlo,

There is some detail on what we are looking to do at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/index.html#project-reboot, though the aim is actually to go a little further than that, even, and to sever the link from solidity into "cpp-ethereum" in that target diagram entirely, so that the Solidity smart contract compiler and the eth C++ runtime are completely separate.

We will still have a dependency onto cpp-ethereum for soltest for the time being.    Further refactorings and decoupling is required before that link can be severed.

Aleth\* and mix will depend on both eth and solidity still, though Aleth\* apps are on their way out, and we hope to make it possible for mix to sit on top of multiple runtime clients (so geth or eth, and maybe more).

**Comment by androlo** [comment]
Thank you.
