### ISSUE TITLE
ABI: include return types in selector (breaking)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4151]
In order to have a stricter commitment to the return types (identified in #4116 as a potential improvement)  it would make sense to include that in the selector, which currently is a keccak256 hash of the function name and the types of its parameters: `name(T1,T2,...)`

The suggestion here is to extend that to include return types: `name(T1,T2,..)->(T1,T2,..)`

If there are no return types, the hash would remain identical.

In practice this would mean that contracts would check for two hashes in the dispatcher to support older contracts calling in.

However for the case of the contract calling out, I think it would have to be a compiler option to resort to the old hash or the new one. New contracts not interacting with older ones could opt to rely on the new hash.

While it should be possible to implement this in a backwards compatible manner (such as keeping both hashes in the ABI encoding), I think that in the long term will be detrimental as the legacy code to be compatible with will not shrink as time progresses. I feel it is better to take a break earlier than later.

**Comment by chriseth** [comment]
As an alternative, the second hash could be provided in the calldata in addition to the first hash at a location that is usually not looked at by the dispatcher and decoder. One possible location would be after static data and another possible location would be at the end of the calldata.

This option might be problematic if people assume that the payload is `calladat[4:]`.

**Comment by chriseth** [comment]
The advantage of the above alternative is that it is fully backwards compatible.

**Comment by chriseth** [comment]
If we do a breaking change, we could also consider using a 32 byte hash of the function signature and thus eliminating the possibility for collisions.

**Comment by Arachnid** [comment]
What's the use-case here? Is calling something with the wrong ABI really a common issue? It seems odd to include things that can't affect function selection in the ABI hash.

**Comment by HarryR** [comment]
Yes, this is an issue, see the recent debacle about dodgy ERC tokens which dont return anything from 'transferFrom' instead of a boolean value.

If you claim to be compliant with an ABI and the ABI says youll return a bool, but your function returns an int instead - where both the positive and failure code is interpreted as a boolean true, then your function has the same ABI selector but any caller following the standard will interpret both success and failure as a success... etc.

IMO the return type should be part of the ABI, so asking for IsSuccess->int is different from IsSuccess->bytes32.
