### ISSUE TITLE
Stray `(B` in CI test output

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4184]
On circle, there are stray symbols at the end of a line, probably connected to the colour output:

`Running commandline tests...(B`

**Comment by mestorlx** [comment]
The output from `$(tput sgr0)` in my local terminal is `^[(B^[[m` so I believe the problem  is on how the websconsole interprets `tput sgr0`. One possible solution is to use `tput setaf 7` which will set the font to white rather than turn off all attributes. 
I submitted PR #5115 which replaces `tput sgr0` with 'tput setaf 7' to test this and seems to work.
