### ISSUE TITLE
Empty binary w/ no error produced when compiling contracts inheriting interfaces that almost match

### ISSUE THREAD

**Issue by XertroV** [ethereum/solidity#4220]
Example:

Try compiling this to get the `Test` binary:

``` solidity
interface TestIface {
    function getThing(bytes13 myThing) external view returns (uint);
}

contract Test is TestIface {
    uint s = 100;

    function getThing(bytes32 myThing) external view returns (uint) {
        return uint256(myThing) + s;
    }
}
```

Even though the function signature doesn't match, no error is produced.

Personally (having more than one complex contract I'm working on atm) I've probably spent about half a day total tracking these bugs down. The most efficient method I've found is commenting out half the interface to determine which incorrect function signature is causing it, and then halving the search space, etc, until I've found the offending function declaration. 

Would obvs be much easier if there were an error (like what happens if you return different arguments, or have `external view` instead of `external`, etc)

**Comment by axic** [comment]
There is no error message because contracts ha be implicitly abstract by not declaring all symbols. Since `getThing(bytes13)` is not declared, but due to overloading `getThing(bytes32)` can coexist with it, `Test` turns into an abstract contract.

Issue #649 tracks a feature request to require explicit declaration for abstract contracts. I'm closing this now, please comment there.

**Comment by XertroV** [comment]
@axic - thanks for this explanation. Didn't make sense to me before but everything clicked when realising the contracts become abstract.
