### ISSUE TITLE
EVM version in syntax tests

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4262]
Currently the syntax tests are confined to the current EVM version and that means some tests cannot be moved.

How about adding a comment at the top of the file for EVM version:
```
// evmversion=byzantium
contract C {
  function f() {
    ...
  }
}
// ---
// TypeError...
```

Or how about adding it after the `---` delimiter?

I think the top may make sense as it is visible instantly and the 0.5.0 pragma is there usually.

Ping @ekpyron.

**Comment by chriseth** [comment]
I would prefer to have it below the separator. Then it is also in line with the semantics tests. We can even have multiple evm versions and multiple expectations.

**Comment by ekpyron** [comment]
Yes, I think having it below the separator is better.
What about the syntax? For the semantics tests so far we had the suggestion to use ``// DEPLOY: Contract[40]: 1, "some_argument", ...`` for specifying which contract to deploy with how much ether and which arguments. If we stay with that, upper case may be a good choice for this as well, so maybe:
```
contract C {
  function f() {
    ...
  }
}
// ----
// EVMVERSION: byzantium
// TypeError: ....
```

**Comment by axic** [comment]
Can we have multiple separators then declaring multiple expectation sections?

```
// ---
// EVMVERSION: byzantium
// TypeError: ...
// ---
// EVMVERSION: homestead
// Warning: ...
```

**Comment by ekpyron** [comment]
So far we can only have one separator and one set of expectations (without additional configuration like ``EVMVERSION`` having multiple sets of expectations wouldn't have made any sense. But we could consider adding support for that now - however, maybe using separate files with only one set of expectations each may be less error-prone, I'm not sure.

If we decide to go for multiple expectation sections we could add support for ``pragma``'s there as well - this way the experimental 0.5.0 tests could have had the form:
```
...
// ----
// Warning: ...
// ----
// PRAGMA: experimental "v0.5.0"
// TypeError: ...
```

This could be of some help for future breaking releases.

Not really related to this issue, but actually it may even make sense to have a distinguished separator for semantics tests and allow both syntax and semantics expectations in the same test contract, so that we can automatically track warnings in semantics tests as well (this would prevent the current situation of having a lot of deprecated syntax in the end-to-end-tests in the future). So:

```
...
// ----
// Warning: ...
// ====
// f(uint, bool) -> 1, true
// -> 0x1234
```

However, I'm not sure whether it is wise to over-complicate the test case syntax - it may be better to keep things simple or we end up needing tests for the test infrastructure itself :).

**Comment by axic** [comment]
If the plan is not to have multiple expectation blocks then I kind of feel like `evmversion` may belong better to the top grouped with the 0.5.0 pragma. Though I do not have a strong preference on this.

**Comment by ekpyron** [comment]
Currently ``soltest`` takes a ``--evm-version`` argument that globally sets the evm version to be used with all tests. In SolidityNameAndTypeResolution.cpp, for some test, the test expectations depend on the evm version that is currently set (i.e. different expectations for different evm versions) - still the tests are only run for a specific globally fixed evm version in each run of ``soltest``, not for multiple versions.

The evm version that is set using ``--evm-version`` is relevant for a lot of the non-extracted test cases.

If we now want to specify the EVM version in the expectations of the extracted syntax tests, then this would override the ``--evm-version`` argument for these tests (I don't think it makes sense to only run extracted tests if the evm version specified in the expectation matches the ``--evm-version`` argument; also specifying multiple expectation blocks with multiple ``EVMVERSION:`` statements and only running one of them depending on the ``--evm-version`` argument may be misleading).
I guess it makes sense to still fall back to the EVM version set using ``--evm-version`` for all test cases that don't explicitly state a version in the expectations.

I still think it makes sense to move the EVM version to the extracted test expectations, but we have to be aware that is somewhat inconsistent with the way ``soltest`` currently works (i.e. running with one specific, globally fixed evm version).

I considered suggesting to remove the ``--evm-version`` argument to ``soltest`` altogether and instead to run all tests with a specific set of evm versions, but I think keeping the argument makes sense - we probably don't want to run all tests for multiple, resp. all evm versions in every invocation of ``soltest``, but it still makes sense to be able to run all tests with different default evm versions.

**Comment by ekpyron** [comment]
The SMT checker pragma could also be part of the "setup" in expectation blocks and such expectation blocks would only be considered if not globally disabled with ``--no-smt``.

**Comment by axic** [comment]
The final syntax is:
```
// EVMVersion: >homestead
// EVMVersion: !byzantium
// EVMVersion: <petersburg
// EVMVersion: =contantinople
```
