### ISSUE TITLE
Make static and dynamic memory arrays interoperable

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#431]
https://www.pivotaltracker.com/story/show/110326726

**Comment by chriseth** [comment]
It seems that this change is not too compatible with our type system. The main reason is that statically-sized arrays are encoded without length prefix in the ABI encoding and quite some places in the code base assume that this encoding is the same for memory.

**Comment by chriseth** [comment]
Failure for colocolo. Moving back to backlog.

**Comment by axic** [comment]
From Pivotaltracker:
> The only difference between static and dynamic arrays in memory is that their size is known at compile-time or not.
> On the other hand, static arrays do not have an explicit length prefix, which makes it impossible to assign static arrays to variables of dynamic array type.
> To make this possible, we should reserve space for the length prefix and potentially write it to memory at the point of assignment (conversion).
> We might consider allowing conversion of empty arrays to anything (so that we can use `[]` as initializer).

**Comment by chriseth** [comment]
With the new ABI coder, we might re-try this one.

**Comment by chriseth** [comment]
One of the main goals here is also to be able to convert array literals to both dynamic and static array types.

**Comment by skyfly200** [comment]
This would be super helpful. I am running into issues with my contracts hitting their size limits because I have a lot of strings. I am working to compress duplicate string data but I need to be able to pass a fixed-length string into a function expecting a dynamic array to work this out. All the ways I have seen of doing this so far seem to end up creating so much extra code I am sure it will make me hit the limit, thus making my efforts in vain.
Anyone know any updates on this or current workarounds that are more succinct?

**Comment by cameel** [comment]
#11879 covers the same thing and has more detail so I'm going to close this one.
