### ISSUE TITLE
mapping should enforce storage keyword

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4319]
The compiler should complain about the missing `storage` keyword, even though mappings cannot live outside storage:

```
contract c {
    mapping(uint => uint) y;
    function f() view public {
        mapping(uint => uint) x= y;
        x;
    }
}
```

**Comment by sifmelcara** [comment]
(Just curious) Isn't local variables' data location default to storage? ( [doc](http://solidity.readthedocs.io/en/v0.4.24/types.html#summary) )
Why should the compiler complain about the missing `storage` keyword?

**Comment by chriseth** [comment]
Because it is no longer optional in 0.5.0.

**Comment by sifmelcara** [comment]
Hmm.. then why don't we enforce the `storage`/`memory` keyword for all complex types in local scope?
Maybe emit a warning when missing data location specifier is a good first step?
(I think I can help implement this)

**Comment by chriseth** [comment]
We do enforce it! The question here is why it does not work for mappings, and my suspicion is that because it is not a reference type.

**Comment by sifmelcara** [comment]
I've finished the patch for this issue. But I think I found a strange behavior that presents in both solc 0.24 and current develop branch.
```solidity
contract Test {
    struct Nested { uint y; }
    function h(function(Nested) external returns (uint)[]) external {}
}
```
```
test.sol:3:25: Warning: Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.
    function h(function(Nested) external returns (uint)[]) external {}
                        ^----^
```
This is caused by `_variable.isExternalCallableParameter()` returning `false` and `_variable.isLocalVariable()` returning `true` (`_variable` = that problematic `Nested`). This is a bit counter-intuitive for me.

Not sure how should we interprete the above code and whether this is intended behavior or not...

**Comment by chriseth** [comment]
Interesting find! Can you create a separate issue about it?
