### ISSUE TITLE
Suggestion: Disallow tuple types with less than two components. Replace empty tuple type with explicit void type.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4436]
Currently we still have rather weird and somewhat inconsistent constructs in connection with tuples, e.g.
``var () = g()``, ``(uint a,) = (1,)`` being an error, etc.

This can be worked around by continuing to remove ``var`` and disallowing constructs like ``(1,)``, but I think it may make sense to rethink tuple types in general.

Whereas one-element tuples hardly occur "naturally" in the type system, especially after multi-var declarations and tuple assignments require equal numbers of components, zero element tuples are used as a ``void`` type at several places (which most of the time is only made comprehensible by an explicit comment in the code).

I suggest to require tuple types to have at least two components by assertion in the ``TupleType`` constructor, to replace one-element tuple types by their component type and to introduce an explicit void type to replace empty tuples.
I already had a look into the code and the required changes wouldn't be very invasive and seem to work well.

I think it would improve readability and consistency in the type system in general.

What do you think @chriseth @axic?

**Comment by chriseth** [comment]
I am fine with removing the special case of `(1,)` and just disallowing empty components in tuple expressions (but not in left-hand-sides).

As far as disallowing tuple types of less than two components is concerned: I'm fine with disallowing to explicitly construct such tuples, but I think it is quite nicely handled for function calls:

A function always returns a tuple. A one-component tuple is auto-converted to its only component by the type checker (with a special case about `(1,)` which would be removed), a zero-component tuple is also called "void". Note that parenthesized expressions are explicit in the AST, result in one-element tuples which are then assigned the type of their component by the type checker (i.e. they are only really visible as a syntactical component inside the AST, not in the type system).

I think because of this handling, it is actually rather consistent inside the internal type system (void being the empty tuple type is consistent with functions returning nothing and also corresponds to the "unit type" available in many functional languages).

Are you sure that the changes required are really so small?

**Comment by ekpyron** [comment]
Well, the function return type initially is not a tuple, but just a vector of types. The type checker annotates function call types as tuple, unless there's only a single element, in which case that element is used. But there's never one-component tuples involved in all that.

I think it would be consistent if every non-tuple type would at the same time be a tuple-type with one component (so there'd need to be some kind of tuple interface implemented by every "non-tuple" type announcing one component, namely itself, as well as by the "real" tuple type announcing more than one components or zero components (unless the void/unit type is made explicit)). That would match what I'd be used to from functional languages or logical type theory. I would imagine that this would be a rather nasty change to the code, though.

So I think either making "one-component types" actually **be** tuples themselves (which would be rather involved) would be consistent (then everything is a tuple) - or letting tuple types always be compound types with more than one component would be consistent (which would require an explicit void type).

Currently, there's a tuple type with a strange "gap" - one-component tuples never actually occur apart from the ``(1,)`` construct - I could assert ``_types.size() != 1`` in the TupleType constructor and it would only fail for these. Still conceptually there are one-component tuple types that are "kind of" the same as the type of their single component, but not really the same, and they are never actually used :).

And the changes for requiring tuples to have at least two components are indeed rather small - I pushed a crude experimental version, if you want to have a look (https://github.com/ethereum/solidity/tree/tupleSuggestion).

But yeah - maybe it's only me who finds tuples at the moment to be a bit weird and I'm fine with just disallowing ``(1,)`` for now, but it may be worth thinking about this some more at some point!

**Comment by ekpyron** [comment]
Yah... I don't think we need this anymore...
