### ISSUE TITLE
Memory leaks in CompilerStack

### ISSUE THREAD

**Issue by guidovranken** [ethereum/solidity#4517]
The following program will result in memory leaks.

```cpp
#include <libsolidity/interface/CompilerStack.h>

int main(void)
{
    std::string sol("contract C {\n"
        "    function f(C c) pure public returns (C) {\n"
        "        return c;\n"
        "    }\n"
        "    function g() pure public returns (bytes4) {\n"
        "        return f(this).f;\n"
        "    }\n"
        "}\n");

    try {
        dev::solidity::CompilerStack m_compiler;
        std::string sourceCode = "pragma solidity >=0.0;\n" + std::string(sol.c_str(), sol.c_str() + sol.size());
        m_compiler.setSources({{"test.sol", sourceCode}});
        m_compiler.compile();
    } catch ( ... ) { 
    }

    return 0;
}
```

See here for an extensive description of each memory leak and where it was allocated: https://gist.github.com/guidovranken/fe23891be27ac170a523b8a9af66238b

Tested on latest 'develop' branch.

**Comment by chriseth** [comment]
I have seen such reports in the past, and I'm not very sure if this is actually the case. Since we are using shared pointers throughout the codebase, the only thing I could think of that could cause this would be circular references.

In any case, since the amount leaked is not too big and the compiler is not a long-running process anyway, I would prioritize this rather low.

**Comment by axic** [comment]
It seems most of those issues are about ownership of shared pointers. For example the ownership of `parameterTypes` in `FunctionType`. `FunctionType::asMemberFunction(bool,bool)` creates it and passes it on to a newly created type.
