### ISSUE TITLE
Introduce a new state variable tx.id

### ISSUE THREAD

**Issue by m-schmoock** [ethereum/solidity#4530]
The transaction ID can be made accessible by a Solidity state variable (i.e. `tx.hash` or `tx.id`. A transaction hash cannot change by the mining process, and will be the same regardless when it is included in a block. 

Rationale: I think it can be useful in various scenarios where the transaction ID hash can used in order to generate and keep track of receipts like objects without the need to replay the blocks to lookup the corresponding TX ids. The only way currently is to generate some clumsy `sha3(msg.data, msg.sender, block.number`) and make the actual receipts some ecc signed message of msg.sender but that doesnt offer a good way to lookup the transaction at a later point.

I found some old discussion about this on stackexchange ( https://ethereum.stackexchange.com/questions/2664/is-it-possible-to-get-the-transaction-hash-from-within-a-solidity-function-call ) but no follow up issue or any pull request.

What do you think?

**Comment by lukas-berlin** [comment]
This is not possible within the scope of solidity. because you can only use data the EVM is delivering. The tx hash is calculated from the sha3(tx.nonce,tx.gasPrice,tx.gasLimit,tx.origin,tx value,tx.data) The EVM only provides part of this data. You could write an EIP to include new opcodes that provide the tx.hash.

**Comment by axic** [comment]
As mentioned by @lukas-berlin the `block`, `msg` and `tx` objects map 1-to-1 onto EVM opcodes. Whatever is available in the EVM we expose there, but cannot do anything else.

[EIP901](https://github.com/ethereum/EIPs/issues/901) suggests the above.

Closing this issue since we cannot do anything unless relevant EIPs are accepted and implemented.
