### ISSUE TITLE
Move determinism compilation check from solc-js to this repo

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4548]
It is currently handled by https://github.com/ethereum/solc-js/blob/master/test/determinism.js by compiling "the DAO" contracts.

Those tests were added in 
https://github.com/ethereum/solc-js/issues/19 mostly for having tests for a compiler non-determinism (covered in 
https://github.com/ethereum/solidity/issues/17).

**Comment by axic** [comment]
I'm not convinced the DAO compilation helps in that regard anymore though, since so many updates were made to it and likely it wouldn't cause the same problem again (in particular the modifier on unimplemented functions change very likely would have stopped the problem from occurring).

Therefore I'd be also content with just removing it alltogether.

**Comment by chriseth** [comment]
The bug was only visible when a contract was compiled twice without resetting the javascript runtime between the two compilation runs (and thus causing different memory allocation behaviour).

Currently, the only way we can find such issues now is by using the cross-platform bytecode comparison tests, but I think we should still also have such a test here, perhaps with a better code base, as you say.

**Comment by axic** [comment]
Sure, but we can move it as Javascript based tests, just as we do with Zeppelin & co.

**Comment by chriseth** [comment]
ok, sure!

**Comment by axic** [comment]
@leonardoalt since you are working on solc-js-smt tests, perhaps you want to consider this too?

**Comment by leonardoalt** [comment]
Ok, I can check it next week with the other stuff.
