### ISSUE TITLE
Split address type into payable and non-payable

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4552]
Current super type is `address`.

`contract` would keep information about the public functions, but would not expose them to the user, however it would enable the compiler to keep certain checks (such as `Value transfer to a contract without a payable fallback function.`).

For example:
```
contract C {
  function() { }
  function f() {}
}

contract D {
  function f(C c) payable {
    // pre-0.5.0 this worked and raised the error:
    c.transfer(msg.value);
    // accessing other functions is possible:
    c.f();

    // in 0.5.0 one must explicitly cast to address first, losing all this information (no error raised here):
    address(c).transfer(msg.value);
    // through address of course accessing other functions is not possible:
    // fails: address(c).f();

    // the proposed option raising the error:
    contract(c).transfer(msg.value);
    // through contract accessing other functions is not possible:
    // fails: contract(c).f();
  }
}

```

**Comment by axic** [comment]
@chriseth need to discuss this, I think we should have this for 0.5.0.

**Comment by ekpyron** [comment]
I vote for only using ``address``, but to let ``address`` internally contain an optional field containing information like the fallback payability, etc. This field(s) would be present, if the ``address`` was converted from a contract, and not present, if it was converted from an integer.
In case this information is present, errors can be issued, e.g. for calling transfer when the fallback is nonpayable.

**Comment by axic** [comment]
A couple of suggestions came up on the meeting:
- the one described by @ekpyron 
- to have two address types: `address` and `payableAddress` (the latter refers to an address which as an external account or one with a payable fallback)
- to have the above `contract` type
- to have the above suggestion but name it `account`

I think the proposal described by @ekpyron is the most reasonable one if we would like to restrict the number of new types added.

**Comment by ekpyron** [comment]
The disadvantage of my suggestion above is that ``address`` as a function argument or as type in a variable declaration cannot be required to be an address that's payable.

However, the suggestion can be extended with an optional ``payable`` specifier for argument and variable declarations of ``address`` type, as follows (similarly to storage specifiers):

```
function f1(address a){
  // a.transfer(...); would be an error
}
function f2(address payable a){
  a.transfer(...); // this is valid
}
```

The default "payability" would be "nonpayable", so ``f1`` can be called with any ``address``, but ``transfer`` cannot be called on ``a``.  ``f2`` cannot be called with ``nonpayable`` addresses, but ``transfer`` can be called on its argument ``a``.

An address converted from an integer is ``payable``, an address converted from a contract gets its payability from the payability of its fallback function.

The modifier would only be used for variable and argument declaration, not for conversions. ``address(c)`` implicitly is of type ``address payable`` if ``c`` has a payable fallback and of type ``address`` otherwise. ``address(0x0...0)`` would implicitly be of ``address payable`` type.

This would be breaking, since it would require users to add ``payable`` to all ``address`` arguments and variables, on which ``transfer`` is called. However, I think it's better than turning it around and use an ``nonpayable`` specfier instead.

Edit: ``address payable`` would be implicitly convertible to ``address``. I don't think ``address`` has to be convertible to ``address payable`` at all, not even explicitly.
This extended suggestion is close to the introduction of a new named type like ``contract`` or ``account``, but I'd prefer it, since it reuses language concepts that are already present and I think it is more user-friendly.

**Comment by leonardoalt** [comment]
@ekpyron 's idea is my favorite so far. I'd like to keep the keyword `address` for all that, and the `payable` modifier sounds like a nice explicit requirement to me.

**Comment by axic** [comment]
So to summarise the proposal:
- `address` has a statemutability property now, with two states: nonpayable, payable
- explicit conversion from a contract, which has a payable fallback, leads to a payable address
- implicit/explicit conversion from an integer always leads to a payable address
- `.transfer()` is only present on payable address
- payable address can be implicitly converted to address
- address cannot be converted to payable address

Is that correct?

**Comment by ekpyron** [comment]
Yes, that's the idea.

**Comment by axic** [comment]
With the external interface we have to consider that `address` in the ABI always represents `address payable`, as a result, an `external` or `public` method can **only** use `address payable`, otherwise we must raise an error.

**Comment by ekpyron** [comment]
@axic Hm - I hadn't thought about that. This may be a problem. An ``external`` or ``public`` method may not even call ``transfer`` or otherwise require the ``address`` to be ``payable`` and I may want to call it with a nonpayable ``address``... which I wouldn't be able to, since there is not even an explicit conversion.

**Comment by ekpyron** [comment]
Maybe it is not actually a problem to allow ``address`` (nonpayable) in ``external`` or ``public`` methods, even though it will be ``address payable`` in the ABI.

**Comment by chriseth** [comment]
I also like the proposal, but have some questions:
 - Why is explicit conversion from address to address payable not possible?

As far as the ABI is concerned, please note that the ABI has always been less strict: You can use `contract` types as function arguments which are just translated to `address` as far as the ABI is concerned. The types are only enforced in solidity-to-solidity calls.

**Comment by chriseth** [comment]
oh and I wonder if integers should be payable by default - I would argue that you have to do `address payable(0x....)` to do get the transfer function.

**Comment by ekpyron** [comment]
When would you ever want to explicitly convert from ``address`` to ``address payable``? Especially if integers are always payable, then you would always be in a bad situation, if you attempt to do that cast...

I don't really like explicit casts of the form ``address payable(...)`` (i.e. split into two keywords) syntactically and the idea was that explicit conversions always have the form ``address(...)``, but that this does not mean that the result is not payable, but that the payability is derived from ``...``.

That's then also a reason for integers to always be ``payable``.

I'd be open to using casts of the form ``address payable(...)`` and ``address(...)`` instead as well, though.

**Comment by ekpyron** [comment]
https://github.com/ethereum/solidity/blob/3dd31b704af6c50bc56217fd07266f7872daaa44/libsolidity/analysis/TypeChecker.cpp#L1633
https://github.com/ethereum/solidity/blob/3dd31b704af6c50bc56217fd07266f7872daaa44/libsolidity/analysis/TypeChecker.cpp#L1634

To try and push this forward a bit: above is the comment explaining the corresponding behaviour for type conversions and data locations. We don't have ``string storage(...)`` and ``string bytes(...)``, but only ``string(...)`` and the data location is "inherited" from ``...``. I'd do the same for ``address(...)`` and state-mutability/payability.

Example:
```
contract C {
    function f(bytes memory b) public pure {
        string memory s = string(b); s; // works
    }
    function g(bytes memory b) internal pure {
        string storage s = string(b); s; // fails
    }
}
```

**Comment by chriseth** [comment]
That is a very good point, although data location is currently tied to the variable declaration and not to the type (even if we handle that differently internally).

**Comment by ekpyron** [comment]
In the future, we might even consider ``address view``, that only allows ``staticcall`` - not that it would immediately make sense now (without some kind of C++-style ``const``-ness construct for contracts) and we shouldn't discuss it here and now, but having the option might be a pro towards using mutability for ``address``.

**Comment by chriseth** [comment]
Clarification: implicit conversion from payable contract to non-payable address is possible.

**Comment by ekpyron** [comment]
Thinking about actually implementing this: do you think we should now introduce an actual address type in the code? It feels somewhat messy to keep using an ``IntegerType`` with modifier with this change.

**Comment by chriseth** [comment]
Closing this as we still have #4969

**Comment by kyriediculous** [comment]
This has always been defined in the called contract through its fallback or the functions being called.

Defining this on the address type itself is bad language design.

**Comment by kyriediculous** [comment]
This has always been defined in the called contract through its fallback or the functions being called.

Defining this on the address type itself is bad language design, as the modifier can be incorrectly implemented on the caller contract anyway, rendering it useless and only cumbersome to deal with when migrating from 0.4.x to 0.5.x . 

The fact that it actually threw before you had to typecast it in 0.5.0 is actually good ... Why was this changed? 

Seems like totally backward to me :(
