### ISSUE TITLE
Drop support for old boost

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4612]
I would really like to drop support for old boost, because we are adding workarounds for old boost versions (most recently some pragma cleanup in #4602).

The reason we are tied to boost 1.54 (released in 2013!) is the fact hat @chriseth wants to keep compilation supported on Ubuntu LTE versions and Trusty Tahr has 1.54.

Interesting fact, Xenial has 1.58.0 and for that version we include a header to fix some bugs in `boost::multiprecision` (which Solidity makes a great use of): https://github.com/ethereum/solidity/blob/develop/libdevcore/Common.h#L48-L55

Would the following workaround be possible? We select a Boost baseline (1.67 IIRC to have all the workarounds removed) and if the system wide installation is lower than that, the we download & build are own version for static linking.

I believe this should be possible with CMake, @chfast is that correct?

Also wondering about @ekpyron's view on this.

**Comment by chfast** [comment]
Yes, it is possible to static link newer version of boost.

**Comment by ekpyron** [comment]
I think this would make a lot of sense. Maintaining compatibility with a broad range of versions of boost is always a pain and that's unlikely to get better in the future.
We could discuss which version of boost makes up a good baseline as a compromise between the needed amount of workarounds and the need to build a custom version on various distros. Maybe 1.67 is too much - statically linking hurts the binary size and having to download and build boost is some discomfort, so best not to force the majority of users to do so. 1.58 would be a good candidate if not for the ``boost::multiprecision`` bug, which is a strong argument against it.

By the way, in the long term I would still love to remove the dependency on boost altogether :). I think @christianparpart supports that, but even if we seriously consider that, it would be a major undertaking and maybe it makes more sense to wait until we can require C++17 - and I think @chriseth is rather sceptical.

**Comment by chriseth** [comment]
Note that we cannot download anything in the PPA build process, it has to be pre-supplied as we do with jsoncpp.

We can try to go more towards header-only boost if that is of any help, but to be honest, I don't see it being removed in the near future. We should also be careful not to replace this single big dependency we have by many tiny not so well tested dependencies.

**Comment by axic** [comment]
`jsoncpp` isn't pre supplied as much as I know, it is downloaded by CMake.

**Comment by chriseth** [comment]
the ppa_build script downloads it.

**Comment by axic** [comment]
Into the location cmake expects it?

**Comment by axic** [comment]
Yeah, in `scripts/release_ppa.sh`. So boost could work the very same way.

**Comment by chfast** [comment]
> We can try to go more towards header-only boost if that is of any help

I'm not sure this is any help here, but it would help with static/dynamic linking issue (because there is not going to be any linking any more).

- regex can be replaced with `std::regex`.
- program_options can be replaced with `CLI11` library.
- filesystem, if needed, will be hard to replace. The easiest probably would be use `std::filesystem` from C++17.

**Comment by chriseth** [comment]
In this case, I would prefer to stay with boost and perhaps upgrade it manually.

**Comment by ekpyron** [comment]
We can re-evaluate the "drop boost altogether" question when we can require ``C++17`` as minimum requirement - which will probably only be in a years from now or so anyways :).
Still I'd vote for bumping the minimum required boost version regularly, since in my experience maintaining backwards compatibility with a larger range of boost versions is an ever increasing hassle.

**Comment by axic** [comment]
This issue should really only be about using a newer version of boost as a minimum 😉

**Comment by ekpyron** [comment]
Since this issue was referenced by @axic recently: in the meantime we solved the PPA build issue for trusty by re-using entirely static binaries built on newer ubuntu versions for the packages for trusty.

So in the meantime we're free to decide to bump basically to any minimum boost version that is available in *some* ubuntu release. Currently the newest option is 1.67 in cosmic. For any older ubuntu versions we can always decide to switch to static builds for the PPAs.

We can also decide to be more conservative and first keep compatibility with 1.58 for shared linking on xenial or with 1.65 for shared linking on bionic (I think it's reasonable to still fully support bionic for a while, so not to go beyond 1.65 for now as minimal requirement, but we can argue about choosing between 1.58 and 1.65, respectively shared or static PPA builds for xenial in the future).

**Comment by chriseth** [comment]
"years from now" - might it have been almost exactly one year? :)

**Comment by ekpyron** [comment]
Haha, I wrote ``which will probably only be in a years from now`` - so I guess the ``s`` in ``years`` was a typo and the estimate was surprisingly accurate :-D.

**Comment by leonardoalt** [comment]
Well it was 1.0192 years later, so technically correct.

**Comment by axic** [comment]
Since we moved on to require 1.65 as a minimum, I think we can close this issue. It is obviously a perpetual thing, we can also move on to require newer ones, but 1.65 (and requiring C++17) allowed to remove all our workarounds, see also #5823.
