### ISSUE TITLE
[CLI] Solc should report if there was no contract to compile

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4617]
Follow-up of https://github.com/ethereum/solidity/pull/4525 :

After that PR, solc properly reports why it does not output anything. There is still one edge, case, though: If you compile a file that does not contain any contracts, it still does not output anything. We should report something like 'input did not contain any contracts'. We should also check what happens if contracts are present but are abstract or interfaces.

**Comment by axic** [comment]
#8646 is a related question which could be useful here.

**Comment by cameel** [comment]
This issue actually requires some clarification. It was originally reported while #4525 was still in progress, probably with the assumption that it will be merged but in the end it wasn't. Instead we merged #4958 some time after that and it apparently solved the issue differently because now compiler always prints `Compiler run successful, no output requested.` when there's no other output. The message is not always correct though because it can be displayed even if user did request some outputs.

As for the case when there are only abstract contracts or interfaces present - the output is non-empty so the problem does not exist - the compiler prints a header describing the type of output and the contract name (though the latter not for all outputs).

So, here's what needs to actually be done:
1. When there are no contracts at all in the input, say just that instead of saying that no outputs were requested.
2. When there are only abstract contracts and interfaces to compile, there's no change required.
    - We might want to print a message saying that there were no deployable contracts but that might actually be a breaking change (do we consider changes like that to console output breaking?). We would also have to handle different outputs differently. For example such contracts can still have some output in `--hashes` or `--devdoc` even if `--bin` is empty. But I think it's better to leave this case up to #12398 I have just reported.
3. I'd change the message displayed in all other cases to `Compiler run successful, no output.`. Optionally, we could actually check if any outputs were requested and print a more specific message in that case.
4. ~Consistently print the header with contract name in all cases (i.e. the `======= test.sol:C =======` part). Currently `--ir`, `--ir-optimized`, `--ewasm` do not print it when used on their own.~ Moved to  #10275.

**Comment by anshss** [comment]
I would like to begin with this issue. This would be my first open source contribution. At what part of the solidity repo do I have to commit the above mentioned changes?

**Comment by cameel** [comment]
See [`CommandLineInterface.cpp`](https://github.com/ethereum/solidity/blob/develop/solc/CommandLineInterface.cpp).

**Comment by Andy53** [comment]
I have submitted a [pull request](https://github.com/ethereum/solidity/pull/13606) to fix this issue. A small number of the automated tests are failing due to the fact that the output has changed when no contract is supplied. All other tests have passed.

**Comment by nikola-matic** [comment]
```
We should also check what happens if contracts are present but are abstract or interfaces.
```
@chriseth what is the desired behaviour in case of abstract contracts/interfaces?

**Comment by cameel** [comment]
I'd say they should not be treated as contracts. They do not produce any artifacts. I guess this should be no different from having a file that only has enum definitions or is empty.

**Comment by nikola-matic** [comment]
> Consistently print the header with contract name in all cases (i.e. the ======= test.sol:C ======= part). Currently `--ir`, `--ir-optimized`, `--ewasm` do not print it when used on their own.

@cameel by the way, it looks like this is not gonna be as easy (and perhaps not even worthwhile), as it looks like we have two stage tests for `--via-ir` and `--ir-optimized` (as part of command line tests), where we have intermediate output, and inserting the contract name in said file is going to break the second round of compilation as it's obviously not a valid statement to have in a file. Do you perhaps know of an easy way to circumvent this, or should we forgo this feature? Perhaps inserting the contract name as a comment instead, i.e. `// ===== test.sol:C=====`, but that doesn't really seem nice to me either.

**Comment by nikola-matic** [comment]
More problems :) Compiling a struct is perfectly valid, however, yields no contracts, which means we output the 'desired' no contracts to compile message. This is a bit of a problem. E.g. the currently failing test where we compile the input .sol file with the `--combined-json ast` option yields a JSON AST output file, with said message appended at the end, since there are technically no contracts there. This then obviously poses problem when attempting to re-import that same JSON AST into the compiler, since the message has now made the JSON AST invalid.

**Comment by cameel** [comment]
> Do you perhaps know of an easy way to circumvent this, or should we forgo this feature? Perhaps inserting the contract name as a comment instead, i.e. `// ===== test.sol:C=====`, but that doesn't really seem nice to me either.

Well, the IR output is already not machine readable. It has `IR:` (or `Optimized IR:`) header and you have to strip that if you want to pipe it to compiler's input. So it's just a matter of having to strip one more line.

Having said that, having these non-code bits in the output is annoying and we do have task to allow disabling them: #10275. Pragmatically, I do think it would be better to postpone making these frames consistent until we can actually easily disable them. IMO this is not a deal-breaker here.

> E.g. the currently failing test where we compile the input .sol file with the `--combined-json ast` option yields a JSON AST output file, with said message appended at the end, since there are technically no contracts there. 

Ah, looks like I was wrong about there being no artifacts if there are no contracts.

But anyway, this is still simple to solve - only print that message when there was no output. If there are no contracts but we also have some output, don't print it.
