### ISSUE TITLE
Standard library contracts questions

### ISSUE THREAD

**Issue by androlo** [ethereum/solidity#462]
- Is the standard contracts going to be in the Solidity repository. Just need final confirmation.
- If so, is the tests going to run together with the other Solidity tests or separately.
- How will the tests actually run.

Not sure if this is a discussion or it's decided, but I need to know.

**Comment by chriseth** [comment]
Some solidity contract/library code will go into the repository and there will also be tests. If possible, they should of course be run together with all other tests. For that, we need a backend node implementation that does not have the "1 second per block" limitation, otherwise the tests will take too long.

**Comment by androlo** [comment]
go-ethereum simulated chain does this, and also allow you to generate proxies (like `web3.contracts` does).

**Comment by androlo** [comment]
(and is also the same chain/vm implementation that the code will most often be run in live)

**Comment by chriseth** [comment]
We now use `eth --test` to run tests. Standard contracts can be tested in the same way. Please feel free to contact me about how to add some contracts.
