### ISSUE TITLE
Potential improvement of syntax test annotations

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4620]
This is inspired by the test syntax of flint by @franklinsch : https://github.com/flintlang/flint/blob/master/Tests/SemanticTests/invalid_types.flint

Perhaps we should move expected errors in syntax tests that span only a single line as a comment into that line:

```
contract C {
  function f() {} // 2-15: TypeError: ...
}
```

where the numbers indicate the covered columns. This way, modifications in other lines will not create conflicts and it is easy to see where the error applies (i.e. it might be possible to mix failing and succeeding cases).

If an error spans multiple lines, it would still appear at the bottom.

One downside is that this would not check the order of the errors.

**Comment by ekpyron** [comment]
Thinking about this some more, I'm starting to like it. Maybe we should use ``///`` instead to distinguish from "normal" comments (or something else like ``//!``). We can also consider such a comment in an otherwise empty line to refer to the line above or below - however, it may be problematic that it's not quite clear which one it would be.

Maybe even:
```
contract C {
  function f(uint a) {}
         /// ^----^  Warning: Unused function parameter
}
```
Not sure about that, though.

This would be compatible with multiple expectation sections (for EVM version and pragma settings) - errors expected with this syntax would just be added to all sections.

I'll keep it in mind for the next test infrastructure overhaul.

**Comment by chriseth** [comment]
I think `//!` is a good idea (`///` interferes with natspec), but putting it in a line below is probably not too useful, especially with non-fixed-width fonts or tabs.
