### ISSUE TITLE
Improve test coverage of the Scanner

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#4627]
`libsolidity/parsing/Scanner.cpp` has a test coverage of 69% when running the syntax tests, but 92% when also running the semantics (end-to-end) tests.

Should add test cases to the `tes/solidity/syntaxTests` directory.

Missing cases:
- unicode escapes
- upper case hex values
- multiline comments
- `Token::Dec`, `Token::AssignSub`, `Token::AssignBitOr`

**Comment by herrBez** [comment]
I have a doubt: should this hexadecimal literal `uint x = 0xAa;` in which compare both upper case and lower case hexadecimal numbers accepted or not? (Currently it works)

**Comment by chriseth** [comment]
@herrBez thanks that you want to help out! Please create a pull request early so that we have a place for discussion. I'm not too much into how to extract coverage information either, but I think you have to compile with `cmake -DCOVERAGE=ON ..; make` and then use the codecov tool. If we are lucky, you will get coverage results on the pull request itself (but sometimes they are broken).

**Comment by herrBez** [comment]
Thank you very much for the support. I will try to conclude (hopefully soon!) (I am currently using codecov on my fork to see the test coverage). It is ok to make multiple commits or it is better a single commit with the fix for this issue?

**Comment by chriseth** [comment]
Feel free to do it in whatever way you like. At the end, depending on the amount of changes, a single commit is probably best, but it can always be squashed.
