### ISSUE TITLE
Document semver syntax supported in version pragmas

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4642]
Add short introduction to semver and explain caret in the version pragma section.

From https://github.com/ethereum/solidity/pull/4214

Quoting @axic: I'd vote to have a short intro to semver with some useful patterns we use (^0.4.24, >0.4.24 <0.5.0, 0.4.24).

**Comment by cameel** [comment]
I think we should actually explain our whole semver syntax in the docs. We do not support all the syntax npm does and we also support some very weird stuff like `X` as a valid version, quoting or `*.*.*`.

Many examples of valid and invalid pragmas can be found in [`test/libsolidity/SemVerMatcher.cpp`](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SemVerMatcher.cpp) but #11295 shows that we do not have complete coverage of all valid syntax variants.

**Comment by chriseth** [comment]
I think we should not explain that we support some weird things (I would not encourage anyone using it). I have never heard that people have problems with semver, also because in our use-case you usually do not need complex expressions.

**Comment by christianparpart** [comment]
> I think we should actually explain our whole semver syntax in the docs. We do not support all the syntax npm does and we also support some very weird stuff like `X` as a valid version, quoting or `*.*.*`.
> 
> Many examples of valid and invalid pragmas can be found in [`test/libsolidity/SemVerMatcher.cpp`](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SemVerMatcher.cpp) but #11295 shows that we do not have complete coverage of all valid syntax variants.

I just suggested to have the handling of `x` and `*` in semver matching removed (instead of documented). It's not part of semver.

**Comment by chriseth** [comment]
`x` and `*` are part of the grammar at least: https://www.npmjs.com/package/semver

**Comment by cameel** [comment]
Oh wow, they are. In that case better to leave it for compatibility. I thought it was a weirdness only in our implementation but it's actually `npm`'s quirk (or maybe even more general).

As for documenting it, I think these things should generally be documented because they also matter for tools or for compatibility with other compilers. But you have a point. We should probably have a separate reference section for that and keep the general description simple.

**Comment by kevinclancy** [comment]
As far as I can tell, the way `x` and `*` are used in solc does not match their corresponding behavior in npm. In npm, `1.x ` denotes the range `>=1.0.0 <2.0.0-0`. The npm documentation says nothing about putting `x` variables inside range bounds, which solc allows. For example, I can compile a sol file that includes the line `pragma solidity >0.x.0;`; this is useless because I could just write `pragma solidity >0.0.0` instead.

It might be a good idea to prohibit the use of `x` and `*` in conjunction with `<`, `<=`, `>`, and `>=`.
