### ISSUE TITLE
Mappings cannot be returned from internal functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4670]

**Comment by ekpyron** [comment]
What about the following:
```
mapping(uint=>uint) m;
mapping(uint=>uint) n;
function f() internal returns (mapping(uint=>uint) storage r) {
  r = m;
  r[1] = 4;
  r = n;
  r[2] = 8;
}
```
~~Currently, if just allowing mapping returns syntactically, this will end up writing 4 to key 1 in **n** :).~~
Currently, this does not work as expected (further investigation required).

So we should:
  - Fix this, so that it will write to key 1 in ``m`` and to key 2 in ``n`` and correctly return ``n``.
  - ~~Try to detect a second assignment and make it an error (probably equivalent/related to #4669)?~~
  - ~~Disallow naming storage return variables, forcing the use of ``return``?~~

~~If this construct is allowed for return values, that may be inconsistent with disallowing it for local variables (allowing it for local variables faces the same problems, though~~).

EDIT: In fact this does work as expected for local variables. #4671 will allow it syntactically. Therefore it should also work as expected for return types (but currently it doesn't without further changes).

**Comment by chriseth** [comment]
This code here seems to work as expected:
```
contract c {
mapping(uint=>uint) m;
mapping(uint=>uint) n;
function f() internal {
    mapping(uint=>uint)  r = m;
  r[1] = 4;
  uint a;
  (r,a) = (n,2);
  r[2] = 8;
}
function g() returns (uint, uint) {
    f();
    return (m[1], n[2]);
}
}
```

**Comment by ekpyron** [comment]
Hm... I'll recheck, at the moment I can't reproduce the behavior from before, maybe I did something wrong before...

If it turns out to indeed work, we can probably allow assignments to local mapping variables right away.

**Comment by ekpyron** [comment]
Yes, it seems that it in fact works for local variable. I'll create another PR that allows assignments for them in general and will add some semantics tests for them.

**Comment by ekpyron** [comment]
I updated  #4671 to allow assignments for local variables (this already works as verified by the added semantics test).

What remains is to allow returning mappings in internal functions and to verify that this works with semantics tests (I rechecked - allowing the returns syntactically alone will not result in the desired behaviour, so this will need some further investigation).

**Comment by ekpyron** [comment]
Not sure whether something changed or whether I was simply wrong before, but I checked again during #4635 and I don't experience any problems with internal mapping returns (and arguments) anymore. I'm considering fixing this together with #4635 now.
