### ISSUE TITLE
Document that abi.encode and abi.encodePacked can be used for concatenation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4704]
Also for `bytes32 -> bytes` conversion.

**Comment by axic** [comment]
Should we consider adding aliases for these? Would be easier if we could extend the language with "standard libraries".

**Comment by chriseth** [comment]
I still don't want to take the burden to implement a standard library, but people could use this in an external string library, for example.

**Comment by axic** [comment]
I should have written "language extensions written in Solidity" (aka meta programming the compiler) instead of standard library.

Adding `abi.convertFixedBytes()` would be easy to write in Solidity itself, but would be nice to include that as part of the compilation process, just like we have `appendLowLevelAssembly`.

**Comment by axic** [comment]
@ChrisChinchilla I think you've started to document this.

**Comment by ChrisChinchilla** [comment]
@axic Yes I have, this may get closed as part of that, or it might need further expansion. I shall take a look.

**Comment by thegostep** [comment]
@ChrisChinchilla 

Is the concatenated data created by abi.encode equivalent to RLP encoding?

I've previously used this library for RLP decoding: https://github.com/hamdiallam/Solidity-RLP

Also wondering if there are more efficient encoding / decoding methods out there for the purpose of concatenation.

**Comment by chriseth** [comment]
@thegostep the Solidity compiler does not implement any RLP functionality.
