### ISSUE TITLE
Rethink ``Type::canLiveOutsideStorage``; allow as arguments/return values for internal functions.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4804]
Came up in #4798.

``Type::canLiveOutsideStorage`` seems to mainly be used for mappings - we may want to consider removing it and using a shared flag for storage references and mappings instead. Also in ``TypeChecker::visit(FunctionDefinition const& _function)`` we should allow such types as arguments and return values for internal functions in general (currently mappings are allowed explicitly), but we have to recheck whether this requires new tests, etc.

**Comment by chriseth** [comment]
Also, we should better unify mappings and reference types (not through inheritance but perhaps through a shared bool function) - we often have special cases that apply to reference types and to mappings.

The `canLiveOutsideStorage` could be replaced by a function that tells whether the type has a name or not, because we have many weird types (TypeType, MagicType, ``super``, ...) which should not be exposed.

**Comment by hrkrshnn** [comment]
@chriseth https://github.com/ethereum/solidity/pull/6282 extends `canLiveOutsideStorage` to Struct.

If you want changes, we should think about it now.

**Comment by chriseth** [comment]
Closed by https://github.com/ethereum/solidity/pull/9146
