### ISSUE TITLE
Grammar: Type names are expressions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4807]
Any type name (user-defined or not, including arrays) should be an expression, but data location specifiers are part of the variable declaration and not the type.

Discovered in #4738

**Comment by axic** [comment]
I think this seems to be solved (https://github.com/ethereum/solidity/blob/develop/docs/Solidity.g4#L116 and https://github.com/ethereum/solidity/blob/develop/docs/Solidity.g4#L132) but admittedly I haven't reviewed the grammar too much.

**Comment by fvictorio** [comment]
Hey @chriseth, I've been maintaining [a fork](https://github.com/solidity-parser/antlr) of the solidity ANTLR grammar for some months, and many projects are already depending on it. Of course, it would make much more sense for this grammar to live under `ethereum/solidity`. Do you think we could unify efforts here?

I think something like this would allow some testing strategies to make sure the grammar is up to date. For example, the test suite could generate the ANTLR parser and run it with the solidity files used for testing the compiler.

**Comment by chriseth** [comment]
@fvictorio we added the grammar to this repository recently. We actually test the grammar in the way you describe :)
If you would like to make any changes, please create a pull request or open an issue. I'm closing this issue since it is about something else.

**Comment by axic** [comment]
This isn't the right issue to discuss this on, but we have an ANTLR grammar: https://github.com/ethereum/solidity/blob/develop/docs/Solidity.g4

It is the https://github.com/ConsenSys/solidity-antlr4 merged and maintained by us (as requested by the team behind upstream). You could consider checking it and pushing PRs if there is any difference to yours.

**Comment by fvictorio** [comment]
Yeah, I created the fork from that one because there wasn't a lot of activity in it. I think at this point my fork is the one being used the most (by at least solhint, solidity-coverage, buidler and prettier-solidity), so maybe you should sync that one? I can open a new issue if you prefer to discuss this in another place.

**Comment by chriseth** [comment]
I just looked at the diff between your version and the one in the ConsenSys repository and there are not too many changes that we did not already apply. One thing that confuses me is the explicit listing of some identifiers:

https://github.com/ConsenSys/solidity-antlr4/compare/master...solidity-parser:master#diff-931f4b868a25efffc188dc49205ab568R377

Can you explain why it is done like that?

Here is my pull request: https://github.com/ethereum/solidity/pull/9161

**Comment by fvictorio** [comment]
Yeah, that has to do with how ANTLR works. If you don't do that, then there are some ambiguities when the code is parsed. For example, if you have a function `function receive` it can't tell if it's an `Identifier` or a literal `receive` keyword. So that's the way to fix it. (Maybe there's a better way, but I couldn't find one).
