### ISSUE TITLE
Undefined address casting compiles

### ISSUE THREAD

**Issue by decanus** [ethereum/solidity#4833]
## Description

Solidity allows casting an undefined address to a smart contract, this should probably not be allowed. The code can be found [here](https://github.com/HarbourProject/protocol/blob/204312da5b445f5574ec10a79ab7ac9ba06653dc/contracts/Organization.sol#L72-L85).

In this example ```proposal``` is undefined yet we can do this

```Solidity
ProposalInterface proposal = ProposalInterface(proposal);
```

From what I can see, it initializes an ProposalInterface with the address ```0x0```, ideally, this would not even compile as there is never a previous variable definition of ```proposal```.

## Environment

- Compiler version: 0.4.24
- Framework/IDE (e.g. Truffle or Remix): Truffle

**Comment by chriseth** [comment]
This will fail to compile with 0.5.0 because we changed the default scoping rules from "JavaScript-like" to "C99-like".

In general, explicit type conversions do not have runtime-checks, so yes, you can cast every address to every contract type. It is mathematically impossible to check whether the bytecode of a contract implements a certain interface, and even getting close to checking almost all would be very costly.

**Comment by decanus** [comment]
I mean, the implicit thing is not an issue, more the fact that you can cast something which hasn't been defined as a variable.

There should be at least a ReferenceError like in JS, saying that ```proposal is undefined```.

**Comment by chriseth** [comment]
Most of this will be impossible starting from 0.5.0, the remaining part is tracked in https://github.com/ethereum/solidity/issues/4669
