### ISSUE TITLE
Internal compiler error on storage pointer casts and assignments.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#4948]
The following crashes with "InternalCompilerError: Invalid conversion to storage type." for 0.4.24 and develop.

```
contract C {
        uint[] a;
        uint[] b;
        function f() public view {
            uint[] storage c = a;
            uint[] storage d = b;
            d = uint[](c);
        }
}
```

The same for base types other than ``uint``.

Found during #4911.

**Comment by ekpyron** [comment]
Related, but not entirely a duplicate: #4901.

**Comment by ekpyron** [comment]
Same for:
```
 contract C {
        uint[] a;
        uint[] b;
        function f() public view {
            uint[] storage c = a;
            uint[] memory d = b;
            d = uint[](c);
        }
}
```

**Comment by liangdzou** [comment]
#4901 is fixed in PR 4904. I do not know why Chriseth stoped respond on the PR for more than 5 days.

**Comment by liangdzou** [comment]
This issue looks interesting. The conversion looks valid since the base type is exactly the same.

**Comment by liangdzou** [comment]
The type analysis for type conversion actually will always convert array pointer to array ref since array inherits from ReferenceType. Therefore, the target type will be a reference, instead of a pointer which makes the assertion to be violated.
@chriseth suggested me to add a branch to only allow bytes and string array conversion. I have added tests in the PR4904, this issue is fixed by adding the restriction. All code and the test are added to the PR.

**Comment by chriseth** [comment]
Something here is very wrong. In `T(x)` for a type `T`, the check whether conversion is possible should check whether a conversion to a pointer can be done. After the conversion has happened, the result should again be a reference, I think. But perhaps we should rather fully re-architect this and add the `copyof` operator.

**Comment by liangdzou** [comment]
@chriseth Actually, the array pointer is modified to reference before checking if it is possible to convert.
