### ISSUE TITLE
Replace explicit cast from external function types by member

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#4994]
To reduce confusion, external function types should have a `.address` member instead of the explicit conversion to address.

**Comment by ekpyron** [comment]
I vote for this!

**Comment by axic** [comment]
Hm, interesting idea.

I guess we cannot do the same with contract types, because that would conflict function members. So that is a disparity between the two.

However, we already have `.selector` on functions (including function types), so this feature should be in line with that.

I'd suggest we consider implementing it earlier (0.5.2?) and deprecating the explicit conversion.

**Comment by chriseth** [comment]
I would say we implement all things we are quite confident about and make 0.6.0 early.

**Comment by ekpyron** [comment]
I'll implement this for functions now. Do we want this for contracts? I.e. ``c.address`` instead of ``address(c)``? Personally I'd stay with casts there, but I'd be fine with changing it as well.

**Comment by chriseth** [comment]
We can only do it for functions like that because they do not have user-defined members.

**Comment by ekpyron** [comment]
We could still do it, since ``address`` has never been a valid identifier - I'd still not do it, but I opened #7235 for tracking it anyways.

**Comment by leonardoalt** [comment]
Closed by https://github.com/ethereum/solidity/pull/7239
