### ISSUE TITLE
Semver checker doesn't work with ^0

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5081]
```
k.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.5.0-develop.2018.9.24+commit.c9290462.mod.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0;
^-----------------^
```

I think `^0` should work for any `0.y.z` version, but I may be mistaken.

**Comment by chriseth** [comment]
If someone takes this, please check if it should work or not.

**Comment by mestorlx** [comment]
According to the [docs](https://solidity.readthedocs.io/en/v0.4.25/layout-of-source-files.html#version-pragma) that should not work since will allow only the right most number to be anything to avoid breaking changes. However, this is not the behaivour specified in [npm](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), and the docs clearly state that "It is possible to specify much more complex rules for the compiler version, the expression follows those used by npm." 

If I am not mistaken theres is a contradiction in the documentation.

**Comment by mestorlx** [comment]
I do believe there is an issue if npm rules are accepted. According to npm docs "A missing minor and patch values will desugar to zero, but also allow flexibility within those values, even if the major version is zero." so 
`pragma solidity ^0.4.0;` and `pragma solidity ^0.4;` should be equivalent, however the latter does not work in Version: 0.4.26-develop.2018.9.27.  The version of solc installed by brew  (Version: 0.4.8) both samples compile so maybe is an intended change.

**Comment by christianparpart** [comment]
That is exactly how I understand it too @mestorlx. @chriseth if you agree, I'd take this one over.

**Comment by HenryRLee** [comment]
Can I take this one if no one is working on it?

**Comment by erak** [comment]
@HenryRLee Sure. This one is up for grabs. Please assign yourself then.

**Comment by HenryRLee** [comment]
Thanks, @erak. I'll start working on it. But I don't think I have the privilege to self-assign.

**Comment by erak** [comment]
Great! I've assigned this issue to you now. Thanks.

**Comment by chriseth** [comment]
Fixed by https://github.com/ethereum/solidity/pull/7583
