### ISSUE TITLE
compiler [Stack too deep, try removing local variables] even return parameter number less than 7

### ISSUE THREAD

**Issue by passionofvc** [ethereum/solidity#5118]
try compile Test.sol it show me error, but replace last return parameter type to address , it compile well.
Does this is a compiler bug?
 
Test.sol:15:57: Compiler error: Stack too deep, try removing local variables.
         return (hash, prefix_hash, sig, owner, signer, amount);

## Environment

- Compiler version:
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Darwin.appleclang

- Operating system:
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

## Steps to Reproduce

```
// Some *minimal* Solidity source code to reproduce the bug.
// ...

pragma solidity ^0.4.25;
 
 contract Test{
      address owner = msg.sender;
 
      function claimPayment(uint256 amount, uint256 nonce, bytes sig)
      view public returns (bytes32, bytes32, bytes, address, address, uint256) {
      //view public returns (bytes32, bytes32, bytes, address, address, address) {
 
          bytes32 hash  = keccak256( abi.encodePacked(msg.sender, amount, nonce, this) );
          bytes32 prefix_hash =  hash ;
 
          address signer =address(0);
          require(signer == owner);
          return (hash, prefix_hash, sig, owner, signer, amount);
          //return (hash, prefix_hash, sig, owner, signer, owner);
      }
 
 }
$ solc Test.sol 
Test.sol:15:57: Compiler error: Stack too deep, try removing local variables.
         return (hash, prefix_hash, sig, owner, signer, amount);
```

**Comment by chriseth** [comment]
It is a limitation we will hopefully be able to lift soon, but not a bug. You could try to assign return values instead of using `return` and also split statements into multiple smaller ones.

**Comment by lazaridiscom** [comment]
@passionofvc, as @chriseth  said, it's not a bug, but a known limitation / known issue.

Now, for the case that you assume that it should work, because an `address` has the same size with an `uint256`: 

Within https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#types, you'll see that the size of `address` is **20 bytes** or 160bits, thus its 96bits or **12 bytes smaller** than a uint 256. That's why `address` does not hit the (currently admittedly very small) stack-limit.

-

You can find much info on `Stack too deep, try removing local variables`, i picked you one which describes some workarounds:

https://ethereum.stackexchange.com/questions/7325/stack-too-deep-try-removing-local-variables

You can usually find better help there (I answered you thoroughly 'cause I'm currently doing a teach-in).

So, in the future, the best is: First stackexchange, then issue-tracker.

cu around.

**Comment by chriseth** [comment]
The reason for the difference is not the number of bytes in the memory representation (which actually is 32 for both types if you read the ABI closely) but the fact that you read `owner` from storage and not from the stack.

**Comment by lazaridiscom** [comment]
Oh my... I've a long way to go!

**Comment by passionofvc** [comment]
hi @chriseth @lazaridiscom 
very thanks,

Please accept my apology for not being able to learn from 
[stackexchange](https://ethereum.stackexchange.com/questions/)

I will continue to learn ethereum, smart contract every day passionately.
