### ISSUE TITLE
Re-group section structure of the documentation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5151]
The section structure of the documentation is suboptimal. Most of the important information about the language is part of "Solidity in depth", although it is only one of 14 top-level elements in the TOC on the sidebar.

Perhaps it would be possible to show the sidebar in a multi-level format like on https://dutchx.readthedocs.io

**Comment by chriseth** [comment]
@ChrisChinchilla would you like to take a shot at this?

**Comment by lazaridiscom** [comment]
I've just overflown https://solidity.readthedocs.io, and spotted some main problems:

* It is nearly unbelievable that documentation of a programming-language contains advertisements (ethically or not, whatever this means). I have to put effort it, in order to get rid of them (adblock plus, block element).
* "Solidity by Example" starts with a bombastic example - this is not good, it should be a simple one.
* "Solidity in Depth" looks actually nice 

The multi-level-format / hierarchy / tree of solidity-docs ( e.g. https://solidity.readthedocs.io/en/latest/layout-of-source-files.html#version-pragma) is nicer than the one of dutchx (I had a hard time to detect any level at all there). The only thing: the white-to-dark-grey coloring going deeper levels should be reversed (dark-to white, because the root is black).

And some general points re docs:

Documentation should be better written/reviewed by newcomers, because they lack the domain-knowledge, they depend on a good structure (e.g. giving the information in the correct sequence). And thats why newcomers can detect documentation flaws better.

I no way should the documentation be written by the designers themselves. They are far too familiar with the system (this is a general rule).

Finally: writing compact/concise documentation is an art. Not everyone masters this art, and having many hands one docs sometimes reduces the quality/consistency.

**Comment by chriseth** [comment]
@lazaridiscom thanks for your comments! I will focus only on the points directly related to this issue. Please feel free to open new issues for the other aspects. A agree that having many levels is a good thing. The main point I wanted to make here is that "Solidity in Depth" should be more prominent in the sidebar and perhaps even be extended no matter where you currently are in the documentation.

**Comment by lazaridiscom** [comment]
> I will focus only on the points directly related to this issue. 
Guess I got too verbose.

> Perhaps it would be possible to show the sidebar in a multi-level format like on https://dutchx.readthedocs.io

Actually this will worsen the documentation (No professional documentation has items in the root)

**Comment by chriseth** [comment]
@lazaridiscom could you please expand the previous statement a little? What do you mean with "items in the root" and why do you think it would worsen the documentation?

**Comment by lazaridiscom** [comment]
I try:

This I mean with "root":

```
    Introduction to Smart Contracts
    Installing the Solidity Compiler
    Solidity by Example
    Solidity in Depth
    Security Considerations
    Using the compiler
    Contract Metadata
    Application Binary Interface Specification
    Joyfully Universal Language for (Inline) Assembly
    Style Guide
    Common Patterns
    List of Known Bugs
    Contributing
    Frequently Asked Questions
```

Some entries are a bit too long, but for a "root menu" it seems ok (could be a little bit more compact)

Now, doing something like this:

```
    Introduction to Smart Contracts
    Installing the Solidity Compiler
    Solidity by Example
    SOLIDITY IN DEPTH
      Layout of a Solidity Source File
      Structure of a Contract
      Types
      Units and Globally Available Variables
      Expressions and Control Structures
      Contracts
      Solidity Assembly
      Miscellaneous
      Solidity v0.5.0 Breaking Changes
    Security Considerations
    Using the compiler
    Contract Metadata
    Application Binary Interface Specification
    Joyfully Universal Language for (Inline) Assembly
    Style Guide
    Common Patterns
    List of Known Bugs
    Contributing
    Frequently Asked Questions
```
would make it worser (too much information visible immediately in root, even if indented).

I need more time/teach-in to have suggestions, currently I just speak when something is clear to me (e.g. it's of general nature).

**Comment by chriseth** [comment]
We can try it out. This issue could also be solved by just grouping things that are currently parallel to "Soldity in Depth" into new sections so that at least the section "Solidity in Depth" is more prominent due to the smaller number of root level items, even if it is not expanded by default.

**Comment by ChrisChinchilla** [comment]
@chriseth and @lazaridiscom I had a pass at this.

Sphinx and the RTD theme don't give a lot of flexibility in menu layout (and I spoke to a few people with the same issue / questions), and there is no ability to have items expanded by default. SO I tried two things that I have in a branch, and here's a gif where you can see my rough ideas in progress.

I added:

- RTD does have these expandable plus icons that let you see the structure of docs without having open them. Added them so you can see how they work.
- With Sphinx and RTD you can create multiple groups of `toctree`s and manually determine the order. While the links under each of the sections I've created in the gif are not final, hopefully you get the idea.

OK, and if you like both or either of these ideas, then I can work on the final changes.

![2018-10-30_15-28-36](https://user-images.githubusercontent.com/42080/47726939-c892d200-dc5b-11e8-96b3-ddb610a22353.gif)

**Comment by franzihei** [comment]
Seems like this got addressed in the meantime. If not feel free to re-open this.
