### ISSUE TITLE
Add some guards around the editor execution in isoltest.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5159]
We should not blindly execute `$EDITOR`. We could check that it is a path to an executable and also inform the user about what is about to be executed. Also, the filename should probably be properly quoted.

**Comment by ekpyron** [comment]
Actually I'm not really convinced by this one and even less sure about it being of "medium severity" in the audit - the respective code will never be executed in production scenarios and will only ever be executed interactively - it makes no sense to use it automatically or without user interaction... If one considers it bad to execute $EDITOR in an interactive testing tool, since its value may have been compromised, by the same logic, we cannot "blindly execute" $DEBUG_PREFIX in scripts/soltest.sh and there's probably a lot more of these cases...

That being said we could of course just not fall back to the environment variable at all in ``isoltest`` and only rely on the ``--editor`` argument, skipping the edit suggestion, if no ``--editor`` argument was given. Also, we could go for platform specific code for actually executing it (although avoiding that was the main reason to use the dubious ``system`` call in the first place).

Actually we could just use ``--editor ${EDITOR}`` in ``isoltest.sh``, since it seems like doing something like that in shell scripts is fine ;-).

**Comment by leonardoalt** [comment]
Is this still relevant?

**Comment by chriseth** [comment]
I agree about the security assessment. We blindly execute "$CC", but we should probably add quotes.

**Comment by chriseth** [comment]
Actually we do not need quotes there.
