### ISSUE TITLE
Add performance tests

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5252]
The compiler should have tests that ensure that the compilation performance stays within reasonable bounds.

**Comment by leonardoalt** [comment]
Should this go to the Backlog?

**Comment by chriseth** [comment]
At least for the optimizer, but probably also for other things. Is there a good way to write performance test so that they do not depend on the load or something like that?

**Comment by axic** [comment]
> The compiler should have tests that ensure that the compilation performance stays within reasonable bounds.

As we can see with the DataFlowAnalyzer (#10405), having such tests would be nice.

**Comment by axic** [comment]
Not sure how could we do this. It would be reasonably simple adding a "compilationTime" line to isoltest for syntax/semantic tests, but that is really prone to machine differences (thinking about developer's machine vs. ci).

**Comment by cameel** [comment]
We might try running them only in CI and always on the machine of the same size so that results are always comparable? I.e. you could still run them locally but there would be a flag to enforce them and the flag would only be set in CI.

CircleCI upgrading their machines might interfere with that though. And from what I have seen running time can vary a lot for the same job even when rerunning on the same commit. And we will have to "recalibrate" the expectations if we switch CI in the future.

**Comment by cameel** [comment]
We could use external tests for this. Unfortunately, such tests would be affected by upstream changes though so we might be better off creating something like a performance report rather than strict tests that pass or fail.

In #12396 I'm adding `time` commands to existing external tests so we'll be able to see the timings in the CI logs. Given the number of runs, however, consistently reviewing all of them would be pretty tedious.

We could instead have a weekly run that gathers all compilation times, creates a short table and posts it to gitter. Maybe even with a diff to the previous version if we store old results somewhere (e.g. as a CI artifact).

Or the report could be committed by CI to a small repo created just for that purpose. I was actually thinking about doing something similar but with IR produced by compiling external tests to be able to observe how the optimizer output changes. This would be especially useful on PRs in relation to `develop`.
