### ISSUE TITLE
"allow-paths" is not used correctly for imports in standard json

### ISSUE THREAD

**Issue by justinmeiners** [ethereum/solidity#5280]
EDIT:

Add option `--base-path` for standard-json CLI such that the read callback reads relative to that.

---

## Description

`--allow-paths` does not work correctly when importing files with standard json. All imports, even relative to the current file are disallowed. 

When using command line flags, instead of `--standard-json` it works just fine.

## Environment

- Compiler version:
   * 0.5.0-develop.2018.10.12+commit.94526b2d.Linux.g++
   * 0.4.25+commit.59dbf8f1.Linux.g++
- Operating system:
   * Linux (Ubuntu 18)

## Steps to Reproduce

Create the following structure in your home directory:
```
bug/
    bug.json
    file.sol
    test.sol
```

file.sol
```
pragma solidity ^0.4.25;
import "./test.sol";
```

test.sol
```
pragma solidity ^0.4.25;
contract Token {
}
```

bug.json
```
{
  "language": "Solidity",
  "sources": {
    "file.sol": {
      "urls": [
        "/home/user/bug/file.sol"
      ]
    }
  },
  "settings": {
    "evmVersion": "byzantium",
    "outputSelection": {
      "*": {
        "*": [
          "abi"
        ]
      }
    }
  }
}
```

Now navigate to the directory above and run the following:
```
cat bug/bug.json | solc --allow-paths /home/user/bug --standard-json
```
The compiler will find `file.sol` just fine, but will complain that `test.sol` is not in an allowed directory.

**Comment by chriseth** [comment]
The difference between standard-json and the old commandline interface is that stardad-json allows you to specify both the internal path of the file and the path of the file "on disk". The internal file is the key of the source map and is called `file.sol` in your input json. When the compiler now sees an `import ./test.sol`, it first resolves it local to the current internal path - which is just the root path, which results in the global path `test.sol`. Since the map does not contain a key `test.sol`, the compiler tries to find it on disk and looks just at the path `test.sol`, which is taken relative to the CWD because it does not start with a slash.

What would work is the following:
```
{
  "language": "Solidity",
  "sources": {
    "contracts/file.sol": {
      "urls": [
        "/home/user/bug/file.sol"
      ]
    }
  },
  "settings": {
    "remappings": ["contracts=/home/user/bug/"],
    "evmVersion": "byzantium",
    "outputSelection": {
      "*": {
        "*": [
          "abi"
        ]
      }
    }
  }
}
```

I'm sorry that this is probably more complicated than you would like. In general, automatic file discovery is unfortunately still suboptimal. The compiler would probably work best if you skipped that altogether and just supplied all the contents of all files in the json input itself.

**Comment by justinmeiners** [comment]
@chriseth  This is definitely tricky. I thought the purpose of standard json was to provide a uniform way to provide input arguments. With relative imports, I was hoping that it could include files which I didn't anticipate including. For example, I don't want to know all the files in a library in order to include one of them. Oh well,

I will follow your advice of discovering all the files that need to be imported and including them in JSON. However, I worry that will end up traversing the import graph as I would expect it to do.

Thanks.

**Comment by chriseth** [comment]
Maybe we could add a flag `--base-path` such that all lookups of the read callback are relative to that path. I think that should work with all setups that do not have complicated package imports.

**Comment by thomasbernardi** [comment]
I ran into this problem too, and I think part of the issue is that it's unclear the significance of the keys in the `sources` map. It's hinted it in the documentation:
> The keys here are the "global" names of the source files

but [this](https://solidity.readthedocs.io/en/v0.6.6/using-the-compiler.html) page does not make it very clear what this concept of a global name is.

For me I really think it was a lack of clarity in the documentation that made it very difficult for me to figure out what the standard-json API was expecting of me: It seems natural that, in this example `file.sol` would be used when compiling other files, for example to find some import `import "./file.sol";`. However, it just doesn't seem intuitive that this key is what is used to find local imports within `file.sol` (I would expect this to be done relative to one of the `urls` I provide for `file.sol`) and I only figured it out when I stuck a bunch of print statements in the compiler to see where it was looking.

So I think it would be useful to put some sort of suggestion that this key is important for file discovery in the standard-json documentation.
