### ISSUE TITLE
Import paths that do not start with `.` or `..` are not treated as global paths and are treated differently when remapping

### ISSUE THREAD

**Issue by justinmeiners** [ethereum/solidity#5281]
## Description

The solidity documentation makes the following claim:

> All path names are treated as absolute paths unless they start with the current . or the parent directory ..

This does not appear to be true from a remapping perspective. This suggests to me that  a remapping such as `/=/some/include/path` should apply to imports which do not start with `.` or `..` For example, `import "file.solc";` These remapping to do not  work on these unprefixed imports.

In version 4.25 empty remappings could modify these imports. For example `=/some/include/path` would successfully remap `import "file.solc";` However, empty remappings seem to apply to everything, including relative imprts that start with `.` This contradicts this claim:
> ... always treated as a path with `/` as directory separator, `.` as the current and `..` as the parent directory.

 I am guessing this is why empty remappings were [removed recently](https://github.com/ethereum/solidity/commit/954d7433bd8c10bce917326f70070077f0cfc165#diff-a8a5760144e03e410389fb0afd20e8c8R148).

### Expected

If I am misinterpreting what the documentation means by "treated as absolute path", there still needs to be a way to remap includes which are not prefixed, without breaking relative imports.

In C and C++ `#include "file.h"` is used to include a file relative, to the current. While `#include <file.h>` would search the header include paths.

Similarly I expect something like `import "./file.sol"` to be a relative import. While `import "file.sol"` would be able to be remapped elsewhere. Currently there appears no way to do this.

Once, again, the solidity documentation seems to suggest this is the behaviour:

> To import a file `x` from the same directory as the current file, use `import "./x" as x;`. If you use `import "x" as x;` instead, a different file could be referenced (in a global “include directory”).

## Environment

Tested on both theses compilers. As I mentioned 0.50 is slightly different in that it disallows relative imports.
- Compiler version:
   * 0.5.0-develop.2018.10.12+commit.94526b2d.Linux.g++
   * 0.4.25+commit.59dbf8f1.Linux.g++
- Operating system:
   * Linux (Ubuntu 18)

### Example 1

This will not remap file.sol elsewhere. It will attempt to include relative to the current file.
```
solc  root.sol /=/some/other/path
```
root.sol
```
import "file.sol";
```

### Example 2

This will remap file.sol elsewhere, despite being a relative import.
```
solc  root.sol =/some/other/path
```
root.sol
```
import "./file.sol";
```

**Comment by chriseth** [comment]
I fear that trying to remap `"/"` to something is just as little helpful as trying to remap `""`. In general, remappings only really work with actual directories (and the "root" is not really a directory).
Importing files without context is unfortunately not supported. If you move your file into a directory, the remapping would work:

If you want to import a file called `file.h` from a library called `fileLib`, just use `import "fileLib/file.h"` and then use the remapping to point to the correct directory: `fileLib=/usr/local/mylibs/`.

We did not add a feature to just search for imported files in some random directories in the way a C compiler would do it because - at least to me - where the actual file in the end comes from is not clear in such a setting. `import "x.h"` and `import "g.h"` could import from different directories. If you use `import "lib1/x.h"` and `import "lib2/g.h"` it at least gets a little clearer where to look.

**Comment by justinmeiners** [comment]
@chriseth that is reasonable, although the confusing of where an import is happening hasn't been an issue for C. Could the documentation be updated to specify this behaviour?

**Comment by cameel** [comment]
This seems related to #11036.

So it appears that an empty path, `/` and paths starting with `./` and `../` are not remappable on purpose? I think that an attempt to remap them should not be ignored and result in an error instead (preferably with a message explaining why this is the case).

**Comment by chriseth** [comment]
@cameel I would say remappings are applied after removal of `.` and `..` from the path.

**Comment by cameel** [comment]
OK. That's exactly what happens now (i.e. it kinda looks to the user as if `./` and `../` are not remappable but that's just because they're no longer in the path that the remapping is operating on). But I think that's all the more reason to report an error when user tries to remap them.

Also, I wonder if the current behavior is actually useful in practice. In normal circumstances it seems redundant. For example if you do `/a/b=/x/y` then you change `import "/a/b/c.sol"` to `import "/x/y/c.sol"`. If `d.sol` then contains `import "./d.sol"`, the compiler will look for `d.sol` in `/x/y/` (because that's where `c.sol` is physically located) so the remapping does not play any role here.

The only thing you can achieve by remapping the expanded path is the unintuitive behavior where `import "./d.sol"` ends up importing a file that's not in the same directory as `c.sol`. This would happen for example if you used `/a/b=/x/y /x/y=/a/b` in the example above.

For that reason I think it would be better to just completely forbid remapping `.` and `..`. To me it looks like its main use would be writing underhanded code :)

**Comment by cameel** [comment]
I'm closing this since the documentation has been updated to precisely describe the behavior of relative and direct imports: [Import Path Resolution > Imports](https://docs.soliditylang.org/en/latest/path-resolution.html#imports).

After working on the import paths I see that the current behavior does have its merits. There are things that maybe should be improved but better to create new issues for them, describing exactly the part we'd want to change.
