### ISSUE TITLE
[CLI] Increase Coverage of CommandlineInterface.cpp

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5303]

**Comment by leonardoalt** [comment]
Are we still doing this?

**Comment by chriseth** [comment]
Yes!

**Comment by chriseth** [comment]
I think coverage should be much higher now that we have more commandline tests.

**Comment by axic** [comment]
We don't have proper coverage numbers, but we do have 134 tests.

**Comment by axic** [comment]
Should we close this?

**Comment by cameel** [comment]
I think that many options/option combinations are not being tested. At least that's the impression I got when I was adding/changing stuff in it. Still, those tests are usually just simple smoke tests because they just expect the output to match 1:1 so it's debatable how much of this really needs to be explicitly tested. A coverage report would be helpful here.
