### ISSUE TITLE
`uint` variables shouldn't allow negative prefix

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#533]
1) This compiles without error:

```
uint a;
a = a * -a;
```

or

```
uint a;
a = 1 * -a;
```

2) This properly throws an error:

```
uint a;
a = a * -1;
```

The error is:

```
Untitled1:24:13: Error: Operator * not compatible with types uint256 and int_const -1
        a = a * -1;
            ^----^
```

**Comment by axic** [comment]
A more complex example for 1): 

```
function wrong(uint a) returns (uint) {
        return 1 * -a;
    }
```

When passing `1` as an input, this will return `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`, which is -1 in two's complement (`int`).

**Comment by VoR0220** [comment]
@chriseth I think he raises a good point here. We should disallow negative unary operations on a uint.

**Comment by chriseth** [comment]
Sorry, but I don't really see the problem :-)
Forget about two's complement, this is just how it is represented internally, but the math should work out even without having to think about two's complement. Here is how it works:

Operations on variables of `uint` are performed in the ring mod `2**256`. Furthermore, if `x` and `y` are `uint` variables, then certainly something like `x-y` should be possible (and is just computed mod `2**256`). Since `-a` is just a short hand for `0-a`, I don't see why it should be disallowed. Since `0` is equivalent to `2**256`, is is just natural that `-1` is the same as `2**256-1`, which is `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`.

**Comment by VoR0220** [comment]
then I suppose we should call this closed.

**Comment by chriseth** [comment]
Folloing the protocol, @axic should close this.

**Comment by VoR0220** [comment]
okay

**Comment by axic** [comment]
@chriseth basically it just works as ho
