### ISSUE TITLE
Solidity for loop over a huge amount of data failed.

### ISSUE THREAD

**Issue by hello2mao** [ethereum/solidity#5354]
## Description

Solidity for loop over a huge amount of data failed.

## Environment

- Compiler version::0.4.25
- Framework/IDE (e.g. Truffle or Remix):Remix
- EVM execution environment / backend / blockchain client:POA Geth
- Operating system:MacOS

## Steps to Reproduce
case_20000() success.
case_40000() failed.
```
contract Test {
    
    uint[] public _storage;
   
    // this is success. 
    function case_20000()
    public
    {
        for (uint i = 0; i < 20000; i++) {
            _storage.push(i);
        }
    }
    
     // this is failed.
    function case_40000()
    public
    {
        for (uint i = 0; i < 40000; i++) {
            _storage.push(i);
        }
    }
}
```

**Comment by erak** [comment]
@hello2mao Could you please provide the output of Remix' console after the transaction has failed? This most likely happened because you ran out of gas. On a fresh Remix session using Javascript VM and an initial gas limit of 3000000, ``case_20000`` uses too much gas already. Remix has an analysis feature that warns about infinite gas costs:

_Gas requirement of function Test.case_20000() high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage)_

Does this answer your question?

**Comment by hello2mao** [comment]
@bit-shift Thank you. Increase block gas limit solves this problem.
