### ISSUE TITLE
[Yul] Make variable suffixes an official feature of YulString/optimizer/implementation

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5372]
Extension of https://github.com/ethereum/solidity/issues/5074:

During optimization, we often need to generate unique names. Currently, this adds decimal suffixes to string names. This feature proposes to promote the suffixes to being an official part of the name, such that names are pairs of string prefixes and optional integer suffixes (which are not turned into strings).

This way, we can remove suffixes again if they turn out not to be necessary anymore or we can re-arrange the integers. The name dispenser should then have separate counters for each prefix as @ekpyron suggested.

**Comment by robechun** [comment]
I'd like to try and work on this!

**Comment by chriseth** [comment]
Please do! Note that the `YulString` class already has a hash and an ID now. I would hope to still have a class that is easy to pass by value.

**Comment by robechun** [comment]
Couple questions:

1) You indicate the suffixes shouldn't be turned into strings; a way to differentiate between different ID's--then-- would be adding a ```size_t suffix``` into the ```Handle``` struct. This way, we could have the ```YulString.str()``` function append the suffix if say-- it's not 0. However, this seems to be contrasting to @ekpyron's comment in [#5365](https://github.com/ethereum/solidity/pull/5365) where he wants one ID to allow multiple suffixes. Furthermore, this would have a memory overhead per YulString vs per YulString ID as ekpyron suggests. If you could clarify this for me a little bit, I'd appreciate it.

2) I was curious as to why NameDispenser creates at least 1 extra YulString -- which I'm understanding  that it stays alive in the YulStringRepository-- during the ```newName()``` process. Isn't this an inefficiency?

3) I found a comment in YulString.h saying the hash function can be replaced for a better one. I looked up xxhash64 online and found that there were libraries for it. Were you planning on importing one of them & using it?

**Comment by chriseth** [comment]
I think it would be better to add the suffix ID to the StringRepository instead of to the handle or YulString class - if that is possible.

If you can find a non-invasive method to avoid the additional string created by NameDispenser, then please feel free to submit a PR!

Whether we should use a different hash function or not should be evaluated by using a profiler, feel free to do so, but please try to use a more or less realistic setting, like `test/libyul/yulOptimizerTests/fullSuite/medium.yul`.

**Comment by ekpyron** [comment]
My findings regarding the issue are the following:

When adding suffices we have to be careful to have correct behavior with suffices supplied in string form, e.g. ``YulString("a_1",0) == YulString("a",1)``. This affects hash computation, parsing of user-supplied identifiers and comparison operations.

The least performance-degrading option that I found for this is to parse the suffix for *all* YulString's during creation - it can be done simultanously with hashing the string (we already have to walk the string anyways for hashing and we can hash from back to front, simultanously checking for a suffix).

This means that a new suffix for ``YulString("a_1")`` would be ``YulString("a",2)``, not ``YulString("a_1",1)``.

Given that, in ``NameDispenser`` we *could* just have a map from prefix to the highest used suffix. However, that will not result in the nicest suffices (if we have a user supplied identifier "a_99", then the next suffix for "a" will be "a_100", not "a_1", etc.) - a map from prefixes to a set of used suffices is another option and allows for "tighter" suffix allocation and surprisingly doesn't seem to perform much worse (at least for the fullSuite test cases - there may be scaling issues for more complex cases).

A lot of optimization is required to not actually *loose* performance compared to the current version, so maybe we should evaluate how important nicer/tighter suffices actually are.

If we still want them, we have to consider a lot of details, if we parse all strings with suffices, e.g. we have to limit the number of digits considered a suffix to prevent overflows (if we start at 1 with 64-bit suffices we don't really have to care, but if we parse user-supplied identifiers with suffix, we can easily run into overflow problems and we have to parse an identifier like ``a_999999999999999999999999999`` correctly).

Profiling seems to be absolutely necessary here, since a lot of seemingly good options will actually be worse in performance in practice (and a lot don't make much of a difference). Maybe we should add a first class profiling tool or allow ``yulOpti`` to be run the full suite non-interactively for profiling purposes? For profiling we have to be careful not to run the optimization multiple times without resetting the repository, since the first run will behave differently than subsequent ones due to the YulStringRepository being static.

Different hash functions do have an effect, but not a large one and we have to consider that the more advanced hash functions might perform *worse* on asm.js/emscripten (e.g. simple 32-bit hashes are better for asm.js, but noticable worse for native 64-bit systems).

**Comment by axic** [comment]
@ekpyron @chriseth what is the status of this issue now, given we have dots in identifiers?

I've tried to read the intro, but it is unclear to me whether this is a language feature, an implementation detail, or an optimiser feature. Admittedly haven't read the little essay from @ekpyron.

**Comment by ekpyron** [comment]
Well, we still don't know how well the YulStringRepository stuff reports and whether name dispensing could be more efficient than it is... I'm not particularly sure this issue itself provides that much value, though. It's one option for doing things differently, but we currently just don't know if it'd be better or worse than what we do now...

**Comment by axic** [comment]
So is this changing the language or an implementation detail?

**Comment by ekpyron** [comment]
Mostly implementation detail, probably exclusively.
