### ISSUE TITLE
Assembly: invalid value assignment can cause misleading error message

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#538]
I get `Compiler error: Stack too deep, try removing local variables.` on the following:

```
contract A {
    function a() returns (uint b) {
        assembly {
            =: b
        }
    }
}
```

While it seems like a useless/broken code, shouldn't it raise a proper error message as many other stack manipulating opcodes do?

**Comment by chriseth** [comment]
This might also be useful code: Inline assembly generally ignores stack height problems, so if you want, you can mess around with the stack. The reason this error is produced here is because we use a new assembly context for the inline assembly block and thus the stack height is actually zero at the start.

The way to fix this is to either ignore the stack height in this situation or not create a new assembly context (which will also solve the problem that functions cannot be referenced).
