### ISSUE TITLE
Rename AssemblyStack to YulStack

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5474]
From https://github.com/ethereum/solidity/pull/2233#discussion_r119631657

Not sure it is still relevant. @chriseth close if not.

**Comment by axic** [comment]
@ekpyron @chriseth I don't think `BackendStack` is an appropriate name anymore. Could consider `YulStack` or just stay with `AssemblyStack`.

**Comment by axic** [comment]
I think a better name would be `YulCompiler`.

**Comment by axic** [comment]
Since this was moved to `libyul` I'd suggest to go with either `YulCompiler`, `YulStack`, `CompilerStack`.

**Comment by s0sharma** [comment]
Hi, I would like to work on this, can you elaborate exactly what I have to do?

**Comment by cameel** [comment]
Sure, the class is defined in [`libyul/AssemblyStack.h`](https://github.com/ethereum/solidity/blob/develop/libyul/AssemblyStack.h). You just have to change its name there and update all references to it in other files. Remember to also rename variables it's assigned to and update comments that mention it. It might also be used in some file names. Overall this is just a simple refactor and should not change compiler output in any way.

Just to make sure this is ready to be worked on - @axic @chriseth can we go with `YulStack` or would you prefer one of the other names now? Also, since this issue is pretty old - is there anything more that should be done here? Any other classes or other stuff that should be renamed to match?

**Comment by chriseth** [comment]
I think `YulStack` is a good name that also sets it apart from evmasm.

**Comment by JoshIQui** [comment]
Does this change still need to be implemented. If so, I could take a look at it. I would just need a few pointers on where I should be looking for changes to make.

**Comment by chriseth** [comment]
Sure! Take a look at the file `AssemblyStack.h` - the file and the main class inside it should be renamed `YulStack`.

**Comment by JoshIQui** [comment]
I just created the pull request about 40 minutes ago. It automatically sends a message here, but I'm not 100% sure if it gives the group a notification. So, here I am, sending a corresponding message.

**Comment by cameel** [comment]
@jiq4449 Thanks! Don't worry, we have notifications. We're just swamped with PRs right now so it sometimes takes a moment before someone can take a look.
