### ISSUE TITLE
ABIEncoderV2 + external = UnimplementedFeatureError

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#5479]
I have solidity code that contains methods which rely on the ABIEncoderV2 to get input structs.

If the method is public (input stored in memory) everything works well. However, if the method is external (input stored in calldata) then the compiler gives me a "NotImplementedFeatureError"

Minimal reproducible code:

    pragma solidity ^0.4.25;
    pragma experimental ABIEncoderV2;
    contract Test {
        event MyEvent(uint256 a);
        struct MyStruct { uint256 a; }
        function broadcast(MyStruct _value) external { emit MyEvent(_value.a); }
    }

Error visible on remix with 0.4.25+commit.59dbf8f1.Emscripten.clang

**Comment by axic** [comment]
```
Unimplemented feature:
/Users/alex/Projects/solidity/libsolidity/codegen/ABIFunctions.cpp(1283): Throw in function std::__1::string dev::solidity::ABIFunctions::abiDecodingFunctionStruct(const dev::solidity::StructType &, bool)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::UnimplementedFeatureError>
std::exception::what: 
[dev::tag_comment*] = 
```

I think this is about decoding from calldata for structs is not implemented.

(The feature is also missing in 0.5.0.)

**Comment by chriseth** [comment]
The problem is that calldata structs are not a defined concept in Solidity. We might want to disallow calldata structs at the type checker level.

**Comment by gitpusha** [comment]
Hi @chriseth ,

I started using `ABIEncoderV2` yesterday in order to make use of `structs` in my function calls and to emit them or elements of them in events.

Now I also got a `UnimplementedFeatureError` for the first time. 

Is it still the case that `calldata structs` are not a defined concept in Solidity? (the compiler did not warn about this).

I was able to circumvent this compile error by marking all my functions that accept the `struct` as `public` and data location `memory`. Before, I thought this was only necessary, if I wanted to modify the struct in the function block, but apparently it always needs to be in `memory`, even if its element values are only `read`.

One strange thing is that now it compiles, even though I still have many solidity interface functions that are all `external` and defined with `Struct calldata _struct` as a param. I also inherit from the `interface` and `override` its methods with `public override`. 

Is this all intended behaviour by the compiler?

Edit for explicitness:

This compiles (`ExecClaim` is a `struct`):

```
function exec(ExecClaim calldata _execClaim, bytes32 _execClaimHash) external;
```

This also compiles (`ActionPayload` is a `struct`):

```
function action(bytes calldata _actionPayload) external payable override virtual {
    (ActionPayload memory _p) = abi.decode(_actionPayload[4:], (ActionPayload));
        action(_p);
}
```
