### ISSUE TITLE
Suggestion: sign solc binaries for post-download verification

### ISSUE THREAD

**Issue by weijiekoh** [ethereum/solidity#5627]
It would be great if the binary releases of the Solidity compiler (https://github.com/ethereum/solidity/releases) could be signed with GPG, or at least had their SHA256 checksums published somewhere. This would add a level of assurance and security to developers' smart contract development toolchains.

**Comment by chriseth** [comment]
Thanks for your suggestion! Could you explain the possible attack scenarios a bit more in detail, please? Key distribution is always hard. We might be able to use a blockchain to improve that, and I think there even is an open issue about storing the hashes of the compiler binaries in ENS or something like that. It would only help with a specific binary, but at least you can verify the compilation result using the "trusted" binary.

**Comment by weijiekoh** [comment]
No problem. The attack scenarios include:

1) Github gets hacked
2) a solc developer's account or machine gets hacked
3) someone creates a phishing site that looks like the solc download page

... leading to users downloading infected binaries which in turn generate backdoored contracts.

Additional scenarios can be gleaned from projects which have thought through security pretty well, such as Tails: https://tails.boum.org/contribute/design/verification_extension/

Key distribution is certainly hard. Even if hashes are stored on an immutable ledger, the question remains: is the address which stores those hashes legit? Maybe the good o' web-of-trust model would work - GPG key signing parties to establish trust in the official solc GPG key, and use that key to create signatures of each release.

**Comment by lookfirst** [comment]
It would make me feel better if the follow steps were followed:

1. Publish sha256 hashes of the binaries that are produced during the CI build, so that downloads can be verified.
2. Require that all commits are signed. ![image](https://user-images.githubusercontent.com/85355/49915502-95816680-fec8-11e8-85fc-408d54cb4174.png)
3. Enforce the rules even for administrators. 
![image](https://user-images.githubusercontent.com/85355/49915555-d5e0e480-fec8-11e8-8bbf-b51a71c21b53.png)
4. In terms of 'key management' for signed binaries, that is pretty easy with the GPG keyserver and a key signing party.

**Comment by chriseth** [comment]
Here it is: https://github.com/ethereum/solidity/issues/628

**Comment by chriseth** [comment]
I think the discussion can continue as part of #628
