### ISSUE TITLE
[Tests] clean up commandline tests

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#5640]
The auxiliary files for the commandline tests should all be moved such that we have one directory per test, each containing multiple files. Also, the json and non-json tests could be combined to share the same form.

**Comment by androlo** [comment]
up for grabs?

**Comment by androlo** [comment]
how do you feel about adding exit and stdout to the input file and turn into one single json file?

**Comment by chriseth** [comment]
@androlo yes, please feel free to work on it! The problem is that we have json tests now that required stdin to be redirected and "regular" tests that work on input files. Combining everything into a single file sounds like a good idea, but then it would be great to have a single script that could auto-fix the expectations.

**Comment by androlo** [comment]
I have looked in the script. There are two relevant sections - "general JSON tests" and "standard JSON tests". I could port all of the tests to standard json format and move into folders.

I guess including the json result in the input json file doesn't really make sense since it's just a bash script. i thought maybe it used a test runner that parsed the json files, and i wasn't even aware of the `--standard-json` flag.

just to be sure: do you want them all on `--standard-json` format, or do you want .sol files as well so that each test has a regular and a standard json version?

**Comment by androlo** [comment]
Right now I have moved them into folders:

```
- cmdlineTests
  - standard_json
    - wrong_key_metadata
      exit
      input.json
      output.json
    - ...
  - regular_sol
    - data_storage
      args
      contracts.json
      output
    - ...
```
All json tests has `exit`, `input.json`, and `output.json`.

All regular tests has a contract file named `contracts.json`, and `args`, `output`, `exit`, `err` files depending on need (what was already there).

The script has been updated to work with folders instead of files.

**Comment by androlo** [comment]
Also is it ok that I move functions to the top, and put the simpler tests (bad input, stdin, etc.) before the bigger ones that compiles code. Since it exits on failure.

I already did this...

**Comment by chriseth** [comment]
Good work! I think it would make it easier to add new tests by not requiring standard-json format, because there you need to escape input code and so on, and it is much harder to read.

Do you have each test in its own directory?

Can you make a pull request?

**Comment by androlo** [comment]
yes each test is in its own folder, and i can make pr. just wanted to make sure i was on the right track. i'll do it tomorrow.
