### ISSUE TITLE
solc.compileStandardWrapper passes mutated strings to its callback

### ISSUE THREAD

**Issue by coventry** [ethereum/solidity#5708]
When I instrument [the callback](https://github.com/smartcontractkit/chainlink/blob/4b35cabb939d7296bbc1aa5a678ca37e1fe953fd/solidity/app/compile.js#L45) used in [this invocation of `compileStandardWrapper`](https://github.com/smartcontractkit/chainlink/blob/4b35cabb939d7296bbc1aa5a678ca37e1fe953fd/solidity/app/compile.js#L30), and use it to run [this test file](https://github.com/smartcontractkit/chainlink/blob/4ef9addc8c410f31403c570070ce4382809e5b47/examples/echo_server/test/RunLog_test.js), which compiles [this contract](https://github.com/smartcontractkit/chainlink/blob/4ef9addc8c410f31403c570070ce4382809e5b47/examples/echo_server/contracts/RunLog.sol) via the above invocation of `compileStandardWrapper`, I find that the `import "../../../solidity/contracts/Chainlinked.sol"` is resulting in `solidity/contracts/Chainlinked.sol` being passed to the callback. I.e., the parent-directory elements of the path, `../../../` are stripped off.

Is this intended behavior? It makes it tricky to use relative paths like that.

**Comment by chriseth** [comment]
I'm pretty sure this is expected behaviour. It is unrelated to solc-js or callbacks in general and is a property of the internal path system of the Solidity compiler. The `sources` map in https://github.com/smartcontractkit/chainlink/blob/4b35cabb939d7296bbc1aa5a678ca37e1fe953fd/solidity/app/compile.js#L20 sets up full paths for use inside the compiler and `..` is always relative to that path, and not to the path on your system. So if you just use `sources: { "RunLog.sol": { ... } }`, then the file will be at the root folder of the virtual filesystem provided to the compiler. If you want `../../..` to work properly, you have to use `sources: { "examples/echo_server/contracts/RunLog.sol": { ... } }`.

Hope that helps!

**Comment by axic** [comment]
@coventry what do you think of @chriseth's answer?

**Comment by axic** [comment]
@coventry please comment if the answer was unsatisfactory.
