### ISSUE TITLE
Is it possible to remove Solidity compiler version statement

### ISSUE THREAD

**Issue by sowmyakannan** [ethereum/solidity#5724]
Hi All,

After upgrading truffle and solc to the latest versions, I upgraded openzeppelin-solidity library too, however contracts now dont compile because truffle 5.0.0 uses solc 0.5.2 whereas openzeppelin-solidity relies on solc version 0.4.24.  Our contracts inherit from these contracts in the library and hence inorder to make our contracts compile we either change the compiler version used by the contracts in the library file directly by changing pragma solidity ^0.5.2; (which is not a great way at all) or downgrade truffle and solc.

My point is even in future releases this might become an issue. Is it possible to not have the compiler version statement "pragma solidity ^0.5.2;" at the beginning of each Solidity program similar to how its done in Java. In Java we do not specify the compiler version in each and every program, instead we update jdk. 

This would make it easier to keep track of versions of various dependencies. 

That was my 2 cents on this.
Thanks.

**Comment by startgeek** [comment]
exacly same problem which drives me crazy these three constantly changing version and nothing is compatible .

**Comment by chriseth** [comment]
Because it is very young and we do not want to carry on too much baggage, we are making breaking changes to the compiler. Because of that, users are advised to use these pragmas. You can use pragmas like `pragma Solidity >=0.4.0`, which works for both 0.4.0 and 0.5.0.

In any case, I think this is rather related to how a feature of the compiler is best used and not about the feature itself.

Because of that I'm closing this issue. Please feel free to re-open if you think otherwise.
