### ISSUE TITLE
Compiler errors/warnings should contain an unambiguous error code 

### ISSUE THREAD

**Issue by flantony** [ethereum/solidity#5819]
Edited by @chriseth: All errors and warnings should contain a unique error code. This cannot simply be done by looking at the error message, because it is more specific (contains names of types, etc). It should be done based on the position of the error check in the code, although the codes should also be consistent  across versions.

Once this is done, we can easily implement https://github.com/ethereum/solidity/issues/4383

----

I'm using the compiler via JSON - API. The compiler reports issues in the following way (from the 0.5.2 documentation):
```
 errors: [
    {
      sourceLocation: {
        file: "sourceFile.sol",
        start: 0,
        end: 100
      ],
      type: "TypeError",
      component: "general",
      severity: "error",
      message: "Invalid keyword"
      formattedMessage: "sourceFile.sol:100: Invalid keyword"
    }
  ]
```
Currently, the cause of the error is only identifiable by the "message"  field.  I propose to add an additional field 'code' to the error output, that unambiguously identifies the cause of the issue like this:
```
 errors: [
    {
      sourceLocation: {
        file: "sourceFile.sol",
        start: 0,
        end: 100
      ],
      type: "TypeError",
      component: "general",
      severity: "error",
      code: "207001",
      message: "Invalid keyword"
      formattedMessage: "sourceFile.sol:100: Invalid keyword"
    }
  ]
```
The main reason is that while the cause of error is more or less stable the "message" might change more frequently.

I am currently writing code to us compiler errors/warnings to automatically fix the issue that caused the error in the first place. At the moment I rely on parsing the messages, which is error-prone and sometimes ambiguous. A unique code that identifies the issue would be prefereable and future proof. 

A possible pattern could be like ABBCCC
where: 
A: severity (0:info, 1:warning, 2:error ...) 
B: type (01: JSONError, 02: IOError, 03: ParseError ...)
C: identifier (001: VAR_KEYWORD_DISSALLOWED, 002: THROW_KEYWORD_DISALLOWED ... )  

I don't see any backwards compatibility issues here since existing behaviour is not changed.

**Comment by chriseth** [comment]
Sounds good!

**Comment by a3d4** [comment]
I'm looking at this.

**Comment by christianparpart** [comment]
> I'm looking at this.

Hey @a3d4, do you have a branch to share already?

**Comment by a3d4** [comment]
@christianparpart 
Not yet. Right now I'm working on a Python script which would find and tag every error reporting.

**Comment by axic** [comment]
It would be nice to list the use cases for this. Is it for LSP? Someone mentioned it helps in test coverage?

I think if we want to introduce error codes we should take example from existing compilers:
- rustc -- has a single incrementing list (https://doc.rust-lang.org/error-index.html)
- msvc -- has categories and ranges (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/c-cpp-build-errors?view=vs-2019)
- c# -- a mix between incrementing and ranges (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/)
- gcc and clang doesn't seem to have error codes

In the issue above the proposals were:
a) a numbering scheme
b) based on file + line number in the compiler?

(Sidenote: the error codes in Rust are nice because each of them has a "man" entry. However, this approach I think requires a lot of attention to detail to be useful.)

**Comment by chriseth** [comment]
File and line numbers are not consistent. I would prefer categories (based on the error types we currently have - TypeError, DeclarationError, Warning, ...) and then numbers that increment. I would not expect too many conflicts and shorter numbers are better than random e.g. 8-digit codes.

Use-cases:
 - track that we have at least one syntax test for each error 
 - people are compiling lists with error messages and recommended solutions: https://github.com/CJ42/Solidity-Compiler-Debug-List

**Comment by axic** [comment]
But are we creating a
a) single number for each new entry, and once it is removed, the number is dropped
b) or trying to assign the same number to the same semantic errors

To me this is a key question to be answered, because it affects usability and design the most.

**Comment by ekpyron** [comment]
The problem is that those two use cases impose different numbering schemes...
For tracking tests it makes sense to have a number for each actual error emission in the code, whereas for compiling lists of recommended solutions the number should rather be based on the semantics on the error. example: ``"Identifier already declared."`` in NameAndTypeResolver.cpp occurs twice - is this the same error code or two distinct errors?

Similarly, we should think about errors for which we generate the message (although that can be considered an implementation detail).

**Comment by chriseth** [comment]
Duplicate: https://github.com/ethereum/solidity/issues/3202 (shows use-case by IDEs)

**Comment by chriseth** [comment]
@ekpyron this example is two different errors - the one happens during inheritance, the other not.

**Comment by ekpyron** [comment]
Yeah, it may be that that issue doesn't occur in practice or can be avoided.

**Comment by a3d4** [comment]
#8680 introduces a mechanism of error unique identification, and applies it to most of the cases. Still, not all errors have their own ids, several special cases need to be addressed.

Besides, the ids are not used yet.

**Comment by chriseth** [comment]
@a3d4 is this still in progress or can it be closed?
