### ISSUE TITLE
Verify that there are no more obsolete boost workarounds in the code.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#5823]
We have a reimplementation of ``weakly_canonical`` in ``libdevcoce/CommonIO`` for backwards compatibility with boost < 1.60 - but since we now require boost >= 1.65 anyways, we can remove that and use the (superious) boost version directly.

**Comment by axic** [comment]
There are at least two more workarounds:
- https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.h#L60
- `boost_multiprecision_number_compare_bug_workaround.hpp` in libdevcore

**Comment by ekpyron** [comment]
Extended scope to all boost workarounds.

**Comment by ekpyron** [comment]
There will probably be some overlap with the C++17 PR that is definitely to be expected soon :-) - e.g. with C++17 we even have ``std::filesystem::weakly_canonical`` and should prefer that.

**Comment by axic** [comment]
I'd prefer to get the boost simplifications merged first.

**Comment by ekpyron** [comment]
I'll keep this open for now, since I think there are more workarounds - if anybody double-checks, we can close it, otherwise I'll look into it next month.
EDIT: unassigning the issue since I changed its scope.

**Comment by ekpyron** [comment]
Just saw one boost < 1.59 workaround left in ``test/boostTest.cpp``.

**Comment by bshastry** [comment]
Hmm... This could be related to the ossfuzz build CI failure in #7010

**Comment by axic** [comment]
Here's one more workaround for <1.55: https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L55

And a boost test workaround for <1.59: https://github.com/ethereum/solidity/blob/develop/test/boostTest.cpp#L52

And three more workaround in the `RuleList`:

1) Fixed in 1.64 (we require >=1.65):
https://github.com/ethereum/solidity/blob/develop/libevmasm/RuleList.h#L50-L55

2) I'm not sure what version these appeared in or what bug they have produced
https://github.com/ethereum/solidity/blob/develop/libevmasm/RuleList.h#L40-L48

**Comment by axic** [comment]
And a boost test workaround for <1.59: https://github.com/ethereum/solidity/blob/develop/test/boostTest.cpp#L52

**Comment by axic** [comment]
And three more workaround in the `RuleList`:

1) Fixed in 1.64 (we require >=1.65):
https://github.com/ethereum/solidity/blob/develop/libevmasm/RuleList.h#L50-L55

2) I'm not sure what version these appeared in or what bug they have produced
https://github.com/ethereum/solidity/blob/develop/libevmasm/RuleList.h#L40-L48

**Comment by axic** [comment]
The only workarounds seem to be in `RuleList.h` for multiprecision div/mod/shl.

@ekpyron still want to track it here? Can those be removed?

**Comment by ekpyron** [comment]
Maybe we better not remove those - it'd be quite bad if there is any situation in which they'd be needed and we removed them. If those are the only ones I'd say we can close this.

**Comment by axic** [comment]
Agree, that's why I didn't touch them last time :wink:

I think those are the only ones left. Will remove them with #3851.
