### ISSUE TITLE
Use C++17

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5913]
I thought @christianparpart had an issue for this already.

**Comment by axic** [comment]
Unfortunately it seems that CVC4 (at least the one using on CircleCI) is not C++17 compatible:
```
In file included from /usr/include/cvc4/expr/uninterpreted_constant.h:23:0,
                 from /usr/include/cvc4/expr/expr.h:55,
                 from /usr/include/cvc4/expr/datatype.h:36,
                 from /usr/include/cvc4/cvc4.h:23,
                 from /root/project/libsolidity/formal/CVC4Interface.h:30,
                 from /root/project/libsolidity/formal/SMTPortfolio.cpp:24:
/usr/include/cvc4/expr/type.h:397:42: error: ISO C++1z does not allow dynamic exception specifications
   BooleanType(const Type& type = Type()) throw(IllegalArgumentException);
                                          ^~~~~
/usr/include/cvc4/expr/type.h:408:42: error: ISO C++1z does not allow dynamic exception specifications
   IntegerType(const Type& type = Type()) throw(IllegalArgumentException);
                                          ^~~~~
```

**Comment by christianparpart** [comment]
I had a pretty for this already, which I closed because the diff was trivial and the only blocker had been emscripten, which shouldn't be one anymore /cc @ekpyron

**Comment by ekpyron** [comment]
I think this problem might be solved in newer versions of CVC4 - the current version 1.6 doesn't use these problematic exception specifications at least. I haven't checked that the build works with it yet, though.

**Comment by ekpyron** [comment]
That's the commit in CVC4: https://github.com/CVC4/CVC4/commit/9ee67c0d1180c7cf85fb648b57bb47100db3d633#diff-a242743d56fdf976402ac6ac36162b11
Unfortunately it's only in 1.6 and that will only be part of Ubunutu disco (19.04).

**Comment by axic** [comment]
The above version is what we have on CI.

**Comment by ekpyron** [comment]
As a reminder: if we move to C++17, we effectively drop support for Debian older than Buster (which is due to be released this year). Personally I'm fine with both just accepting to break Debian stable or with waiting for the next Debian release, since it's not too far away.

Regarding CVC4 and Z3, @leonardoalt and I agreed that moving forward with #5652 might make sense, i.e. maintaining static versions of Z3 (and possibly CVC4) in our own Ubuntu PPAs and then to just use those for our tests and release builds.

**Comment by ekpyron** [comment]
This is done in #7205
