### ISSUE TITLE
Japanese Docs translation

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethereum/solidity#5918]
This issue is to track the progress of the Japanese translation of the Solidity documentation.

It includes the GitHub usernames of all involved, and links to any issues or pull requests related to the French translation.

All translation efforts in progress from this date are pinned to commit 
https://github.com/ethereum/solidity/commit/bb46e91677a4d9b5ef4e620b9190be7569e27264

## Contributors

Based on comments in pull requests and issues, and other conversations. If you also want to be involved, please comment below.

@akira-19, @NoCtrlZ, @taizo-kato 

## Fork

https://github.com/akira-19/solidity

**Comment by akira-19** [comment]
@ChrisChinchilla Thank you. I just started translating. I'm also going to ask the Japanese community to help this project to make the translation better.

**Comment by ChrisChinchilla** [comment]
@akira-19 Great! So I can help you more and connect you to other Solidity translators, can you email me your email address? Or you can also ping me on https://gitter.im/ethereum/documentation

**Comment by akira-19** [comment]
@ChrisChinchilla Hi, I found a couple of people who are going to help the translation. So can you add @NoCtrlZ and @taizo-kato as contributors? And I think they might want to join gitter documentation room.

**Comment by ChrisChinchilla** [comment]
@akira-19 Excellent! I'll add them here, but for creating the translation, you create a fork of this repo, so you can add whoever you like to that. When you have that fork, let me know 👍.

**Comment by akira-19** [comment]
@ChrisChinchilla Thank you. The fork is here. https://github.com/akira-19/solidity

**Comment by shunMB** [comment]
@ChrisChinchilla and @akira-19 Hi, can I help this translation? If possible, let me know.

**Comment by ChrisChinchilla** [comment]
@shunMB From my perspective yes, but it's up to @akira-19 mostly :)

**Comment by shunMB** [comment]
@ChrisChinchilla Thank you! @akira-19 I'm waiting for your reply ;)

**Comment by akira-19** [comment]
@shunMB Thank you for joining us! We have slack workspace. Can you join this? https://join.slack.com/t/solidity-translation/shared_invite/enQtNTk2NTYwNzcwOTQ2LTlkMzY1MGJiZmM4OWE1ZTc4MjVlYzFiNDkxZTZiZjhmNzhmNGRlNGExM2NiZjFlM2JmMWYzYjU4NzdhZTM1YWE

**Comment by shunMB** [comment]
@akira-19 Sure! I just joined the workspace. Thanks!

**Comment by ChrisChinchilla** [comment]
Amazing! 👏

You can also join us in the Ethereum documentation Gitter channel if you want to ;)

https://gitter.im/ethereum/documentation

**Comment by ashWhiteHat** [comment]
Thank you for the invitation!

2019年4月23日(火) 12:07 Chris Chinchilla <notifications@github.com>:

**Comment by akira-19** [comment]
@ChrisChinchilla We completed the translation. Can I create pull request to develop branch? We made a directory "docs_jp" on the same level as "docs". Would it be ok with that?

**Comment by chriseth** [comment]
@axira-19 that's wonderful! How up-to-date is the translation? My main concerns about not merging right away are about versions: The version number in the japanese translation should reflect the actual state of the translation and not of the develop branch. Because of that, you would at least need to modify the part of `conf.py` that auto-discovers the version and maybe we should find a more sustainable solution to that problem.

**Comment by akira-19** [comment]
@ChrisChinchilla We translated based on version 0.5.4. which I forked. During the translation, we didn't merge the "official" documentation. So literally, the Japanese translation is version 0.5.4.

It's hard to catch up with the latest version because the update is pretty fast. 
This is the very first Japanese translation and I think we made some mistakes (we tried not to make them though), so we might still need some modifications.

In my opinion, we can publish this and we will modify some mistakes after a while (I think users will point out some mistakes). Then, when version 0.6.0 is published, I can translate breaking changes if I'm available.

What do you say?

**Comment by chriseth** [comment]
@akira-19 that sounds good! Maybe the best approach forward now is to link to the japanese version from the main page of the solidity docs. Once it is up to date, we can include it inside the repository.

**Comment by akira-19** [comment]
@ChrisChinchilla You mean I publish them and you add the link, and you add them into the repository when we finish the modifications?

**Comment by chriseth** [comment]
Yes!

**Comment by akira-19** [comment]
@ChrisChinchilla I got it. I'll let you know when I publish them. Thanks.

**Comment by akira-19** [comment]
@ChrisChinchilla I published the translation. Please add the link into the original documentation. Thanks! 
https://solidity-jp.readthedocs.io/

**Comment by ChrisChinchilla** [comment]
Sorry @akira-19 I was on holiday, will get this done now, and thank you again for your work, most appreciated!

**Comment by akira-19** [comment]
@ChrisChinchilla No worries! I appreciate your quick action.
