### ISSUE TITLE
Constants in Yul

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5928]
From https://github.com/ethereum/solidity/issues/5914#issuecomment-460623404:

I think introducing support for constants could improve the clarity of the code and the same time helping the optimiser. Currently the lack of constants incentivizes users to duplicate constants several times to avoid using a stack slot for them (as a variable).

Marking them constant is a hint to the optimiser (a new optimisation stage).

Regarding syntax I'd propose either `constant x = 0x1324` or `const x = 0x1234`.

**Comment by ekpyron** [comment]
I think the optimizer can handle constants quite well without this. If the user duplicates the constant, then that should be detected and if saving stack slots makes sense the optimizer should do so as well, so I don't see the need for a language construct here.

**Comment by axic** [comment]
> I think the optimizer can handle constants quite well without this.

Does it? Even if it does, since it is not clearly expressed anywhere, I as a user wouldn't put constants into a let statement.

Ideally I'd actually prefer Rust's way where `let` is immutable, `let mut` is mutable and shadowing the same variable is by design to help scoping :)

**Comment by ekpyron** [comment]
From gitter (@axic): ``This actually may be a real benefit of constants, right now constants have to be passed to functions via variables and then you end up with this stack issue.``

While true, that's also solved by using ``function constantName() -> x { x := value }`` for the constants...
We also discussed that since shadowing global variables in functions is an error, constants could have global scope - which is again also the case for (top-level) functions.

So *if* we ever decided that we want constants, then I think we could have a simple pre-processing step that does the following:
- Replace any declaration ``constant x := <literal>`` by ``function x() -> r { r := <litearl> }``.
- Replace any reference to ``x`` by ``x()``.

and we would pretty much get what we want, wouldn't we? So it could be pure sugar that is removed in a step before optimization or codegen.

So the main question is probably how much sugar like that we want in Yul. I think having a sugar-full variant of yul could be nice. On the other hand we pretty much deferred that to Yul+ so far - and in inline assembly Solidity constants could be used for exactly this purpose...

**Comment by axic** [comment]
> While true, that's also solved by using `function constantName() -> x { x := value }` for the constants...

Yes, I did mention that, and also that I am not sold by it being a really convenient option.

> So it could be pure sugar that is removed in a step before optimization or codegen.

I thought about it being just a "sugar" in the sense there would be an early optimiser step which replaces all assignments from constants with their literal value, or the function madness proposed above.

> So the main question is probably how much sugar like that we want in Yul. I think having a sugar-full variant of yul could be nice. On the other hand we pretty much deferred that to Yul+ so far

I do not think it was "deferred", rather that Yul+ is a good place to be a playground, but what makes sense, should be included.

> - and in inline assembly Solidity constants could be used for exactly this purpose...

I'd say that is a separate issue to this. Inline assembly is a weird beast.
