### ISSUE TITLE
Should be possible to create a mapping key from a struct object

### ISSUE THREAD

**Issue by VoR0220** [ethereum/solidity#599]
it would act in the idea of a sha3 of each of the combined inner types of the struct to map to each value. 

For example

```
struct A {
uint b;
string c;
}
```

would be represented in a mapping by sha3(b, c). For inner structs, this would go sequentially as they all appear in storage for as many types pop up.

**Comment by chriseth** [comment]
Indeed, as log as the structs do not contain mappings. Furthermore, the sha3 should be applied with "tight packing" applied, i.e. no padding to 32 bytes and structs and tuples should be handled identically.

**Comment by VoR0220** [comment]
tuples handled identically? How do you mean? Can you write an example please?

**Comment by VoR0220** [comment]
So should it look something like this for a tuple?

```
contract test {
            mapping((uint, string, int) => string) aMapping;
        }
```

**Comment by VoR0220** [comment]
or should we enable var here? I think adding var is not the best here...

**Comment by VoR0220** [comment]
also...if this is the case....should we allow arrays? Or is that overkill?

**Comment by chriseth** [comment]
yes, that is how tuples are written, but I think we should keep the focus for now.

**Comment by RomeshKTripathi** [comment]
Can you suggest me how can I start contribution.

**Comment by cameel** [comment]
Hello @RomeshKTripathi. This is a very old issue and I'm not sure we even want to implement it as proposed. Since it was proposed we moved in the other direction, e.g. requiring explicit encoding when hashing. This change would go against it. I think we should close it.

Please take a look at the list of ["good first issues"](https://github.com/ethereum/solidity/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) instead.
