### ISSUE TITLE
Memory leak totaling 920 bytes across 11 allocations

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6011]
## Description

The following contract leaks memory as mentioned in the title.

```
contract C {
    function f() public returns (C) { return this; }
    function g() public returns (uint) { return f().balance(); }
}
```

## Environment

- Compiler version: latest develop commit
- Target EVM version (as per compiler settings): n/a
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: Ubuntu bionic

## Steps to Reproduce

```
$ cmake -DSANITIZE=address ..
$ make solfuzzer
$ solfuzzer < `contract.sol`
```

**Comment by leonardoalt** [comment]
@bshastry is this still the case?

**Comment by axic** [comment]
@bshastry can you reproduce and copy in the log from the sanitizer/valgrind?

**Comment by axic** [comment]
#5882 describes a similar case:
> (Found by ossfuzz: issue number 12673)
>
> While processing the following Soldity contract, the Solidity compiler leaks 464 bytes of memory across 7 allocation sites
>
> ```
> contract C{function f()returns(C){f().r;}}
> ```

**Comment by nikola-matic** [comment]
It's been a very long time since this was opened, and given the above steps, I can only repro a 26 byte leak, which is unrelated to solc/solfuzzer - but rather `libcln`:

```
==13452==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x7f73192e1359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f731998ebe1  (/usr/lib/libcln.so.6+0x64be1) (BuildId: 0a8ed6dcb14ad393978cb145b99030bc45633191)

SUMMARY: AddressSanitizer: 26 byte(s) leaked in 1 allocation(s)
```

We're already aware of this (it showed up in the nightlies), and have suppressed it - since there's not much we can do about it, at least not quickly and easily: see https://github.com/ethereum/solidity/issues/13891.

Closing this as not an issue.
