### ISSUE TITLE
Out of range exception thrown while assembling strict assembly code containing call to datasize

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6103]
## Description

The following call leads to an exception

```
$ echo "{pop(datasize(0))}" | ./solc/solc - --strict-assembly

======= <stdin> (EVM) =======

Pretty printed source:
object "object" {
    code {
        pop(datasize(0))
    }
}

Unknown exception while assembling.
```

The stack trace revealed by the fuzzer shows that the problem is from here

https://github.com/ethereum/solidity/blob/97d3b88f65b9ee146d7d799e44d59c3d213a0d96/libyul/backends/evm/EVMDialect.cpp#L59

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): constantinople
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: n/a

## Steps to Reproduce

```
$ echo "{pop(datasize(0))}" | ./solc/solc - --strict-assembly
```

**Comment by chriseth** [comment]
I'm pretty sure this is not due to the selfdestruct but due to the `datasize`.

**Comment by bshastry** [comment]
@chriseth you are right. I edited the bug title and description accordingly.

**Comment by christianparpart** [comment]
@bshastry / @chriseth what is the expected output of `datasize(0)`? Why this one is raising is because the parameter (`0`) isn't in the map of assembly IDs (`m_subIDs`) and just adding `yulAssert()`'s in front  does indeed improve the error output but doesn't really feel like a fix.

If this parameter is wrong input, we should improve the API to allow detailed error diagnostics propagation up to the caller's layer.

**Comment by christianparpart** [comment]
I believe I just found out my first question; the parameter should be of type string and represent the path to an assembly object in dot-notation. Since we passed an invalid parameter, we should pass this information up to the caller, somehow. (returning `false` and reporting to `ErrorReporter` would be my proposal?)
