### ISSUE TITLE
Source code verification

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#611]
As the ways to compile contracts get more and more complex, it becomes paramount to provide a simple way to verify the source code of a contract. Also as swarm is now more or less within reach, a way to store the source code of a contract becomes viable.

The following way to perform source code verification is hopefully forward-compatible and does not rely on timing problems or the need for a registration contract.
- At compile time, the compiler creates a json object containing metadata about the contract including the source code used to compile it, the (path-qualified) name of the contract in the source, the compiler version and for usability purposes also the ABI and documentation. This json object can be amended in the future. Its byte representation is called "the metadata".
- The hash of the metadata is stored as part of the contract creation bytecode (as `push32 metadata, pop` at the beginning of the contract). It is important to store this with the creation bytecode because the constructor is not covered if it is only stored in the deployed bytecode. Also not storing it with the deployed bytecode saves costs.
- If a user wants to verify the source code of a contract, they have to ask the ethereum node for the data that was used for creating that contract (including constructor parameters, which is very important). From that data, the hash is extracted and swarm or some other storage solution is asked for the content corresponding to that hash (i.e. the metadata). From the metadata, the complier version is extracted (the "version" might also just be a swarm-hash of the binary itself), verified that it is an "official" compiler version and the compiler (or corresponding verifier) is downloaded from swarm. Both solc and solc-js provide a verification mode: You supply the creation data and the metadata and the compiler verifies that they match and optionally outputs the constructor arguments in parsed form.
- in order to make it easier to discover the creation data, the constructor will issue a log as the first operation until there is protocol-level support for that. There is of course the option to switch off both the creation of the log and the inclusion of the metadata hash.

Problems to solve: Unlinked objects cannot provide the metadata hash because the addresess of the libraries have to be part of the metadata hash. This might not be a problem in the end.

**Comment by VoR0220** [comment]
what does the metadata object look like?

**Comment by frozeman** [comment]
+1
Tho I don't fully understand. Do you want to store a hash of the json meta data with the contract deployment itself?

And how would a verifier know at which tx to ask for the right deployed code?

**Comment by axic** [comment]
I think the metadata would only represent all the sources and options used to generate that given binary. It doesn't matter where you get that binary from as long as you can acquire the metadata and all of its references to recreate the binary.

**Comment by zelig** [comment]
nice one Chris. 
great question Fabian
the hash of the metadata is cheaper to store in the contract creation tx . and because of the source -> byte code depends on constructor parameters which are only in the contract creation tx you need to look there anyway.
now I think the best way to get that is to actually register block number and tx index together with the metadata content hash in ENS
to complicate things a little, sometimes the transaction needs to be replayed if the creation is called from another contract

**Comment by axic** [comment]
@chriseth wouldn't it make more sense putting a _metadata pointer_ section at an unreachable, but fixed part of the binary (i.e. the very end of it?). This _metadata pointer_ could contain just the hash you suggested, or a flags/version/type field + the hash for future upgradeability.

Alternatively I still like the suggestion (from #529) to have this value accessible via a method. Good because you don't need to parse the binary, but bad because you need to execute it.

**Comment by Arachnid** [comment]
This solution will mean that only full nodes retain the data required to verify contract source code, which seems like a bad idea. Like @axic, I think it makes a lot more sense to embed the relevant information as a method.

**Comment by chriseth** [comment]
@axic @Arachnid in general, there are two ways to verify compilation:

1) compile the source code, retrieve the runtime bytecode and compare with the code at that address

2) compile the source code, retrieve the creation code and compare with the data that was used to create the contract (either the tx payload or the data of a CREATE operation).

Method (1) has a major flaw: It completely ignores the code in the constructor and the constructor parameters. If you have a contract that has a constructor that sets an important option in storage, the contract will still verify even after a total semantic change in the constructor.

The only safe way to perform source code verification is at the point of creation. This has the benefit, that we can even decode the constructor arguments and show them to the user that requests the verification.

It requires some effort to retrieve the creation data, but I think it is worth it and we should add indexing structures to help that process, perhaps even with the help of a registration contract. There is also a trustless way that can be used by light clients. It requires replaying a full transaction, but light clients have to be able to do that for other things, too.

@axic this proposal puts the metadata at a fixed point in the binary, namely 32 bytes starting in the second byte. The end of the bytecode cannot be used because that is where the constructor arguments go.

**Comment by Arachnid** [comment]
Is that a major flaw? The constructor can only affect the ongoing behaviour of the contract by setting data in storage, which can be verified by the user by examining the contract's storage on the blockchain. I don't think the constructor data is directly relevant to how the contract behaves now, which is what a user examining the contract wants to determine.

**Comment by chriseth** [comment]
Yes, I think so. If you require the user to verify storage contents in addition to bytecode, it gets much more complicated, because you would have to retrieve the contents at the point the contract was created, you have to require from the user to be able to interpret which storage values are set by the constructor and so on. If the constructor sets dynamic arrays or mappings, this gets very complicated very fast. The behaviour of the constructor is paramount to the behaviour of the smart contract: You can easily fool someone by just flipping a flag that represents the state of the smart contract.

I'm not saying that there is no value in verifying runtime bytecode alone, I'm just saying that the proper way would be to verify the creation time bytecode and we should focus on that usecase.

**Comment by Arachnid** [comment]
For the constructor to influence the contract, the runtime code has to contain instructions that alter its results based on the contents of storage; in that event the user absolutely has to check the contents of storage in any case, or else they can't be sure that the value is set to what they expect it to be. Verifying that it was set that way at creation time isn't enough.

No matter what, users have to verify both the operation, and the parts of the state that are relevant to the operation; there's no avoiding that. Since the constructor code doesn't form part of the operation code, and only acts to set the initial state, I don't think there's a significant loss in excluding it from the verification, as long as users are aware of how to audit a contract as a whole.

I'd be happy to be proven wrong, if anyone can demonstrate a contract that's obviously broken when viewed with the constructor, but doesn't set off alarm bells when viewing the code alone.

**Comment by chriseth** [comment]
@Arachnid I disagree. Since the contract starts in a defined state (empty storage) there is nothing to check if you begin at creation time. Of course, you have to get an impression of the current state of the contract if you want to interact with it, but you do not have to check that the contract at least started in a way that was set in its constructor. One of the big problems here are mappings. If the constructor does something like `x[a] = 2;` where `x` is a mapping and `a` is a constructor argument, there is no way to find out what `a` is without looking at the creation transaction (or finding out about constructor arguments in another way which is probably more complicated).

Just to have an example, let us look at the constructor of the DAO: https://github.com/slockit/DAO/blob/master/DAO.sol#L354

As you propose, we completely ignore the creation transaction and as a possible attack, someone modifies the actual constructor that was used to write to storage at strategical places such that the number of votes for proposal 11 are pre-initialized before the proposal is created. If you want to verify the contract, it is not enough to check that certain values exist in storage, you actually have to identify every single value that is set in storage and find out where it came from.

And now please compare that to starting at 0, with empty storage and at least 100% verifying the initial state of the contract and its rules. For many use cases, you do not need to verify the full current state of the contract, but just the part that is relevant for you. In the example of the DAO, verifying the full current state is practically impossible: Because of the `balances` mapping, you have to replay every single transaction to find the addresses used there.

**Comment by Arachnid** [comment]
I somewhat see your point; constructors can place the contract in a part of the state space that couldn't be reached purely by following the rules baked into the contract's code. I don't think it's that useful to users, though. 

When users are auditing a contract, it's generally with a view to using it. When a contract's anything other than very straightforward, generally you need to be able to assess the contract's current state in order to know if interacting with it is a useful proposition; it doesn't matter to you how the votes on proposal 11 got there, ultimately, as long as you can determine they're there. 

Block explorers such as ether.camp are capable of displaying contract storage data, given Solidity source code. Doing so without a full node is problematic, though probably not impossible.

**Comment by bobsummerwill** [comment]
I think I agree with you here, @Arachnid.

When you start venturing into analysis of stateful behaviour, it is likely a bottomless pit.

I think it might actually be harmful to even try, because it runs the risk of getting people false confidence.

Verifying that the code is as expected is a very discrete and solvable problem.    When it comes to stateful behaviour which will, by definition be different for each smart contract instance ... that is a much trickier issue.

You're getting into formal verification there.    Which would be cool.    But I think it's a different tool which is required at that point.

**Comment by chriseth** [comment]
@Arachnid I'm not sure you understand what I wanted to say with the "proposal 11" example: If you verify the code at construction stage and see that the current proposal counter is below 11 (by querying a single point in storage), you can be sure that by adding your new proposal with id 11, all votes will be initialized to 0, because there is no way to inject votes for proposal 11 before it was created. Whereas when you only check the deployed code, you actually have to read all the full storage and scan all transactions in order to invert the sha3 to see that nobody injected any votes into the proposal prior to its creation.

**Comment by Arachnid** [comment]
@chriseth Yes, that's what I meant by saying that constructors let you reach parts of the state space the code wouldn't. Without the constructor, you would know that combination of states isn't possible, because no set of function calls could produce that result.

While I agree that's useful information, I don't think it's enough: I still think that anyone auditing a contract needs to include evaluating the current state as part of that, so any audit mechanism that presupposes they won't do that is of limited usefulness.

**Comment by chriseth** [comment]
(updated description to add a log to help discovery of the creation point and data)

**Comment by Arachnid** [comment]
How will source discovery and verification for contracts created by other contracts be handled?

**Comment by chriseth** [comment]
Source discovery is out of scope. In the future, it will be retrieved from swarm, currently it might be retrieved from github gists or any other source. Verification of contracts created by other contracts will be handled in exactly the same way. You search for the first log at that address, if it is a creation tx for that contract, you use the input data there. If it is not a creation operation, some support from the backend node is needed. In the worst case (if there is no support), you have to request the trace of the transaction and retrieve the data that way. Remix already reads those traces, so we might just provide some helper script to extract the data from the trace.

**Comment by romanman** [comment]
@chriseth : any thoughts to 
include validation hashes into
the code  ?

P.S: it is hackabale by changing compiler code , 
but it's not an easy hack and the validation 
can give much better solution that we have now.
