### ISSUE TITLE
get elements from strings array 

### ISSUE THREAD

**Issue by panicape** [ethereum/solidity#6123]
Hi everyone, i'm glad to follow this forum, it is very helpful.
I'm using truffle to develop contracts and i just found that dynamic arrays are not yet suported, for that reason i was using string arrays with a fixed lenght and i found that the element with index 0 is not showing anything and last one says undefined. do you know ay reason of that?, do i have to get elements in a different way??

This is the function in solidity:

`function getStringArray() public returns (string[])  {
        string[] memory resultStr = new string[](3);

        resultStr[0] = "355555555";
        resultStr[1] = "2";
        resultStr[2] = "8888";

       return resultStr;
    }`

in javascript i test getting elements one by one and i got this:

list size=3, value 0=      , 1=355555555, 2=2, 3=undefined

any idea about what's happening in this case?, how do i have work well with string arrays to get all elements?

**Comment by chriseth** [comment]
I'm sorry, but this is not a forum, it is a tracker for bugs and features in the Solidity compiler.
This question is better asked at https://ethereum.stackexchange.com - you will get faster and better replies there.

**Comment by panicape** [comment]
@chriseth ok, thanks

**Comment by eprabhakar** [comment]
@panicape 
I got into a similar issue, and found that the issue is with the 'experimental ABIEncoderV2'.. 
I am not sure if you have posted an issue on the [https://ethereum.stackexchange.com/  ](url) and got a response, but I posted the following issue and did not get a response

[https://stackoverflow.com/questions/55772497/truffle-console-command-result-is-not-the-same-as-the-react-redux-async-await-so](url)

After a bit of research, I found that retrieving the individual assets strings from the array is a better option as mentioned in my answer to the above issue.

@chriseth , this appears to be an issue with the 'experimental ABIEncoderV2'. Please check and let me know.
