### ISSUE TITLE
Fuzzing Low-level Lisp-like Language parser/compiler

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#6201]
## Description

The following sub directories inside solidity are not touched by the fuzzer atm
  - `liblll`
  - `lllc`

Is it worth while to write a fuzzer for the LLL parser/compiler? Of course, it would be interesting to additionally test code optimization/generation but currently we don't have the same test infrastructure (interpreter) that we have for yul code.

**Comment by chriseth** [comment]
The main problem with lllc is that it was written in a rather peculiar style and thus the code is rather hard to understand. I think nobody currently on the team has proper knowledge of that code and it would take quite some time to fix bugs.

**Comment by axic** [comment]
I've fixed couple of issues back in the day, but it would rather need a rewrite to make use of all our new features, APIs and Yul.

A while back we have agreed to phase out LLL from the codebase (pending another compiler be written by for lll -> yul) and because of that I'd suggest to ignore LLL in fuzzing.

**Comment by bshastry** [comment]
As per the discussion, it seems like LLL is not an interesting target for fuzzing since it is going to be phased out. Closing issue.
