### ISSUE TITLE
Optimizer: Weird shifts still unoptimized

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6214]
The following sequence is part of bytecode generated from Solidity after the optimizer has run.

`and(0xff, shr(0xf8, shl(0xf8, shr(0xf8, x))))`

It can obviously be simplified to `shr(0xf8, x)`.

Related: https://github.com/ethereum/solidity/issues/5810

**Comment by Marenz** [comment]
Though, for certain values it could shift the lower/upper parts "out" of the type right?

**Comment by ekpyron** [comment]
I wonder if there is a nice general "normal form" for shifting and masking that can express all ``and``s, ``shl``s and ``shr``s, such that two of these "normal form" operations can always be easily combined to one...

Then we could always use that form and only replace it with its simplest representation using ``and``/``shl``/``shr`` as a very last step... I think that might be cleaner and more stable than having a lot of shift and ``and`` rules that will interact in various ways...

**Comment by ekpyron** [comment]
"rotate right and mask" would probably work... two of those could probably be combined by adding the rotation amount (modulo 256) and ``and``-ing the mask of one with the rotated mask of the other...
Not sure it's a good direction to go, though.

**Comment by ekpyron** [comment]
For the sake of the argument (and not to be taken as 100% verified, but rather a quick draft):
``and(x,A) -> rorand(x,0,A)``
``and(A,x) -> rorand(x,0,A)``
``shl(A,x) -> rorand(x,256-A, not(2^A - 1))`` (given 1 <= A <= 255, otherwise: trivial shift)
``shr(A,x) -> rorand(x, A, 2^(256-A) - 1)`` (given 1 <= A <= 255, otherwise: trivial shift)
``rorand(rorand(x,A,B),C,D) -> rorand(x, (A + C) mod 256, and(D, ror(B,C)))`` (or sth like that - probably some more care needed)

and in the end ``rorand(x,A,B)`` can be resolved to its cheapest representation using shifts and ``and``s. That'll take some doing, especially if ``B`` has "gaps", but it's definitely feasible...
EDIT: actually probably not too hard - "weird" values of ``B`` with gaps can only stem from ``and``s anyways and in the worst case we have to keep one such ``and`` - only constant size might complicate things.

**Comment by chriseth** [comment]
llvm turns expressions into a certain normal form ( https://llvm.org/docs/Passes.html ):

1. If a binary operator has a constant operand, it is moved to the right-hand side.

2. Bitwise operators with constant operands are always grouped so that shifts are performed first, then ors, then ands, then xors.

We already do 1 and I think 2 might also be a good idea in general, not only for constant operands.

**Comment by ekpyron** [comment]
In the example case of ``and(0xff, shr(0xf8, shl(0xf8, shr(0xf8, x))))``, this would look like:
```
and(0xff, shr(0xf8, shl(0xf8, shr(0xf8, x)))) ->
and(0xff, shr(0xf8, shl(0xf8, rorand(x,0xf8, 0xFF)))) ->
and(0xff, shr(0xf8, rorand(rorand(x,0xf8, 0xFF), 8, 0xFF00...00))) ->
and(0xff, shr(0xf8, rorand(x,0, and(0xFF00...00, ror(0xFF,0x8))) ->
and(0xff, shr(0xf8, rorand(x,0, 0xFF00...00))) ->
and(0xff, rorand(rorand(x,0, 0xFF00...00), 0xf8, 0xFF)) ->
and(0xff, rorand(x,0xF8, and(0xFF, ror(0xFF00...00, 0xF8)))) ->
and(0xff, rorand(x,0xF8, 0xFF)) ->
rorand(rorand(x,0xF8, 0xFF), 0, 0xFF) ->
rorand(x,0xF8, 0xFF)
````

**Comment by chriseth** [comment]
I think we can even work with that without introducing a new opcode. It may be, that the following rules suffice, which can be fully implemented in the current framework:

```
shr(A, shl(B, x)) -> and(shX(B - A, x), MASK)
// where shX is shr if A > B, shl if B >= A and MASK is the mask that results from the combination
// analogously for shl(A, shr(B, X))

shX(A, and(X, B)) -> and(shX(A, X), MASK)  // where MASK is the appropriate modification of B
```

**Comment by ekpyron** [comment]
Note to be careful with the ``B - A`` (resp. ``A - B`` or generally ``abs(B - A)``) case and over- and underflows :-).
(EDIT: i.e. the rules should best be limited to non trivial shifts with a constant 0 < A < 256 or something similar - the other ones will be removed elsewhere anyways)

**Comment by chriseth** [comment]
I agree, any shift value larger than 255 is already handled by other rules anyway.

**Comment by bshastry** [comment]
Does #6530 close this issue? Came here from 0.5.8 project "needs review" tickets.
