### ISSUE TITLE
delete inherited functions in child contract

### ISSUE THREAD

**Issue by Amxx** [ethereum/solidity#6245]
I've seen at EthCC that solidity 0.6.0 will includes keywords `override` and `virtual`. This is awesome! However, an additional keyword to delete function could be very nice to have.

Example, I have a smart contract `A` that implements a complexe ownership mechanism and a `verify(something)` function. I could want to have a smart contract `B` i herite all of `A`'s code, except for the `verify` function that will be replaced (but not overriden) by `verify(something different)`.

This will reduce the cost of deploying `B` and reduce the risk of error when calling the `verify` function.

**Comment by chriseth** [comment]
If I understand you correctly, you are proposing to remove functions from the external ABI of a contract - is that right? In that case, I don't think this is a good idea because it is incompatible with inheritance rules:

If `x` is an instance of `B` which inherits from `A`, then the full interface of `A` has to be available on `x` because you can always convert `x` to the type `A`.

Note that functions that are essentially unused because they are overridden will not be part of the bytecode - this should already be the case now.

**Comment by leonardoalt** [comment]
@Amxx is that what you meant?

**Comment by Amxx** [comment]
yes,

an example of usage for me was to have a contract be ownable but without the possibility to ever change the ownership. In my case I inherit from openzeppelin's owable contract and add:

    	function transferOwnership(address) public { revert("disabled"); }

I'd much rather have put something like

        delete transferOwnership(address) public;

so the function doesn't even appear in the ABI, and no one tries to call it to then have its transaction reverted

**Comment by 0xdcota** [comment]
I still think what @Amxx proposed is a desired feature. 
``
    delete transferOwnership(address) public;
``
I am in need to deleting methods I am not using from inheriting from some Openzeppelin contracts.
