### ISSUE TITLE
[soltest] Format expectations as compact hex literals by default.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6298]
When reformatting a hex literal like ``0x42``, isoltest will currently correctly output a hex literal, but always a full 32-bytes long one like (at least confirmed on mismatching expectations), e.g. ``0x000000000000000000000000000000000000000000000000000000000000002a``. This is "fine", but it would be nice to just change the formatting to use "toCompactHexWithPrefix", which will result in a nice ``0x2a``.

On a related note (but probably not worth its own issue): parsing of hex literals should be more relaxed: currently odd numbers of digits are considered invalid literals, e.g. ``0x01`` is fine, but ``0x1`` and ``0x101`` are invalid and instead you have to use ``0x01`` or ``0x0101``. This is inherited from solidity, where it makes sense, but here I think it is more cumbersome than useful.

**Comment by chriseth** [comment]
Please take a look at `formatNumberReadable`.

**Comment by erak** [comment]
@chriseth I think calling `formatNumberReadable` seems to be not applicable in this case, since it would format "small" numbers (<= 0x1000000) as decimals and I would want to keep the hex format.

@ekpyron Does you suggestion also imply formatting values returned from a call as hex if i.e. user did not define expectations?
