### ISSUE TITLE
ABIEncoderV2: wrong function signature in libraries

### ISSUE THREAD

**Issue by Alirun** [ethereum/solidity#6420]
## Description

Function signatures in libraries public functions with structs in arguments are calculated in wrong way.

Probably somehow related to #6001 , which seems to be fixed already.
And also probably somehow related to #3400 , but author didn't provided enough information to finally solve this issue and it was closed.

## Steps to Reproduce
If you write a code in this way

```
pragma solidity ^0.5.4;
pragma experimental ABIEncoderV2;

library LibStructTest {
    struct CoolStruct {
        uint256 coolValue;
    }

    function getHash(CoolStruct memory self) public pure returns (bytes32 hash) {
        hash = keccak256(abi.encodePacked(
            self.coolValue
        ));
    }
}
```
You expect `getHash` function to have signature
`keccak256("getHash((uint256))") // 0xe1c67ed8`
But we get
`keccak256("getHash(LibStructTest.CoolStruct)") // 0x54d08d7a`

Then if you change the code and add one more parameter to struct this way
```
pragma solidity ^0.5.4;
pragma experimental ABIEncoderV2;

library LibStructTest {
    struct CoolStruct {
        uint256 coolValue;
        uint256 otherCoolValue;
    }

    function getHash(CoolStruct memory self) public pure returns (bytes32 hash) {
        hash = keccak256(abi.encodePacked(
            self.coolValue
        ));
    }
}
```
You expect `getHash` function to have signature
`keccak256("getHash((uint256,uint256))") // 0x31183ed7`
But we still get
`keccak256("getHash(LibStructTest.CoolStruct)") // 0x54d08d7a`

## Environment

- Compiler version: 0.5.7
- Framework/IDE (e.g. Truffle or Remix): both
- Operating system: All of them

**Comment by chriseth** [comment]
As libraries are (or at least were) an internal construct of Solidity, their functions are not meant to be called "from outside". This allowed us to introduce the concept of (especially storage) structs much earlier than for contract functions and just chose an internal representation for computing the function signature.

For pure functions, it does make sense to call library functions, so we might change the behaviour in the future. The problem is that this will be a serious breaking change and any contract linking to such a library function will silently fail.

**Comment by chriseth** [comment]
One option to allow this in a backwards-compatible manner is to allow both signatures (old style and new style) to lead to the same function.

**Comment by ekpyron** [comment]
Allowing both signatures for now sounds reasonable, yes.

**Comment by chriseth** [comment]
Adding it to the scope of 0.6.0 since this has come up a lot lately.

**Comment by haltman-at** [comment]
Some notes on this, since I've been thinking about this lately: (some of these should possibly be separate issues but oh well)

1. Of course, there are `pure` and `view` functions that are excluded from the ABI, namely, those that take or return storage pointers.  I notice that at the moment, despite being excluded from the ABI, these functions still lack the `DELEGATECALL` guard.  Maybe they should get it, and only those functions that actually go in the ABI should not have it?

2. Similarly, functions that take or return storage pointers should probably be excluded from getting new-style selectors (to the extent that's even meaningful in this case!) even if they're `pure` or `view`.  Well, OK, I guess that's obvious since they *can't* really get new-style selectors, but...

3. Thought: Once new-style selectors are implemented for `pure` and `view` functions (that don't take or return storage pointers), you could allow storing such functions in `function external` variables!  Currently storing library functions in such variables is illegal, and for good reason, but once they have new-style selectors there no longer seems to be any reason to exclude them.

**Comment by ekpyron** [comment]
After some discussion we are actually hesitant to implement this for 0.6.0.
Among the open questions: if we use allow both old and new signatures, which one would we use when compiling new library calls? If we use the new ones, we break all calls to existing pre-0.6.0-libraries - if we use the old one, the new ones are kind of useless...

So far our plan is to first document how library signatures are computed right now and allow accessing the signatures using member accesses to the library functions just like for regular external contract functions - both of which would at least clarify the current situation.

For actually moving to a new kind of selectors we're open to suggestions on how to properly solve the backwards- and forwards-compatibility issues.

**Comment by haltman-at** [comment]
> After some discussion we are actually hesitant to implement this for 0.6.0.
Among the open questions: if we use allow both old and new signatures, which one would we use when compiling new library calls? If we use the new ones, we break all calls to existing pre-0.6.0-libraries - if we use the old one, the new ones are kind of useless...

I thought the idea was to always use the old one when compiling library calls, and the point of the new one would be to allow calls from outside Solidity, based on the ABI JSON, using something like Truffle or `web3.eth.Contract`, to work properly?

The alternative, I suppose, is what's been discussed elsewhere -- adding a `selector` or `signature` field to the ABI JSON.  Then people wouldn't need to compute it since they could just read it out of the JSON.  I suppose that's a lot simpler than making two styles of selector work!

> So far our plan is to first document how library signatures are computed right now and allow accessing the signatures using member accesses to the library functions just like for regular external contract functions - both of which would at least clarify the current situation.

Ooh, that's nice.  This raises a question though about typing.  Currently, `Lib.f` is of internal type, even if `f` was declared `external`.  Does this mean it's now going to be possible for it to be treated as external instead in some contexts?  Hard to take a selector otherwise, right?

But also if so... does that mean if `f` is a `view` or `pure` function -- where we might want to possibly make the additional restriction that `f` must have no `storage` parameters, either input or output -- it might now be possible to store it in a `function external` variable?  Because currently that isn't possible.  (Allowing this for more general functions probably doesn't make sense, but for those ones you could do it.)

> For actually moving to a new kind of selectors we're open to suggestions on how to properly solve the backwards- and forwards-compatibility issues.

Well, my suggestion (or rather pair of suggestions, either of which work) is above. :)

**Comment by chriseth** [comment]
@haltman-at the feature of libraries was originally meant to use delegatecall only. At some point, people wanted functions to be inlined, so we allowed internal library functions to be inlined. I'm really not sure we should extend the use of libraries for non-delegatecall any more, because for that purpose, you can also just use contracts.

Maybe we could have a call where we can talk more about the use-cases?

**Comment by haltman-at** [comment]
Honestly, I just wanted to see about making things consistent!  It's just a little confusing when there are these hidden limitations and exceptions.  I'll admit I didn't have a real use case in mind.

Although -- and at this point I'm repeating what I said above, but -- I think there's one way in which you should probably *restrict* it a bit more, in that I noticed there's no delegatecall guard on library functions which are `view` or `pure` but have storage parameters in the input or output.  You're clearly doing something to distinguish such functions as they're excluded from the ABI; maybe it would make sense to add a delegatecall guard to them as well?

**Comment by ekpyron** [comment]
@haltman-at The current draft for addressing this, respectively at least documenting what's currently happening is here https://github.com/ethereum/solidity/pull/7719 (there may be a lot of room for improvements in the documentation part).

In fact I don't think anything is actually "excluded from the ABI" - rather its not really an "ABI", but rather an internal calling convention that works differently from the regular ABI.

I'll have a look into the ``delegatecall`` guards. For ``pure`` functions it should be fine *not* having them, because while they can receive storage pointers, they won't be able to actually read from (let alone write to) them - That may sound weird, but think:
```
library L {
    function decideWhichStoragePointerToUse(uint256[] storage a, uint256[] storage b, ComplexStruct memory s) public pure returns(uint256[] storage) {
        if (someFancyProperty(s))
            return a;
        else
            return b;
    }
}
```
No need for a ``delegatecall`` guard in that one and it's in fact perfectly ``pure`` - it just passes offsets to/slots in storage around, but doesn't actually care about storage itself.

For ``view``, though, things may be different, though - I'll look into that.

**Comment by ekpyron** [comment]
Ah, ok - you meant excluded from the json ABI, right...

**Comment by ekpyron** [comment]
I'll add some documentation about what goes into the json ABI and why to #7719 - and I'll check for consistency along the way.

**Comment by ekpyron** [comment]
@haltman-at You're right - view library functions *should* have a delegatecall guard- at least if they do in fact read from storage, but currently they don't.

**Comment by ekpyron** [comment]
Is there a case for a view library function, in which it actually makes sense to call it without delegatecall, but in which it couldn't just as well be declared pure?

I wonder whether all view library functions should get the guard - and only pure library functions don't...

**Comment by ekpyron** [comment]
There is a case - the view library function could staticcall other contracts - that's fine, since it doesn't read from its own storage, but it's not ``pure``...

**Comment by ekpyron** [comment]
Yeah ok - I agree - we should put in the delegatecall guard for view functions that have storage pointers in the signature.

**Comment by ekpyron** [comment]
This is kind of tricky to get *exactly* right... Consider calling ``L.f`` without ``delegatecall`` in the following:

This is fine:
```
library L {
    function f(uint256[] storage a, uint256[] storage b, bool c) external pure returns (uint256[] storage)
    {
        return c ? a : b;
    }
}
```


And this is fine:
```
contract D { uint256 s; function f() external view returns (bool) { return s > 1; } }
library L {
    function f(uint256[] storage a, uint256[] storage b, D d) external view returns (uint256[] storage)
    {
        return d.f() ? a : b;
    }
}
```


But this is not fine:
```
library L {
    function f(uint256[] storage a, uint256[] storage b) external view returns (uint256[] storage)
    {
        return a.length > 0 ? a : b;
    }
}
```

The *really* correct and tight notion is somewhere between ``view`` and ``pure``... Well, it's actually exactly being ``pure`` plus allowing staticcalls...
But my guess is that all of these are highly artificial cases...

**Comment by haltman-at** [comment]
OK thinking about things some more I'm realizing my idea of "ooh, you could even put these in variables now!" would probably require some type weirdness that would likely not actually be easy to do without messing some things up.  So, uh, maybe just ignore that suggestion.  I was thinking "oh if you can take selectors" it's an external, but I guess the sensible way to implement that is actually just to add that capability to things that are `delegatecall`, not add some weird thing where sometimes `delegatecall` gets turned into `external`.  Oops.  So, that suggestion should probably be ignored.

But yeah being able to take selectors would be useful!
