### ISSUE TITLE
Libraries should not be able to call their own functions externally

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#6451]
... because it is impossible to properly link them.

The following code should not compile:
```
library L {
using L for *;
function f() public pure returns (uint r) { return r.g(); }
function g(uint) public pure returns (uint) { return 2; }
}
```

Reported by @haltman-at

**Comment by haltman-at** [comment]
I should make a note here of what I said on Gitter, since there is another possibility here, that would allow such libraries to be usable, although I'll admit I don't know how feasible this solution is.

Currently, libraries already need to include their own address for the delegatecall guard.  This isn't handled by the linker obviously but rather by having the constructor write in the address when it runs.  Perhaps the same thing could be applied to self-external calls?  Don't put in link references, but rather put in zeroes, and have the constructor fill them with the address when it runs?

I don't know if doing this is actually feasible right now, mind you.  And one reason not to do this is that it might give the impression that circular external library calls are OK when (if multiple distinct libraries become involved) they are not (since there's no deploy/link order that will work).  But, I thought I should at least record the suggestion.  Thanks again!
