### ISSUE TITLE
msg.sender, tx.origin and address literals should not be payable.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/solidity#6452]
Currently, `msg.sender` is considered an `address payable` by the Solidity compiler.  However, there is no guarantee that `msg.sender` is `payable` at all, and in fact for a lot of cross-contract calls it is explicitly not payable.  Because the compiler cannot guarantee that `msg.sender` is `payable`, I believe the correct course of action is to mark `msg.sender` as `address` and require the developer to do an explicit cast to `address payable` after they have validated in some way that the caller is in fact `address payable`.

This change would follow the theme of moving Solidity towards a more explicit language, which reduces the incident rate of bugs and exploits.  By changing `msg.sender` to `address`, the compiler will validate for the developer what it can assert, but it will not assert things that it cannot know.  The compiler would give the developer a warning, and the developer can then assert additional information that they know (e.g., that `msg.sender` is `address payable`) before proceeding.

One difficulty with this is that at the moment, you cannot do an explicit cast from `address` to `address payable`.  My recommendation would be to allow for such an _explicit_ cast, or provide a built-in function that does an explicit cast.  Generally speaking, I want the compiler to stop me when I'm doing something implicitly that cannot be guaranteed by static analysis, or I want it to stop me when I try to do something that the static analyzer can assert is not possible.  However, I do not want the compiler to stop me from _explicitly_ doing something that _may_ be possible (such as converting from `address` to `address payable`).

**Comment by ekpyron** [comment]
You're making a good point. As a side remark: You are aware that there is a workaround for converting ``address`` to ``address payable``? You can use ``address x; address payable y = address(uint160(x));`` - we might want to think about adding a smoother way to do this, though.

Apart from that (and given that such an explicit conversion is in fact possible) I think you're right and we should definitely consider changing ``msg.sender`` to ``address`` - that'd be a breaking change, though, so I'll add this for being discussed for the (hopefully soonish) upcoming 0.6.0 release.

**Comment by MicahZoltu** [comment]
Yeah, I'm familiar with routing through `uint16`.  I feel like the developer shouldn't have to try to trick the compiler into letting it do something that the compiler should recognize is a distinct possibility.  It is similar to how if you have a `Cat` class that derives from an `Animal` class, the compiler may know you have an `Animal` and it will refuse to implicitly cast it into a `Cat` but it will allow you to explicitly cast it into a `Cat`.  This explicit cast is the developers way of saying, "I have done the necessary checks to ensure that this is in fact a `Cat`, so treat it as a `Cat` from here on out.

**Comment by ekpyron** [comment]
The main reason for not allowing casts like ``address payable(x);`` is that two-keyword casts look kind of awkward (and would slightly complicate parsing). I wouldn't necessarily think of casting via ``uint160`` as "tricking the compiler", but yeah - maybe you're right and we should think of a nicer way for the explicit cast :-).

**Comment by chriseth** [comment]
The main reason for making `msg.sender` payable is that it simplifies the withdrawal pattern. I think we should find a good solution for the withdrawal pattern first before making this change.

For the explicit cast: Perhaps `payable(x)` would be fine already?

**Comment by MicahZoltu** [comment]
@chriseth Assuming `payable(x)` works for an explicit cast, what is the problem with the withdraw pattern?
```
function withdrawAll() payable {
    payable(msg.sender).call.value(this.balance)();
}
```

In this example, the author is explicitly telling the compiler:
> I'm aware that not all `msg.sender`s are `payable`, but I'm either confident that all callers of this method _are_ `payable` or I am OK with the transaction failing if `msg.sender` is not payable.

**Comment by chriseth** [comment]
@MicahZoltu indeed, it was a proposal on how to solve it.

**Comment by chriseth** [comment]
Oh but it would be
```
payable(msg.sender).transfer(this.balance);
```

**Comment by MicahZoltu** [comment]
Wow, totally screwed up my code snippet example.  Fixed above, though not using `.transfer` because no one should ever use `.transfer` or `.send`.  😉

**Comment by guylando** [comment]
If this is changed then need to change the note here: https://solidity.readthedocs.io/en/v0.5.8/types.html#address which says "For example, if you are using the withdrawal pattern, you can (and should) store the address itself as address, because you invoke the transfer function on msg.sender, which is an address payable"

**Comment by chriseth** [comment]
With this change, we should maybe also make address literals non-payable, i.e. in general anything that is not know to be payable should be non-payable.

**Comment by ekpyron** [comment]
@MicahZoltu Just to confirm back with you that we arrive at what you want here ;-). The issue only talkes about address literals, not about integers and we just realized that the open PR still lets ``address(uint160(0))`` be ``address payable`` - that's *not* what we want, right :-)?

But then, if we make those cases non-payable as well, the only case left in which ``address(...)`` will be ``address payable`` would be ``address(contract)`` where ``contract`` has a ``receive`` function.

Which is ok, but @hrkrshnn and I now started to wonder, if we should go even a step further:
``address(...)`` is just *always* ``address`` (non-payable). The only way to get an ``address payable`` would then be to explicitly use ``payable(...)``.
Now as for contracts: ``address(contract)`` would also always be non-payable and ``payable(contract)`` would *only* be valid if ``contract`` has a ``receive`` function, otherwise it's a compile-time error.

So with what part of that do you agree and what do you like most?

EDIT: @chriseth just mentioned on gitter, that he rather wants to keep ``address(contract)`` being payable, if ``contract`` is payable (i.e. has a ``receive`` function), so we'll go for that.

**Comment by haltman-at** [comment]
Hm, why `tx.origin`?  That one should be always be payable, right?

**Comment by axic** [comment]
Technically today yes, as an EOA must be the origin so it is always payable.

However with a bunch of proposals (like AA) this won't be the case. Perhaps this is too eagerly done, but maybe it is better to prepare for it?

**Comment by MicahZoltu** [comment]
> `address(...)` is just _always_ `address` (non-payable). The only way to get an `address payable` would then be to explicitly use `payable(...)`.
> Now as for contracts: `address(contract)` would also always be non-payable and `payable(contract)` would _only_ be valid if `contract` has a `receive` function, otherwise it's a compile-time error.
> @chriseth just mentioned on gitter, that he rather wants to keep `address(contract)` being payable, if `contract` is payable (i.e. has a `receive` function), so we'll go for that.

I have a minor preference for `payable(anything)` always returns an `address payable` and `address(anything)` always returns an `address`.  This is mainly just for consistency and simplicity in the language.  It is generally easier to audit things when everything is explicit and there are no implicit conversions.  To me it feels like `address(contract)` where `contract` has a `receive` function is something that dev time tooling could notice and help a user out with "this contract has a receive function, did you mean `payable(contract)`?"

@chriseth What is the argument for having the implicit conversion?  `address` and `payable` both have a similar number of characters, so it is unclear to me what we gain by having an implicit conversion here?

----

On a separate topic, why don't we just have a type `payable` instead of `address payable`?  I'm guessing this has already been discussed and I just missed or forgot the discussion.

**Comment by ekpyron** [comment]
> On a separate topic, why don't we just have a type payable instead of address payable? I'm guessing this has already been discussed and I just missed or forgot the discussion.

Yeah, that's a bit unfortunate... IIRC initially we wanted to have two single-word names for both types that are now ``address`` and ``address payable``, but we didn't find consensus about names and then went for ``address payable`` as compromise (it may even be that I'm to blame for bringing that suggestion up back then) - which in retrospect may not have been overly wise... but ``payable`` for example is not a particularly good name for a type, is it?

**Comment by MicahZoltu** [comment]
I would argue that pretty much *any* single word name is superior to a two-word name.  😄 Multi-word types increases parser complexity which makes writing tooling harder.

**Comment by chriseth** [comment]
That is indeed a point: The reason for `address(<contract>)` to be an `address payable` depending on the presence of a payable fallback or receive function was that otherwise, these functions serve no purpose in the type system. We could, though, also do it in the following way:

 - `address(<contract>)` is always possible, it returns a non-payable address
 - `payable(<contract>)` is only possible if there is a payable fallback or receive function and it returns an `address payable`.

You can still use `payable(address(<contract>))` to force the conversion.

**Comment by chriseth** [comment]
FIxed by https://github.com/ethereum/solidity/pull/10496
