### ISSUE TITLE
[Yul] Optimizer: move loop condition into loop body so we can apply expression splitter

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#6480]
Follow-up of #6449 

Since we now support `break` statement in for-loop, we could move loop condition into loop body for the ease of further optimizations.

For example,
```
for { } lt(i, exponent) { i := add(i, 1:u256) }
{
    result := mul(result, base)
}
```
can be rewrite to
```
for { } true { i := add(i, 1:u256) }
{
    if lt(i, exponent) { break }
    result := mul(result, base)
}
```

At this moment, seems like loop conditions expressions are the only exception of SSA transformation. This can cause trouble when we want to apply optimizations which relies on SSA transformation. (#6449 is an example)

And the control flow graph should be isomorphic(?) before and after the transformation. So it probably should not be harder to optimize if we analyze the control flow correctly.

**Comment by sifmelcara** [comment]
Inspired by #6492 , we may also want to move loop post to the end of loop body.
```
for { } 1 { sstore(1, 2) }
{
    stop()
}
```
`sstore(1, 2)` in the above snippet is obviously a dead code, but current DeadCodeEliminator is unable to remove it.

**Comment by chriseth** [comment]
Since we are planning some transforms that would have problems with for loop conditions, it is probably now a good idea to introduce this transform. At the same time, it would be good to undo the transform again in the cleanup phase of the optimizer, since for loops with actual conditions are much easier to read.

The post block cannot be easily moved as soon as there is a `continue` statement in the loop, so we should be careful about it. Removing dead code in for loops could be its own optimizer step, since I guess it will often lead to the loop being transformed to a simpler construct altogether. It might also make sense to consider (tentative) loop unrolling.

**Comment by sifmelcara** [comment]
My plan on this issue:

1. Rename `ForLoopInitRewriter` to `ForLoopRewriter`
2. Add code that move loop condition into loop body to `ForLoopRewriter`.
3. Open a separate issue or PR to address the issue about DeadCodeEliminator and post block.

**Comment by chriseth** [comment]
For loops are delicate structures both with regards to scoping and with regards to control flow. I think the optimizer would be easier to verify if those two steps were kept separate. Otherwise, it sounds great!

**Comment by sifmelcara** [comment]
The examples above are wrong... we need to invert the cond expressions when move them into the loop. i.e `for {} c {} {}` should be rewrite to `for {} true {} { if not(c) { break } }`

**Comment by chriseth** [comment]
Ah right! Also note that you need to use `iszero` instead of `not` (`not` is bitwise negation).
