### ISSUE TITLE
PC for JUMPDESTS of functions in compiler meta data

### ISSUE THREAD

**Issue by MrChico** [ethereum/solidity#6485]
## Abstract

For symbolic analysis of solidity generated bytecode, it is often useful to be able to extract the program counter associated with a particular solidity function. I propose to add an optional field to the meta-data AST called `pc`, which for nodes associated with functions contains the JUMPDEST associated with that method.

## Motivation

Currently, the only way to figure out the JUMPDEST associated with a particular solidity function is to reverse engineer it from the sourcemapping in the AST, which is cumbersome and error prone. Having pc counters associated with solidity methods would make formal analysis of solidity generated bytecode a lot easier.

## Specification

Here's the suggested node AST structure of the function.
`  function add(uint x, uint y) internal pure returns (uint z) {`:
The new entry being the `pc` header.
```
              {
                "attributes": {
                  "constant": true,
                  "documentation": null,
                  "implemented": true,
                  "isConstructor": false,
                  "modifiers": [ null ],
                  "name": "add",
                  "payable": false,
                  "scope": 40,
                  "stateMutability": "pure",
                  "superFunction": null,
                  "visibility": "internal"
                },
                "children": [...],
                "id": 39,
                "name": "FunctionDefinition",
                "src": "153:101:0",
                "pc": 129
              }
```

**Comment by haltman-at** [comment]
Not on the Solidity project, just commenting as someone else who might find this useful -- due to inheritance, there'd have to be a bit more to it, wouldn't there?  Like, a function in `Base` could have one PC in `Base` but a different PC in `Derived`, right?  If it just listed the PC in `Base`, that would be pretty incomplete information.

**Comment by chriseth** [comment]
I would defer such features until we have proper debugging metadata. I think adding the PC to the AST is not a good solution because the AST mostly concerns syntactical features. Furthermore, connecting the bytecode offset start to a function is a very delicate matter. The PC is only really determined at the very last stage in the compiler called the assembly stage. At this point, functions are fully erased from the data structures that the compiler deals with. Furthermore, more or less anything can happen to a function at these stages: Two functions could be combined, a function might even be split into two separate code pieces and of course it could be fully inlined to whereever it is used. On top of that, we have the added complications that due to inheritance and the fact that a function can be used both in creation and deployed context, it is not really clear which function we are referring to.

**Comment by MrChico** [comment]
@chriseth here is the issue for `PC` values for functionss and modifiers. If you think the AST is the wrong place for this, I'm open for other suggestions

**Comment by MrChico** [comment]
Specifically, it would be very helpful to get `PC` values for:
- Functions, especially internal functions
- Modifiers
- Loop headers 

an additional thing I mentioned in the talk is to also get the (stack or memory) location or the arguments given to internal functions, but perhaps this is better to keep in a separate issue?

**Comment by chriseth** [comment]
@MrChico is https://github.com/ethereum/solidity/pull/8868 sufficient for your needs for now? I would prefer to close this issue and create new issues for further features.

**Comment by chriseth** [comment]
The core of this issue has been implemented both in the old and the new code generator. Please create new issues for further information you need.
