### ISSUE TITLE
[Yul] Assert that AST is still valid every time after applying optimizer component

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#6495]
In `libyul/optimiser/Suite.cpp`, we might want to do some "sanity check" every time after applying an optimizer component to AST.

By doing this we can ensure that every AST transformation is valid when running `solc`.

(Inspired by #6492)

**Comment by bshastry** [comment]
Won't such a sanity check involve parsing the AST after each step, which is expensive? We could probably use this piece of code

https://github.com/ethereum/solidity/blob/bf653b004eb1168ac84a7c0532ba9ea66c415d0b/test/tools/yulopti.cpp#L89-L114

in here

https://github.com/ethereum/solidity/blob/bf653b004eb1168ac84a7c0532ba9ea66c415d0b/test/libyul/YulOptimizerTest.cpp#L71

and then add

```
if (!parse(m_obtainedResult))
  return false;
```

here

https://github.com/ethereum/solidity/blob/bf653b004eb1168ac84a7c0532ba9ea66c415d0b/test/libyul/YulOptimizerTest.cpp#L274

What do you think?

P.S. Probably better to add an additional method such as `YulOptimizerTest::parseObtainedResult` that looks very much like `YulOptimizerTest::parse` with `s/m_source/m_obtainedResult/` and minus the assignment of resulting ast to private members.

P.P.S. Doing sanity checking inside YulOptimizerTests is redundant because if a test input results in unparseable AST post optimization, it is going to fail that test (assuming the expectation is correctly encoded which is fair) regardless.

**Comment by chriseth** [comment]
I think parsing is not really required, because we perform optimizer steps based on its memory representation. So I think the checks we can do would be those performed by the AsmAnalyzer.

I would assume that the checks are optional and only performed e.g. during fuzzer runs, right?

**Comment by sifmelcara** [comment]
@bshastry Sorry for the late reply. Yes it is expensive but probably worth it? Typically smart contracts are `< 1000` lines so the overhead should not be noticeable from the user side.

@chriseth I agree. Using `AsmAnalyzer` makes sense.

> I would assume that the checks are optional and only performed e.g. during fuzzer runs, right?

At minimum we should do this sanity check when fuzzing. Not sure if we should turn on the check by default though..
