### ISSUE TITLE
Return back loose assembly and forbid optimizer to touch its output

### ISSUE THREAD

**Issue by 3sGgpQ8H** [ethereum/solidity#6517]
## Abstract

In version 0.5.0 of Solidity compiler loose inline assembly was permanently disabled in favor of strict function-style inline assembly.  In my opinion, strict assembly is not a full replacement for loose assembly, thus loose assembly need to be returned back.  Also optimizer should be forbidden to touch byte code generated from inline assembly sections containing loose assembly.

## Motivation

In mainstream languages, inline assembly is traditionally used for two purposes:

1. to access low-level features of the platform, that are not directly accessible via high-level language constructions and
2. to manually optimize performance-critical code parts.

In Solidity, strict inline assembly is good for the first purpose, and is actually bad for the second, because Solidity compiler inserts stack-management opcodes and jumps between opcodes written by developer, and even applies optimizer on top of the byte code generated from assembly, so developer actually has little control on final byte code.
In contract, loose inline assembly is quite bad for the first purpose, because developer has to write lots of complicated and error-prone glue code between low-level instructions that actually access desired low-level features of EVM; but loose assembly is actually good for the second purpose, and would be even better if optimizer will be forbidden to touch byte code generated from loose inline assembly.

While for high-level business logic loose inline assembly is usually a bad choice, because of its complexity and error-proneness, for low-level libraries, such as [this one](https://github.com/abdk-consulting/abdk-libraries-solidity/blob/master/ABDKMath64x64.sol), it could significantly decrease gas cost.

## Specification

1. Make loose inline assembly available again, probably only when explicitly enabled by command-line option, and probably producing warning messages about its unsafety.
2. Make optimizer to skip byte code generated from inline assembly sections containing loose assembly.

## Backwards Compatibility

This change is 100% backward compatible with 0.5.x versions, and, even more, it partially restores backward compatibility with 0.4.x versions, that was broken by permanently disabling loose inline assembly.

**Comment by chriseth** [comment]
We currently do not plan to re-introduce loose assembly mainly because it complicates the whole compiler stack and also makes it very hard to ensure certain properties of the whole contract (e.g. pure and view functions), especially since loose inline assembly can interfere with any outer parts and this is very hard for the compiler to detect properly.

I am not aware of any jumps being inserted between opcodes by the compiler, could you please point me at an example?

As far as sub-optimal code being generated, this is unfortunately still true. We are working on making the optimizer generate good code for all uses. It would be nice if you could point us at examples that show how manually written assembly code is better than the one generated by the optimizer. This helps us improving the optimizer such that everyone can benefit automatically.

**Comment by 3sGgpQ8H** [comment]
Inline assembly inserts jumps for constructs `if`, `switch`, and `for`.

Inline assembly is being used for manual optimizations even with compilers that are known to have best in class optimizers, so I don't think necessity of loose inline assembly is anyhow related to whether optimizer is perfect or not.

Here is an example, where function style assembly makes logic more complicated.  Suppose I have local variable `x` and I want to do something in case `x` is zero.  For functional assembly I do:

    if (izzero (x)) { ... }

for loose assembly I do:

    lbl
    dupN // put `x` on top of the stack
    jumpi
    ...
    lbl:

So no `iszero` opcode at all.

**Comment by chriseth** [comment]
Ok, sure, if you use control-flow constructs, jumps are inserted, but they are not inserted "between opcodes" - that's what confused me.

Perhaps I would like to re-state one of the design principles of Solidity, which is another justification to remove loose assembly: Correct code is more important than efficient code and this also includes manual overrides since almost all of the big issues in the past were related to manual overrides.

Concerning your code: the "iszero removal before jump" is part of 0.5.6, so Solidity generates exactly the code you mention.

I know that you can always find manually optimized inline assembly that is better than the current optimizer of Solidity. My point is that it is much better to add appropriate optimizer rules so that everyone automatically benefits from them instead of everyone individually searching for the same optimizations all over again and potentially also making mistakes there.

If you find any deficiencies with the optimizer, please open issues so we can fix them.
