### ISSUE TITLE
Have modifiers JUMP rather than inlining

### ISSUE THREAD

**Issue by rainbreak** [ethereum/solidity#6584]
The code of a modifier is currently copied into the function to which it is applied. Instead, I suggest to treat the modifier more like an internal function and to use a `jump` instead.

This has some benefits:

1. Reduces codesize of contracts through code reuse.
2. Some static analysis can be made more efficient (e.g. lemmas can be made for internal functions much more easily than inlined code).
3. Modifiers would no longer contribute to "stack too deep" errors.

**Comment by livnev** [comment]
To be precise, what seems to happen when you use modifiers is that the execution jumps to a new location in the bytecode to execute the modifier, similarly to "internal calls", however the code that it jumps to seems to be duplicated for every use of the modifier, instead of sharing the same code like you would expect.

**Comment by chriseth** [comment]
This would require adding a "jump in PC" and a "return PC" as arguments to each modifier. I think we have to revisit this when we implement modifiers in the Solidity -> Yul code generation, but I don't think this will be feasible to implement with the old code generator.

**Comment by chriseth** [comment]
For modifiers of the form `{... _;}` this might be doable.

**Comment by nventuro** [comment]
I just came accross [this article](https://blog.polymath.network/solidity-tips-and-tricks-to-save-gas-and-reduce-bytecode-size-c44580b218e6), which recommends using internal functions instead of modifiers to reduce bytecode size.

I think the existence of these suggestions is an issue: people should not rely on quirks of the compiler's implementation and choose between sintactic constructs because of the bytecode they generate. This is the same case as the one described [on this PR](https://github.com/ethereum/solidity/issues/6075#issuecomment-472622304).

We should make sure these sort of codegen decisions are taken by the optimizer based on user settings (e..g the 'runs' parameter, or a size vs 'speed'/gas switch), and not by how a developer wrote chose to write their code.

(I know much of this will become better once the Solidity -> Yul generation is complete and that work is very much underway, I just wanted to emphasize the importance of this point).

**Comment by chriseth** [comment]
Let's try to see if this is doable in a non-dangerous way for `{... _;}`-modifiers

**Comment by nventuro** [comment]
I think this issue is still very much valid, and the suggestion concrete (unless the behavior for modifiers has recently changed?).

**Comment by cameel** [comment]
It did not look very promising when @chriseth tried to improve it recently (https://github.com/ethereum/solidity/pull/12465#issuecomment-1004009007):

> I actually think that it's more complicated to implement it in the new codegen :)
>
> Having said that, we really should check that it provides a good improvement in "real" contracts.

In any case, there seems to still be some interest in it so I'm reopening.

**Comment by gabrielkrell** [comment]
> Having said that, we really should check that it provides a good improvement in "real" contracts.

Bumping this I guess. One of the large contracts my team is working has 24 `onlyOwner` functions. Turning those modifiers into internal functions (of the form `{... _;}`) reduces our deployed size by 0.763 KiB, which is significant as we are pretty close to the 24KiB limit. Hate to see good language features disabled by the compiler.
