### ISSUE TITLE
Explicit conversion of bool to int

### ISSUE THREAD

**Issue by graup** [ethereum/solidity#659]
I cannot do this:

```
function C(bool flag) {
    test = int(flag);
}


Error: Explicit type conversion not allowed.
    test = int(flag);
           ^-------^
```

Is this intentional?

**Comment by chriseth** [comment]
Yes, this is intentional to avoid unwanted conversions. You can change your code to
`test = flag ? 1 : 0` to make it work.

**Comment by graup** [comment]
Oh, with the ternary operator it is indeed very easy. Didn't know Solidity has that, but now I do see it mentioned in [the guide](http://solidity.readthedocs.io/en/latest/control-structures.html#control-structures).

Thanks!

**Comment by wchargin** [comment]
Unfortunately, the `flag ? 1 : 0` version (a) has a subtle footgun that
makes it easy to use incorrectly, and (b) is slower than the direct
conversion. Consider the following contract, which tries to form a mask
by shifting a boolean by a constant:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Benchmark {
    function boolShiftedBad(bool _b) external pure returns (uint256) {
        return (_b ? 1 : 0) << 8;
    }
    function boolShiftedSlow(bool _b) external pure returns (uint256) {
        return uint256(_b ? 1 : 0) << 8;
    }
    function boolShiftedFast(bool _b) external pure returns (uint256) {
        uint256 _bInt;
        assembly {
            // SAFETY: Simple bool-to-int cast.
            _bInt := _b
        }
        return _bInt << 8;
    }
}
```

The function `boolShiftedBad` tries the obvious approach as suggested
in this thread. But in fact this function always returns `0`, even when
called with `true` as its argument! This seems like it has to do with
the literals in `_b ? 1 : 0` being treated as `uint8`s for some reason.
The assembly shows an `0xff; and` after the `shl`, and replacing `<< 8`
with `<< 7` hides the problem (the code returns 127).

If the right-hand side of the shift is a `uint256` variable (`<< _v`),
then Solidity helpfully issues a warning. But if it's a `uint8`
variable---which is entirely reasonable, since `uint8 _v` indicates
which bit to select in the `_b << _v` mask---then there is no warning!

Explicitly converting `_b ? 1 : 0` to `uint256` works, as shown in
`boolShiftedSlow`. However, this approach appears to have an overhead of
40 gas, even with the optimizer enabled and set to `runs: 999999`. (Also
with `runs` set to `200` or `0`; it makes no difference.) Thus:

```
boolShiftedSlow(false): 21551 gas
boolShiftedSlow(true):  21553 gas
boolShiftedFast(false): 21511 gas
boolShiftedFast(true):  21523 gas
```

Looking at the assembly, it looks like the `? 1 : 0` literally compiles
to a jump, plus an `& 0xff`(?):

```
      0x08 /* "contracts/Benchmark.sol":322:323  8 */
      dup3 /* "contracts/Benchmark.sol":307:309  _b */
      tag_24 /* "contracts/Benchmark.sol":307:317  _b ? 1 : 0 */
      jumpi
      0x00 /* "contracts/Benchmark.sol":316:317  0 */
      jump(tag_25) /* "contracts/Benchmark.sol":307:317  _b ? 1 : 0 */
    tag_24:
      0x01 /* "contracts/Benchmark.sol":312:313  1 */
    tag_25: /* "contracts/Benchmark.sol":307:317  _b ? 1 : 0 */
      0xff /* "contracts/Benchmark.sol":299:318  uint256(_b ? 1 : 0) */
      and
      swap1 /* "contracts/Benchmark.sol":299:323  uint256(_b ? 1 : 0) << 8 */
      shl
```

This seems pretty unfortunate, since this conversion doesn't actually
require *anything* to be done at runtime. In my production contract, I
saved hundreds of gas by making this change to a few places that occur
in a loop.

IMHO, avoiding "unwanted conversions" is definitely desirable, but explicitly
writing the cast `uint256(_b)` is enough to signal that this conversion is, in
fact, wanted. It'd be more readable, more safe, and more efficient.

<details>
<summary>Driver script</summary>

```javascript
const hre = require("hardhat"); // v2.8.0

async function main() {
  await hre.run("compile");
  const Benchmark = await hre.ethers.getContractFactory("Benchmark");
  const benchmark = await Benchmark.deploy();
  await benchmark.deployed();

  // First, demonstrate that omitting an explicit `uint256` cast leads to the
  // wrong answer.
  for (const input of [false, true]) {
    const result = await benchmark.boolShiftedBad(input);
    console.log(`boolShiftedBad(${input}) = ${result}`);
  }
  console.log();

  for (const method of ["boolShiftedSlow", "boolShiftedFast"]) {
    for (const input of [false, true]) {
      const result = await benchmark[method](input);
      if (!result.eq(input << 8)) {
        throw new Error(`wrong answer for ${method}(${input}): ${result}`);
      }
      const gas = await benchmark.estimateGas[method](input);
      console.log(`${method}${`(${input}):`.padEnd(8)} ${gas} gas`);
    }
  }
}

main().catch((e) => {
  console.error(e);
  process.exitStatus = 1;
});
```

</details>

**Comment by chriseth** [comment]
I think the best way to solve this is to create a free function of the following form:
```
function toUInt256(bool x) pure returns (uint r) {
  assembly { r := x }
}
```
It will very likely be inlined and as efficient as adding a conversion function to the compiler, with the added benefit that you can use "follow definition" to look up the semantics of this conversion function.
