### ISSUE TITLE
SMTChecker works in solc v. 0.4.25

### ISSUE THREAD

**Issue by sunbeomso** [ethereum/solidity#6644]
## Description

I wonder whether my usage of SMTChecker is correct or not.
According to Solidity official docs, SMTChecker is enabled starting from "solc v. 0.5.0":
https://solidity.readthedocs.io/en/v0.5.6/050-breaking-changes.html?highlight=smtchecker

However, I checked that SMTChecker works, although the solc version installed in my machine is 0.4.25 (I tested on macOS 10.14).

## Question
Regarding the above situation, I would like to ask particularly two things:
[Q1.] Am I using SMTChecker properly? I don't understand why SMTChecker works on solc v 0.4.25 . 

[Q2.] If my current usage is not proper, can you recommend any good mitigations to run the latest SMTChecker on Solidity code written in older version?

Although solc currently changes rapidly, it seems that there are lots of code that fits in older version of solc in practice.

**Comment by leonardoalt** [comment]
Hi @SunBeomSo ,
the SMTChecker component is enabled in 0.4.x as well, that comment in the docs just highlights that the SMTChecker is the alternative to the old `--formal` option which was removed in 0.5.0.
The difference you will see in the usage of the SMTChecker in different versions of the compiler is that the older a version is, the fewer features the SMTChecker has, especially since we've recently added many features in the 0.5.x versions.

**Comment by sunbeomso** [comment]
@leonardoalt thanks for the response. I close the issue.
