### ISSUE TITLE
[soltest] Incorrect re-encoding of left-aligned bytes.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6697]
```
 Contract:
    contract C {
        function f() public pure returns (bytes32) {
            return bytes32(bytes1(0xFF));
        }
    }

  Expected result:
  // f() -> 0xff

  Obtained result:
  // f() -> 0xff
```

The suggestion should either be ``0xff00...00`` or ``left(0xff)``.

**Comment by ekpyron** [comment]
Ping @erak ;-).

**Comment by axic** [comment]
Tested it now, and this is what it auto-filled out:
```
    contract C {
        function f() public pure returns (bytes32) {
            return bytes32(bytes1(0xFF));
        }
    }
// ====
// compileViaYul: also
// ----
// f() -> 0xff00000000000000000000000000000000000000000000000000000000000000
```

So this issue seems to be fixed. Having `left(0xff)` would be nice, but I wouldn't say it is a necessity.

In a separate issue perhaps we could argue about a canonical representation the files should use, including all different number/bytes/string encodings.
