### ISSUE TITLE
[SMTChecker] Analyze Mythril and Slither examples

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#6721]
Compile the [Mythril](https://github.com/ConsenSys/mythril) and [Slither](https://github.com/crytic/slither) examples with the SMTChecker enabled and analyze the output looking for:
- False negatives (bugs)
- False positives
    * Why do they happen, what is the limitation?
    * Lack of expressiveness or support to the language?

**Comment by axic** [comment]
Anyone started this?

**Comment by leonardoalt** [comment]
Don't think so.

**Comment by leonardoalt** [comment]
We should do another round of this.

**Comment by pgebal** [comment]
Versions:
solc 0.8.20
mythril 0.23.24

On Mythril:
Unfortunately example contracts use `pragma 0.5.0` https://github.com/Consensys/mythril/tree/develop/solidity_examples
I compared mythril results with SMTChecker results only on the contract from Mythril tutorial: https://github.com/pgebal/mythril/blob/refactor_to_sol_0.8/solidity_examples/Exceptions.sol

Both programs reported the same warnings on failed assertions, although I had to run Mythril with `-t` parameter higher than default.
- SMTChecker  results after running  `solc --model-checker-targets all --model-checker-engine all --model-checker-solver z3`  https://github.com/pgebal/mythril/blob/refactor_to_sol_0.8/solidity_examples/Exceptions_smodel_checker
-  Mythril results after running `myth analyze -t 4`  https://github.com/pgebal/mythril/blob/refactor_to_sol_0.8/solidity_examples/Exceptions_mythril_t_4

Reported failed assertions are true positives and all failing assertions were reported in both cases.

SMTChecker was better on reporting `uint` overflow. Mythril looks bugged. It reported invalid source locations and 2 overflows instead of 1.
@leonardoalt

**Comment by pgebal** [comment]
On Slither:
I used the following script to run slither and SMTChecker https://github.com/pgebal/slither/blob/compare/examples/printers/run.py on example contracts. I compared results manually and no big difference there. There are no assertions in solidity code and contracts trigger only uint overflow warnings.

**Comment by leonardoalt** [comment]
@pgebal ok great, thanks!
