### ISSUE TITLE
``make_vector`` evaluates its arguments in undefined order

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#6789]
Since the order in which the expressions of function arguments are executed is undefined in C++, the new ``make_vector`` helper might have unexpected behaviour, e.g.:

``make_vector<SomeType>(visit(A), visit(B))`` might (and probably will) call ``visit(B)`` before ``visit(A)``, while one might expect that it first calls ``visit(A)`` and then ``visit(B)``.

There's no nice and easy way around this. With C++17 the standard requires that in a function call the expression determining which function to call is evaluated before the arguments, so then we could change the syntax to something like:

``make_vector<SomeType>(visit(A))(visit(B)).get()``

There might be better solutions, but it'd be good to solve this issue in some way.

**Comment by peroket** [comment]
Hello, I would like to take part in the community, and this task seems like a good one to start with.

One solution would be to use the vector `initializer_list' constructor. The order for those is defined left to right. The constraints is that all types need to match, so it may require casting first. That is a solution for light types though, as the values will be copied.

Otherwise I could propose a syntax like
```c++
auto vector = (make_vector<int>() << visit(A) << visit(B)).get() // Explicit get
std::vector<int> vector2 = make_vector<int>() << visit(A) << visit(B); // Implicit cast
```

What do you think?

@ekpyron @cameel

**Comment by cameel** [comment]
Sorry for a late response. I think we'll actually need @ekpyron's opinion here. This issue is marked only as a candidate rather than `good first issue` because, while it'll be easy to implement once we have the right idea, it needs some discussion before we get what we want.

Personally I like your explicit get syntax. Stacked `()` operator never reads well. So as long as it enforces the order too I'd be fine with that.

To be honest though, the fact that these expressions do enforce order does not stand out enough to me so I'd always leave a comment anyway losing the conciseness. In that case I'm not sure if keeping it simple isn't actually the best choice:
```c++
T a = visit(A);
T b = visit(B);
std::vector<T> v = make_vector<T>(move(a), move(b));
```

**Comment by peroket** [comment]
So maybe the best is to not provide such a functionality at all, and let each person solve that problem locally (meaning remove the helper function)?
It's not used in many places, so I can do that easily as well.
