### ISSUE TITLE
add a new instruction

### ISSUE THREAD

**Issue by unicornonea** [ethereum/solidity#6941]
If I want to add a new instruction in the solidity compiler, I have some confusions:
 How I pass all the unit tests in test directory?
And how to avoid conflicts with the current code?

**Comment by ekpyron** [comment]
You can check https://solidity.readthedocs.io/en/v0.5.9/contributing.html#running-the-compiler-tests for information about the tests - basically you'll need a running instance of ``aleth`` (https://github.com/ethereum/solidity) in test mode and run ``scripts/tests.sh``.

For adding a new instruction (I guess you mean a non-standard EVM instruction?) I think you mostly need to add it to the list in ``libevmasm/Instruction.h`` (giving it a previously unused 8-bit value, e.g. ``0xfb``). Then you need to define its name and information about it (e.g. number of arguments and return values, etc.) in the maps in ``libevmasm/Instruction.cpp``. After that you should be able to use it in inline assembly already and you can also emit it during code generation.

**Comment by unicornonea** [comment]
@ekpyron Thanks for your great answer. I've passed all the test cases, and  added a new instruction successfully. But after adding a non-standard EVM instruction, almost all of the test cases cannot be passed again. How I modify the original test cases so that they can be compatible with the new instruction?

**Comment by ekpyron** [comment]
I don't think that any of the existing tests should fail due to adding a new EVM instruction. If they do there might very well be a bug in your change (i.e. you might have inadvertently added the new instruction to the list in such a way that the byte value of existing instructions changed or something like that). We won't be able to properly help you here without knowing what you do exactly, though.
