### ISSUE TITLE
Failed semantic tests have strange "expected result v.s obtained result" formatting

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#6946]
To reproduce this issue, first intentionally modify a semantic test test case's expected output, for example
```
--- a/test/libsolidity/semanticTests/abiEncoderV2/calldata_array_dynamic_index_access.sol
+++ b/test/libsolidity/semanticTests/abiEncoderV2/calldata_array_dynamic_index_access.sol
@@ -23,7 +23,7 @@ contract C {
 // ====
 // EVMVersion: >homestead
 // ----
-// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
+// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 88
 // g(uint256[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
 // g(uint256[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
 // h(uint8[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
```

Then run the tests:
```
./build/test/soltest -p -- --ipcpath /tmp/testeth/geth.ipc --evm-version byzantium --no-smt --testpath ./test
```

it outputs
```
error: in "semanticTests/abiEncoderV2/calldata_array_dynamic_index_access": Test expectation mismatch.
Expected result:
// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 88
// g(uint256[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// g(uint256[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// h(uint8[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// j(bytes): 32, 3, hex"AB11FF" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 0, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 1, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 4, left(0xFF791432)

Obtained result:
// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, hex"0000000000000000000000000000000000000000000000000000000000000020"
Warning: Encoding does not match byte range. The call returned 224 bytes, but 224 bytes were expected.
// g(uint256[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// g(uint256[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// h(uint8[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// j(bytes): 32, 3, hex"AB11FF" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 0, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 1, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 4, left(0xFF791432)

Attention: Updates on the test will apply the detected format displayed.

```
I think it does not properly print the actual obtained result?

I guess something went wrong in the following function
https://github.com/ethereum/solidity/blob/a6cc296cd9b9221df9a203cc9e85cb45f0086756/test/libsolidity/util/TestFunctionCall.h#L143-L154

cc author of the file @erak , thanks!

**Comment by erak** [comment]
Thanks for the report. I can reproduce this issue and it seems to be related to a feature that was not fully implemented yet: When there's a mismatch in the expected and the actual result, the contract ABI is consulted in order to retrieve the correct type for that particular return value. This mechanism is not handling all types at the moment, which results in this issue. 

We're working on it and we'll also write up a proper documentation after.

**Comment by sifmelcara** [comment]
> the contract ABI is consulted in order to retrieve the correct type for that particular return value

Could you elaborate the reason why test suite need to know the type of encoded data? Is this for pretty-print purpose?

Thanks!

**Comment by erak** [comment]
Sure! The purpose is to help developers to interactively update their semantic tests during development using one of our tools called `isoltest`. It provides an auto-update routine which can correct the expectations (e.g. in the case you've mentioned). And in order to provide "human-readable" formats of values passed to or returned by a call to the contract, the ABI is consulted to provide the type information needed to do this formatting.

This is very helpful if a change in the compiler needs a lot of semantic tests to be updated manually, or if you're developing a feature in test-driven manner or simply to correct typos you made. Does this answer your question?

**Comment by sifmelcara** [comment]
Yes, thanks!
