### ISSUE TITLE
Allow longer unicode escapes

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#7089]
## Abstract

Solidity currently allows unicode escapes in strings, in the form `\uNNNN`.  However, this is only sufficient to cover the basic multilingual plane.  Anything beyond that must first be encoded as UTF-8 and then have its bytes entered manually.

## Motivation

Add unicode escapes covering the entire range of unicode code points.  One could perhaps borrow Javascript's syntax for this, which is `\u{hex}`, where `hex` consists of any number of hex digits -- so long as the resulting number is, of course, at most 0x10FFFF and not a surrogate.  Otherwise it should be a compile error.

## Specification

See above for one possibility.

## Backwards Compatibility

If it's implemented as suggested above, there should be no backwards incompatibility, as currently `\u{` forms an invalid escape sequence.  If it's implemented some other way, who can say?  That said, even if you don't want to handle it the way suggested above, it should be easy to handle it in a way that avoids backwards incompatibility.

**Comment by christianparpart** [comment]
Whereas `\u{hhh....h}` may be equivalent to what JS is doing, i think it should still be limited to the number of hex digits being passed on (i.e. 8).

What C/C++ has for that, is `\U` to express 32bit escape values (such as UTF-32), that should then be enough for all of current standards Unicode, as far as I remember?

Reference: https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences

**Comment by axic** [comment]
![Screenshot 2020-04-06 at 12 03 24](https://user-images.githubusercontent.com/20340/78552011-a1501500-77fe-11ea-9885-72fd54747959.png)

@christianparpart does that mean you propose uppercase `N` as an escape, such as `\UNNNNNNNN`?

**Comment by cameel** [comment]
Yeah, the C++ version would suffice here. It's an alternative to the JS syntax which simply lets you use less digits for convenience. Since Unicode code points go only up to `0x10FFFF`, you'll always have at least two leading zeros if you strictly require 8 digits. But it adds braces which makes the escapes longer again so it's a wash.

BTW, just for reference, here's more about how JS handles unicode escapes, including the `\u{}` syntax: https://mathiasbynens.be/notes/javascript-unicode

**Comment by axic** [comment]
Why don't we just accept `\uNNNN` and `\uNNNNNN`?

**Comment by cameel** [comment]
I don't think that inventing yet another way to write these escape sequences is a good idea :). Unless there's a very good reason for it but I don't see one. I think that using syntax that's already common elsewhere would make it more intuitive for users coming from other languages even if it's longer.

**Comment by axic** [comment]
As a quick check:
- C/C++ -- `\uNNNN`, `\UNNNNNNNN`
- Python -- `\uNNNN`, `\UNNNNNNNN` (https://docs.python.org/3/howto/unicode.html)
- Javascript -- `\uNNNN` and `\u{hex}` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#String_literals)
- Rust -- ` \u{hex}`, where `hex` can be up to 6 nibbles (https://doc.rust-lang.org/reference/tokens.html#unicode-escapes)
- Ruby -- `\uNNNN` and `\u{NNNNNN}` (https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Literals)
- Kotlin -- `\uNNNN` (https://kotlinlang.org/docs/reference/basic-types.html#characters)
- Java -- `\uNNNN` (https://docs.oracle.com/javase/specs/jls/se13/html/jls-3.html)

I am definitely not in favour of the `\u{hex}` syntax. I could accept `\uNNNNNN` and `\UNNNNNNNN`.

**Comment by cameel** [comment]
It's a mess. But `\uNNNNNN` would just make the mess bigger :) Of the two, I'd vote for `\UNNNNNNNN`.

**Comment by chriseth** [comment]
I would not spend too much time on this - why would you use unicode escape sequences at all in source code? It is very hard to verify that the sequence is the right one.

**Comment by axic** [comment]
@chriseth are you proposing to remove it entirely? I think we should either support the entire range of Unicode code points or none.

**Comment by chriseth** [comment]
No, but I think we should not spend so much time on it, unless we find a way to make these unicode escapes "readable".

**Comment by axic** [comment]
I don't think we have spent too much time on it, to me it is clear we have two options only: `\uNNNNNN` (a new invention, but similar to `\u{hex}` of Javascript/Rust/Ruby) or `\UNNNNNNNN` (shared with C/C++/Python). Nobody wants `\u{hex}`.

There is a "readable" version supported by multiple languages where the code point name is inserted, such as `\N{GREEK CAPITAL LETTER DELTA}` (from Python). We definitely don't want to support that as that would imply having a huge Unicode translation table.

**Comment by christianparpart** [comment]
I was a little quick in self-assigning, but do we still want to persue this? If so, I'd like to start working on this.

**Comment by hughescr** [comment]
`\uNNNNNN` would be a breaking change
`\UNNNNNN` (or` \u{NNNNNN}`) wouldn't
The current source `"\u1D80AB"` would yield an error if `\uNNNNNN` is adopted, but should be valid currently (it'd currently be a 3-character string of `U+1D80`, `U+0041`, `U+0042`: `unicode"აAB"`) but it should parse as an invalid codepoint under `\uNNNNNN`.
`"\u100000"` would be even worse, currently, that would be the 3-character string `U+1000`, `U+0030`, `U+0030`: `unicode"က00"`, but under `\uNNNNNN` would be the single character `U+1000000` or `unicode"􀀀"`

One nice benefit of `\u{NNNNNN}` vs `\UNNNNNN` is that the delimiting `{}` mean that you can allow upto 6 `N`s inside the braces and not require always exactly 6 `N`s, since most of the high codepoints are only 5 hex digits not 6, so it's a little cleaner to read and write, and slightly more typo-proof without all the extra leading 0s.

**Comment by haltman-at** [comment]
Hi!  Could this be reopened?

**Comment by ekpyron** [comment]
Are there any particular strong reasons for wanting this? Our current policy is to mostly keep issues around that have a high enough demand and priority, s.t. we can expect to actually implement it in the foreseeable future (i.e. 6 to 12 months) - this issue here I'd consider "nice to have", but quite low priority, so I'm not sure it qualifies.

**Comment by haltman-at** [comment]
Not really a strong use case to be honest, I just opened it because it was a consistency thing and it bugged me. :P  Same motivation as a lot of my issues, really. :P
