### ISSUE TITLE
msg.sender.call.value(address(this).balance); should produce a warning

### ISSUE THREAD

**Issue by ColonelJ** [ethereum/solidity#7096]
## Description

When entering a statement such as `msg.sender.call.value(address(this).balance);` which doesn't actually do anything since the last `()` is missing, you'd expect to get a warning because the statement has no side effects and the value isn't used (as you do for something like `1+1;` where you get "Warning: Statement has no effect.")  However, you get no warning whatsoever.

## Environment

- Compiler version: 0.5.10
- Target EVM version (as per compiler settings): compiler default
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: N/A
- Operating system: N/A

## Steps to Reproduce

Enter the following code in Remix and set compiler to 0.5.10:

```solidity
pragma solidity >=0.4.24;

contract MissingSend
{
    function() external payable {}

    function withdraw()
    public
    payable
    {
        if (msg.value >= 100)
        {
            msg.sender.call.value(address(this).balance);
        }
    }
}
```

**Comment by chriseth** [comment]
Not even `msg.sender.call.value(3)` seems to produce a warning.

**Comment by erak** [comment]
This seems to not be easily solvable. We're dealing with the two concepts of pure statements (which are compile-time constant) and state mutabilities. Pure statements like `1+1;` will result in a `"Statement has no effect."` warning, whereas `msg.data;` is not pure and thus does not generate this warning.

On the other hand, `msg.data;` has it's state mutability set to `pure` and this is used to generate a warning for
```
contract C {
    function f() public {
        msg.data;
    }
}
```
```
Warning: Function state mutability can be restricted to pure
function f() public {
^ (Relevant source part starts here and spans across multiple lines).
```

But since function state mutability set to pure does not imply side-effect-freeness in memory, it can't be used to generate the desired warning.

The reported code makes use of `msg.sender` which implies that function state mutability cannot be pure any more and would even pass checks that prefer state mutability over pureness at this point. But that particular member access could be subject to change.

**Comment by chriseth** [comment]
Maybe it is time to define a new property just for this use-case. @leonardoalt would this be the same side-effect-freeness that we need to enforce inside expressions for invariants?

**Comment by chriseth** [comment]
Created an issue to define side-effect-free-ness: https://github.com/ethereum/solidity/issues/7118

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/solidity/issues/2707

**Comment by leonardoalt** [comment]
@chriseth Yes it should be the same

**Comment by erak** [comment]
Shall we remove this in favour of https://github.com/ethereum/solidity/issues/7118 from the project already? We could also wait until 0.5.12 planning.

**Comment by chriseth** [comment]
Closing this since we now have the new notation.
