### ISSUE TITLE
address payable as mapping type's key

### ISSUE THREAD

**Issue by sifmelcara** [ethereum/solidity#7149]
## Abstract

Currently `mapping (address payable => uint256)` causes a parsing error:
```
ParserError: Expected '=>' but got 'payable'
mapping (address payable => uint) a;
^-----^
```

Is there any reason that this mapping type is not supported?

**Comment by leonardoalt** [comment]
After reading https://github.com/ethereum/solidity/pull/4926#discussion_r216245203 and https://github.com/ethereum/solidity/pull/4926 in general it looks like it simply hasn't been implemented yet.
@chriseth @ekpyron ?

**Comment by ekpyron** [comment]
I'd ask the contrary: *should* this mapping type be supported? I think the original thought was, that it's not really useful, since ``address payable`` is implicitly convertible to ``address``, so you can always use an ``address payable`` as key in ``mapping (address => T)``, i.e. whenever you'd use ``mapping(address payable => T)`` you can just use ``mapping(address => T)`` instead. You'll never be able to call ``send`` or ``transfer`` on the keys in a mapping anyways.

Thinking about it, one might argue that it could be useful to explicitly restrict keys to only payable addresses, but is that really useful? So is it likely that one wants to have a mapping, such that ``m[a] = v`` is valid only if ``a`` is ``address payable``, but not if ``a`` is ``address``?

**Comment by sifmelcara** [comment]
I agree that `mapping(address payable => T)` is not very useful.

The reason I encounter this issue is, I was upgrading a contract from 0.4.X to 0.5.X, and that contract uses `address` in a way that non-payable address type does not make much sense in the context (since the contract is all about sending money to people). In that case I would like to use `address payable` instead of `address` in mapping type's key, for the sake of consistency.

**Comment by PepperAndSalt999** [comment]
how isn't that useful ? Every time you want to add some eth to those addresses you need to convert their type to payable, it's litteraly taking more memory and thus more gas. How is that useful ?

**Comment by cameel** [comment]
It's a compile-time implicit conversion so it's not adding anything in terms of memory or gas usage. It would probably be a bigger problem if you could enumerate mapping keys but you can't.

**Comment by ekpyron** [comment]
Since you *can't* enumerate the keys of a mapping, this doesn't really serve that much of a purpose at all - there's no situation in which any explicit conversion has to happen or any additional code is generated or in which you can actually fetch an address out of such a mapping and run into problems due to it not being payable.

The only thing new allowing this would enable would be a mapping that artificially restricts lookups syntactically to only payable addresses.

**Comment by cameel** [comment]
> The only thing new allowing this would enable would be a mapping that artificially restricts lookups syntactically to only payable addresses.

This might actually have some low key uses. E.g. when you're storing balances that can be paid out, it would make sense to ensure that your mapping only has payable addresses in it. You would use the `payable` type in place where you actually store addresses, but that does not prevent you from doing lookups on the mapping for a non-payable key, which is likely to be the result of a bug on your part. So it's not like this feature would make no sense at all. Just probably not worth spending time on this because what we have currently is good enough in most cases.

**Comment by ekpyron** [comment]
Yeah, that's why I didn't close the issue right away :-).
