### ISSUE TITLE
SMT checker non-linear arithmetic Z3 issues

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7196]
Basically, disabling CVC4 and only relying on Z3 as in https://github.com/ethereum/solidity/pull/7193 should work.
Maybe we should even have test runs with either *and* both SMT solvers.

**Comment by ekpyron** [comment]
For the record: this multiplication https://github.com/ethereum/solidity/blob/d44f680a51668bf5f73221593b614761a15bc305/test/libsolidity/SMTChecker.cpp#L104 incorrectly caused an overflow warning for some reason when only using Z3, while the other similar tests work just fine.
See the test results at https://circleci.com/gh/ethereum/solidity/158785.

**Comment by leonardoalt** [comment]
Z3 times out for that query on CI, that's why the result is `might overflow`. CVC4 seems to be better at handling nonlinear arithmetics and solves it.
To be fair, Z3 does solve it on my machine as well. The whole set up just seems to be much slower on the CI machines. I've also seen examples that run in 0.2s on my machine and timeout on CI (10s).

**Comment by leonardoalt** [comment]
We now rely on resource limit (and not time limit) and each test can choose which solver should run, so I'd say we can close this.
@ekpyron please reopen otherwise.
