### ISSUE TITLE
[isoltest] String formatting should not output padded zeros

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7198]
Sneaked in with https://github.com/ethereum/solidity/pull/7080.

The following test
```
contract C {
    function e() public {
        revert("Transaction failed.");
    }
}
// ====
// EVMVersion: >homestead
// ----
// _() -> FAILURE
// e() ->
```
does not print strings correctly:
```
Obtained result:
// _() -> FAILURE
// e() -> FAILURE, hex"08c379a0", 0x20, 19, "Transaction failed.\0\0\0\0\0\0\0\0\0\0\0\0\0"
```
It should rather output
```
// e() -> FAILURE, hex"08c379a0", 0x20, 19, "Transaction failed."
```

**Comment by ghallak** [comment]
The `\0` chars are showing because when the test fails, `formatBytesRange` is called with the result of `ContractABIUtils::failureParameters(_bytes)` here https://github.com/ethereum/solidity/blob/6cbcc3796c9aad55da605125667fb6e4a6c41751/test/libsolidity/util/TestFunctionCall.cpp#L199-L208

And failure parameters don't specify the size of the `ABIType` for the string parameter, so it's set to `32` by default.

Calculating the number of padding zeros and passing it as `ABIType` size here might help https://github.com/ethereum/solidity/blob/6cbcc3796c9aad55da605125667fb6e4a6c41751/test/libsolidity/util/ContractABIUtils.cpp#L327
But doing that will make the size of the parameters not equal the size of bytes here https://github.com/ethereum/solidity/blob/6cbcc3796c9aad55da605125667fb6e4a6c41751/test/libsolidity/util/BytesUtils.cpp#L215-L218
And default parameters will be chosen, which is not helpful.

Another way to do this is by finding the number of padding zeros here https://github.com/ethereum/solidity/blob/6cbcc3796c9aad55da605125667fb6e4a6c41751/test/libsolidity/util/BytesUtils.cpp#L265-L267

Then passing this number as a second argument to `formatString`, or by finding the number of padding zeros inside the `formatString` and only print the chars before the padding zeros.

**Comment by erak** [comment]
@ghallak Thanks for your investigation. Since this issue does not only pops up in case of a failure (`revert` and such), but for any strings in general, either adjusting `ByteslUtils::formatString()` itself, or as you suggested, finding the size of padded zeros before and then passing the cut-off would be sufficient. I think the latter is the better option.

Do you want to work on this?

**Comment by ghallak** [comment]
I'll submit a PR soon.
