### ISSUE TITLE
Adding Data to a Wallet to Wallet Transaction

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [ethereum/solidity#7319]
This is more of a general question, but i believe it could evolve to a further discussion if need be.

I am currently using Ganache, Remix and Web3.py to test Ethereum Transactions and inserting some arbitrary data ( for instance, a string of hex digits ) in the **Data** field.

like 

`web3.eth.sendTransaction {from:wallet_1, to:wallet_2, nonce:nonce, data:"0x1234", gas:gas}`

am i violating any part of the Ethereum Protocol by sending some arbitrary or custom string in the transaction's data field ? or is it permissible to do so ?

please kindly let me know

**Comment by chriseth** [comment]
Of course it is permissible, but you have to be aware of the effects. If the `to` address is a contract, it will use the data as input data, so it is not just ignored.

I hope this answered your question. If you want to know more, I would advise you to use https://ethereum.stackexchange.com/ instead, because you will also get better answers there.
