### ISSUE TITLE
[yul] Undefined behavior for loads to and stores from u256(-31) to u256(-1)?

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7336]
## Description

Please see https://github.com/ethereum/solidity/pull/7330#issuecomment-527377730

Should there be an exception thrown (or some form of user visible error/warning message) when the machine or hand-written code like the following 

```
{
  mload(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
  mstore(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
  sload(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
  sstore(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
}
```

I suppose sstores and sloads are fine because storage is a key value store? The yul interpreter "writes" and "reads" zeroes to and from bytes outside the addressable range.

Essentially 

https://github.com/ethereum/solidity/blob/dce52509b4be05fe090c6cf5702b04159946c930/test/tools/yulInterpreter/EVMInstructionInterpreter.cpp#L451

the `accessMemory` ceils `msize` to `u256(-1)` and tells the caller that the memory is **not** accessible. Subsequently, most callers return zero.

**Comment by chriseth** [comment]
So maybe we should extend the memory array by another 31 bytes?

**Comment by chriseth** [comment]
So the thing is that in practice, executing this code costs more gas than anyone can pay. Taking the gas costs into account makes it very hard to randomly generate code that actually runs in a meaningful way. Because of that, I would propose to keep ignoring the gas costs and instead make `mstore(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff, ...)` work and also not truncate any data.
