### ISSUE TITLE
Trailing spaces in JSON output

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7373]
Came up in https://github.com/ethereum/solidity/pull/7372.

Our JSON AST output (and potentially other json output) has trailing spaces, which required a workaround in our check_style script for the recovery_ast_constructor commandline test and for all ASTJSON tests.

The whitespace is needlessly generated by json-cpp, so we need to postprocess its output.

The task is to adjust ``ASTJsonConverter`` to remove all trailing whitespace generated by json-cpp before printing.
A possible approach would be to change ``ASTJsonConverter::print`` to write to a temporary ``std::stringstream`` first. Then the contents of that can be read back line by line, stripped of whitespace and written to the desired ``std::ostream``.

**Comment by chriseth** [comment]
Lets get rid of that.

**Comment by chriseth** [comment]
Maybe also investigate whether the function `jsonPrettyPrint` in `libdevcore/JSON.cpp` or its settings could be of value.

**Comment by ghallak** [comment]
@chriseth This can either be solved by using `jsonPrettyPrint(toJson(_node))` instead of `toJson(_node)` here https://github.com/ethereum/solidity/blob/634da933fafae7486cb9db3feb10f01d258bb884/libsolidity/ast/ASTJsonConverter.cpp#L190-L193
and this will require changing the [test/cmdlineTests/recovery_ast_constructor/output](https://github.com/ethereum/solidity/blob/f88437314290cb6fc8b5ab856769ee53852b276a/test/cmdlineTests/recovery_ast_constructor/output) to use 2 spaces for indention instead of using tabs, since that's what `jsonPrettyPrint` uses https://github.com/ethereum/solidity/blob/f88437314290cb6fc8b5ab856769ee53852b276a/libdevcore/JSON.cpp#L94

Or it can be solved by writing the JSON value to a string in the function `ASTJsonConverter::print` using `Json::writeString` and then using `boost::replace_all` to remove the spaces from the ends of lines. This won't require any change to [test/cmdlineTests/recovery_ast_constructor/output](https://github.com/ethereum/solidity/blob/f88437314290cb6fc8b5ab856769ee53852b276a/test/cmdlineTests/recovery_ast_constructor/output).

**Comment by chriseth** [comment]
So the "yaml compatibility" removes the trailing whitespace? Then I would say that `jsonPrettyPrint` is the way to go, even if it uses spaces for indentation.
Note that if you run the commandline tests, it will auto-update the expectation after asking for confirmation, so manually changing `test/cmdlineTests/recovery_ast_constructor/output` is not necessary.

**Comment by ekpyron** [comment]
That's what removes the trailing whitespace:
https://github.com/ethereum/solidity/blob/f88437314290cb6fc8b5ab856769ee53852b276a/libdevcore/JSON.cpp#L97
So I'd say that's probably the way to go...

**Comment by ghallak** [comment]
@ekpyron is right, I couldn't find out what yaml compatibility is doing.

Edit: yaml cmpatibility is actually removing the space between the key and the colon, so enabling yaml compatibility will result in `"key": x` instead of `"key" : x`.
