### ISSUE TITLE
[Yul] Represent numbers that look like ascii strings as ascii strings

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7495]
Could be done as a prettifying step in the optimizer or in the printer, or both.

The printer should not just change the kind of literal.

**Comment by Neyromancer** [comment]
i can try this issue, but what does it exactly mean "look like ascii strings as ascii strings"? could example be provided?

**Comment by cameel** [comment]
@Neyromancer #7505 has a better description for this but looks like it's already implemented in #7770 so I'm closing this.

I see you commented on a few issues labeled `good first issue`. Unfortunately it looks like most of the good stuff with that label has already been picked off some time ago. I went through the newer issues now and added some that might be good for starters (with difficulty labels) so please take another look.

If you're up for something that is not just a simple warm up and would be actually appreciated by users, I have three suggestions:
- Quick warmup: [signed integer support in `solidity::util::formatNumberReadable()`](https://github.com/ethereum/solidity/issues/9601)
- Less challenging: take a look at the issues in [SOLC Overhaul](https://github.com/ethereum/solidity/projects/44#card-48430766). The inconsistencies between the current set of command-line flags and the JSON input have been really bugging everyone lately and there are multiple reports related to that. Internally it's a big mess and we'd like a fresh start. The most important issue is #9583 but I don't think it's a good one for starters - mostly because of its scope, it's not technically hard - but either doing one of the smaller ones or just doing a clean rewrite of a small part of the CLI with full test coverage would be a big help.
- More challenging: You could try implementing a small language feature. I think that the one about tuple/struct comparisons (#9598) is relatively easy because the code generation part for individual types is already there and you'd just need to make the compiler use it in a new way. The challenging part would be that it's a deep dive into the middle of the compiler and you'd need to learn a bit about its structure to tackle this but I think that with some guidance it's entirely doable for someone who knows C++ well and is just not familiar with the compiler code base.

**Comment by Neyromancer** [comment]
Hi @cameel, thank you for giving the choice between the issues and for providing recommendation. I will walk through the ones you mentioned then, starting form the very first one and then go into SOLC Overhaul issues.
