### ISSUE TITLE
Use snailtracer for optimiser tests

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7513]
@karalabe's raytracer in Solidity (https://github.com/karalabe/snailtracer) is quite heavy on gas. I have put a 0.5.x compatible version here: https://github.com/axic/snailtracer

**Comment by Neyromancer** [comment]
if the issue is still open i can try it

**Comment by cameel** [comment]
It's still open, but I'm not sure how we would use this. Part of this task would definitely be bringing the contract up to date with latest compiler version since 0.5.x is ancient at this point.

@axic Was your intention to just add the `.sol` file to `test/libsolidity/gasTests/` or did you have some idea of a new performance test suite in mind?

**Comment by axic** [comment]
> Was your intention to just add the .sol file to test/libsolidity/gasTests/ or did you have some idea of a new performance test suite in mind?

I think more for the optimiser. I guess we could use it for stress testing the IR + optimizer too.

**Comment by axic** [comment]
This is now mostly ready, given we have #10475 and the snailtracer has been ported to 0.5.x/0.6.x/0.7.x, however not 0.8.x. It is failing with that with panic code 0x11, e.g. some kind of overflow/underflow. If someone can find the culprit, we could easily add it.
