### ISSUE TITLE
What are the possible reasons for `UnimplementedFeatureError: Only byte arrays can be encoded from calldata currently.`

### ISSUE THREAD

**Issue by lowesyang** [ethereum/solidity#7553]
## Description

I got this error when compile a complex solidity contract with solc ^0.4.24, but cannot get which line causes this error.

`UnimplementedFeatureError: Only byte arrays can be encoded from calldata currently.`

What are the possible reasons for the error above?

**Comment by erak** [comment]
@yyh1102 I assume you're calling `abi.encode(array)` where `array` is not of type `bytes`? I can't tell with confidence without having seen the code. In 0.4.24 the error appears because other types than `bytes` indeed can't be encoded from `calldata`. This was only added with 0.5.8. Would you be able to update your contracts, such that they compile with a newer version?

**Comment by lowesyang** [comment]
@erak Yeah i've check all things you mention. Sometimes i remove codes that are nothing with the problems(nothing about `bytes` or something like that), and it works. Sometimes  i remove the interface of a contract and it throws this error. If i upgrade to 0.5.x and it works easily.

**Comment by erak** [comment]
@yyh1102 Ok, so updating works for you, right? Then I'd close this issue.
