### ISSUE TITLE
Compiling with errors results in a `0` exit code when in `standard-json` mode

### ISSUE THREAD

**Issue by travs** [ethereum/solidity#7586]
On `standard-json` mode, the compiler gives a `0` exit code when there is a compilation error, or if the JSON is malformatted.

I understand the docs say that output in this mode is printed to standard output, so I have two main queries:

1. whether there is a rationale for printing error messages to stdout, since this is against the usual convention (even in the normal compiler mode) of printing to stderr. The same for the zero exit code
2. if there is a reason for this, could we make it more explicit in the docs why this behaviour exists?

- Compiler version: `0.5.12+commit.7709ece9.Linux.g++`

## Steps to Reproduce

```
solc - <<< 'fails'
echo $? # 1

solc --standard-json <<< 'passes'
echo $?  # 0, and message on stdout
```

**Comment by Marenz** [comment]
Hmm the `--standard-json` switch basically makes every input/output interaction with the compiler into a json-based interaction. Usually, this is used when a third-party app is using the compiler via that json interface, I suspect that for example remix uses that mode. Such an app would want to have a consistent way to get that info, in this case stdout. If we were to output errors on errout the application would need to read both outputs adding more complexity to it. 

I'd say the error code part of your issue is due to similar reasons. The terminal is no longer the primary means of interactions with that switch, so we offer a consistent behavior for any call to the compiler and give out all relevant info in json only.

I suppose this can be explained better in the documentation (I have not checked). @ChrisChinchilla maybe you want to check that out when you have time.
