### ISSUE TITLE
refactor inline assembly reference resolving

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7656]
See https://github.com/ethereum/solidity/pull/7648#issuecomment-551054356
Two tasks:
- [x] ``ReferencesResolver`` should be a yul ast visitor and descend into inline assembly to resolve refrences https://github.com/ethereum/solidity/pull/8063
- [ ] Evaluate whether something similar would be good for the ``TypeChecker`` (e.g. inherit from ``AsmAnalyzer``?), but the step above might actually be enough.

**Comment by Marenz** [comment]
I tried doing this and got lots of errors. I think the problem is that the `yul::` namespace is suddenly also inside the `ReferencesResolver` when you derive from the `yul::ASTWalker`. 
Here is the branch with the experimental changes: https://github.com/ethereum/solidity/tree/yulvisit-7656-attempt1

A nicer solution might be to have an extra class to do the visits.. will try that way now.
