### ISSUE TITLE
[Build] Build evmone from source for ubuntu 18.04

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#7704]
see https://github.com/ethereum/solidity/pull/7700#discussion_r345725338

**Comment by ekpyron** [comment]
Why :-)?

**Comment by ekpyron** [comment]
As you stated in the other PR: we don't need the static libraries for anything but the fuzzing docker image, so for them the release tarballs are just fine... Only for the fuzzing image we do need to build from sources, since we need the static libraries... so I'd say it's fine as it is... but we could of course still change it, no problem with that.

**Comment by bshastry** [comment]
I don't have a strong opinion on this. For me, it feels more of a uniformity issue since for the 19.04 image (also not used by fuzzer), we build evmone from source but for 18.04 we use the release tar ball. Can become a source of confusion in the future.

**Comment by ekpyron** [comment]
Ah, ok, I didn't realize that ubuntu 18.04 and ubuntu 19.04 did it differently - I thought they did the same and only the clang/fuzzing one differed.

Ok, we should definitely at least do it uniformly between 18.04 and 19.04 - the fuzzing/clang image may or may not stay different from them, that I don't really mind.
