### ISSUE TITLE
Increase use of C++ constexpr constant expressions in the code base.

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#7720]
Came up in https://github.com/ethereum/solidity/pull/7655#discussion_r343720759 with one minor example for this.
But in general I'd expect a lot of places in the compiler could be refactored to benefit from constant expressions. One prominent example would be the simplification rule list, which is entirely compile time constant and with a bit of care could be constexpr initialized to a ``std::array`` which could live statically in the data segment. That might especially have beneficial consequences for the emscripten builds and the stack issues.
There's probably a lot of other places as well.

**Comment by chriseth** [comment]
This requires rather modern compilers, though.

**Comment by ekpyron** [comment]
For a lot of stuff like this compilers that are *actually* C++17 standard compliant should be sufficient... but yeah - for more complex stuff like the rule list this would be rather tricky and would probably also require quite some restructuring, so that we'd have to evaluate separately.

**Comment by christianparpart** [comment]
I think one may want to start with the obvious stuff, and create smaller PRs for each iteration (whenever they come up), and by the time, evaluate whether or not it makes sense to also migrate the more complex stuff.

However, I'd highly recommend to apply `constexpr` as much as possible, since it's also ensuring we have no undefined behavior.
