### ISSUE TITLE
Own private key of smart contract to sign a line of text

### ISSUE THREAD

**Issue by lfrickel** [ethereum/solidity#7777]
## Abstract

For my project it is necessary for smart contract to sign a message (for example, EC-signature) I have not found a way to generate a pair of public and private keys inside the contract so that the private key remains invisible to anyone, and smart contract could sign a line of text with it. Maybe a contract could have its own private key that can be used in this way? Thanks in advance.

**Comment by leonardoalt** [comment]
Hi @lfrickel , any keys/information that you keep in the smart contract's storage will be visible to anyone, as you correctly pointed out.
I don't think it's possible to have a contract return a signed message, because control over signatures would mean you have control over a contract's private key and could impersonate it, compromising the contract itself.

Depending on your exact use case, one way would be for the contract to send the message as transaction data to another contract. This wouldn't give you a signed message, but the protocol would ensure the message was sent by that contract.

**Comment by lfrickel** [comment]
Hi @leonardoalt and thanks for the reply.
The purpose of my question was to create a blind signature, independent of the human factor. I completely agree that Smart Contracts are not suitable for this purpose because of their transparency. Nevertheless, since the execution of Smart Contracts is essentially based on a random oracle model, I could imagine the option that the miner / the node (first) executing contract could make this blind signature based on its own private key (or a one-time private key derived from its own). The public keys for verification of the signature could be stored on the blockchain.

**Comment by leonardoalt** [comment]
@lfrickel wouldn't that require changes in the client/protocol or at least in the EVM?

**Comment by lfrickel** [comment]
@leonardoalt Probably. But this property would open up fundamentally new possibilities.
