### ISSUE TITLE
StructType::recursive() does not always work for recursive structs

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#7779]
Discovered in https://github.com/ethereum/solidity/pull/6282.

In the implementation of https://github.com/ethereum/solidity/pull/6282, `StructType::recursive()` is called in multiple compilation stages while traversing struct members in order to check if they can live outside storage. This leads to an ICE in codegen because `StructType::recursive()` does not return `true` anymore for recursive structs such as
```
contract Test {
    struct RecursiveStruct {
        RecursiveStruct[] vals;
    }

    function func() private pure {
        RecursiveStruct[1] memory val;
        val;
    }
}

```

**Comment by ekpyron** [comment]
I'm pretty sure, this is due to ``recursive`` depending on ``interfaceType``, but ignoring any errors it returns - so if ``recursive`` is called before type information is complete, ``interfaceType`` will silently fail and the ``m_recursive`` member will have incorrect values. Shall we look into this together @erak?

**Comment by leonardoalt** [comment]
@ekpyron @erak is anyone working on this?

**Comment by ekpyron** [comment]
I'm not...

**Comment by erak** [comment]
@leonardoalt I'm also not working on this atm. Do you want to pick it up?

**Comment by ekpyron** [comment]
Should be fixed by https://github.com/ethereum/solidity/issues/8291
