### ISSUE TITLE
[SolYul] Enforce left-right top-down evaluation of expressions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7825]
All expressions should be evaluated in a certain order and the documentation about this should be changed (currently, it says that the order of evaluation is unspecified).

Fixes https://github.com/ethereum/solidity/issues/7820

**Comment by axic** [comment]
Do we have an idea which parts of the generator may not be following the left-right top-down rule?

**Comment by ekpyron** [comment]
Given https://github.com/ethereum/solidity/pull/11537, resp. https://github.com/ethereum/solidity/issues/11536 and the fact that function arguments are evaluated right-to-left, I'd say that right-left is the better choice...

**Comment by ekpyron** [comment]
Since it has come up during the 0.8.15 release and the bug reports we received prior to that:

An interesting case is
```
(x,y,z) = (a,b,c);
```

Currently, the *one* thing that the docs in https://docs.soliditylang.org/en/latest/control-structures.html#order-of-evaluation-of-expressions specify is that children of a node are evaluated before the node.
Here this means, that we have to evaluate ``(x,y,z)`` and ``(a,b,c)`` *before* assigning (while it is unspecified which we evaluate first and in which order we evaluate the tuple elements each time).

This means that according to the current docs we cannot evaluate this as:
```
x = a;
y = b;
z = c;
```
and thereby increase the chance to run into dangling references like in ``(byteArray.push(), byteArray.push()) = ...``.

To be honest, I actually also don't think that ``(x,y,z) = (a,b,c)`` should evaluate as ``x = a; y = b; z = c;``, since this would be a very special case compared to regular operator and expression evaluation, but yeah - if we even want to consider it, we'd need to break the current language spec breakingly for it.
