### ISSUE TITLE
Yul Dialects

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#7830]
This is more or less a brainstorming issue about which dialects in Yul we can expect in the future.

The dialect is defined by the built-in functions, the list of types (which are already given by the parameters and return parameters of the built-in functions) and the default type.

 - EVM(version): EVM opcodes (depending on version) operating on u256, default type: u256
 - EWasm: wasm builtins (minus floating point) operating on i64, i32, default type: i64
 - YulIR(version): EVM opcodes (depending on version) operating on u256 plus `calldataload4() -> u256`, default type: u256
 - TypedYulIR(version): variants of EVM opcodes (depending on version) - to be defined, maybe intermingled with some opcodes taken from wasm, operating on u256, u224, u192, p160, u128, u120, u96, u64, u32 and bool, defaul type: u256

In the above, version is always an EVM version (hardfork name).

Translations are defined (in a way similar to what we do for ewasm) between those dialects:

YulIR -> EVM
YulIR -> EWasm
YulIR -> TypedYulIR
TypedYulIR -> EVM
TypedYulIR -> EWasm

In the long run, YulIR will probably be fully replaced by TypedYulIR

**Comment by chriseth** [comment]
I would like to propose identifiers for yul dialects. The only normative (i.e. non-experimental) identifiers for now are:

EVM-frontier
EVM-homestead
...
EVM-berlin

The we would have `TypedEVM-<version>` and so on like above.

It would be good to have some more room for changes than just the evm version, especially for the typed and yul ir variants:

EVM_0-homestead / TypedEVM_0-homestead?

Maybe we could also use letters to not confuse this with "EVM1.x"?

**Comment by axic** [comment]
It would also be nice to remove this extra complexity of `Language` and `Machine` in `libyul/AssemblyStack`:
```
        enum class Language { Yul, Assembly, StrictAssembly, Ewasm };
        enum class Machine { EVM, EVM15, Ewasm };
```

If we could encapsulate machine/target into dialect, then all we need is a dialect and a translation map. Perhaps having a target and a dialect would be natural as well, but unfortunately there is an overlap between dialects and targets for EVM: EVM15 just specifies a dialect of EVM.

I would suggest to adopt the "target triplet" idea from other compilers (which usually goes as `<machine>-<vendor>-<os>`) and change it to our needs: `<machine>-<dialect>-<subdialect>`, where all fields are lowercase and only `[a-zA-Z0-9_]` are valid symbols. The `subdialect` (and the preceding dash) can be omitted if there's none. I would consider "yul" a machine under this.

Remember, the current configurations in use are:
- Inline assembly (EVM, untyped, default type u256, EVM version)
- Yul (EVM, typed, default type u256, EVM version)
- Ewasm (typed, default type u64, no EVM version)

What we want to support as a minimum (to replicate everything we have currently) is the following:
- `evm-<hardfork>` -- the EVM machine target for a given hardfork
- `ewasm-<hardfork>` -- the ewasm machine target for a given hardfork (and the only supported configuration is `ewasm-byzantium`)
- `evm-eip615` -- machine target for what we call EVM15/EVM1.5 now
- `yul-evm-<hardfork>` or `inlineassembly-<hardfork>` -- the untyped EVM used in inline assembly
- `yul-solir-<hardfork>` -- the Yul Solidity IR for a given hardfork

**Comment by axic** [comment]
On a side note two questions:
1) Why are we making a distinction between typed and untyped Yul? When we decided to support a "default type", I think that made the fully typed version obsolete.
2) Why aren't we allowing the types (default type u256) for inline assembly?

**Comment by axic** [comment]
The `solc` options today are the following:
```
Alternative Input Modes:
  --assemble           Switch to assembly mode, ignoring all options except 
                       --machine, --yul-dialect, --optimize and 
                       --yul-optimizations and assumes input is assembly.
  --yul                Switch to Yul mode, ignoring all options except 
                       --machine, --yul-dialect, --optimize and 
                       --yul-optimizations and assumes input is Yul.
  --strict-assembly    Switch to strict assembly mode, ignoring all options 
                       except --machine, --yul-dialect, --optimize and 
                       --yul-optimizations and assumes input is strict 
                       assembly.
Assembly Mode Options:
  --machine evm,evm15,ewasm
                       Target machine in assembly or Yul mode.
  --yul-dialect evm,ewasm
                       Input dialect to use in assembly or yul mode.
```

I would propose to replace that as follows:
1. Remove `--assemble`, `--strict-assembly`, `--machine`.

2. `--yul` turns on Yul mode. Sets input dialect to `yul-evm-<lasthardfork>`. Sets target/output dialect to `evm-<lasthardfork>`.

3. `--yul-input-dialect` (or `--yul-source-dialect`) changes the input dialect. `--yul-output-dialect` (or `--yul-target-dialect`) changes the output dialect.

4. In the future `--yul-optimizations` could be split or adjusted to specify different optims for the different dialect stages.

**Comment by cameel** [comment]
> 1. Remove `--assemble`, `--strict-assembly`, `--machine`.

I think this is a good idea. The way `--assemble`/`--strict-assembly`/`--yul` + `--machine` + `--yul-dialect` options interact with each other is pretty complicated and I spent too much time trying to wrap my head around it back when I was working on #9074. It's not documented and they do not map in a simple way to the internal `Machine`, `Language` and `Dialect` types.

Here's a table from that PR (now a bit simpler since `--yul` and `--assemble` are disallowed with `--machine wasm` and result in an error):

Machine: `ewasm`
|                     | dialect: not specified  | dialect: `evm`   | dialect: `ewasm`      |
|---------------------|-------------------------|------------------|-----------------------|
| `--strict-assembly` | ewasm                   | strict assembly  | ewasm                 |
| `--yul`             | (error)       | strict assembly  | ewasm                 |
| `--assemble`        | (error)  | strict assembly  | ewasm                 |

Machine: `evm` or `evm15`
|                     | dialect: not specified  | dialect: `evm`   | dialect: `ewasm`      |
|---------------------|-------------------------|------------------|-----------------------|
| `--strict-assembly` | strict assembly         | strict assembly  | (error)               |
| `--yul`             | typed Yul               | strict assembly  | (error)               |
| `--assemble`        | ~loose assembly~ strict assembly | strict assembly  | (error)               |

EDIT 2024-08-26: Looks like `--assembly` does not really enable "loose assembly" after all . It still has a separate enum entry so I assumed it's handled separately, but looks like it's handled as "strict assembly" by [`languageToDialect()`](https://github.com/ethereum/solidity/blob/v0.8.26/libyul/YulStack.cpp#L50-L62).

**Comment by axic** [comment]
cc @ekpyron any opinion on all this? :)

**Comment by ekpyron** [comment]
Definitely a good idea to clean this up - the current options are a mess and really annoying :-).
But does ``evm-<lasthardfork>`` really qualify as a "yul output dialect"? I suppose what it'd output is evm bytecode, right? But instead of ``--yul-output-dialect`` or ``--yul-target-dialect`` it could just be plain ``--target`` for example...

**Comment by axic** [comment]
> But does evm-<lasthardfork> really qualify as a "yul output dialect"? 

No, all of these things are "target triples". I didn't use the term target as it can be a source as well.

> But instead of --yul-output-dialect or --yul-target-dialect it could just be plain --target for example...

Yes, one could opt to use `--target`, but then there's no nice counterpart for the input side. `--source` doesn't seem to be a good option.

**Comment by chriseth** [comment]
I think it's a good idea to drop machine and just say that we compile to yul and then potentially translate yul to another yul dialect that is close to some machine. The final stage is an assembler that is tied to the dialect (some intermediate dialects mightnot have an assembler).

One reason for "typed yul" was to introduce a `bool` type that could make some functions safer and also clear up the mess about `not` and `iszero`.

**Comment by chriseth** [comment]
Oh and another comment: I would like to keep the "yul ir" dialect more or less in flux so that we can introduce breaking changes as we go (like introduce memory objects and so on).

**Comment by leonardoalt** [comment]
Also agree with the cleanup and single `--yul` option

**Comment by leonardoalt** [comment]
After a long discussion on Gitter, I agree with the triplets idea.
I slightly disagree with the triplets that would be needed to replace the current behaviors we have.
To me they would be:
* evm-\<hardfork\> -- the EVM machine target for a given hardfork
* ewasm-\<hardfork\> -- the ewasm machine target for a given hardfork (and the only supported configuration is ewasm-byzantium)
* evm-eip615 -- machine target for what we call EVM15/EVM1.5 now
* yul-evm-\<hardfork\> -- the untyped EVM used in inline assembly, IR, and potential input, default type u256, max width 256
* yul-ewasm-\<hardfork\> -- the typed ewasm with default type u64, max width 64
* yul-typedevm-\<hardfork\> -- same as yul-evm, but typed. Not sure about the name

**Comment by chriseth** [comment]
Can we get a summary of the latest competing proposals?

**Comment by ekpyron** [comment]
Reading the proposals above I have one question: are there different variants of yul for different hardforks? E.g. all of them just get ``shl`` and the code transform Yul->EVM takes care of it not being an opcode in old EVM versions, doesn't it?
If so far Yul is the same for all hardforks, can we expect this to be the case in perpetuity?

**Comment by ekpyron** [comment]
No longer planned.
