### ISSUE TITLE
Remove rmd160 and sha2

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#784]

**Comment by axic** [comment]
Why?

**Comment by chriseth** [comment]
Ah sorry, they are used in the end-to-end tests. Still, we could replace these tests by constants.

**Comment by winsvega** [comment]
so replace to particular output instead of function here:
https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SolidityExecutionFramework.h#L121

right?

**Comment by chriseth** [comment]
not at that point, but yeah, where it is used.

**Comment by Denton-L** [comment]
What's the rationale behind removing these?

**Comment by chriseth** [comment]
They are not used by the compiler, only for a single test.

**Comment by Denton-L** [comment]
So it's still gonna be available for Solidity contracts?

**Comment by bobsummerwill** [comment]
Context for these changes as a whole, @Denton-L and @axic.

We orphaned a subset of `libdevcore` into Solidity as part of the "standalone" changes, and I tried to make that subset as minimal as possible.    This (and a few other issues logged against the repo) are aiming to chop back on some of the dependencies which needed a little rework rather than just straight code deletion.

They are almost exclusively for little bits of code which were used within tests, and which calculated constants (because we had the code around so that was easy), but they can be replaced with actual constants, and we can drop the cut-and-pasted code to have to maintain.

**Comment by bobsummerwill** [comment]
@Denton-L So the smart contracts run on specific EVM client implementations.

In the C++ case, that code will like inside `eth`, and actually be exactly the code whose cut-and-paste we are removing here.     The two were previously intertwined because of the dual-purpose of webthree-umbrella.

Hope that makes sense!

**Comment by bobsummerwill** [comment]
See also #780, #781, #782, #785.
