### ISSUE TITLE
yulInterpreter crashes on infinite recursion

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7943]
Found by ossfuzz (13647 and 13811)

```
{
    function f() {
      f()
    }
    f()
}
```

The problem manifests in `Interpreter::openScope` in `test/tools/yulInterpreter/Interpreter.h`.

**Comment by bshastry** [comment]
@axic I've not looked into these closely but they seem to be due to lower stack memory allocated in the fuzzing VM allocated by Google.

**Comment by christianparpart** [comment]
For me this looks like a recursion (i.e. are the rewritten to loops?). Would it make sense to limit recursion depth then, or somehow simulate what gas is doing (to stop/fail after a certain amount of too many instructions?)

**Comment by bshastry** [comment]
@christianparpart We limit recursion depth by counting how many basic blocks have been interpreted at any given point in time:

https://github.com/ethereum/solidity/blob/7247e72d8bddaa2a30f9f7b5801e47f362c79c5b/test/tools/yulInterpreter/Interpreter.cpp#L171

Once the number of steps (basic blocks interpreted) equals max steps, we throw an exception.

Max steps is defined as "100"

https://github.com/ethereum/solidity/blob/7247e72d8bddaa2a30f9f7b5801e47f362c79c5b/test/tools/ossfuzz/yulFuzzerCommon.h#L43

Perhaps that's already too much for lower stack sizes is what I'm thinking. Besides, I've not been able to reproduce it locally in order to experiment with different stack limits versus maxsteps.

**Comment by axic** [comment]
@bshastry is this still a problem?

**Comment by bshastry** [comment]
Closing because this is no longer an issue. May have been fixed by #9459

**Comment by axic** [comment]
@bshastry can you add a test case to verify it?

Please close again if you think that's unnecessary.
