### ISSUE TITLE
Rename opcodes (in asm and Yul) according to EIP-1803

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#7966]
See discussion here https://ethereum-magicians.org/t/eip-1803-rename-opcodes-for-clarity/3345 (and the EIP text here: https://eips.ethereum.org/EIPS/eip-1803)

It would make sense to apply these changes in both Yul and the internal assembler.

**Comment by axic** [comment]
I think we're too late to do this in 0.6.0. The next best option is to add aliases in 0.6.1 and remove the old ones in 0.7.0.

**Comment by christianparpart** [comment]
I just wanted to implicitly ask that this is not a breaking change, is it? (changing instructions would cause inline assembly to fail on those changed instructions). @axic

**Comment by axic** [comment]
It is breaking if we just rename them.

**Comment by axic** [comment]
Preliminary accepted for 0.7.0, given we agree on names within the next 2 weeks.

**Comment by ekpyron** [comment]
@axic You asked me to go through the Instruction list:

``RETURN`` and ``STOP`` might be something to think about... maybe ``RETURNTX`` or ``TXRETURN`` would be nicer - but I don't like either of them visually...
But then we'd also need ``TXABORT`` or ``TXINVALID`` and ``TXREVERT``... which starts getting silly...

So probably better no explicit `TX` for those, but then referring to the transaction becomes (somewhat of) a *default*, which means:
- I *don't* think we need the TX ones proposed in the magician thread, i.e. ``ORIGIN->TXORIGIN`` and ``GASPRICE->TXGASPRICE``.
- This strengthens the need for ``GASLIMIT -> BLOCKGASLIMIT``.

``LOG2`` looks like a bit like a base-2-logarithm... but it's fine I think...

``JUMPI`` also isn't *that* nice... I see that there's also ``JUMPIF`` for some subroutine EIP... the latter ``JUMPIF`` should probably be ``JUMPSUBI`` or ``JUMPSUBIF`` and ``JUMPI`` could be ``JUMPIF``... or ``CONDJUMP``... but yeah, all of this is a bit weird, so maybe none of it is better than doing nothing...

So in summary:
- I'd definitely agree with the need for ``GASLIMIT -> BLOCKGASLIMIT``
- Prepending ``TX`` to some of them would be kind of inconsistent, if not done for *everything* relating to the transaction - and that would look silly...
- The rest of the instructions not mentioned in the magician thread nor the EIP seem fine to me.
- Bitwise operations may still be worth a thought.

Regarding the others mentioned in the EIP and/or the thread:
- ``NUMBER -> BLOCKNUMBER`` would be nice for making the ``BLOCK`` prefix consistent.
- ``BALANCE -> EXTBALANCE`` is also a good one
- Arguably prepending ``SELF`` to any of the others is only due to ``BALANCE`` not already having been renamed to ``EXTBALANCE``... unfortunately renaming both ``BALANCE -> EXTBALANCE`` and ``SELFBALANCE -> BALANCE`` at the same time is too dangerous and not an option... so prepending ``SELF`` does make sense - but it's a bit propagating a hack...
- Pro prepending ``SELF`` would be that I said earlier that ``TX`` seems to be the "default" - but that's not a good argument, because this distinction should be clear from the respective names, so since ``SELF`` and ``TX`` have no overlap, they could both be implicit defaults at the same time.

So yeah, I definitely agree with axic on ``GASLIMIT -> BLOCKGASLIMIT`` being important. Renaming ``INVALID -> ABORT`` makes sense. ``BALANCE -> EXTBALANCE`` and ``NUMBER -> BLOCKNUMBER`` might be good further candidates. Anything else would probably be more controversial.

**Comment by axic** [comment]
To put @ekpyron's analysis into perspective, these are the changes proposed by EIP at the time the analysis was done:
- `BALANCE` (0x31) to `EXTBALANCE` to be in line with `EXTCODESIZE`, `EXTCODECOPY` and `EXTCODEHASH`
- `SHA3` (0x20) to `KECCAK256`
- `NUMBER` (0x43) to `BLOCKNUMBER`
- `GASLIMIT` (0x45) to `BLOCKGASLIMIT` to avoid confusion with the gas limit of the transaction
- `GAS` (0x5a) to `GASLEFT` to be clear what it refers to
- `INVALID` (0xfe) to `ABORT` to clearly articulate when someone refers this opcode as opposed to “any invalid opcode”

Since the EIP was written there have been the following suggestions:
- `ADDRESS` -> `SELFADDRESS` (in line with `SELFBALANCE`)
- `ORIGIN` -> `TXORIGIN`
- `CODESIZE` -> `SELFCODESIZE` (as above)
- `CODECOPY` -> `SELFCODECOPY` (as above)
- `GASPRICE` -> `TXGASPRICE`
- `DIFFICULTY` -> `BLOCKDIFFICULTY`
- `TIMESTAMP` -> `BLOCKTIMESTAMP`
- `NOT` -> `NEG` or `BITNOT` (and prefix other bit operations with `BIT`)

**Comment by axic** [comment]
I think @ekpyron's feedback on `EXT` vs `SELF` is spot on, not sure how to resolve that. What seems to be better is to keep the `EXT` prefix and remove the `SELF` prefix, because that was the only out-of-order late addition. Perhaps it could be done over the course of some longer period.

The reasoning about `TX` is also an interesting one. I think the prefix-less opcodes deal with account state *and* transaction state at the same time. It would be nice separating those two, but arguably adding `TX` would mean adding it to a lot of things (like `RETURN`, etc.) so perhaps the better direction is adding the `ACCOUNT` or `SELF` prefixes for the account state?

**Comment by christianparpart** [comment]
Generally speaking I am absolutely for renaming opcode mnemonics for better intuitivity/readability.

In this case, it reads like you are also namespacing with some prefix/suffix to resolve ambiguity, such as NUMBER to BLOCKNUMBER or GASPRICE to TXGASPRICE, which I think is good, too.

One would have to see how much redundancy would be created when applying the above idea to *all* opcode mnemonics to see if that change is justified.

Other changes (GAS -> GASLEFT, INVALID -> ABORT, NOT -> BNOT) I think are more intuitive to read, too.

p.s.: I think if we first provide an stdlib, then there might be fewer need of actively writing inline assembly by others /libs, hence, the renames would be feel less intrusive to those, IMHO.
