### ISSUE TITLE
[Sol - Yul] Implement support for libraries

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8078]

**Comment by cameel** [comment]
@axic @chriseth Is there anything missing besides external calls/library addresses?

Looking at disabled tests, these two fail only because of missing support for external functions:
- using enums and contracts as keys in mappings
- library function selectors

And these two rely on other missing features:
- storing internal library function pointers in storage (storing internal function pointers in storage not implemented)
- calling functions bound to structs (structs not fully implemented)

**Comment by chriseth** [comment]
I don't have an overview of what is still needed, but support for library addresses and calling via delegatecall would be the most important part, now, I think. For that, we need a new builtin added to the dialect similar to `datasize`.

**Comment by cameel** [comment]
Yeah, I remember that part from https://github.com/ethereum/solidity/issues/8485#issuecomment-607981435

> For this, I think we should start adding a builtin function called `linkerSymbol` to EVMDialect, which requires `"literalArguments"` and is in all aspects very similar to `datasize`. Its code generation should just call `linkerSymbol` on the abstract assembly.
> 
> As a next step, `void IRGeneratorForStatements::endVisit(Identifier const& _identifier)` can be changed to implement the library case by defining the identifier via the linker symbol (the library's address).

**Comment by cameel** [comment]
#10230 Adds support for library addresses and external calls. Stuff that's left after this as far as I know:
- Library function selectors
- Call guards ([Call Protection For Libraries](https://solidity.readthedocs.io/en/latest/contracts.html#call-protection-for-libraries)).
- Parameters of storage mapping types (See `semanticTests/libraries/external_call_with_storage_mapping_parameter.sol`)

**Comment by axic** [comment]
Wasn't this done?
