### ISSUE TITLE
Fix homebrew release for 0.5.16 and 0.6.1

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8094]

**Comment by ChrisChinchilla** [comment]
Strangely, when I install the formula locally I get no problems, but also quite different output from the circleCI logs I see. I think this could be due to two reasons.

1. One of the dependencies had a Python issue and since fixed it. I can't rerun the build (permissions) to test.
2. The CI is using Mavericks, I'm on Catalina. it's hard for me to test any other way, but also, Mavericks is quite old now, and Mac users upgrade quite quickly, so it might be time update the version we use if that's possible?

**Comment by chriseth** [comment]
I think the problem might be that homebrew wants to install python3 as "python" but that command is already occupied by python2. So a fix might be uninstall python2 first. Log:
```
==> Pouring python-3.7.6_1.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink Frameworks/Python.framework/Headers
Target /usr/local/Frameworks/Python.framework/Headers
is a symlink belonging to python@2. You can unlink it:
  brew unlink python@2
```

**Comment by chriseth** [comment]
Some googling suggests that just increasing the xcode version requirement might help.

**Comment by ChrisChinchilla** [comment]
It feels like this has become more of a Circle CI issue than a Homebrew issue, as in my mind, I don't know why python@2 needs unlinking, as we're not even installing it in the formula.

Anyway, I can confirm that these all install and work locally, which is most important anyway.

**Comment by chriseth** [comment]
it is an issue on travis and other systems, too. As far as I understand, the python3 package in homebrew took over /usr/bin/python without python2 releasing it.

**Comment by chriseth** [comment]
Fixed by uninstalling python2
