### ISSUE TITLE
Feature request: Change default Emscripten namespace (Module) to something like (Solidity)

### ISSUE THREAD

**Issue by juanfranblanco** [ethereum/solidity#8157]
The solidity javascript library created using Emscripten defaults the namespace to "Module", this is can cause a conflict with other libraries that use the same namespace (still using the default).

A suggestion of a new namespace could be "Solidity", emphasis on suggestion :).

## Backwards Compatibility
The emscripten library is wrapped by solcjs and with the new WebAssembly ouput I assume that will be required to change as well. This may the ideal opportunity to do the change, as that will be the main library affected for the majority of end users.

Thanks!!

**Comment by chriseth** [comment]
General feeling is that this is a good idea but is a breaking changes, so moving to 0.7.0.

**Comment by axic** [comment]
Explanation in the documentation: https://emscripten.org/docs/getting_started/FAQ.html#can-i-use-multiple-emscripten-compiled-programs-on-one-web-page

**Comment by ekpyron** [comment]
To summarize the current state of this: we want to switch from the namespace being called ``Module`` to calling it ``Solidity`` with 0.7.0.

We'd like to get some input about this from everybody who uses ``soljson.js``, though. If you let ``solc-js`` load ``soljson.js`` directly (which might be the case when running on node-js), then we can deal with the renaming inside ``solc-js``.
But if you manually pass the ``Module`` global defined by ``soljson.js`` to the ``solc-js`` wrapper, then this renaming will require support on your end (which is the likely case for using ``soljson.js`` within the browser).

Does anybody pre-define some emscripten-specific fields in ``Module`` like ``Module["onabort"]`` before loading ``soljson.js``? This will even break when using node-js and solc-js and you would have to e.g. define ``Solidity = Module`` on your end for it to continue to work with 0.7.

So our main questions are: do you all agree that this is a reasonable change? Will it cause problems for you? Are you prepared to support this in time for 0.7 being released (which *might* happen in about two weeks time already)?

**Comment by juanfranblanco** [comment]
@ekpyron great points, I load normally different compiler versions dynamically, (node) users might have already stored them locally (cache or downloaded), but the crwap method is already part of the compiler when you call ```setupmethods``` in the wrapper, so i don't think that it will be an issue in general. Now.. my guess is that loading remotely in the browser may require all previous compilers to have the "Solidity" namespace.

**Comment by ekpyron** [comment]
We won't really nicely be able to change the previous compiler versions (for various reasons), that's the main issue with this.
So anybody who will want to support loading old as well as new compiler versions and relies on the name of this global, will need to support this on their end - that's why we're trying to reach out now to check, if that's acceptable to everyone :-).

**Comment by ekpyron** [comment]
Since we put out the word already and linked this issue, let me add this as a note:

We'd still be considering *not* to do this, in case overall this turns out to be more trouble than it's worth.
So feel free to let us know, in case you think this is a bad idea in general.

We're still not entirely sure ourselves, under which circumstances the namespace being called ``Module`` is actually a problem that cannot be solved.
For loading recent compiler versions in the browser it is required to use WebWorkers anyways (since chromium needs that for allowing WebAssembly compilation) and those workers (1) have their own namespace anyways and (2) you can e.g. do ``importScripts('soljson.js'); Solidity = Module; Module = undefined`` (and something similar for other emscripten modules in case you need multiple ones). Node-js similarly shouldn't really suffer from it being called ``Module``.

So it would also be helpful to us, if you could elaborate on the precise circumstances where this might be helpful.

Based on that we could decide, if introducing this incompatibility is actually worth it.

**Comment by juanfranblanco** [comment]
@ekpyron I had this problems in the past where other web assembly components have been registered and use Module as the main namespace, when loaded they will "compete" with each other overwriting their space. This has made it impossible to integrate with both. In my context I have seen this (although it might been resolved now as they might have also changed their namespace) with: mono-wasm (.net runtime), unity3d (unity engine) and other projects.. EDITI am talking in the browser :)

**Comment by ekpyron** [comment]
How exactly were you loading soljson.js and the other modules? Using ``<script>`` tags? I'm wondering, since I think at least chrome will reject the wasm compilation outside of web workers, so we generelly expect the loading to take place within web workers.

**Comment by juanfranblanco** [comment]
Hi we are talking about a few months back, so it may have changed but yeah it was the script tag. An example of the conflict can be seen here with mono-wasm and the Nethereum playground:  
![image](https://user-images.githubusercontent.com/562371/87433330-1773cd00-c5e1-11ea-8f00-68467d8d2807.png) also not Nethereum related using as well mono-wasm (they need to change their namespace too!, I have already told them)
![image](https://user-images.githubusercontent.com/562371/87433554-57d34b00-c5e1-11ea-9f36-b79bb98bbbde.png)
