### ISSUE TITLE
Templates for error reporting

### ISSUE THREAD

**Issue by erak** [ethereum/solidity#8218]
## Abstract

Support a more readable and consistent error reporting. Whiskers came up as a reference.

## Motivation

Came out of https://github.com/ethereum/solidity/pull/8103.

## Specification

E.g. `"Cannot use <to_string(operator)> on <type.string()>."`

**Comment by christianparpart** [comment]
I really like the idea of streamlining error reports. But if Whiskers is the right way to do that, I am not too sure.

My initial motivation was to improve readability of error messages by using semantic colouring, something that would be a convenient argument for using fmtlib (part of C++20's std::format), so that passing custom types to the error formatter could be auto-colorized & pretty-printed without additional effort on the caller side.

**Comment by cameel** [comment]
This PR seems relevant in this context: #11273.
