### ISSUE TITLE
Change scanner / docstringparser so that docstrings can be parsed during parsing

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8247]
Follow-up of https://github.com/ethereum/solidity/issues/7835

The goal is that docstring elements can have their own source locations.

**Comment by hrkrshnn** [comment]
I think this is a good idea. Currently, the `docStringParser` is too complicated I think. One problem I see is how `\n` is used as a line break and also to indicate end of a tag. For example, for the following contract.

```solidity
contract C {
	/// @notice this is a function that has a long notice tag so that we have to
	/// wrap the line.
	/// @param x integer
	function f(int x) public {

	}
}
```

The "StructuredDocumentation", "text" attribute is `text": "@notice this is a function that has a long notice tag so that we have to\n wrap the line.\n @param x integer"`. We could simplify the `docStringParser` if the main parser can separate the text at the beginning.
