### ISSUE TITLE
bool results can equal to true even when function calls throw

### ISSUE THREAD

**Issue by balboah** [ethereum/solidity#825]
in this example:

```
contract priced {
    address public tokenContractAddress;

    modifier costs(uint256 amount) {
        Token tc = Token(tokenContractAddress);
        bool result = tc.transfer();
        if (result == true) _
    }
}

contract Token {
    function transfer() returns (bool success) {
        throw;
    }
}

contract Foo is priced {
    uint public called;

    function Foo(address tokenContract) {
        tokenContract = 0;
    }

    function bar() costs(1) {
        called++;
    }
}
```

When tokenContractAddress is 0, we will always have a true result in the priced modifier, as opposed to what I would expect.

This happened to me where I incorrectly set the tokenContract instead of tokenContractAddress.

**Comment by holiman** [comment]
Well, you're invoking `transfer()`on a contract (`0`) which does not have any code. Thus, the contract `0` does not throw. Nothing strange about this. EDIT: I agree it's strange that it returns `true`

**Comment by Denton-L** [comment]
I don't know what's going on but I have additional information to provide:

Take the following set of contracts:

```
contract A {
    B b = B(address(0));

    function caller() returns (uint) {
        return b.dummy();
    }

    function methodSignature() constant returns (bytes4) {
        return bytes4(sha3("dummy()"));
    }
}

contract B {
    function dummy() returns (uint) {
        throw;
    }
}
```

Calling `caller()` seems to consistently return `0x32e43a1100000000000000000000000000000000000000000000000000000000`. The first four bytes of this are equal to the return value of `methodSignature()` (the method signature of `dummy()`). For some reason, it is returning the method signature.

Here is what I suspect is happening, though I could be wrong though because I don't know the internals of the EVM too well.

When `caller()` calls `dummy()`, it has to push the method signature onto the stack. Since `B`'s code is all zeros (since it hasn't been initialised), when it tries to execute, it'll hit `0x00` which corresponds to the `STOP` opcode. When it "returns", the method signature will still be on the stack, because it hasn't been cleared by  call to `dummy()`, so `caller()` will read that as the return value.

Of course, in your case, any non-zero value, such as the method signature, will be `true`.

**Comment by holiman** [comment]
Some details are wrong, but I think you're on the right track. 

So when doing a `call`, the evm gets two sets of "pointers". The first being [memory in offset, memory in size], which in points to a memory location containing the `calldata` (method signature). And then there's [memory out offset, memory out size]. And that's where the EVM will write the return values. And if there is no return value, the EVM will not touch the [memout - memout+memoutsz] area, leaving it _as is_ . 

So, I guess that Solidity compiler defaults to reusing the `mem_in` - area for output. Which is economically sound (less memory area used == less gas consumed) but becomes very fragile, since the return values depend on the method signature. Fun quirk, actually quite deadly.

**Comment by axic** [comment]
I think I've raised the same issue a while ago: https://github.com/ethereum/solidity/issues/520

**Comment by nmushegian** [comment]
When you call empty code it doesn't throw, so you get garbage. See: https://github.com/nexusdev/dappsys/blob/develop/contracts/lang/fallback_tests.sol

**Comment by balboah** [comment]
Yes I realized that I didn't initialize it properly and thus didn't get a `throw`. But I really don't think an uninitialized contract should be able to return something that can be interpreted as true, or being able to change the default value of a variable. It must be a big source of hard to track bugs and a security concern to many.

**Comment by chriseth** [comment]
Fixed as far as it is fixable in https://github.com/ethereum/solidity/pull/839

**Comment by balboah** [comment]
that was quick! 👍
