### ISSUE TITLE
Memory mappings

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#8439]
## Abstract
For some algorithms having a mapping or set type to check the existence of multiple values can simplify code and improve its performance.

## Motivation
In the next Ethereum hard fork, with EIP-1884, which increases the cost of SLOAD from 200 to 800 it might start to be more cost effective to store some data directly in code, in data structures, and query it. Having a memory mapping or set type would help with this.

External Solidity functions that are only meant to be called by off chain code would benefit with cleaner code in some cases that could use a mapping in the algorithm. Solidity functions that are only meant to be called off-chain have no gas cost but I think some of them could still be implemented more efficiently if there was a memory mapping type.

**Comment by ekpyron** [comment]
How would you index the memory mapping? If we use hashes of keys as for storage, then - at least on-chain - this would immediately result in out-of-gas... and I'm not sure every off-chain execution environment can be relied on to support arbitrarily high memory accesses either...

**Comment by mudgen** [comment]
It is a good question.  Maybe limit the value of the hashed keys, so there are no high memory accesses. For example, limit the hash value to uint32 and put any values with hash collisions into an array bucket. I don't think contract functions are going to often work with data sets that are very large so the mapping implementation could be optimized for smaller datasets,  like less than 10,000 values or something. 

It would be really good if the memory mapping could still be used on-chain somehow as a way to implement algorithms where you store your data in the function and search and retrieve it using the memory mapping,  bypassing having to use storage.

**Comment by mudgen** [comment]
I realize that what I am asking for might not be possible.

Maybe a mapping type for really small datasets for on chain execution to bypass using storage could work.

Use a small amount of memory to index the mapping on,  like 500 bytes, to search like 50 values.  Perhaps some testing would need to be done to find out the gas performance sweet spot.

It would need to have better gas efficiency than linear searches to be useful.

Here is an example of a problem that could be solved easier with a memory map:
Let's say that I have 100 function selectors stored in an array. And each function selector is associated with a contract address.  The program must produce an array of contract addresses that are all the addresses that are associated with the function selectors.  The program prevents duplicate addresses.

The algorithm would do this:
1. Loop through the array of function selectors. For each selector get the contract address associated with it. See if the contract address is in our map.  If it is not then put it into our map and put the contract address in our results array. If the contract address is in the map then skip it and go on to the next selector. When all the selectors are exhausted return the results array.

It would be great, if possible, to be able to query a memory mapping to return all of its keys or values as arrays, if that is possible.

**Comment by ekpyron** [comment]
Hm... I'm not sure - mappings in storage work, since we can write to arbitrary slots and with 256-bit hashes we can just trust that there are no collisions (i.e. no buckets, no actual key comparisons, etc.).
In memory we would severely need to restrict the hash size (random access to memory locations up to 2^32 would still be way too expensive, so it'd need to be restricted to much less than uint32). That in turn means we would need to account for collisions with buckets of some sort - for which it would not be clear where to allocate them, unless we have full proper memory management, which itself is too costly... I'm pretty sure the randomly high memory accesses plus the hashing plus the arithmetic on hashes plus buckets plus actually having to compare the keys in the buckets, etc., would hardly ever be cheaper than other algorithms. In your example an appropriate sorting algorithm for example would do and you could achieve very reasonable complexity that way...

And if you're talking off chain where gas costs don't matter, you can use linear searches in arrays anyways... and like for the growing arrays you could e.g. use helper functions or libraries to make it more convenient...

Currently, I don't see a feasible way to do this efficiently and safely in general...

**Comment by mudgen** [comment]
I understand and make sense. Thanks @ekpyron!
