### ISSUE TITLE
Testing / EVMHost: Failure should only be revert, out of gas or invalid opcode

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8463]
During testing, we should check that EVM call failures are ever only
 - revert
 - out of gas (debatable)
 - invalid opcode

the other error codes result from invalid code generated and should not appear.

**Comment by ekpyron** [comment]
To do this we should assert in ``ExecutionFramework::sendMessage`` that ``result.status_code`` is one of the status codes corresponding to those errors.

**Comment by chriseth** [comment]
I would also like to have that for inner calls.

**Comment by ekpyron** [comment]
I had a quick look yesterday - apparently we get underflow results for some tests for uninitialized function pointers in memory and surprisingly also for a test with an assembly "invalid"... not exactly sure why...

**Comment by ekpyron** [comment]
Confirming: Using ``build/test/soltest --color_output=false --log_level=test_suite -t SolidityEndToEndTest -- --show-messages`` I see "result: 7" (which is ``EVMC_STACK_UNDERFLOW``) on develop for a handful of test cases.

**Comment by ekpyron** [comment]
Apparently, (thanks @axic) this is most probably due to a peculiarity in the evmone implementation. Apparently, for performance reasons, the status code is not always entirely accurate. Also I looked at the bytecode for one example of the cases for which we had a stack underflow result and it looked just fine. But unfortunately this probably means that we won't be able to check the exact status code.

**Comment by ekpyron** [comment]
For reference, see https://github.com/ethereum/evmone/blob/master/docs/efficient_gas_calculation_algorithm.md#evm-may-terminate-earlier

**Comment by ekpyron** [comment]
Based on that I think I'll close this.
