### ISSUE TITLE
Discussion: Delegate contracts / dynamic libraries / upgradable contracts

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8490]
This is a general discussion item about high-level support for "dynamic delegatecall with storage access", upgradable contracts including storage layouts that permits changing the data format.

**Comment by chriseth** [comment]
Related: #2469 #8430 #8353

**Comment by 3esmit** [comment]
maybe it could be discussed to solidity use storage in a way its not affected by upgrades on the schema (data format). 

For example, if you make at high level, a mapping (bytes32 => bytes) data, and this is used to store all the contract state variables. 
I've seen this approach being done in top of solidity but it renders code thats very hard to read and maintain, if solidity does that, it should be only for some type of contracts (upgradable ones) because this would increase the gas cost. 

In language design, maybe this could be sorted out in a similar way that "pointers" are in C programming language?

`bytes32 * varName;`  would use this new method of accessing storage.
