### ISSUE TITLE
Cleanup of intra-solidity libraries

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#854]
The solidity repository has several libraries which is not really needed.
We can either put everything in libsolidity or just do not provide libraries, but instead link everything that is needed in the executables soltest, solc, soljson and lllc.

In this task, the weird `eth_use` macro should also be removed and replaced by a cmake native feature.

**Comment by bobsummerwill** [comment]
I can do a pass on the CMake files, just like I already did for cpp-ethereum at https://github.com/bobsummerwill/cpp-ethereum/pull/2.

Having gone through that process once, I can do it again much quicker for Solidity, which has many fewer modules.

The easiest approach is likely just to plop everything into `libsolidity`, yes.

Aside - I honestly think that the same kind of consolidation makes sense in cpp-ethereum too - ie. just blob everything together into libethereum.     You can still have sub-structure within folders, but the actual separate `.so` files really add no value, IMHO.

If we were actually having optional modules for optional features with runtime dynamic library loading with some plugin mechanism, it would be a different story.

Another consideration here is that because we are (intentionally) not providing any published C++ API, the innards of these repositories can be refactored at will.     We just need to make them as simple as they can be, for ease of work and iteration.

If at some future point we add published C++ APIs then that is when we need to consider fine-grained `.so` boundaries again.    For now it's just "you're never gonna need it" premature, IMHO.

**Comment by chriseth** [comment]
sounds good!

**Comment by axic** [comment]
Is this still an open issue?

**Comment by chriseth** [comment]
Yes, eth_use is still present.

**Comment by chriseth** [comment]
@chfast could you also take a look at this one, please?

**Comment by chfast** [comment]
Yes, sure.

**Comment by chfast** [comment]
Fixed by https://github.com/ethereum/solidity/pull/2757.
