### ISSUE TITLE
[Sol->Yul] Immutables

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8551]
Part of #3835 

We should also implement the code generation for immutables for Yul.

For this, we need new built-in functions in the dialect:
 - `setImmutable("name", value)`
 - `loadImmutable("name")`

This adds the complication that it is a builtin function that has a literal parameter but not all parameters are literals, so we need to modify the member "literalAguments" to specify the parameters that are required to be literals.

It should be possible to transfer the lvalue mechanism of the legacy codegen for immutables.

Finally, `setImmutable` and `loadImmutable` need an implementation in the assembly:

AbstractAssembly and all classes inheriting from it need two new functions to set and retrieve immutables. These are already implemented in the legacy Assembly (which is accessed via the EVMAssemblyAdapter).

**Comment by Marenz** [comment]
I am starting to work on this, for now only the literalArguments parts #8626

**Comment by chriseth** [comment]
I'm working on the actual code generation, assuming the dialect has the needed support.

**Comment by ekpyron** [comment]
Since we disabled external function pointers temporarily for the bugfix release in https://github.com/ethereum/solidity/pull/8586, we now need to decide how to deal with them. Two options:
- Use two separate slots (so basically just revert https://github.com/ethereum/solidity/pull/8586) and think about how to deal with this in the debug output.
- Pack them into one slot.

It may make sense to think ahead a bit and consider how dynamic arrays will work. Are they actually planned? Will they be one offset into the code only and the length will be stored at that offset followed by the data? Or will they have two "slots" - an offset and a length? How will they look in the debug output (we might need to split into pointer and content).

**Comment by chriseth** [comment]
Dynamically-sized arrays have to use codecopy at least for the actual data. This invalidates the "datasize" builtin, but I think it is still fine, because we only use it on the construction data.

Can you draft how it would look if we use the length literally and codecopy for the data and if we use codecopy for both?

**Comment by ekpyron** [comment]
Ok, let's think about
```
contract C {
  uint[] immutable x;
  constructor() public {
     x = new uint256[](2); x[0] = 23; x[1] = 42;
  }
  function f() public returns (uint256[] memory) {
    return x;
  }
}
```

During the constructor code, there will probably be one "reserved" memory slot for the array.
Storing would just be ``setimmutable("x", mpos)``.
After the constructor body, I expect that we won't be able to copy the code to offset 0 anymore, but will have to copy to the free memory pointer instead.

```
  let codeStart := mload(<freeMem>)
  let codeEnd := add(codeStart, <runtimeCodeSize>)
  // copy runtime code to [codeStart, codeEnd)

  // ... copy value type immutables from reserved memory to occurrences in code ...
  // for x itself:
  let x_src_mpos := mload(<reservedMemorySlotForX>)
  let x_dst_pos := codeEnd
  codeEnd := <copyArrayFunction>(codeEnd, x_mpos) // copy array x to codeEnd and return memory end
  // copy x_dst_pos to occurrences in code
```

Actually, instead of copying the array that part could be:
```
codeEnd := <abiEncodingFunction>(codeEnd, x_mpos)
```

Accessing the immutable from runtime code:
```
  let result

  let x_ptr := getimmutable("x") // fetches the one-slot offset into code
  let mpos := mload(<freeMem>)
  result := mpos
  codecopy(mpos, x_ptr, 32)
  let x_len := mload(mpos)
  let x_msize := mul(x_len, <memoryHeadSize>)
  codecopy(mpos, add(x_ptr, 32), x_msize)
  mpos := add(mpos, x_msize)
  // iterate further for nested arrays... for those the length has to be in code only anyways...
  mstore(<freeMem>, mpos)
```


Actually, this could really be
```
  let result

  let x_ptr := getimmutable("x")
  result := <abiDecodeFromĆodeFunction>(x_ptr, codesize())
```

**Comment by ekpyron** [comment]
Not sure that comment above is too helpful, but in any case, there seems to be arguments for and agreement about packing external function pointers into one slot for immutables.

**Comment by chriseth** [comment]
Maybe we should even have `code` references then like we use for `calldata`: If you use `immutableVar[2]` you don't need the full copy to memory.

**Comment by ekpyron** [comment]
Haha, if we go down that road, one might argue that ``immutable`` really isn't a good name, but that we instead rather should have said that state variables can have two different data locations, namely ``storage`` and ``code`` :-).

**Comment by chriseth** [comment]
I think this is fully implemented now. Please reopen if I'm mistaken.

**Comment by wminshew** [comment]
> I think this is fully implemented now. Please reopen if I'm mistaken.

hi -- saw there was some discussion in here around immutable dynamic arrays. Is there any plan to still include those (and perhaps mappings) in the future?

**Comment by k06a** [comment]
Can we have it somehow available in Solidity Assembly?

**Comment by zerosnacks** [comment]
> Can we have it somehow available in Solidity Assembly?

Seconding this, would be great to have this available there
