### ISSUE TITLE
Yul support in Pygments

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8608]
Similar to the Solidity version (https://gitlab.com/veox/pygments-lexer-solidity), this would help us to have nice syntax highlighting in the Solidity documentation.

@veox would you be interested in helping out? If so, how could we help you?

**Comment by veox** [comment]
Sure, why not.

There's already [some support for `assembly`](https://gitlab.com/veox/pygments-lexer-solidity/-/blob/17cc012c0aae3103bad0d5ee5ed1bd110bf3da71/pygments_lexer_solidity/lexer.py#L66), that one's relatively simple. I don't think Yul will be much ~~different~~ more difficult.

That said: can Yul be used from a Solidity program (similar to Assembly)? Because if yes, then `token['yul'] = token['assembly']` in the existing Solidity lexer is the starting point; and if no, then copy-pasting a `pygments-lexer-yul` might be the approach, or perhaps branching off a `YulLexer` class...

([All the examples](https://solidity.readthedocs.io/en/v0.6.4/yul.html) seem to be for standalone use.)

**Comment by axic** [comment]
Inline assembly in Solidity **is** Yul, but a different sub/superset.

The main difference, which cannot be represented in inline assembly, is Yul objects currently. See https://solidity.readthedocs.io/en/v0.6.4/yul.html#specification-of-yul-object

**Comment by veox** [comment]
> Inline assembly in Solidity **is** Yul, but a different sub/superset.

Ah, yes, [I see now](https://solidity.readthedocs.io/en/v0.6.4/assembly.html).

So what you'd want, essentially, is this:

```
.. code-block:: yul
    
    {
        function power(base, exponent) -> result
        {
            ...
```

Right?

-----

Another thing is that the lexer still has to support previous versions of Solidity, from when Yul didn't yet exist in current form. I.e. `assembly` code with `dupXX`s and `swapXX`s should still be highlighted properly.

Not a big issue, nothing inheritance can't fix. Already working on it.

**Comment by axic** [comment]
Yes with it will be used with `code-block` or `highlights`.

It would be nice to also support the Yul object notation I've linked above.

**Comment by veox** [comment]
First attempt is now in `pygments-lexer-solidity` v0.5.0 ([just pushed to PyPI](https://pypi.org/project/pygments-lexer-solidity/#history)).

Sphinx's `conf.py` will need modification: also importing the `YulLexer`.

Testing it locally, I see that variable declarations with types, e.g.

```
let zero:uint32 := 0:uint32
```

are not done well, since `:` is not matched by anything. This is easy to fix, but I am wondering:

* whether this is the only thing I missed;
* whether this is valid syntax in "inline assembly", including before Yul got the name "Yul".

-----

Would you mind also testing it locally and saying if anything else is wrong? I'd like to not be pushing a release for every one-line change. :)

**Comment by veox** [comment]
If the CI supports building docs, I could also submit a PR, so the visuals can be viewed online.

Not sure you're not better suited for the task, though.

**Comment by veox** [comment]
FWIW, [v0.5.1](https://pypi.org/project/pygments-lexer-solidity/0.5.1/) with the above fix is out.

**Comment by chriseth** [comment]
@veox yes, the CI builds the docs and also has a preview feature. Could you please create a PR to activate your module?

About the types: Currently, inline assembly does not support types, but it probably will in the future - so it would be good to already activate that feature in the highlighter.
