### ISSUE TITLE
Ability to import into inline assembly

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8612]
Should we allow the ability to import contract-wide function definitions into an inline assembly block?

Example:

```
contract c {
  assembly EVM named "mainblock" {
    function f() { ... }
  }

  function g() public {
    assembly EVM import("mainblock") {
      f()
    }
  }
}

```

**Comment by cameel** [comment]
Do we still want this given that we're planning to allow file-level assembly blocks (#9282)?

**Comment by k06a** [comment]
What about "assembly libraries"? https://github.com/ethereum/solidity/issues/13472

**Comment by cameel** [comment]
I think #9282 is meant to allow use very similar to "assembly libraries" (or rather "assembly free functions", but free functions are not much different from internal library functions, they are just not grouped into a namespace). The assembly functions are going to be visible globally in the whole file that contains them and you will also be able to import into other files via the normal import mechanism.

The issue here seems very similar to #9282 but without making the assembly functions available globally. Instead you define them in a block inside a contract and explicitly import that in another block. This is different enough so I'm not closing it yet but it seems to me that #9282 is a simpler way to enable the same use cases.

In the "assembly libraries" use case this issue gives you an extra namespace for free but I don't think it's such a big deal since you can just put the file-level block in a separate file to get a namespace.

**Comment by ekpyron** [comment]
I consider this superseded by #9282 and am closing.
