### ISSUE TITLE
Optimiser confused by something

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8670]
This is the most minimal example I've got so far:
```
contract C {
  function f() external {
        bytes memory amount;
        bytes24 zero_bytes24;
        bytes32 signature_root;
        bytes32 node = sha256(abi.encodePacked(
            sha256(abi.encodePacked(amount, zero_bytes24, signature_root))
        ));
  }
}
```

With `--optimize` (default settings, albeit tried with `--optimize-runs 10000000` too) there is this snippet in the output:
```
        /* "optim.sol":197:251  abi.encodePacked(amount, zero_bytes24, signature_root) */
      pop
      pop
      pop
      swap1
      pop
      add
      dup4
      not(0xffffffffffffffff)
      and
      not(0xffffffffffffffff)
      and
      dup2
      mstore
      0x18
      add
```

The `not and not and` part doesn't seem to make any sense.

**Comment by chriseth** [comment]
Can it be that we never had optimizer rules for `x and (x and y) -> x and y`?

**Comment by chriseth** [comment]
We indeed did not have such a rule, but moving constants out and applying `and(x, x) -> x` should also do the trick here...

**Comment by chriseth** [comment]
It seems that #8707 does not solve this issue :(

**Comment by axic** [comment]
```
      0xffffffffffffffff
      not
      and
      0xffffffffffffffff
      not
      and
```

Probably the optimiser can't understand `not(0xffffffffffffffff)` as a single "value". Should we first flatten these expressions, run the rulelist, and then as part of the constant optimiser shorten them? (Perhaps need to add a rule for turning them into `NOT(A)` expressions if it is shorter than `A`.)

**Comment by axic** [comment]
>  Should we first flatten these expressions

The RuleList already contains `NOT(A)`, so not sure why it is not picked up.

> (Perhaps need to add a rule for turning them into NOT(A) expressions if it is shorter than A.)

Constant optimiser does that already.

**Comment by chriseth** [comment]
It could be that the constant representation (the last step) re-introduces the `not` because it is shorter. My problem is rather why the double-and is not reduced. The reason for that could be that the argument to the `and` is not coming from a `dup` but rather it is just reducing the initial stack of the block and thus shortening it.

**Comment by chriseth** [comment]
I did some more investigation on this, but could not find the exact place the code is generated from. The double-and is not removed by the optimizer because it is not an 'intermediate operation' and the stack height before and after the chunk it can operator on is different (at least that is what I think).

**Comment by chriseth** [comment]
The only thing left here that could be done is finding out where the code is generated and maybe remove one of the masks.

**Comment by Marenz** [comment]
This might not even be a problem currently. The current code with the current `develop` branch produces the following:

```
     /* "test.sol":197:251  abi.encodePacked(amount, zero_bytes24, signature_root) */
      add(0x20, mload(0x40))
      dup1
      dup5
      dup1
      mload
      swap1
      0x20
      add
      swap1
      dup1
      dup4
      dup4
```

no trace of `not` and `and`..

**Comment by chriseth** [comment]
It is still there. I think it is  generated because we perform cleanup twice: Once in CompilerUtils.cpp:480 (call to  convertType) and once in CompilerUtils::storeInMemoryDynamic -> prepareMemoryStore -> convertType

Can you check if it is doable without much disturbance and potential for bugs to see if we can skip either the first or the second cleanup?
