### ISSUE TITLE
SMTChecker exhibits strange behavior on unused mappings

### ISSUE THREAD

**Issue by ericr-aon** [ethereum/solidity#8688]
The following code returns no warnings by the SMT checker, as is expected:

```Solidity
pragma solidity >=0.5.0;
pragma experimental SMTChecker;

contract C {
  uint8 x;
  uint8 y;
  // mapping (address => bool) public never_used;

  function inc() public {
    require(x < 10);
    require(y < 10);

    if(x == 0) x = 0; // noop state var read

    x++;
    y++;

    assert(y == x);
  }
}
```

However, as soon as a mapping state variable is introduced we witness the model checker's incompleteness in some very strange ways. Unrelated assertions begin to fail if the function contains any state-reading conditionals at all:

```Solidity
pragma solidity >=0.5.0;
pragma experimental SMTChecker;

contract C {
  uint8 x;
  uint8 y;
  mapping (address => bool) public never_used;

  function inc() public {
    require(x < 10);
    require(y < 10);

    if(x == 0) x = 0; // noop state var read

    x++;
    y++;

    assert(y == x);
  }
}
```

Result:

```
Warning: Assertion violation happens here
  --> bug:18:5:
   |
18 |     assert(y == x);
   |     ^^^^^^^^^^^^^^
Note:   for:
  x = 2
  y = 3

Note: Callstack:
Note:
```

**Comment by leonardoalt** [comment]
Unfortunately this comes from the Horn solver used by the CHC engine. Apparently just adding an SMT Array (used by the Solidity `mapping`) to the predicates (even though they are only passed around and not used in any constraints) makes the solver return `unknown`. In this case, the BMC engine is used, and since it doesn't have knowledge about contract invariants it returns this false positive.
I'm going to try the current development version of the solver to see if the problem persists, and in that case open an issue with them.
Thanks for reporting!

**Comment by leonardoalt** [comment]
Ref https://github.com/Z3Prover/z3/issues/4054
