### ISSUE TITLE
In-language testing syntax / support

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#8773]
I thought we had a tracking issue for this already. Last we've discussed I believe was in September 2017.

Some languages have built-in support for unit testing, such as [C#](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2019), [Rust](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html) and [Python](https://docs.python.org/3/library/unittest.html). Many other languages don't have it, but delegate it numerous external libraries, such as Javascript and C/C++.

In Solidity currently there is no language level support and different external projects approach the question differently:
- Embark only support [tests written in Javascript](https://framework.embarklabs.io/docs/contracts_testing.html)
- Truffle supports both [Javascript](https://www.trufflesuite.com/docs/truffle/testing/writing-tests-in-javascript) and [Solidity tests](https://www.trufflesuite.com/docs/truffle/testing/writing-tests-in-solidity)
- Remix supports a testing framework [written in Solidity](https://github.com/ethereum/remix/tree/master/remix-tests)
- Dapphub's ds-test is also [written in Solidity](https://github.com/dapphub/ds-test)
- *not sure about others*

I think it would be nice to explore whether language support could be beneficial here.

#### Current tests written in Solidity

Truffle's [AssertBool.sol](https://github.com/trufflesuite/truffle/blob/4bcb4691d58e92f89ee5b94cce273d0db5f51544/packages/core/lib/testing/AssertBool.sol), Remix's [test.sol](https://github.com/ethereum/remix/blob/master/remix-tests/sol/tests.sol.js) and ds-test's [test.sol](https://github.com/dapphub/ds-test/blob/master/src/test.sol) all define a helper assertion library, which under the hood emits an event. The runner can catch this event and display the results.

#### What is the benefit of having language-level support?

The main benefit is that tests would be more closely coupled with sources. Potentially (some) tests could be framework agnostic, facilitating cross-platform support (e.g. running something in Remix, then transitioning to Embark/Truffle)

A secondary benefit is having access to `internal`/`private` members when the test is closely coupled. Currently contracts have to avoid using internal/private members or introduce (derived contracts and) helpers exposing those.

#### Some initial proposal

An important question to address: do a) we want tests to be executed by the compiler; or b) only exposed them in some standard way (through "standard json")?

In any of the cases it would be beneficial to separate the syntactically tests. I really like the approach of Rust and C# where tests are decorated (with `#[test]` and `[TestClass]`, respectively). Furthermore Rust has a syntax for configuration options further separating tests (`#[cfg(test)]` -- a somewhat relevant attempt was discussed in #1650).

In Solidity we could introduce a new top level keyword to group tests:
`test {}`

Any function inside could be its own test case, however supporting "before"/"after" handlers would also be useful.

Q1: Is this a useful/needed feature?
Q2: Should the compiler perform these unit tests?
Q3: Should these test contracts be exposed with some special marking in the standard json output (so that frameworks can run the tests)?
Q4: Is there a need for init / beforeEach / afterEach / beforeAll /  afterAll?
Q5: Should these tests support more complex features (such as changing "chain" properties, including time)?
Q6: Should it amend calls with "sender" or introduce another interface (such as `msg.sender = 0x1234`)

---

Here is a longer example:
```
// Based off https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/token/ERC20/ERC20.test.js

contract ERC20 { 
    // Assume the ERC20 token is here.
}

test {
    address token;

    address initialHolder = 0x123;
    string name = "My Token";
    string symbol = "MTKN";
    uint initialSupply = 100;

    modifier beforeEach() {
        token = new ERC20(name, symbol, initialHolder, initialSupply);

        _;
    }

    case("has a name") beforeEach {
        expect.isEqual(token.name, name);
    }

    case("has a symbol") {
        expect.isEqual(token.name, name);
    }

    case("transfer without balance") beforeEach {
        try {
            token.transfer{sender=0x555}(0x333, 12 eth);
            expect.failure();
        } catch (bytes memory) {
            expect.success();
        }
    }
}
```

Some alternate syntax options:
```
    test "has a name" { }
    test("has a name") {}
    case "has a name" {}
    case("has a name") {}
```

**Comment by axic** [comment]
Discussed this during the Solidity Summit and on the gitter channel.

There seemed to be an interest to at least define conventions which can be shared with all the different frameworks. An easy option is to define an interface for the "assertion library" so that tests all can use the same functions, but allow the frameworks to implement their own methods (the specific events those assertions output).

Additionally would need to agree on conventions for beforeAll/afterAll/beforeEach/afterAll.

**Comment by GNSPS** [comment]
_Pasting formatted comments and images from the Gitter chat in case it is helpful for future reference:_

Dominic Letz @dominicletz 16:20
i'm definitely pro having "native" syntax to enable testing switches
having testing support outside the compiler e.g. in some preprocessor means we're losing type support , and in the worst case could lead to the C/C++ precompiler macro mess

chriseth @chriseth 16:21
@dominicletz what do you mean by "testing switches"?

Alex Beregszaszi @axic 16:22
Damn deleted by editing :(
Slides are here: https://axic.github.io/notes/summit/testing_syntax/

Some features proposed: https://axic.github.io/notes/summit/testing_syntax/#/8

An example: https://axic.github.io/notes/summit/testing_syntax/#/9 (need to scroll within the highlighting)

It uses `token.transfer{sender=0x555}(0x333, 12 eth);` to change sender.

Feist Josselin @montyly 16:23
I would advocate to do a review of the features of the different unit tests framework that exist, and evaluate which ones you want/can have

I like the idea, but my concern is that due to the limitations we discussed, the developers will either need to use two different framework for testing (the "solidity unit tests", and an additional one), or will just not use the solidity unit tests

Dominic Letz @dominicletz 16:23
@chriseth e.g. switching private members public, or changing variables during test runs, or changing imports during test runs

Alex Beregszaszi @axic 16:25
@montyly @MrChico @alcuadrado would you guys prefer to agree on a “testing syntax” using regular Solidity contracts, e.g. a standard “assert” library? Or would you prefer having some special syntax/annotations? Or both?

chriseth @chriseth 16:25
thanks, @dominicletz ! maybe something that could be useful short-term would be some kind of mock support, basically transparently exchanging contract names.
on the other hand, that could probably also be done using remappings

Feist Josselin @montyly 16:28
@axic I am not sure. I could be interesting when designing the unit test syntax to take into account the discussion on the pre/post conditions annotations

Dominic Letz @dominicletz 16:31
@chriseth would be awesome, I've got this pile of ugly source code, that we've annotated with comments and that our CI is sending through sed to generate and execute tests

![image](https://user-images.githubusercontent.com/4008213/80735395-883e3980-8b08-11ea-87f1-0aaf2819df3c.png)
![image](https://user-images.githubusercontent.com/4008213/80735409-8d9b8400-8b08-11ea-92de-98f73f3cfd52.png)

would love to get rid of that stuff

Alex Beregszaszi @axic 16:32
@montyly yep, all of these are quite related :)

MrChico @MrChico 16:32
@axic I think it could be a good idea to come to an agree on annotations for tests. `dapp` deals with `setUp()` (a.k.a. beforeEach) and simply marks test functions to be run by having `test` or `testFail` as part of their name. The convention is `.t.sol` for tests.
conforming on these annotations sounds like a good idea

Alex Beregszaszi @axic 16:33
:thumbsup:

Feist Josselin @montyly 16:33
+1 with @MrChico

Gonçalo Sá @GNSPS 16:34
> @montyly @MrChico @alcuadrado would you guys prefer to agree on a “testing syntax” using regular Solidity contracts, e.g. a standard “assert” library? Or would you prefer having some special syntax/annotations? Or both?

I think the library approach is fine and definitely keeps a separation of concerns.

I do remember that Truffle was a little bit buggy and strict when it came to running tests with assertion libraries I wrote to extend their own. (https://github.com/GNSPS/solidity-bytes-utils/blob/master/test/TestBytesLib1.sol#L42-L44)

Probably a standard is in order? To at least have the frameworks agree on the events being fired?

> @axic I think it could be a good idea to come to an agree on annotations for tests. `dapp` deals with `setUp()` (a.k.a. beforeEach) and simply marks test functions to be run by having `test` or `testFail` as part of their name. The convention is `.t.sol` for tests.
> conforming on these annotations sounds like a good idea

A cross-framework standard for function names, file names and event names.

Alex Beregszaszi @axic 16:36
Would you want to enforce the implementation of the assertion library (e.g. the events it generates) or just the interface?

MrChico @MrChico 16:37
an advantage of using functions over case("test") syntax is that it can take arguments which is great for more advanced testing
Just the interface I think is sufficient

Gonçalo Sá @GNSPS 16:38
I think the interface is sufficient, too

Alex Beregszaszi @axic 16:38
There also the option of `case “test” (arg1, arg2, …) {}`


MrChico @MrChico 16:40
haha okay

 > There also the option of `case “test” (arg1, arg2, …) {}`

would this generate the same code as `function testCase(arg1, arg2, ...) {}`?

Alex Beregszaszi @axic 16:40
With the added functionality that the test case can have spaces, etc. I think today that is hidden in assertions.

**Comment by montyly** [comment]
Hi,

Is there any news on this topic? Imho having unit-tests support within Solidity would ease a lot the testing, and remove the burden from all the developers working on different compilation frameworks. 

As we discussed back in 2020, it could also allow having pre/post invariants written directly in Solidity, and makes the property-based testing/verification a lot simpler.

In the long term, I think it would be awesome to see less fragmentation in the Solidity compilations ecosystem, and a unified cargo-style approach for solc, like:
```
$ solc new project_name
$ solc compile
$ solc test
```
