### ISSUE TITLE
[Sol -> Yul] Cleanup not always done

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8795]
I think that in the Sol -> Yul translation, cleanup is not always done, at least not before equality comparison. Maybe we should do cleanup for every single type conversion?

Specifically, type conversion does not lead to cleanup when the types are the same. This could lead to problems with regards to inline assembly.

**Comment by chriseth** [comment]
Another solution (maybe this is what we had in mind?) is to write every operation on smaller types with dirty higher order bits in mind.

**Comment by chriseth** [comment]
The main question to answer here is if dirty higher order bits would trigger a revert or not.

**Comment by ekpyron** [comment]
I'd argue that neither cleanup in *every* type conversion, nor assuming dirty inputs for operations is actually nice... Since I think this issue can *only* occur using inline assembly, two more options to consider:
- Clean up everything that was written to in inline assembly after the inline assembly block.
- Translate assignments to external references to ``IRVariable`` assignments instead of plain assignments, i.e. do conversions on them. I like this option. It would be weird if ``uint8 x; bool y; assembly { x := 0x2a2a y := eq(x, 0x2a) }`` set ``y`` to ``true``, but it could just revert on ``x := 0x2a2a``...
