### ISSUE TITLE
Support custom natspec / doc tags.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#8802]
We could support e.g. all tags that start with `_`.

**Comment by chriseth** [comment]
The contents of these tags could be exported via json, either only in the ast or even somewhere else.

**Comment by frangio** [comment]
This would be great. I've wanted something like it before for our documentation generator. https://github.com/OpenZeppelin/solidity-docgen/issues/131

**Comment by axic** [comment]
From @frangio:
```
/**
 * @notice Description...
 * !since v2.5.0
 */
contract Foo { ... }
```

I kind of like this separate syntax than underscores. We should consult doxygen for best practice.

**Comment by frangio** [comment]
I was suggesting that syntax only as a hack as long as custom tags are not supported! But I wouldn't go for that for something built in.

We can also consider using an `x-` prefix, it's quite common in different standards.

```
/**
 * @notice Description...
 * @x-since v2.5.0
 */
contract Foo { ... }
```

**Comment by frangio** [comment]
I assume we don't want to allow arbitrary tags in case any of them are granted special meaning in the future. Can we make that explicit?

I was looking at Javadoc or JSDoc and they seem to allow arbitrary tags.

**Comment by chriseth** [comment]
@frangio can you link those standards that use `x-` or something like that?

**Comment by axic** [comment]
Email has it for example.

**Comment by frangio** [comment]
Also HTTP headers. It seems to be popular in network protocols, though there also seems to be a [newer recommendation](https://tools.ietf.org/html/rfc6648) _not_ to use the `X-` prefix. I was pretty sure I had seen it in other places but I can't find any now.

**Comment by chriseth** [comment]
The recommendation not to use `x-` does not suggest an alternative, and we need a way to mark such tags because we want to warn on tags that are not known to the compiler.

We could also say that we accept all tags of the form `@x-...` and `@_...`.

**Comment by leonardoalt** [comment]
+1 for `@_...`

**Comment by cameel** [comment]
I did a little research to see what other projects are doing. Here's what I've found:

#### MIME types
`x-` is also used for custom MIME types:

[RFC 2045 > 6.3. New Content-Transfer-Encodings](https://tools.ietf.org/html/rfc2045#section-6.3)
> Implementors may, if necessary, define private Content-Transfer-
> Encoding values, but must use an x-token, which is a name prefixed by
> "X-", to indicate its non-standard status, e.g., "Content-Transfer-
> Encoding: x-my-new-encoding".  Additional standardized Content-
> Transfer-Encoding values must be specified by a standards-track RFC.
> The requirements such specifications must meet are given in RFC 2048.
> As such, all content-transfer-encoding namespace except that
> beginning with "X-" is explicitly reserved to the IETF for future
> use.

#### CSS prefixes
Another example are vendor prefixes on CSS properties like `-webkit-` and `-moz-`. The use case is a little different though - they're for experimental properties implemented independently by multiple vendors, possibly in incompatible ways, with the intention of being deprecated when the feature is standardized. And they're a mess: [Vendor Prefixes - about to go south](https://remysharp.com/2012/02/09/vendor-prefixes-about-to-go-south).

#### JSON Schema
On the other hand JSON Schema does not require prefixes:

[6.5. Extending JSON Schema](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.5)
> Additional schema keywords and schema vocabularies MAY be defined by any entity. Save for explicit agreement, schema authors SHALL NOT expect these additional keywords and vocabularies to be supported by implementations that do not explicitly document such support. Implementations SHOULD ignore keywords they do not support. 

#### Javadoc
Javadoc does not require prefixes but suggests using names like `com.mycompany.since` - so a bit like CSS prefixes.

[Javadoc Guide > Javadoc Doclet Options](https://docs.oracle.com/javase/10/javadoc/javadoc-command.htm#JSJAV-GUID-3051737B-FFF9-45F9-85D1-5F07D6703592)
> **Avoiding Conflicts**
>
> If you want to create your own namespace, then you can use a dot-separated naming convention similar to that used for packages: `com.mycompany.todo`. Oracle continues to create standard tags whose names don't contain dots. Any tag that you create overrides the behavior of a tag by the same name defined by Oracle. If you create a `@todo` tag or taglet, then it always has the same behavior that you define, even when Oracle later creates a standard tag of the same name.

#### Doxygen
[Doxygen Manual > Custom Commands](https://www.doxygen.nl/manual/custcmd.html) shows how to create new tags (aliases) but does not list any limitations. There's also no recommended convention. From what I have seen in my search results, people don't seem to bother using prefixes.

#### Python
The `_` prefix is used in Python for private class members (just a convention though, not enforced).

#### Summary
So the common options are:
- no prefix
- `@x-since`
- `@_since`
- `@-docgen-since`
- `@docgen.since`

I'll add two more from myself:
- `@SINCE`
- `@custom:since`

I like the javadoc convention with dots but it might be a bit verbose. Using uppercase letters seems like a succint alternative, though not as obvious. `x-` might be clearer to people who are familiar with this convention from other standards, even if those standards no longer recommend it.

**Comment by frangio** [comment]
@chriseth Please do not emit a warning when the compiler sees a custom tag. If that were the case I would not use the feature, because it would spam our users' terminals with warnings.

Edit: ...or do you mean that unknown tags that are not marked with the special custom notation would emit a warning?

**Comment by cameel** [comment]
> Edit: ...or do you mean that unknown tags that are not marked with the special custom notation would emit a warning?

Yeah, I think this is the intention. So you would get a warning for `@notiec` but not for `@_mycustomtag`.

**Comment by ekpyron** [comment]
We can allow defining custom tags in pragmas - either with or without forcing those to have a special prefix.
```
pragma natspec-extension since "Defines the first version this function appeared in.";
```
We could still warn about unknown tags then, preventing typos in them - and it would document what these tags are supposed to mean.

**Comment by dddejan** [comment]
If there is a strict part of natspec that is parsed with restrictions (e.g., only one `@notice` and such) I think adding extensions like @ekpyron mentioned makes a lot of sense. For such extensions, since they are to be interpreted by the user, there would be no restrictions and they could be attached to any code element (statements, loops, declarations, ...).

We rely on natspec to be able to write annotations in code, so it would be nice to have lots of flexibility in annotation. At the moment, e.g., we have to fiddle with the parser code to be able to annotate loops which is far from ideal (see, e.g., 7391c4e53ba07188ad0f2b377b371757a445ea25).

**Comment by axic** [comment]
While `x-` seems to be widespread given its use in email, I think @cameel's suggestion for `@custom:<tag>` is interesting.

In #10825 there is a proposal to have `@spec[dialect]`.

Maybe we should consider using the same syntax for both (using `since` as an example custom tag):
- `@spec[dialect]` and `@custom[since]` or
- `@spec:dialect` and `@custom:since`

**Comment by axic** [comment]
An important point was brought up during the #10825 call that if random tags are allowed, that also means that mistyped versions of current natspec tags are allowed, which are then easy to miss given the compiler won't complain. One could argue this could be the duty of linters and not the compiler though.

**Comment by cameel** [comment]
Another idea: how about using a different initial character for custom tags? E.g. `#since` or `&since`?

**Comment by chriseth** [comment]
Note that strictly, natspec is only the `@notice` tag. So if we go the pragma route, we should call it `doctag-extension` or something.

**Comment by mijovic** [comment]
> Another idea: how about using a different initial character for custom tags? E.g. `#since` or `&since`?

Or even for example `@#since`?

**Comment by axic** [comment]
Just to summarise, the following prefixes were suggested so far:
- `!since`
- `#since`
- `&since`
- `@x-since`
- `@_since`
- `@#since`
- `@-docgen-since`
- `@docgen.since`
- `@custom:since`
- `@custom[since]`

**Comment by cameel** [comment]
OK, I see that this has already been suggested above (`!` and `@_`) so it was not really a new idea :)

**Comment by chriseth** [comment]
Decision in call: Allow all tags that start with `custom:` without any warning.

**Comment by axic** [comment]
I think we failed to state the formatting of the custom tag (this should apply to the regular tags too, with the exception of `:` for custom), but to be clear I think the following is a good rule: lowercase alphanumeric (a-z0-9) which can not start with a number (`^[a-z][a-Z0-9]*$`). Should it allow any symbols?

**Comment by chriseth** [comment]
@axic I would allow all identifier characters, even including `-`

**Comment by chriseth** [comment]
i.e. `a-zA-Z0-9$_-`

**Comment by axic** [comment]
One question we did not clarify, whether this tag should be emitted in the user documentation or only in the dev documentation.

Currently it is only part of the dev documentation, and thus allows for use cases considering developers only.

**Comment by axic** [comment]
Also for anyone reading this and not the documentation, the pattern mentioned in https://github.com/ethereum/solidity/issues/8802#issuecomment-788062522 is not valid. The final implemented pattern is `[a-z][a-z-]*`.
