### ISSUE TITLE
Allow inheriting implementation for an abstract function

### ISSUE THREAD

**Issue by niklasb** [ethereum/solidity#8970]
## Abstract

This feature request is asking for the following code to compile without errors:

```
pragma solidity ^0.6.8;

interface I {
    function foo() external pure returns (uint256);
}

contract A {
    function foo() external pure returns (uint256) {
        return 1337;
    }
}

contract B is A, I { }
```

## Motivation

In my understanding, an interface in Solidity is similar to a Java interface in that it describes a set of functions that a contract supports. The eventual "final" contracts needs to implement all functions specified in any of the inherited interface. Pulling in implementations of these functions from different base classes is an elegant way to decouple functionality. This technique is often referred to as mixins in other programming languages.

As a practical example based on ERC-20, it might make sense to extract all the allowance-specific functionality into a self-contained `AllowanceManager` contract, and inherit it from `Token` as a mixin:

```
contract AllowanceManager {
  function approve(...) {
    ...
  }
}

contract Token is AllowanceManager, IERC20 {
  ...
}
```

Currently the best possible workaround is to declare `approve` as `public virtual` inside of `AllowanceManager` and override it in Token via `override(AllowanceManager, IERC20)` by just calling `super.approve()`. I assume this induces a small performance panelty for the super call and the `public` instead of `external`

## Specification

The example code in the abstract yields the type error

```
TypeError: Derived contract must override function "foo". Two or more base classes define function with same name and parameter types.
```

I believe this error should be skipped if exactly one of the inheritied definitions contains an actual implementation. In the example code, one of the inherited function is a mere prototype, so the implementation can be resolved unambiguously.

## Backwards Compatibility

I see no issues in this regard.

**Comment by chriseth** [comment]
Two functions declared in two unrelated contracts (`I` and `A`) may have the same name and parameter types, but this does not mean that they are conceptually the same thing. In order to avoid situations where you "accidentally" implement or override conceptually different functions from two unrelated base contracts, Solidity 0.6.x requires you to take action and state "yes, I know that I am overriding two unrelated functions and this is how I combine the two".

I did not try this, but I believe that another solution is to make AllowanceManager abstract and make it inherit from IERC20. This way you tell the compiler that you are actually implementing a part of the interface and the allowance function is the actual allowance function of the ERC20 interface.

**Comment by niklasb** [comment]
I will close this, since the feature request as suggested goes against the design rationales you explained, but just as a quick note: In C++ there is a specific syntax to select a specific inherited function for usage in a subclass to resolve these kinds of ambiguities:

```
using Base::function;
```

which could also be applicable here. What you suggest as a workaround seems reasonable however, and works well for the example case.

**Comment by chriseth** [comment]
Yes, we were actually considering `function f() = Base.function;` as a syntax for such situations.
