### ISSUE TITLE
ICE on calling externally a function that returns calldata pointers

### ISSUE THREAD

**Issue by haltman-at** [ethereum/solidity#9134]
## Description

As of Solidity 0.6.9, it is possible for functions to return calldata pointers.  If such a function is called externally, an InternalCompilerError results.

Suggested fix: Since I don't think there's really any sensible way to handle calling such a function externally, only `internal` and `private` functions should be allowed to return calldata pointers.

## Environment

- Compiler version: 0.6.9
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle

## Steps to Reproduce

```solidity
//SPDX-License-Identifier: MIT
pragma solidity ^0.6.9;

contract CalldataTest {
  function test(bytes calldata x) public returns (bytes calldata) {
    return x;
  }
  function tester(bytes calldata x) public {
    this.test(x);
  }
}
```

Attempting to compile this yields an ICE.

**Comment by chriseth** [comment]
Right before the release, I thought "did we actually test this"? We did, and it worked, but I only tested the `test` function via remix, not the `tester` :)

I think the bug is that `FunctionType::asExternallyCallableFunction` does not properly change the location of the return variables, only the parameters.
