### ISSUE TITLE
[docker] Automated build of docker images.

### ISSUE THREAD

**Issue by aarlt** [ethereum/solidity#9213]
On Docker Hub automated builds can be triggered by commits on a specific branch, or if a tag was created. Build rules can be used to configure how to build the sources into docker images. 

Maybe we could use the tagging mechanism to trigger the automated builds. We could define that tags beginning with `docker-*` will automatically trigger the docker image generation (using the Dockerfiles defined in `.circleci/docker`. The only drawback is maybe that it probably makes the GitHub release page a bit confusing.

However, if we do this on the base of tags named `docker-v<VERSION>` we could create the images with the following tags:
- `ethereum/solidity-buildpack-deps`
	- `emsdk-<VERSION>`
	- `ubuntu2004-<VERSION>`
	- `ubuntu2004.clang-<VERSION>`
	- `ubuntu1804-<VERSION>`
	- `ubuntu1604.clang.ossfuzz-<VERSION>`

I think it would make sense to use the tagging mechanism to realise automated builds of docker images.

How should we do this?

**Comment by cameel** [comment]
Why not do this for the `v<VERSION>` tags? Do we want these images to be built more often than the stable releases?

**Comment by aarlt** [comment]
@cameel The thing is that we may need to change the docker images before a release, to e.g. add some fancy testing to `develop` and probably the docker images stay the same over many solidity releases. 

Right now I think that the cleanest solution is to extract the Dockerfiles (`.circleci/docker`) from the solidity repository and create a new repository e.g. `solidity-buildpack-deps` and configure the image automation there, if a new tag was created there.

@chriseth To the question on whether we couldn't do this based on changes on `develop`: I don't know how we can create nice versioned docker tags. Of course we could probably use the commit hash as an identifier, but with this we may create much more docker images than needed. I would prefer to do the docker image creation more explicitly - based on tags - it makes also the selection of specific versions within the CircleCI config more clean. 

I think to have a new repository `solidity-buildpack-deps` from where the docker image creation is triggered is a good solution.

**Comment by cameel** [comment]
> The thing is that we may need to change the docker images before a release, to e.g. add some fancy testing to `develop`

How about tagging release candidate versions? Something like `0.6.10.rc1`. We could also mark them as pre-relases on github's "Releases" page so they would not be confusing to users. Without release notes they would also not take as much space on the page as stable releases.

> probably the docker images stay the same over many solidity releases.

I think it's nice to at least create a new docker tag even if the image itself is the same. If I were a user and saw a docker image for 0.6.2 while 0.6.10 is the current `solc` version, I would think it's outdated and I would have no easy way to tell that it's not. And if you're building with docker cache, a new image built from the same files is really just a tag so it's very lightweight.

> Right now I think that the cleanest solution is to extract the Dockerfiles (`.circleci/docker`) from the solidity repository and create a new repository e.g. `solidity-buildpack-deps` and configure the image automation there, if a new tag was created there.

I like that idea. It does sound cleaner. We could have versions like `0.6.10-4` for it. `4` would mean that it's the fourth docker image release for `solc` 0.6.10. This is the same system that e.g. Arch Linux uses when they need to release a new, rebuilt package with the same version.

> I don't know how we can create nice versioned docker tags

I also think that building only from tags is the best way to handle this but if you really wanted to build from untagged commits too then you could get a nice, human-readable name for a commit using `git describe --tags`. It returns something like `v0.6.10-44-gf923088d2` where 44 is the number of commits since the tag was created and `f923088d2` is the abbreviated commit hash.

**Comment by chriseth** [comment]
Indeed, this is fully decoupled from solidity compiler releases. I just created solidity-buildpack-deps.

**Comment by chriseth** [comment]
We are currently just incrementing a counter for the docker image names. I think we should stick to that scheme and should not correlate it with the Solidity version - I don't think we should trigger the creation of a new docker image just because we released solidity.

**Comment by cameel** [comment]
Oh, then it's even simpler than I thought. Many projects include version in tags on dockerhub. I thought Solidity had them too.

**Comment by chriseth** [comment]
Note that this is about docker images that provide the build environment, not the docker images that contain the final solidity compiler.

**Comment by cameel** [comment]
Rgiht. Thanks for pointing that out. From the original description I somehow thought we were talking about images with the compiler.
