### ISSUE TITLE
Support compiling GnosisSafe with the IR

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9351]
This source: https://github.com/solidity-external-tests/safe-contracts/tree/development_060

Missing feature: calldata to memory array copy (`address[] calldata -> address[] memory` and `bytes calldata -> bytes memory`) aka #8844.

**Comment by axic** [comment]
I can confirm this compiles now to IR after #9501!

The generated IR (even with `--ir-optimized`) cannot be yet compiled:
```
Exception while assembling: /Users/alex/Projects/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(66): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object &, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Variable param_1 is 2 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Variable param_1 is 2 slot(s) too deep inside the stack.
```

cc @mijovic @chriseth @cameel

**Comment by axic** [comment]
Trying to compile https://github.com/solidity-external-tests/safe-contracts/tree/development_070 results in a new failure:
```
Error: Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:2718
  --> a/safe-contracts/contracts/GnosisSafe.sol:70:9:
   |
70 |         setupOwners(_owners, _threshold);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If I comment out this line, it compiles, but the resulting Yul is still not compilable with or without the optimizer:
```
Exception while assembling: /Users/alex/Projects/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(66): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object &, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Variable param_3 is 2 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Variable param_3 is 2 slot(s) too deep inside the stack.
```

**Comment by ekpyron** [comment]
How did you try to build these exactly? Or better yet: do you happen to still have the yul source that triggers the stack error in the end and can make it a gist or so? I just wanted to check if force-enabling https://github.com/ethereum/solidity/pull/10015 would actually make this compilable, but was quickly fed up by dealing with npm and truffle and all that for it... (that is I haven't actually tried, maybe it wouldn't have been too bad)...

**Comment by axic** [comment]
@ekpyron sorry haven't seen the message. What I was doing in the past is to 1. run `--ir-optimized`; 2. remove the text wrapping from the output; 3. pass it in as yul with `--strict-assembly --optimize`. IIRC.

Now after #10147 I run `--bin --optimize --experimental-via-ir` and it all works flawlessly.

For this particular contract it is still stuck on that missing feature (cc @mijovic): 
```
Error: Unimplemented feature error in /Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp:3362
  --> a/safe-contracts/contracts/GnosisSafe.sol:70:9:
   |
70 |         setupOwners(_owners, _threshold);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ekpyron** [comment]
Ah, ok - I somehow expected it to need some magic standard-json produced by truffle or sth and not that it's just the plain contract file that works just as it is :-).

But yeah, I just tried this with https://github.com/ethereum/solidity/pull/10147 merged together with https://github.com/ethereum/solidity/pull/10015 and commenting out the one offending ``setupOwners(_owners, _threshold);`` line. EDIT: actually changing ``address[] calldata _owners`` to ``address[] memory _owners`` in GnosisSafe.sol:L57 in fact allows to keep the ``setupOwners`` thing uncommented. It's the byte array from calldata to memory copy that is unimplemented, but moving the entire function argument to memory works already.

With disabled memory guards I still get:
```
$ build/solc/solc --experimental-via-ir --bin --optimize ../safe-contracts/contracts/GnosisSafe.sol 
Exception during compilation: /solidity/libyul/backends/evm/EVMObjectCompiler.cpp(66): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object&, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Variable param_13 is 2 slot(s) too deep inside the stack.
[solidity::util::tag_comment*] = Variable param_13 is 2 slot(s) too deep inside the stack.
```

But if I also force-enable the memory guards (even ignoring the assembly, i.e. instead of just reverting https://github.com/ethereum/solidity/pull/10047 forcing ``_useMemoryGuard`` to ``true`` there), then it actually compiles:

```
$ build/solc/solc --experimental-via-ir --bin --optimize ../safe-contracts/contracts/GnosisSafe.sol 
Warning: This is a pre-release compiler version, please do not use it in production.

Warning: SPDX license identifier...

======= ../safe-contracts/contracts/GnosisSafe.sol:GnosisSafe =======
Binary:
608060405234156100...
```
Of course, I have no idea if what it compiles is actually correct ;-). But it at least looks like the stack limit evader stuff can theoretically work with this.
Although unfortunately the inline assembly in those contracts actually allocates memory and all - so to properly support compiling this by default, we'd really need a proper yul-with-memory-objects dialect and rewrite the assembly parts of those contracts in that dialect.

But yeah - I was just curious about that, I'll be off again now :-). But I'm looking forward to see if there's any progress on that last missing feature and on https://github.com/ethereum/solidity/issues/10057 when I'm back in December ;-)!

**Comment by rmeissner** [comment]
(Cross posting from the solidity forum)
I added compiling with `viaIR` and `0.8.2` to the Gnosis Safe Github workflows (see https://github.com/gnosis/safe-contracts/runs/2081894289?check_suite_focus=true#step:6:5) and encountered the error `YulException: Variable param_15 is 2 slot(s) too deep inside the stack.` (can be seen further down in the logs).

**Comment by rmeissner** [comment]
Just a follow up question: Is there a way to fix the error above on our side or does this require an update from solidity side? (Note: I get the same behaviour with `0.8.3`).

**Comment by axic** [comment]
It can be fixed by #10015 (with some changes), as seen in https://github.com/ethereum/solidity/issues/9351#issuecomment-718288343. The PR is not merged yet, ant perhaps it won't be as-is but others providing similar functionality. Optimising the stack layout and stack-to-memory evasion is a big task we are tackling, but unfortunately it may take a bit longer.

**Comment by rmeissner** [comment]
Ohhh I missed the comment 🤦 sorry. Thanks for the update I will keep an eye open for this :)

**Comment by cameel** [comment]
Given that #10015 has been merged and we no longer consider the IR experimental (#12760), I think we can close this.

We've actually had the Gnosis external test running in our CI with `viaIR` enabled since the end of 2021: #12396.
