### ISSUE TITLE
Callcode doesn't work

### ISSUE THREAD

**Issue by ghost** [ethereum/solidity#944]
**COMPILER:** Online Solidity Compiler
**WEB3:** injected with MetaMask

**Here's what I do from JS side:**
1. A.makeCallCode({gas:100000});
2. A.sender() // **0x00000000000000000000000000000000000000000000000000000000000000ff**
3. A.x() // **0x0000000000000000000000000000000000000000000000000000000000000000**

**As I understand it I should get this:** 
1. A.makeCallCode({gas:100000});
2. A.sender() // **tx.origin - my account address**
3. A.x() // **0x00000000000000000000000000000000000000000000000000000000000000ff**

```
contract A {
    B addressB;
    address public sender;
    uint public x;

    function A() {
        addressB = new B();
    }

    function makeCallCode() {
        addressB.callcode(bytes4(sha3('set(uint256)')), 255);
    }
}
contract B {
    address public sender;
    uint public x;

    function set(uint _x) {
        x = _x;
        sender = msg.sender;
    }
}
```

**Comment by Denton-L** [comment]
The reason why this doesn't work is because of the way the compiled bytecode accesses variables in Solidity. When `B.set` executes, it doesn't look for `x`, explicitly. Instead, when `B` is compiled, it sees that `B.x` is in the second storage slot so whenever it deals with `B.x`, it will go there. (This is a gross oversimplification but it should get the point across.)

When you call `A.makeCallCode`, it will run `B.set`. What that does is it will look in the second storage slot (because that's where `B.x` is). In `A`'s case, though, the second storage slot is `A.sender`. Thus, `A.sender` is set to `255`, instead of `A.x`.

In order to fix this, simply rearrange the variable declarations as follows:

```
address public sender;
uint public x;
B addressB;
```

**Comment by ghost** [comment]
@Denton-L, thank you very much, good sir!
