### ISSUE TITLE
Parsing of NatSpec documentation results in unexpected tags/docs.

### ISSUE THREAD

**Issue by dddejan** [ethereum/solidity#9482]
## Description

I am not really sure what to expect from NatSpec parsing. 

Coming from doxygen world, for the following doc

```solidity
/**
 * @dev Line 1
 *      Line 2.
 *
 * Line 3.
 *
 * 1. More docs
 *    @notice hey hey
 *
 * 2. Even more docs
 *    @notice hey hey hey
 */
```

I would expect to get tags:

1. @dev: Line1\nLine2
2. @notice: hey hey
3. @notice hey hey hey

The current compile gives strange results (see below).

Having a good understanding of NatSpec is important for us since our tool `solc-verify` parses contract specification from the comments.

It could be that this is expected behavior. In which case, it would be great if you could clarify a bit how the tags/docs are extracted.

## Environment

- Compiler version: 0.6.8+commit.0bbfe453.Darwin.appleclang

## Steps to Reproduce

Test.sol

```solidity
pragma solidity >=0.5.0;

/**
 * @dev Line 1
 *      Line 2.
 *
 * Line 3.
 *
 * 1. More docs
 *    @notice hey hey
 *
 * 2. Even more docs
 *    @notice hey hey hey
 */
contract Test {}
```

Running 

```console
$ solc Test.sol --combined-json devdoc,userdoc | ruby -r json -e 'jj JSON.parse gets'
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> Test.sol

{
  "contracts": {
    "Test.sol:Test": {
      "devdoc": "{\"details\":\"Line 1     Line 2. * Line 3. * 1. More docs\",\"methods\":{}}",
      "userdoc": "{\"methods\":{},\"notice\":\"hey hey * 2. Even more docshey hey hey\"}"
    }
  },
  "version": "0.6.8+commit.0bbfe453.Darwin.appleclang"
}
```

**Comment by chriseth** [comment]
This is indeed weird, thanks for reporting!

Since `@notice` is the summary of the functionality of a function, it might make sense to disallow it for contracts and it might certainly make sense to only allow a single `@notice` tag.

You mentioned that you parse a contract's specification from the tags. In that case, you might profit from custom tags, don't you? It would be great if you could add your thoughts to https://github.com/ethereum/solidity/issues/8802 !

**Comment by hrkrshnn** [comment]
There used to be a bug in the NatSpec parser which caused problems with empty lines (i.e., lines with just `*`.) This was fixed in https://github.com/ethereum/solidity/pull/8800, i.e., solidity version 0.6.9

Currently this is what the NatSpec for your contract looks like:
```

Developer Documentation
{
  "details": "Line 1      Line 2. Line 3. 1. More docs",
  "kind": "dev",
  "methods": {},
  "version": 1
}
User Documentation
{
  "kind": "user",
  "methods": {},
  "notice": "hey hey 2. Even more docshey hey hey",
  "version": 1
}
```

The NatSpec parser is very rudimentary and doesn't clean up extra white spaces. A quick fix would be to remove more than one whitespaces after the parsing. There are issues asking for improving NatSpec parsing: https://github.com/ethereum/solidity/issues/8247, https://github.com/ethereum/solidity/issues/1617

**Comment by chriseth** [comment]
@dddejan I think there are multiple problems reported here. In your initial example, where would you say `Line 3` is assigned to?

**Comment by dddejan** [comment]
> @dddejan I think there are multiple problems reported here. In your initial example, where would you say `Line 3` is assigned to?

Intuitively, I was thinking that a blank line (ignoring the leading `*`) is a separator so it wouldn't be assigned to any tag. My intuition seems to be wrong though, I just looked up the [javadoc spec](https://docs.oracle.com/javase/9/docs/specs/doc-comment-spec.html) and it says: `Each block tag has associated text, which includes any text following the tag up to, but not including, either the next block tag, or the end of the documentation comment. This associated text can span multiple lines.`

**Comment by chriseth** [comment]
I actually don't think anymore that this is a bug. Please feel free to re-open.
