### ISSUE TITLE
Remove support for the old "legacy" JSON AST

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9512]
The compiler has two JSON AST outputs: the "legacy" and the "compact" form. They mostly contain the same detail but in a vastly different structure.

For a long time Remix static analyzer was relying on the legacy format, but this is not the case anymore. We have also discussed this during our call with frameworks.

*I could not find an issue for this, despite our numerous discussions about it.*

**Comment by chriseth** [comment]
As long as it does not cause us a lot of pain - and I would say it currently does not since we have a conversion function in place that does not need maintenance - I would propose to keep it.

**Comment by ekpyron** [comment]
The "legacy" AST is pretty weird... e.g. it contains stuff like ``baseContracts: [ null ]`` and ``nodes: [ null ]`` for ``contract C {}``...

I guess the reason is that InheritanceSpecifiers are rather children of the contract definition in the legacy AST - but we *still* generate the ``baseContracts`` attribute with weird values apparently...

In any case I vote for dropping this weird legacy AST.

**Comment by blitz-1306** [comment]
Well, let me leave my 5 cents.

Since https://github.com/ethereum/solidity/issues/9552 patch and https://github.com/ethereum/solidity/releases/tag/v0.7.1 release, **legacy** AST lacks an info regarding node positions in following sample:

```solidity
contract Test {
    function some() public {
        uint a;
        for (a = 0; a < 3; a++) {}
        for (a = 0; ; a++) break;
        for (a = 0; a < 3; ) break;
        for ( ; a < 3; a++) break;
        for ( ; a < 3;) break;
        for ( ; ; a++) break;
        for ( ; ; ) break;
    }
}
```
As `null` values was removed in the patch, for listed `for` statements in legacy AST I do not see a way to be certian if `a = 0`, `a < 3`, `a++` are belong to a specific loop header section or to it's body. 

Same could be said about following:
```solidity
contract Test {
    function some() public {
        uint a;

        msg.data[a:10];
        msg.data[a:];
        msg.data[:10];
        msg.data[:];
    }
}
```
I can be certain only for the first and last entries `msg.data[a:10];` and `msg.data[:];`. For other entries, there is no certainty: distincting node position (if `a`/`10` is start/end of slice) for `msg.data[a:];` and `msg.data[:10];` now would be guessing.

So in some sense, legacy AST is already broken (at least in SolcJS).

However, I could be missing something. Would be cool if somebody would clarify the approach for provided samples. Note that compact/modern/newer AST is not affected by the issue.

**Comment by axic** [comment]
Just for clarity, on a design meeting two weeks ago (as seen by "chriseth moved this from Design Backlog to Implementation Backlog in Solidity 9 days ago") it was decided to drop the old JSON AST with 0.8.0.

**Comment by chriseth** [comment]
Closed by https://github.com/ethereum/solidity/pull/10363
