### ISSUE TITLE
Support all Solidity Constants in Inline Assembly

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#9570]
It would be nice if Solidity constants were supported in Yul.

Currently I have to do this:

```Solidity
    bytes32 internal constant ERC20TOKEN_STORAGE_POSITION = keccak256("governance.token.diamond.ERC20Token");

    function erc20TokenStorage() internal pure returns(ERC20TokenStorage storage ds) {
        bytes32 position = ERC20TOKEN_STORAGE_POSITION;
        assembly { ds.slot := position }
    }
```

It would be nice if it worked this way:

```Solidity
    bytes32 internal constant ERC20TOKEN_STORAGE_POSITION = keccak256("governance.token.diamond.ERC20Token");

    function erc20TokenStorage() internal pure returns(ERC20TokenStorage storage ds) {
        assembly { ds.slot := ERC20TOKEN_STORAGE_POSITION }
    }
```

**Comment by ekpyron** [comment]
In general there *is* support for accessing solidity constants from yul just like you want - but unfortunately only as long as they are actually compile-time constant, i.e. with ``bytes32 internal constant ERC20TOKEN_STORAGE_POSITION = 0x6ed1e8b58b8677af52e598804adae6eaacd4c419a6334c92069fde3cd6d8affc;`` it should work.
Calls to e.g. ``keccak256``, however, are not evaluated at compile-time, but rather inlined... we want to fix that and we have several long-standing issues for it e.g. https://github.com/ethereum/solidity/issues/3157 - once that's finally done this should just work... but I'm not sure when that'll be :-).

**Comment by axic** [comment]
Here's the original issue: #3776

**Comment by mudgen** [comment]
@ekpyron The [changelog for Solidity 0.6.12](https://github.com/ethereum/solidity/releases/tag/v0.6.12) says this:
*  Code Generator: Evaluate keccak256 of string literals at compile-time.

So it seems like it should work now. I am using Solidity 0.7.0

**Comment by ekpyron** [comment]
Good point :-). But that change in 0.6.12 was rather a code generation optimization - so you're right, the compiler now actually evaluates keccak256 during code generation, but that's "too late"...
So this issue is a special case of the more general problem, namely, that this works:
```
contract C {
    uint256 constant x = 3 + 1;
    function f() public returns (bytes32) {
        assembly {
            let y := x
        }
    }
}
```
while this doesn't:

```
contract C {
    uint256 constant x = uint256(3) + uint256(1);
    function f() public returns (bytes32) {
        assembly {
            let y := x
        }
    }
}
```

(the latter is not evaluated *early* enough, even though after optimization you'll likely still have ``4`` in the bytecode when referring to ``x``, i.e. it's still *eventually* evaluated during optimization...)

So I still think the most general solution to this would be to implement https://github.com/ethereum/solidity/issues/3157 - but we could also think about introducing a special case for string-literal-keccak256 earlier than that, since that's a likely use for constants...

**Comment by mudgen** [comment]
@ekpyron I gotcha. I appreciate the explanation. Thank you. Yes, a special case for string-literal-keccak256 earlier than that would be great!
