### ISSUE TITLE
A '404' error in the latest Solidity Documentation 

### ISSUE THREAD

**Issue by gitpushOmnik** [ethereum/solidity#9580]
- Noticed a **dead link** present  in **Solidity by Example** module under the  **Recovering the Message Signer in Solidity** section of the Solidity Web Documentation.
  https://solidity.readthedocs.io/en/latest/solidity-by-example.html](url) 

- In the above stated section **Recovering the Message Signer in Solidity**, it states that Solidity provides a built-in function ecrecover and describes its use. The sentence  used in the documentation is as follows:

     "Solidity provides a built-in function ecrecover that accepts a message along with the r, s and v parameters and returns the 
     address that was used to sign the message."

- In the above sentence the word "ecrecover" is a hypertext which contains a link to [https://solidity.readthedocs.io/en/latest/mathematical-and-cryptographic-functions](url) to describe it further. But the page to which the hypertext "ecrecover" directs doesn't exist. i.e page is not found.  

So this is an issue regarding a **Page Not Found** error on Solidity Documentation

**Comment by cameel** [comment]
@cakesoft-omkar Thanks for reporting this! Looks like the link was indeed broken and it was not detected automatically by Sphinx because of wrong syntax being used. I corrected that and also fixed a few more broken links that I found while doing it. It's in #9587 and should be fixed in `develop` soon. https://solidity.readthedocs.io will get updated once the v0.7.1 is out.
