### ISSUE TITLE
Remove or fix install_deps.sh

### ISSUE THREAD

**Issue by ekpyron** [ethereum/solidity#9582]
It's horribly outdated for most distributions. And we don't ever test it.

We just had a report that it doesn't recognize CentOS, even though there is a case for it in the script - but even if it *was* recognized, it would install weird versions of things from weird sources, not install smt checkers, etc.

I vote for removing it and instead making sure to properly document the dependencies (should be the case though).

Somewhat related to https://github.com/ethereum/solidity/issues/8860 - and getting rid of boost :-).

**Comment by chriseth** [comment]
I agree, we should not have any scripts that are fully untested. Furthermore, I always find it scary to run scripts that modify my system.

**Comment by Zachinquarantine** [comment]
can I have this assigned to me? I'd like to work on it.

**Comment by cameel** [comment]
@Zachinquarantine Great! This might not be the easiest task to finish because it's a bit open-ended. We need to agree on what we want to do here. It should not be technically hard though which is why I marked it as `good first issue` anyway.

So, the first question is if we want to keep the script at all. We're getting PRs from people using it from time to time so I guess it must useful to someone. So my vote would be for keeping it but making it more maintainable. Reducing its scope would be a good step in that direction and #11808 looks good in these terms.

I think that one uncontroversial part is that we'd accept PRs that improve the script on specific systems where the submitter can run it locally and verify his changes.

A big open question is how to test it as a whole. I don't think we can realistically maintain CI checks for the whole range of systems it's meant to support but we could be testing it at least on the ones we do have. So adding CI jobs for it would be another thing to do here if we agree on that.

The rest mostly depends on whether this script is even worth more effort. Maybe we could crowd-source it and find some people running various OSes who would be willing to at least periodically check that it works for them and report back? Or maybe periodically create issues asking a larger group of people to verify it on their systems. First though we should somehow gauge interest in that. I suspect that the vast majority of users get the compiler either through tools/frameworks or directly from solc-bin and the script is not relevant to them at all.

**Comment by ekpyron** [comment]
As already stated in the issue I strongly vote for just removing it :-). People are only using it, since we mention it in the docs, if we just specifically list the dependencies there trusting that people are able to install them on their respective platform, then people won't use it anymore. And expecting users to just run a huge intransparent script with root privileges is rather insane anyways :-).

**Comment by cameel** [comment]
> And expecting users to just run a huge intransparent script with root privileges is rather insane anyways :-).

Yeah, I share the sentiment :) We should recommend piping it directly from `curl` to `bash` to make it extra ~scary~ convenient :P

> if we just specifically list the dependencies there trusting that people are able to install them on their respective platform, then people won't use it anymore

Oh. Actually I never really reviewed the whole script, just seen parts of it, but skimming over it now it looks like it indeed just installs a bunch of packages or prints a message in most cases. Only for CentOS it seems to be doing more but that could be extracted into a separate, much smaller script. So I agree, it would be better to just list deps in the docs and get rid of the script. This way there's no expectation that it "just works". As a bonus, people seem much more eager to submit PRs fixing the docs than ones fixing the scripts.

**Comment by cameel** [comment]
In that case, @Zachinquarantine, the next step here would be to replace [Dependencies Helper Script](https://docs.soliditylang.org/en/latest/installing-solidity.html#dependencies-helper-script) section in the docs with the list of dependencies for specific platforms. 

We could also just name the dependencies without going into specific systems but if we already have that info in the script, it would be a waste not to use it. Even if it's incomplete or outdated, we'll likely receive PRs fixing that anyway.

**Comment by ekpyron** [comment]
> Only for CentOS it seems to be doing more 

What the script does for CentOS is *extra* insane :-). And probably also really not what it *should* be doing.

**Comment by cameel** [comment]
Looks like it was hacky from the very beginning: https://github.com/ethereum/solidity/pull/1085#issuecomment-246753624

True, I think that keeping this part is pointless. Might make sense if it was at least up to date but it's both hacky and useless. Looks like it installs GCC 4.8 which we do not support at this point. We even had someone trying to build on CentOS recently (https://github.com/ethereum/solidity/issues/11757#issuecomment-894851120) and I don't think he even tried to run it. If he did, it would not help at all because part of his problem was using GCC 4.8 :)

**Comment by cameel** [comment]
This is now done - the script has been removed in #12237.

**Comment by ekpyron** [comment]
Actually, now I'm wondering about ``scripts/install_deps.cmake``, ``scripts/install_deps.ps1`` and ``scripts/install_deps.bat``... how many of these things are there :-D? ``install_deps.ps1`` is used in CI, so that'll have to stay (even though I'd actually tend to move it to ``scripts/ci``)...
``scripts/install_deps.bat`` is just a wrapper for ``scripts/install_deps.cmake``... which seems to pull in some rather old version of boost... I guess we can remove both of those as well?

**Comment by ekpyron** [comment]
And what's the deal with ``snap/snapcraft.yaml`` :-D? That's for example still on z3 4.8.4 and there's https://github.com/ethereum/solidity/issues/11940... is that file used anywhere? Does anyone maintain it?
I'd vote for getting rid of all that weird baggage :-).

**Comment by cameel** [comment]
- The snapcraft config is maintained by @elopio. He's been working on updating it recently but that effort seems to have stalled. Maybe he's busy. I see no harm in keeping it as long as there's someone willing to maintain it.
- `install_deps.cmake` and `install_deps.bat` are so out of date that I suspect we could safely drop them.
- Moving `install_deps.ps1` to the CI dir sounds fine to me. `install_evmone.ps1` and `install_obsolete_jsoncpp_1_7_4.sh` probably should go there too?
- We also have `install_static_z3.sh`, which is not used anywhere and probably obsolete. I see you almost removed it once (https://github.com/ethereum/solidity/pull/5376#discussion_r241387945) but the PR was closed in the end to be redone properly.

**Comment by ekpyron** [comment]
The ones up for removal are removed in https://github.com/ethereum/solidity/pull/12247.
About the windows scripts: I'd keep them there for now, we actually mention at least ``install_deps.ps1`` in our documentation so far. And since windows doesn't have canonical native package management which could pull in boost and the process is a bit of a hassle IIRC, maybe it makes sense to keep it.
