### ISSUE TITLE
Output Yul ASTs

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#9590]
It would be helpful/essential for verification tools to have access to the Yul ASTs that are generated throughout compilation via Yul.

**Comment by chriseth** [comment]
Related to https://github.com/ethereum/solidity/pull/9053

**Comment by chriseth** [comment]
I'm wondering - is it really essential or would it also work to run solidity in yul mode and output the ast?

**Comment by leonardoalt** [comment]
Which ast would that be? What I'm imagining is that all the Yul compilation steps could be exported:
- Solidity -> Yul
- Yul -> Optimized Yul
- Optimized Yul -> Dialect Yul (if applicable)

**Comment by axic** [comment]
> Which ast would that be? What I'm imagining is that all the Yul compilation steps could be exported:
> 
> Solidity -> Yul

This is called `ir` in standard json, and displayed via `--ir` on cli.

> Yul -> Optimized Yul

This is displayed on cli via `--ir-optimized`.

> Optimized Yul -> Dialect Yul (if applicable)

This is not available yet.

**Comment by chriseth** [comment]
I'm still not sure what this issue is about and what functionality we are really missing here.

**Comment by Marenz** [comment]
As far as I understood, it's about the YulAST, being output as JSON just like our Solidity AST can be exported...

**Comment by cameel** [comment]
This feature was also requested in #11043.

**Comment by bendyarm** [comment]
I believe this issue has its roots in a discussion @acoglio and I had with @leonardoalt .

In order to verify the correctness of specific applications of Yul optimizers, you need the before and after Yul code.

Right now, the "standard JSON" form can contain "ir" and "irOptimized", but those are source code, not ASTs.  Yul surface syntax is unambiguous so that's not too bad.  It does require that we trust the prettyprinter and that we have a formal grammar and parser.  (We have those now.  E.g., the [ABNF grammar](https://github.com/acl2/acl2/blob/master/books/kestrel/yul/language/abnf-grammar-new.txt) could be useful to others.)

However, it would be higher assurance if, in addition to the before and after Yul code, the before and after internal ASTs (that are input and output to the optimizers) could be serialized to the JSON output structure, as @Marenz suggests.

**Comment by cameel** [comment]
@bendyarm 
> the [ABNF grammar](https://github.com/acl2/acl2/blob/master/books/kestrel/yul/language/abnf-grammar-new.txt)

A bit off-topic but since you posted this here, just a heads up that we have made a slight adjustment to Yul grammar recently: #12545. Not sure if it makes any difference to your grammar definition (it might not be 1:1 with yours) but I see you do have `yul-path` there.

**Comment by gnidan** [comment]
I notice this is closed, but I don't get any output for `irAst` for `*.yul` files. Does this require `--via-ir`? Seems like a separate concern... standalone Yul files don't always go through the new IR pipeline, after all.

**Comment by cameel** [comment]
@gnidan `irAst` is only for `*.sol` files. That's to distinguish it from the `ast` output, which gives you the Solidity AST. For Yul you just use the `ast` output to get the AST.

It's independent of `--via-ir`. If you don't use this option, you still get the AST of IR produced by the new pipeline but that IR is just no what what the bytecode was generated from.

**Comment by haltman-at** [comment]
Hey, so I just tried this with Solidity 0.8.21, and I'm still not getting ASTs for my Yul sources?  I'm not using `irAst` or anything, I'm just using the usual `ast` output selection, but I'm not getting anything.

Edit: It's not just that there's no AST; it's that there's no `sources` output at all, only `contracts` and `errors`!  Should I suggest reopening #11043...?  Or is there some other way I'm supposed to do this for Yul...?

Edit: Oh, I see -- I have to request the AST at the contract level, instead of at the file level.  (Even though it ultimately appears in `sources`, not `contracts`.)  That seems like a bug?  But at least it's workable...

**Comment by haltman-at** [comment]
Oh, yikes, here's a bug -- the `sources` output gives the ID as `1`, rather than zero!  Oy...

**Comment by haltman-at** [comment]
(OK, I filed two issues for these -- #14452 and #14453.)
