### ISSUE TITLE
pragma experimental ABIEncoderV2 cannot compile some existing code

### ISSUE THREAD

**Issue by saurik** [ethereum/solidity#9597]
I have now read through a number of issues--mostly supposedly closed and fixed?--surrounding ABIEncoderV2 and stack depth, but I can't find anything that addresses this and it feels like a bug: there is code that works fine without ABIEncoderV2 that breaks with the new encoder... and this code doesn't even use any of the new encoding features, which seems incorrect (and makes it so you can't turn on ABIEncoderV2 on existing code if you want to use the new encoder for some new function).

```solidity
pragma solidity 0.7.0;
pragma experimental ABIEncoderV2;

contract Test {
    function test(
        int, int, int,
        int, int, int,
        int, int, int,
        int, int, int, int
    ) external {
    }
}
```

```Compiler error: Stack too deep when compiling inline assembly: Variable dataEnd is 1 slot(s) too deep inside the stack.```

If this is intentional, is there some place I can get a better understanding of what this new encoder is doing that is so much different than the old encoder for these basic functions?

**Comment by chriseth** [comment]
Sorry, but this is a know limitation. We are trying to improve stack problems, but ABIEncoderV2 is not a drop-in replacement for the older encoder. The way to fix this is to back the 13 variables into structs to allow for better readability.

The reason this fails is because the new encoder uses an intermediate language that prevents some errors but at the same time adds overhead which needs more stack slots.

**Comment by saurik** [comment]
> The way to fix this is to back the 13 variables into structs to allow for better readability.

Thanks for the suggestion, but in addition to finding the readability of a structure vs. parameters subjective, when I tested the gas cost of the structure it was higher than the arguments; I can check that again (as maybe I'd done that wrong or had forgotten exactly what I had tested now, as this was a while ago), but "it is maybe, subjectively, ever so slightly harder for some people to read code that uses parameters, but the resulting program will be more expensive to run until the end of time", I know which side I'm going to fall on (particularly as the entire reason I'm embarking on this project task right now with this new ABI support is to reduce my gas cost ;P).

FWIW, the reason I still consider this a bug is because you can't always just change the code anyway: if that function is specified on an interface, I guess you just can't use the ABIv2 encoder anywhere in your contract? If a function doesn't actually use any struct or tuple arguments, it should have identical drop-in behavior to the v1 encoder, as the v1 encoder would literally still work: like, opting in to "I want to be able to serialize and deserialize structs and tuples using a new maybe-experimental/unstable ABI" shouldn't affect the behavior of functions that are using neither structs nor tuples as parameters, as the ABI for those functions hasn't changed, right?

**Comment by chriseth** [comment]
ABIEncoderV2 is a re-implementation of the original ABI coder. It adds features but the ABI did not change. Since it is a re-implementation, some tradeoff decisions were made with different goals in mind. The new coder creates intermediate code that is readable while the old coder just creates a big mess of opcodes nobody can understand. The new coder performs range checks while the old coder just masks invalid data. Because of that, the V2 coder is not a drop-in replacement and will fail to compile some contracts.
