### ISSUE TITLE
solidity::util::formatNumberReadable signed integer support

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/solidity#9601]
Currently that function does not support signed values, causing, for example:
`Warning 3944: (110-115): Underflow (resulting value less than -57896044618658097711785492504343953926634992332820282019728792003956564819968) happens here`.
That number is actually `-2**255`, so it could be better formatted.

**Comment by axic** [comment]
Probably the same issue: https://github.com/ethereum/solidity/pull/9479#discussion_r464505293

**Comment by Neyromancer** [comment]
Hi, i will try to work on it.

**Comment by Neyromancer** [comment]
Hi, just to clarify. Should the number `-57896044618658097711785492504343953926634992332820282019728792003956564819968 `
be transformed to `-2**255 `
or it can also be represented as 
`-0x80 * 2**248`?
Asking because the number `57896044618658097711785492504343953926634992332820282019728792003956564819968` is now transformed into `0x80 * 2**248`.

**Comment by cameel** [comment]
In my opinion, if that's the current behavior in the positive case then doing a similar thing in the negative one is fine as well. It's still some improvement.

But, it would be best to just change it in both cases to `-2**255`/`2**255`. Unless there's some technical reason preventing this - I haven't really looked at the current implementation yet so there might be something I'm not aware of.

Also note that after implementing it you should update expectations in tests because that's where these numbers are used currently. But don't do it manually - you can just run `isoltest` and accept the changes it proposes (see [Writing and Running Syntax Tests](https://docs.soliditylang.org/en/latest/contributing.html#writing-and-running-syntax-tests) in the docs in case you haven't yet).

**Comment by Neyromancer** [comment]
Actually, i think it is technically possible to move from `0x80 * 2 ** 248` to` 2 ** 255` so i will try to implement it.

I just was not sure whether to follow the current implementation or to do it in the way it was written in the task, i.e. which number representation to take as a basiс representation. But i understand now.
By the way thank you for the link:)

**Comment by Neyromancer** [comment]
if this problem does not block anything. i am still working on it. it took a bit more than expected but guess it is only due to personal reasons.

**Comment by cameel** [comment]
There's no hurry. It would be pretty helpful, especially in cases like https://github.com/ethereum/solidity/pull/10776#discussion_r559728114 but fixing this is not a priority right now so you can work on it at your own pace.

**Comment by cameel** [comment]
@Neyromancer Are you still working on it? Do you need any help?

**Comment by Ruko97** [comment]
If this issue hasn't been resolved yet, I am interested to work on it.

**Comment by cameel** [comment]
It's up for the taking. But I'd recommend the other issue you commented on (#9926) because it's more visible to users and should be more satisfying to fix.

**Comment by Ruko97** [comment]
Are signed integers implemented in the compiler using u256 as well, or is there another datatype for representing signed integers?

**Comment by cameel** [comment]
We have [`s256`](https://github.com/ethereum/solidity/blob/develop/libsolutil/Numeric.h#L47-L50) as well.

**Comment by cameel** [comment]
But to be clear, this function is not limited to `u256`/`s256`. See for example [this place in `BMC::checkUnderflow()`, where it's called](https://github.com/ethereum/solidity/blob/develop/libsolidity/formal/BMC.cpp#L760-L762). It takes the type from the expression so it can be any of the [integer types provided by `TypeProvider`](https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/TypeProvider.cpp#L44-L147).

**Comment by Ruko97** [comment]
It seems that signed integer was not supported in formatNumberReadable because bigint doesn't support the right shift operator. Should i replace the right shift operators with division for all types of integers, or just use division for bigint in a separate condition and keep the right shift operator for the rest of the integer types?

**Comment by cameel** [comment]
@nikola-matic @matheusaaguiar What's the status here? Did these merged PRs fix this issue or is there somehing left to do?

**Comment by nikola-matic** [comment]
> @nikola-matic @matheusaaguiar What's the status here? Did these merged PRs fix this issue or is there somehing left to do?

Should be, but @matheusaaguiar spent a lot more time on this, so let's wait for him to chime in.

**Comment by matheusaaguiar** [comment]
The mentioned PRs have fixed this fixed this issue.
