### ISSUE TITLE
[Yul] Require parentheses around return variables in function definitions

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#9617]
Currently functions definitions look like:
```
function f(a, b) -> x, y {}
```

The proposal is to require parentheses around the return variables:
```
function f(a, b) -> (x, y) {}
```

I do not remember why we have opted to not require parentheses, but the benefit of the second notation is making it clear it returns a tuple.

I'm not yet sold on this change, but thought it is worth discussing.

**Comment by ekpyron** [comment]
I'd vote against this (because per se there's no need for it and I don't think it is required for readability), *unless* we go for https://github.com/ethereum/solidity/issues/8303#issuecomment-673476722, in which case having parentheses around any kind of tuple in general might solve potential issues.

**Comment by chriseth** [comment]
I agree 100% with @ekpyron. The reason there are no parentheses is because tuples do not exist in the language. That's also why we have `let x, y := f()` and not `let (x, y) := f()`.

**Comment by axic** [comment]
Please also refer to the lengthy discussion on gitter about this.
