### ISSUE TITLE
EquivalentFunctionCombiner should be run multiple times

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9668]
The equivalent function combiner is only run once, but I think it does not consider two functions equivalent if they call two different, but equivalent functions. Furthermore, I think it fully fails for two equivalent recursive functions.

**Comment by ekpyron** [comment]
Yeah, I think the idea at the time was that it will/should be run multiple times anyways, since functions might *become* equivalent due to optimization - and we just ignored recursive functions.
The block hasher can rather easily be adjusted to produce equal hashes in these cases (even for equivalent recursive functions) - I imagine actually comparing equivalent recursive functions for equality to be a bit of a hassle, though, but I'd need to think about it, maybe it won't be too bad...
