### ISSUE TITLE
Compiler crash: Variable headStart is 2 slot(s) too deep inside the stack

### ISSUE THREAD

**Issue by k06a** [ethereum/solidity#9685]
## Description

Compiler crash when optimizations enabled, disabling optimization fixes the issue.

## Environment

- Compiler version: 0.6.12 + optimizations enabled
- Framework/IDE (e.g. Truffle or Remix): Truffle + Remix
- Operating system: MacOS 10.15.6

## Steps to Reproduce

Try to compile this file:
[OneRouterView.full.sol.zip](https://github.com/ethereum/solidity/files/5132642/OneRouterView.full.sol.zip)

Output:
```
CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 2 slot(s) too deep inside the stack.

/Users/k06a/Projects/1split/node_modules/solc/solcjs:154
      writeFile(contractFileName + '.bin', output.contracts[fileName][contractName].evm.bytecode.object);
                                                                                        ^

TypeError: Cannot read property 'bytecode' of undefined
    at Object.<anonymous> (/Users/k06a/Projects/1split/node_modules/solc/solcjs:154:89)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by hrkrshnn** [comment]
This seems like a regular stack too deep error, but for the IR. Perhaps you can try compiling with yul-optimizations disabled? For references, see https://github.com/ethereum/solidity/issues/9280 and https://github.com/ethereum/solidity/issues/8959

**Comment by k06a** [comment]
Aren't you gonna fix it? At least point place in the code where the problem is.

**Comment by leonardoalt** [comment]
> Aren't you gonna fix it? At least point place in the code where the problem is.

@k06a In that case you could also try making it easier for us to check the code instead of just pasting a zip file.

**Comment by ekpyron** [comment]
The underlying problem is the fact that the EVM only provides access to the top-most 16 stack slots, which we cannot fix, but only work around. Working around it is quite non-trivial - the first step for that is in progress in https://github.com/ethereum/solidity/pull/9162, but that alone won't be enough (there are several further steps planned on top of that), so it will take a while until we have a general solution for this issue, and it is unclear whether it will happen before we switch to the new Yul IR codegen entirely.

That being said, it usually helps to reduce the number of local variables inside functions or (as probably in your case, since it seems to be an ABIEncoderV2 function argument in your case) reduce the number of arguments to functions to reduce the overall stack strain. Or you can try tweaking the ``--yul-optimizations`` sequence, it may be possible to tweak it for your particular case - but as @leonardoalt says it's quite hard to tell you more than that from the huge code snippet rather than from a minimized example containing the code part in there triggering this (which is most probably only one or two functions).

**Comment by k06a** [comment]
The problem is that this is compiler failure. Wish to see properly handled error of Solidity code. It is pretty huge to determine the exact place of failure. It is not an issue for me, I wish to help you to fix this compiler failure.

**Comment by ekpyron** [comment]
It's a known compiler failure that cannot be detected before code generation, so it's also non-trivial to provide a better error message (the issue is occurring in compiler-generated code that depends on the types you use *somewhere* in Solidity - and then only after the optimizer has then rewritten this compiler-generated code). But you're actually right, it would be nice to retain the original source location in the solidity source through this process and make it part of the error message - I'll check if we have an issue for that.

**Comment by chriseth** [comment]
@ekpyron we had an issue for that but it might be closed because we actually implemented that for most of the "stack too deep" errors. The problem with this instance of the error is that it happens in the utility code and it is not clear which line of the source was responsible for the failing line in the utility code to be generated - there might even be multiple or none at all.

**Comment by ekpyron** [comment]
Yeah, it's somewhat related to https://github.com/ethereum/solidity/issues/8807 then... we could track which solidity source locations trigger the generation of utility code - I think that might be generally helpful for https://github.com/ethereum/solidity/issues/8807...
