### ISSUE TITLE
when build solc, the version is solidity_develop_yyyy_mm_dd.commitxxx, how to remove develop_yyy_mm_dd

### ISSUE THREAD

**Issue by dutyk** [ethereum/solidity#9700]
when build solc from the source, I execute:
cmake .. -DCMAKE_BUILD_TYPE=Release && make  
the solc version is: solidity_develop_yyyy_mm_dd.commitxxx
how to remove develop_yyy_mm_dd, the version is solidity_commitxxx?

**Comment by cameel** [comment]
Just create an empty file called `prerelease.txt`. If it's missing or non-empty, it's a development/prerelease build and the content of the file is included in the version string.

@chriseth I've seen people asking about it a few times already. Maybe we should mention it in https://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source?

**Comment by chriseth** [comment]
Yes! Also note that there is a source archive on the release page that contains the prerelease.txt file. So actually if you build yourself from just some source, it might be good that the version is a prerelease version, since there is no guarantee that the source is actually the one of the release.
