### ISSUE TITLE
Restrict free functions

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity#9735]
@axic brought up that free function still carry around implicit "state" and should maybe be restricted more.

`this` is already disallowed and probably rightfully so.

Maybe it would make sense to also disallow them making external calls, or at least adding a keyword that tells if they can make external calls (and thus forward ether from the contract).

**Comment by mudgen** [comment]
@chriseth @axic What implicit state?  Values such as msg.sender etc?

Why is `this` disallowed? In some small cases `this` might be useful in free functions.  

People don't have to use `this` in free functions if they don't want to.  I don't like restricting/removing capability on the basis that programmers are too stupid to do the right thing.  It can cause us to implement complicated workarounds to do what we are trying to do.

I really like free functions but if they are limited too much then I probably won't use them.  

But I think making things more explicit is good.

**Comment by leonardoalt** [comment]
A free function naturally is not associated with any contract, therefore, in my opinion, conceptually it doesn't make any sense to allow `this` in free functions, and allowing it would be a hack. To me free functions should be as strict as possible.
As @axic pointed out, if `this` is so important for a free function it can just take it as an argument.

> People don't have to use this in free functions if they don't want to.

"People don't have to declare function mutability/visibility if they don't want to", I can go on with the list of things that were less strict and programmers still did the wrong thing, causing big problems.

**Comment by mudgen** [comment]
I don't think we should assume how people will or should write code.  There may be surprising or unthought of uses and patterns that are very useful that people want to use and do.  

We are not programmers of every possible type of application so I don't think we can assume or know how every program should be written. In addition, different programmers have different styles and abilities and knowledge.   

@leonardoalt I don't think that function mutability/visibility limits much what a programmers does.  It enables a programmer to be explicit and enforce how he wants things to work.   I like a language I use to give me capability, choice, expressiveness, explicitness but not restrict me, unless I want that restriction ( this is choice here).

**Comment by leonardoalt** [comment]
> I don't think that function mutability/visibility limits much what a programmers does. It enables a programmer to be explicit and enforce how he wants things to work.

That's not true, since it's mandatory to specify function visibility, for example (except for constructors). It precisely enforces the programmer to be explicit, it's not a choice.
Similarly, disallowing `this` in free functions and forcing the programmer to pass it via argument enforces explicitness.

> In addition, different programmers have different styles and abilities and knowledge.

Of course, in the same way that different languages are more permissive or stricter. In C you can do anything, JS has confusing semantics, would you write smart contracts in any of those languages?
Stricter languages are in general safer, _precisely_ because they don't allow the programmer to do all sorts of crazy stuff, which crazier people might find cool and reuse.
In my opinion, yes we should assume people are going to do crazy unsafe stuff with whatever feature is added, and it's important to try to limit that by design.

**Comment by cameel** [comment]
> I don't think that function mutability/visibility limits much what a programmers does.

But in the same vein passing `this` via a parameter does not really limit you either. It just requires you to be explicit about the fact that your function needs to access the contract instance. There are languages that require you to do this all the time - e.g. Python where every instance method has `self` as the first parameter. You also have to do it in Solidity with libraries and `using for` (the instance needs to be the first parameter). Honestly, I find this style more readable than the implicit `this` in other languages.

Another thing is that like @leonardoalt said, a function is not associated with any specific contract - so what type would `this` have? To make it work the compiler would either have to erase the type or generate a copy of the function code for every type behind the scenes. And it would be confusing to the programmer because now the type of `this` depends on the context in which the function is called rather than where it is defined. JavaScript does this and it's in my opinion one of the more confusing features of the language (the whole prototypal inheritance is).

**Comment by mudgen** [comment]
@cameel @leonardoalt You guys have good points.   I agree with you that good, simple, sane design and safety are important.

**Comment by mudgen** [comment]
@cameel How does `this` work in internal library functions?  Isn't that the same situation where `this` is not associated with any specific contract?  

Not supporting `this` in free functions creates an inconsistency with the rest of the language where `this` is always available in non-pure functions. I'd rather keep that consistency with free functions.

**Comment by axic** [comment]
Free functions are introduced to replace libraries. It does really not matter what libraries do today, because many would agree they are not well designed.

**Comment by mudgen** [comment]
Okay, I think passing `this` as an argument makes free functions harder/less convienent to use and costs more gas.  I'd prefer to have `this` available as it always has been.

**Comment by axic** [comment]
Why would it cost more gas?

**Comment by mudgen** [comment]
@axic I did some checking. I'm sorry I was wrong. It wouldn't cost more gas.

**Comment by cameel** [comment]
@mudgen
> How does this work in internal library functions? Isn't that the same situation where this is not associated with any specific contract?

If a contract calls an internal library function, `this` represents that contract. But in this use case `this` is pretty much neutered. I'm not sure if you can actually do anything more than cast it to an address (`address(this)`) .You definitely can't call other external functions from the same library via it. You also can't refer to contract's functions and storage variables that way. That's why there are no issues with its type.

If you meant it that way then yeah, it would be technically possible to make the address available via `this` in internal functions but I don't think it's worth it just to save some typing. The less stuff is magically available globally, the better in my opinion. Free functions are a new construct so expectations are different and it's a good opportunity to clean it up a bit.

**Comment by mudgen** [comment]
I see, thanks @cameel.

**Comment by mudgen** [comment]
@cameel How you describe `this` in libraries is how I use it and I find it useful the way it is.

There is a consistency in the language that is good.  Having `this` available everywhere and making it work the same way everywhere makes the language easy to understand and use.   I've never had a problem with `this` being available. Solving problems that exist in theory but not in practice may create problems in practice.  

I am leery of developers of tools who don't actually use those tools to make and maintain real word applications in production. Though I realize that sentiment may be impractical or unfair.

I am for adding new useful functionality but I'm not for removing currently useful functionality that breaks the consistency and mental modal of the languages unless the changes create a new and better consistency and mental model and is more useful or convenient and safe.

In practice the magically available variables have been very convenient and useful and haven't caused me problems.

**Comment by leonardoalt** [comment]
> I am for adding new useful functionality but I'm not for removing currently useful functionality

What exactly are you referring to here? `this` isn't even accepted in free functions at the moment, so how is it "removing currently useful functionality"?

**Comment by mudgen** [comment]
@leonardoalt Free functions are a replacement for Solidity libraries in some cases.  Solidity libraries support `this`.

**Comment by mudgen** [comment]
Here is something else:

Sometimes I will write code in a function within a contract.   Later I decide to move that code to a library or free function.  If I can move that code to a free function directly and with no or little change, that is good. It makes it easy to use free functions.   If I have to refactor my code to make it work in a free function because free functions don't support `this` then it is harder to use free functions and complicates my development.

**Comment by leonardoalt** [comment]
Not everything should be moved to free functions. Probably very little should. Sometimes it might make sense, sometimes it makes zero sense. It's easy to claim "free functions need `this`!!!" by saying that not every function is trivially movable to free.

**Comment by mudgen** [comment]
@leonardoalt I think it is good to consider these various things like you are doing.  Thank you.

**Comment by cameel** [comment]
@mudgen Honestly, this is mostly a matter of opinion at this point :) On a purely technical level a limited version of `this` like in libraries is possible. If that's enough for you and you feel very strongly about it, then I think that adding it is not out of the question. But right now the sentiment is slightly against it so you'd just need to somehow show in a compelling way that it's better than just keeping the status quo.

Here's another perspective: part of the reason behind not feeling compelled to make free functions a 1:1 equivalent of libraries is that we think that libraries as a feature came a bit short of solving the issues they were meant to solve. Free functions are a new construct and perhaps a chance to improve on that. Consistency is good but sticking to bad choices for the sake of it isn't necessarily good. `this` is a pretty minor difference so we might remove it but I think that keeping free functions and library functions fully equivalent is not something we want to commit to in general.

**Comment by mudgen** [comment]
@cameel Makes sense. Thanks for your consideration.  I am interested in what you guys come up with to make free functions more useful, safe and convenient. 

I'm pretty happy with how internal functions work in Solidity libraries.  How do they come up short?

**Comment by axic** [comment]
> Maybe it would make sense to also disallow them making external calls, or at least adding a keyword that tells if they can make external calls (and thus forward ether from the contract).

We discussed this on today's call and came up with two potential solutions:
1. Following #9248 introduce the `mutable`/`mutating` mutability keyword. Such free functions allow external calls, others not. Not sure about sending ether.

2. Since storage can only be modified via passing in storage references, a similar explicit method for function calls could be passing in function type pointers.

Example for 2):
```solidity
contract C {
  function adjust(function (uint a, uint b) returns (uint) add) returns (uint) {
    return add(1, 2);
  }
}
```

I think this mostly depends on coming up with a nicer syntax for function types tbh (see #9616).

**Comment by chriseth** [comment]
We could also open up the function call options to tell free functions which part of a contract's "account" they can access:
`freeFunction{sendEther: true}()`, `freeFunction{externalCalls: true}()`

The main things we want to restrict functions to do is sending ether and assuming the "identity" of the current contract in external calls. Is there really a use-case to restrict which external functions a free function can call? If yes, then we can use external function pointers.

**Comment by mudgen** [comment]
Will passing `this` as a parameter to functions make `stake too deep` errors more likely?
