### ISSUE TITLE
[SMTChecker] ICE in if-then-else evaluation because *_trueValue.sort != *_falseValue.sort

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#9741]
## Description

```
pragma experimental SMTChecker;
contract C {
  function f(bool x) public pure { x ? (1,2) : (3,4); }
}
```

throws

https://github.com/ethereum/solidity/blob/f964966090f7e3571e20144fd4aa0b6391aea26e/libsmtutil/SolverInterface.h#L114

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

**Comment by cakesoft-arpit** [comment]
We are hitting that smtAssert because in the class TupleSort, in the operator==, we are comparing "members", which has the following values:

"members" field in Tuple (1, 2) has the following two elements:
tuple(int_const 1,int_const 2)_accessor_0
tuple(int_const 1,int_const 2)_accessor_1

"members" field in Tuple (3, 4) has the following two elements:
tuple(int_const 3,int_const 4)_accessor_0
tuple(int_const 3,int_const 4)_accessor_1

Since those strings are different, TupleSort operator== is returning false causing that smtAssert to hit.

I'm not sure about the best way to solve this issue. Any suggestion?

**Comment by leonardoalt** [comment]
@cakesoft-arpit Yea that's an annoying case with RationalNumberTypes that put the value itself into the type name. I started looking into it yesterday and might have a fix today.
