### ISSUE TITLE
ICE's formattedMessage field is truncated

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/solidity#9926]
## Description

When the compiler emits an ICE in the standard json output, the ICE's `formattedMessage` field is truncated. For example:

```
{ 
     component: 'general',
     formattedMessage: 'InternalCompilerError: \n',
     message:
      'Internal compiler error (/solidity/libsolidity/codegen/CompilerUtils.cpp:1440):',
     severity: 'error',
     type: 'InternalCompilerError'
}
```

I believe it should be something like: `"InternalCompilerError: (/solidity/libsolidity/codegen/CompilerUtils.cpp:1440)"`.

While the proposed version is not very human friendly, it would make googling for errors much much easier.

## Environment

- Compiler version: I tried in 0.7.2, but I'm pretty confident that th
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): buidler
- EVM execution environment / backend / blockchain client: nonce
- Operating system: macos catalina

## Steps to Reproduce

Compile a file that doesn't use abi encoder v2, and imports one that does.

**Comment by Ruko97** [comment]
Has this issue been resolved yet? If not, I am interested to work on it.

**Comment by cameel** [comment]
@Ruko97 It hasn't and it would be a nice improvement. So if you want to try, go ahead.

I'd start by looking at [these exception handlers in `StandardCompiler.cpp`](https://github.com/ethereum/solidity/blob/v0.8.14/libsolidity/interface/StandardCompiler.cpp#L1121-L1223), especially the one for `InternalCompilerError`. Then [`formatError()` and related helpers](https://github.com/ethereum/solidity/blob/v0.8.14/libsolidity/interface/StandardCompiler.cpp#L56-L151). I suspect that the problem is somewhere in there. Try to modify the code locally so that the error handler always executes and see why it gets truncated. If it's not the right handler, look for others that might catch `InternalCompilerError`.

**Comment by axic** [comment]
I do not think there is any bug here, and certainly no truncation.

The original finding refers to 0.7.2 and `CompilerUtils.cpp#L1440`, which [is here](https://github.com/ethereum/solidity/blob/v0.7.2/libsolidity/codegen/CompilerUtils.cpp#L1440):
```cpp
	solAssert(_type.isValueType(), "");
```

The sole reason the message is empty, because it is empty in the code.

There was #1042 and #5160 about that.

**Comment by axic** [comment]
Re-reading @alcuadrado's original suggestion, I think the issue isn't about potentially having truncated `message`s, but that `formattedMessage` should also include the line number. Based on the code snippets in [StandardCompiler](https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/StandardCompiler.cpp#L1161) this applies to every single exception based error:
```cpp
		errors.append(formatErrorWithException(
			compilerStack,
			_exception,
			Error::Severity::Error,
			"InternalCompilerError",
			"general",
			"Internal compiler error (" + _exception.lineInfo() + ")"
		));
```

The problem is that for `formattedMessage` we take in "error type" and a message, however the exceptions also have a relevant line number. Probably can modify the special cases [here](https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/StandardCompiler.cpp#L126) and [here](https://github.com/ethereum/solidity/blob/develop/libsolidity/interface/StandardCompiler.cpp#L132).

**Comment by cameel** [comment]
I thought it was being truncated from something like this (taken from an unrelated issue):
```
Internal compiler error:
/solidity/libsolidity/ast/Types.cpp(2877): Throw in function solidity::frontend::TypePointers solidity::frontend::FunctionType::returnParameterTypesWithoutDynamicTypes() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```
Especially the trailing `\n` in the single-line message makes it look like it's just a fragment that came from a longer multiline piece of text.

But I think you're right. It's not technically truncated. It's just that the `formattedMessage` field only includes the error type and the message and the message used to be empty in most of our assertions. We implemented #12019 some time ago so now these are no longer empty. The default message is just as useless for debugging though (something like "Solidity assertion failed") so including either file/line or the function name would be an improvement.

**Comment by Ruko97** [comment]
Importing a library that uses ABI Encoder V2 in a file that doesn't use ABI Encoder V1 no longer seems to cause an Internal Compiler Error. Is there any other way to simulate an ICE?

**Comment by cameel** [comment]
You'll find lots of ways to cause an ICE under the [`bug` label](https://github.com/ethereum/solidity/issues?q=is%3Aissue+is%3Aopen+label%3A"bug+%3Abug%3A").
