### ISSUE TITLE
A very weird problem causing overflow for string!!!

### ISSUE THREAD

**Issue by jayateertha043** [ethereum/solidity#9949]
Please read entire problem here:
https://stackoverflow.com/questions/64174076/solidity-overflow-in-my-web3-code-but-works-in-oneclickdapp-final-year-project

**Comment by cameel** [comment]
This does not seem to be a problem in the compiler. You're getting an integer overflow error from `bignumber` library used by Truffle because the number is very big (looks like 512 bits) while it's probably expecting a 256-bit integer:
```
Error: overflow (fault="overflow", operation="toNumber", value="3963877391197344453575983046348115674221700746820753546331534351508065746944", code=NUMERIC_FAULT, version=bignumber/5.0.7)
```

All of this happens in JavaScript, not in Solidity. Honestly, I'm not sure where the number comes from, if I had to guess, I'd say that `this.state.account` might not really be an address and maybe truffle is trying to convert it for you and fails. It's hard to tell because your post only includes a small fragment of your JS code.

But anyway this bug tracker is not a good place to get answer to that. StackOverflow is a much better one. Please be a little patient, you only asked 3 hours ago :) I'm sure someone will chime in and help you debug this. If you don't get an answer try on our [Gitter channel](https://gitter.im/ethereum/solidity) where many experienced users of the language and related tools usually hang out.

I'm closing this but feel free to reopen if you find anything related to this that actually looks like a bug or missing feature in the compiler itself rather than in the JavaScript tooling or your own code.

**Comment by cameel** [comment]
Also, just a bit of advice regarding StackOverflow: you'll get more answers if you reduce your code to the simplest form possible that still causes the error. Right now you're asking anyone wanting to help to understand your project and reconstruct the code to deploy it which means that you'll only get answers from people motivated enough to do so, even if the project is very small (unless the cause is very obvious). A self-contained, minimal example without dependencies is much easier to analyze and more enticing.

**Comment by jayateertha043** [comment]
Hey,
I did verify that this.state.account return my current account as a string 
I am passing my address as a string to that function ,yes I too think truffle is converting my string address to bignumber ,

But problem is I have another function which also accepts parameter which is same this.state.account but is working fine .
