### ISSUE TITLE
block.timestamp not correct in view function

### ISSUE THREAD

**Issue by true-eye** [ethereum/solidity#9984]
## Description

```
function getBlockTimestamp() external view returns (uint256) {
        return block.timestamp;
}
```
In view functions, the `block.timestamp` is not the same as the real timestamp. It seems it returns the last timestamp which the contract was interacted or executed with non-view functions.

## Environment

- Compiler version: 0.6.2
- Target EVM version (as per compiler settings): 
- Framework/IDE (e.g. Truffle or Remix): Truffle
- EVM execution environment / backend / blockchain client: Ganache
- Operating system: MacOS

## Steps to Reproduce

```
function getBlockTimestamp() external view returns (uint256) {
        return block.timestamp;
}
```

Thanks in advance,

**Comment by cameel** [comment]
That's correct behavior. `block.timestamp` is the timestamp of the most recent block. On the actual blockchain the timestamp would be changing simply because there are new blocks being mined all the time but if you're checking it in a test environment running ganache, you're just seeing the timestamp from the last time you did something that involved creating a new transaction and adding a block. Calling a view function does not involve creating a transaction so there's no new block in that case.

**Comment by true-eye** [comment]
Thanks for your explanation. That fully makes sense.

Then for unit testing on a test environment, how can we handle this?
It seems that there is no solution, right?

**Comment by cameel** [comment]
You can use `evm_increaseTime` from Ganache for testing.

See for example https://ethereum.stackexchange.com/questions/67593/as-in-truffle-tests-pass-the-check-by-block-timestamp
