### ISSUE TITLE
Enable Enums to be Extended in Upgradeable Contracts

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#9986]
Currently an upgradable proxy contract or diamond can't extend an enum.

Please see this article for details: https://hackernoon.com/beware-the-solidity-enums-9v1qa31b2?source=rss

It would be great if enums could be extended to include additional values in upgradeable contracts.

I understand that if more than 256 values are used by an enum then it uses 16 bits instead of 8 bits.   This poses a danger for upgradable contracts that extend an enum to include more values. To solve this problem can the Solidity compiler enforce that an enum uses no more than 256 items?   Has anyone ever used an enum with more than 256 possible values?  It seems to me that 256 values is enough.

**Comment by chriseth** [comment]
Are these two different issues? I can totally see the benefit in restricting enums to 256 values.

About the upgradability - do you have any suggestions?

**Comment by mudgen** [comment]
Thanks for looking at this @chriseth!

Yes there are two issues here:
1. Limit enums to 256 possible values so the contract storage size is fixed at 8 bits. 
2. Allow enums to be extended by contract upgrades.

According to the article I linked to there is a runtime check that prevents using an enum outside its defined set of values.  Remove this check so that enums can be extended in contract upgrades.   I think this check should be a compile time check. 

I am not familiar with the implementation of Solidity so please consider and/or investigate any issues or problems that my suggestion might cause.

**Comment by cameel** [comment]
This was discussed on the meeting today - mostly regarding limiting the number of possible values. @chriseth suspects that enums occupying more than one byte might be so rare in practice that some tools might not even support them properly. An assumption that enum is always equivalent with `uint8` might be common.

The decision was to gather some feedback first and see if anyone is using enums with more than 256 values in practice.

**Comment by cameel** [comment]
I created a separate issue for adding the limit because we might want it even if in the end we decide not to implement extensible enums: #10035.

**Comment by cameel** [comment]
@mudgen As for the extensible enums, I think there are serious problems with enabling something like that.

Consider this example:
```solidity
enum Operation {Add, Delete}

contract C {
    function executeOperation(Operation _operation) public {
        if (_operation == Operation.Add) {
            // Add stuff
        }
        else {
            // Delete stuff
        }
    }
}
```
Now what happens if you extend the `enum` to `enum Operation {Add, Delete, Modify}`? `Modify` will delete stuff.

This is not a style I recommend (I wouldn't write it myself without adding `assert(_operation == Operation.Delete)` in the `else` branch) but I strongly suspect that this is what people often do. I've seen this pattern used a lot in other languages I worked in, even with types that do not have built-in checks like enums. In Solidity it's a bigger problem because the compiler currently guarantees the `assert` so people might feel justified in not adding it themselves and they would be completely right.

I think that removing the runtime enum check now has potential to break too many contracts. Code that was completely safe until now would suddenly become buggy. The worst thing is that there wouldn't be any warning about it so I think people in many cases wouldn't spot it until long after a new version of their contract, compiled using new Solidity version, had been deployed.

For the use case from the article I think that `uint8` with a set of pre-defined constants for values would be more appropriate than an enumeration anyway. Using an enum is misleading because it suggests that only values specified in the definition are allowed while really you want the contract to allow all of them. Some just have not been defined yet.

The only downside to using constants I can see is that you lose type safety. But this would not be a problem if we had user-defined type aliases so maybe we should work on that instead? We do have a feature request for it (#1100) and this would be another use case.

**Comment by mudgen** [comment]
@cameel Thanks for looking into this.  I see what you mean. Good points!  Good idea to use constants.

I think you are right. Best not to change how enums work concerning this, but provide another way.

How might it work and look if a user-defined type alias was used instead of an enum so it could be extended by upgrades?

**Comment by cameel** [comment]
With the syntax proposed in #1100 it could look like this:

```solidity
interface IStorage {    
    typedef uint8 RecordState;
    RecordState constant StateA = 0;
    RecordState constant StateB = 1;

    function setState(address user, RecordState newState) public;
}
```

Then extending it would not be a problem because defining constants does not limit `RecordState` in any way.

On a side note, when #2918 gets implemented you'd also be able to use an arbitrary range to have more control over how exensible the set of values should be. E.g. `typedef number{-1000, 1000} RecordState`.

**Comment by mudgen** [comment]
I see, cool! I like it.  Thanks.

**Comment by cameel** [comment]
Great :) In that case I'm going to close this one. I put the issue with user-defined type aliases at the top of design backlog to get some discussion about it. We have a long backlog of feature requests so not sure when exactly we'll get to this one (we actually discussed that today; we really need to focus more on the Sol->Yul codegen) but having a good use case and clear spec should help move it forward.

**Comment by mudgen** [comment]
Sounds good, thanks.

**Comment by jalextowle** [comment]
@cameel I found your conversation with @mudgen on this topic to be interesting. I'd like to offer a slightly different perspective that I acquired this week while writing a new set of contracts. I may be missing something that makes my proposal undesirable, and this feature may be too niche to warrant support. If that is the case, I'd appreciate a comment explaining what the problem in this solution is, but I'll support your decision.

# Problem

I'm currently working with a set of contracts that need to return instead of reverting so that a nonce can be updated in either case. I've started to use a pattern where I define a set of exit codes as an enum so that I can still provide relatively rich error messages without incurring a large cost. Some of the logic was generic enough to be abstracted into a library, but these library functions also needed to adopt the exit code convention instead of reverting. 

This brings us to the point where extensible enums would be nice. The main contract uses a superset of the exit codes used in the library contract since I want to faithfully return the exit codes resulting from the library calls (for the purposes of this system, each library call is only made once in context, so this is really all you need to see where execution failed).  What I can do for now is copy an enum defined within the library into the main contract so that the lower values are the same. This would allow me to cast the enum like this:

```
Lib.ExitCode libExitCode = Lib.bar();
ExitCode exitCode = ExitCode(uint8(libExitCode));
if (exitCode != ExitCode.Success) {
    return exitCode;
}
```

so that I don't need to use a set of if-statements to correctly decode the exit code and encode it to the correct analogue for the main contract. This scares me since any change to the enums in one file could change the semantics of this call, so I'll probably stick with the set of if-statements.

# Proposal

It would be nice if the Solidity compiler could provide good enough type-checking to protect me from the maintenance headache described above. I think something like the following would be great: 

```
library Lib {
    enum ExitCode {
        Success,
        SomeLibError
    }
    
    function foo() internal pure returns (ExitCode) {
        // Do some stuff and potentially return ExitCode.Success or ExitCode.SomeLibError
    }
}
```

and then extend this in the main contract:

```
import { Lib } from "./Lib.sol";

contract Main {
    enum ExitCode extends Lib.ExitCode {
        SomeMainError
    }

    function foo() external returns (ExitCode) {
        // This is a safe cast since ExitCode extends Lib.ExitCode
        ExitCode exitCode = Lib.bar();

        if (exitCode != ExitCode.Success) {
            return exitCode;
        }

        // Do some more stuff
        
        return exitCode.Success;
    }
}
```

This basically just shows `Main.ExitCode` extending `Lib.ExitCode`. What I would want is for `Main.ExitCode` to be equivalent to:

```
enum ExitCode {
    Success,
    SomeLibError,
    SomeMainError
}
```

To fix the issue that you pointed out to @mudgen, you could represent `Lib.ExitCode` and `Main.ExitCode` as distinct types within the compiler so that `Lib.ExitCode` only contains `Success` and `SomeLibError` (I don't really know the correct way to phrase this within the context of `solc`, but hopefully you get the gist of this idea). This would prevent someone from passing in an enum (like `SomeMainError`) that would break the semantics of the else. 

Note: It would only make sense to allow an enum to extend one other enums, since multiple extensions wouldn't play nicely with each other.

**Comment by mudgen** [comment]
@chriseth Any plans to make extensible enums?

**Comment by mudgen** [comment]
@chriseth @cameel Currently is there any way or alternative for upgrading enums?
