### ISSUE TITLE
How do I return paged map or list?

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum/solidity#9997]
Suppose there is a large map or list, is there a way to return them in pages? This is useful in cases like query all NFT tokens under an address.

**Comment by cameel** [comment]
Why do you think that would be useful? If you have a public storage variable that is a list or a mapping then the compiler generates a public getter function that lets you access the elements one at a time. But the function is `view` so querying it does not require a blockchain transaction. You can just ask your local blockchain client for all the values one by one. If you want to display them paginated, that's not a Solidity concern - you implement that separately in your UI code (not written in Solidity).

Also please note that you can't really enumerate all values from a mapping without knowing the keys so it's not possible for a getter to return them all or a even a subset. You have to store the keys separately (or know how to generate them) and write a custom function that uses that information to iterate over the mapping.

If you mean paginating an array or a mapping returned by an external function then (1) you can't really return a mapping from such a function, (2) if a function returns an array then it's the function that decides what the array contains. If you write a function that returns array values in batches then you get pagination but that's on you. If the function by design returns the whole array you can't just request a part of it. I mean, you can ignore part of the array but you still have to get it first and then trim it - which means paying the gas cost for the whole array anyway if you're doing it from another contract. And if that's not from a contract then again, that's not a Solidity concern.

Anyway, this is a bug tracker meant for bugs and feature requests. Questions like this are better discussed on the [solidity](https://gitter.im/ethereum/solidity) gitter channel or on [Ethereum StackExchange](https://ethereum.stackexchange.com/). If this is actually a feature request feel free to reopen but please describe it in enough detail that it's clear what you're actually requesting.
